### DISCUSSION TITLE
how to configure multiple IMAP/SMTP domain adresses ?

### DISCUSSION THREAD

**Discussion by estebanlm** [docker-mailserver/docker-mailserver#2596] [Q&A] [answered]
Hello, 
I am sorry if this is not the right place, but I have been lurking around without finding any answer... 

I have docker-mailserver behind a reverse proxy, configured with a virtual host and a secondary domain, let's say `mail.virtualhostdomain.com`and `mail.secondarydomain.com`. 
Each domain has a couple of email addresses.
Now, my problem is when configuring IMAP/SMTP client. If I use `mail.virtualhostdomain.com` it works properly for addresses in that domain AND in addresses in the secondary domain... but if I use `mail.secondarydomain.com` to configure a client for `someaddress@secondarydomain.com`, the IMAP/SMTP server is not recognized (not reachable, it says).

This is my docker compose config: 

```Yaml
version: "3.3"

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail
    domainname: domain.com
    # env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - ./docker-data/certbot/certs/:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    stop_grace_period: 1m
    environment:
      - SSL_TYPE=letsencrypt
      - VIRTUAL_HOST=mail.domain.com
      - LETSENCRYPT_HOST=mail.domain.com
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ENABLE_SASLAUTHD=0
      - ONE_DIR=1
      - DOMAINS=mail.secondary.com
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    networks:
      - server

  nginx-proxy-lorenzano:
    image: nginx
    container_name: nginx-proxy-secondary
    environment:
      - VIRTUAL_HOST=mail.secondary.com
      - LETSENCRYPT_HOST=mail.secondary.com
    networks:
      - server

networks:
    server:
        external: true
```

Any help is welcome :)
