### DISCUSSION TITLE
Connecting to the mailserver within a k8s cluster, is it possible?

### DISCUSSION THREAD

**Discussion by winston0410** [docker-mailserver/docker-mailserver#2795] [Q&A]
I am trying to connect the mailserver with services within the cluster, but I cannot figure out how to use `smtps` for the transport. I have encountered the following blockers with my attempts:

1. Generate a cert with Let's Encrypt, using cert-manager

With this approach I have used `manual` for `SSL_TYPE`, and tried to provided a certificate like this:

```yaml
---
apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: mail-tls-certificate-rsa
  namespace: mailserver

spec:
  secretName: mail-tls-certificate-rsa
  dnsNames:
    - mailserver-service.mailserver.svc.cluster.local
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
```
The trouble is, I cannot use the domain name inside the cluster here, as the domain name is not an accepted FQDN.

```sh
The certificate request has failed to complete and will be retried: Failed to wait for order resource "mail-tls-certificate-rsa-9rq87-1466730672" to become ready: order is in "errored" state: Failed to create Order: 400 urn:ietf:params:acme:error:rejectedIdentifier: Error creating new order :: Cannot issue for "mailserver-service.mailserver.svc.cluster.local": Domain name does not end with a valid public suffix (TLD)
```

2. Use Service Mesh and mTLS to deal with TLS issue

I have set up linkerd in my cluster, and I tried to use it to deal with the TLS issue, but I have no clue how to do it yet...

It would be great if someone can shed some light on how to accomplish this.
