### DISCUSSION TITLE
postfix/postfix-script: warning: not owned by root: /var/spool/postfix/.

### DISCUSSION THREAD

**Discussion by winston0410** [docker-mailserver/docker-mailserver#2846] [Q&A]
Not sure if this is a bug, I notice a lot of warning like this in my mailserver. I run it in K8S:

```sh
Oct 17 22:39:16 mail postfix/postdrop[5901]: warning: mail_queue_enter: create file maildrop/988304.5901: Permission denied
```

And I tried to debug it:

```sh
# postfix check 
postfix/postfix-script: warning: not owned by root: /var/spool/postfix/.
# ls -al /var/spool/postfix
lrwxrwxrwx 1 root root 29 Oct 21 08:49 /var/spool/postfix -> /var/mail-state/spool-postfix
# ls -al /var/spool/postfix/.
total 0
drwxr-xr-x 20 postfix root     400 Oct 21 08:49 .
drwxrwxrwt  7 root    root     140 Oct 21 08:49 ..
drwx------  2 postfix root      40 Oct 21 08:50 active
drwx------  2 postfix root      40 Sep 23 00:36 bounce
drwx------  2 postfix root      40 Sep 23 00:36 corrupt
drwx------  2 postfix root      40 Sep 23 00:36 defer
drwx------  2 postfix root      40 Sep 23 00:36 deferred
drwxr-xr-x  2 root    root     100 Oct 21 08:49 dev
drwxr-xr-x  3 root    root     180 Oct 21 08:49 etc
drwx------  2 postfix root      40 Sep 23 00:36 flush
drwx------  2 postfix root      40 Oct 21 08:49 hold
drwx------  2 postfix root      40 Oct 21 08:49 incoming
drwxr-xr-x  3 root    root      60 Oct 21 08:49 lib
drwx-wx--T  2 postfix postdrop  40 Oct 21 08:49 maildrop
drwxr-xr-x  2 root    root     100 Oct 21 08:49 pid
drwx------  2 postfix root     520 Oct 21 08:49 private
drwx--x---  2 postfix postdrop 160 Oct 21 08:49 public
drwx------  2 postfix root      40 Sep 23 00:36 saved
drwx------  2 postfix root      40 Oct 21 08:49 trace
drwxr-xr-x  3 root    root      60 Sep 23 00:36 usr
```
I am able to make `postfix check` pass by running `chown root /var/spool/postfix/.` I am going to observe and see if I get that log in the upcoming days.

This is my configuration:

```yaml
# For internal traffic, use smtp://mailserver-service.mailserver
---
apiVersion: v1
kind: Namespace
metadata:
  name: mailserver
  annotations:
    linkerd.io/inject: disabled
---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: data
  namespace: mailserver

spec:
  storageClassName: "oci-bv"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service

metadata:
  name: mailserver-service
  namespace: mailserver
  labels:
    app: mailserver

spec:
  type: ClusterIP

  selector:
    app: mailserver

  ports:
    - name: msa
      port: 587
      targetPort: 587
      protocol: TCP
    - name: imap
      port: 143
      targetPort: 143
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: mailserver
  namespace: mailserver

  annotations:
    ignore-check.kube-linter.io/run-as-non-root: >-
      'mailserver' needs to run as root
    ignore-check.kube-linter.io/privileged-ports: >-
      'mailserver' needs privilegdes ports
    ignore-check.kube-linter.io/no-read-only-root-fs: >-
      There are too many files written to make The
      root FS read-only

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailserver

  template:
    metadata:
      labels:
        app: mailserver

      annotations:
        # FIXME Need to enable apparmor in host first
        # container.apparmor.security.beta.kubernetes.io/mailserver: runtime/default

    spec:
      # REF https://docker-mailserver.github.io/docker-mailserver/edge/config/troubleshooting/debugging/#enable-verbose-debugging-output
      hostname: mail
      initContainers:
        - name: prep-config
          image: docker.io/mailserver/docker-mailserver:11.1.0@sha256:c55f48f69fb620c636b10ce5555cf4f4e97816205b439d75129e808182a76228
          command: [
              "sh",
              "-c",
              "mkdir -p /tmp/docker-mailserver;
              setup email add root@jyut.info $K8S_MAILSERVER_PWD;
              setup email add noreply@jyut.info $K8S_MAILSERVER_PWD;
              setup config dkim;"
            ]
          volumeMounts:
            - name: tmp-files
              mountPath: /tmp
              readOnly: false
            - name: data
              mountPath: /var/mail-state
              subPath: state
              readOnly: false
          env:
            - name: K8S_MAILSERVER_PWD
              valueFrom:
                secretKeyRef:
                  name: mailserver-secret
                  key: K8S_MAILSERVER_PWD
      containers:
        - name: mailserver
          image: docker.io/mailserver/docker-mailserver:edge@sha256:a78c0134351729a4edf6657759b62d4c5e129ed6eb69f059a1e7811936d75439
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            privileged: false
            capabilities:
              add:
                # file permission capabilities
                - CHOWN
                - FOWNER
                - MKNOD
                - SETGID
                - SETUID
                - DAC_OVERRIDE
                # network capabilities
                - NET_ADMIN # needed for F2B
                - NET_RAW # needed for F2B
                - NET_BIND_SERVICE
                # miscellaneous  capabilities
                - SYS_CHROOT
                - KILL
              drop: [ALL]
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              memory: 1Gi
              cpu: 300m

          volumeMounts:
            # PVCs
            - name: data
              mountPath: /var/mail
              subPath: data
              readOnly: false
            - name: data
              mountPath: /var/mail-state
              subPath: state
              readOnly: false
            - name: data
              mountPath: /var/log/mail
              subPath: log
              readOnly: false

            # certificates
            - name: certificates-rsa
              mountPath: /secrets/ssl/rsa/
              readOnly: true

            # other
            - name: tmp-files
              mountPath: /tmp
              readOnly: false

            # override postfix main config
            - name: files
              subPath: postfix-main.cf
              mountPath: /tmp/docker-mailserver/postfix-main.cf
              readOnly: true

            # override postfix master config
            - name: files
              subPath: postfix-master.cf
              mountPath: /tmp/docker-mailserver/postfix-master.cf
              readOnly: true
          ports:
            - name: msa
              containerPort: 587
              protocol: TCP
            - name: imap
              containerPort: 143
              protocol: TCP

          envFrom:
            - configMapRef:
                name: mailserver.environment

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 5

          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - supervisorctl status | grep -E "mailserver|postfix" | grep RUNNING
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 1
            failureThreshold: 3

      restartPolicy: Always

      volumes:
        # configuration files
        - name: files
          configMap:
            name: mailserver.files

        # PVCs
        - name: data
          persistentVolumeClaim:
            claimName: data

        # certificates
        - name: certificates-rsa
          secret:
            secretName: mail-tls-certificate-rsa
            items:
              - key: tls.key
                path: tls.key
              - key: tls.crt
                path: tls.crt

        # other
        - name: tmp-files
          emptyDir: {}
```
