### DISCUSSION TITLE
Cannot send email from other container of the same network

### DISCUSSION THREAD

**Discussion by graille** [docker-mailserver/docker-mailserver#2914] [Q&A]
Hello everyone,

Using [this tutorial](https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/mailserver-behind-proxy/), I deployed docker-mailserver behind my Traefik reverse proxy. Everything is fine and I can now send and receive email directly from Thunderbird.

HOWEVER, I have a Passbolt instance on my server, on the same docker network than the mailserver, I configured it like this :

```yaml
    passbolt:
        # Documentation: https://github.com/passbolt/passbolt_docker
        container_name: passbolt
        image: passbolt/passbolt:latest-ce
        restart: unless-stopped
        environment:
             # Email configuration
            EMAIL_TRANSPORT_DEFAULT_CLASS_NAME: "Smtp"
            EMAIL_DEFAULT_FROM: "contact@mydomain.com"
            EMAIL_TRANSPORT_DEFAULT_HOST: "mailserver"
            EMAIL_TRANSPORT_DEFAULT_PORT: "465"
            EMAIL_TRANSPORT_DEFAULT_USERNAME: "contact@mydomain.com"
            EMAIL_TRANSPORT_DEFAULT_PASSWORD: "${EMAIL_SMTP_SERVER_PASSWORD}"
            EMAIL_TRANSPORT_DEFAULT_TLS: "true"
            # ....
```

With this configuration, I am unable to send any email when launching passbolt. 
This is the logs  of the mailserver when trying to send an email, which show that it is receiving the request, but I don't know why is it closing it:

```
Dec  1 00:18:48 mail postfix/smtps/smtpd[2270]: warning: haproxy read: timeout error
Dec  1 00:18:48 mail postfix/smtps/smtpd[2270]: connect from passbolt.reverse_proxy[172.18.0.5]
Dec  1 00:18:48 mail postfix/smtps/smtpd[2270]: disconnect from passbolt.reverse_proxy[172.18.0.5] commands=0/0
```

Any idea ?
