### DISCUSSION TITLE
Best practice for changing the mailserver domain

### DISCUSSION THREAD

**Discussion by jayknyn** [docker-mailserver/docker-mailserver#3107] [Q&A] [answered]
Hi, I would like some feedback from the community on this situation:
- I've been running DMS on mail.domain1.com for about 2 years and have no issues with sending or receiving mail (good IP reputation)
- I would like to change the mailserver domain to mail.domain2.com (for branding purposes) and keep it at the existing IP
- What is the best practice for going about this change?
- My plan is to update the config (compose and .env), get SSL cert for mail.domain2.com, create new DKIM keys, create DNS records for the new domain, create PTR record for the new domain, and update the MX records of all the other domains that I have in DMS
- anything else?

Current relevant parts of compose file:
```
services:
  mailserver:
    domainname: domain1.com
    environment:
      OVERRIDE_HOSTNAME: mail.domain1.com
```
