### DISCUSSION TITLE
Container cannot launch because Dovecot is stuck

### DISCUSSION THREAD

**Discussion by MarcS1975** [docker-mailserver/docker-mailserver#3194] [Q&A]
I have downloaded the docker container via portainer stack but Dovecot always gets stuck. What shall I do?

```
[   INF   ]  Welcome to docker-mailserver 11.3.0
[   INF   ]  Initializing setup
[   INF   ]  Checking configuration
[   INF   ]  Configuring mail server
[ WARNING ]  You need at least one mail account to start Dovecot (120s left for account creation before shutdown)
[ WARNING ]  You need at least one mail account to start Dovecot (110s left for account creation before shutdown)

```

this is my stack
```
`services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.abcd.com
    ports:
      - "28:25"
      - "590:587"
      - "996:993"
    volumes:
    - /srv/dev-disk-by-uuid-14a35ebc-6358-492c-af84-4e920f0c55bc/Docker/volumes/ajmail/mail-data/:/var/mail/
    - /srv/dev-disk-by-uuid-14a35ebc-6358-492c-af84-4e920f0c55bc/Docker/volumes/ajmail/data/mail-state/:/var/mail-state/
    - /srv/dev-disk-by-uuid-14a35ebc-6358-492c-af84-4e920f0c55bc/Docker/volumes/ajmail/data/mail-logs/:/var/log/mail/
    - /srv/dev-disk-by-uuid-14a35ebc-6358-492c-af84-4e920f0c55bc/Docker/volumes/ajmail/data/config/:/tmp/docker-mailserver/
    - /etc/localtime/:/etc/localtime:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
    restart: always
  #  stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
  #  healthcheck:
  #    test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
  #    timeout: 3s
  #    retries: 0`
```
