### DISCUSSION TITLE
Shared Mailboxes

### DISCUSSION THREAD

**Discussion by peracchi** [docker-mailserver/docker-mailserver#3279] [Q&A]
Hey guys!

I googled a lot and didn't find any guides/tutorials on how to set up a mail server using shared mailboxes.

Distribution lists are relatively easy to set up but have, in my understanding, two major problems:
- wasted storage when copying an email to all group members' mailboxes
- when a group member replies to an email, the others do not know or have access to the reply

Let's assume the following scenario:
- Docker Mailserver (obviously)
- an LDAP container
- a domain **"mydomain.net"**
- five users: alice, bob, charlie, dave and erin
- three _"users"_ that would be the shared mailboxes: _"announcements"_, _"sales"_ and _"support"_
- three groups that indicate who has access to shared mailboxes: **"announcements"** (everyone is a member of this group), **"sales"** (alice, charlie and erin are members of this group) and **"support"** (bob and dave are members of this group group)

I assume the structure on the filesystem would be as follows:
```
./mail-data/shared/announcements
./mail-data/shared/sales
./mail-data/shared/support
./mail-data/users/alice
./mail-data/users/bob
./mail-data/users/charlie
./mail-data/users/dave
./mail-data/users/erin
```

In this way, any email sent to user addresses
```
alice@mydomain.net
bob@mydomain.net
charlie@mydomain.net
dave@mydomain.net
erin@mydomain.net
```
or shared email addresses
```
announcements@mydomain.net
sales@mydomain.net
support@mydomain.net
```
is only saved once, in only one of the folders below `./mail-data/`.

Members of shared mailboxes can read all emails sent to them and when replying to emails will use the shared mailbox address as the sender. It is important that responses to emails remain in the shared mailbox so that other group members can know that a response has already been sent and also read its contents.

Below are the files needed to create the base environment in which the configuration of shared mailboxes will be done.

`docker-compose.yml` for LDAP container:
```
version: "3.9"
services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    hostname: ldap
    restart: unless-stopped
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - config:/etc/ldap/slapd.d
      - data:/var/lib/ldap
      # I use Caddy to obtain a valid certificate from Let's Encrypt
      - /var/lib/docker/volumes/caddy_data/_data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/ldap.mydomain.net:/container/service/slapd/assets/certs
    environment:
      LDAP_LOG_LEVEL: 256
      LDAP_ORGANISATION: MyDomain Net
      LDAP_DOMAIN: mydomain.net
      LDAP_BASE_DN: 
      LDAP_ADMIN_PASSWORD: password
      LDAP_CONFIG_PASSWORD: password
      LDAP_READONLY_USER: false
      #LDAP_READONLY_USER_USERNAME: readonly
      #LDAP_READONLY_USER_PASSWORD: readonly
      LDAP_RFC2307BIS_SCHEMA: true
      LDAP_BACKEND: mdb
      LDAP_TLS: true
      LDAP_TLS_CRT_FILENAME: ldap.mydomain.net.crt
      LDAP_TLS_KEY_FILENAME: ldap.mydomain.net.key
      LDAP_TLS_CA_CRT_FILENAME: ldap.mydomain.net.crt
      #LDAP_TLS_DH_PARAM_FILENAME: dhparam.pem
      LDAP_TLS_ENFORCE: false
      LDAP_TLS_CIPHER_SUITE: NORMAL:SECURE256:-VERS-SSL3.0
      LDAP_TLS_VERIFY_CLIENT: try
      LDAP_REPLICATION: false
      KEEP_EXISTING_CONFIG: false
      LDAP_REMOVE_CONFIG_AFTER_SETUP: true
      LDAP_SSL_HELPER_PREFIX: ldap
      LDAP_OPENLDAP_UID: 0
      LDAP_OPENLDAP_GID: 0
    tty: true
    stdin_open: true
    domainname: mydomain.net
volumes:
  config:
  data:
```

`docker-compose.yml` for Docker Mailserver container:
```
version: "3.9"
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:12.0.0
    container_name: mydomain-dms
    hostname: mydomain-mail
    domainname: mydomain.net
    ports:
      - "25:25"     # SMTP  (explicit TLS => STARTTLS)
      - "143:143"   # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"   # ESMTP (implicit TLS)
      - "587:587"   # ESMTP (explicit TLS => STARTTLS)
      - "993:993"   # IMAP4 (implicit TLS)
      - "4190:4190" # Managesieve
    volumes:
      - $PWD/config/:/tmp/docker-mailserver/
      - $PWD/mail-data/:/var/mail/
      - $PWD/mail-logs/:/var/log/mail/
      - $PWD/mail-state/:/var/mail-state/
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/volumes/caddy_data/_data/caddy/certificates/acme-v02.api.letsencrypt.org-directory:/tmp/dms/custom-certs/:ro
    environment:
      - OVERRIDE_HOSTNAME=mail.mydomain.net
      - LOG_LEVEL=info
      - ACCOUNT_PROVISIONER=LDAP
      - TZ=America/Sao_Paulo
      - SPOOF_PROTECTION=1
      - ENABLE_POLICYD_SPF=0
      - ENABLE_CLAMAV=1
      - ENABLE_RSPAMD=1
      - RSPAMD_LEARN=1
      - RSPAMD_GREYLISTING=1
      - ENABLE_DNSBL=1
      - ENABLE_FAIL2BAN=1
      - FAIL2BAN_BLOCKTYPE=drop
      - ENABLE_MANAGESIEVE=1
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/tmp/dms/custom-certs/mail.mydomain.net/mail.mydomain.net.crt
      - SSL_KEY_PATH=/tmp/dms/custom-certs/mail.mydomain.net/mail.mydomain.net.key
      - POSTFIX_MAILBOX_SIZE_LIMIT=1073741824
      - POSTFIX_MESSAGE_SIZE_LIMIT=52428800
      - PFLOGSUMM_TRIGGER=logrotate
      - LOGWATCH_INTERVAL=weekly
      - REPORT_SENDER=no-reply@mydomain.net
      - LOGROTATE_INTERVAL=monthly
      - POSTFIX_INET_PROTOCOLS=ipv4
      - DOVECOT_INET_PROTOCOLS=ipv4
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_SPAMASSASSIN_KAM=1
      - MOVE_SPAM_TO_JUNK=1
      - ENABLE_POSTGREY=1
      - LDAP_START_TLS=yes
      - LDAP_SERVER_HOST=ldap
      - LDAP_SEARCH_BASE=dc=mydomain,dc=net
      - LDAP_BIND_DN=cn=admin,dc=mydomain,dc=net
      - LDAP_BIND_PW=password
      - LDAP_QUERY_FILTER_DOMAIN=(mail=*@%s)
      - LDAP_QUERY_FILTER_USER=(&(mail=%s)(mailEnabled=TRUE))
      - LDAP_QUERY_FILTER_ALIAS=(&(mailAlias=%s)(mailEnabled=TRUE))
      - LDAP_QUERY_FILTER_GROUP=(&(objectclass=groupOfUniqueNames)(cn=%s))
      - LDAP_QUERY_FILTER_SENDERS=(|(mail=%s)(mailAlias=%s)(mail=admin@*))
      - DOVECOT_USER_FILTER=(&(objectClass=PostfixBookMailAccount)(mail=%u)(mailEnabled=TRUE))
      - DOVECOT_PASS_FILTER=(&(objectClass=PostfixBookMailAccount)(mail=%u)(mailEnabled=TRUE))
      - DOVECOT_AUTH_BIND=yes
      - ENABLE_SASLAUTHD=1
      - SASLAUTHD_MECHANISMS=ldap
      - SASLAUTHD_LDAP_SERVER=ldap
      - SASLAUTHD_LDAP_BIND_DN=cn=admin,dc=mydomain,dc=net
      - SASLAUTHD_LDAP_PASSWORD=password
      - SASLAUTHD_LDAP_SEARCH_BASE=dc=mydomain,dc=net
      - SASLAUTHD_LDAP_FILTER=(&(objectClass=PostfixBookMailAccount)(mail=%u@%r)(mailEnabled=TRUE))
    cap_add:
      - NET_ADMIN
    restart: always
```

LDIF file/content to populate LDAP:
```
# Create organizational unit for Users

dn: ou=users,dc=mydomain,dc=net
ou: users
objectClass: organizationalUnit
objectClass: top

# Create User Accounts

dn: uid=alice,ou=users,dc=mydomain,dc=net
uid: alice
userPassword: {SSHA}+fyY+IoSc163VYMz1J+z6tTMnNlTIKG1
sn: alice
cn: alice
mail: alice@mydomain.net
mailEnabled: TRUE
mailUidNumber: 5000
mailGidNumber: 5000
mailHomeDirectory: /var/mail/mydomain.net/users/alice/
mailStorageDirectory: maildir:/var/mail/mydomain.net/users/alice/
objectClass: PostfixBookMailAccount
objectClass: inetOrgPerson
objectClass: organizationalPerson
objectClass: person
objectClass: top

dn: uid=bob,ou=users,dc=mydomain,dc=net
uid: bob
userPassword: {SSHA}+fyY+IoSc163VYMz1J+z6tTMnNlTIKG1
sn: bob
cn: bob
mail: bob@mydomain.net
mailEnabled: TRUE
mailUidNumber: 5000
mailGidNumber: 5000
mailHomeDirectory: /var/mail/mydomain.net/users/bob/
mailStorageDirectory: maildir:/var/mail/mydomain.net/users/bob/
objectClass: PostfixBookMailAccount
objectClass: inetOrgPerson
objectClass: organizationalPerson
objectClass: person
objectClass: top

dn: uid=charlie,ou=users,dc=mydomain,dc=net
uid: charlie
userPassword: {SSHA}+fyY+IoSc163VYMz1J+z6tTMnNlTIKG1
sn: charlie
cn: charlie
mail: charlie@mydomain.net
mailEnabled: TRUE
mailUidNumber: 5000
mailGidNumber: 5000
mailHomeDirectory: /var/mail/mydomain.net/users/charlie/
mailStorageDirectory: maildir:/var/mail/mydomain.net/users/charlie/
objectClass: PostfixBookMailAccount
objectClass: inetOrgPerson
objectClass: organizationalPerson
objectClass: person
objectClass: top

dn: uid=dave,ou=users,dc=mydomain,dc=net
uid: dave
userPassword: {SSHA}+fyY+IoSc163VYMz1J+z6tTMnNlTIKG1
sn: dave
cn: dave
mail: dave@mydomain.net
mailEnabled: TRUE
mailUidNumber: 5000
mailGidNumber: 5000
mailHomeDirectory: /var/mail/mydomain.net/users/dave/
mailStorageDirectory: maildir:/var/mail/mydomain.net/users/dave/
objectClass: PostfixBookMailAccount
objectClass: inetOrgPerson
objectClass: organizationalPerson
objectClass: person
objectClass: top

dn: uid=erin,ou=users,dc=mydomain,dc=net
uid: erin
userPassword: {SSHA}+fyY+IoSc163VYMz1J+z6tTMnNlTIKG1
sn: erin
cn: erin
mail: erin@mydomain.net
mailEnabled: TRUE
mailUidNumber: 5000
mailGidNumber: 5000
mailHomeDirectory: /var/mail/mydomain.net/users/erin/
mailStorageDirectory: maildir:/var/mail/mydomain.net/users/erin/
objectClass: PostfixBookMailAccount
objectClass: inetOrgPerson
objectClass: organizationalPerson
objectClass: person
objectClass: top

################################################################################

# Create organizational unit for Shared Mailboxes

dn: ou=shared,dc=mydomain,dc=net
ou: shared
objectClass: organizationalUnit
objectClass: top

# Create Shared Mailboxes

dn: uid=announcements,ou=shared,dc=mydomain,dc=net
uid: announcements
userPassword: {SSHA}+fyY+IoSc163VYMz1J+z6tTMnNlTIKG1
sn: announcements
cn: announcements
mail: announcements@mydomain.net
mailEnabled: TRUE
mailUidNumber: 5000
mailGidNumber: 5000
mailHomeDirectory: /var/mail/mydomain.net/shared/announcements/
mailStorageDirectory: maildir:/var/mail/mydomain.net/shared/announcements/
objectClass: PostfixBookMailAccount
objectClass: inetOrgPerson
objectClass: organizationalPerson
objectClass: person
objectClass: top

dn: uid=sales,ou=shared,dc=mydomain,dc=net
uid: sales
userPassword: {SSHA}+fyY+IoSc163VYMz1J+z6tTMnNlTIKG1
sn: sales
cn: sales
mail: sales@mydomain.net
mailEnabled: TRUE
mailUidNumber: 5000
mailGidNumber: 5000
mailHomeDirectory: /var/mail/mydomain.net/shared/sales/
mailStorageDirectory: maildir:/var/mail/mydomain.net/shared/sales/
objectClass: PostfixBookMailAccount
objectClass: inetOrgPerson
objectClass: organizationalPerson
objectClass: person
objectClass: top

dn: uid=support,ou=shared,dc=mydomain,dc=net
uid: support
userPassword: {SSHA}+fyY+IoSc163VYMz1J+z6tTMnNlTIKG1
sn: support
cn: support
mail: support@mydomain.net
mailEnabled: TRUE
mailUidNumber: 5000
mailGidNumber: 5000
mailHomeDirectory: /var/mail/mydomain.net/shared/support/
mailStorageDirectory: maildir:/var/mail/mydomain.net/shared/support/
objectClass: PostfixBookMailAccount
objectClass: inetOrgPerson
objectClass: organizationalPerson
objectClass: person
objectClass: top

################################################################################

# Create organizational unit for Groups

dn: ou=groups,dc=mydomain,dc=net
ou: groups
objectClass: organizationalUnit
objectClass: top

# Create Groups

dn: cn=announcements,ou=groups,dc=mydomain,dc=net
cn: announcements
uniqueMember: uid=alice,ou=users,dc=mydomain,dc=net
uniqueMember: uid=bob,ou=users,dc=mydomain,dc=net
uniqueMember: uid=charlie,ou=users,dc=mydomain,dc=net
uniqueMember: uid=dave,ou=users,dc=mydomain,dc=net
uniqueMember: uid=erin,ou=users,dc=mydomain,dc=net
objectClass: groupOfUniqueNames
objectClass: top

dn: cn=sales,ou=groups,dc=mydomain,dc=net
cn: sales
uniqueMember: uid=alice,ou=users,dc=mydomain,dc=net
uniqueMember: uid=charlie,ou=users,dc=mydomain,dc=net
uniqueMember: uid=erin,ou=users,dc=mydomain,dc=net
objectClass: groupOfUniqueNames
objectClass: top

dn: cn=support,ou=groups,dc=mydomain,dc=net
cn: support
uniqueMember: uid=bob,ou=users,dc=mydomain,dc=net
uniqueMember: uid=dave,ou=users,dc=mydomain,dc=net
objectClass: groupOfUniqueNames
objectClass: top
```
