### DISCUSSION TITLE
Host did not advertise authentication

### DISCUSSION THREAD

**Discussion by thi-baut** [docker-mailserver/docker-mailserver#3564] [Q&A] [answered]
Hi, I'm trying to configure an SMTP server so that a printer on my LAN can send documents by email. SMTP server does not need to be publicly accessible. 

Steps I followed:
1. Start container using docker-compose file below - pointed to existing Let's encrypt wildcard cert
2. Created the user xerox@domain.com
3. Registered A record and MX record as explained in instructions (not sure I need this for a private SMTP server though)

I checked 

The error I can see in the logs (when trying from the printer or using swaks) are : 

```
swaks -server mail.domain.com:587 -tls --auth-user "xerox@domain.com" --auth-password "password" --to test-email@gmail.com --from xerox@domain.com

=== Trying mail.domain.com:587...
=== Connected to mail.domain.com.
<-  220 mail.domain.com ESMTP
 -> EHLO Raven
<-  250-mail.domain.com
<-  250-PIPELINING
<-  250-SIZE 10240000
<-  250-ETRN
<-  250-STARTTLS
<-  250-ENHANCEDSTATUSCODES
<-  250-8BITMIME
<-  250-DSN
<-  250 CHUNKING
 -> STARTTLS
<-  220 2.0.0 Ready to start TLS
=== TLS started with cipher TLSv1.3:TLS_AES_256_GCM_SHA384:256
=== TLS no local certificate set
=== TLS peer DN="/CN=domain.com"
 ~> EHLO Raven
<~  250-mail.domain.com
<~  250-PIPELINING
<~  250-SIZE 10240000
<~  250-ETRN
<~  250-ENHANCEDSTATUSCODES
<~  250-8BITMIME
<~  250-DSN
<~  250 CHUNKING
*** Host did not advertise authentication
 ~> QUIT
<~  221 2.0.0 Bye
=== Connection closed with remote host.
```

Container logs (testing using swaks on the server) :

```
Oct  2 21:08:13 mail postfix/postscreen[3975]: CONNECT from [127.0.0.1]:42154 to [127.0.0.1]:25
Oct  2 21:08:13 mail postfix/postscreen[3975]: PASS OLD [127.0.0.1]:42154
Oct  2 21:08:13 mail postfix/smtpd[3976]: connect from localhost[127.0.0.1]
Oct  2 21:08:13 mail opendmarc[364]: ignoring connection from localhost
Oct  2 21:08:13 mail opendmarc[364]: ignoring connection from localhost
Oct  2 21:08:13 mail postfix/smtpd[3976]: Anonymous TLS connection established from localhost[127.0.0.1]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (2048 bits) server-digest SHA256
Oct  2 21:08:13 mail postfix/smtpd[3976]: lost connection after STARTTLS from localhost[127.0.0.1]
Oct  2 21:08:13 mail postfix/smtpd[3976]: disconnect from localhost[127.0.0.1] ehlo=1 starttls=1 commands=2
```

I used the following compose file:

```yaml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.domain.com
    env_file: mailserver.env
    ports:
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "25:25"  
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /home/thibaut/nginx/data/certbot/conf:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

Any help appreciated, thanks

EDIT, I tested TLS config like this to check if it's working: 
```
docker exec mailserver openssl s_client   -connect 0.0.0.0:25   -starttls smtp   -CApath /etc/ssl/certs/

Can't use SSL_get_servername
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = domain.com
verify return:1
250 CHUNKING
DONE
CONNECTED(00000003)
---
Certificate chain
 0 s:CN = domain.com
   i:C = US, O = Let's Encrypt, CN = R3
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIE9TCCA92g[........]==
-----END CERTIFICATE-----
subject=CN =domain.com

issuer=C = US, O = Let's Encrypt, CN = R3

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 4728 bytes and written 396 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```
