### DISCUSSION TITLE
how i can use roundcube ?

### DISCUSSION THREAD

**Discussion by vahidalvandi** [docker-mailserver/docker-mailserver#3587] [General]
please show me how i can use roundcube ?

**Comment by leoborlot** [comment]
Yes, I running with this stack, with traefik as a reverse proxy. 
Look for enviroments in roundcube docker documentation to complete yout setup as you need. 

```
version: "3.9"
services:
  roundcube:
    image: roundcube/roundcubemail:1.6.1-apache
    container_name: roundcube
    hostname: roundcube
    networks:
      - public
    restart: unless-stopped
    volumes:
      - /DMS/config/roundcube/config:/var/roundcube/config
      - app:/var/www/html
      - data:/var/roundcube/db
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=srv01.email.com.br
      - ROUNDCUBEMAIL_SMTP_SERVER=srv01.email.com.br
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=10M
      #- ROUNDCUBEMAIL_DB_TYPE=mysql
      #- ROUNDCUBEMAIL_DB_HOST=roundcubedb
      #- ROUNDCUBEMAIL_DB_PASSWORD=roundcube-mysql-pw

    labels:
      - traefik.enable=true
      - traefik.http.routers.mail_email_com_br.rule=Host(`mail.email.com.br`)
      - traefik.http.routers.mail_email_com_br.entrypoints=web
      - traefik.http.routers.mail_email_com_brS.entrypoints=websecure
      - traefik.http.routers.mail_email_com_brS.tls.certresolver=myresolver
      - traefik.http.routers.mail_email_com_brS.tls=true
      - traefik.http.routers.mail_email_com_brS.rule=Host(`mail.email.com.br`)

volumes:
  app:
    name: roundcube_app
  data:
    name: roundcube_data
    
networks:
  public:
    name: public
    external: true
```
