### DISCUSSION TITLE
dovecot raises Permission denied on rename of dovecut-uidlist.tmp when trying to fetch mails

### DISCUSSION THREAD

**Discussion by dweipert-3138720606** [docker-mailserver/docker-mailserver#3695] [Q&A]
I mounted the `/var/mail` folder to a remote cifs volume like this

```
services:
  mailserver:
  [...]
  volumes:
    - "remote-mail:/var/mail"
  [...]

volumes:
  remote-mail:
    driver: local
    driver_opts:
      type: cifs
      o: "addr=${REMOTE_DOMAIN},username=${REMOTE_USERNAME},password=${REMOTE_PASSWORD},file_mode=0777,dir_mode=0777"
      device: "//${REMOTE_DOMAIN}${REMOTE_PATH}"
```

When trying to open a folder from a mail client, like Thunderbird or aerc, I get errors like these:
```
Error: Mailbox INBOX: rename(/var/mail/dweipert.de/d/dovecot-uidlist.tmp, /var/mail/dweipert.de/d/dovecot-uidlist) failed: Permission denied
Error: Mailbox Sent: rename(/var/mail/dweipert.de/d/.Sent/dovecot-uidlist.tmp, /var/mail/dweipert.de/d/.Sent/dovecot-uidlist) failed: Permission denied
```

I can generate Drafts in the `.Drafts` folder for example, but not fetch a list of mails.

I tried mounting the directory within `/etc/fstab` and it's the same errors.
Permissions are correctly set to be world read/writable.

![20231211_11h52m49s_grim](https://github.com/docker-mailserver/docker-mailserver/assets/16617893/9cbe8304-5869-48c0-a602-fb3c041f5ee9)

Any ideas what's wrong?
