### DISCUSSION TITLE
Updating docker image 12->13

### DISCUSSION THREAD

**Discussion by MarcS1975** [docker-mailserver/docker-mailserver#3701] [General]
I have been running version 12.1.0 for a while now and am unsure how upgrading to V 13 would impact my settings. I spent  alot of time manually amending configs and settings around:
- postfix 
- fail2ban 
- DKIM
- SPF
- DMARC
Is there a way to preserve the settings?

**Comment by polarathene** [comment]
> I spent alot of time manually amending configs and settings around

How did you manage that?

If you followed our documentation you should be using config files provided to DMS via volume mounts. Upgrading the container rarely has any impact on that data, but just in case make a backup copy before you do.

On the Github Releases page of the project you will find release notes, while on the main repo page, there is a `CHANGELOG.md` which is a bit more detailed (_I revised the v13 changelog so it's a better source than the GH releases for users to grok changes_). You want to pay special attention to the "Breaking Changes" section as this is a major version something may break for you with the upgrade (_usually you can roll back to the prior version if necessary, especially with a backup of your volume data_).

---

> Is there a way to preserve the settings?

What settings are you concerned about being affected? Are they not managed by volumes?

**Comment by MarcS1975** [comment]
Thanks for the reply. Below is my compose file. Yes I am using volumes as suggested but still `/etc/postfix/main.cf` will be updated by the container upgrade. right? And I had to make changes in there because a lot of valid email got rejected.
~~~
services:

  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver2
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    # added one vol for import aj
    hostname: xxx.mydomain.xxx
    ports:
      - "yy:25"
      - "yyy:143"
      - "yyy:587"
      - "yyy:993"
      - "yyy:465"
    volumes:
    - /srv/dev-disk-by-uuid-c8781cb8-41f2-42a6-9ee0-acd14b06524f/Dockerapps/ajmail2/mail-data/:/var/mail/
    - /srv/dev-disk-by-uuid-c8781cb8-41f2-42a6-9ee0-acd14b06524f/Dockerapps/ajmail2/mail-state/:/var/mail-state/
    - /srv/dev-disk-by-uuid-c8781cb8-41f2-42a6-9ee0-acd14b06524f/Dockerapps/ajmail2/mail-logs/:/var/log/mail/
    - /srv/dev-disk-by-uuid-c8781cb8-41f2-42a6-9ee0-acd14b06524f/Dockerapps/ajmail2/config/:/tmp/docker-mailserver/
    - /etc/localtime/:/etc/localtime:ro
    - /srv/dev-disk-by-uuid-c8781cb8-41f2-42a6-9ee0 acd14b06524f/Dockerapps/letsencrypt/fromDSM_T17/xxxxxxx/:/tmp/dms/custom-certs/
    - /srv/dev-disk-by-uuid-c8781cb8-41f2-42a6-9ee0-acd14b06524f/Dockerapps240/ajmail2/import/:/tmp/import/
    environment:
      - LOG_LEVEL=debug #by AJ
      - PFLOGSUMM_TRIGGER=daily_cron # by AJ
      - PFLOGSUMM_RECIPIENT=abc@gmail.com # by AJ
      - LOGWATCH_INTERVAL=daily # by AJ
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=0 # by AJ
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=0
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/tmp/dms/custom-certs/fullchain.pem

**Reply by polarathene** [reply]
> but still `/etc/postfix/main.cf` will be updated by the container upgrade. right? And I had to make changes in there because a lot of valid email got rejected.

`/etc/postfix/main.cf` is an internal file. You should only modify this via `user-patches.sh` or our override file `postfix-main.cf` (see our docs), both files are provided via the volume to `/tmp/docker-mailserver`.

---

You've not said how you're modifying `/etc/postfix/main.cf`, if it's not via either of those two and you don't have a direct volume mount, know that changes to files within the container aren't persisted across new container instances.

This is important to be aware of, since some users rely on stopping/starting and restart of a container. However DMS startup scripts are not always prepared for this and expect to work with fresh internal state as provided by our image, so that can lead to bugs. Instead we encourage always starting/restarting DMS with a fresh container instance (`docker compose up --force-recreate`).

If you have been relying on the same container instance, your changes to such files will be lost, not just from an upgrade but anything that would remove that container instance and start a new one (_I believe an ENV or volume change can do that for example_). So best to back that up.

**Comment by MarcS1975** [comment]
OK thanks. I understand.
The way I amend configuration files is that I log I to the container (via
portainer) and then simply nano config.file. I know from experience that
upgrades overwrite my changes. That's why I raised the question here.

**Reply by polarathene** [reply]
> The way I amend configuration files is that I log I to the container (via portainer) and then simply nano config.file. I know from experience that upgrades overwrite my changes.

No worries, use the features we provide instead and that won't be an issue 👍

**Comment by MarcS1975** [comment]
Awesome, thank you so much!

**Comment by MarcS1975** [comment]
By the way, will you think about adding a simple mail client to the
container (like roundcube or so)? That would be an awesome package....

**Reply by polarathene** [reply]
You can make a feature request, but I think it's unlikely as all maintainers have little time to spare on new features

**Reply by casperklein** [reply]
It's really easy to do so, just add [these lines](https://github.com/roundcube/roundcubemail-docker/blob/28069c0316b8130d16445b8d05fe9a4efe2bb749/examples/docker-compose-simple.yaml#L4-L17) to your existing DMS `compose.yaml`.

**Comment by MarcS1975** [comment]
Wow. I will try that. Thank you very much Casper!

**Comment by MarcS1975** [comment]
Hello again. I just tried the Roundcube container and it worked like a
charm. I needed to tweak the ports a bit but after that it all runs
smoothly...And the speed is impressive. Lets see how it goes after a few
months.
One step closer to terminating Gmail surveilance :)))
thank you guys!

**Reply by audioscavenger** [reply]
awesome! will you share the config and yml part as an example in show and tell pretty please?

**Reply by polarathene** [reply]
Adapted from my comment: https://github.com/orgs/docker-mailserver/discussions/3898#discussioncomment-10263045

```yaml
# DISCLAIMER: This is an example config to demonstrate functionality,
# It does not represent any considerations for secure production deployments.
services:
  dms:
    image: mailserver/docker-mailserver:latest
    hostname: mail.example.test
    # `configs` is a feature that can embed files into this `compose.yaml` example, simplifying trying it out
    # NOTE: Normally this would be `volumes` with external files persisted to your host filesystem.
    configs:
      - source: dms-accounts
        target: /tmp/docker-mailserver/postfix-accounts.cf

  roundcube:
    image: roundcube/roundcubemail:latest
    # NOTE: If you've got a reverse proxy with TLS already with ports published,
    # Comment this out and have it route to this `roundcube` container instead.
    ports:
      - 80:80
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://mail.example.test
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://mail.example.test

# NOTE: The Docker Compose `configs.<name>.content` feature is supported in Docker Compose releases since 2024.
#
# Docker Compose has a variable interpolation feature which matches the `$` character, which we do not want to mistakenly use.
# - File content below avoids that feature via it's escape syntax of repeating that character (`$$`).
# - If you copy/paste to separate files for `volumes` make sure you revert that change.
configs:
  # Created via `setup email add john.doe@example.test secret`
  # - Username: `john.doe@example.test`
  # - Password: `secret`
  dms-accounts:
    content: |
      john.doe@example.test|{SHA512-CRYPT}$$6$$sbgFRCmQ.KWS5ryb$$EsWrlYosiadgdUOxCBHY0DQ3qFbeudDhNMqHs6jZt.8gmxUwiLVy738knqkHD4zj4amkb296HFqQ3yDq4UXt8.
```

I recall that being sufficient to get going with RoundCube, but for OAuth integration it was a it more involved and had some issues.

If you attempt to use OAuth / OIDC.. I may have documented those somewhere in our repo issues or a PR comment, I don't think I got around to addressing some config changes into DMS and may have lost the related information when my system crashed 😓

---

For the `compose.yaml` example above I believe I ran that locally on Windows with WSL2.

If you'd use a local mail client like Thunderbird instead, then that was also doable, but you'd publish a port on DMS like port 587 and 143, and could configure DMS to be reachable via `mail.example.localhost` I think and it'd manage to route that into the container. If you need a certificate just provision a certificate locally with the DMS FQDN and that extra one for the windows host to connect with as the SANs. Pretty sure that works, but the Roundcube container is simpler 👍
