### DISCUSSION TITLE
Trying to use gmail relay but does not work

### DISCUSSION THREAD

**Discussion by albgen** [docker-mailserver/docker-mailserver#3731] [Q&A] [answered]
I have tried to configure DMS as a null mailer (`SMTP_ONLY=1`) to relay mail through Gmail, but it is failing with `451 4.3.0 Error: queue file write error`.

The username and password are correct, because I'm using another container with another image and is sending the mail.

Checked also the docs here:
- https://docker-mailserver.github.io/docker-mailserver/v13.1/examples/use-cases/forward-only-mailserver-with-ldap-authentication/#building-a-forward-only-mail-server
- https://docker-mailserver.github.io/docker-mailserver/v13.1/config/advanced/mail-forwarding/relay-hosts/

```yaml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: smtp-relay.gmail.com
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PERMIT_DOCKER=network
      - ENABLE_SPAMASSASSIN=0
      - SMTP_ONLY=1
      - ENABLE_FETCHMAIL=0
      - ENABLE_POP3=
      - ENABLE_CLAMAV=0
      - RELAY_HOST=smtp-relay.gmail.com
      - RELAY_PORT=587
      - RELAY_USER=myuse@gmail.com
      - RELAY_PASSWORD=myAPPpassw
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    restart: always
```
