### DISCUSSION TITLE
Add Users:  Get a message "File not found".

### DISCUSSION THREAD

**Discussion by Doni49** [docker-mailserver/docker-mailserver#3993] [Q&A] [answered]
I'm trying to get docker-mailserver up and running.
- After running `docker compose up` against the `compose.yaml` file, it acts like it's loading but keeps warning me that I need to create a user or it will stop.  But the only way I can access the command line to create the user is to force it to stop. 
- Having done that, when I run the "add user" code from the example provided on the website, I get an error message:
   **`/bin/bash: line 1: /mnt/docker/mailserver/config/postfix-accounts.cf: No such file or directory`**.
- The folder DOES exist, I even changed to that directory just to be sure.  Then I CREATED the file (**`touch postfix-accounts.cf`**) with nothing in it and tried again with the same results.

While I was actively IN THAT DIRECTORY, I changed it to use `./postfix-accounts.cf` instead of all the full path.  That no longer threw the error but the file is still blank and when I try to start the container, I get the message about needing to create a user.

![image](https://github.com/docker-mailserver/docker-mailserver/assets/14239245/d01070e5-2af3-4dec-a612-0d0b0738c449)

Here's my `compose.yaml` file:

```yaml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.home.arpa
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-p>
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 i>
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - /mnt/docker/mailserver/data/:/var/mail/
      - /mnt/docker/mailserver/state/:/var/mail-state/
      - /mnt/docker/mailserver/logs/:/var/log/mail/
      - /mnt/docker/mailserver/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```
