### DISCUSSION TITLE
Implementing Docker-MailServer as a Relay server

### DISCUSSION THREAD

**Discussion by ashwaqrehman** [docker-mailserver/docker-mailserver#4031] [Q&A]
Hello Community,

I'm currently exploring docker-mailserver and have set up a relay configuration between two servers, but I'm encountering issues. Here is my setup:

- **Server-1**: Installed postfix (mailutils).
- **Server-2**: Set up docker-mailserver, configured to use AWS SES as the relay host.

### Configuration Details

1. **Server-1**:
   - Configured `relayhost` in `main.cf` to `[IP address of Server-2]:587`.

2. **Server-2**:
   - Running docker-mailserver.
   - Configured to use AWS SES as the relay host.
   - In AWS SES, the domain `mydomain.com` is verified with the necessary MX and TXT records.
   - The `docker-compose.yml` for docker-mailserver includes `mail.mydomain.com` as the hostname.

### Desired Functionality

When I send an email from Server-1 using the command:

```
echo "This is a test email." | mail -s "Test email" user@anydomain.com
```

I expect the email to:

1. Be relayed from Server-1 to Server-2.
2. Server-2 (docker-mailserver) should then relay the email through AWS SES.
3. The recipient (`user@anydomain.com`) should receive the email, sent via AWS SES but originally sent by Server-1.

### Problem

Currently, I have set up the relayhosts in both configuration files. I also generated SSL certificates using OpenSSL on Server-2 and copied them to Server-1, updating the `main.cf` on Server-1 accordingly. Despite these efforts, I am facing issues.

**Logs from Server-2 (docker-mailserver):**

```
mailserver  | May 24 10:38:19 mail postfix/submission/smtpd[2049]: connect from <ip of server1>.ap-south-1.compute.internal[ip of server1]
mailserver  | May 24 10:38:19 mail postfix/submission/smtpd[2049]: Anonymous TLS connection established from <ip of server1>.ap-south-1.compute.internal[ip of server1]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (2048 bits)
mailserver  | May 24 10:38:20 mail postfix/submission/smtpd[2049]: NOQUEUE: reject: RCPT from <ip of server1>.ap-south-1.compute.internal[ip of server1]: 554 5.7.1 <ip of server1>.ap-south-1.compute.internal[ip of server1]>: Client host rejected: Access denied; from=<ubuntu@ip of server1>.ap-south-1.compute.internal to=<user@mail.mydomain.com> proto=ESMTP helo=<ip of server1>.ap-south-1.compute.internal
mailserver  | May 24 10:38:20 mail postfix/submission/smtpd[2049]: disconnect from <ip of server1>.ap-south-1.compute.internal[ip of server1] ehlo=2 starttls=1 mail=1 rcpt=0/1 data=0/1 rset=1 quit=1 commands=6/8
```

The key issue here is the `554 5.7.1` error indicating that the client host is rejected and access is denied.

### Request for Help

Could anyone provide guidance on the specific configuration changes needed on both servers to achieve the desired functionality? Any insights into resolving the `554 5.7.1` access denied error would be greatly appreciated.

Thank you!

**Comment by glime-ai** [comment]
**Please note** that this response was created using generative AI, leveraging previously available information from the repository. This information may be helpful. However, it is our strong recommendation that you carefully consider the information before blindly applying it.

---

Hello,

Based on the details you've provided and the error logs from Server-2 (docker-mailserver), it seems that the issue is related to the SMTP client authentication and permission settings on Server-2. The error `554 5.7.1: Client host rejected: Access denied` typically indicates that the sending server (Server-1 in your case) is not authorized to relay emails through Server-2.

Here are a few steps and configurations you might need to check or adjust:

1. **Ensure Proper Client Authentication:**
   - On Server-2, ensure that the `postfix/main.cf` or relevant configuration allows Server-1 to authenticate successfully. You might need to set up or adjust the `mynetworks` setting to include the IP address of Server-1, allowing it to relay emails. This setting tells Postfix which IPs are trusted to send emails without further authentication.

2. **Configure Relay Permissions:**
   - Check the `smtpd_recipient_restrictions` in your `postfix/main.cf` on Server-2. Ensure that it includes permissions for authenticated users to send emails. It typically looks something like this:
     ```
     smtpd_recipient_restrictions =
        permit_mynetworks,
        permit_sasl_authenticated,
        reject_unauth_destination
     ```

3. **Verify SSL/TLS Settings:**
   - Since you mentioned setting up SSL certificates, ensure that the configurations related to SSL/TLS in `postfix/main.cf` on both servers are correctly pointing to the certificate files and that the certificates are valid and trusted by both servers.

4. **Check AWS SES Configuration:**
   - Since Server-2 is configured to use AWS SES as a relay, ensure that all configurations related to AWS SES are correct, including `relayhost`, and that the credentials (username and password for SES) are correctly set up in `postfix/sasl_passwd`.

5. **Logs and Debugging:**
   - Increase the logging level on Server-2 to get more detailed information about the connection and any errors. This can be done by adjusting the `maillog_file` and `debug_peer_level` settings in Postfix.

6. **Firewall and Network Settings:**
   - Ensure that no firewall or network settings are blocking the communication between Server-1 and Server-2, especially on the port used for sending emails (587 in your case).

If after checking these settings the issue persists, you might want to provide more detailed logs or configuration snippets for further analysis.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=0d5b86fb7eea4a54acac405212c29aba&utm_medium=github).

**Comment by ashwaqrehman** [comment]
> **Configure Relay Permissions:**
> 
> * Check the `smtpd_recipient_restrictions` in your `postfix/main.cf` on Server-2. Ensure that it includes permissions for authenticated users to send emails. It typically looks something like this:
>   ```
>   smtpd_recipient_restrictions =
>      permit_mynetworks,
>      permit_sasl_authenticated,
>      reject_unauth_destination
>   ```
Yeah, I've tried these changes also and my current config have all these required variables configured

Here is my compose.yml:
```
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.mydomain.com
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

My mailserver.env:
```
OVERRIDE_HOSTNAME=
DMS_DEBUG=0
LOG_LEVEL=info
SUPERVISOR_LOGLEVEL=
ONE_DIR=1
DMS_VMAIL_UID=
DMS_VMAIL_GID=
ACCOUNT_PROVISIONER=
POSTMASTER_ADDRESS=
ENABLE_UPDATE_CHECK=1
UPDATE_CHECK_INTERVAL=1d
PERMIT_DOCKER=none
TZ=
NETWORK_INTERFACE=
TLS_LEVEL=
SPOOF_PROTECTION=
ENABLE_SRS=0
ENABLE_OPENDKIM=1
ENABLE_OPENDMARC=1
ENABLE_POLICYD_SPF=1
ENABLE_POP3=
ENABLE_IMAP=1
ENABLE_CLAMAV=0
ENABLE_RSPAMD=0
ENABLE_RSPAMD_REDIS=
RSPAMD_LEARN=0
RSPAMD_GREYLISTING=0
RSPAMD_HFILTER=1
RSPAMD_HFILTER_HOSTNAME_UNKNOWN_SCORE=6
ENABLE_AMAVIS=1
AMAVIS_LOGLEVEL=0
ENABLE_DNSBL=0
ENABLE_FAIL2BAN=0
FAIL2BAN_BLOCKTYPE=drop
ENABLE_MANAGESIEVE=
SMTP_ONLY=
SSL_TYPE=manual
SSL_CERT_PATH=/tmp/docker-mailserver/ssl/mail.mydomain.com-cert.pem
SSL_KEY_PATH=/tmp/docker-mailserver/ssl/mail.mydomain.com-key.pem
POSTFIX_MAILBOX_SIZE_LIMIT=
ENABLE_QUOTAS=1
POSTFIX_MESSAGE_SIZE_LIMIT=
CLAMAV_MESSAGE_SIZE_LIMIT=
PFLOGSUMM_TRIGGER=
PFLOGSUMM_RECIPIENT=
PFLOGSUMM_SENDER=
LOGWATCH_INTERVAL=
LOGWATCH_SENDER=
REPORT_SENDER=
POSTFIX_INET_PROTOCOLS=all
ENABLE_MTA_STS=0
DOVECOT_INET_PROTOCOLS=all
ENABLE_SPAMASSASSIN=0
ENABLE_SPAMASSASSIN_KAM=0
SPAMASSASSIN_SPAM_TO_INBOX=1
MOVE_SPAM_TO_JUNK=1
MARK_SPAM_AS_READ=0
SA_TAG=2.0
SA_TAG2=6.31
SA_KILL=10.0
ENABLE_FETCHMAIL=0
FETCHMAIL_POLL=300
FETCHMAIL_PARALLEL=0
ENABLE_GETMAIL=0
GETMAIL_POLL=5
ENABLE_OAUTH2=
OAUTH2_INTROSPECTION_URL=
LDAP_START_TLS=
LDAP_SERVER_HOST=
LDAP_SEARCH_BASE=
LDAP_BIND_DN=
LDAP_BIND_PW=
LDAP_QUERY_FILTER_USER=
LDAP_QUERY_FILTER_GROUP=
LDAP_QUERY_FILTER_DOMAIN=
DOVECOT_TLS=
DOVECOT_USER_FILTER=
DOVECOT_PASS_FILTER=
DOVECOT_MAILBOX_FORMAT=maildir
DOVECOT_AUTH_BIND=
ENABLE_POSTGREY=0
POSTGREY_DELAY=300
POSTGREY_MAX_AGE=35
# response when a mail is greylisted
POSTGREY_TEXT="Delayed by Postgrey"
POSTGREY_AUTO_WHITELIST_CLIENTS=5
ENABLE_SASLAUTHD=0
SASLAUTHD_MECHANISMS=
SASLAUTHD_LDAP_SERVER=
SASLAUTHD_LDAP_BIND_DN=
SASLAUTHD_LDAP_PASSWORD=
SASLAUTHD_LDAP_SEARCH_BASE=
SASLAUTHD_LDAP_FILTER=
SASLAUTHD_LDAP_START_TLS=
SASLAUTHD_LDAP_TLS_CHECK_PEER=
SASLAUTHD_LDAP_TLS_CACERT_FILE=
SASLAUTHD_LDAP_TLS_CACERT_DIR=
SASLAUTHD_LDAP_PASSWORD_ATTR=
SASLAUTHD_LDAP_AUTH_METHOD=
SASLAUTHD_LDAP_MECH=
SRS_SENDER_CLASSES=envelope_sender
SRS_EXCLUDE_DOMAINS=
SRS_SECRET=
DEFAULT_RELAY_HOST=
RELAY_HOST=email-smtp.ap-south-1.amazonaws.com
RELAY_PORT=587
RELAY_USER=aws_username
RELAY_PASSWORD=aws_password

```
This is my `docker-mailserver-13.3.1/docker-data/dms/config/postfix-main.cf` file
```
smtpd_recipient_restrictions =
   permit_mynetworks,
   permit_sasl_authenticated,
   reject_unauth_destination
mynetworks = 127.0.0.0/8, [ip of server-1]
mydestination = localhost
virtual_mailbox_domains = mail.mydomain.com
```

**Here is my `main.cf` of Server-1:**
```
smtpd_banner = $myhostname ESMTP $mail_name (Ubuntu)
biff = no
append_dot_mydomain = no
#delay_warning_time = 4h
readme_directory = no
compatibility_level = 2
smtpd_tls_cert_file=/etc/ssl/certs/mail.mydomain.com-cert.pem
smtpd_tls_key_file=/etc/ssl/private/mail.mydomain.com-key.pem
smtpd_tls_security_level=may
smtpd_recipient_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination
smtpd_client_restrictions = permit_mynetworks, reject_rbl_client zen.spamhaus.org, reject_rbl_client bl.spamcop.net, permit_sasl_authenticated
smtp_tls_CApath=/etc/ssl/certs
smtp_tls_security_level=may
smtp_tls_loglevel = 1
smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache
#smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
myhostname = [server-1 hostname]
alias_maps = hash:/etc/aliases
alias_database = hash:/etc/aliases
#myorigin = /etc/mailname
mydestination =  localhost.ap-south-1.compute.internal, localhost
relayhost = [server-2 IP]:587
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
mailbox_size_limit = 0
recipient_delimiter = +
inet_interfaces = all
inet_protocols = all
```

@polarathene  @georglauterbach Can anyone of you please help me with this
