### DISCUSSION TITLE
14.0.0 WARN exited: fetchmail (exit status 5; not expected)

### DISCUSSION THREAD

**Discussion by Jobsays** [docker-mailserver/docker-mailserver#4053] [Q&A]
I've been running docker-mailserver `v13.3.1` successfully for months now with this docker compose setting:

```yml
image: ghcr.io/docker-mailserver/docker-mailserver:latest
```

Today, when I had to bounce the docker host for maintenance, so docker-mailserver `v14.0.0` image was downloaded.  When it starts up, it just starts spamming the logs with: `WARN exited: fetchmail (exit status 5; not expected)`.  To work around the issue, I've temporarily modified my docker compose, and everything starts normally:

```yml
image: ghcr.io/docker-mailserver/docker-mailserver:13.3.1
```

I didn't see anything in 14.0.0 `CHANGELOG.md` that might point to a `mailserver.env` setting I need to change to run the new version, but I'm guessing that's at the root of the problem.  Any ideas?  Here's my `.yaml` & `.env` file attached:

```yaml
version: '3'

services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:13.3.1
    container_name: dockermailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.obfuscated.com
    env_file: /share/Container/dockermailserver/mailserver.env
    dns:
        - "192.168.8.1"
    networks:
        qnet-static:
            ipv4_address: 192.168.8.14
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - /share/Container/dockermailserver/mail-data/:/var/mail/
      - /share/Container/dockermailserver//mail-state/:/var/mail-state/
      - /share/Container/dockermailserver/mail-logs/:/var/log/mail/
      - /share/Container/dockermailserver/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /share/Container/dockermailserver/certs/:/tmp/dms/custom-certs/:ro
      - /share/Container/dockermailserver/config/dovecot/15-mailboxes.conf:/etc/dovecot/conf.d/15-mailboxes.conf:ro
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    restart: always
    stop_grace_period: 1m
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
      
## Network config for hosting on Qnap
networks:
    qnet-static:
        name:  qnet-static-eth0-013562
        external: true
```

[mailserver.env.zip](https://github.com/user-attachments/files/15672790/mailserver.env.zip)

**Comment by glime-ai** [comment]
**Please note** that this response was created using generative AI, leveraging previously available information from the repository. This information may be helpful. However, it is our strong recommendation that you carefully consider the information before blindly applying it.

**This response is generated only once - you will not be able to interact with the glime-ai.**

---

The issue you're encountering with the `fetchmail` service in docker-mailserver v14.0.0 could be due to changes or new requirements in the configuration that were introduced in the latest version. Here are a few steps you can take to troubleshoot and resolve the issue:

1. **Check the Changelog and Documentation:**
   Although you mentioned not finding anything relevant in the changelog, it's always a good idea to double-check the [CHANGELOG](https://github.com/docker-mailserver/docker-mailserver/blob/master/CHANGELOG.md) and the [official documentation](https://docker-mailserver.github.io/docker-mailserver/edge/faq) for any updates or breaking changes that might affect `fetchmail`.

2. **Review `mailserver.env` Configuration:**
   Ensure that your `mailserver.env` file is correctly configured and includes all necessary environment variables. Sometimes, new versions introduce new environment variables or deprecate old ones.

3. **Fetchmail Configuration:**
   Verify if there are any specific configurations related to `fetchmail` that need to be updated. You can refer to the [Environment Variables documentation](https://docker-mailserver.github.io/docker-mailserver/edge/config/environment) for any new or updated variables.

4. **Logs and Debugging:**
   Check the detailed logs for more information on why `fetchmail` is failing. You can increase the verbosity of the logs to get more insights.

5. **Update Docker Compose File:**
   Ensure that your `docker-compose.yaml` file is up-to-date with the latest recommendations from the documentation. Here is an example configuration for reference:

   ```yaml
   version: '3'

   services:
     mailserver:
       image: ghcr.io/docker-mailserver/docker-mailserver:latest
       container_name: dockermailserver
       hostname: mail.obfuscated.com
       env_file: /share/Container/dockermailserver/mailserver.env
       dns:
         - "192.168.8.1"
       networks:
         qnet-static:
           ipv4_address: 192.168.8.14
       ports:
         - "25:25"
         - "143:143"
         - "465:465"
         - "587:587"
         - "993:993"
       volumes:
         - /share/Container/dockermailserver/mail-data/:/var/mail/
         - /share/Container/dockermailserver/mail-state/:/var/mail-state/
         - /share/Container/dockermailserver/mail-logs/:/var/log/mail/
         - /share/Container/dockermailserver/config/:/tmp/docker-mailserver/
         - /etc/localtime:/etc/localtime:ro
         - /share/Container/dockermailserver/certs/:/tmp/dms/custom-certs/:ro
         - /share/Container/dockermailserver/config/dovecot/15-mailboxes.conf:/etc/dovecot/conf.d/15-mailboxes.conf:ro
       cap_add:
         - NET_ADMIN
       restart: always
       stop_grace_period: 1m
       healthcheck:
         test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
         timeout: 3s
         retries: 0

   networks:
     qnet-static:
       name: qnet-static-eth0-013562
       external: true
   ```

6. **Community and Support:**
   If the issue persists, consider reaching out to the community or opening an issue on the [GitHub repository](https://github.com/docker-mailserver/docker-mailserver/issues) for more specific guidance.

By following these steps, you should be able to identify and resolve the issue with `fetchmail` in the latest version of docker-mailserver.

This comment was generated by [Glime](https://glimelab.ai/?utm_source=0d5b86fb7eea4a54acac405212c29aba&utm_medium=github).
