### DISCUSSION TITLE
Need help：Relay forwarding but not working

### DISCUSSION THREAD

**Discussion by ReloadingPeace** [docker-mailserver/docker-mailserver#4132] [Q&A] [answered]
As a novice trying to build an email service for the first time. Due to some reason, VPS vendors blocked port 25 and Gmail and some mail providers are not available in my area , making it impossible to send emails directly . So consider using a relay service to forward emails.

At present, the DMS has been deployed and can receive emails, but it cannot be relayed. 

The following is my compose.yml configuration and log.

compose.yml
```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    domainname: <mail.example.com>
    env_file: mailserver.env
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - ./docker-data/dms/custom-certs/:/tmp/dms/custom-certs/:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/tmp/dms/custom-certs/example_bundle.crt
      - SSL_KEY_PATH=/tmp/dms/custom-certs/example.cn.key
      - DEFAULT_RELAY_HOST=smtp.163.com:465
      - RELAY_HOST=smtp.163.com
      - RELAY_PORT=465
      - RELAY_USER=<My Relay Account>
      - RELAY_PASSWORD=<My Relay PASSWORD>
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

```log
mailserver  | 2024-07-25T15:50:53.376582+08:00 f4d64eda90b6 postfix/submissions/smtpd[799]: connect from 74-50-96-206.static.hvvc.us[74.50.96.206]
mailserver  | 2024-07-25T15:50:54.226251+08:00 f4d64eda90b6 postfix/submissions/smtpd[799]: Anonymous TLS connection established from 74-50-96-206.static.hvvc.us[74.50.96.206]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (2048 bits) server-digest SHA256
mailserver  | 2024-07-25T15:50:57.043818+08:00 f4d64eda90b6 postfix/submissions/smtpd[799]: 0AAC6400B9: client=74-50-96-206.static.hvvc.us[74.50.96.206], sasl_method=LOGIN, sasl_username=system@mail.example.com
mailserver  | 2024-07-25T15:50:57.882556+08:00 f4d64eda90b6 postfix/sender-cleanup/cleanup[811]: 0AAC6400B9: message-id=<1041571359.0.1721893855466@DESKTOP-TLIH5GK>
mailserver  | 2024-07-25T15:50:57.882582+08:00 f4d64eda90b6 postfix/sender-cleanup/cleanup[811]: 0AAC6400B9: replace: header MIME-Version: 1.0 from 74-50-96-206.static.hvvc.us[74.50.96.206]; from=<system@mail.example.com> to=<123@qq.com> proto=ESMTP helo=<DESKTOP-TLIH5GK>: MIME-Version: 1.0
mailserver  | 2024-07-25T15:50:57.890354+08:00 f4d64eda90b6 opendkim[633]: 0AAC6400B9: DKIM-Signature field added (s=mail, d=mail.example.com)
mailserver  | 2024-07-25T15:50:57.932392+08:00 f4d64eda90b6 postfix/qmgr[768]: 0AAC6400B9: from=<system@mail.example.com>, size=344, nrcpt=1 (queue active)
mailserver  | 2024-07-25T15:50:58.080310+08:00 f4d64eda90b6 postfix/smtpd-amavis/smtpd[814]: connect from localhost[127.0.0.1]
mailserver  | 2024-07-25T15:50:58.088840+08:00 f4d64eda90b6 postfix/smtpd-amavis/smtpd[814]: 15A9240257: client=localhost[127.0.0.1]
mailserver  | 2024-07-25T15:50:58.090370+08:00 f4d64eda90b6 postfix/cleanup[815]: 15A9240257: message-id=<1041571359.0.1721893855466@DESKTOP-TLIH5GK>
mailserver  | 2024-07-25T15:50:58.093155+08:00 f4d64eda90b6 postfix/qmgr[768]: 15A9240257: from=<system@mail.example.com>, size=1065, nrcpt=1 (queue active)
mailserver  | 2024-07-25T15:50:58.103284+08:00 f4d64eda90b6 amavis[782]: (00782-01) Passed CLEAN {RelayedOpenRelay}, [74.50.96.206]:6211 [74.50.96.206] <system@mail.example.com> -> <123@qq.com>, Queue-ID: 0AAC6400B9, Message-ID: <1041571359.0.1721893855466@desktop-tlih5gk>, mail_id: 6DhCWg2mRbO9, Hits: -, size: 847, queued_as: 15A9240257, 154 ms
mailserver  | 2024-07-25T15:50:58.111809+08:00 f4d64eda90b6 postfix/smtp-amavis/smtp[812]: 0AAC6400B9: to=<123@qq.com>, relay=127.0.0.1[127.0.0.1]:10024, delay=1.4, delays=1.2/0.02/0/0.16, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 15A9240257)
mailserver  | 2024-07-25T15:50:58.112408+08:00 f4d64eda90b6 postfix/qmgr[768]: 0AAC6400B9: removed
mailserver  | 2024-07-25T15:50:58.112874+08:00 f4d64eda90b6 postfix/smtp[816]: SMTPS wrappermode (TCP port 465) requires setting "smtp_tls_wrappermode = yes", and "smtp_tls_security_level = encrypt" (or stronger)
mailserver  | 2024-07-25T15:50:58.323660+08:00 f4d64eda90b6 postfix/submissions/smtpd[799]: disconnect from 74-50-96-206.static.hvvc.us[74.50.96.206] ehlo=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=6
mailserver  | 2024-07-25T15:51:18.216330+08:00 f4d64eda90b6 postfix/smtp[816]: 15A9240257: to=<123@qq.com>, relay=smtp.163.com[111.124.203.45]:465, delay=20, delays=0.01/0.02/20/0, dsn=4.4.2, status=deferred (lost connection with smtp.163.com[111.124.203.45] while receiving the initial server greeting)
```
Below is what I wrote in the host ` /etc/postfix/main.cf `file, nothing else has changed
```yml
relayhost = smtp.163.com:465
smtp_use_tls = yes
smtp_sasl_auth_enable = yes
smtp_tls_wrappermode = yes
smtp_tls_security_level = encrypt
smtp_sasl_security_options = noanonymous
smtp_sasl_type = cyrus
smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
```

May I ask how to configure the mail correctly to be relayed and forwarded? Since I am a novice, any help from you will be of great help to me. Thank you very much.
