### DISCUSSION TITLE
sieve script executed only when my client (thunderbird) is open and connected

### DISCUSSION THREAD

**Discussion by siktec-lab** [docker-mailserver/docker-mailserver#4168] [Q&A] [answered]
So, Everything is working fine, and I have a mailbox with a sieve script activated (which executes an external program).
When my local client (Thunderbird) is connected to the server and polling for incoming emails, the sieve script triggers. But when my client is closed, and an email is sent, the script fails with a timeout: "... Forcibly terminated with signal 15" in the logs.
What am I missing? Is there a way to process emails immediately?

**Comment by polarathene** [comment]
You should probably share more details, the easier it is to reproduce the better someone could chime in to assist.

My experience with sieve is that it works without needing any mail client connected. Probably something wrong with your configuration, or you're trying to do something a bit differently.

**Reply by siktec-lab** [reply]
The funny thing is that it works until I close Thunderbird...

The log when thunderbird is closed:
```
mail dovecot: lmtp(557700): Connect from local
mail dovecot: lmtp(shlomi@mysecretdomain.com)<557700><I3lIBlfgzWaEgggAXAl5VQ>: Error: program exec:/usr/lib/dovecot/sieve-pipe/pipe-email-vinyasa.py (557701): Forcibly terminated with signal 15
mail dovecot: lmtp(shlomi@mysecretdomain.com)<557700><I3lIBlfgzWaEgggAXAl5VQ>: sieve: msgid=<01000191943421a8-5b686d39-fd29-4aab-a442-50165418b193-000000@email.amazonses.com>: stored mail into mailbox 'INBOX'
mail postfix/lmtp[557699]: D493982E35: to=<shlomi@mysecretdomain.com>, relay=mail.mysecretdomain.com[/var/run/dovecot/lmtp], delay=10, delays=0.06/0.06/0.12/10, dsn=2.0.0, status=sent (250 2.0.0 <shlomi@mysecretdomain.com> I3lIBlfgzWaEgggAXAl5VQ Saved)
mail postfix/qmgr[937]: D493982E35: removed
mail dovecot: lmtp(557700): Disconnect from local: Logged out (state=READY)
```

And the dovecot.sieve.log: (thunderbird is closed)
```
error: failed to pipe message to program `pipe-email-vinyasa.py': refer to server log for more information.
```
The log when Thunderbird is opened:
```
mail dovecot: lmtp(14040): Connect from local
mail dovecot: lmtp(shlomi@mysecretdomain.com)<14040><LNGAFxVvz2bYNgAAXAl5VQ>: sieve: msgid=<010001919a49c2f5-ec14e85d-2622-43f0-ad9c-855d2e189740-000000@email.amazonses.com>: pipe action: piped message to program `pipe-email-vinyasa.py'
mail dovecot: lmtp(shlomi@mysecretdomain.com)<14040><LNGAFxVvz2bYNgAAXAl5VQ>: sieve: msgid=<010001919a49c2f5-ec14e85d-2622-43f0-ad9c-855d2e189740-000000@email.amazonses.com>: stored mail into mailbox 'INBOX'
mail postfix/lmtp[14039]: 5797782E4E: to=<shlomi@mysecretdomain.com>, relay=mail.mysecretdomain.com[/var/run/dovecot/lmtp], delay=4.6, delays=0.01/0.02/0.01/4.5, dsn=2.0.0, status=sent (250 2.0.0 <shlomi@mysecretdomain.com> LNGAFxVvz2bYNgAAXAl5VQ Saved)
mail postfix/qmgr[294]: 5797782E4E: removed
mail dovecot: lmtp(14040): Disconnect from local: Logged out (state=READY)
```
The sieve script was installed and activated for "shlomi@mysecretdomain.com" (I can see it in ... shlomi/home ....)
```sieve
require "copy";
require "vnd.dovecot.pipe";
pipe :copy :try "pipe-email-vinyasa.py";
```
Here is my DMS service:
```yaml
services:

  dms:
    build: 
      context: .
      # just adding some python stuff ontop of ghcr.io/docker-mailserver/docker-mailserver:latest
      dockerfile: ./services/dms/Dockerfile.dms

    container_name: dms
    hostname: mail.mysecretdomain.com
    env_file: mailserver.env
    restart: always
    stop_grace_period: 1m
    environment:
      - SSL_TYPE=letsencrypt
      - SSL_DOMAIN=mysecretdomain.com
      - ENABLE_IMAP=1
      - ENABLE_MANAGESIEVE=1
      - ENABLE_OPENDKIM=1
      - ENABLE_OPENDMARC=1
      - ENABLE_POLICYD_SPF=1
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=0
      - ENABLE_CLAMAV=0
      - ENABLE_SPAMASSASSIN=0
      - SPOOF_PROTECTION=0
      - POSTFIX_INET_PROTOCOLS=ipv4
      - DOVECOT_INET_PROTOCOLS=ipv4
      - DMS_DEBUG=1
      - LOG_LEVEL=debug
      - DOVECOT_TLS=yes
    #ports:
      # - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      # - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      # - "465:465"  # ESMTP (implicit TLS)
      # - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      # - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - ./docker-data/dms/config/policyd-spf.conf:/etc/postfix-policyd-spf-python/policyd-spf.conf
      - ./docker-data/traefik/certs/acme.json:/etc/letsencrypt/acme.json:ro
      - /etc/localtime:/etc/localtime:ro
      - ./services/dms/api:/var/server-api/src
      - ./services/dms/handlers:/usr/lib/dovecot/sieve-pipe
    networks:
      default:
        ipv4_address: 172.16.42.4
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      # The SMTP service:
      - traefik.tcp.routers.smtp.rule=HostSNI(`*`)
      - traefik.tcp.routers.smtp.entrypoints=smtp
      - traefik.tcp.routers.smtp.service=smtp
      - traefik.tcp.services.smtp.loadbalancer.server.port=25
      - traefik.tcp.services.smtp.loadbalancer.proxyProtocol.version=2
      # The SMTP SSL service:
      - traefik.tcp.routers.smtp-ssl.rule=HostSNI(`*`)
      - traefik.tcp.routers.smtp-ssl.entrypoints=smtp-ssl
      - traefik.tcp.routers.smtp-ssl.service=smtp-ssl
      - traefik.tcp.services.smtp-ssl.loadbalancer.server.port=465
      - traefik.tcp.services.smtp-ssl.loadbalancer.proxyProtocol.version=1
      # The Submission service:
      - traefik.tcp.routers.smtp-submission.rule=HostSNI(`*`)
      - traefik.tcp.routers.smtp-submission.entrypoints=smtp-submission
      - traefik.tcp.routers.smtp-submission.service=smtp-submission
      - traefik.tcp.services.smtp-submission.loadbalancer.server.port=587
      - traefik.tcp.services.smtp-submission.loadbalancer.proxyProtocol.version=2
      # The IMAP service:
      - traefik.tcp.routers.imap.rule=HostSNI(`*`)
      - traefik.tcp.routers.imap.entrypoints=imap
      - traefik.tcp.routers.imap.service=imap
      - traefik.tcp.services.imap.loadbalancer.server.port=143
      - traefik.tcp.services.imap.loadbalancer.proxyProtocol.version=2
      # The IMAP SSL service:
      - traefik.tcp.routers.imap-ssl.rule=HostSNI(`*`)
      - traefik.tcp.routers.imap-ssl.entrypoints=imap-ssl
      - traefik.tcp.routers.imap-ssl.service=imap-ssl
      - traefik.tcp.services.imap-ssl.loadbalancer.server.port=993
      - traefik.tcp.services.imap-ssl.loadbalancer.proxyProtocol.version=2
      # The Sieve service:
      - traefik.tcp.routers.sieve.rule=HostSNI(`*`)
      - traefik.tcp.routers.sieve.entrypoints=sieve
      - traefik.tcp.routers.sieve.service=sieve
      - traefik.tcp.services.sieve.loadbalancer.server.port=4190
      - traefik.tcp.services.sieve.loadbalancer.proxyProtocol.version=2
 ```

Here is my dovecot.cf
```cf
haproxy_trusted_networks=172.16.42.2,172.16.42.5

haproxy_timeout=30secs

mail_max_userip_connections = 200

default_process_limit = 150

# Override Dovecot services to use ProxyProtocol:
service imap-login {
  inet_listener imaps {
    haproxy = yes
    port = 993
  }

  inet_listener imap {
    haproxy = yes
  }
}

service pop3-login {
  inet_listener pop3 {
    haproxy = no
  }

  inet_listener pop3s {
    haproxy = no
  }
}

service managesieve-login {
  inet_listener sieve {
    haproxy = yes
    port = 4190
  }
}

protocol sieve {
    managesieve_max_line_length = 65536
}
```
postfix-master.cf
```
smtp/inet/postscreen_upstream_proxy_protocol=haproxy
submission/inet/smtpd_upstream_proxy_protocol=haproxy
submissions/inet/smtpd_upstream_proxy_protocol=haproxy
```
