### DISCUSSION TITLE
Web interface to manage email aliases

### DISCUSSION THREAD

**Discussion by scheidti** [docker-mailserver/docker-mailserver#4177] [Show and tell]
Hi community,

I’m excited to share an addon I’ve developed for DMS. It’s called [Docker Mailserver Aliases](https://github.com/scheidti/docker-mailserver-aliases), and it provides a simple web interface to manage email aliases! I developed it for my own DMS instance to easily create and delete email aliases.

For now this are the implemented features:

- List existing aliases: Easily view all email aliases and their forwarding addresses.
- Add new aliases: Create new email aliases.
- Delete aliases: Remove any unwanted or outdated aliases.

You can run it as a Docker container alongside Docker Mailserver.

Maybe someone will find it useful, and I’d love to get feedback!

![screenshot](https://github.com/user-attachments/assets/aaca854b-bc6a-45b8-a7d9-dfceff8879c5)

**Comment by casperklein** [comment]
I couldn't get it to work. After startup, the `mailserver-alias` container immediately exits: ``mailserver-aliases-1 exited with code 0`` 

Here is the demo setup I used:

<details>
<summary>compose.yaml</summary>

```yaml
services:
  mailserver:
    hostname: mail.example.com
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    configs:
      - source: dms-account
        target: /tmp/docker-mailserver/postfix-accounts.cf

  mailserver-aliases:
    image: chscheid/docker-mailserver-aliases:1.0.1
    restart: unless-stopped
    environment:
      - GIN_ADDR=8080
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# NOTE: This feature requires Docker Compose v2.23.1 (Nov 2023) or newer:
# https://github.com/compose-spec/compose-spec/pull/446
configs:
  # DMS requires an account to complete setup
  # password is `secret`
  dms-account:
    content: |
      jane.doe@example.com|{SHA512-CRYPT}$$6$$sbgFRCmQ.KWS5ryb$$EsWrlYosiadgdUOxCBHY0DQ3qFbeudDhNMqHs6jZt.8gmxUwiLVy738knqkHD4zj4amkb296HFqQ3yDq4UXt8.
```
</details>

---

Two thoughts:

1. Mounting `/var/run/docker.sock` gives the container full access to the docker daemon. This is bad from a security point of view (allowing the container to control every container, running additional containers etc.). Instead you could install a SSH daemon in the DMS container and issue the commands via ssh.
2. If I understand correctly, DMS is detected by the used [image name](https://github.com/scheidti/docker-mailserver-aliases/blob/bcaa8b1a2224f331d909192e3bf8f2484da8c3d6/models/models.go#L3). If DMS is run with a custom image build (with a different image name), it does not work? The container name could be configurable via an ENV.
