### DISCUSSION TITLE
Configuration for multiple domains

### DISCUSSION THREAD

**Discussion by devkarlos** [docker-mailserver/docker-mailserver#4295] [Q&A] [answered]
Hey,

How exactly should I configure `mailserver.env` for multiple domains? In your [documentation](https://docker-mailserver.github.io/docker-mailserver/latest/faq/#do-you-support-multiple-domains), it is stated that you support it, but there is no information on how to set it up. I have also found only three issues about the similar thing #1100 #742 #57.

To be specific, I am having issues with SSL certificates. I cannot configure them in a way that works correctly for both domains.  
![image](https://github.com/user-attachments/assets/d06aeaab-0335-4c67-b77c-f1c0295cbe14)

I am using [nginx-proxy-manager](https://nginxproxymanager.com/) to manage my reverse proxy, and I have attached its storage to the `docker-compose.yml` of the mailserver. The same applies to its network.

### `docker-compose.yml`
```yaml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    restart: always
    ports:
      - 25:25      # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - 587:587  # ESMTP (explicit TLS => STARTTLS)
      - 465:465  # ESMTP (implicit TLS)
      - 143:143  # IMAP4 (explicit TLS => STARTTLS)
      - 993:993  # IMAP4 (implicit TLS)
      - 995:995  # POP3
    volumes:
      - config:/tmp/docker-mailserver/
      - data:/var/mail/
      - state:/var/mail-state/
      - logs:/var/log/mail/
      - npm_letsencrypt:/etc/letsencrypt/:ro
    stop_grace_period: 1m
    env_file: mailserver.env
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 3

volumes:
  config:
    name: mailserver_config
  data:
    name: mailserver_data
  state:
    name: mailserver_state
  logs:
    name: mailserver_logs
  npm_letsencrypt:
      external: true

networks:
  npm_proxy:
    external: true
```

### `mailserver.env`
```
OVERRIDE_HOSTNAME=mail.example1.com
POSTMASTER_ADDRESS=postmaster@example1.com
SSL_TYPE=letsencrypt
VIRTUAL_HOST=mail.example1.com,mail.example2.com
LETSENCRYPT_HOST=mail.example1.com,mail.example2.com
PFLOGSUMM_RECIPIENT=admin@example1.com
PFLOGSUMM_SENDER=noreply@example1.com
LOGWATCH_RECIPIENT=admin@example1.com
LOGWATCH_SENDER=noreply@example1.com
REPORT_RECIPIENT=admin@example1.com
REPORT_SENDER=noreply@example1.com
```

I have created symlinks in `/etc/letsencrypt/live` for the `npm-xx` certificates to be `mail.example1.com` and `mail.example2.com`. I have also tried to:
1. Create a SAN certificate
2. Change the certificates to be for just example1.com and example2.com
3. ^ Create a SAN certificate for this
4. Manually link the certificates using SSL_TYPE=manual and using both CERT and ALT_CERT for the other domain
5. Disable SSL completely and perform reverse proxying in NPM. This does not work because I cannot use a single certificate for multiple domains (e.g., imap., smtp.)

Thanks for your help!
