### DISCUSSION TITLE
Large mailbox - archiving possible?

### DISCUSSION THREAD

**Discussion by Softbox44** [docker-mailserver/docker-mailserver#4446] [Q&A]
I am getgin fairly large mail folders with some `cur` over 50GB ,mainly due to received emails with file attachments of 10-30MB. Is there a clever way to archive large emails? Or alternativelly an automated way to extract the attachments?

**Comment by Softbox44** [comment]
any ideas??

**Reply by polarathene** [reply]
Look through existing issues/discussions and you should find some advice on using various tools to manage backup archives.

If you want to filter specifically for specific conditions, you can possibly to so with Dovecot Sieve script or similar.

This isn't a common use-case for DMS so you'll need to figure this out yourself or wait until someone from the community potentially chimes in with better advice.

**Comment by casperklein** [comment]
This can be done with the find command:

```bash
find ./cur -type f -size +50M  # find files larger than 50mb
find ./cur -type f -mtime +30  # find files older than 30 days
```

```bash
# Move mails older than 30 days to /my-archive
find ./cur -type f -mtime +30 -exec mv {} /my-archive/ \;
```

**Comment by Softbox44** [comment]
Thanks. Great search terms. Thank you. Is there a way to extract attachments. The main issue is with large attachments I receive where I'd like to keep the email but remove the attachment from the mail folder.
Any tips?

**Reply by polarathene** [reply]
You would use a cron script in the container to run that `find` command I think, which can be paired with `-exec mv` to run a command for each large file found (_similar to the example @casperklein provided you above that does it for `-mtime +30` instead_).

If you prefer systemd timers instead, or a cron job on the host, you could have the script with `find` command mounted in the DMS container, and have your scheduled task run `docker exec dms /my-script-name.sh`.

Just have it `mv` the attachment to a volume mount to persist the attachment.

Make sure you have a backup copy of your data to try that on, so that you are able to restore or access it at a later date should you need it.

**Comment by polarathene** [comment]
Actually it seems [Dovecot has support for storing attachments separately](https://portal.smartertools.com/community/a93183/ability-to-set-an-alternate-dedicated-storage-for-attachments.aspx):

> On dovecot this exists since 2010  is easily configurable for example like this:
> 
> ```
> mail_home = /mailstore/local/%d/%n
> mail_location = mdbox:/mailstore/local/%d/%n:ALT=/mailstore/remote/%d/%n
> mail_attachment_fs = sis posix
> mail_attachment_dir = /mailstore/attachments
> mail_attachment_min_size = 128k
> ```

`sis` apparently refers to SIS (Single Instance attachment Storage).

~~I don't have the time to look into this right now~~, but I know DMS manages `mail_home` + `mail_location`, we probably don't touch the `mail_attachment*` settings in that quote.

You can see there's a threshold size for when the attachment is split off to attachment storage dir. So those two settings are straightforward, while `mail_attachment_fs` seems to already default to the value `sis posix` but in Dovecot 2.4 the setting name has changed and SIS is deprecated (_thus only `posix` FS driver` supported, dedupe functionality may require FS capability to handle it instead_):

- Dovecot 2.3 (_which DMS uses as of DMS v15_): [`mail_attachment_fs`](https://doc.dovecot.org/2.3/settings/core/#core_setting-mail_attachment_fs)
- Dovecot 2.4 (_DMS does not support this upgrade yet, many breaking changes_): [`mail_ext_attachment`](https://doc.dovecot.org/main/core/summaries/settings.html#mail_ext_attachment)

Likewise the equivalent settings between these versions for [`mail_attachment_dir`](https://doc.dovecot.org/2.3/settings/core/#core_setting-mail_attachment_dir) / [`mail_ext_attachment_path`](https://doc.dovecot.org/main/core/summaries/settings.html#mail_ext_attachment_path) have the same docs line mentioned:

> _With [sdbox](https://doc.dovecot.org/main/core/config/mailbox_formats/dbox.html#single-dbox-sdbox) and [mdbox](https://doc.dovecot.org/main/core/config/mailbox_formats/dbox.html#multi-dbox-mdbox), mail attachments can be saved to external files, which also allows single-instance storage of them._

DMS however uses `maildir`:

https://github.com/docker-mailserver/docker-mailserver/blob/c9aac24a7256352f537aa32b149fcf5a4e4c7706/target/dovecot/10-mail.conf#L30-L31

DMS presently does support changing that to a different format [`sdbox` or `mdbox`](https://github.com/docker-mailserver/docker-mailserver/blob/c9aac24a7256352f537aa32b149fcf5a4e4c7706/test/tests/parallel/set1/dovecot/mailbox_format_dbox.bats) (_both categorized as `dbox` under Dovecot docs_) via the [`DOVECOT_MAILBOX_FORMAT` ENV](https://docker-mailserver.github.io/docker-mailserver/v15.0/config/environment/#dovecot_mailbox_format)

https://github.com/docker-mailserver/docker-mailserver/blob/c9aac24a7256352f537aa32b149fcf5a4e4c7706/target/scripts/startup/setup.d/dovecot.sh#L59-L72

It seems that may be required for the attachment feature as the [Dovecot docs](https://doc.dovecot.org/2.3/admin_manual/mailbox_formats/dbox/#alternate-storage) suggest that `maildir` is not supported? (_**EDIT:** That actually seems to be about a separate [`ALT` storage path support in `mail_location`](https://doc.dovecot.org/2.3/configuration_manual/mail_location/dbox/#dbox-settings-alt-storage)_)

Migrating your existing mail to a different storage format would be another task for you to suss out, although I think this has been covered in other discussions should you need to tackle that too.

---

Here is how to get this functionality in DMS with the following (for Dovecot 2.3), I've verified it to work:

```yaml
services:
  dms:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest # :15.0
    hostname: mail.example.internal
    environment:
      # Updates `mail_location` with `sdbox` or `mbox` (default is `maildir`):
      # NOTE: Support for alternative mailbox formats is not well tested in DMS
      DOVECOT_MAILBOX_FORMAT: mdbox
    volumes:
      # Use whatever you like for paths here, so long as the target path in the
      # container matches the path for the `dovecot.cf` override setting `mail_attachment_dir`
      #
      # NOTE: Dovecot expects ownership (5000:5000 default in DMS)
      # Might differ for LDAP if not corrected there, otherwise should be configurable via `DMS_VMAIL_UID`:
      # https://docker-mailserver.github.io/docker-mailserver/latest/config/environment/#dms_vmail_uid
      - ./dovecot-attachments:/srv/dovecot/attachments
    configs:
      - source: dms-accounts
        target: /tmp/docker-mailserver/postfix-accounts.cf
      - source: dovecot-override
        target: /tmp/docker-mailserver/dovecot.cf

# Remove this if you're providing your own DMS config volume for
# `/tmp/docker-mailserver` with equivalent files.
configs:
  dms-accounts:
    content: |
      john.doe@example.internal|{SHA512-CRYPT}$$6$$sbgFRCmQ.KWS5ryb$$EsWrlYosiadgdUOxCBHY0DQ3qFbeudDhNMqHs6jZt.8gmxUwiLVy738knqkHD4zj4amkb296HFqQ3yDq4UXt8.

  dovecot-override:
    content: |
      # Add support for storing mail attachments at a different location:
      mail_attachment_fs = posix
      mail_attachment_dir = /srv/dovecot/attachments
      mail_attachment_min_size = 128k
```

```console
# Start DMS and shell into it:
$ docker compose up -d --force-recreate
$ docker compose exec -it dms bash

# Create a sparse file of 1MB size to test as an attachment:
$ truncate -s 1MB /tmp/example.dat

# Send a mail with that file attached:
$ swaks --server localhost \
  --from alice.doe@example.internal --to john.doe@example.internal \
  --header "Subject: This is an attachment example" \
  --attach-name example.dat --attach @/tmp/example.dat

# Attachment was split off into expected location:
$ du -shx /srv/dovecot/attachments
1016K   /srv/dovecot/attachments

$ du -shx /var/mail
64K     /var/mail
```
