### DISCUSSION TITLE
Docker Mailserver potential conflict with Nextcloud?

### DISCUSSION THREAD

**Discussion by cogdavid** [docker-mailserver/docker-mailserver#4452] [Q&A]
I am using Docker Mailserver. Users authenticate with LLDAP. Everything was working fine until I setup an email account to send email from Nextcloud and integrated Nextcloud with LLDAP.

I got nextcloud to send a test email - this appears to have removed my mailboxes and stopped them from receiving email from any source other than Nextcloud.

This is the error message from my logs:

```
Recipient address rejected: User unknown in virtual mailbox table; from=<prvs=52072ff83d=david@xyz.com> to=<xxxx@recognition-circular.org> proto=ESMTP helo=<mx07-0060ad01.pphosted.com>
```

If I do a `./setup.sh email list`, all the accounts now look like this:

```
Fatal: Unknown command 'quota', but plugin quota exists. Try to set mail_plugins=quota

2025-04-22 15:03:32+02:00 **ERROR** listmailuser: Supplied non-number argument '' to '_bytes_to_human_readable_size()'

2025-04-22 15:03:32+02:00 **ERROR** listmailuser: Aborting

2025-04-22 15:03:32+02:00 **ERROR** listmailuser: Supplied non-number argument '' to '_bytes_to_human_readable_size()'

2025-04-22 15:03:32+02:00 **ERROR** listmailuser: Aborting

* `cloud@recognition-circular.org` ( / ) [%]
```

Apart from the Nextcloud integration nothing has changed with my mailserver config or my lldap config.

I have stoped/removed the container and rebuilt - no effect.

**Comment by polarathene** [comment]
> If I do a `./setup.sh email list`, all the accounts now look like this:

`setup email list` is only for the default `ACCOUNT_PROVISIONER=FILE`, not for LDAP:

https://github.com/docker-mailserver/docker-mailserver/blob/b653d9a586ca951711f05a7d35266b6db5108afb/target/bin/listmailuser#L10-L27

> ```
> Fatal: Unknown command 'quota', but plugin quota exists. Try to set mail_plugins=quota
> ```

This is from running the `doveadm` command as part of that above functionality:

https://github.com/docker-mailserver/docker-mailserver/blob/b653d9a586ca951711f05a7d35266b6db5108afb/target/bin/listmailuser#L55

Likewise the feature Dovecot Quotas is enabled by default (_ENV toggle via [`ENABLE_QUOTAS`](https://docker-mailserver.github.io/docker-mailserver/v15.0/config/environment/#enable_quotas)_), and this also lacks LDAP support (_no one implemented it_), thus the feature is enabled for default `FILE` account provisioner but not `LDAP`:

https://github.com/docker-mailserver/docker-mailserver/blob/b653d9a586ca951711f05a7d35266b6db5108afb/target/scripts/startup/setup.d/dovecot.sh#L142-L146

The other errors you receive after this are because of this failure. The command should technically fail earlier for you or even better communicate the lack of support for LDAP. I can get that sorted out (**EDIT:** [Done](https://github.com/docker-mailserver/docker-mailserver/pull/4453)).

---

> Everything was working fine until I setup an email account to send email from Nextcloud and integrated Nextcloud with LLDAP.

I assume this setup was done via LLDAP, not through our `setup` CLI commands which only provide account management for file based config. DMS shouldn't support a mix of the two AFAIK, but if you did create file based configs this way perhaps it accidentally broke something.

If your account was created via LLDAP, that may be an issue with the LDAP implementation in DMS, or a misconfiguration on your end. Unfortunately no maintainers user LDAP, that feature was community contributed many years ago. There is an active PR you can subscribe to related to LDAP feature work, but I need to find time to finish it.

**Reply by cogdavid** [reply]
@polarathene - thanks for your help. Changing from  ACCOUNT_PROVISIONER=LDAP to ACCOUNT_PROVISIONER=FILE seems to have resolved the issue. 

For info, I used this page to help me format the docker compose file and as you can see it uses ACCOUNT_PROVISIONER=LDAP https://docker-mailserver.github.io/docker-mailserver/latest/examples/tutorials/basic-installation/. Whoever maintains that page, it would be useful to mention the issue here. 

Thanks again - much appreciated.

**Reply by polarathene** [reply]
Yeah sorry about that, time is limited for the project but I do plan to get to rewriting that page. The author that contributed it chose LDAP for the account management, but most of our docs will assume file based provisioning.

**Reply by cogdavid** [reply]
No worries, I understand. Having changed that variable, it looks like Dovecot is now trying to authenticate against the local password and not lldap. Is there something else I need to adjust in my docker-compose.yaml (I have edited to password lines for the purpose of the post)?

```yaml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    networks:
      - app_network
      - nextcloud-aio  
    hostname: mail.recognition-circular.org
    env_file: mailserver.env
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    environment:
      # Core LDAP Configuration
      - ACCOUNT_PROVISIONER=FILE
      - LDAP_SERVER_HOST=ldap://lldap:3890
      - LDAP_SEARCH_BASE=ou=people,dc=recognition-circular,dc=org
      - LDAP_BIND_DN=uid=admin,ou=people,dc=recognition-circular,dc=org
      - LDAP_BIND_PW=xxxxx
      - LDAP_QUERY_FILTER_USER=(&(objectClass=inetOrgPerson)(|(uid=%u)(mail=%u)))
      - LDAP_QUERY_FILTER_GROUP=(&(objectClass=groupOfUniqueNames)(uid=%s))
      - LDAP_QUERY_FILTER_ALIAS=(&(objectClass=inetOrgPerson)(|(uid=%u)(mail=%u)))
      - LDAP_QUERY_FILTER_DOMAIN=(mail=*@%s)
     # Dovecot-Specific LDAP Mapping
      - DOVECOT_USER_FILTER=(&(objectClass=inetOrgPerson)(|(uid=%u)(mail=%u)))
      - DOVECOT_USER_ATTRS==uid=5000,=gid=5000,=home=/var/mail/%Ln,=mail=maildir:~/Maildir
      - DOVECOT_AUTH_BIND=yes 
     # SASL Configuration
     # - ENABLE_SASLAUTHD=1
     # - SASLAUTHD_MECHANISMS=ldap
     # - SASLAUTHD_LDAP_SERVER=ldap://lldap:3890
     # - SASLAUTHD_LDAP_BIND_DN=uid=admin,ou=people,dc=recognition-circular,dc=org
     # - SASLAUTHD_LDAP_PASSWORD=a_secure_pwd   
     # - SASLAUTHD_LDAP_SEARCH_BASE=ou=people,dc=recognition-circular,dc=org
     # - SASLAUTHD_LDAP_FILTER=(&(objectClass=PostfixBookMailAccount)(mail=%U))
      
      # Other Settings
      - SSL_TYPE=letsencrypt
      - DOVECOT_MAILBOX_FORMAT=maildir
      - POSTFIX_INET_PROTOCOLS=all
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_FETCHMAIL=0
      - POSTMASTER_ADDRESS=postmaster@recognition-circular.org

    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ./docker-data/certbot/certs:/etc/letsencrypt


    restart: always
    stop_grace_period: 1m

networks:
  app_network:
    external: true
  nextcloud-aio:
```
