### DISCUSSION TITLE
IMAP authentication fails on Outlook - Multi domains setup

### DISCUSSION THREAD

**Discussion by tigerblue77** [docker-mailserver/docker-mailserver#4458] [Q&A]
Hello everyone,
It's my second time deploying a mail server and I'm sorry but I'm stuck. I guess my TLS configuration is incorrect even if I've read the documentation in details. My setup :
- Homelab behind a DynDNS
- Multiple domains from which I want to be able to send and receive emails, some that I already use to host websites, some not
- Traefik reverse proxy, that I successfully reuse to generate DMS SSL certificate(s)
- I deploy my whole homelab with Ansible, that's why you might see some Jinja2 variables (i.e. `{{ XXX }}`)

Here is my current docker compose file :
```yaml
services:
  application:
    container_name: Mail_server
    image: mailserver/docker-mailserver
    deploy:
      restart_policy:
        condition: on-failure
    restart: always
    # stop_grace_period: 1m
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      interval: 30s # Default : 30s
      timeout: 30s # Default : 30s
      start_period: 0s # Default : 0s
      retries: 3 # Default : 3
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.bbcs-XXX.pub.wingo.ch
    cap_add:
      - NET_ADMIN # Required for Fail2Ban to work
    environment:
      PUID: "1000" # For security reasons : https://docs.linuxserver.io/general/understanding-puid-and-pgid
      PGID: "1000" # For security reasons : https://docs.linuxserver.io/general/understanding-puid-and-pgid
      TZ: "Europe/Paris"
      LOG_LEVEL: info
      ENABLE_CLAMAV: 1
      ENABLE_FAIL2BAN: 1
      SSL_TYPE: "letsencrypt"
      SSL_DOMAIN: "mail.bbcs-XXX.pub.wingo.ch"
      ENABLE_SPAMASSASSIN: 1
      ENABLE_SPAMASSASSIN_KAM: 1
      SPAMASSASSIN_SPAM_TO_INBOX: 1
      ENABLE_POSTGREY: 1
    volumes:
      - data:/var/mail/
      - state:/var/mail-state/
      - logs:/var/log/mail/
      - config:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/volumes/Traefik_SSL_certificates/_data/acme.json:/etc/letsencrypt/acme.json:ro
    ports:
      - "25:25/TCP"   # ESMTP / Explicit TLS : > STARTTLS / Transfer
      - "465:465/TCP" # ESMTP / Implicit TLS / Submission
      - "993:993/TCP" # IMAP4 / Implicit TLS / Retrieval
      - "25:25/UDP"   # ESMTP / Explicit TLS : > STARTTLS / Transfer
      - "465:465/UDP" # ESMTP / Implicit TLS / Submission
      - "993:993/UDP" # IMAP4 / Implicit TLS / Retrieval

  # Required to get SSL certificate through Traefik for domains which does not host any website at the moment
  SSL_certificate_guardian:
    image: docker.io/traefik/whoami
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.http.services.Mail_SSL_certificates_guardian.loadbalancer.server.port: 80
        traefik.http.routers.Mail_SSL_certificates_guardian.rule: "Host(`mail.bbcs-XXX.pub.wingo.ch`) || Host(`mail.XXX.fr.nf`) || Host(`mail.XXX.fr.nf`) || Host(`mail.XXX.fr.nf`) || Host(`mail.XXX.fr.nf`)"
        traefik.http.routers.Mail_SSL_certificates_guardian.entrypoints: "websecure"
    networks:
      - DMZ

volumes:
  data:
  state:
  logs:
  config:

networks:
  Mail_server_network:
    driver: overlay
    external: true
    name: Mail_server_network
  # attachable: true

  DMZ:
    external: true
    name: DMZ
```

Then I run :
```bash
setup email add admin@XXX.fr.nf {{ ansible_password }}
setup alias add {{ alias1 }} admin@XXX.fr.nf
setup alias add {{ alias2 }} admin@XXX.fr.nf
setup alias add {{ alias3 }} admin@XXX.fr.nf
setup alias add {{ alias4 }} admin@XXX.fr.nf
setup alias add {{ alias5 }} admin@XXX.fr.nf
```

From mxtoolbox's perspective, everything looks great :
![image](https://github.com/user-attachments/assets/9732616d-a7e0-43b6-a871-08ffadd1ea6a)

But from outlook (desktop), when I try to log in as admin@XXX.fr.nf, I get the following error message :
> Sorry ... We were unable to connect to the outgoing (SMTP) server. Please check outgoing (SMTP) server settings, then try again.

So I go to "edit settings", here is what I see :

![image](https://github.com/user-attachments/assets/99c91cd3-2d1a-49dc-a563-330767d2d60f)

so I change both "server" fields to `mail.bbcs-XXX.pub.wingo.ch` (the "hostname" I defined in my `docker compose` file, which is the PTR record of my IP, so that it matches the SMTP banner) but the problem persists. And I don't know what I'm missing actually...

Few questions I have :
- Can you confirm that I need a certificate for the DMS hostname + every mail.domain.XX I want to be able to send mails from ? Because I read [everything](https://github.com/orgs/docker-mailserver/discussions/3700#discussioncomment-7867942) and [it's contrary](https://github.com/orgs/docker-mailserver/discussions/4295#discussioncomment-11653532) so I'm a bit lost
- Can you confirm if ports 25/465/993 are all TCP ? I wasn't sure so I opened both UDP and TCP while debugging

Thanks in advance for your help !
Tigerblue77
