### DISCUSSION TITLE
dovecot config overrides not working

### DISCUSSION THREAD

**Discussion by tilllt** [docker-mailserver/docker-mailserver#4461] [Q&A] [answered]
i am running: ghcr.io/docker-mailserver/docker-mailserver:latest

I have an inline compose compose config to override / extend the dovecot configuration
```
    configs:
        - source: xapian
        - target: /tmp/docker-mailserver/dovecot/fts-xapian-plugin.cf
```

```
# Full-text-search Dovecot config for Xapian (example config from DMS docs without opt-in sections):

  xapian:
    content: |
      mail_plugins = $$mail_plugins fts fts_xapian
      plugin {
          fts = xapian
          fts_xapian = partial=3 full=20 attachments=1 verbose=2
          fts_autoindex = yes
          fts_enforced = yes
      }
      service indexer-worker {
          # limit size of indexer-worker RAM usage, ex: 512MB, 1GB, 2GB
          vsz_limit = 2GB
      }
      plugin {
          fts_decoder = decode2text
      }
      service decode2text {
          executable = script /usr/lib/dovecot/decode2text.sh
          user = vmail
          unix_listener decode2text {
          mode = 0666
          }
      }
```

i can see that the config file is correctly copied to ./DATA/dms/config/dovecot/fts-xapian-plugin.cf

After restarting the container with
`docker compose down && docker compose up --force-recreate -d`

and checking the dovecot config with 
`./setup.sh debug login doveconf | grep fts`

the full text search config is not added to the dovecot config.

am i doing something wrong or is this a bug?

**Comment by polarathene** [comment]
> i can see that the config file is correctly copied to ./DATA/dms/config/dovecot/fts-xapian-plugin.cf

I've not tried mounting config files to paths that are persisted by volumes before 🤔 So that's interesting that it got sync'd into the volume / host.

> am i doing something wrong or is this a bug?

I don't think we document any support for what you're trying to do?

We copy a single overrides file:

https://github.com/docker-mailserver/docker-mailserver/blob/491c30b19482af8670f38db4edee2b9b5f67981b/target/scripts/startup/setup.d/dovecot.sh#L97

That is documented at the [top of our Dovecot overrides page](https://docker-mailserver.github.io/docker-mailserver/latest/config/advanced/override-defaults/dovecot/), and later there is a secton on other overrides having a direct mount into `/etc/dovecot` rather than indirectly through our config volume (thus no support).

---

If you were following the [docs page for full-text search](https://docker-mailserver.github.io/docker-mailserver/latest/config/advanced/full-text-search/#setup) it shows a config file to store in your DMS config volume, but if you look at the `compose.yaml` example that follows it is mounted into the container at `/etc/dovecot/...`, DMS doesn't automate that.

**Reply by tilllt** [reply]
I tried it verbatim how it's described in the docs now, the extra config file does still not be added to the dovecot config.

**Reply by polarathene** [reply, marked as answer]
I just followed the instructions in the linked docs page, then `doveconf | grep xapian` output shows that Dovecot has read in the configuration. You are doing something incorrectly on your side.

Here's what I did, adapted to the `configs` feature:

```yaml
services:
  dms:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: dms
    hostname: mail.example.test
    configs:
      - source: dms-accounts
        target: /tmp/docker-mailserver/postfix-accounts.cf
      - source: dovecot-fts
        target: /etc/dovecot/conf.d/10-plugin.conf

# NOTE: `$` in `compose.yaml` needs to be repeated to escape it,
# which opts out of the Docker Compose variable interpolation feature.
configs:
  # DMS expects an account to be configured to run, this example provide an accounts already created.
  # Login credentials:
  # user: "john.doe@example.test" password: "secret"
  dms-accounts:
    content: |
      john.doe@example.test|{SHA512-CRYPT}$$6$$sbgFRCmQ.KWS5ryb$$EsWrlYosiadgdUOxCBHY0DQ3qFbeudDhNMqHs6jZt.8gmxUwiLVy738knqkHD4zj4amkb296HFqQ3yDq4UXt8.

  dovecot-fts:
    content: |
      mail_plugins = $$mail_plugins fts fts_xapian

      plugin {
          fts = xapian
          fts_xapian = partial=3 full=20 verbose=0
          fts_autoindex = yes
          fts_enforced = yes
      }
      
      service indexer-worker {
          # limit size of indexer-worker RAM usage, ex: 512MB, 1GB, 2GB
          vsz_limit = 1GB
      }
```

```console
$ docker compose up -d --force-recreate
$ docker compose exec -it dms bash -c 'doveconf | grep xapian'

mail_plugins = " quota fts fts_xapian"
  fts = xapian
  fts_xapian = partial=3 full=20 verbose=0
  mail_plugins = " quota fts fts_xapian sieve"
  mail_plugins = " quota fts fts_xapian sieve"
  mail_plugins = " quota fts fts_xapian imap_quota"
```

---

That should work for you and matches the documented example config. As your config differs perhaps there was an error logged somewhere about a problem preventing it from working 🤷‍♂️ 

If that's the case you may be affected by [this issue](https://github.com/docker-mailserver/docker-mailserver/issues/4229#issuecomment-2440710794), but no one took action to resolve it. So in that sense your decision to enable `decode2text` is probably broken and would need to be fixed as described in that issue linked.
