### DISCUSSION TITLE
How to setup Traefik + DMS?

### DISCUSSION THREAD

**Discussion by dalmatheo** [docker-mailserver/docker-mailserver#4470] [Q&A] [answered]
Hello guys, I'm sending this today because I tried for 3 hours to setup mailserver behind traefik, and each time I failed. I looked at the documentation, and got this configuration:

<details>
  <summary>docker-compose.yml (Traefik)</summary>

  ```yaml
services:
    traefik:
        image: traefik:latest
        restart: unless-stopped
        environment:
            - CF_DNS_API_TOKEN=My token
        command:
            - "--log.format=json"
            - "--log.level=INFO"
            - "--api=true"

            - "--providers.docker=true"
            - "--providers.docker.exposedByDefault=false"
            - "--providers.docker.network=traefik"

            # Setting up DnsChallenge
            - "--certificatesResolvers.letsencrypt.acme.dnsChallenge=true"
            - "--certificatesResolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare"

            # Setting up Let's Encrypt
            - "--certificatesresolvers.letsencrypt.acme.email=my email"
            - "--certificatesresolvers.letsencrypt.acme.storage=/etc/certs/acme.json"
            - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"

            # Setting up TLS
            - "--certificatesresolvers.letsencrypt.acme.tlsChallenge=true"
            # - "--tls.options.default.minVersion=VersionTLS12"

            # Setting up EntryPoints

            # Web entrypoint
            - "--entryPoints.web.address=:80"
            - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
            - "--entryPoints.web.http.redirections.entryPoint.scheme=https"

            # Websecure (Secure) entrypoint
            - "--entryPoints.websecure.address=:443"
            - "--entryPoints.websecure.http.tls=true"
            - "--entryPoints.websecure.http.tls.certResolver=letsencrypt"
            - "--entryPoints.websecure.asDefault=true"

            # SMTP entrypoint
            - "--entryPoints.smtp.address=:25"
            - "--entryPoints.smtp.proxyProtocol.insecure"

            # SMTPS entrypoint
            - "--entryPoints.smtps.address=:465"
            - "--entryPoints.smtps.proxyProtocol.insecure"

            # IMAPS entrypoint
            - "--entryPoints.imaps.address=:993"
            - "--entryPoints.imaps.proxyProtocol.insecure"
            
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.traefik-api.rule=Host(`dashboard.mydomain.dev`)"
            - "traefik.http.routers.traefik-api.entrypoints=websecure"
            - "traefik.http.routers.traefik-api.service=api@internal"
            - "traefik.http.routers.traefik-api.middlewares=traefik-auth"
            - "traefik.http.middlewares.traefik-auth.basicauth.users=dalmatheo:password"
        ports:
            - 80:80
            - 443:443
            - 25:25
            - 465:465
            - 993:993
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /etc/certs:/etc/certs
        networks:
            traefik:
            traefik_mailserver:
                ipv4_address: 172.16.42.2
            

volumes:
  certs:
      driver: local

networks:
  traefik:
    external: true
    driver: bridge
  traefik_mailserver:
    external: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.42.0/24
  ```
</details>

<details>
  <summary>docker-compose.yml (mailserver)</summary>

  ```yaml
  services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    restart: unless-stopped
    hostname: mail.mydomain.dev
    networks:
      traefik_mailserver:
        ipv4_address: 172.16.42.3
    environment:
      SSL_TYPE: letsencrypt
      SSL_DOMAIN: mail.mydomain.dev
    volumes:
      - /etc/certs/acme.json:/etc/letsencrypt/acme.json:ro
      - mailserver_var:/var
      - docker_mailserver:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_mailserver
    
      # These are examples, configure the equivalent for any additional ports you proxy.
      # Explicit TLS (STARTTLS):
      - traefik.tcp.routers.smtp.rule=HostSNI(`*`)
      - traefik.tcp.routers.smtp.entrypoints=smtp
      - traefik.tcp.routers.smtp.service=smtp
      - traefik.tcp.services.smtp.loadbalancer.server.port=25
      
      # Implicit TLS is no different, except for optional HostSNI support:
      - traefik.tcp.routers.smtps.rule=HostSNI(`*`)
      # - traefik.tcp.routers.smtps.tls.passthrough=true
      - traefik.tcp.routers.smtps.entrypoints=smtps
      - traefik.tcp.routers.smtps.service=smtps
      - traefik.tcp.services.smtps.loadbalancer.server.port=465
      - traefik.tcp.services.smtps.loadbalancer.proxyProtocol.version=2
      # NOTE: Optionally match by SNI rule, this requires TLS passthrough (not compatible with STARTTLS):
      #- traefik.tcp.routers.mail-submissions.rule=HostSNI(`mail.example.com`)
      #- traefik.tcp.routers.mail-submissions.tls.passthrough=true

      - traefik.tcp.routers.imaps.rule=HostSNI(`*`)
      # - traefik.tcp.routers.imaps.tls.passthrough=true
      - traefik.tcp.routers.imaps.entrypoints=imaps
      - traefik.tcp.routers.imaps.service=imaps
      - traefik.tcp.services.imaps.loadbalancer.server.port=993
      - traefik.tcp.services.imaps.loadbalancer.proxyProtocol.version=2


volumes:
  traefik_certs:
      external: true
  mailserver_var:
    driver: local
  docker_mailserver:
    driver: local

networks:  
  traefik_mailserver:
    external: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.42.0/24
  ```
</details>

<details>
  <summary>postfix-master.cf (At the right place)</summary>

  ```
  smtp/inet/postscreen_upstream_proxy_protocol=haproxy
  submission/inet/smtpd_upstream_proxy_protocol=haproxy
  submissions/inet/smtpd_upstream_proxy_protocol=haproxy
  ```
</details>

<details>
  <summary>dovecot.cf (At the right place also)</summary>

  ```
haproxy_trusted_networks = 172.16.42.2

service imap-login {
  inet_listener imap {
    haproxy = yes
  }

  inet_listener imaps {
    haproxy = yes
  }
}

service pop3-login {
  inet_listener pop3 {
    haproxy = yes
  }

  inet_listener pop3s {
    haproxy = yes
  }
}

service managesieve-login {
  inet_listener sieve {
    haproxy = yes
  }
}
  ```
</details>

The problem faced is simple, no traffic goes to mailserver, and I don't know why. If someone know what I did wrong, or if someone has a working configuration that I could borrow, it would be incredible. Thanks.
