### ISSUE TITLE
ClamAV - permission denied on amavis tmp dir

### ISSUE THREAD

**Issue by starfoxx82** [docker-mailserver/docker-mailserver#1691]
## Context

Hi, I have the same problem like the closed issue no #1353 I've installed the mailserver on an kubernetes cluster and want to use the integrated ClamAV service for scanning. with (ENABLE_CLAMAV=1). 

### *What* is affected by this bug?
The mails will not be scanned by ClamAV. It generate an permission denied error log message

### *When* does this occur?
on running the application.

## *How* do we replicate the issue?

1. Install [(like wiki)](https://github.com/tomav/docker-mailserver/wiki/Using-in-Kubernetes)
2. send a mail from existing user to himself
3. see logs

## Actual Behavior

On an incoming email, this is writes in the logs:

> run_av (ClamAV-clamd) FAILED - unexpected , output="/var/lib/amavis/tmp/amavis-20201117T091752-00289-lTvNEEz7/parts: lstat() failed: Permission denied. ERROR\n"
> amavis[289]: (00289-01) (!)ClamAV-clamd av-scanner FAILED: CODE(0x55dda70f2a50) unexpected , output="/var/lib/amavis/tmp/amavis-20201117T091752-00289-lTvNEEz7/parts: lstat() failed: Permission denied. ERROR\n" at (eval 98) line 951.
> amavis[289]: (00289-01) (!)WARN: all primary virus scanners failed, considering backups

## Expected behavior (i.e. solution)

ClamAV should be able to analyze the emails without permission problems

## Your Environment

* Amount of RAM available: 8GB
* Mailserver version used: latest
* Docker version used: 19.03.13
* kubernetes version used: v1.19.3
* Environment settings relevant to the config:

## System
A kubernetes Cluster with an NFS pv

### pv.yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mail-storage
  labels:
    type: local
  namespace: mailserver
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: xxx.xxx.xxx.xxx
    path: "/srv/nfs/kubedata/smtp/mail-storage"
```

### pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mail-storage-claim
  namespace: mailserver
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
```

### configmap.yaml

```
data:
  ONE_DIR: "1"
```

### deployment.yaml
```
          - name: data
            mountPath: /var/mail
            subPath: data
          - name: data
            mountPath: /var/mail-state
            subPath: state
          - name: data
            mountPath: /var/log/mail
            subPath: log

        - name: data
          persistentVolumeClaim:
            claimName: mail-storage-claim
```

### NFS

And when I do ls -aln /var/lib/amavis/tmp/, I get this :
> drwxrwx--- 4 112 114 4096 Nov 17 10:21 .
> drwxr-x--- 8 112 114 4096 Nov 17 10:19 ..
> drwxr-x--- 3 112 114 4096 Nov 17 10:20 amavis-20201117T092012-00283-H7KnOmih
> drwxr-x--- 3 112 114 4096 Nov 17 10:21 amavis-20201117T092102-00282-5WnlwIhO

and on the NFS server i do ls -aln /srv/nfs/kubedata/smtp/mail-storage/state/lib-amavis/tmp, I get this:

> drwxrwx--- 4 112 114 4096 Nov 17 10:21 .
> drwxr-x--- 8 112 114 4096 Nov 17 10:19 ..
> drwxr-x--- 3 112 114 4096 Nov 17 10:20 amavis-20201117T092012-00283-H7KnOmih
> drwxr-x--- 3 112 114 4096 Nov 17 10:21 amavis-20201117T092102-00282-5WnlwIhO

**Comment by aendeavor** [comment]
Alright. Although I have _some_ experience with K8S, remotely trying to find the issue is hard. I hope someone has an idea. As you opened this issue, I'll close the other one again. Good luck!

**Comment by erik-wramner** [comment]
If you have a test cluster I would suggest trying one thing at a time. Specifically get rid of the NFS server and use a simpler mount option. If that works you know it is NFS-related (which I suspect).

**Comment by aendeavor** [comment]
This issue is marked as stale. Please report back. Otherwise this issue is closed due to inactivity.

**Comment by starfoxx82** [comment]
I have to try this out. I will write my realizations soon.

**Comment by starfoxx82** [comment]
i changed my configuration to the following:

### pv.yaml
```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-mail-storage
  labels:
    type: local
  namespace: mailserver
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/kubedata/smtp/mail-storage"
```
### pvc.yaml
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-mail-storage-claim
  namespace: mailserver
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
```

### deployment.yaml

```
      volumes:
        - name: config
          configMap:
            name: mailserver.config
        - name: opendkim-keys
          secret:
            secretName: mailserver.opendkim.keys
        - name: data
          persistentVolumeClaim:
            claimName: local-mail-storage-claim
        - name: tmp-files
          emptyDir: {}
```

### Log Output

it looks so good :-)


> Dec  3 08:10:05 pod amavis[901]: (00901-01) ESMTP :10024 /var/lib/amavis/tmp/amavis-20201203T081005-00901-QST18qWr: <testuser@example.com> -> <testuser@example.com> SIZE=15638 BODY=8BITMIME Received: from smtp.example.com ([127.0.0.1]) by localhost (smtp.example.com [127.0.0.1]) (amavisd-new, port 10024) with ESMTP for <testuser@example.com>; Thu,  3 Dec 2020 08:10:05 +0000 (UTC)
> Dec  3 08:10:06 pod amavis[901]: (00901-01) Checking: reZIr_MEOf9x [10.244.1.1] <testuser@example.com> -> <testuser@example.com>
> Dec  3 08:10:06 pod amavis[901]: (00901-01) p004 1 Content-Type: multipart/mixed
> Dec  3 08:10:06 pod amavis[901]: (00901-01) p005 1/1 Content-Type: multipart/alternative
> Dec  3 08:10:06 pod amavis[901]: (00901-01) p001 1/1/1 Content-Type: text/plain, 7bit, size: 27, SHA1 digest: f248aa114c26563c3c7b4ace89029e00b0a4478a
> Dec  3 08:10:06 pod amavis[901]: (00901-01) p002 1/1/2 Content-Type: text/html, 7bit, size: 232, SHA1 digest: 3353047c46e80f04e6a30de7f7c4285980d81389
> Dec  3 08:10:06 pod amavis[901]: (00901-01) p003 1/2 Content-Type: application/vnd.oasis.opendocument.text, base64, size: 10398, SHA1 digest: 05559cbe7d783dcf4f3cecf1a2c89cafc2108280, name: Testfile.odt
> ...


### NFS - exports
```
/srv/nfs/kubedata    192.168.17.0/24(rw,insecure,sync,no_subtree_check,no_root_squash)
```
