### ISSUE TITLE
[HELP] Outlook periodically produces 0x800ccc0e

### ISSUE THREAD

**Issue by NothingWorksToday** [docker-mailserver/docker-mailserver#1772]
# Subject

I would like some feedback concerning a use case
I have questions about TLS/SSL/STARTTLS/OpenSSL

## Description

I run the mail-server on Ubuntu with docker-compose and it works fine most of the time. 
However Outlook stops synchronising folders from time to time, throwing error 0x800ccc0e (always the same).
When I open Thunderbird after this it cannot connect to server due to timeout.

I use IMAP via 993 / SSL and SMTP via 465 / SSL. Can anyone help me spot the mistake and fix it? 
Below is the mail.info log from the time the error occured - not sure if it's relevant though.

``` 
Jan 27 09:18:13 mail postfix/anvil[1072356]: statistics: max connection rate 2/60s for (smtps:84.132.155.10) at Jan 27 09:14:52
Jan 27 09:18:13 mail postfix/anvil[1072356]: statistics: max connection count 1 for (smtps:84.132.155.10) at Jan 27 09:14:17
Jan 27 09:18:13 mail postfix/anvil[1072356]: statistics: max cache size 1 at Jan 27 09:14:17
Jan 27 09:28:13 mail dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=52.125.138.0, lip=172.18.0.2, TLS: Connection closed, session=<ZP3sY965wBU0fYoA>
Jan 27 09:28:14 mail postfix/smtps/smtpd[1076353]: connect from unknown[52.125.138.0]
Jan 27 09:28:14 mail postfix/smtps/smtpd[1076353]: Anonymous TLS connection established from unknown[52.125.138.0]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Jan 27 09:28:14 mail postfix/smtps/smtpd[1076353]: lost connection after EHLO from unknown[52.125.138.0]
Jan 27 09:28:14 mail postfix/smtps/smtpd[1076353]: disconnect from unknown[52.125.138.0] ehlo=1 commands=1
Jan 27 09:31:34 mail postfix/anvil[1076360]: statistics: max connection rate 1/60s for (smtps:52.125.138.0) at Jan 27 09:28:14
Jan 27 09:31:34 mail postfix/anvil[1076360]: statistics: max connection count 1 for (smtps:52.125.138.0) at Jan 27 09:28:14
Jan 27 09:31:34 mail postfix/anvil[1076360]: statistics: max cache size 1 at Jan 27 09:28:14
Jan 27 09:32:46 mail dovecot: imap(mail1@example.com)<1071018><HHZJId650YJUhJsK>: Connection closed (IDLE running for 0.001 + waiting input for 1092.050 secs, 2 B in + 10 B out, state=wait-input) in=522 out=2537 deleted=0 expunged=0 trashed=0 hdr_count=1 hdr_bytes=410 body_count=0 body_bytes=0
Jan 27 09:32:48 mail dovecot: imap(mail1@example.com)<1069739><3CiUEd65mYJUhJsK>: Connection closed (IDLE running for 0.001 + waiting input for 1094.168 secs, 2 B in + 10 B out, state=wait-input) in=116 out=9583 deleted=0 expunged=0 trashed=0 hdr_count=2 hdr_bytes=368 body_count=2 body_bytes=5248
Jan 27 09:32:48 mail dovecot: imap(mail1@example.com)<1069897><7rd8E965oYJUhJsK>: Connection closed (IDLE running for 0.001 + waiting input for 1094.408 secs, 2 B in + 10 B out, state=wait-input) in=346  out=1811 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Jan 27 09:33:27 mail dovecot: imap(mail2@example.com)<1070773><sM9wHt65zYJUhJsK>: Connection closed (IDLE running for 0.001 + waiting input for 1260.938 secs, 2 B in + 10 B out, state=wait-input) in=501 out=5717 deleted=1 expunged=1 trashed=0 hdr_count=0 hdr_bytes=0 body_count=1 body_bytes=3447
```
## Edit
Right now, approx. 3 hours later it's working again. To me it sounds like a timing problem.

**Comment by aendeavor** [comment]
> I use IMAP via 993 / SSL and SMTP via 465 / SSL

Can you try with 587 for SMTPs?

**Comment by NothingWorksToday** [comment]
> **Literally** using Google with "Outllook 0x800ccc0e" yielded https://www.hostix.de/service/outlook-fehler-0x800ccc0e after **10 seconds**. Why would you take the time for this issue tracker when Google is so much faster? Put the text into a translator and you're good to go.
> 
> Is there anything you have **already** looked up about this that we can help you with?
> 
> PS: Double check your SSL/TLS configuration. Seems off.

Not sure if you read my description at all...
The "solution" you mention tells me to use SSL on port 993/465/587. Guess what I do? I use SSL on those ports. Surprise!

I used 587 before with STARTTLS  but wanted to switch to full SSL. Right now it works, so it cannot be a SSL problem. I'd like to know why it *sometimes* works and *sometimes* not, as i expect my mail server to be reliable.

**Comment by aendeavor** [comment]
According to

> Guess what I do? I use SSL on those ports.

You have checked that with  [drwetter/testssl.sh]( https://github.com/drwetter/testssl.sh) for example, or any other testing software, MxTools, something like that?

> I used 587 before with STARTTLS but wanted to switch to full SSL

What do you mean by "full SSL"?

> Right now it works, so it cannot be a SSL problem.

Wrong.

> i expect my mail server to be reliable.

It's only as reliable as the underlying configuration. Since other users are not reporting this, and SSL/TLS configuration is knows to cause problems among users, the chances for a wrong configuration are higher.

Nevertheless, if it's not, we need to find out. Since when does this occur?

**Comment by NothingWorksToday** [comment]
> You have checked that with [drwetter/testssl.sh](https://github.com/drwetter/testssl.sh) for example, or any other testing software, MxTools, something like that?

Yes, I used SSL Labs:
![image](https://user-images.githubusercontent.com/69650589/106018399-c1b8cb00-60c1-11eb-8932-0ffdced0c6d1.png)

I followed the [Wiki ](https://github.com/docker-mailserver/docker-mailserver/wiki/Configure-SSL#traefik) to let Traefik generate the SSL cert and import it into the mailserver. For reference see my config:

```
version: '3.0'

networks:
  external:
    external : true
  internal:
    external: false

services:
  cert-renewer-traefik:
    image: youtous/mailserver-traefik:latest
    container_name: cert-handler
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../traefik/letsencrypt/acme.json:/tmp/traefik/acme.json:ro # link traefik acme.json file (read-only)
    environment:
      - TRAEFIK_VERSION=2
      - CERTS_SOURCE=file
      - DOMAINS=mail.example.com
    networks:
      - internal

  mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "465:465"
      - "993:993"
    volumes:
      - ../traefik/letsencrypt/acme.json:/etc/letsencrypt/acme.json:ro
      - ../../data/mailserver/maildata:/var/mail
      - ../../data/mailserver/mailstate:/var/mail-state
      - ../../data/mailserver/maillogs:/var/log/mail
      - ../../data/mailserver/config/:/tmp/docker-mailserver/
      # ? if SELinux is enabled, uncomment the line below and comment the line above
      # - ./config/:/tmp/docker-mailserver/${SELINUX_LABEL}
    labels:
      - "mailserver-traefik.renew.domain=mail.example.com" # tag the service
      # traefik configuration using labels, not required
      - "traefik.enable=true" # use traefik v2 for certificate generation
      - "traefik.port=443" # dummy port, required generating certs with traefik
      - "traefik.http.routers.mail.rule=Host(`mail.example.com`)"
      - "traefik.http.routers.mail.entrypoints=https"
      - "traefik.http.routers.mail.tls=true"
      - "traefik.http.routers.mail.tls.certresolver=le"
      - "traefik.http.routers.mail.middlewares=redirect-webmail@docker,secHeaders@file" # redirect to webmail
      - "traefik.http.middlewares.redirect-webmail.redirectregex.regex=.*"
      - "traefik.http.middlewares.redirect-webmail.redirectregex.replacement=https://webmail.example.com/" # not needed but still here
    env_file:
      - mailserver.env
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
    networks:
      - internal
      - external
```

> 
> > I used 587 before with STARTTLS but wanted to switch to full SSL
> 
> What do you mean by "full SSL"?

If i understand the [Wiki](https://github.com/docker-mailserver/docker-mailserver/wiki/Understanding-the-ports#overview-of-email-ports) correctly (I'm no expert on this) port 465 uses Implicit TLS, so all communication is encrypted, while 587 uses Explicit TLS and starts in cleartext. So in my humble opinion it should be best to use 465.

> It's only as reliable as the underlying configuration. Since other users are not reporting this, and SSL/TLS configuration is known to cause problems among users, the chances for a wrong configuration are higher.

I absolutely agree on that! That's why I'm asking ;)

I'm new to mailservers, so pls let me know what configs, logs etc you need to spot my mistake.

**Comment by aendeavor** [comment]
> I'm new to mailservers, so pls let me know what configs, logs etc you need to spot my mistake.

Your config with Traefik seems fine to me, compared it to my own. I'm not 100% sure why you're using

> ``` YAML
> - "traefik.http.routers.mail.middlewares=redirect-webmail@docker,secHeaders@file" # redirect to webmail
> - "traefik.http.middlewares.redirect-webmail.redirectregex.regex=.*"
> - "traefik.http.middlewares.redirect-webmail.redirectregex.replacement=https://webmail.example.com/" # not needed but still here
> ```

What you're trying to achieve is to get a web-mailer on this domain as well. This can be done easier, since the ports for HTTP(S) will do the trick:

``` YAML
version: '3.9'

services:

  server:
    image: docker.io/mailserver/docker-mailserver:stable
    ...

  web:
    image: docker.io/roundcube/roundcubemail:1.4.10-apache
    networks: [ 'mail-proxy', 'generic-egress' ]
    environment:
      ROUNDCUBEMAIL_DEFAULT_HOST: tls://mail.itbsd.com
      ROUNDCUBEMAIL_SMTP_SERVER: tls://mail.itbsd.com
      ROUNDCUBEMAIL_SKIN: elastic
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 15s
      labels:
        - traefik.enable=true
        - traefik.docker.network=mail-proxy
        # ? Router
        - traefik.http.routers.webmailer.rule=Host(`mail.<NOPE>`)
        - traefik.http.routers.webmailer.entrypoints=https
        # ? TLS
        - traefik.http.routers.webmailer.tls=true
        - traefik.http.routers.webmailer.tls.options=modern@file
        - traefik.http.routers.webmailer.tls.certresolver=lcdns
        # ? Service
        - traefik.http.services.webmailer.loadbalancer.server.port=80

networks:
  ...

```

This is just an example.

---

I'd try this: Use 587 instead of 465 and try again. I'm almost certain it's related to the ports.

**Comment by aendeavor** [comment]
> I'm new to mailservers, so pls let me know what configs, logs etc you need to spot my mistake.

Your config with Traefik seems fine to me, compared it to my own. I'm not 100% sure why you're using

> ``` YAML
> - "traefik.http.routers.mail.middlewares=redirect-webmail@docker,secHeaders@file" # redirect to webmail
> - "traefik.http.middlewares.redirect-webmail.redirectregex.regex=.*"
> - "traefik.http.middlewares.redirect-webmail.redirectregex.replacement=https://webmail.example.com/" # not needed but still here
> ```

What you're trying to achieve is to get a web-mailer on this domain as well. This can be done easier, since the ports for HTTP(S) will do the trick:

``` YAML
version: '3.9'

services:

  server:
    image: docker.io/mailserver/docker-mailserver:stable
    ...

  web:
    image: docker.io/roundcube/roundcubemail:1.4.10-apache
    ...
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 15s
      labels:
        - traefik.enable=true
        - traefik.docker.network=mail-proxy
        # ? Router
        - traefik.http.routers.webmailer.rule=Host(`mail.<NOPE>`)
        - traefik.http.routers.webmailer.entrypoints=https
        # ? TLS
        - traefik.http.routers.webmailer.tls=true
        - traefik.http.routers.webmailer.tls.options=modern@file
        - traefik.http.routers.webmailer.tls.certresolver=lcdns
        # ? Service
        - traefik.http.services.webmailer.loadbalancer.server.port=80

networks:
  ...

```

This is just an example.

---

I'd try this: Use 587 instead of 465 and try again. I'm almost certain it's related to the ports.
