### ISSUE TITLE
[FR] Make path configurable using an ENV for generate-dkim-config

### ISSUE THREAD

**Issue by williamdes** [docker-mailserver/docker-mailserver#1775]
# Feature Request

https://github.com/docker-mailserver/docker-mailserver/blob/master/target/bin/generate-dkim-config

On LDAP setups the `/tmp/docker-mailserver` is not the one on the host.
Maybe the example is not right, because if I run the script following the example it will output files in the `/tmp/docker-mailserver`  but that is not the right folder because `/tmp/docker-mailserver` is mounted on a volume

```
docker-compose up -d mail

./setup.sh config dkim <key-size> <domain.tld>[,<domain2.tld>]
```

## Context

On a LDAP setup I want to generate my DKIM keys

### Is your Feature Request related to a Problem?

Maybe a problem

### Describe the Solution you'd like

Edit the readme or add an ENV to change the path

### Are you going to implement it?

no, not now

### What are you going to contribute??

no, not now

**Comment by williamdes** [comment]
To fix this I did
```
root@xxxxx:/home/desportes/infrastructure# ln -s /home/desportes/volumes/mails/config /tmp/docker-mailserver
root@xxxxx:/home/desportes/infrastructure# ls -lah /tmp/docker-mailserver
lrwxrwxrwx 1 root root 36 Jan 27 17:13 /tmp/docker-mailserver -> /home/desportes/volumes/mails/config
```

**Comment by aendeavor** [comment]
cc @wernerfred

**Comment by wernerfred** [comment]
Sorry @williamdes I'm not getting the point of your problem.
`/tmp/mailserver` is where the (custom) configuration lives which is mounted (if you follow the examples) to a directory on the host named `config`

If you configure your system different (doesn't get why your config should be valid for LDAP systems in general) then you have to deal with your special setup.

Give me an hint ;)

**Comment by williamdes** [comment]
```
docker run --rm -v /home/desportes/volumes/mails/config:/tmp/docker-mailserver -it docker.io/mailserver/docker-mailserver:edge generate-dkim-config 4096 domain1.tld,domain2.tld
```
This is the best working solution for now, setup.sh seems not to work

**Comment by williamdes** [comment]
My point is: local is not the same as in the container and the README explains how to setup everything assuming `/tmp/docker-mailserver` on your workstation is the same as in the running container.
This is not true on docker compose setups.

And `docker-compose up -d mail` seems useless in the command example provided, or maybe I did miss something big :thinking:

**Comment by aendeavor** [comment]
I'm not getting it either tbh, sorry :D

**Comment by aendeavor** [comment]
> This is the best working solution for now, setup.sh seems not to work

Very unlikely since tests are passing.

**Comment by wernerfred** [comment]
Now you are mixing things up. Let me provide you a guideline (only taken from the README):

1. Edit .env and mailserver.env accordingly
2. run docker-compose up -d (which will use the `docker-compose.yml` from the repo with the following content:
```
version: '3.8'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    env_file: mailserver.env
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/${SELINUX_LABEL}
    restart: always
    cap_add: [ "NET_ADMIN", "SYS_PTRACE" ]

volumes:
  maildata:
  mailstate:
  maillogs:
``` 

Keep an eye on this line:
```
 - ./config/:/tmp/docker-mailserver/${SELINUX_LABEL}
 ```

Current subdirectory config is mounted onto `/tmp/docker-mailserver` inside the container

3. If you use the `setup.sh` script it will create the content inside the container in `/tmp/docker-mailserver` which you can access on your current maschine inside directory `config`
