### ISSUE TITLE
[BUG] Cannot create dkim key other than default size

### ISSUE THREAD

**Issue by stsg** [docker-mailserver/docker-mailserver#1845]
# Bug Report

Cannot create dkim key other than default size.

## Context

**./setup.sh config dkim size 1024**

**Unknown options size 1024. Aborting.**

––– UNCHECKED ERROR
  – script    = setup.sh
  – function  = _docker_image / ${CRI}
  – line      = run
  – exit code = --rm

--------------
**./setup.sh config dkim 1024**

**Unknown options 1024 . Aborting.**

––– UNCHECKED ERROR
  – script    = setup.sh
  – function  = _docker_image / ${CRI}
  – line      = run
  – exit code = --rm

**Comment by aendeavor** [comment]
Is it actually that hard to **_use the issue template COMPLETELY_**? Why do you remove certain information, like the version of the mail server you're using? Now I have to waste time and ask.

The command is not `config dkim size` but `config dkim keysize`. Where did you find this? I just found one occurrence of the old `size` argument in the `setup.sh help` command and corrected it. Did you encounter it somewhere else?

**Comment by stsg** [comment]
Thank you )
I'm using docker compose with:
```
services:
  mail:
    image: docker.io/mailserver/docker-mailserver:latest
    # image: tvial/docker-mailserver:latest
    hostname: mail
    restart: always
    domainname: domainname.tld
    container_name: mail
    env_file: mailserver.env
    logging:
          driver: json-file
          options:
            max-size: "10m"
            max-file: "5"
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
    volumes:
      # - /etc/localtime:/etc/localtime:ro
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./etc/mail/:/tmp/docker-mailserver/${SELINUX_LABEL}
      - ./etc/ssl/:/etc/letsencrypt/
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

```
when execute from docker-compose directory directly:

``` 
docker exec mail open-dkim size 1024
```
or
```
docker exec mail open-dkim 1024
```
I will get:
```
Unknown options size 1024. Aborting.
```
or 
```
Unknown options 1024. Aborting.
```
