### ISSUE TITLE
Kubernetes docker-mailserver configuring dkim

### ISSUE THREAD

**Issue by rajsenthil** [docker-mailserver/docker-mailserver#1867]
# Subject
I would like to configure a not documented mail server use case

## Description
I have my kubernetes docker-mailserver running and could login with email client. 
I confirmed that the login is working from the log
`Mar 25 03:19:52 mailserver-5f4494fb94-tjgtr dovecot: imap-login: Login: user=<user1@example.com>, method=PLAIN, rip=172.17.0.1, lip=172.17.0.34, mpid=7375, TLS, session=<N7iF41O+SzSsEQAB>`

But getting the dkim error which is keep showing up at regular intervals
```
Mar 25 03:22:17 mailserver-5f4494fb94-tjgtr postfix/cleanup[6896]: 83A1772CAB6: message-id=<20210325032217.83A1772CAB6@example.com>
Mar 25 03:22:17 mailserver-5f4494fb94-tjgtr opendkim[196]: 83A1772CAB6: SSL error:0D06B08E:asn1 encoding routines:asn1_d2i_read_bio:not enough data
Mar 25 03:22:17 mailserver-5f4494fb94-tjgtr opendkim[196]: 83A1772CAB6: dkim_eom(): resource unavailable: d2i_PrivateKey_bio() failed
```
This issues is the same issue as [the one already reported](https://github.com/docker-mailserver/docker-mailserver/issues/1566)
I am trying to follow the documents and solutions posted to resolve this.

Using setup.sh I generated the dkim config with command 
`./setup.sh config dkim domain example.com`
and it generated private keys
`/tmp/docker-mailserver/opendkim/keys/example.com/mail.private`
and 
`/tmp/docker-mailserver/opendkim/keys/example.com/mail.txt`

The content of mail.txt is 
```
mail._domainkey IN      TXT     ( "v=DKIM1; h=sha256; k=rsa; "          "p=MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAt3gdw9pBc+mUIDBvwwNmXWRUbGK2k2SDNl4cGA/ZBjXV0ilvCDW6NQZOyH0UGmY14q4RhZLkUagGDY1UTh4ITDhmKyMeReypKM5dTcHal4SZR8Pj7jYic7LwyA9CVXgTZnhWJNCO+fDFjbH3B7YQRh8K+KwpkhF89EdcFtIpPniuex/s47sLM0l4rh8VLqddBAKruuy1Vyg8Wx"
          "PnCg6j6Nz/hx6mqNO8JV6zyhAbRXeIadOAUthGr9taiY7ntjKcq80cT8jHD0Gb1AJVzK/RGnkc5TUZ7taCfLBoejdXfOTOCaxYnoiKsPTlvUXIGpfwqLa+D8OhJCQAIABJN/XI6rkLSGmv9vnu4Zblg4qdM1S560ToEL5rPlfRzGvXEBswSERQVs69eZDJH4vdGdI/zHAPWa4U5oEfOb2Y0p2OpXbMOFseycL9alIEtDi5zxRoi/ts8Q+b"
          "la7yKgkjZC+o1MXnyMg+zIULsAN9mmV0gOJ6lNcrjlydbFqnQQnAvnunan8mY5L9kboLhZJW3mpTCmMzlginuc0tTH5bVoC24YZa3gICwnbd1uF7AJiCGVnBv2myCr5JD4RH0WHdzHojWtMgyI8LXPOoHPYIIJdq+nPXZtEoxA6fp92aHuyfftFuyQMb/LseqknepdIUoLNrtctqn3V9FuwY2o0Z9O321ycCAwEAAQ==" )  ; ----- DKIM key mail for example.com

```

The content of mail.private is a private ssh key type content.

Please let me know, how to resolve the dkim error.

**Comment by casperklein** [comment]
Just a shot in the dark: Default key size is 4096. You could try 2048 instead.

`./setup.sh config dkim keysize 2048`

**Comment by rajsenthil** [comment]
I am going through this page to configure the DKIM 

> Just a shot in the dark: Default key size is 4096. You could try 2048 instead.
> 
> `./setup.sh config dkim keysize 2048`

I tried to config with size 2048 and did not see any change. 
Following this [message](https://github.com/docker-mailserver/docker-mailserver/issues/1565) by an user who resolved a similar issue with steps
```
I fix my problem, just as a reference,

I had to manually create the path config/opendkim/keys/mydomain.com.
create an email account ./setup.sh email add user@domain
run ./setup config dkim
I can find the mail.txt file in config/opendkim/keys/mydomain.com

```
The folder structure `config/opendkim/keys/mydomain.com` is not what I see in kubernetes pod. 
It is currently in `/tmp/docker-mailserver/opendkim/`.

I will try that and see.

**Comment by casperklein** [comment]
> The folder structure config/opendkim/keys/mydomain.com is not what I see in kubernetes pod.

That is on the host

>It is currently in /tmp/docker-mailserver/opendkim/.

That is in the container

**Comment by rajsenthil** [comment]
> > The folder structure config/opendkim/keys/mydomain.com is not what I see in kubernetes pod.
> 
> That is on the host
> 
> > It is currently in /tmp/docker-mailserver/opendkim/.
> 
> That is in the container

I think the issue with opendkim is around this configuration copied from [wiki](https://github.com/docker-mailserver/docker-mailserver/wiki/Using-in-Kubernetes)

```
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mailserver.config
  namespace: mailserver
  labels:
    app: mailserver
data:
  postfix-accounts.cf: |
    user1@example.com|{SHA512-CRYPT}$6$2YpW1nYtPBs2yLYS$z.5PGH1OEzsHHNhl3gJrc3D.YMZkvKw/vp.r5WIiwya6z7P/CQ9GDEJDr2G2V0cAfjDFeAQPUoopsuWPXLk3u1

  postfix-virtual.cf: |
    alias1@example.com user1@dexample.com

  #dovecot.cf: |
  #  service stats {
  #    unix_listener stats-reader {
  #      group = docker
  #      mode = 0666
  #    }
  #    unix_listener stats-writer {
  #      group = docker
  #      mode = 0666
  #    }
  #  }

  SigningTable: |
    *@example.com mail._domainkey.example.com

  KeyTable: |
    mail._domainkey.example.com example.com:mail:/etc/opendkim/keys/example.com-mail.key

  TrustedHosts: |
    127.0.0.1
    localhost
 
  #user-patches.sh: |
  #  #!/bin/bash

  #fetchmail.cf: |

---
kind: Secret
apiVersion: v1
metadata:
  name: mailserver.opendkim.keys
  namespace: mailserver
  labels:
    app: mailserver
type: Opaque
data:
  example.com-mail.key: 'base64-encoded-DKIM-key'

---

```

I used is as it is without analyzing how it is used by the mailserver.
I have the secret key for `example.com-mail.key: 'bWFpbHNlcnZlcg=='` (base64 of mailserver). 
The rest of things remain as it is. 

Do I need this configmap or secrets, if I am using setup.sh to generate useraccounts and opendkim config? 

Thank you.
