### ISSUE TITLE
docker-compose mail configuration with nginx and letsencrypt 

### ISSUE THREAD

**Issue by allanext** [docker-mailserver/docker-mailserver#1875]
I've been using [https://github.com/evertramos/nginx-proxy-automation](https://github.com/evertramos/nginx-proxy-automation) for all my web docker containers and I'm finally moving also the mail service.

The issue is that I can't reach the service and I don't understand why. 
I've also noticed that SSL is not responding properly but not sure if it's related to another issue:
```
openssl s_client -showcerts -connect mail2.mydomain.com:465
CONNECTED(00000005)
4425047724:error:140040E5:SSL routines:CONNECT_CR_SRVR_HELLO:ssl handshake failure:/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-56.60.2/libressl-2.8/ssl/ssl_pkt.c:585:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Start Time: 1617135872
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
```
From the mail container I can ping outside and the nginx container can ping the mail container.

Netcat gives mixed results:
```
users-Mac-Pro:~ user$ nc -zv mail2.mydomain.com 465
Connection to mail2.mydomain.com port 465 [tcp/urd] succeeded!
users-Mac-Pro:~ user$ nc -zv mail2.mydomain.com 993
Connection to mail2.mydomain.com port 993 [tcp/imaps] succeeded!
users-Mac-Pro:~ user$ nc -zv mail2.mydomain.com 25
nc: connectx to mail2.mydomain.com port 25 (tcp) failed: Operation timed out
```

For configuring Letsencrypt I've followed the documentation on mailserver.env: [https://docker-mailserver.github.io/docker-mailserver/edge/config/security/ssl/](https://docker-mailserver.github.io/docker-mailserver/edge/config/security/ssl/) although a bit outdated

Here's my mail docker-compose:
```
version: '3.8'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:9.1.0
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    env_file: mailserver.env
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    networks: 
      - webproxy
    expose:
      - 25
      - 143
      - 465
      - 587
      - 993
    volumes:
      - ./maildata:/var/mail
      - ./mailstate:/var/mail-state
      - ./maillogs:/var/log/mail
      - /etc/localtime:/etc/localtime:ro
      - ./config/:/tmp/docker-mailserver/${SELINUX_LABEL}
      - /home/ec2-user/docker/nginx/data/certs:/etc/letsencrypt/live:ro
    restart: always
    cap_add: [ "NET_ADMIN", "SYS_PTRACE" ]
    environment:
      ENABLE_SPAMASSASSIN: 1
      SPAMASSASSIN_SPAM_TO_INBOX: 1
      ENABLE_CLAMAV: 1
      ENABLE_FAIL2BAN: 1
      ENABLE_POSTGREY: 1
      ENABLE_SASLAUTHD: 0
      ONE_DIR: 1
      DMS_DEBUG: 1
      VIRTUAL_HOST: $DOMAINS
      LETSENCRYPT_HOST: $DOMAINS
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL

networks:
  webproxy:
    external: true
```

.env file:
```
# –––––––––––––––––––––––––––––––––––––––––––––––
# ––– Docker Compose Settings Variables –––––––––
# –––––––––––––––––––––––––––––––––––––––––––––––

HOSTNAME=mail2
DOMAINNAME=mydomain.com
CONTAINER_NAME=container-mail
DOMAINS=mail2.mydomain.com
LETSENCRYPT_EMAIL=user@mydomain.com

# –––––––––––––––––––––––––––––––––––––––––––––––
# ––– SELinux Compose File Settings Variables –––
# ––– options: empty, '-z' or '-Z'  –––––––––––––
# –––––––––––––––––––––––––––––––––––––––––––––––

SELINUX_LABEL=
```

Finally the nginx docker-compose file: 

```
version: '3'
services:
  nginx-web:
    image: nginx:stable-alpine
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: ${NGINX_WEB:-nginx-web}
    restart: always
    ports:
      - "${IP:-0.0.0.0}:${DOCKER_HTTP:-80}:80"
      - "${IP:-0.0.0.0}:${DOCKER_HTTPS:-443}:443"
      - "${IP:-0.0.0.0}:25:25"
      - "${IP:-0.0.0.0}:993:993"
      - "${IP:-0.0.0.0}:465:465"
      - "${IP:-0.0.0.0}:587:587"
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
    logging:
      driver: ${NGINX_WEB_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_WEB_LOG_MAX_SIZE:-4m}
        max-file: ${NGINX_WEB_LOG_MAX_FILE:-10}

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup ${NGINX_WEB:-nginx-web} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: ${DOCKER_GEN:-nginx-gen}
    restart: always
    environment:
      SSL_POLICY: ${SSL_POLICY:-Mozilla-Intermediate}
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      driver: ${NGINX_GEN_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_GEN_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_GEN_LOG_MAX_FILE:-10}

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    container_name: ${LETS_ENCRYPT:-nginx-letsencrypt}
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: ${DOCKER_GEN:-nginx-gen}
      NGINX_PROXY_CONTAINER: ${NGINX_WEB:-nginx-web}
    logging:
      driver: ${NGINX_LETSENCRYPT_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_LETSENCRYPT_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_LETSENCRYPT_LOG_MAX_FILE:-10}

networks:
  default:
    external:
      name: ${NETWORK:-webproxy}
```

Apparently I can share the `nginx-letsencrypt` volume of created certificates with the mail container (/etc/letsencrypt/live), not sure if this helps.

Any idea on how I can better troubleshoot the issue?
Thank you!

**Comment by polarathene** [comment]
The documentation may be out of date yes. We just recently migrated it from Github Wiki, as it was not as easy to keep in sync with development in git. Troubleshooting the issue to identify where the docs can be improved would be great :)

I've personally only setup `docker-mailserver` locally with my own certs. This should work for `letsencrypt` in the same way. I'm not yet familiar with the specialized `letsencrypt` handling/support, but taking a more manual approach for now should at least let you verify it can be configured correctly, and we can go from there?

Use these env vars:

```yaml
volumes:
  - $PWD/path/to/certs:/tls:ro
environment:
  - SSL_TYPE=manual
  - SSL_CERT_PATH=/tls/certs/example.test.rsa.pem
  - SSL_KEY_PATH=/tls/private/example.test.rsa.key
```

You'll want to update the paths accordingly to what you're using. The `manual` type will reference the two other env vars to load your letsencrypt cert.

---

If this isn't working, my first guess will be the issue is related to your nginx proxy layer. I would advise trying the mail ports being directly exposed by the `docker-mailserver` image. Our docs don't show using mail ports through nginx like you've configured. Have you configured nginx to handle these ports properly?

Ports 993 and 465 are implicit TLS, they're similar to HTTPS 443. However ports 25, 587 and some others are explicit TLS via STARTTLS protocol, nginx won't be configured for such by default and might be why you're finding port 25 fails.

I'm not entirely sure with your first test response from openssl on 465, I assume the failure may be related to your nginx proxy. Unless configured to forward/passthrough the port TLS to the backing service, a reverse proxy like nginx will terminate TLS on arrival. This is fine for the usual web service, since you'd connect to port 80 over HTTP to your backend and public traffic through the proxy on port 443.

How is your nginx proxy configured to handle port 465 for example? If it's assuming it's just another TLS port for HTTPS, it may try to connect via port 80 which wouldn't work, or select a different port open as fallback that isn't matching port 465?

---

There isn't really any reason to put a reverse proxy in front for your mailserver, the typical reason for using a reverse-proxy is to respond to multiple domains, terminate the traffic on a common port like 443 for HTTPS and then connect the traffic to the desired service for that domain on a different port (since only one service can listen to a specific port, not everything can be on port 80 or 443 externally).

- Your DNS will connect a domain to an IP.
- `docker-mailserver` ports are all exclusive to mail, they shouldn't need to go through nginx.
-  You just need to automate your cert renewals with letsencrypt for the domains and provide them to `docker-mailserver` to use.
