### ISSUE TITLE
Wrong LDAP user query

### ISSUE THREAD

**Issue by netthier** [docker-mailserver/docker-mailserver#19]
Despite settings the LDAP_QUERY_FILTER_USER variable, docker-mailserver sends the wrong query string to my LDAP server.
```yaml
mailserver:
    image: mailserver/docker-mailserver
    container_name: mailserver
    hostname: mail
    domainname: domain.it
    environment:
      - ONE_DIR=1
      - ENABLE_LDAP=1
      - LDAP_SERVER_HOST=openldap
      - LDAP_SEARCH_BASE=dc=domain,dc=it
      - LDAP_BIND_DN=cn=admin,dc=domain,dc=it
      - LDAP_BIND_PW=secret
      - LDAP_QUERY_FILTER_USER=(&(objectClass=inetOrgPerson)(mail=%s))
      - LDAP_QUERY_FILTER_DOMAIN=(mail=*@%s)
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/le-ssl/letsencrypt/live/domain.it/cert.pem
      - SSL_KEY_PATH=/le-ssl/letsencrypt/live/domain.it/privkey.pem
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - /root/docker/mailserver/data:/var/mail
      - /root/docker/mailserver/state:/var/mail-state
      - /root/docker/swag/etc:/le-ssl:ro
    restart: unless-stopped
```
While starting up, the logs also show the correct query strings:
```
mailserver      |   >> /etc/postfix/ldap-domains.cf: query_filter = (mail=*@%s)
mailserver      |   >> /etc/postfix/ldap-domains.cf: query_filter_user = (&(objectClass=inetOrgPerson)(mail=%s))
```
However, when actually trying to log in (with the email server@domain.it, a valid LDAP user), my ldap server receives the following query:
```
openldap        | 6005afe8 conn=4224 op=6 SRCH base="dc=domain,dc=it" scope=2 deref=0 filter="(&(?objectClass=PostfixBookMailAccount)(uniqueIdentifier=server))"
```
Since there are no PostfixBookMailAccount users, the mailserver-docker tells me that this user is unknown.
Is my configuration wrong, or is this a mailserver bug?
