### ISSUE TITLE
Can't login mail server with ldap

### ISSUE THREAD

**Issue by KimPinot** [docker-mailserver/docker-mailserver#1929]
## Problem

I can't login mail server with ldap.
when I run `setup.sh email list` command it shows 'test@test.mail'.
but, I exec command `dovecot user '*'` in mail docker, It show noting.
also, I can't see anything users at A like following image
<img width="343" alt="image" src="https://user-images.githubusercontent.com/42037851/115698221-58ceaf80-a39f-11eb-859a-13b32b2109e6.png">

## Goal

- [ ] Can login with rainloop
- [ ] Send / Receive mail
- [ ] Can change password using by ldap-change-password@rainloop

## Tried thing

* Read and follow #1003
* Read doc Configure LDAP at wiki

## Images

* mail : mailserver/docker-mailserver:latest
* ldap : jsmitsnl/docker-openldap-postfix-book:latest
* Rainloop : hardware/rainloop:latest

### mail
```yaml
- hostname: mail
- domainname: test.mail
- container_name: mail
- ENABLE_SPAMASSASSIN : 1
- ENABLE_CLAMAV : 0
- ENABLE_FAIL2BAN : 1
- ENABLE_POSTGREY : 1
- ENABLE_SASLAUTHD : 1
- SASLAUTHD_LDAP_SERVER : 172.17.0.5 # ldap
- SASLAUTHD_LDAP_BIND_DN : cn=admin,dc=test,dc=mail
- SASLAUTHD_LDAP_PASSWORD : admin
- SASLAUTHD_LDAP_SEARCH_BASE : dc=test,dc=mail
- SASLAUTHD_LDAP_FILTER : (&(mail=%s)(objectClass=person))
- SASLAUTHD_MECHANISMS : ldap
- ENABLE_LDAP : 1
- LDAP_SERVER_HOST : 172.17.0.5 # ldap server
- LDAP_SEARCH_BASE : dc=test.mail
- LDAP_BIND_DN : cn=admin,dc=test,dc=mail
- LDAP_BIND_PW : admin
- LDAP_QUERY_FILTER_USER : (&(objectClass=user)(mail=%s))
- LDAP_QUERY_FILTER_GROUP : (&(objectclass=group)(mail=%s))
- LDAP_QUERY_FILTER_ALIAS : (&(objectClass=user)(otherMailbox=%s))
- LDAP_QUERY_FILTER_DOMAIN : (&(\|(mail=*@%s)(mailalias=*@%s)(mailGroupMember=*@%s))(mailEnabled=TRUE))
- ENABLE_POSTFIX_VIRTUAL_TRANSPORT : 1
- POSTFIX_DAGENT : POSTFIX_DAGENT
- DOVECOT_PASS_FILTER : (&(objectClass=mailAccount)(mail=%n))
- DOVECOT_USER_FILTER : (&(objectClass=mailAccount)(mail=%n))
```

### ldap
```yaml
- LDAP_ADMIN_PASSWORD : admin
- LDAP_ORGANISATION : mail
- LDAP_DOMAIN : test.mail
- LDAP_LOG_LEVEL : 1
```

I'm not sure what I do test and look for this issue. Any help or Question will be greatly appreciated and helpful.

**Comment by KimPinot** [comment]
added some log.

```
Apr 22 13:43:59 mail dovecot: auth: ldap(test@test.mail,0.0.0.0,<vEcW34/AloAPpJbQ>): unknown user (SHA1 of given password: 8cb223)
Apr 22 13:44:01 mail dovecot: imap-login: Disconnected (auth failed, 1 attempts in 2 secs): user=<test@test.mail>, method=PLAIN, rip= 0.0.0.0, lip=172.17.0.4, TLS, session=<vEcW34/AloAPpJbQ>
```

**Comment by reneploetz** [comment]
From your screenshot it appears you did not configure any users in LDAP.

Please note that this image will not add any users to LDAP directly nor does it allow to manage them directly. You cannot use the setup.sh command, but have to use an LDAP manager (like the one in your screenshot) to manage any users or aliases. 

---

Your configuration should also omit "SASLAUTHD_LDAP_FILTER" / "LDAP_QUERY_FILTER_USER" / "LDAP_QUERY_FILTER_GROUP" / "LDAP_QUERY_FILTER_ALIAS" / "LDAP_QUERY_FILTER_DOMAIN" as the LDAP schema of that image uses the default values used in this image.

The default setup here should work just fine if you use the postfix book schema: https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md#examples (scroll down to "LDAP setup")

**Comment by KimPinot** [comment]
Thanks. I will reply ASAP!

**Comment by KimPinot** [comment]
<img width="672" alt="image" src="https://user-images.githubusercontent.com/42037851/116331145-1a574b80-a80a-11eb-9c0a-57ff9899e3a2.png">

I'm sorry for the late reply.
As you told me, I am trying to add LDAP users using PostfixBookMailAccount Object, but it is not progressing due to the error below.
Is there anything you can point out?

```
You tried to perform an operation that would cause an undefined attribute to exist or that would remove a required attribute, given the current list of ObjectClasses. This can also occur if you do not specify a structural objectClass when creating an entry, or if you specify more than one structural objectClass.
```

**Comment by reneploetz** [comment]
I don't know the specific program well enough to comment on its usage.

According to the schema: https://github.com/docker-mailserver/docker-mailserver/blob/master/test/docker-openldap/bootstrap/schema/mmc/postfix-book.schema

```
objectclass ( 1.3.6.1.4.1.29426.1.2.2.1 NAME 'PostfixBookMailAccount'
        SUP top AUXILIARY
	DESC 'Mail account used in Postfix Book'
	MUST ( mail )
        MAY ( mailHomeDirectory $ mailAlias $ mailGroupMember
		$ mailUidNumber $ mailGidNumber $ mailEnabled
		$ mailQuota $mailStorageDirectory ) )
```

You did not specify "mail" according to the screenshot, but used "Email" instead. Can you check if this is not some kind of UI issue?

**Comment by KimPinot** [comment]
Thanks. I'll check and reply.

**Comment by KimPinot** [comment]
I'm using phpLDAPadmin as 'osixia/phpldapadmin:latest (ldap : 1.2.5)'.

I've tried to reinstall more than two times.
However, the results are equally set. I don't think it's just a UI issue.

<img width="564" alt="스크린샷 2021-05-01 03 17 52" src="https://user-images.githubusercontent.com/42037851/116737151-d17edd00-aa2b-11eb-858e-7a43be738ae0.png">

**Comment by MaEchallier** [comment]
Hello, I'm not really sure what you want to do, but if I understood correctly, you want to create an user : PosixAccount with attribute of PostfixBookMailAccount with PHPLDAPadmin.  

You must have already import LDIF file of PostfixBookMail schema.

In this case you need to create an user with PosixAccount first : 

<img width="1062" alt="Create Posix Account" src="https://user-images.githubusercontent.com/83538830/116812006-ac35c000-ab4c-11eb-8db7-28e9b07e4e39.png">

After this is done, go to your fresh new user, scroll down to the "objectClass" section and go for add value like this : 

<img width="676" alt="Capture d’écran 2021-05-02 à 13 48 26" src="https://user-images.githubusercontent.com/83538830/116812092-223a2700-ab4d-11eb-8645-a68d22cd89dd.png">

Now select your desired value, in my case it's PostfixBookMailAccount, and in the next window add email to bind to the user

<img width="1026" alt="Capture d’écran 2021-05-02 à 13 49 05" src="https://user-images.githubusercontent.com/83538830/116812142-7fce7380-ab4d-11eb-9d5b-1cd8eb02872a.png">

Now you can add all desired attributes to the user in "Add new attributes" section

I hope my answer gonna help you, keep me in touch if you need more help with LDAP

**Comment by KimPinot** [comment]
Your detailed help helped me a lot. Thank you.

However, as you told me, I wrote it as below, and these logs are printed out and I can't log in properly.
Is there anything can guess?

### group schema
<img width="559" alt="스크린샷 2021-05-07 00 53 43" src="https://user-images.githubusercontent.com/42037851/117328523-adf5df80-aece-11eb-8737-a3cee31168cf.png">

### user schema
`cn=test,cn=people,dc=fancy,dc=domain`

<img width="617" alt="image" src="https://user-images.githubusercontent.com/42037851/117328312-77b86000-aece-11eb-933c-3bdedae21dfc.png">
<img width="620" alt="스크린샷 2021-05-07 00 52 22" src="https://user-images.githubusercontent.com/42037851/117328324-7d15aa80-aece-11eb-86df-504d956dc361.png">

### error log
```
60940fd3 conn=1561 op=11 SEARCH RESULT tag=101 err=0 nentries=1 text=,
60940fd3 conn=1561 op=12 SRCH base="cn=people,dc=test,dc=domain” scope=2 deref=0 filter="(&(objectClass=PostfixBookMailAccount)(cn=test))",
60940fd3 conn=1561 op=12 SRCH attr=mailHomeDirectory mailUidNumber mailGidNumber mailStorageDirectory,
60940fd3 <= bdb_equality_candidates: (cn) not indexed
```

**Comment by MaEchallier** [comment]
Try to retrieve users with a filter like that : 
`- LDAP_QUERY_FILTER_USER=(&(objectClass=inetOrgPerson)(mail=%s))`

**Comment by KimPinot** [comment]
@MaEchallier Thank you for your help.
I don't think the method you explained doesn't apply because I'm using the relevant openLDAP in the docker.

**Comment by KimPinot** [comment]
Add Content:
The index part was not done, but the query change part seems to be correct. Thank you again @MaEchallier.
As you can see in the log below, the query seems to be looking for variables named `uniqueIdentifier` and `userPassword`. Is there anyone who knows the schema that includes this?
```
60982734 conn=1023 op=0 RESULT tag=97 err=0 text=,
60982734 conn=1023 op=1 SEARCH RESULT tag=101 err=0 nentries=0 text=,
60982734 conn=1023 op=1 SRCH attr=uniqueIdentifier userPassword,
60982734 conn=1023 op=1 SRCH base="cn=people,dc=domain,dc=awesome" scope=2 deref=0 filter="(&(objectClass=inetOrgPerson)(mail=test))"
```

**Comment by KimPinot** [comment]
@MaEchallier, I really appreciate your help.
However, when I ran the query from phpLDAPAdmin to mail=test (as test user), it showed no information. Am I doing exactly what I'm doing?

<img width="916" alt="image" src="https://user-images.githubusercontent.com/42037851/117583401-e3eeca00-b141-11eb-8a4c-4dd8dd56d696.png">

**Comment by reneploetz** [comment]
The log message "SEARCH RESULT tag=101 err=0 nentries=1" means that you got 1 query result for "(&(objectClass=PostfixBookMailAccount)(cn=test))"
The indexing issue is somewhat irrelevant as this is just a performance issue - the results will not be affected.
For querying the mail attribute to work, you would need the field content (= mail address), so "mail=test@domain" would be needed.

Can you provide more details on your current issues? I assume you have issues logging into dovecot? Or do you also have issues when you try to send a mail via postfix, e.g. you cannot you use SMTP?
Can you provide a log for the LDAP server when that happens?

It would also help others if you can provide your values for:
- LDAP_SEARCH_BASE
- LDAP_QUERY_FILTER_USER
- LDAP_QUERY_FILTER_GROUP
- LDAP_QUERY_FILTER_DOMAIN
- DOVECOT_PASS_ATTRS
- DOVECOT_PASS_FILTER
- DOVECOT_USER_ATTRS
- DOVECOT_USER_FILTER

**Comment by KimPinot** [comment]
@reneploetz Thanks for your help.
I am currently working on webmail login using rainloop and ldap-change-password plug-in. I haven't applied to a separate mail client, and only the message 'Authentication failed' is always printed out.

Also, I am sending you my env together.
```yaml
- LDAP_SEARCH_BASE : cn=people,dc=domain,dc=awesome
- LDAP_QUERY_FILTER_USER : (&(mail=%s)(mailEnabled=TRUE))
- LDAP_QUERY_FILTER_GROUP : (&(mailGroupMember=%s)(mailEnabled=TRUE))
- LDAP_QUERY_FILTER_DOMAIN : (|(&(mail=*@%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE))(&(mailGroupMember=*@%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE))(&(mailalias=*@%s)(objectClass=PostfixBookMailForward)))
- DOVECOT_PASS_ATTRS : null
- DOVECOT_PASS_FILTER : (&(objectClass=inetOrgPerson)(mail=%n))
- DOVECOT_USER_ATTRS : null
- DOVECOT_USER_FILTER : (&(objectClass=inetOrgPerson)(mail=%n))
```
