### ISSUE TITLE
Error in configuration file /etc/dovecot/dovecot-ldap.conf.ext line 12: Invalid boolean

### ISSUE THREAD

**Issue by clayrisser** [docker-mailserver/docker-mailserver#1935]
# Bug Report

## Context

I am getting the following error when using ldap.

```
Error in configuration file /etc/dovecot/dovecot-ldap.conf.ext line 12: Invalid boolean
```

The `/etc/dovecot/dovecot-ldap.conf.ext` file contains the following

```
base = ou=people,dc=example,dc=org
default_pass_scheme = 
dn = cn=admin,dc=example,dc=org
dnpass = SHHHHH
uris = ldaps://siliconhills-ldap-openldap-openldap-stack-ha.siliconhills-ldap.svc.cluster.local:636
tls = no
ldap_version = 3
pass_attrs = 
pass_filter = (&(objectClass=PostfixBookMailAccount)(uid=%n))
user_attrs = 
user_filter = (&(objectClass=PostfixBookMailAccount)(uid=%n))
auth_bind = 
```

### What is affected by this bug?

Connecting to the SMTP and IMAP server.

### When does this occur?

This happens when I try and connect from telnet or another other valid email client.

I'm using the `edge` release because I need to use the `ldaps` protocol.

### How do we replicate the issue?

Deploy the helm chart with the equivalent settings.

```
    configMap:
      useExisting: true
    demoMode:
      enabled: false
    deployment:
      replicas: 1
    domains:
    - v8.mail.siliconhills.dev
    haproxy:
      enabled: false
    image:
      name: mailserver/docker-mailserver
      pullPolicy: Always
      tag: edge
    initContainer:
      image:
        name: busybox
        pullPolicy: Always
        tag: "1.28"
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
    monitoring:
      pod:
        path: /metrics
        port: "9102"
        probe: "false"
        scrape: "true"
      service:
        path: /metrics
        port: "9102"
        probe: "false"
        scrape: "true"
    persistence:
      annotations: {}
      size: 1Gi
    pod:
      dockermailserver:
        default_relay_host: null
        dms_debug: 1
        dovecot_pass_attr: ""
        dovecot_pass_filter: (&(objectClass=PostfixBookMailAccount)(uid=%n))
        dovecot_user_attr: ""
        dovecot_user_filter: (&(objectClass=PostfixBookMailAccount)(uid=%n))
        enable_clamav: 0
        enable_dovecot_replication: true
        enable_fail2ban: 0
        enable_fetchmail: 0
        enable_ldap: "1"
        enable_managesieve: 0
        enable_pop3: 0
        enable_postfix_virtual_transport: null
        enable_postgrey: 0
        enable_saslauthd: 1
        enable_spamassassin: 0
        enable_srs: 0
        fetchmail_poll: 300
        hostNetwork: false
        hostPID: false
        ldap_bind_dn: cn=admin,dc=example,dc=org
        ldap_bind_pw: OBMjdgQO3D911VSGFhSmiby2
        ldap_query_filter_alias: (|(&(mailAlias=%s)(objectClass=PostfixBookMailForward))(&(mailAlias=%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE)))
        ldap_query_filter_domain: (|(&(mail=*@%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE))(&(mailGroupMember=*@%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE))(&(mailalias=*@%s)(objectClass=PostfixBookMailForward)))
        ldap_query_filter_group: (&(mailGroupMember=%s)(mailEnabled=TRUE))
        ldap_query_filter_user: (&(mail=%s)(mailEnabled=TRUE))
        ldap_search_base: ou=people,dc=example,dc=org
        ldap_server_host: ldaps://siliconhills-ldap-openldap-openldap-stack-ha.siliconhills-ldap.svc.cluster.local:636
        one_dir: 1
        override_hostname: v8.mail.siliconhills.dev
        permit_docker: host
        pflogsumm_recipient: null
        pflogsumm_trigger: null
        postfix_dagent: null
        postfix_mailbox_size_limit: null
        postfix_message_size_limit: null
        postgrey_auto_whitelist_clients: 5
        postgrey_delay: 300
        postgrey_max_age: 35
        postgrey_text: Delayed by postgrey
        postmaster_address: postmaster@v8.mail.siliconhills.dev
        postscreen_action: enforce
        relay_host: null
        relay_password: null
        relay_port: 25
        relay_user: null
        report_interval: null
        report_recipient: 0
        report_sender: null
        sa_kill: 6.31
        sa_spam_subject: '***SPAM***'
        sa_tag: 2
        sa_tag2: 6.31
        sasl_passwd: null
        saslauthd_ldap_bind_dn: cn=admin,dc=example,dc=org
        saslauthd_ldap_filter: (&(uid=%u)(mailEnabled=TRUE))
        saslauthd_ldap_password: SHHHHHHHH
        saslauthd_ldap_search_base: ou=people,dc=example,dc=org
        saslauthd_ldap_server: ldaps://siliconhills-ldap-openldap-openldap-stack-ha.siliconhills-ldap.svc.cluster.local:636
        saslauthd_ldap_ssl: 1
        saslauthd_mech_options: ""
        saslauthd_mechanisms: ldap
        smtp_only: ""
        spoof_protection: 0
        srs_domainname: v8.mail.siliconhills.dev
        srs_exclude_domains: ""
        srs_secret: P@ssw0rd
        ssl_cert_path: /tmp/ssl/tls.crt
        ssl_key_path: /tmp/ssl/tls.key
        ssl_type: manual
        strategy:
          type: Recreate
        tls_level: intermediate
        virusmails_delete_delay: "7"
    poorMansK8sLb:
      enabled: false
    psp:
      create: true
    rainloop:
      container:
        port: 8888
      enabled: true
      image:
        name: hardware/rainloop
        pullPolicy: Always
        strategy:
          type: Recreate
        tag: 1.13.0
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: "true"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
        enabled: true
        hosts:
        - v8.mail.siliconhills.dev
        path: /
        tls:
        - hosts:
          - v8.mail.siliconhills.dev
          secretName: tmp-mailserver-mailserver-rainloop-letsencrypt
      persistence:
        annotations: {}
        size: 1Gi
      service:
        port: 80
      serviceAccount:
        create: true
        name: rainloop
    rblRejectDomains: []
    resources:
      limits:
        cpu: "2"
        memory: 2048Mi
      requests:
        cpu: "1"
        memory: 1536Mi
    secret:
      useExisting: true
    service:
      annotations: {}
      loadBalancer:
        allowedIps:
        - 0.0.0.0/0
        hostName: v8.mail.siliconhills.dev
      nodePort:
        imap: 30143
        imaps: 30993
        pop3: 30110
        pop3s: 30995
        smtp: 30025
        smtps: 30465
        submission: 30587
      type: ClusterIP
    serviceAccount:
      create: "true"
    spfTestsDisabled: true
    ssl:
      existingName: tmp-mailserver-mailserver-rainloop-letsencrypt
      useExisting: true
```

I'm using the following branch `docker-mailserver-0.3.0` of the helm chart.

### Actual Behavior

Telnet and other clients fail to connect

```
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3031 bytes and written 396 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
read:errno=0
```

The server throws the following error log.

```
Error in configuration file /etc/dovecot/dovecot-ldap.conf.ext line 12: Invalid boolean
```

### Expected Behavior

I expect it to connect with no errors.

### Environment Variables

```CFG
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_587_TCP_ADDR=10.43.251.197
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_995_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT_HTTPS=443
POSTGREY_DELAY=300
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_4190_TCP=tcp://10.43.251.197:4190
DEFAULT_RELAY_HOST=
KUBERNETES_SERVICE_PORT=443
TLS_LEVEL=intermediate
POSTSCREEN_ACTION=enforce
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_465_TCP_ADDR=10.43.251.197
POSTFIX_INET_PROTOCOLS=all
ENABLE_SRS=0
ENABLE_LDAP=1
SPOOF_PROTECTION=0
RELAY_PASSWORD=
ENABLE_MANAGESIEVE=0
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_110_TCP_ADDR=10.43.251.197
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_4190_TCP_PORT=4190
ENABLE_POSTGREY=0
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_RAINLOOP_PORT_80_TCP=tcp://10.43.200.184:80
REPORT_SENDER=mailserver-report@v8.mail.siliconhills.dev
HOSTNAME=tmp-mailserver-mailserver-docker-mailserver-9b7d86c6b-p9hr4
ENABLE_QUOTAS=1
ENABLE_SASLAUTHD=1
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_SERVICE_PORT_TCP_IMAPS_RAINLOOP=10993
DOVECOT_LDAP_VERSION=3
NETWORK_INTERFACE=eth0
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_465_TCP=tcp://10.43.251.197:465
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_587_TCP_PROTO=tcp
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_RAINLOOP_PORT_80_TCP_ADDR=10.43.200.184
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_995_TCP_PORT=995
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_RAINLOOP_SERVICE_PORT_HTTP=80
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_SERVICE_PORT_TCP_SMTPS=465
DMS_DEBUG=1
SRS_EXCLUDE_DOMAINS=
LDAP_SEARCH_BASE=ou=people,dc=example,dc=org
SSL_CERT_PATH=/tmp/ssl/tls.crt
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_SERVICE_PORT_TCP_POP3=110
LDAP_QUERY_FILTER_USER=(&(mail=%s)(mailEnabled=TRUE))
SASLAUTHD_LDAP_BIND_DN=cn=admin,dc=example,dc=org
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_993_TCP_PORT=993
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_4711_TCP_PORT=4711
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_143_TCP_ADDR=10.43.251.197
SPAMASSASSIN_SPAM_TO_INBOX_IS_SET=
RELAY_HOST=
LDAP_QUERY_FILTER_ALIAS=(|(&(mailAlias=%s)(objectClass=PostfixBookMailForward))(&(mailAlias=%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE)))
PWD=/
SA_SPAM_SUBJECT=***SPAM***
LDAP_SERVER_HOST=ldaps://siliconhills-ldap-openldap-openldap-stack-ha.siliconhills-ldap.svc.cluster.local:636
DOVECOT_MAILBOX_FORMAT=maildir
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_25_TCP_PORT=25
SA_TAG2=6.31
REPORT_INTERVAL=
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_4190_TCP_PROTO=tcp
SASL_PASSWD=
POSTFIX_MAILBOX_SIZE_LIMIT=0
SMTP_ONLY=0
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_110_TCP=tcp://10.43.251.197:110
DOVECOT_DEFAULT_PASS_SCHEME=
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_10993_TCP_PORT=10993
ENABLE_POSTFIX_VIRTUAL_TRANSPORT=
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_993_TCP_PROTO=tcp
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_RAINLOOP_SERVICE_HOST=10.43.200.184
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_995_TCP_ADDR=10.43.251.197
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_110_TCP_PORT=110
SSL_KEY_PATH=/tmp/ssl/tls.key
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_10993_TCP_ADDR=10.43.251.197
ONE_DIR=1
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_SERVICE_PORT_TCP_SMTP=25
RELAY_USER=
HOME=/root
SASLAUTHD_LDAP_SERVER=ldaps://siliconhills-ldap-openldap-openldap-stack-ha.siliconhills-ldap.svc.cluster.local:636
KUBERNETES_PORT_443_TCP=tcp://10.43.0.1:443
LDAP_START_TLS=no
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_10993_TCP_PROTO=tcp
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_4711_TCP_PROTO=tcp
SASLAUTHD_LDAP_FILTER=(&(uid=%u)(mailEnabled=TRUE))
OVERRIDE_HOSTNAME=v8.mail.siliconhills.dev
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_SERVICE_PORT_TCP_SUBMISSION=587
LDAP_BIND_DN=cn=admin,dc=example,dc=org
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_SERVICE_PORT_TCP_DSYNC=4711
RELAY_PORT=25
SA_KILL=6.31
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_993_TCP_ADDR=10.43.251.197
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_993_TCP=tcp://10.43.251.197:993
ENABLE_FETCHMAIL=0
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_10993_TCP=tcp://10.43.251.197:10993
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_SERVICE_HOST=10.43.251.197
FETCHMAIL_POLL=300
ENABLE_AMAVIS=1
LDAP_BIND_PW=OBMjdgQO3D911VSGFhSmiby2
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_587_TCP_PORT=587
MOVE_SPAM_TO_JUNK=1
POSTMASTER_ADDRESS=postmaster@v8.mail.siliconhills.dev
POSTFIX_MESSAGE_SIZE_LIMIT=10240000
FETCHMAIL_PARALLEL=0
SA_TAG=2
LDAP_QUERY_FILTER_GROUP=(&(mailGroupMember=%s)(mailEnabled=TRUE))
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_465_TCP_PROTO=tcp
DOVECOT_USER_FILTER=(&(objectClass=PostfixBookMailAccount)(uid=%n))
TERM=xterm-256color
ENABLE_FAIL2BAN=false
DOVECOT_AUTH_BIND=
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_143_TCP_PORT=143
SASLAUTHD_LDAP_SSL=1
LOGWATCH_INTERVAL=none
POSTGREY_MAX_AGE=35
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_SERVICE_PORT=25
SRS_DOMAINNAME=v8.mail.siliconhills.dev
ENABLE_POP3=0
PFLOGSUMM_SENDER=mailserver-report@v8.mail.siliconhills.dev
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_25_TCP_ADDR=10.43.251.197
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_4711_TCP=tcp://10.43.251.197:4711
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_4190_TCP_ADDR=10.43.251.197
DOVECOT_TLS=no
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_SERVICE_PORT_TCP_IMAP=143
POSTGREY_AUTO_WHITELIST_CLIENTS=5
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_25_TCP=tcp://10.43.251.197:25
SHLVL=1
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_110_TCP_PROTO=tcp
PFLOGSUMM_TRIGGER=none
KUBERNETES_PORT_443_TCP_PROTO=tcp
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_SERVICE_PORT_TCP_MANAGESIEVE=4190
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_SERVICE_PORT_TCP_POP3S=995
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_465_TCP_PORT=465
POSTGREY_TEXT=Delayed by postgrey
KUBERNETES_PORT_443_TCP_ADDR=10.43.0.1
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_RAINLOOP_PORT_80_TCP_PORT=80
SRS_SENDER_CLASSES=envelope_sender
FAIL2BAN_BLOCKTYPE=drop
DOVECOT_PASS_ATTRS=
DOVECOT_PASS_FILTER=(&(objectClass=PostfixBookMailAccount)(uid=%n))
SSL_TYPE=manual
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_SERVICE_PORT_TCP_IMAPS=993
PERMIT_DOCKER=host
SRS_SECRET=P@ssw0rd
REPORT_RECIPIENT=postmaster@v8.mail.siliconhills.dev
KUBERNETES_SERVICE_HOST=10.43.0.1
KUBERNETES_PORT=tcp://10.43.0.1:443
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_4711_TCP_ADDR=10.43.251.197
KUBERNETES_PORT_443_TCP_PORT=443
POSTFIX_DAGENT=
VIRUSMAILS_DELETE_DELAY=7
SASLAUTHD_LDAP_SEARCH_BASE=ou=people,dc=example,dc=org
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_RAINLOOP_SERVICE_PORT=80
SASLAUTHD_MECH_OPTIONS=
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_995_TCP=tcp://10.43.251.197:995
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SUPERVISOR_LOGLEVEL=warn
SASLAUTHD_MECHANISMS=ldap
DOVECOT_USER_ATTRS=
ENABLE_SPAMASSASSIN=0
SPAMASSASSIN_SPAM_TO_INBOX=0
SASLAUTHD_LDAP_PASSWORD=SHHHHHHHHHH
ENABLE_CLAMAV=0
LOGROTATE_INTERVAL=daily
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT=tcp://10.43.251.197:25
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_25_TCP_PROTO=tcp
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_143_TCP=tcp://10.43.251.197:143
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_RAINLOOP_PORT=tcp://10.43.200.184:80
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_143_TCP_PROTO=tcp
LDAP_QUERY_FILTER_DOMAIN=(|(&(mail=*@%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE))(&(mailGroupMember=*@%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE))(&(mailalias=*@%s)(objectClass=PostfixBookMailForward)))
PFLOGSUMM_RECIPIENT=postmaster@v8.mail.siliconhills.dev
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_PORT_587_TCP=tcp://10.43.251.197:587
TMP_MAILSERVER_MAILSERVER_DOCKER_MAILSERVER_RAINLOOP_PORT_80_TCP_PROTO=tcp
_=/usr/bin/env
```

### Relevant Stack Traces

```
Apr 29 20:01:04 tmp-mailserver-mailserver-docker-mailserver-9b7d86c6b-p9hr4 dovecot: imap-login: Warning: Timeout leak: 0x7f4967d39730 (auth-server-connection.c:397)
Thu, Apr 29 2021 3:01:35 pm | Apr 29 20:01:34 tmp-mailserver-mailserver-docker-mailserver-9b7d86c6b-p9hr4 postfix/postscreen[2100]: warning: haproxy read: time limit exceeded
Thu, Apr 29 2021 3:01:57 pm | Apr 29 20:01:56 tmp-mailserver-mailserver-docker-mailserver-9b7d86c6b-p9hr4 postfix/postscreen[2100]: warning: haproxy read: time limit exceeded
Thu, Apr 29 2021 3:02:12 pm | Apr 29 20:02:11 tmp-mailserver-mailserver-docker-mailserver-9b7d86c6b-p9hr4 postfix/submission/smtpd[2348]: warning: haproxy read: timeout error
Thu, Apr 29 2021 3:02:12 pm | Apr 29 20:02:11 tmp-mailserver-mailserver-docker-mailserver-9b7d86c6b-p9hr4 postfix/submission/smtpd[2348]: connect from unknown[unknown]
Thu, Apr 29 2021 3:02:12 pm | Apr 29 20:02:11 tmp-mailserver-mailserver-docker-mailserver-9b7d86c6b-p9hr4 postfix/submission/smtpd[2348]: disconnect from unknown[unknown] commands=0/0
Thu, Apr 29 2021 3:02:29 pm | Apr 29 20:02:28 tmp-mailserver-mailserver-docker-mailserver-9b7d86c6b-p9hr4 dovecot: auth: Fatal: ldap /etc/dovecot/dovecot-ldap.conf.ext: Error in configuration file /etc/dovecot/dovecot-ldap.conf.ext line 12: Invalid boolean:
Thu, Apr 29 2021 3:02:29 pm | Apr 29 20:02:28 tmp-mailserver-mailserver-docker-mailserver-9b7d86c6b-p9hr4 dovecot: master: Error: service(auth): command startup failed, throttling for 8 secs
Thu, Apr 29 2021 3:02:29 pm | Apr 29 20:02:28 tmp-mailserver-mailserver-docker-mailserver-9b7d86c6b-p9hr4 dovecot: imap-login: Disconnected: Auth process broken (disconnected before auth was ready, waited 0 secs): user=<>, rip=10.42.3.0, lip=10.42.5.68, session=<Ps2V+SHBGK0KKgMA>
Thu, Apr 29 2021 3:02:29 pm | Apr 29 20:02:28 tmp-mailserver-mailserver-docker-mailserver-9b7d86c6b-p9hr4 dovecot: imap-login: Warning: Timeout leak: 0x7f28522fd730 (auth-server-connection.c:397)
Thu, Apr 29 2021 3:02:44 pm | Apr 29 20:02:43 tmp-mailserver-mailserver-docker-mailserver-9b7d86c6b-p9hr4 dovecot: auth: Fatal: ldap /etc/dovecot/dovecot-ldap.conf.ext: Error in configuration file /etc/dovecot/dovecot-ldap.conf.ext line 12: Invalid boolean:
Thu, Apr 29 2021 3:02:44 pm | Apr 29 20:02:43 tmp-mailserver-mailserver-docker-mailserver-9b7d86c6b-p9hr4 dovecot: master: Error: service(auth): command startup failed, throttling for 16 secs
Thu, Apr 29 2021 3:02:44 pm | Apr 29 20:02:43 tmp-mailserver-mailserver-docker-mailserver-9b7d86c6b-p9hr4 dovecot: imap-login: Disconnected: Auth process broken (disconnected before auth was ready, waited 0 secs): user=<>, rip=143.110.235.158, lip=10.42.5.68, TLS handshaking, session=<3t96+iHBmoePbuue>
Thu, Apr 29 2021 3:02:44 pm


```
