### ISSUE TITLE
SpamAssassin block spam mail that doesn't pass spf and dkim tests

### ISSUE THREAD

**Issue by e-fo** [docker-mailserver/docker-mailserver#1941]
# Subject
I have questions about SpamAssassins plugin

## Description
My users getting some spam emails that don't passes the spf and dkim tests. I'm enabled the SpamAssassins in mailserver.env and ran docker-compose stop and then docker-compose up -d commands for applying new configs but still getting these spam emails.

My questions is:
1- How can I be sure about the SpamAssassins is enable on my container?
2- According to my configs why my users still getting spam emails.

this is my docker-compose configs and attached my mailserver.env to this issue:
```
version: '3.8'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
      - /etc/letsencrypt:/etc/letsencrypt
      # ? if SELinux is enabled, uncomment the line below and comment the line above
      # - ./config/:/tmp/docker-mailserver/${SELINUX_LABEL}
    env_file:
      - mailserver.env
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

volumes:
  maildata:
  mailstate:
  maillogs:

```

[mailserver.env.txt](https://github.com/docker-mailserver/docker-mailserver/files/6409589/mailserver.env.txt)
