### ISSUE TITLE
Custom / own certificate files not picking up

### ISSUE THREAD

**Issue by KyleDuPlessis** [docker-mailserver/docker-mailserver#1943]
# Subject

I would like to contribute to the project
I would like to configure a not documented mail server use case
I would like some feedback concerning a use case
**I have questions about TLS/SSL/STARTTLS/OpenSSL**
Other

## Description

Added the following entries to the docker-compose.yml (for providing own certificate files):

```
    environment:
    - SSL_TYPE=manual
    - SSL_CERT_PATH=/tmp/ssl/cert/cert.crt
    - SSL_KEY_PATH=/tmp/ssl/private/cert.key
    volumes:
    - /etc/ssl:/tmp/ssl:ro
```

The path where the ssl certificates reside is in /etc/ssl (i.e. /etc/ssl/cert.crt and /etc/ssl/cert.key). However, it is not being picked up and get the following error messages:

```
mail    | #
mail    | # docker-mailserver
mail    | #
mail    | #
mail    |
mail    | Initializing setup
mail    | Checking configuration
mail    | Configuring mail server
mail    |  Warning No DKIM key provided. Check the documentation to find how to get your keys.
mail    | cp: cannot stat '/tmp/ssl/cert/cert.crt': No such file or directory
mail    | cp: cannot stat '/tmp/ssl/private/cert.key': No such file or directory
mail    | chmod: cannot access '/etc/postfix/ssl/cert': No such file or directory
mail    | chmod: cannot access '/etc/postfix/ssl/key': No such file or directory
```

Full docker-compose.yml:

```
version: '2'
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    - "465:465"
    - "995:995"
    - "110:110"
    environment:
    - SSL_TYPE=manual
    - SSL_CERT_PATH=/tmp/ssl/cert/cert.crt
    - SSL_KEY_PATH=/tmp/ssl/private/cert.key
    - ENABLE_POP3=1
    - ENABLE_CLAMAV=0
    - ENABLE_FAIL2BAN=1
    - ENABLE_SPAMASSASSIN=0

    volumes:
    - /etc/ssl:/tmp/ssl:ro
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - maillogs:/var/log/mail
    - ./config/:/tmp/docker-mailserver/
    env_file:
    - .env
    - env-mailserver
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always
volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  maillogs:
    driver: local
```
I have restarted the mailserver after including the changes, but the certificates are still not being picked up. What needs to be done to resolve this issue?
