### ISSUE TITLE
Desktop mail client unable to connect to mailserver

### ISSUE THREAD

**Issue by KyleDuPlessis** [docker-mailserver/docker-mailserver#1944]
# Subject

I would like to contribute to the project
I would like to configure a not documented mail server use case
I would like some feedback concerning a use case
I have questions about TLS/SSL/STARTTLS/OpenSSL
**Other**

## Description

My desktop mail client (Mozilla Thunderbird) cannot connect to mailserver: "Thunderbird failed to find the settings for your email account". I have verified that the email account exists using: `./setup.sh -i tvial/docker-mailserver:latest email list`. I'm using a bare domain (host name = domain name) - [followed these instructions](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#can-i-use-nakedbare-domains-no-host-name). What's causing the issue and how can it be resolved?

<img width="449" alt="Screenshot from 2021-05-03 19-14-10" src="https://user-images.githubusercontent.com/27058026/116906666-d9639a80-ac40-11eb-9a40-b6ee8efe5e6c.png">

**Mailserver output:**

`.`

**docker-compose.yml:**

```
version: '2'
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    - "465:465"
    - "995:995"
    - "110:110"
    environment:
    - SSL_TYPE=manual
    - SSL_CERT_PATH=/tmp/ssl/certs/cert.crt
    - SSL_KEY_PATH=/tmp/ssl/private/cert.key
    - ENABLE_POP3=1
    - ENABLE_CLAMAV=0
    - ENABLE_FAIL2BAN=1
    - ENABLE_SPAMASSASSIN=0

    volumes:
    - /etc/ssl:/tmp/ssl:ro
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - maillogs:/var/log/mail
    - ./config/:/tmp/docker-mailserver/
    env_file:
    - .env
    - env-mailserver
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always
volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  maillogs:
    driver: local
```
