### ISSUE TITLE
migration transition

### ISSUE THREAD

**Issue by aendeavor** [docker-mailserver/docker-mailserver#2]
This is the official tracking issue for the transition into the new repository in the new organization. Related discussions take place here.

---

#### Top Priority

- [x] Integrate GH Actions
- [x] Integrate a scheduled build for the `stable` branch

#### Medium Priority

- [x] Update the labelling (<https://github.com/opencontainers/image-spec/blob/master/annotations.md>)
- [x] Update the `Makefile`

**Comment by radicand** [comment]
Opened PR #3 to bring in Github Actions CI.

**Comment by aendeavor** [comment]
@radicand I have a question which you can probably easily answer for me:) I am currently re-working the labeling of the image to use the current standardized [OCI Image Spec Annotatios](https://github.com/opencontainers/image-spec/blob/master/annotations.md). Therefore, I would like to use

``` DOCKERFILE
LABEL org.opencontainers.image.created=${CREATED}
```

which is working perfectly, but I will need to integrate it into the CI too. Therefore, how do I go about this? This sectin the workflow and one other section like this need it:

``` YAML
      - name: Build image locally
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          build-args: |
            VCS_REF=${{ github.sha }}
            VCS_VERSION=${{ github.ref }}
            # HERE IS THE NEW ARG
            CREATED=`date -u +'%Y-%m-%dT%H:%M:%SZ'`
```

The date is formatted with the Bash command `date -u +'%Y-%m-%dT%H:%M:%SZ'`. How do I write that in the GH Actions?
