### ISSUE TITLE
LDAP Authentication process "broken"

### ISSUE THREAD

**Issue by 0x4A-0x41-0x4B** [docker-mailserver/docker-mailserver#2003]
# I have questions about LDAP authentication

## Description
I have recently started using docker-mailserver as im migrating more and more to open source self hosted software.
After using it for a while i thought, why not integrate this into my central authentication system using LDAP.
(I am using a samba domain controller in this case, ldap authentication is fully set up and has been working for months, nextcloud for example works flawlessly)
I am using the following docker-compose.yml (altered in domain name and passwords of course)

``` yml
version: '3.8'

services:
  mailserver:


services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    hostname: Mail
    domainname: example.com
    container_name: mailserver
    env_file: mailserver.env
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - /etc/localtime:/etc/localtime:ro
      - ./config/:/tmp/docker-mailserver/${SELINUX_LABEL}
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1

      # Enable STARTTLS
      - LDAP_START_TLS=yes
      - DOVECOT_TLS=yes
      - SASLAUTHD_LDAP_START_TLS=yes

      # >>> Postfix LDAP Integration
      - ENABLE_LDAP=1
      - LDAP_SERVER_HOST=dc001
      - LDAP_BIND_DN=CN=Mail (SERVICE),OU=Users,DC=example,DC=com
      - LDAP_BIND_PW=Passw0rdForBindUser
      - LDAP_SEARCH_BASE=DC=example,DC=com
      - LDAP_QUERY_FILTER_DOMAIN=(|(mail=*@%s)(mailAlias=*@%s)(mailGroupMember=*@%s))
      - LDAP_QUERY_FILTER_USER=(&(objectClass=inetOrgPerson)(mail=%s))
      - LDAP_QUERY_FILTER_ALIAS=(&(objectClass=inetOrgPerson)(mailAlias=%s))
      - LDAP_QUERY_FILTER_GROUP=(&(objectClass=inetOrgPerson)(mailGroupMember=%s))
      - LDAP_QUERY_FILTER_SENDERS=(&(objectClass=inetOrgPerson)(|(mail=%s)(mailAlias=%s)(mailGroupMember=%s)))
      - SPOOF_PROTECTION=1
      # <<< Postfix LDAP Integration

      # >>> Dovecot LDAP Integration
      - DOVECOT_USER_FILTER=(&(objectClass=inetOrgPerson)(mail=%u))
      - DOVECOT_PASS_ATTRS=uid=user,userPassword=password
      - DOVECOT_USER_ATTRS==home=/var/mail/%{ldap:uid},=mail=maildir:~/Maildir,uidNumber=uid,gidNumber=gid
      # <<< Dovecot LDAP Integration

      # >>> SASL LDAP Authentication
      - ENABLE_SASLAUTHD=1
      - SASLAUTHD_MECHANISMS=ldap
      - SASLAUTHD_LDAP_FILTER=(&(mail=%U@example.org)(objectClass=inetOrgPerson))
      # <<< SASL LDAP Authentication

      - ONE_DIR=1
      - DMS_DEBUG=1
      # - SSL_TYPE=letsencrypt
      - PERMIT_DOCKER=host
    restart: unless-stopped
    cap_add: [ "NET_ADMIN", "SYS_PTRACE" ]

volumes:
  maildata:
  mailstate:
  maillogs:
```

## What i tried
- Using different users as bind users, the default administrator comes to mind.
- Disabling STARTTLS on ldap resulted in something along the lines of "Strong(er) Authentication required" error message from my ad (In other words, tls has to be used)
- Appending "yes" to the config /etc/dovecot/dovecot-ldap.conf.ext in line 12

# Environment
I am running a virtualized - newly set up - debian buster with the newest patches and i installed docker-mailserver using the installation guide described in the readme.
--> uname -a
--> Linux Mail 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

mailserver.txt is the output of running docker-compose up mailserver and trying to connect once using thunderbird with a working and not disabled user.
[mailserver.txt](https://github.com/docker-mailserver/docker-mailserver/files/6534883/mailserver.txt)

Did i forget any configuration/are any flags missing?

Thanks in advance :)!
