### ISSUE TITLE
SMTP_ONLY from LAN only

### ISSUE THREAD

**Issue by Glideh** [docker-mailserver/docker-mailserver#2007]
I need my applications (and only them, mostly php and node) to be able to send emails.
Those applications have common networks with the SMTP.
My first question is, do I need TLS here ?

If yes, I have a pfSense with HAProxy that can offload the Letsencrypt business.
I'm starting with that docker composition:

```yml
version: '3.4'

services:
  mail:
    image: mailserver/docker-mailserver:9.1.0
    hostname: mail
    domainname: mydomain.eu
    environment:
      - SMTP_ONLY=1
    ports:
#      - "25:25"
#      - "587:587"
      - "465:465"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/:/tmp/docker-mailserver/
```

But I don't really understand the flows that'll take place. For example when and by whom the certificate will be used ?
Does my config seem ok to you ? I didn't test yet, I'd like to understand well first.
