### ISSUE TITLE
[BUG] Cant login to accounts after restarting

### ISSUE THREAD

**Issue by crowlKats** [docker-mailserver/docker-mailserver#2010]
# Bug Report

## Context

Whenever i `compose down` and then `up` the image, i cant login to my account anymore and the logs show "unknown user"

### What is affected by this bug?

Ability to login

### When does this occur?

Whenever image is restarted and files are persisted. I can fix it by deleting majority of the local files.

### How do we replicate the issue?

1. Run server
2. Create account
3. Restart server
4. Attempt to login

## Your Environment

- version: latest edge as of opening
- available RAM: `8GB`
- Docker version: `v20.10.6`
- docker-compose version: `v1.29.1`

### Environment Variables

```CFG

OVERRIDE_HOSTNAME=
DMS_DEBUG=0
SUPERVISOR_LOGLEVEL=
ONE_DIR=1
PERMIT_DOCKER=
ENABLE_AMAVIS=1
AMAVIS_LOGLEVEL=0
ENABLE_CLAMAV=1
ENABLE_POP3=
ENABLE_FAIL2BAN=1
FAIL2BAN_BLOCKTYPE=drop
SMTP_ONLY=
SSL_TYPE=manual
SSL_CERT_PATH=/tmp/ssl/cert/public.crt
SSL_KEY_PATH=/tmp/ssl/private/private.key
TLS_LEVEL=modern
SPOOF_PROTECTION=1
# TODO ENABLE_SRS
NETWORK_INTERFACE=
# TODO VIRUSMAILS_DELETE_DELAY=
ENABLE_POSTFIX_VIRTUAL_TRANSPORT=
POSTFIX_DAGENT=
POSTFIX_MAILBOX_SIZE_LIMIT=0
ENABLE_QUOTAS=1
POSTFIX_MESSAGE_SIZE_LIMIT=
ENABLE_MANAGESIEVE=
POSTMASTER_ADDRESS=postmaster@example.com
POSTSCREEN_ACTION=enforce
DOVECOT_MAILBOX_FORMAT=maildir
POSTFIX_INET_PROTOCOLS=all
PFLOGSUMM_TRIGGER=logrotate
# TODO PFLOGSUMM_RECIPIENT=
# TODO PFLOGSUMM_SENDER=
LOGWATCH_INTERVAL=weekly
#TODO LOGWATCH_RECIPIENT=
LOGROTATE_INTERVAL=weekly

# Spamassassin
ENABLE_SPAMASSASSIN=1
SPAMASSASSIN_SPAM_TO_INBOX=1
MOVE_SPAM_TO_JUNK=1
SA_TAG=2.0
SA_TAG2=6.31
SA_KILL=6.31
SA_SPAM_SUBJECT=***SPAM(_SCORE_)***
# TODO SA_SHORTCIRCUIT_BAYES_SPAM=1
# TODO SA_SHORTCIRCUIT_BAYES_HAM=1

# Fetchmail
#TODO ENABLE_FETCHMAIL=0
FETCHMAIL_POLL=300
FETCHMAIL_PARALLEL=0

# LDAP
ENABLE_LDAP=
LDAP_START_TLS=
LDAP_SERVER_HOST=
LDAP_SEARCH_BASE=
LDAP_BIND_DN=
LDAP_BIND_PW=
LDAP_QUERY_FILTER_USER=
LDAP_QUERY_FILTER_GROUP=
LDAP_QUERY_FILTER_ALIAS=
LDAP_QUERY_FILTER_DOMAIN=
LDAP_QUERY_FILTER_SENDERS=
DOVECOT_TLS=

# Dovecot
DOVECOT_BASE=
# TODO DOVECOT_DEFAULT_PASS_SCHEME=SSHA512
DOVECOT_DN=
DOVECOT_DNPASS=
DOVECOT_URIS=
DOVECOT_LDAP_VERSION=
DOVECOT_AUTH_BIND=
# TODO DOVECOT_USER_FILTER
# TODO DOVECOT_USER_ATTRS
# TODO DOVECOT_PASS_FILTER
# TODO DOVECOT_PASS_ATTRS

# Postgrey
ENABLE_POSTGREY=0
POSTGREY_DELAY=300
POSTGREY_MAX_AGE=35
POSTGREY_TEXT=Delayed by Postgrey
POSTGREY_AUTO_WHITELIST_CLIENTS=5

# SASL
ENABLE_SASLAUTHD=0
SASLAUTHD_MECHANISMS=
SASLAUTHD_MECH_OPTIONS=
SASLAUTHD_LDAP_SERVER=
SASLAUTHD_LDAP_SSL=
SASLAUTHD_LDAP_START_TLS=
SASLAUTHD_LDAP_TLS_CHECK_PEER=
SASLAUTHD_LDAP_TLS_CACERT_DIR=
SASLAUTHD_LDAP_TLS_CACERT_FILE=
SASLAUTHD_LDAP_BIND_DN=
SASLAUTHD_LDAP_PASSWORD=
SASLAUTHD_LDAP_SEARCH_BASE=
SASLAUTHD_LDAP_FILTER=
SASLAUTHD_LDAP_PASSWORD_ATTR=
SASL_PASSWD=
SASLAUTHD_LDAP_AUTH_METHOD=
SASLAUTHD_LDAP_MECH=

# SRS
SRS_SENDER_CLASSES=envelope_sender
SRS_EXCLUDE_DOMAINS=
SRS_SECRET=
SRS_DOMAINNAME=

# Default Relay Host
DEFAULT_RELAY_HOST=

# Multi-Domain Relay
RELAY_HOST=
RELAY_PORT=25
RELAY_USER=
RELAY_PASSWORD=
```

```yaml
  mail:
    container_name: mail
    image: mailserver/docker-mailserver:edge
    hostname: mail
    domainname: example.com
    env_file: ./mail/env.env
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - ./mail/mails:/var/mail
      - ./mail/state:/var/mail-state
      - ./mail/logs:/var/log/mail
      - ./mail/config/:/tmp/docker-mailserver
      - ./mail/certificates/mail.example.com.crt:/tmp/ssl/cert/public.crt
      - ./mail/certificates/mail.example.com.key:/tmp/ssl/private/private.key
      - ./mail/certs:/certs
      - ./mail/config/dovecot/20-lmtp.conf:/etc/dovecot/conf.d/20-lmtp.conf
      - ./mail/config/dovecot/20-imap.conf:/etc/dovecot/conf.d/20-imap.conf
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
```

Additionally i have configured https://docker-mailserver.github.io/docker-mailserver/edge/config/security/mail_crypt/ and added a fail2ban config
