### ISSUE TITLE
Clarification needed re: DOCKER_NETWORK, SPF, and Open Relays behind a router

### ISSUE THREAD

**Issue by dc-bond** [docker-mailserver/docker-mailserver#2057]
I set up docker-mailserver in swarm stack behind my router. My ISP blocks port 25 inbound and outbound. As a workaround, I can successfully send mail on port 587 using a relay (Sendgrid), and I can successfully receive mail via a forwarding service (MX Guarddog). I have MX Guarddog sending mail to an arbitrary port number on my router, which then forwards that port to the docker host machine, and docker-mailserver maps that to port 25 inside the container.

Here is where I get very confused though and need some guidance. Leaving DOCKER_NETWORK parameter set to null prevents me from receiving any external mail - I get "SPF check failed" messages. If I change DOCKER_NETWORK to "host", I can receive external mail. I am unsure if the mailserver is at that point an open relay though. When I try to send an email using this website: https://www.smtper.net/ - with no authentication it definitely works, which makes me think something is very wrong with my setup.

I have googled and seen several other issues here that seem to indicate the complication is with how my networking is setup - that I "lose" the external IP address because of the port forwarding from my router's firewall (indeed, I can see the external connections in the log are from the internal subnet for this container) - but I am at a loss at this point to understand what the recommended approach is for my use-case, or if it is even possible to run this behind a router successfully (as opposed to a VPS where the server is plugged directly into the internet).

Even any remote hints as to what I should be looking at would be very welcome. Here is my docker-compose.yml for what it's worth:

```
version: '3.9'

networks:
  mailserver:
    name: mailserver
    driver: overlay
    attachable: false
    ipam:
      config:
        - subnet: 10.25.0.0/24

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:10.0.0
    networks:
      - mailserver
    env_file: mailserver.env
    ports:
      - "2280:25"    # SMTP  (explicit TLS => STARTTLS)
      #- "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "2282:465"  # ESMTP (implicit TLS)
      #- "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "2281:993"  # IMAP4 (implicit TLS)
    volumes:
      - /home/xixor/hdd1/docker-stack/mailserver/maildata:/var/mail
      - /home/xixor/hdd1/docker-stack/mailserver/mailstate:/var/mail-state
      - /home/xixor/hdd1/docker-stack/mailserver/maillogs:/var/log/mail
      - /home/xixor/hdd1/docker-stack/mailserver/config:/tmp/docker-mailserver
      - /home/xixor/hdd1/docker-stack/traefik/acme/acme.json:/etc/letsencrypt/acme.json:ro
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    deploy:
      mode: replicated
      replicas: 1
```
