### ISSUE TITLE
The Best Kubernetes Setup Possible

### ISSUE THREAD

**Issue by georglauterbach** [docker-mailserver/docker-mailserver#2094]
# Subject

I would like to **reconfigure** and **document** an already documented mail server use case.

## Description

The current documentation on K8s (Kubenetes) is okay, and I was able to extract essential parts off of it. However, it lacked a bit of quality from my POV. I would like to re-do the docs on K8s. I am currently transitioning to [K3s](https://k3s.io/) and **I want to get the, especially security-wise, best "deployment"** (this is a Kubernetes-native term, but I'm referring to Services, etc. too) **possible**. I'm using Kustomize for the whole setup, and I'd document this too once finished.

I'm linking the maintainers that I know are using K8s to get some help on the topic: @radicand 
I'm also trying to get some feedback from the currently most active maintainers: @casperklein @wernerfred @polarathene
And, because in this case, more are better, I'll also link @NorseGaud, @fbartels and @reneploetz

## Manifests

I'm posting my current manifest files, that is, the deployment and the service here. I'd like to get feedback on them. Moreover, I have some questions down below.

The deployment goes first. There are a lot of file mounts that may not all be necessary, but I will explain them below.

``` YAML
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: mailserver

  annotations:
    ignore-check.kube-linter.io/run-as-non-root: >-
      The mail server needs to run as root
    ignore-check.kube-linter.io/privileged-ports: >-
      The mail server needs privilegdes ports
    ignore-check.kube-linter.io/no-read-only-root-fs: >-
      There are too many files written to make The
      root FS read-only

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailserver

  template:
    metadata:
      labels:
        app: mailserver

      annotations:
        container.apparmor.security.beta.kubernetes.io/mailserver: runtime/default

    spec:
      hostname: mailserver
      containers:
        - name: mailserver
          image: ghcr.io/docker-mailserver/docker-mailserver:10.0.0
          imagePullPolicy: IfNotPresent

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            privileged: false
            capabilities:
              add:
                # file permission capabilities
                - CHOWN
                - FOWNER
                - MKNOD
                - SETGID
                - SETUID
                - DAC_OVERRIDE
                # miscellaneous  capabilities
                - SYS_CHROOT
                - NET_BIND_SERVICE
                - KILL
              drop: [ALL]
            seccompProfile:
              type: RuntimeDefault

          resources:
            limits:
              memory: 4Gi
              cpu: 1500m
            requests:
              memory: 2Gi
              cpu: 600m

          volumeMounts:
            # OpenDKIM
            - name: opendkim-files
              subPath: mail_com.private
              mountPath: /tmp/docker-mailserver/opendkim/keys/domain1.tld/mail.private
              readOnly: true
            - name: opendkim-files
              subPath: mail_com.txt
              mountPath: /tmp/docker-mailserver/opendkim/keys/domain1.tld/mail.txt
              readOnly: true
            - name: opendkim-files
              subPath: mail_de.private
              mountPath: /tmp/docker-mailserver/opendkim/keys/domain2.tld/mail.private
              readOnly: true
            - name: opendkim-files
              subPath: mail_de.txt
              mountPath: /tmp/docker-mailserver/opendkim/keys/domain2.tld/mail.txt
              readOnly: true
            - name: opendkim-files
              subPath: KeyTable
              mountPath: /tmp/docker-mailserver/opendkim/KeyTable
              readOnly: true
            - name: opendkim-files
              subPath: SigningTable
              mountPath: /tmp/docker-mailserver/opendkim/SigningTable
              readOnly: true
            - name: opendkim-files
              subPath: TrustedHosts
              mountPath: /tmp/docker-mailserver/opendkim/TrustedHosts
              readOnly: true

            # other
            - name: files
              subPath: dh_4096.pem
              mountPath: /etc/postfix/dh_4096.pem
              readOnly: true
            - name: files
              subPath: hostname
              mountPath: /etc/hostname
              readOnly: true
            - name: files
              subPath: hosts
              mountPath: /etc/hosts
              readOnly: true

            # Postfix
            - name: files
              subPath: main.cf
              mountPath: /etc/postfix/main.cf
              readOnly: true
            - name: files
              subPath: postfix-accounts.cf
              mountPath: /tmp/docker-mailserver/postfix-accounts.cf
              readOnly: true
            - name: files
              subPath: postfix-virtual.cf
              mountPath: /tmp/docker-mailserver/postfix-virtual.cf
              readOnly: true

            # scrips
            - name: files
              subPath: setup-stack.sh
              mountPath: /usr/local/bin/setup-stack.sh
              readOnly: true
            - name: files
              subPath: user-patches.sh
              mountPath: /tmp/docker-mailserver/user-patches.sh
              readOnly: true

            # spam
            - name: files
              subPath: 50-user
              mountPath: /etc/amavis/conf.d/50-user
              readOnly: true
            - name: files
              subPath: header_checks.pcre
              mountPath: /etc/postfix/maps/header_checks.pcre
              readOnly: true
            - name: files
              subPath: postscreen.conf
              mountPath: /etc/fail2ban/filter.d/postscreen.conf
              readOnly: true
            - name: files
              subPath: user-jail.local
              mountPath: /etc/fail2ban/jail.d/user-jail.local
              readOnly: true

            # PVCs
            - name: data
              mountPath: /var/mail
              subPath: data
              readOnly: false
            - name: data
              mountPath: /var/mail-state
              subPath: state
              readOnly: false
            - name: data
              mountPath: /var/log/mail
              subPath: log
              readOnly: false

            # time
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: timezone
              mountPath: /etc/timezone
              readOnly: true

            # certificates
            - name: certificates-rsa
              mountPath: /secrets/ssl/rsa/
              readOnly: true
            - name: certificates-ecdsa
              mountPath: /secrets/ssl/ecdsa/
              readOnly: true

            # other
            - name: tmp-files
              mountPath: /tmp
              readOnly: false

          ports:
            - name: transfer
              containerPort: 25
              protocol: TCP
            - name: esmtp-implicit
              containerPort: 465
              protocol: TCP
            - name: esmtp-explicit
              containerPort: 587
            - name: imap-implicit
              containerPort: 993
              protocol: TCP

          envFrom:
            - configMapRef:
                name: mailserver.environment

      restartPolicy: Always

      volumes:
        # configuration files
        - name: files
          configMap:
            name: mailserver.other.files
        - name: opendkim-files
          configMap:
            name: mailserver.opendkim.files

        # PVCs
        - name: data
          persistentVolumeClaim:
            claimName: data

        # time
        - name: timezone
          hostPath:
            path: /etc/timezone
            type: File
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File

        # certificates
        - name: certificates-rsa
          secret:
            secretName: mail-tls-certificate-rsa
            items:
              - key: tls.key
                path: tls.key
              - key: tls.crt
                path: tls.crt
        - name: certificates-ecdsa
          secret:
            secretName: mail-tls-certificate-ecdsa
            items:
              - key: tls.key
                path: tls.key
              - key: tls.crt
                path: tls.crt

        # other
        - name: tmp-files
          emptyDir: {}

```

The service is more or less straight-forward:

``` YAML
---
apiVersion: v1
kind: Service

metadata:
  name: mailserver
  labels:
    app: mailserver

spec:
  type: LoadBalancer
  externalTrafficPolicy: Local

  selector:
    app: mailserver

  ports:
    # Transfer
    - name: transfer
      port: 25
      targetPort: transfer
      protocol: TCP
    # ESMTP with implicit TLS
    - name: esmtp-implicit
      port: 465
      targetPort: esmtp-implicit
      protocol: TCP
    # ESMTP with explicit TLS (STARTTLS)
    - name: esmtp-explicit
      port: 587
      targetPort: esmtp-explicit
      protocol: TCP
    # IMAPS with implicit TLS
    - name: imap-implicit
      port: 993
      targetPort: imap-implicit
      protocol: TCP

```

## (Possible) Improvements

The goal is simple, achieving it non-trivial:  _Define a proper ´securityContext` in the deployment_. This is, at least to me, critical in achieving the best security possible.

Especially getting

1. `readOnlyRootFilesystem:` set to `true`
2. `runAsUser:` to not be 0
3. `runAsGroup:` to not be 0
4. `runAsNonRoot:` set to `true`
5. `capabilities.drop` set to `[ALL]` and only add the caps that we really need with `capabilities.add`

This will require

1. All files that need to be adjusted on run-time to be mounted externally
2. Have a user that can manage the server as if root but without being root
3. Have a group that can manage the server as if root but without being root
4. If 2. and 3. are fulfilled, this becomes true automatically
5. Just a matter of knowing which capabilities we _actually_ need...

Feedback very welcome! I will test the deployment tomorrow at the earliest because I've got a lot to do ATM, but I will report back. In the meantime, I'd be happy to hear your ideas :D

**Comment by NorseGaud** [comment]
Nice, I've been preparing to do this myself. I wonder if a helm chart would be a good idea

**Comment by radicand** [comment]
Thanks for the mention on this, happy to contribute where I can. If the goal is the best possible k8s setup, I believe starting with security, and then moving on to customization are good steps to take.

My experience with non-root containers has been mixed - sometimes it's as easy as changing the parameters in the deployment, but quite often there are changes in the container (users, groups, etc) that also need adjustment. We should approach that eyes open knowing it may be difficult.

Lastly, I would suggest, as @NorseGaud did as I was typing this :) that we work towards a helm chart. I'd suggest resolving the security questions first and then developing the chart second though.

**Comment by georglauterbach** [comment]
@NorseGaud @radicand How should we go about this? I would start by building the container locally adding something like

``` DOCKERFILE
USER 65534
```

at the end to create a non-privileged user. From thereon, I'd test what the container does and adjust the configuration accordingly.

I'd highly press on building a K8s image separately to not interfere with images built on master.

About Helm: As a mail server is a fairly complex system, you may be right about Helm. I'm personally not a big fan of it: I think the template language is unreadable and the chart management could be better. Moreover, you have to be willing to take the components as a black box if you're unwilling to either look into the chart itself (which is horrendous) or use Kustomize. Therefore, I'd dedicate this issue to getting a secure rootless alternative to the current image.

**Comment by wernerfred** [comment]
> I'd highly press on building a K8s image separately to not interfere with images built on master.

Isn't that something we (and you^^) always tell others in Issues that we only support docker and other environments are documented at max?

Don't get me wrong - i'm highly interested in a running setup using k3s - but it is against current statements. Need further discussion on another level i think.

**Comment by georglauterbach** [comment]
> > I'd highly press on building a K8s image separately to not interfere with images built on master.
> 
> Isn't that something we (and you^^) always tell others in Issues that we only support docker and other environments are documented at max?

The way I phrased that was wrong and lead to a misunderstanding. I‘m not trying to change the status quo. I’m not trying to get K8s maintainers support :)

If we decide to build an image, then this is at maximum community-supported.

What I am trying to achieve is to get a K8s documentation and maybe a community-mainted image with support for rootless mode, read-only root fs, etc.

**Comment by NorseGaud** [comment]
Cool! It's seeming like Helm should, at max, be an afterthought to an already existing set of deployment files for running k8s. Let's do that first and if someone wants to do a Helm, so be it. I'm thinking Helm adds some abstraction that would make it less flexible than we'd want and add potential failures that are helm-specific and hard to solve/maintain.

- I'd recommend not having a whole separate dockerfile and instead build from the one we use in the root. This may point us to separating the dockerfile into smaller pieces (might be useful for the admin/UI project), but I'm not certain yet.
- _"at the end to create a non-privileged user. From there on, I'd test what the container does and adjust the configuration accordingly."_ Yes, that sounds like a great idea. Reach out if you need some help testing something specific. I use minikube locally, but can always set something else up.

**Comment by georglauterbach** [comment]
>     * I'd recommend not having a whole separate dockerfile and instead build from the one we use in the root. This may point us to separating the dockerfile into smaller pieces (might be useful for the admin/UI project), but I'm not certain yet.

Yes, that was the idea.

>     * _"at the end to create a non-privileged user. From there on, I'd test what the container does and adjust the configuration accordingly."_ Yes, that sounds like a great idea. Reach out if you need some help testing something specific. I use minikube locally, but can always set something else up.

I will :)

>     * I'll try out the example manifests you posted and see if I can find any issues. I can't today due to my schedule and other to-dos piling up :(

I wouldn't recommend using these files just yet. I did not come around to test them myself yet. I will reach back to you when I think they are ready :D

**Comment by georglauterbach** [comment]
This quickly got out of control :D

I now have a perfectly working web-mailer setup (Roundcube) with as few permissions as possible. I updated the deployment above and added the web-mailer deployment). This took a lot more time than expected because Roundcube was not meant to work with a read-only root FS.

The mail server is even more complicated. I tested around with using a new user (with `UID` `65534`) and using the `setuid` bit. Turns out: <https://unix.stackexchange.com/questions/364/allow-setuid-on-shell-scripts> TL;DR this does not work. The read-only root FS is (extremely) difficult to achieve too. I even had to make the container privileged to make `sysctl` work (disabling IPv6 etc,). ATM I do not think that we can do very much with the `securityContext`. Mounting `configMaps` is always read-only in K8s 1.21+ (actually even earlier, but who cares). The log then looks like this:

``` TXT
[ TASKLOG ]  Welcome to docker-mailserver 10.0.0
[ TASKLOG ]  Initializing setup
[ TASKLOG ]  Checking configuration
[ TASKLOG ]  Configuring mail server
sed: cannot rename /etc/postfix/sedpvCbMk: Device or resource busy
sed: cannot rename /tmp/docker-mailserver/sedH2D8Sk: Device or resource busy
sed: cannot rename /tmp/docker-mailserver/sedR1bI0k: Device or resource busy
sed: cannot rename /etc/postfix/sedoseDJn: Device or resource busy
postconf: fatal: close /etc/postfix/main.cf.tmp: Device or resource busy
sed: cannot rename /etc/postfix/sedDBeK7m: Device or resource busy
sed: cannot rename /etc/postfix/sedx9Gdgn: Device or resource busy
sed: cannot rename /etc/postfix/sedcGoXln: Device or resource busy
sed: cannot rename /etc/postfix/sedraO2tn: Device or resource busy
[  ERROR  ]  Cannot access '/etc/letsencrypt/live/mail.georglauterbach.com/fullchain.pem' or '/etc/letsencrypt/live/georglauterbach.com/fullchain.pem'
postconf: fatal: close /etc/postfix/main.cf.tmp: Device or resource busy
postconf: fatal: close /etc/postfix/main.cf.tmp: Device or resource busy
postconf: fatal: close /etc/postfix/main.cf.tmp: Device or resource busy
postconf: fatal: close /etc/postfix/main.cf.tmp: Device or resource busy
sed: cannot rename /etc/postfix/sedQ5FYs8: Device or resource busy
postconf: fatal: close /etc/postfix/main.cf.tmp: Device or resource busy
postconf: fatal: close /etc/postfix/main.cf.tmp: Device or resource busy
postconf: fatal: close /etc/postfix/main.cf.tmp: Device or resource busy
sed: cannot rename /etc/postfix/seddFZLsr: Device or resource busy
postconf: fatal: close /etc/postfix/main.cf.tmp: Device or resource busy
postconf: fatal: close /etc/postfix/main.cf.tmp: Device or resource busy
[ TASKLOG ]  Applying user patches
chmod: changing permissions of '/tmp/docker-mailserver/user-patches.sh': Read-only file system
/usr/local/bin/setup-stack.sh: line 1619: /tmp/docker-mailserver/user-patches.sh: Permission denied
[ TASKLOG ]  Post-configuration checks
[ TASKLOG ]  Starting daemons & mail server
cron: started
rsyslog: started
dovecot: started
update-check: started
opendkim: started
opendmarc: started
postgrey: started
postfix: started
fail2ban: started
clamav: started
changedetector: started
amavis: started
[ TASKLOG ]  mail.georglauterbach.com is up and running
whitelisted: 66.216.126.174/32
whitelisted: 193.77.153.67/32
whitelisted 2: 195.235.39.0/24
whitelisted: 216.238.112.99/32
whitelisted: 193.81.20.195/32
whitelisted: 193.77.126.208/32
whitelisted: 80.200.249.216/32
whitelisted: 193.191.218.141/32
whitelisted: 193.191.218.142/32
whitelisted: 193.191.218.143/32
whitelisted: 194.7.234.141/32
whitelisted: 194.7.234.142/32
whitelisted: 194.7.234.143/32
whitelisted: 213.143.66.210/32
2021/07/27-16:41:54 postgrey (type Net::Server::Multiplex) starting! pid(320)
Binding to TCP port 10023 on host 127.0.0.1 with IPv4
Setting gid to "112 112"
Setting uid to "110"
ERROR: locked: /var/lib/postgrey/postgrey.lock
whitelisted: 66.216.126.174/32

...
```

I updated the deployment above to my current state, which really is not usable. @radicand how do you go about mounting files (say `main.cf` for Postfix or files that will be altered in the Pod)?

**Comment by radicand** [comment]
@georglauterbach - I use volume mounts - below is from the deployment I use in production. There are a bunch of config mounts (from the configMap that are not mutable), and then two mutable volume mounts over nfs (the PVCs)

```yaml
          volumeMounts:
            - name: config
              subPath: postfix-accounts.cf
              mountPath: /tmp/docker-mailserver/postfix-accounts.cf
              readOnly: true
            - name: config
              subPath: postfix-main.cf
              mountPath: /tmp/docker-mailserver/postfix-main.cf
              readOnly: true
            - name: config
              subPath: postfix-receive-access.cf
              mountPath: /tmp/docker-mailserver/postfix-receive-access.cf
              readOnly: true
            - name: config
              subPath: postfix-virtual.cf
              mountPath: /tmp/docker-mailserver/postfix-virtual.cf
              readOnly: true
            - name: config
              subPath: postfix-send-access.cf
              mountPath: /tmp/docker-mailserver/postfix-send-access.cf
              readOnly: true
            - name: config
              subPath: spamassassin-rules.cf
              mountPath: /tmp/docker-mailserver/spamassassin-rules.cf
              readOnly: true
            - name: config
              subPath: sa-cron
              mountPath: /etc/cron.d/sa-learn
              readOnly: true
              # mode: 0644
            - name: config
              subPath: SigningTable
              mountPath: /tmp/docker-mailserver/opendkim/SigningTable
              readOnly: true
            - name: config
              subPath: KeyTable
              mountPath: /tmp/docker-mailserver/opendkim/KeyTable
              readOnly: true
            - name: config
              subPath: TrustedHosts
              mountPath: /tmp/docker-mailserver/opendkim/TrustedHosts
              readOnly: true
            - name: opendkim-keys
              mountPath: /tmp/docker-mailserver/opendkim/keys
              readOnly: true
            - name: state
              mountPath: /var/mail-state
            - name: data
              mountPath: /var/mail
            - name: tls
              mountPath: /etc/ssl/mailserver
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: mailserver.config
            # items:
            #   - key: sa-cron
            #     path: /etc/cron.d
            #     mode: 0644
        - name: opendkim-keys
          secret:
            secretName: mailserver.opendkim.keys
        - name: state
          persistentVolumeClaim:
            claimName: "mailserver-pvc"
        - name: data
          persistentVolumeClaim:
            claimName: "mailserver-data-pvc"
        - name: tls
          secret:
            secretName: mail-radicand-net-tls
```
