### ISSUE TITLE
Mailserver behind Traefik

### ISSUE THREAD

**Issue by EthraZa** [docker-mailserver/docker-mailserver#2102]
# Subject

I have questions about TLS/SSL/STARTTLS/OpenSSL

## Description
I can't connect to IMAPS service.

It returns:
```bash
read R BLOCK
400 Bad Requestclosed
```

In the log I can see:
```bash
[[  INF  ]]  Hostname has been set to mail.a.domain.com
[[  INF  ]]  Cert found in /etc/letsencrypt/acme.json for mail.a.domain.com
[[  INF  ]]  Adding mail.a.domain.com SSL certificate to the postfix and dovecot configuration
[ TASKLOG ]  mail.a.domain.com is up and running
```

$ cat dovecot.cf 
```bash
haproxy_trusted_networks = 127.0.0.0/8, 10.0.15.0/24, 10.0.0.0/32, 0.0.0.0/32
haproxy_timeout = 3 secs
service imap-login {
  inet_listener imaps {
    haproxy = yes
    ssl = yes
    port = 10993
  }
}
```

From within container:
``` BASH
root@mail:/# openssl s_client -crlf -connect mail.a.domain.com:993
140052345033856:error:0200206F:system library:connect:Connection refused:../crypto/bio/b_sock2.c:110:
140052345033856:error:2008A067:BIO routines:BIO_connect:connect error:../crypto/bio/b_sock2.c:111:
140052345033856:error:0200206F:system library:connect:Connection refused:../crypto/bio/b_sock2.c:110:
140052345033856:error:2008A067:BIO routines:BIO_connect:connect error:../crypto/bio/b_sock2.c:111:
connect:errno=111

root@mail:/# openssl s_client -crlf -connect mail.a.domain.com:10993
CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 311 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
---
```

From outside:
```bash
$ openssl s_client -crlf -connect mail.a.domain.com:993              
CONNECTED(00000003)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = mail.a.domain.com
verify return:1
---
Certificate chain
 0 s:CN = mail.a.domain.com
   i:C = US, O = Let's Encrypt, CN = R3
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGLTCCBRWgAwIBAgISAwfS5Waz9MhiVWM0g5rI7KocMA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMTA3MjYxMzU0NDBaFw0yMTEwMjQxMzU0MzhaMB4xHDAaBgNVBAMT
E21haWwuYS5naHNpeC5jb20uYnIwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
AoICAQCp7c4nq6VPmkLnB4pR6IFEN6i9TMJmovthG7lhzqnhsaJsLEMQg/haUh/R
fTjQO2vXweCMIjX8dCUvKNOFX4utPj5brpmKYp7zb7b8WOOCciQkYHA+mg089S+a
D8BqODZ9VP2khcLQi5+r3A2E8y/Ml1AB/pGJADYQtYcN9SdeW0bj3labho/P+/Wl
HxT4EsgX/q5nrCzwg06V8kh6rsCpov2hx/voaSWy+VSuFVN/HsBywPkxbDgkOJiZ
4xPTzbSd2ur4HJIewH5vCAK9wIJMtDlFxdxgeRcRhrhynfQCTcEK1v3y9UJgX5nJ
toqcomKm68NJY4MRD2HZdp9JSZ0HVQcbwSez+BVbQudhjQKx4AXg1cR6SJojMdAr
h5IP+vGI3/IcWcUyUbMB9tk1S/3GeQoNLBbP/UBJDMUO/Holnu5XzQq+0x2LOXoN
73pVQwHrgWUkkmdB9gZg2UCDtZIOpuGyPWRMzcuODLZsAiJ0XbEogoqzo/bgL7/r
Q7+F7CXkpGfAa3sUaWPy73PQOlHDT/iDZGdhZzXYySfx1fGbfCcACop93LKBf9la
cbBmQwEHyGsm53Vk8Xx4OKDewumLpCEBHqwr58SuvJie4DW7opQw/scHpobJy0Cd
AnHUH8YsLcCdfIjofArVoRt+YvUTnAsElNJJF0GCbK+9EbCO9QIDAQABo4ICTzCC
AkswDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
AjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBRQ+VUFnGCswnFWTv95V46TelUe+jAf
BgNVHSMEGDAWgBQULrMXt1hWy65QCUDmH6+dixTCxjBVBggrBgEFBQcBAQRJMEcw
IQYIKwYBBQUHMAGGFWh0dHA6Ly9yMy5vLmxlbmNyLm9yZzAiBggrBgEFBQcwAoYW
aHR0cDovL3IzLmkubGVuY3Iub3JnLzAeBgNVHREEFzAVghNtYWlsLmEuZ2hzaXgu
Y29tLmJyMEwGA1UdIARFMEMwCAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEBMCgwJgYI
KwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIIBBQYKKwYBBAHW
eQIEAgSB9gSB8wDxAHcAXNxDkv7mq0VEsV6a1FbmEDf71fpH3KFzlLJe5vbHDsoA
AAF640+ReAAABAMASDBGAiEA3pFnawYYWT90JrB+tx4Fb9XkB22XbzHMmh0qV/Rv
E3sCIQC79eNt6sHlUi4XtTDsZOE7FcVyXt5cKGcWoo6N9+HJZgB2APZclC/RdzAi
FFQYCDCUVo7jTRMZM7/fDC8gC8xO8WTjAAABeuNPkW4AAAQDAEcwRQIgNGuGy2PE
h+aNT5HSbodm9RZR+Sgf04vULFgdp6ATi+kCIQDxvyLi4nQSARQ7Bf9QuFQZFUo6
je6+2ChlRFrYFBsjQDANBgkqhkiG9w0BAQsFAAOCAQEAOCA6sIrCztZuIZD0Rei1
LqX6fkYOWcBKy30mrhi0inNxavLokv1SjWA42AOUFuNO+LYz/Gsc1siFVwXJszHB
G+a/tMN0l9k3PKtt9w/pPpZq52GDVxsDlMqbIUP2HTJCAau+dRLPbKLPbCMwF9jT
FdB8xHoWasIPd+5dH+lODrgef1f/XyY+rR8v4b9rx+Rek7yxoxO+bNPFPXwBAS67
StMLkU2dWrA+bfj7KUl44yOXZ6QHoZkl/Ki+Kryn8u7gQM0gZmpD+dTQZFwk7AoA
/OaqnjbQ6gWz1Q7BBjIrV2BvFzaYnhqxT1gjrx5rVXMp68KMPUdM7ntKwqLalg2f
aQ==
-----END CERTIFICATE-----
subject=CN = mail.a.domain.com

issuer=C = US, O = Let's Encrypt, CN = R3

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 5077 bytes and written 375 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_128_GCM_SHA256
Server public key is 4096 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_128_GCM_SHA256
    Session-ID: A5E94CCFE1EA286CC25D2F9F75B5D5AC9A1DD95E28AE4E335C2F7331327651C1
    Session-ID-ctx: 
    Resumption PSK: F4C2D0F4C873481C19FB07FF672FAA76FC57E1DE9962D2297277F72F8E6A33A6
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 604800 (seconds)
    TLS session ticket:
    0000 - 86 f8 ff cb aa 7f f2 d8-be 60 6d 54 69 f4 b0 e0   .........`mTi...
    0010 - 66 d9 24 83 b4 63 3b 6f-27 23 4a 6a f0 0d e6 79   f.$..c;o'#Jj...y
    0020 - f8 2d 53 27 fd 38 2f a7-0f f7 7e 3c dd e3 43 5a   .-S'.8/...~<..CZ
    0030 - cc f4 2c d6 6a 9c a6 b5-39 7d 47 b7 24 9f f6 6f   ..,.j...9}G.$..o
    0040 - d0 ff 03 a0 42 d3 e6 4b-6e 1c 3a a9 13 f5 12 75   ....B..Kn.:....u
    0050 - 5d 7b 7b 45 6d 8b f9 af-03 43 b9 4f c7 6f e3 5e   ]{{Em....C.O.o.^
    0060 - c2 50 67 72 d8 d2 7e a5-26 c6 89 38 59 30 08 5b   .Pgr..~.&..8Y0.[
    0070 - 19                                                .

    Start Time: 1627328202
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK

HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close

400 Bad Requestclosed
```
- Looks like it's missing: _* OK [CAPABILITY IMAP..._ after **read R BLOCK** and anything I type give me a Bad Request back.

What am I missing?

**Comment by EthraZa** [comment]
Please SOS!

Test with **https://testconnectivity.microsoft.com**:
```php

Testando IMAP para usuário user@a.domain.com no host mail.a.domain.com:993:SSL.
Falha ao testar o IMAP.
Etapas do Teste

Tentando resolver o nome de host mail.a.domain.com no DNS.
Êxito ao resolver o nome de host.
Detalhes Adicionais

Testando porta TCP 993 no host mail.a.domain.com para garantir que ela esteja escutando e aberta.
Êxito ao abrir a porta.

Testando o certificado SSL, para verificar se ele é válido.
O certificado passou por todos os requisitos de validação.
Expandir
Etapas do Teste

O serviço IMAP está sendo testado.
Erro ao testar o serviço IMAP
Detalhes Adicionais
Log de Protocolo: C: 1 CAPABILITY
S: HTTP/1.1 400 Bad Request
Detalhes da exceção:
Mensagem: O servidor IMAP respondeu com um status de erro "HTTP/1.1 400 Bad Request".
Tipo: Microsoft.M365.RCA.Services.Protocols.Imap.ImapServerErrorException
Rastreamento de pilha:
at Microsoft.M365.RCA.Services.Protocols.Imap.ImapCommand`1.CheckForOk(IList`1 response)
at Microsoft.M365.RCA.Services.Protocols.Imap.CapabilityCommand.ProcessResponse(IList`1 response)
at Microsoft.M365.RCA.Services.Protocols.ProtocolClient.<SendCommandAsync>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.M365.RCA.Services.Protocols.Imap.ImapProtocolClient.<Capability>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.M365.RCA.ConnectivityTests.ImapPop.BaseProtocolTest.<PerformTestInternalAsync>d__12.MoveNext()
```

**Comment by casperklein** [comment]
If you get an HTTP reply, when you connect to an IMAP service, then something is wrong:

```
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close
```

**Comment by wernerfred** [comment]
Hi, i documented my working mailserver setup behind traefik in [this section in the docs](https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/mailserver-behind-proxy/#configuration-of-the-used-proxy-software) 
Does this help?

**Comment by EthraZa** [comment]
Thank you for answering.

I have followed the docs at [mailserver-behind-proxy](https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/mailserver-behind-proxy/).

I have no idea about what can be wrong. The one thing I think is very strange is the port 10993 from inside the container not showing a SSL cert since dovecot is configured to use it and the mailserver logs are showing it is been set too:
```php
[[  INF  ]]  Cert found in /etc/letsencrypt/acme.json for mail.a.domain.com
[[  INF  ]]  Adding mail.a.domain.com SSL certificate to the postfix and dovecot configuration
```

My related configs:
```yml
version: "3.8"
services:
  traefik:
    image: traefik:latest
    ports: # Host:Container
      - "${PORTSMTP:-25}:${PORTSMTP:-25}" # Transfer
      - "${PORTHTTP:-80}:${PORTHTTP:-80}"
      - "${PORTHTTPS:-443}:${PORTHTTPS:-443}"
      - "${PORTSMTPS:-465}:${PORTSMTPS:-465}" # Submission SMTPS
      - "${PORTIMAPS:-993}:${PORTIMAPS:-993}" # Retrieval IMAP 143, IMAPS 993, POP 110, POPS 995
      - "${PORTSIEVE:-4190}:${PORTSIEVE:-4190}"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=net_infra"
        - "traefik.http.routers.dash.middlewares=secHeader"
        - "traefik.http.middlewares.secHeader.headers.framedeny=true"
        - "traefik.http.middlewares.secHeader.headers.sslredirect=true"
        - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
        - "traefik.http.routers.redirs.entrypoints=web"
        - "traefik.http.routers.redirs.middlewares=redirect-to-https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    command:
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=proxy
      - --entrypoints.ftp.address=:${PORTFTP:-21}
      - --entrypoints.smtp.address=:${PORTSMTP:-25}
      - --entrypoints.web.address=:${PORTHTTP:-80}
      - --entrypoints.websecure.address=:${PORTHTTPS:-443}
      - --entrypoints.smtp-ssl.address=:${PORTSMTPS:-465}
      - --entrypoints.imap-ssl.address=:${PORTIMAPS:-993}
      - --entrypoints.sieve.address=:${PORTSIEVE:-4190}
```

```yml
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mail_mailserver
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.mail==1"
        preferences:
          - spread: node.labels.mail
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=net_systems"
      - "traefik.tcp.routers.smtp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smtp.entrypoints=smtp"
      - "traefik.tcp.routers.smtp.service=smtp"
      - "traefik.tcp.services.smtp.loadbalancer.server.port=25"
      - "traefik.tcp.services.smtp.loadbalancer.proxyProtocol.version=1"
      - "traefik.tcp.routers.smtp-ssl.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smtp-ssl.entrypoints=smtp-ssl"
      - "traefik.tcp.routers.smtp-ssl.service=smtp-ssl"
      - "traefik.tcp.services.smtp-ssl.loadbalancer.server.port=465"
      - "traefik.tcp.services.smtp-ssl.loadbalancer.proxyProtocol.version=1"
      - "traefik.tcp.routers.imap-ssl.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.imap-ssl.entrypoints=imap-ssl"
      - "traefik.tcp.routers.imap-ssl.service=imap-ssl"
      - "traefik.tcp.services.imap-ssl.loadbalancer.server.port=10993"
      - "traefik.tcp.services.imap-ssl.loadbalancer.proxyProtocol.version=2"
      - "traefik.tcp.routers.sieve.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.sieve.entrypoints=sieve"
      - "traefik.tcp.routers.sieve.service=sieve"
      - "traefik.tcp.services.sieve.loadbalancer.server.port=4190"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/apps/mailserver/docker/var/mail/:/var/mail/
      - /var/apps/mailserver/docker/var/mail-state/:/var/mail-state/
      - /var/apps/mailserver/docker/var/log/mail/:/var/log/mail/
      - /var/apps/mailserver/docker/tmp/docker-mailserver/:/tmp/docker-mailserver/
      - /var/apps/traefik/docker/etc/traefik/certs/acme.json:/etc/letsencrypt/acme.json:ro
    hostname: mail.a.domain.com.br
    domainname: domain.com.br
    environment:
      # --- Mailserver Environment Variables ----------
      # --- General Section ---------------------------
      - DMS_DEBUG=1
      - NETWORK_INTERFACE=
      - TLS_LEVEL=
      - ENABLE_MANAGESIEVE=1
      - SMTP_ONLY=
      - SSL_TYPE=letsencrypt
      - ...
      # --- Dovecot Section ---------------------------
      - DOVECOT_TLS=
      - DOVECOT_USER_FILTER=
      - DOVECOT_PASS_FILTER=
      - DOVECOT_MAILBOX_FORMAT=maildir
      - DOVECOT_AUTH_BIND=
      - ENABLE_POSTGREY=0
      - POSTGREY_DELAY=300
      - POSTGREY_MAX_AGE=35
      - POSTGREY_TEXT=Delayed by Postgrey
      - POSTGREY_AUTO_WHITELIST_CLIENTS=5
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

whoami:
    image: docker.io/traefik/whoami:latest
    deploy:
      labels:
         - "traefik.enable=true"
         - "traefik.docker.network=net_systems"
         - "traefik.http.services.whoami-web.loadbalancer.server.port=80"
         - "traefik.http.routers.whoami-webecure.entrypoints=websecure"
         - "traefik.http.routers.whoami-websecure.rule=Host(`mail.${DOMAIN0:-a.domain.com.br}`)"
```
