### ISSUE TITLE
Spam/Malspam collector configuration

### ISSUE THREAD

**Issue by AC-WhiteGlint** [docker-mailserver/docker-mailserver#2149]
# Subject

Other

## Description

Hi All,

I am trying to use this docker mailserver to collect spam/malspam.

Please find my docker-compose configuration

``` YAML
version: '3.8'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    hostname: mail
    domainname: exemple.com
    container_name: mailserver
    privileged: true
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - /home/acwg/config/:/tmp/docker-mailserver/
    environment:
      - ENABLE_SPAMASSASSIN=0
      - SPAMASSASSIN_SPAM_TO_INBOX=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=0
      - ENABLE_SASLAUTHD=0
      - ENABLE_AMAVIS=0
      - DMS_DEBUG=1
      - RELAY_HOST=
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

volumes:
  maildata:
  mailstate:
  maillogs:

```
I have users and password defined in my postfix-account.cf 

I have also defined catch all account in postfix-virtual.cf 

I am trying to act as an open relay (receiving email to relay without relaying them) to catch spam and malspam.

How can I catch email going to all domain using my relay and to redirect them to a specific user account?

How can I disable all backlist and filter in mailserver?

Thank you in advance.
