### ISSUE TITLE
How to choose the correct public IPv4 address?

### ISSUE THREAD

**Issue by jampy** [docker-mailserver/docker-mailserver#2315]
# choose public (Internet-facing) IP address

I would like to configure a not documented mail server use case

## Description

My host (a VM) is dedicated to run docker-mailserver only, has been set up yesterday with Debian 11.1 and current docker-mailserver.

It has **two** public IPv4 addresses on the same network interface `eth0`. 

```
ip addr show
...
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 96:00:00:fb:e9:fb brd ff:ff:ff:ff:ff:ff
    altname enp1s0
    inet 23.88.x.x/32 brd 23.88.x.x scope global dynamic eth0
       valid_lft 84284sec preferred_lft 84284sec
    inet 116.202.x.x/32 scope global eth0:1
       valid_lft forever preferred_lft forever
    inet6 xxxxx/64 scope global
       valid_lft forever preferred_lft forever
    inet6 xxxxx/64 scope link
       valid_lft forever preferred_lft forever
...
```

I need docker-mailserver to use the IP address `116.202.x.x` **for outgoing mail** as it is static whereas the other address (`23.88.x.x`) might change during VM restarts and similar. The reasoning is that the server IP address will gain reputation (blacklists...) and should not loose it when the VM dynamic IP changes for whatever reason.

I tried setting `NETWORK_INTERFACE=eth0:1` in `mailserver.env` but that didn't help at all.

I searched Docker docs and docker-mailserver docs but could not find an option where to bind outgoing connections to a specific IP address.

To verify the public visible IP address I check `Received:` headers in mails sent by my host, which reveals `23.88.x.x` is used:

```
Received: from mx.***** (static.*.*.88.23.clients.your-server.de. [23.88.x.x])
        by mx.google.com with ESMTPS id ***
```

Yes, this is a Hetzner Cloud host.

My `docker-compose.yml`:

```yaml
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mx
    domainname: (omitted)
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
      - "110:110"  # POP3
      - "995:995"  # POP3 (with TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ./docker-data/certbot/certs/:/etc/letsencrypt/
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
```

So, how to restrict the public IP address in docker-mailserver? Thanks!
