### ISSUE TITLE
SELinux Kubernetes

### ISSUE THREAD

**Issue by sando38** [docker-mailserver/docker-mailserver#2318]
# Subject
I would like some feedback concerning a use case

## Description
Docker-Mailserver runs fine, however, I switched my host machines using centos7 were SELinux is enabled, postfix is blocked by SELinux (see error messages below).

Logs from audit.log
```
type=AVC msg=audit(1638961787.706:1148): avc:  denied  { open } for  pid=5813 comm="master" path="/var/mail-state/spool-postfix/public/pickup" dev="0:221" ino=1179729 scontext=system_u:system_r:container_t:s0:c204,c292 tcontext=system_u:object_r:nfs_t:s0 tclass=fifo_file permissive=1
type=AVC msg=audit(1638962148.471:1180): avc:  denied  { write } for  pid=5813 comm="master" name="pickup" dev="0:221" ino=1179729 scontext=system_u:system_r:container_t:s0:c204,c292 tcontext=system_u:object_r:nfs_t:s0 tclass=fifo_file permissive=0
```
Logs from mail-server:
```
Dec  8 12:39:04 mail postfix/master[2463]: fatal: fifo_listen: remove public/pickup: Permission denied
2021-12-08 12:39:05,556 INFO spawned: 'postfix' with pid 2465
2021-12-08 12:39:05,581 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-12-08 12:39:11,325 INFO exited: postfix (exit status 0; expected)
2021-12-08 12:39:11,326 INFO spawned: 'postfix' with pid 3133
2021-12-08 12:39:11,343 INFO success: postfix entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Dec  8 12:39:11 mail postfix/master[3131]: fatal: fifo_listen: remove public/pickup: Permission denied
```

Switching SELinux to be permissive solves the issue. In Kubernetes, I can define SecurityContext in deployments.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailserver
  namespace: mail
spec:
  template:
    spec:
      containers:
        - name: mailserver
          securityContext:
            seLinuxOptions:
              level: 
              role: 
              type: 
              user:
```
On two pages I saw certain hints about domains, processes being configurable with SELinux and postfix:
https://linux.die.net/man/8/postfix_selinux
https://www.systutorials.com/docs/linux/man/8-postfix_smtp_selinux/

However I am unable to manage it to get it working. 
I am not sure where to start:
- altering something in the security context
- altering something on the host machine
- or both :)

Do you have any idea? 
If further information are needed, I am happy to provide.

BTW: I have a running Kustomize setup I could share with your repo or documentation which include:
- LDAP 
- Mail-Encrpytion
- Proxy-Protocol
- and else.
It could extend your example on your documentation page.

Thanks in advance and have a great day!
