### ISSUE TITLE
[BUG]  sieve error when enabling MOVE_SPAM_TO_JUNK=1

### ISSUE THREAD

**Issue by doets001** [docker-mailserver/docker-mailserver#2366]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

sieve shows errors in the logging when enabling MOVE_SPAM_TO_JUNK=1

### What happened and when does this occur?

```Markdown
When I enable MOVE_SPAM_TO_JUNK=1 I get sieve errors when receiving mail. I do not know if it is a bug or I did something wrong.
When I move it back to MOVE_SPAM_TO_JUNK=0 and keep the rest the same the issue is gone.

my spamassassin settings are

# -----------------------------------------------------------------------------------------------------------------------------
# --------------------- Spamassassin section ----------------------------------------------------------------------------------
# -----------------------------------------------------------------------------------------------------------------------------

ENABLE_SPAMASSASSIN=1

SA_TAG=2.0

SA_TAG2=6.31

SA_KILL=6.31

SA_SPAM_SUBJECT=***SPAM(_SCORE_)***

SPAMASSASSIN_SPAM_TO_INBOX=1

MOVE_SPAM_TO_JUNK=1
```

### What did you expect to happen?

```Markdown
no sieve errors in the logging.
```

### How do we replicate the issue?

```Markdown
1. use spam assassins settings like shown and toggle MOVE_SPAM_TO_JUNK. It fails when set to 1 and does not show any errors when disabled
```

### DMS version

10.4.0

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yaml
mail:
    image: mailserver/docker-mailserver:10.4.0
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    extra_hosts:
      - "mail.mydomain.com:xxx.xxx.xxx.xxx"
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    dns:
      - 10.0.2.34
      - 8.8.8.8
    volumes:
      - /var/dyn_data/mail/maildata:/var/mail
      - /var/dyn_data/mail/mailstate:/var/mail-state
      - /var/dyn_data/mail/maillogs:/var/log/mail
      - /var/dyn_data/mail/scripts/config/:/tmp/docker-mailserver/
      - /var/dyn_data/mail/certificates:/tmp/ssl:ro
    env_file:
      - .env
      - env-mailserver
    environment:
      - TZ=Europe/Amsterdam
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
```

### Relevant log output

```shell
some example error logs

Jan  8 19:08:07 mail dovecot: lmtp(mail@john.do)<7614><oLqVHwfT2WG+HQAA79KMpg>: Error: sieve: binary /usr/lib/dovecot/sieve-global/before/60-spam.svbin: save: failed to create temporary file: open(/usr/lib/dovecot/sieve-global/before/60-spam.svbin.) failed: Permission denied (euid=5000(docker) egid=5000(docker) missing +w perm: /usr/lib/dovecot/sieve-global/before, dir owner missing perms)
Jan  8 19:08:07 mail dovecot: lmtp(mail@john.do)<7614><oLqVHwfT2WG+HQAA79KMpg>: Error: sieve: The LDA Sieve plugin does not have permission to save global Sieve script binaries; global Sieve scripts like `/usr/lib/dovecot/sieve-global/before/60-spam.sieve' need to be pre-compiled using the sievec tool
Jan  8 19:08:07 mail dovecot: lmtp(mail@john.do)<7614><oLqVHwfT2WG+HQAA79KMpg>: sieve: msgid=<1984914869.3457568.1641665284275@ox-webmail.xs4all.nl>: stored mail into mailbox 'INBOX'
```
```


### Other relevant information

_No response_

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

### Improvements to this form?

_No response_
