### ISSUE TITLE
Can't create email accounts while enabling LDAP

### ISSUE THREAD

**Issue by DeolTito** [docker-mailserver/docker-mailserver#2379]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

Mail creation, deletion and listing

### What happened and when does this occur?

```Markdown
While trying to create the email account using the setup.sh; I'm encountering the error below.

Waiting for dovecot to create /var/mail/deol.com/deoltito...
Waiting for dovecot to create /var/mail/deol.com/deoltito...
Waiting for dovecot to create /var/mail/deol.com/deoltito...
Waiting for dovecot to create /var/mail/deol.com/deoltito...

This message goes on until I stops it. However the email account won't be created. 

When I try to list the available email accounts, this particular error is seen under it.
==========
# ./setup.sh email list
Fatal: Unknown command 'quota', but plugin quota exists. Try to set mail_plugins=quota
/usr/local/bin/listmailuser: line 15: 1024 *  : syntax error: operand expected (error token is "*  ")
/usr/local/bin/listmailuser: line 15: 1024 *  : syntax error: operand expected (error token is "*  ")
* new@deol.com (  /  ) [%]
==========
```

### What did you expect to happen?

```Markdown
I believe it has something to with the LDAP integration. When I disable LDAP in the compose file, the email accounts can be created, listed and deleted without any issues.
```

### How do we replicate the issue?

```Markdown
1. Try to create a compose file with LDAP enabled and integrated in it
2. Try creating an email account after that
3. Try to list or delete the email accounts too
...
```

### DMS version

v10.4.0

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yaml
version: '3.8'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: deol.com
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ENABLE_SASLAUTHD=1
      - ONE_DIR=1
      - DMS_DEBUG=1
      - ENABLE_LDAP=1
      - LDAP_SERVER_HOST=LDAPNEW # your ldap container/IP/ServerName
      - LDAP_SEARCH_BASE=ou=people,dc=ds,dc=domain,dc=com
      - LDAP_BIND_DN=cn=admin,dc=ds,dc=domain,dc=com
      - LDAP_BIND_PW=
      - ENABLE_SASLAUTHD=1
      - SASLAUTHD_MECHANISMS=ldap
      - SASLAUTHD_LDAP_SERVER=LDAPNEW
      - SASLAUTHD_LDAP_BIND_DN=cn=admin,dc=ds,dc=domain,dc=com
      - SASLAUTHD_LDAP_PASSWORD=
      - SASLAUTHD_LDAP_SEARCH_BASE=ou=people,dc=ds,dc=domain,dc=com
      - SASLAUTHD_LDAP_FILTER=(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%U))
      - POSTMASTER_ADDRESS=postmaster@deol.com
      - POSTFIX_MESSAGE_SIZE_LIMIT=100000000
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
```

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution
