### ISSUE TITLE
Need help on SSL configuration

### ISSUE THREAD

**Issue by guillaumedc** [docker-mailserver/docker-mailserver#2405]
# Subject

I have questions about TLS/SSL/STARTTLS/OpenSSL

## Description

I try to setup SSL using a wildcard certificate generated by a Traefik container, but I have this error when starting DMS.

``` BASH
[ TASKLOG ]  Configuring mail server
[  ERROR  ]  Cannot find a valid DOMAIN for '/etc/letsencrypt/live/<DOMAIN>/', tried: 'domain.tld', 'mail.domain.tld', 'domain.tld'
[  FATAL  ]  TLS Setup [SSL_TYPE=letsencrypt] | LETSENCRYPT_DOMAIN appears to be misconfigured, please verify.
[  ERROR  ]  Shutting down..
```

My current docker-compose configuration looks like that:

``` Yaml
   mail:                                                                                             
     image: ghcr.io/docker-mailserver/docker-mailserver:latest                                                                                            
     hostname: mail                                                                                  
     dns:                                                                                            
       - 9.9.9.11 #QUAD9 DNS Server with ECS enabled see: https://www.quad9.net/service/service-addresses-and-features/#ecssec
     domainname: domain.tld                                                                    
     container_name: mail                                                                            
     ports:                                                                                          
     - "25:25"                                                                                                                
     - "143:143"                                                                                     
     - "587:587"                                                                                     
     - "993:993"                                                                                     
     - "4190:4190"                                                                                   
     volumes:                                                                                        
     - /srv/data/mailbox/maildata:/var/mail                                                          
     - /srv/data/mailbox/mailstate:/var/mail-state                                                   
     - /srv/data/mailbox/config/:/tmp/docker-mailserver/                                             
     - /srv/data/traefik/data/acme.json:/etc/letsencrypt/acme.json:ro                                
    #- /etc/letsencrypt:/etc/letsencrypt:ro                                                          
     - /etc/localtime:/etc/localtime:ro                                                              
     environment:                                                                                    
     - ENABLE_SPAMASSASSIN=1                                                                         
     - SPAMASSASSIN_SPAM_TO_INBOX=1                                                                                 
     - ENABLE_CLAMAV=0                                                                                              
     - ENABLE_FAIL2BAN=1                                                                                            
     - ENABLE_QUOTA=0                                                                                
     - ONE_DIR=1                                                                                     
     - DMS_DEBUG=0                                                                                   
     - POSTMASTER_ADDRESS="postmaster@domain.tld"                                              
     - PERMIT_DOCKER=host                                                                            
     - TLS_LEVEL=intermediate                                                                        
     - SSL_TYPE=letsencrypt                                                                          
     - SSL_DOMAIN=domain.tld                                                                  
     - LETSENCRYPT_DOMAIN=domain.tld                                                          
     - ENABLE_POSTGREY=0                                                                             
     - POSTGREY_DELAY=120                                                                            
     - POSTGREY_MAX_AGE=30                                                                           
     - POSTGREY_AUTO_WHITELIST_CLIENTS=3                                                             
     - ENABLE_MANAGESIEVE=1                                                                          
     cap_add:                                                                                        
     - NET_ADMIN                                                                                     
     - SYS_PTRACE                                                                                    
     restart: always
```

I tried with and without `LETSENCRYPT_DOMAIN` and it doesn't work in any case.

Do you have any idea to fix this issue?
Tell me if I can give you any more details to understand what's going on.
Thanks!
