### ISSUE TITLE
can not add email account , waiting for dovecot to create maildir

### ISSUE THREAD

**Issue by changchichung** [docker-mailserver/docker-mailserver#2406]
# Subject

I have questions about setup.sh

## Description
I try to add a new account with setup.sh by following command
```

2022-02-11 10:46:53 [mini@s013 docker-mailserver]$ ./setup.sh email add test@test.com testpassword

```
after input the password , console keeps showing endless messages
```
Waiting for dovecot to create /var/mail/test.com/test...
Waiting for dovecot to create /var/mail/test.com/test...
Waiting for dovecot to create /var/mail/test.com/test...
Waiting for dovecot to create /var/mail/test.com/test...
Waiting for dovecot to create /var/mail/test.com/test...
Waiting for dovecot to create /var/mail/test.com/test...
Waiting for dovecot to create /var/mail/test.com/test...
Waiting for dovecot to create /var/mail/test.com/test...
Waiting for dovecot to create /var/mail/test.com/test...
Waiting for dovecot to create /var/mail/test.com/test...
Waiting for dovecot to create /var/mail/test.com/test...
Waiting for dovecot to create /var/mail/test.com/test...
Waiting for dovecot to create /var/mail/test.com/test...
Waiting for dovecot to create /var/mail/test.com/test...
Waiting for dovecot to create /var/mail/test.com/test...
Waiting for dovecot to create /var/mail/test.com/test...
Waiting for dovecot to create /var/mail/test.com/test...
Waiting for dovecot to create /var/mail/test.com/test...
Waiting for dovecot to create /var/mail/test.com/test...
Waiting for dovecot to create /var/mail/test.com/test...
```
docker logs shows nothing error/critical

if I interupt the setup.sh by ctrl+c
and the next time I try to run the same add account command 
it tells me that account is already exist.
```
2022-02-11 10:52:05 [mini@s013 docker-mailserver]$ ./setup.sh email add test@test.com
User 'test@test.com' already exists.

--- UNCHECKED ERROR
  - script    = ./setup.sh
  - function  = _main
  - command   = ${CRI} exec "${USE_TTY}" "${CONTAINER_NAME}" setup "${@:+$@}"
  - line      = 237
  - exit code = 1

This should not have happened. Please file a bug report.
```

but I can not connect to the mail server due to  Authentication failed.

and docker logs show unknown user
```
Feb 11 10:54:08 s013 dovecot: auth: Warning: Configuration file /etc/dovecot/dovecot-ldap.conf.ext line 5: Ambiguous '#' character in line, treating it as comment. Add a space before it to remove this warning.
Feb 11 10:54:26 s013 dovecot: auth: ldap(test@test.com,192.168.11.177,<K2pUL7XXVt3AqAux>): unknown user (SHA1 of given password: 8bb611)
```

Did I do something wrong ? I think I did follow the readme to run the container.
any suggestions ??

**Comment by changchichung** [comment]
my docker-compose.yml
```
version: '3.8'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: hqs013
    domainname: test.com
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - DMS_DEBUG=0
      - ENABLE_LDAP=1
      - LDAP_SERVER_HOST=192.168.11.1# your ldap container/IP/ServerName
      - LDAP_SEARCH_BASE=ou=People,dc=test,dc=com
      - LDAP_BIND_DN=cn=admin,dc=test,dc=com
      - LDAP_BIND_PW=adminpassword
      - LDAP_QUERY_FILTER_USER=(&(mail=%s)(mailEnabled=TRUE))
      - LDAP_QUERY_FILTER_GROUP=(&(mailGroupMember=%s)(mailEnabled=TRUE))
      - LDAP_QUERY_FILTER_ALIAS=(|(&(mailAlias=%s)(objectClass=PostfixBookMailForward))(&(mailAlias=%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE)))
      - LDAP_QUERY_FILTER_DOMAIN=(|(&(mail=*@%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE))(&(mailGroupMember=*@%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE))(&(mailalias=*@%s)(objectClass=PostfixBookMailForward)))
      - DOVECOT_PASS_FILTER=(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))
      - DOVECOT_USER_FILTER=(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))
      - ENABLE_SASLAUTHD=1
      - SASLAUTHD_MECHANISMS=ldap
      - SASLAUTHD_LDAP_SERVER=ldap
      - SASLAUTHD_LDAP_BIND_DN=cn=admin,dc=test,dc=com
      - SASLAUTHD_LDAP_PASSWORD=adminpassword
      - SASLAUTHD_LDAP_SEARCH_BASE=ou=People,dc=test,dc=com
      - SASLAUTHD_LDAP_FILTER=(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%U))
      - POSTMASTER_ADDRESS=postmaster@test.com
      - POSTFIX_MESSAGE_SIZE_LIMIT=100000000
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

###############################################################################################################################

#services:
#  mailserver:
#    image: docker.io/mailserver/docker-mailserver:latest
#    container_name: mailserver
#    # If the FQDN for your mail-server is only two labels (eg: example.com),
#    # you can assign this entirely to `hostname` and remove `domainname`.
#    hostname: hqs013
#    domainname: test.com
#    env_file: mailserver.env
#    # More information about the mail-server ports:
#    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
#    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
#    ports:
#      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
#      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
#      - "465:465"  # ESMTP (implicit TLS)
#      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
#      - "993:993"  # IMAP4 (implicit TLS)
#    volumes:
#      - ./docker-data/dms/mail-data/:/var/mail/
#      - ./docker-data/dms/mail-state/:/var/mail-state/
#      - ./docker-data/dms/mail-logs/:/var/log/mail/
#      - ./docker-data/dms/config/:/tmp/docker-mailserver/
#      - /etc/localtime:/etc/localtime:ro
#    restart: always
#    stop_grace_period: 1m
#    cap_add:
#      - NET_ADMIN
#      - SYS_PTRACE

```
