### ISSUE TITLE
Issues with SSL after updating form 9.1 to 10.4

### ISSUE THREAD

**Issue by marcinkunert** [docker-mailserver/docker-mailserver#2415]
I have a problem with SSL after updating from 9.1 to 10.4. The server doesn't start properly and I can't send nor receive mails.

The first error is

```
Error: sed -i -r -e s|^(ssl_key =).*|\1 </etc/dms/tls/key| -e s|^(ssl_cert =).*|\1 </etc/dms/tls/cert| /etc/dovecot/conf.d/10-ssl.conf
```

There are also:

```
Feb 16 11:21:02 mail postfix/smtpd[2883]: warning: error opening chain file: /etc/postfix/ssl/key: No such file or directory
```

I'm using SSL_TYPE=manual in `mailserver.env`

```
SSL_TYPE=manual
SSL_CERT_PATH=/etc/letsencrypt/live/mail.javastart.pl/fullchain.pem
SSL_KEY_PATH=/etc/letsencrypt/live/mail.javastart.pl/privkey.pem
```

`docker-compose.yml` looks like follows:

```
version: '3.8'

services:
  mail:
    image: docker.io/mailserver/docker-mailserver:10.4.0
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
      - /etc/letsencrypt/:/etc/letsencrypt/
    env_file:
      - mailserver.env
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

volumes:
  maildata:
  mailstate:
  maillogs:
```
