### ISSUE TITLE
Right value to put in hostname and domainname when FQDN is a fourth-level-domain

### ISSUE THREAD

**Issue by frugan-it** [docker-mailserver/docker-mailserver#2423]
# Subject

I would like some feedback concerning a use case

## Description

I am a little confused as to what is the right value to put in `hostname` and `domainname` in `docker-compose.yml`, when FQDN is a **fourth-level-domain** (eg. `sub4.sub3.domain.tld`).
I searched the issues a bit, and read these https://github.com/docker-mailserver/docker-mailserver/pull/2245#issuecomment-942919301, https://github.com/docker-mailserver/docker-mailserver/pull/2280, but I don't find my specific case.

I am currently using this setting in `docker-compose.yml`:

```yml
version: '3.9'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:10.4.0
    container_name: mailserver
    hostname: sub4.sub3.domain.tld
    domainname: domain.tld
...
```
but it does not seem correct to me, in fact it causes some small problems:

1. `/etc/mailname` contains `sub3.domain.tld`, and not `sub4.sub3.domain.tld`
2. UNCHECKED mail notifications by Amavis are sent to postmaster@sub3.domain.tld, and not postmaster@sub4.sub3.domain.tld
3. PostSRSd rewrites `Return-Path: <SRS0=xxxx=yy=otherdomain.tld=user@sub3.domain.tld>`, and not `Return-Path: <SRS0=xxxx=yy=otherdomain.tld=user@sub4.sub3.domain.tld>`

However, I think points 2) and 3) depend on point 1), in fact about Amavis:

```bash
$ grep -R postmaster /etc/amavis/conf.d/
conf.d/20-debian_defaults:$virus_admin = "postmaster\@$mydomain"; # due to D_DISCARD default
```
and

```bash
$ cat /etc/amavis/conf.d/05-domain_id 
...
chomp($mydomain = `head -n 1 /etc/mailname`);
...
```
And about PostSRSd:

https://github.com/roehling/postsrsd/blob/master/init/postsrsd-systemd-launcher.in#L4
```
SRS_DOMAIN="`postconf -h mydomain || true`"
```
and
```
$ postconf -h mydomain
sub3.domain.tld
```

**Comment by casperklein** [comment]
Did you try this:

```
services:
  mailserver:
    hostname: sub4
    domainname: sub3.domain.tld
```
