### ISSUE TITLE
The LDA Sieve plugin does not have permission to save global Sieve script binaries 

### ISSUE THREAD

**Issue by frugan-it** [docker-mailserver/docker-mailserver#2440]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

Folder permission error compiling Sieve global scripts

### What happened and when does this occur?

```Markdown
The file `/usr/lib/dovecot/sieve-global/before/50-before.dovecot.svbin` is not created due to permissions issues
```

### What did you expect to happen?

```Markdown
No Sieve errors compiling scripts
```

### How do we replicate the issue?

1. created file `config/dovecot.cf`:
```conf
plugin {
    #https://github.com/docker-mailserver/docker-mailserver/issues/2277#issuecomment-963589913
    #sieve_global_extensions = +editheader
    sieve_extensions = +editheader
}
```

2. created file `config/before.dovecot.sieve`:
```sieve
require [
    "editheader",
    "fileinto",
    "mailbox",
    "variables"
];

#https://answers.microsoft.com/it-it/outlook_com/forum/all/mail-di-spam-dal-dominio-onmicrosoftcom/2ff8b433-576f-493f-9a54-7ad34a092457
if allof (
    header :contains "Received-SPF" "outbound.protection.outlook.com",
    header :is "X-MS-Exchange-CrossTenant-FromEntityHeader" "Hosted",
    header :is "To" "Undisclosed recipients:;"
) {

    # store the original subject in a variable that later rules can use
    if header :matches "Subject" "*" {
        set "subject" "${1}";
    }

    if not header "X-Spam-Flag" "YES" {
        deleteheader "X-Spam-Flag";
        addheader "X-Spam-Flag" "YES";
    }

    if not header :contains "Subject" "***SPAM*****" {
        deleteheader "Subject";
        addheader :last "Subject" "***SPAM*** ${subject}";
    }

    fileinto "Junk";
}
```

3. restarted DMS

### DMS version

v10.4.0

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yaml
version: '3.9'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:10.4.0
    container_name: mailserver
    hostname: my.hostname.tld
    env_file: .env
    ports:
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
    volumes:
      - ${PWD}/sys/mailserver/data:/var/mail
      - ${PWD}/sys/mailserver/state:/var/mail-state
      - ${PWD}/sys/mailserver/logs:/var/log/mail
      - ${PWD}/sys/mailserver/config:/tmp/docker-mailserver
      - ${PWD}/sys/certbot/certs:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
```

### Relevant log output

Startup error logs:

```sh
$ docker-compose logs -f
mailserver    | 50-before.dovecot: line 13: error: require command: unknown Sieve capability `editheader'.
mailserver    | 50-before.dovecot: line 38: error: unknown command 'deleteheader' (only reported once at first occurrence).
mailserver    | 50-before.dovecot: line 39: error: unknown command 'addheader' (only reported once at first occurrence).
mailserver    | 50-before.dovecot: error: validation failed.
mailserver    | sievec: Fatal: failed to compile sieve script '/usr/lib/dovecot/sieve-global/before/50-before.dovecot.sieve'
```

Log upon receipt of an email:
```sh
$ docker exec -it mailserver setup debug show-mail-logs
Error: sieve: binary /usr/lib/dovecot/sieve-global/before/50-before.dovecot.svbin: save: failed to create temporary file: open(/usr/lib/dovecot/sieve-global/before/50-before.dovecot.svbin.) failed: Permission denied (euid=5000(docker) egid=5000(docker) missing +w perm: /usr/lib/dovecot/sieve-global/before, dir owner missing perms)
Error: sieve: The LDA Sieve plugin does not have permission to save global Sieve script binaries; global Sieve scripts like `/usr/lib/dovecot/sieve-global/before/50-before.dovecot.sieve' need to be pre-compiled using the sievec tool
```

### Other relevant information

To solve the problem I added this to `user-patches.sh`:

```sh
chmod +w /usr/lib/dovecot/sieve-global;
chmod +w /usr/lib/dovecot/sieve-global/after;
chmod +w /usr/lib/dovecot/sieve-global/before;
```

This ensures that the Sieve global filters run correctly, despite the fact that some errors log remains on startup (_50-before.dovecot: line 13: error: require command: unknown Sieve capability `editheader'_ ...)

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution
