### ISSUE TITLE
container restarts once every 30 seconds [BUG] 

### ISSUE THREAD

**Issue by JeremyCanfield** [docker-mailserver/docker-mailserver#2482]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

Unable to get container up and running without restarting once every 30 seconds

### What happened and when does this occur?

```Markdown
I have the following docker-compose.yml.


version: '3'
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.freekb.net
    domainname: freekb.net
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/supervisor-logs/:/var/log/supervisor/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ENABLE_SASLAUTHD=0
      - ONE_DIR=1
      - DMS_DEBUG=1
      - SUPERVISOR_LOGLEVEL=debug
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
```

Then issue the following commands.

```
sudo docker-compose up
sudo docker run --rm -v "${PWD}/docker-data/dms/config/:/tmp/docker-mailserver/" docker.io/mailserver/docker-mailserver setup email add john.doe@freekb.net itsasecret
```

The docker container restarts about once every 30 seconds.

```
[jeremy.canfield@lab1 ~]$ date
Mon Mar 14 03:11:44 AM CDT 2022

[jeremy.canfield@lab1 ~]$ sudo docker container ls -a
CONTAINER ID   IMAGE                                 COMMAND                  CREATED          STATUS          PORTS                                                                                                                                                                                         NAMES
ac617d241e45   mailserver/docker-mailserver:latest   "/usr/bin/dumb-init …"   36 seconds ago   Up 29 seconds   0.0.0.0:25->25/tcp, :::25->25/tcp, 110/tcp, 0.0.0.0:143->143/tcp, :::143->143/tcp, 0.0.0.0:587->587/tcp, :::587->587/tcp, 465/tcp, 995/tcp, 0.0.0.0:993->993/tcp, :::993->993/tcp, 4190/tcp   mailserver
[jeremy.canfield@lab1 ~]$ date
Mon Mar 14 03:11:45 AM CDT 2022

[jeremy.canfield@lab1 ~]$ sudo docker container ls -a
CONTAINER ID   IMAGE                                 COMMAND                  CREATED          STATUS                          PORTS     NAMES
ac617d241e45   mailserver/docker-mailserver:latest   "/usr/bin/dumb-init …"   37 seconds ago   Restarting (137) 1 second ago             mailserver
[jeremy.canfield@lab1 ~]$ date
Mon Mar 14 03:11:46 AM CDT 2022

[jeremy.canfield@lab1 ~]$ sudo docker container ls -a
CONTAINER ID   IMAGE                                 COMMAND                  CREATED          STATUS                  PORTS                                                                                                                                                                                         NAMES
ac617d241e45   mailserver/docker-mailserver:latest   "/usr/bin/dumb-init …"   38 seconds ago   Up Less than a second   0.0.0.0:25->25/tcp, :::25->25/tcp, 110/tcp, 0.0.0.0:143->143/tcp, :::143->143/tcp, 0.0.0.0:587->587/tcp, :::587->587/tcp, 465/tcp, 995/tcp, 0.0.0.0:993->993/tcp, :::993->993/tcp, 4190/tcp   mailserver
```

In this example, the container restarted at Mon Mar 14 03:11:45 AM CDT 2022 with exit code 137. I am not seeing any events in docker-data/dms/supervisor-logs/supervisord.log at 3:11:45.

```
2022-03-14 03:11:32,572 DEBG 'mailserver' stdout output:
Mar 14 03:11:32 post postfix/master[1432]: daemon started -- version 3.5.6, configuration /etc/postfix

2022-03-14 03:11:34,427 DEBG 'changedetector' stdout output:
[[  INF  ]]  2022-03-14 03:11:34 check-for-changes is ready

2022-03-14 03:11:46,435 INFO Included extra file "/etc/supervisor/conf.d/saslauth.conf" during parsing
2022-03-14 03:11:46,437 INFO Included extra file "/etc/supervisor/conf.d/supervisor-app.conf" during parsing
```

Or in mail.log.

```
Mar 14 03:11:26 post amavis[417]: Found secondary av scanner ClamAV-clamscan at /usr/bin/clamscan
Mar 14 03:11:32 post postfix/master[1432]: daemon started -- version 3.5.6, configuration /etc/postfix
Mar 14 03:11:51 post dovecot: master: Dovecot v2.3.13 (89f716dc2) starting up for imap, lmtp
Mar 14 03:11:52 post opendkim[206]: OpenDKIM Filter v2.11.0 starting (args: -f)
```

I am not sure why the container keeps restarting once every 30 seconds.
```


### What did you expect to happen?

```Markdown
I am not sure why the container keeps restarting once every 30 seconds.
```

### How do we replicate the issue?

```Markdown
1. sudo docker-compose up
2. sudo docker run --rm -v "${PWD}/docker-data/dms/config/:/tmp/docker-mailserver/" docker.io/mailserver/docker-mailserver setup email add john.doe@freekb.net itsasecret
```

### DMS version

10.5.0

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker

### docker-compose.yml

```yaml
version: '3'
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.freekb.net
    domainname: freekb.net
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/supervisor-logs/:/var/log/supervisor/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ENABLE_SASLAUTHD=0
      - ONE_DIR=1
      - DMS_DEBUG=1
      - SUPERVISOR_LOGLEVEL=debug
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
```

### Relevant log output

```shell
docker-data/dms/supervisor-logs/supervisord.log before/after 3:11:45.


2022-03-14 03:11:32,572 DEBG 'mailserver' stdout output:
Mar 14 03:11:32 post postfix/master[1432]: daemon started -- version 3.5.6, configuration /etc/postfix

2022-03-14 03:11:34,427 DEBG 'changedetector' stdout output:
[[  INF  ]]  2022-03-14 03:11:34 check-for-changes is ready

2022-03-14 03:11:46,435 INFO Included extra file "/etc/supervisor/conf.d/saslauth.conf" during parsing
2022-03-14 03:11:46,437 INFO Included extra file "/etc/supervisor/conf.d/supervisor-app.conf" during parsing
```

docker-data/dms/mail.log before/after 3:11:45.

```
Mar 14 03:11:26 post amavis[417]: Found secondary av scanner ClamAV-clamscan at /usr/bin/clamscan
Mar 14 03:11:32 post postfix/master[1432]: daemon started -- version 3.5.6, configuration /etc/postfix
Mar 14 03:11:51 post dovecot: master: Dovecot v2.3.13 (89f716dc2) starting up for imap, lmtp
Mar 14 03:11:52 post opendkim[206]: OpenDKIM Filter v2.11.0 starting (args: -f)
```
```


### Other relevant information

_No response_

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

### Improvements to this form?

_No response_
