### ISSUE TITLE
[BUG] Rocky/RHEL 8 Podman iptables error tearing down CNI namespace configuration

### ISSUE THREAD

**Issue by winllc** [docker-mailserver/docker-mailserver#2490]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

service network connectivity

### What happened and when does this occur?

```Markdown
The docker-mailserver container periodically stops allowing IMAP/SMTP connections. After restarting the container new connections can be made. While running "podman restart <container id>" an error is displayed.
```

### What did you expect to happen?

```Markdown
The container to accept service connections without the need to restart.
```

### How do we replicate the issue?

```Markdown
1. Run docker-mailserver on Rocky Linux 8
2. Send/receive emails until connections refused
3. Restart the container
```

### DMS version

v10.5.0

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Podman (not officially supported)

### docker-compose.yml

```yaml
Ansible container deployment config:

containers.podman.podman_container:
      image: "{{ mailserver_docker_name }}:{{ mailserver_docker_tag }}"
      name: email-mock-service
      hostname: "{{ inventory_hostname }}"
      state: started
      restart: yes
      restart_policy: unless-stopped
      ports:
        - "25:25"
        - "143:143"
        - "587:587"
        - "993:993"
      cap_add:
        - NET_ADMIN
        - SYS_PTRACE
      env:
        ENABLE_SPAMASSASSIN: 1
        SPAMASSASSIN_SPAM_TO_INBOX: 1
        ENABLE_CLAMAV: 1
        ENABLE_FAIL2BAN: 1
        ENABLE_POSTGREY: 0
        ONE_DIR: 1
        DMS_DEBUG: 1
        ENABLE_LDAP: 1
        LDAP_SERVER_HOST: "{{ ldap_fsd_ip4 }}:{{ ldap_fsd_port }}"
        LDAP_SEARCH_BASE: "{{ ldap_search_base }}"
        LDAP_BIND_DN: "{{ ldap_fsd_username }}"
        LDAP_BIND_PW: "{{ ldap_fsd_password }}"
        LDAP_QUERY_FILTER_USER: (mail=%s)
        LDAP_QUERY_FILTER_GROUP: (mailGroupMember=%s)
        LDAP_QUERY_FILTER_ALIAS: (mailalias=%s)
        LDAP_QUERY_FILTER_DOMAIN: "(|(mail=*@%s)(mailalias=*@%s))"

        #DOVECOT_PASS_FILTER: (&(objectClass=inetOrgPerson)(|(uid=%u)(mail=%u)))
        DOVECOT_USER_FILTER: (&(objectClass=inetOrgPerson)(|(uid=%u)(mail=%u)))
        DOVECOT_PASS_ATTRS: uid=user,userPassword=password
        DOVECOT_USER_ATTRS: "=home=/var/mail/%{ldap:uid},=mail=maildir:~/Maildir,uidNumber=uid,gidNumber=gid"
        #DOVECOT_USER_ATTRS: "=home=/var/mail/%u,uidNumber=mail_uid,gidNumber=mail_gid,uidNumber=uid,gidNumber=gid"

        ENABLE_SASLAUTHD: 0
        SASLAUTHD_MECHANISMS: ldap
        SASLAUTHD_LDAP_SERVER: "{{ ldap_fsd_ip4 }}:{{ ldap_fsd_port }}"
        SASLAUTHD_LDAP_BIND_DN: "{{ ldap_fsd_username }}"
        SASLAUTHD_LDAP_PASSWORD: "{{ ldap_fsd_password }}"
        SASLAUTHD_LDAP_SEARCH_BASE: "{{ ldap_search_base }}"
        SASLAUTHD_LDAP_FILTER: (mail=%n)
        POSTMASTER_ADDRESS: postmaster@localhost.localdomain
        POSTFIX_MESSAGE_SIZE_LIMIT: 100000000
      volumes:
        - /etc/email-mock-service/config/:/tmp/docker-mailserver/:Z
```

### Relevant log output

```shell
ERRO[0011] unable to cleanup network for container 0e567a57002a12fc211881764ed25fcc52d20e67603bce7d6c1652502cd82e6b: "error tearing down CNI namespace configuration for container 0e567a57002a12fc211881764ed25fcc52d20e67603bce7d6c1652502cd82e6b: error removing pod email-mock-service_email-mock-service from CNI network \"podman\": running [/sbin/iptables -t nat -D POSTROUTING -s 10.88.0.5 -j CNI-377c0b712fa4eee995d8eec7 -m comment --comment name: \"podman\" id: \"0e567a57002a12fc211881764ed25fcc52d20e67603bce7d6c1652502cd82e6b\" --wait]: exit status 2: iptables v1.8.4 (nf_tables): Chain 'CNI-377c0b712fa4eee995d8eec7' does not exist\nTry `iptables -h' or 'iptables --help' for more information.\n"
```

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [X] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution
