### ISSUE TITLE
Recipient address rejected: User unknown in local recipient table

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [docker-mailserver/docker-mailserver#2515]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

docker mailserver compose.yaml

### What happened and when does this occur?

```Markdown
I use the docker mailserver in Ubuntu behind a Firewall.
If I use the out of the Box Settings I cannot send E-Mails to the Mailserver with the following error:


Even with the following try it did not work:

For your compose.yaml file, remove any domainname field, only use hostname field with full FQDN.

The only way to fix it was to change the main.cf manually and change mydestination to

mydestination = localhost.$mydomain, localhost
```

### What did you expect to happen?

```Markdown
That I can send E-Mails without error
```

### How do we replicate the issue?

```Markdown
Use the out of the Box config
Configure Hostname and Domain at docker-compose.yaml
Run the mailserver at a local network
Forward the ports through a firewall to the outside ip
Try to send a e-mail to the mailserver.
Sending from it works out of the box.

Then change the main.cf as shown before and it will work.
```

### DMS version

10.5.0

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yaml
Non working one: 

version: '3.7'

services:

mailserver:

image: docker.io/mailserver/docker-mailserver:latest

container\_name: mailserver

hostname: FQDN (external and internal reachable) # <-- CHANGE THIS

domainname: MyDomain#<-- CHANGE THIS

env\_file: mailserver.env

# More information about the mail-server ports:

# <https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-port>>

# To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.

ports:

  - "25:25"    # SMTP  (explicit TLS => STARTTLS)

  - "143:143"  # IMAP4 (explicit TLS => STARTTLS)

  - "465:465"  # ESMTP (implicit TLS)

  - "587:587"  # ESMTP (explicit TLS => STARTTLS)

  - "993:993"  # IMAP4 (implicit TLS)

volumes:

  - ./data/mail-data/:/var/mail/

  - ./data/mail-state/:/var/mail-state/

  - ./data/dms/mail-logs/:/var/log/mail/

  - ./config/:/tmp/docker-mailserver/

  - /etc/localtime:/etc/localtime:ro

  - /home/pgsmailadmin/etc/letsencrypt/:/etc/letsencrypt/

  restart: always

stop\_grace\_period: 1m

cap\_add:

  - NET\_ADMIN

  - SYS\_PTRACE
```

### Relevant log output

```shell
from external mailserver when sending to docker mailserver (anonymized):

from external mailserver when sending to docker mailserver:

Diagnoseinformationen für Administratoren:
Generierender Server: externailmailserver.anonym.com
test@dockermailserver.com
dockermailserver.com
Remote Server returned '554 5.1.1 <dockermailserver.com #5.1.1 smtp; 550 5.1.1 <externailmailserver.anonym.com>: Recipient address rejected: User unknown in local recipient table>'
Ursprüngliche Nachrichtenköpfe:
Return-Path: <externailmailserver.anonym.com>
Received: from externailmailserver.anonym.com (localhost [127.0.0.1])
	by externailmailserver.anonym.com (Test e-Mail Services) with ESMTP id XXX
	for <test@dockermailserver.com>; Wed, 30 Mar 2022 07:09:01 +0200 (CEST)
Received: from [127.0.0.1] (helo=externailmailserver.anonym.com)
	by externailmailserver.anonym.com with ESMTP (eXpurgate 4.37.0)
	(envelope-from <test@dockermailserver.com>)
	id 6243e5ed-0412-7f0000012b03-7f000001e060-1
	for <test@dockermailserver.com>; Wed, 30 Mar 2022 07:09:01 +0200
Received: from externailmailserver.anonym.comm (anonymail [XXX])
	by externailmailserver.anonym.com (Anonym e-Mail Services) with ESMTPS
	for <test@dockermailserver.com>; Wed, 30 Mar 2022 07:09:01 +0200 (CEST)
Received: from externailmailserver.anonym.comm (XXX) by
 externailmailserver.anonym.comm (XXX) with Microsoft SMTP Server
 (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256) id
 15.1.2375.24; Wed, 30 Mar 2022 07:09:00 +0200
Received: from externailmailserver.anonym.comm ([fe80::19d2:673b:9e97:1891]) by
 externailmailserver.anonym.comm ([fe80::19d2:673b:9e97:1891%5]) with mapi id
 15.01.2375.024; Wed, 30 Mar 2022 07:09:00 +0200
From: "Geschwentner, Patrick" <patrick.geschwentner@mindbreeze.com>
To: Patrick Geschwentner <test@dockermailserver.com>
Subject: AW: 
Thread-Index: AQHYQ/Q992IK+l+sh0y19fhgM1F5MKzXYJ0g
Date: Wed, 30 Mar 2022 05:09:00 +0000
Message-ID: <8dfa2118822e439596c60004159a9553@mindbreeze.com>
References: <20220330050847.E6D192F901B8@mail.pgdatacenter.at>
In-Reply-To: <20220330050847.E6D192F901B8@mail.pgdatacenter.at>
Accept-Language: de-AT, en-US
Content-Language: de-DE
X-MS-Has-Attach:
X-MS-TNEF-Correlator:
x-originating-ip: [XXXX]
Content-Type: multipart/alternative;
	boundary="_000_8dfa2118822e439596c60004159a9553mindbreezecom_"
MIME-Version: 1.0
X-purgate-ID: 152191::1648616941-00000412-C0CB1843/0/0
X-purgate-type: clean
X-purgate-size: 3870
X-purgate-Ad: Categorized by eleven eXpurgate (R) http://www.eleven.de
X-purgate: clean
X-purgate: This mail is considered clean (visit http://www.eleven.de for further information)
```

### Other relevant information

```Markdown
.
```

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

### Improvements to this form?

```Markdown
.
```

**Comment by polarathene** [comment]
> ```gfm
> Even with the following try it did not work:
> 
> For your compose.yaml file, remove any domainname field, only use hostname field with full FQDN.
> ```

This portion of the user bug report was referencing [advice from me on a closed issue](https://github.com/docker-mailserver/docker-mailserver/issues/2514#issuecomment-1082474423). They cited [a closed 2019 issue](https://github.com/docker-mailserver/docker-mailserver/issues/1138#issuecomment-1080300494) as still relevant and affecting them, I requested that they open a new bug report.

---

> ```gfm
> The only way to fix it was to change the main.cf manually and change mydestination to
> 
> mydestination = localhost.$mydomain, localhost
> ```

I will assume the error you are trying to workaround is related to what should be logged by `docker-mailserver` container (with sufficient log level setting) from the [original issue](https://github.com/docker-mailserver/docker-mailserver/issues/1138#issuecomment-470187757):

> _warning: do not list domain <domain>.online in BOTH mydestination and virtual_mailbox_domains_

I am wondering if you looked at our docs FAQ, specifically [this item](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#can-i-use-nakedbare-domains-no-host-name)? Notice that it uses the workaround you have applied.

As you did not provide a helpful `docker-compose.yaml` example and anonymized your domain without much information. I assume you are using something like `example.com` instead of `mail.example.com`?

You would have DNS with MX record for `mail.example.com` point to your `docker-mailserver` machine/server usually, and still use `hello@example.com`. Some users seem to misunderstand and think you would have to use `hello@mail.example.com`; perhaps you have also thought so and configured your setup to avoid the `mail` subdomain record?

**Comment by georglauterbach** [comment]
> Forward the ports through a firewall to the outside ip

How exactly did you do that? Are you using the PROXY protocol? Otherwise spf checks will fail.

---

@polarathene privided some nice feedback, I can also concur.

**Comment by MrLoverLoverMMMM** [comment]
Hello!I have a public an intern dns + mx to the same server.Thats how i did it.It works by the way with my workarround.
-------- Ursprüngliche Nachricht --------Von: Georg Lauterbach ***@***.***> Datum: 30.03.22  14:35  (GMT+01:00) An: docker-mailserver/docker-mailserver ***@***.***> Cc: MrLoverLoverMMMM ***@***.***>, Author ***@***.***> Betreff: Re: [docker-mailserver/docker-mailserver] Recipient address rejected:
  User unknown in local recipient table (Issue #2515) 

Forward the ports through a firewall to the outside ip

How exactly did you do that? Are you using the PROXY protocol? Otherwise spf checks will fail.

@polarathene privided some nice feedback, I can also concur.

**Comment by georglauterbach** [comment]
Use [`user-patches.sh`](https://docker-mailserver.github.io/docker-mailserver/edge/faq/#how-to-adjust-settings-with-the-user-patchessh-script) and `sed`.

**Comment by MrLoverLoverMMMM** [comment]
Out of the box would be niceOr more easy, but ill use the workarround
-------- Ursprüngliche Nachricht --------Von: Georg Lauterbach ***@***.***> Datum: 30.03.22  17:22  (GMT+01:00) An: docker-mailserver/docker-mailserver ***@***.***> Cc: MrLoverLoverMMMM ***@***.***>, Author ***@***.***> Betreff: Re: [docker-mailserver/docker-mailserver] Recipient address rejected:
  User unknown in local recipient table (Issue #2515) 
Use user-patches.sh and sed.

**Comment by polarathene** [comment]
> as domain i have configured: `example.com` and as `hostname: mail.example.com`

Do not use:

```yaml
hostname: mail.example.com
domainname: example.com
```

Only use one of these:

```yaml
hostname: mail.example.com

# or old way:

hostname: mail
domainname: example.com
```

Avoid sharing common labels in `hostname` if you also use `domainname` it will give you unexpected problems.

---

> Out of the box would be niceOr more easy, but ill use the workarround

We cannot out of the box configure for everyones different setups. We choose to support defaults that work for majority of users.
