### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by VetheonGames** [docker-mailserver/docker-mailserver#2621]
# Subject
Documentation unclear

## Description

I have *NO IDEA* where to start setting this up. Do I clone the repository? Do I pull the Docker image? Do I do something otherwise? I don't know. 

I have read through ***EVERY OUNCE*** of provided documentation, watched several youtube videos, and read articles that weren't written by the team/person behind this project yet I still have *no idea how to start*.

So, I just wanna know, how do I start using this? I follow the documentation step by step but it's a mess! It makes no sense! THe steps are out of order, you need the setup.sh but you don't need it at the same time?

Is this project abandoned and not functional anymore and I'm banging my head off my desk for no reason?

Or is the documentation convoluted and hard to understand on purpose?

It really should NOT be that hard to just ***list the commands we need in the order we need to run them like every other developer on the planet***

Please. Someone. Provide me a link to documentation that  was written by someone with a handle on how to write tutorials? Because everything I've found docs wise regarding this container and image is non-sensical.

**Comment by VetheonGames** [comment]
Nevermind. I've decided to just completely forego using this or Docker at all. I've learned just how terrible docker is when compared to the software it shamelessly rips off. 

Later docker nerds!

**Comment by polarathene** [comment]
## TL;DR

I'm not sure why you've had trouble getting started, we seem to cover this well?

I have provided a simple 3 step guide below (add a config, run two commands, done).

I care about our docs being better, so if you'd be so kind as to help me figure out a better way to communicate what you'd need to know, please provide more feedback :)

## Full response

> So, I just wanna know, how do I start using this? I follow the documentation step by step but it's a mess! It makes no sense!
> The steps are out of order, you need the `setup.sh` but you don't need it at the same time?

Hi, this project was in a much worse state a couple years back. I and other volunteers have contributed significant time to address this and make it better for users.

We'd appreciate your feedback to be more detailed so we could work through that frustration you went through and learn early on where you started from so that we can improve that experience for other users like yourself in future. It's a big project and volunteers only have so much time to spare, but our docs are important for us to get right too.

---

Regarding `setup.sh` it's a CLI helper with some commands for administration that makes it easier for the user to perform certain actions. You are most likely to use it to setup the first e-mail account to get the project running.

At a later point the bulk of the `setup.sh` functionality was moved into the container as a `setup` command that can be called with `docker exec -it <container-name> setup <command>` instead, so that you don't need to rely on an external `setup.sh` script. `setup.sh` is still preferred by some users, and while mostly a wrapper now, it does provide some extra functionality that's mostly useful if you don't have a container already running, or want to type just a little less.

---

> Is this project abandoned and not functional anymore and I'm banging my head off my desk for no reason?

Look at the project activity? You'll see I'm regularly contributing improvements / fixes and responding to both user issues and discussions and resolving those as best I can, as are other maintainers. We have reasonably frequent releases as well.

Why would you consider that abandoned because you had difficulty, while many others are not? I would say that while we'd love to improve what we can to make your experience better, that you cannot place all the blame on us? It seems that you're new to some technologies like Docker, and perhaps mail servers (and their specific DNS records) are new to you as well?

We cannot teach you everything you should know, our focus is to make setting up a mail-server easier and is where our effort is spent. Many users have different needs and environments, but we provide the project like other Docker projects, with the assumption that you know how to use Docker. Our project is a bit more complicated being a mail-server, with all the configuration you must handle on your end, along with us providing a single container bundling multiple services (but this is one of the reasons users choose our project in particular).

---

> Or is the documentation convoluted and hard to understand on purpose?

No.. I worked very hard actually to clean our docs up from an original Github Wiki that was full of broken links and outdated information. We now have docs that are in sync with the git project commits, that automatically deploy, and has a nice web interface with additional features that Github Wiki lacked.

I assure you the docs are in a much nicer state than they once were, and that I've sunk tens of hours into making them better myself. You as a user may take for granted what you see, but it's a lot more work than it looks. I was confused and frustrated like you and I had much worse to work with.

Instead of complaining and running away, I got informed myself and contributed back to the community for the benefit of others. You don't have to do what I have, but you could assist volunteers like myself who are eager to help the community, by letting us know where you get stuck and we can improve our docs from that point as we go.

It's otherwise entitled to believe our docs should be perfect, when you're not willing to engage with us to help improve them. They can only get better when we have users share the pain points. I can only assume you've not volunteered / contributed to anything yet, and have high expectations for an open-source project maintained by unpaid volunteers and provided to you for free? You're welcome to do it all yourself, or pay someone to make things easy for you?

---

> It really should NOT be that hard to just list the commands we need in the order we need to run them like every other developer on the planet

Lets look at the [README](https://github.com/docker-mailserver/docker-mailserver#usage) shall we?

1. Get `docker-compose.yml`, `mailserver.env`, `setup.sh` files.
   
   ```bash
   DMS_GITHUB_URL='https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/master'
   wget "${DMS_GITHUB_URL}/docker-compose.yml"
   wget "${DMS_GITHUB_URL}/mailserver.env"
   wget "${DMS_GITHUB_URL}/setup.sh"
   chmod a+x ./setup.sh
   ```
   
   Don't forget to edit `docker-compose.yml` and `mailserver.env` to your needs. If you have absolutely no idea what that is and want to start with the bare minimum, don't even bother with `mailserver.env`, just use this `docker-compose.yml` instead:
   
   ```yml
   services:
     mailserver:
       image: docker.io/mailserver/docker-mailserver:latest
       container_name: mailserver
       # This should be set to your DNS A record that you have an MX record pointing to,
       # Usually it's hosted on the same domain you want to send/receive as, eg `user@example.com`
       # The 'mail' part is to point to your MTA (this container), and does not affect your mail address,
       # Do not mistaken it as `user@mail.example.com`
       hostname: mail.example.com
       # More information about the mail-server ports:
       # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
       # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
       ports:
         # Port 25, mail sent to your server from others comes in through this port.
         - "25:25"
         # All four ports below may only be relevant to you with a mail client like ThunderBird
         # These two ports are only relevant if you want to send mail from your server,
         # and that mail client submitting the mail to send needs to be authorized via login.
         - "465:465"
         - "587:587"
         # IMAP4 - Only relevant if you want to read mail sent to your sever,
         # You only need the port your mail client uses.
         - "143:143"
         - "993:993"
       # Persist data across container restarts by mounting these local folders:
       volumes:
         - ./docker-data/dms/mail-data/:/var/mail/
         - ./docker-data/dms/mail-state/:/var/mail-state/
         - ./docker-data/dms/mail-logs/:/var/log/mail/
         - ./docker-data/dms/config/:/tmp/docker-mailserver/

2. Blah blah, skip passed helpful advice to [this part](https://github.com/docker-mailserver/docker-mailserver#starting-for-the-first-time):

   ```bash
   ./setup.sh email add user@example.com this-is-a-weak-password
   docker-compose up -d
   ```

Congratulations, you have a mail-server up and running! You'll need to actually have DNS setup properly of course, and perhaps you have some other issues or expectations... You weren't very clear with your struggle beyond getting the project up and running..

Once more, just for the sake of clarity:

- Create a `docker-compose.yml` configured like above.
- Start it `docker-compose up -d`
- Didn't setup an account with `setup.sh` earlier? You have 2 minutes during startup to add one:
   `docker exec -it mailserver setup email add user@example.com this-is-a-weak-password`
- Done!

I assume that's not a sufficient list for you, so why not chime in with what it's missing?

---

> I have NO IDEA where to start setting this up. Do I clone the repository? Do I pull the Docker image? Do I do something otherwise? I don't know.
> 
> I have read through EVERY OUNCE of provided documentation, watched several youtube videos, and read articles that weren't written by the team/person behind this project yet I still have no idea how to start.

Really...? You didn't come across anything like shown above? I made some minor tweaks from the referenced README, but you'd have become aware of such changes if you really did read our docs.

---

> Please. Someone. Provide me a link to documentation that was written by someone with a handle on how to write tutorials? Because everything I've found docs wise regarding this container and image is non-sensical.

Most of the docs are community contributions. I've revised a fair bit of it, but I can totally understand that we could do better here. If you're willing to engage, we can make that happen together.

---

> Nevermind. I've decided to just completely forego using this or Docker at all. I've learned just how terrible docker is when compared to the software it shamelessly rips off.

What software do you think is being shamelessly ripped off here? We aren't pretending that we don't use third-party software. This project integrates all the software you'd need to do yourself (some you may not need, we cater to a broad audience).

You're welcome to setup Postfix yourself, plenty of guides out there. Depending on your needs that can be easier too. The Postfix docs can get confusing at times if you have to actually dig into them. If your needs are basic, this could definitely be better/easier for you.

Where it can get more problematic is when you need to integrate with other software, Dovecot, Fail2Ban, Amavis+ClamAV+SpamAssassin, making config changes (including when your services get updated certs), what TLS policies you should use, account management, and so forth..

Those tutorials start to get long-winded, or worse you're juggling several separate ones and trying to blend them together (worse if they're severely out of date). All you're managing to do at that point is basically what this project handles (except we unify as a community to maintain it), but you are then responsible for all maintenance and keeping on top of things.

---

If you don't understand the benefits of Docker, that's fine. I wish you good luck.

I'm a little disheartened that you only seem interested in being disgruntled and disrespecting all the effort the community puts into making this project better. If you change your mind and would like to assist with improving our docs, that'd be awesome! :grinning:
