### ISSUE TITLE
[BUG] Can't drop privilege as nonroot user

### ISSUE THREAD

**Issue by Itzdlg** [docker-mailserver/docker-mailserver#2627]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

Unable to start the container with a non-root user.

### What happened and when does this occur?

```Markdown
I'm using docker-compose to launch docker-mailserver, but I've recently went on the hunt to properly manage the permissions of all the services on the container. In order to run the container, from the root user I run `sudo -u mailserver docker-compose up`. This works fine if I don't specify a user ID in the docker-compose.yml file, but once I do, supervisord complains: "Can't drop privilege as nonroot user."
```

### What did you expect to happen?

```Markdown
I expect for the container to run properly even without root privileges, assuming the user provided has rights for all the resources on the file system.
```

### How do we replicate the issue?

```Markdown
1. Set a string user ID in the docker-compose under `services.mailserver.user`
2. Attempt to run `docker-compose up` normally

or supply a user ID with the docker command.
```

### DMS version

docker.io/mailserver/docker-mailserver:latest

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yml
version: "3"
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail
    domainname: schooltests.me
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - /home/mailserver/mail-data/:/var/mail/
      - /home/mailserver/mail-state/:/var/mail-state/
      - /home/mailserver/mail-logs/:/var/log/mail/
      - /home/mailserver/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - "/etc/ssl/certs/schooltests.me/:/var/ssl/"
    user: "1000"
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
```

### Relevant log output

```bash
mailserver    | Error: Can't drop privilege as nonroot user
mailserver    | For help, use /usr/bin/supervisord -h
```

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution
