### ISSUE TITLE
[BUG] /etc/init.d/opendkim fails

### ISSUE THREAD

**Issue by Wunderharke** [docker-mailserver/docker-mailserver#2634]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

/etc/init.d/opendkim

### What happened and when does this occur?

```Markdown
Log shows `warning: connect to Milter service inet:localhost:8891: Connection refused` which indicates that opendkim isn't running. Which is indeed the case.

When bashing into the container any trying to start opendkim via `/etc/init.d/opendkim start` it returns `Starting OpenDKIM: install: invalid user ''`.

When looking into `/etc/init.d/opendkim` one can see that it relies on environment variable for `USER`and `GROUP`:
  
  USER=$USER
  GROUP=$GROUP

As well as `$RUNDIR` I believe.
```

### What did you expect to happen?

```Markdown
I expect opendkim to start automatically when the container is started.
```

### How do we replicate the issue?

```Markdown
1. docker pull monogramm/autodiscover-email-settings:latest
2. docker-compose ip

To check internal error:
1. docker exec -it <container-id> sh
2. su
3. /etc/init.d/opendkim start
```

### DMS version

latest

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yml
version: '2.1'
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: **Truncated for privacy**
    domainname: **Truncated for privacy**
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /opt/docker-mailserver/docker-data/dms/mail-data/:/var/mail/ -Z
      - /opt/docker-mailserver/docker-data/dms/mail-state/:/var/mail-state/ -Z
      - /opt/docker-mailserver/docker-data/dms/mail-logs/:/var/log/mail/ -Z
      - /opt/docker-mailserver/docker-data/dms/config/:/tmp/docker-mailserver/ -Z
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    extra_hosts:
      - **Truncated for privacy**
      - **Truncated for privacy**
      - "host.docker.internal:host-gateway"
  autodiscover:
    restart: always
    image: monogramm/autodiscover-email-settings:latest
    container_name: autodiscover
    environment:
      - COMPANY_NAME=**Truncated for privacy**
      - SUPPORT_URL=**Truncated for privacy**
      - DOMAIN=**Truncated for privacy**
      # IMAP configuration (host mandatory to enable)
      - IMAP_HOST=**Truncated for privacy**
      - IMAP_PORT=993
      - IMAP_SOCKET=SSL
      # SMTP configuration (host mandatory to enable)
      - SMTP_HOST=**Truncated for privacy**
      - SMTP_PORT=587
      - SMTP_SOCKET=STARTTLS
    ports:
      - **Truncated for privacy**
  ipv6nat:
    image: robbertkl/ipv6nat
    restart: always
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro
networks:
  default:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: fd00:0000:000e::/48
          gateway: fd00:0000:000e::1
        - subnet: 172.26.0.0/16
          gateway: 172.26.0.1
```

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

### Improvements to this form?

```Markdown
Make inexperienced user aware of privacy implications when posting docker-compose.yml.
```
