### ISSUE TITLE
Need help on SSL configuration

### ISSUE THREAD

**Issue by Caratpine** [docker-mailserver/docker-mailserver#2698]
logs error
```
 TLS Setup [SSL_TYPE=manual] | File /etc/letsencrypt/archive/mail.<domain>/privkey1.pem or /etc/letsencrypt/archive/mail.<domain>/fullchain1.pem does not exist!
```

I generated the certificate with this command
```
certbot certonly --manual --preferred-challenge dns -d mail.<domain>
```

my docker-compose.yml configuration
```
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: <domain>
    env_file: mailserver.env
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

my mailserver.env configuration
```
SSL_TYPE=manual
SSL_CERT_PATH=/etc/letsencrypt/archive/mail.<domain>/fullchain1.pem
SSL_KEY_PATH=/etc/letsencrypt/archive/mail.<domain>/privkey1.pem
```

I think the /etc/letsencrypt file in my host is not copied to the container, how to solve this? Thanks.
