### ISSUE TITLE
[BUG] dovecot: master: Error: bind(/var/spool/postfix/private/auth) failed: Operation not permitted

### ISSUE THREAD

**Issue by wietsewarendorff** [docker-mailserver/docker-mailserver#2700]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

Dovecot not starting

### What happened and when does this occur?

```Markdown
`docker-compose up -d` works fine, creating an account look ok too (`config/postfix-accounts.cf` shows entry, folder is created in mail-data), but `docker-compose logs` shows me the error "Failed to start listeners".

To me it looks like the process is looking in the wrong folder? If I am correct it should look into the folder `/var/mail-state/spool-postfix/private/auth` but apparently it's looking in the folder `/var/spool/postfix/private/auth`.

Some other issues that have "similar" issues (at least I see the permission problem):
https://github.com/docker-mailserver/docker-mailserver/issues/2678
https://github.com/docker-mailserver/docker-mailserver/issues/2630
```

### What did you expect to happen?

```Markdown
I do not expect these 3 error-lines to be in the logs (which are repeated every second). After adding the account, I cannot connect to it using an email-client.
```

### How do we replicate the issue?

```Markdown
I am using the (imho minimal) setup on a Macbook Pro (macOs Monterey, 12.4) with Docker Desktop 4.10.1 (82475), using the included docker-compose file.
I tried DMS 11.1.0, 11.0.0 and 10.5 but all have the same error messages.
```

### DMS version

v11.1.0

### What operating system is DMS running on?

macOS (not officially supported)

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yml
version: '3.7'

services:
    mailserver:
        image: mailserver/docker-mailserver
        hostname: mailserver
        domainname: mail.mydomain.com
        volumes:
          - ./mail-data/:/var/mail/
          - ./mail-state/:/var/mail-state/
          - ./mail-logs/:/var/log/mail/
          - ./config/:/tmp/docker-mailserver/
          - /etc/localtime:/etc/localtime:ro
        environment:
          - ENABLE_SPAMASSASSIN=0
          - SPAMASSASSIN_SPAM_TO_INBOX=0
          - ENABLE_CLAMAV=0
          - ENABLE_FAIL2BAN=0
          - ENABLE_POSTGREY=0
          - ENABLE_SASLAUTHD=0
          - ONE_DIR=1
        ports:
          - "25:25"
          - "143:143"
          - "465:465"
          - "587:587"
          - "993:993"
        cap_add:
          - NET_ADMIN
        env_file: ./mailserver.env
```

### Relevant log output

```bash
mailserver-1  | Jul 28 13:27:27 mailserver dovecot: master: Error: bind(/var/spool/postfix/private/auth) failed: Operation not permitted
mailserver-1  | Jul 28 13:27:27 mailserver dovecot: master: Error: service(auth): net_listen_unix(/var/spool/postfix/private/auth) failed: Operation not permitted
mailserver-1  | Jul 28 13:27:27 mailserver dovecot: master: Fatal: Failed to start listeners
```

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [X] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution
