### ISSUE TITLE
Dovecot LDAP Operations Error

### ISSUE THREAD

**Issue by tensor5g** [docker-mailserver/docker-mailserver#2711]
I am attempting to configure docker mailserver to use LDAP for authentication. I've spent several hours going over the documentation and have fixed a lot of problems I've ran into but I can't get past this one. When attempting to login via Thunderbird, I see the following error in DMS docker logs:
```dovecot: auth: Error: ldap(test@example.com,192.168.1.123,<Jnfofjflu37AqAHD>): ldap_search(base=DC=example,DC=com filter=(&(objectclass=person)(sAMAccountName=test))) failed: Operations error```

This is weird because if I run the exact same query in ldp on Windows I get a success:
```
***Searching...
ldap_search_s(ld, "DC=example,DC=com", 2, "(&(objectclass=person)(sAMAccountName=test))", attrList,  0, &msg)
Getting 1 entries:
Dn: CN=test,OU=User,OU=Accounts,DC=example,DC=com
canonicalName: example.com/Accounts/User/test; 
name: test; 
objectClass (4): top; person; organizationalPerson; user; 
```

I have a single domain controller (dc.example.com) running Windows Server 2019. It has SSL enabled on port 636 with a custom CA installed in DMS on startup. Before I did that, I was getting a different error, so I don't think SSL or being able to execute queries on the server is the problem.

Inspecting the security log on the DC reveals this error when I attempt to login to DMS with LDAP:
```
Log Name:      Security
Source:        Microsoft-Windows-Security-Auditing
Date:          8/2/2022 6:40:44 PM
Event ID:      4625
Task Category: Logon
Level:         Information
Keywords:      Audit Failure
User:          N/A
Computer:      DC.example.com
Description:
An account failed to log on.

Subject:
	Security ID:		SYSTEM
	Account Name:		DC$
	Account Domain:		EXAMPLE
	Logon ID:		0x3E7

Logon Type:			3

Account For Which Logon Failed:
	Security ID:		NULL SID
	Account Name:		test
	Account Domain:		EXAMPLE

Failure Information:
	Failure Reason:		Unknown user name or bad password.
	Status:			0xC000006D
	Sub Status:		0xC000006A

Process Information:
	Caller Process ID:	0x278
	Caller Process Name:	C:\Windows\System32\lsass.exe

Network Information:
	Workstation Name:	DC
	Source Network Address:	(docker host IP)
	Source Port:		42226

Detailed Authentication Information:
	Logon Process:		Advapi  
	Authentication Package:	MICROSOFT_AUTHENTICATION_PACKAGE_V1_0
	Transited Services:	-
	Package Name (NTLM only):	-
	Key Length:		0
```

I've triple check username and password, they are correct. So I have run out of things I can try. Here is my docker-compose file:
```yml
version: '3.3'
services:
    docker-mailserver:
      restart: unless-stopped
      container_name: mail_test
      ports:
        - "(docker host ip):25:25"
        - "(docker host ip):143:143"
        - "(docker host ip):587:587"

      environment:
        - OVERRIDE_HOSTNAME=mail_test.example.com
        - ENABLE_SPAMASSASSIN=0
        - ENABLE_CLAMAV=0
        - ENABLE_FAIL2BAN=0
        - ENABLE_POSTGREY=0
        - ONE_DIR=1
        - POSTFIX_INET_PROTOCOLS=ipv4
        - TZ=America/Chicago
        - LOG_LEVEL=trace

        - SSL_TYPE=manual
        - SSL_CERT_PATH=/tmp/docker-mailserver/pub.pem
        - SSL_KEY_PATH=/tmp/docker-mailserver/priv.pem

        - ENABLE_LDAP=1
        - LDAP_SERVER_HOST=ldaps://dc.example.com:636
        - LDAP_BIND_DN=CN=Admin,OU=User,OU=Accounts,DC=example,DC=com
        - LDAP_BIND_PW=****
        - LDAP_SEARCH_BASE=DC=example,DC=com

        - SPOOF_PROTECTION=1
        - LDAP_QUERY_FILTER_DOMAIN=(mail=*@%s)
        - LDAP_QUERY_FILTER_USER=(&(objectclass=person)(mail=%s))
        - LDAP_QUERY_FILTER_ALIAS=(&(objectclass=person)(proxyAddresses=smtp:%s))
        - LDAP_QUERY_FILTER_GROUP=(&(objectClass=group)(mail=%s))
        - LDAP_QUERY_FILTER_SENDERS=(mail=%s)

        - DOVECOT_USER_FILTER=(&(objectclass=person)(sAMAccountName=%n))
        - DOVECOT_USER_ATTRS==uid=5000,=gid=5000,=home=/var/mail/%Ln,=mail=maildir:~/Maildir
        - DOVECOT_PASS_ATTR=sAMAccountName=user,userPassword=password

        - ENABLE_SASLAUTHD=1
        - SASLAUTHD_MECHANISMS=ldap
        - SASLAUTHD_LDAP_FILTER=(&(sAMAccountName=%U)(objectClass=person))
      
      volumes:
        - 'data:/var/mail'
        - 'state:/var/mail-state'
        - 'logs:/var/log/mail'
        - 'config:/tmp/docker-mailserver/'

      image: 'mailserver/docker-mailserver:11.1.0'

volumes:
  data:
  state:
  logs:
  config:
```

And here are my Thunderbird settings:
![image](https://user-images.githubusercontent.com/74799905/182497413-b0223fb4-768d-48fb-afd2-d3881ec45a29.png)
