### ISSUE TITLE
Basic Configuration for receiving emails locally via SMTP

### ISSUE THREAD

**Issue by katefike** [docker-mailserver/docker-mailserver#2740]
# Subject
Other

## Description
I want to configure container to receive emails locally via SMTP. No authentication is needed. The problem is that I get the following error when I try to receive an email: 
```
mailserver  | Aug 21 14:04:09 mail postfix/smtpd[1121]: NOQUEUE: reject: RCPT from unknown[xxx.xxx.xx.x]: 454 4.7.1 <incoming@example.com>: Relay access denied; from=<root@localhost> to=<incoming@example.com> proto=ESMTP helo=<localhost>
```

I will show my docker-compose.yml and config files, then I'll show how I produced the error above.

### docker-compose.yml
- Note that I mounted my config files in a different directory (`./docker-data/configs/`) so that I could change the file permissions while working on the config. Not sure if this was a dumb decision or if there's an easier way to lower the permissions, but it hasn't been causing me problems so far that I'm aware of. 
```
version: '3.8'
services:
  mailserver:
      image: docker.io/mailserver/docker-mailserver:latest
      container_name: mailserver
      restart: always
      env_file:
        - .env
      # If the FQDN for your mail-server is only two labels (eg: example.com),
      # you can assign this entirely to `hostname` and remove `domainname`.
      # Override in .env is called OVERRIDE_HOSTNAME
      hostname: mail
      domainname: example.com
      # More information about the mail-server ports:
      # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
      # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
      ports:
        - "25:25"    # SMTP  (explicit TLS => STARTTLS)
        - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
        - "465:465"  # ESMTP (implicit TLS)
        - "587:587"  # ESMTP (explicit TLS => STARTTLS)
        - "993:993"  # IMAP4 (implicit TLS)
      volumes:
        - ./docker-data/dms/mail-data/:/var/mail/
        - ./docker-data/dms/mail-state/:/var/mail-state/
        - ./docker-data/dms/mail-logs/:/var/log/mail/
        - ./docker-data/dms/config/:/tmp/docker-mailserver/
        - ./docker-data/configs/postfix-main.cf:/etc/postfix/main.cf
        - ./docker-data/configs/postfix-master.cf:/etc/postfix/master.cf
        - ./docker-data/configs/postfix-aliases:/etc/aliases
        - /etc/localtime:/etc/localtime:ro
      stop_grace_period: 1m
      cap_add:
        - NET_ADMIN
      healthcheck:
        test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
        timeout: 3s
        retries: 0
```
### postfix-main.cf
```
smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
myhostname = localhost
alias_maps = hash:/etc/aliases
alias_database = hash:/etc/aliases
myorigin = localhost
mydestination = mail, localhost.example.com, localhost
relayhost = 
mynetworks = 127.0.0.0/8 [::1]/128 [fe80::]/64
mailbox_size_limit = 0
recipient_delimiter = +
inet_interfaces = all
inet_protocols = all
local_recipient_maps =
home_mailbox = Maildir/
``` 
### postfix-master.cf
```
# Postfix master process configuration file.  For details on the format
# of the file, see the master(5) manual page (command: "man 5 master" or
# on-line: http://www.postfix.org/master.5.html).
#
# Do not forget to execute "postfix reload" after editing this file.
#
# ==========================================================================
# service type  private unpriv  chroot  wakeup  maxproc command + args
#               (yes)   (yes)   (no)    (never) (100)
# ==========================================================================
smtp      inet  n       -       y       -       -       smtpd
#smtp      inet  n       -       y       -       1       postscreen
#smtpd     pass  -       -       y       -       -       smtpd
#dnsblog   unix  -       -       y       -       0       dnsblog
#tlsproxy  unix  -       -       y       -       0       tlsproxy
# Choose one: enable submission for loopback clients only, or for any client.
#127.0.0.1:submission inet n -   y       -       -       smtpd
#submission inet n       -       y       -       -       smtpd
#  -o syslog_name=postfix/submission
#  -o smtpd_tls_security_level=encrypt
#  -o smtpd_sasl_auth_enable=yes
#  -o smtpd_tls_auth_only=yes
#  -o smtpd_reject_unlisted_recipient=no
#  -o smtpd_client_restrictions=$mua_client_restrictions
#  -o smtpd_helo_restrictions=$mua_helo_restrictions
#  -o smtpd_sender_restrictions=$mua_sender_restrictions
#  -o smtpd_recipient_restrictions=
#  -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
#  -o milter_macro_daemon_name=ORIGINATING
# Choose one: enable smtps for loopback clients only, or for any client.
#127.0.0.1:smtps inet n  -       y       -       -       smtpd
#smtps     inet  n       -       y       -       -       smtpd
#  -o syslog_name=postfix/smtps
#  -o smtpd_tls_wrappermode=yes
  -o smtpd_sasl_auth_enable=yes
#  -o smtpd_reject_unlisted_recipient=no
#  -o smtpd_client_restrictions=$mua_client_restrictions
#  -o smtpd_helo_restrictions=$mua_helo_restrictions
#  -o smtpd_sender_restrictions=$mua_sender_restrictions
#  -o smtpd_recipient_restrictions=
#  -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
#  -o milter_macro_daemon_name=ORIGINATING
#628       inet  n       -       y       -       -       qmqpd
pickup    unix  n       -       y       60      1       pickup
cleanup   unix  n       -       y       -       0       cleanup
qmgr      unix  n       -       n       300     1       qmgr
#qmgr     unix  n       -       n       300     1       oqmgr
tlsmgr    unix  -       -       y       1000?   1       tlsmgr
rewrite   unix  -       -       y       -       -       trivial-rewrite
bounce    unix  -       -       y       -       0       bounce
defer     unix  -       -       y       -       0       bounce
trace     unix  -       -       y       -       0       bounce
verify    unix  -       -       y       -       1       verify
flush     unix  n       -       y       1000?   0       flush
proxymap  unix  -       -       n       -       -       proxymap
proxywrite unix -       -       n       -       1       proxymap
smtp      unix  -       -       y       -       -       smtp
relay     unix  -       -       y       -       -       smtp
        -o syslog_name=postfix/$service_name
#       -o smtp_helo_timeout=5 -o smtp_connect_timeout=5
showq     unix  n       -       y       -       -       showq
error     unix  -       -       y       -       -       error
retry     unix  -       -       y       -       -       error
discard   unix  -       -       y       -       -       discard
local     unix  -       n       n       -       -       local
virtual   unix  -       n       n       -       -       virtual
lmtp      unix  -       -       y       -       -       lmtp
anvil     unix  -       -       y       -       1       anvil
scache    unix  -       -       y       -       1       scache
postlog   unix-dgram n  -       n       -       1       postlogd
#
# ====================================================================
# Interfaces to non-Postfix software. Be sure to examine the manual
# pages of the non-Postfix software to find out what options it wants.
#
# Many of the following services use the Postfix pipe(8) delivery
# agent.  See the pipe(8) man page for information about ${recipient}
# and other message envelope options.
# ====================================================================
#
# maildrop. See the Postfix MAILDROP_README file for details.
# Also specify in main.cf: maildrop_destination_recipient_limit=1
#
maildrop  unix  -       n       n       -       -       pipe
  flags=DRXhu user=vmail argv=/usr/bin/maildrop -d ${recipient}
#
# ====================================================================
#
# Recent Cyrus versions can use the existing "lmtp" master.cf entry.
#
# Specify in cyrus.conf:
#   lmtp    cmd="lmtpd -a" listen="localhost:lmtp" proto=tcp4
#
# Specify in main.cf one or more of the following:
#  mailbox_transport = lmtp:inet:localhost
#  virtual_transport = lmtp:inet:localhost
#
# ====================================================================
#
# Cyrus 2.1.5 (Amos Gouaux)
# Also specify in main.cf: cyrus_destination_recipient_limit=1
#
#cyrus     unix  -       n       n       -       -       pipe
#  flags=DRX user=cyrus argv=/cyrus/bin/deliver -e -r ${sender} -m ${extension} ${user}
#
# ====================================================================
# Old example of delivery via Cyrus.
#
#old-cyrus unix  -       n       n       -       -       pipe
#  flags=R user=cyrus argv=/cyrus/bin/deliver -e -m ${extension} ${user}
#
# ====================================================================
#
# See the Postfix UUCP_README file for configuration details.
#
uucp      unix  -       n       n       -       -       pipe
  flags=Fqhu user=uucp argv=uux -r -n -z -a$sender - $nexthop!rmail ($recipient)
#
# Other external delivery methods.
#
ifmail    unix  -       n       n       -       -       pipe
  flags=F user=ftn argv=/usr/lib/ifmail/ifmail -r $nexthop ($recipient)
bsmtp     unix  -       n       n       -       -       pipe
  flags=Fq. user=bsmtp argv=/usr/lib/bsmtp/bsmtp -t$nexthop -f$sender $recipient
scalemail-backend unix -       n       n       -       2       pipe
  flags=R user=scalemail argv=/usr/lib/scalemail/bin/scalemail-store ${nexthop} ${user} ${extension}
mailman   unix  -       n       n       -       -       pipe
  flags=FRX user=list argv=/usr/lib/mailman/bin/postfix-to-mailman.py ${nexthop} ${user}
```
### Producing the Error
1. One user account was set up via `setup.sh` after I started the container for the very first time. The account is at incoming@example.com
![image](https://user-images.githubusercontent.com/81718723/185804685-78e50408-fc22-44d6-a7ab-a198e4121ca1.png)
2. I start the container. I get the following docker logs:
```
mailserver  | [   INF   ]  Welcome to docker-mailserver 11.1.0
mailserver  | [   INF   ]  Initializing setup
mailserver  | [   INF   ]  Checking configuration
mailserver  | [   INF   ]  Configuring mail server
mailserver  | [ WARNING ]  !! INSECURE !! SSL configured with plain text access - DO NOT USE FOR PRODUCTION DEPLOYMENT
mailserver  | [   INF   ]  Post-configuration checks
mailserver  | [   INF   ]  Starting miscellaneous tasks
mailserver  | [   INF   ]  Starting daemons
mailserver  | [   INF   ]  mail.example.com is up and running
mailserver  | Aug 21 13:47:30 mail amavis[707]: starting. /usr/sbin/amavisd-new at mail.example.com amavisd-new-2.11.1 (20181009), Unicode aware, LC_CTYPE="C.UTF-8"
mailserver  | Aug 21 13:47:30 mail amavis[707]: perl=5.032001, user=, EUID: 112 (112);  group=, EGID: 114 114 (114 114)
mailserver  | Aug 21 13:47:30 mail amavis[707]: Net::Server: Group Not Defined.  Defaulting to EGID '114 114'
mailserver  | Aug 21 13:47:30 mail amavis[707]: Net::Server: User Not Defined.  Defaulting to EUID '112'
mailserver  | Aug 21 13:47:30 mail amavis[707]: No ext program for   .zoo, tried: zoo
mailserver  | Aug 21 13:47:30 mail amavis[707]: No ext program for   .doc, tried: ripole
mailserver  | Aug 21 13:47:30 mail amavis[707]: No decoder for       .F   
mailserver  | Aug 21 13:47:30 mail amavis[707]: No decoder for       .doc 
mailserver  | Aug 21 13:47:30 mail amavis[707]: No decoder for       .zoo
```
3. I use telnet to try to send an email
```
kfike@cutie:~$ telnet localhost 25
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
220 localhost ESMTP Postfix
ehlo localhost
250-localhost
250-PIPELINING
250-SIZE 10240000
250-VRFY
250-ETRN
250-AUTH DIGEST-MD5 NTLM CRAM-MD5 LOGIN PLAIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 CHUNKING
mail from: root@localhost
250 2.1.0 Ok
rcpt to: incoming@example.com
454 4.7.1 <incoming@example.com>: Relay access denied
```
And I get the following docker logs:
```
mailserver  | Aug 21 14:03:40 mail postfix/smtpd[1121]: connect from unknown[192.168.48.1]
mailserver  | Aug 21 14:04:09 mail postfix/smtpd[1121]: NOQUEUE: reject: RCPT from unknown[xxx.xxx.xx.x]: 454 4.7.1 <incoming@example.com>: Relay access denied; from=<root@localhost> to=<incoming@example.com> proto=ESMTP helo=<localhost>
```
### Failed Attempts to Fix the Error
I tried to fix the error by changing the following in `postfix-main.cf`:
- change `myhostname = localhost` to `myhostname = mail`
- change `myorigin = localhost` to `myorigin = /etc/mailname`
- change `mydestination = mail, localhost.example.com, localhost` to 
`mydestination = mydestination = mail.example.com, example.com, localhost.example.com, localhost.localdomain, localhost`

After restarting the container, I execute the following in telnet:
```kfike@cutie:~$ telnet localhost 25
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
220 mail ESMTP Postfix
ehlo mail
250-mail
250-PIPELINING
250-SIZE 10240000
250-VRFY
250-ETRN
250-AUTH DIGEST-MD5 NTLM CRAM-MD5 LOGIN PLAIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 CHUNKING
mail from: root@localhost
250 2.1.0 Ok
rcpt to: incoming@example.com
250 2.1.5 Ok
data
354 End data with <CR><LF>.<CR><LF>
Subject: Test email 1
test email body
.
250 2.0.0 Ok: queued as 24A27A3672
```
And I get the following docker logs:
```
mailserver  | Aug 21 14:16:24 mail postfix/smtpd[705]: warning: hostname cutie does not resolve to address xxx.xxx.xx.x
mailserver  | Aug 21 14:16:24 mail postfix/smtpd[705]: connect from unknown[xxx.xxx.xx.x]
mailserver  | Aug 21 14:16:35 mail postfix/trivial-rewrite[749]: using backwards-compatible default setting append_dot_mydomain=yes to rewrite "localhostrcpt" to "localhostrcpt.localdomain"
mailserver  | Aug 21 14:17:12 mail postfix/smtpd[705]: disconnect from unknown[xxx.xxx.xx.x] ehlo=1 mail=0/1 rcpt=0/1 data=0/1 quit=1 commands=2/5
mailserver  | Aug 21 14:17:14 mail postfix/smtpd[705]: warning: hostname cutie does not resolve to address xxx.xxx.xx.x
mailserver  | Aug 21 14:17:14 mail postfix/smtpd[705]: connect from unknown[xxx.xxx.xx.x]
mailserver  | Aug 21 14:17:33 mail postfix/smtpd[705]: 24A27A3672: client=unknown[xxx.xxx.xx.x]
mailserver  | Aug 21 14:17:55 mail postfix/cleanup[905]: 24A27A3672: message-id=<>
mailserver  | Aug 21 14:17:55 mail postfix/qmgr[672]: 24A27A3672: from=<root@localhost.localdomain>, size=201, nrcpt=1 (queue active)
mailserver  | Aug 21 14:17:55 mail postfix/local[960]: warning: database /etc/aliases.db is older than source file /etc/aliases
mailserver  | Aug 21 14:17:55 mail postfix/local[960]: 24A27A3672: to=<incoming@example.com>, relay=local, delay=27, delays=27/0.01/0/0.01, dsn=5.1.1, status=bounced (unknown user: "incoming")
mailserver  | Aug 21 14:17:55 mail postfix/cleanup[905]: 6D85BA36C5: message-id=<20220821181755.6D85BA36C5@mail>
mailserver  | Aug 21 14:17:55 mail postfix/bounce[965]: 24A27A3672: sender non-delivery notification: 6D85BA36C5
mailserver  | Aug 21 14:17:55 mail postfix/qmgr[672]: 6D85BA36C5: from=<>, size=1888, nrcpt=1 (queue active)
mailserver  | Aug 21 14:17:55 mail postfix/qmgr[672]: 24A27A3672: removed
mailserver  | Aug 21 14:17:55 mail postfix/local[960]: 6D85BA36C5: to=<root@localhost.localdomain>, relay=local, delay=0.01, delays=0/0/0/0, dsn=2.0.0, status=sent (delivered to maildir)
mailserver  | Aug 21 14:17:55 mail postfix/qmgr[672]: 6D85BA36C5: removed
```

I'm unsure if this attempt at a fix helped or made it worse. I'm open to any suggestions and resources that will get me closer to being able to successfully receive emails locally. Thanks!
