### ISSUE TITLE
how to get the correct folder permissions to get started

### ISSUE THREAD

**Issue by lan10rd** [docker-mailserver/docker-mailserver#2762]
I already have a `/letsyencrypt` folder that is used by nginx and other docker apps. I tried mounting it the same way and got _"permission denied"_, along with other important mounts.

---

**`docker-compose.yml`:**
```yml
version: '3.7'

x-swarm:
  enabled: true
services:

  server:
    image: mailserver/docker-mailserver
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail
    domainname: myname.tld
    # env_file: mailserver.env
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "110:110"
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    environment:
      - OVERRIDE_HOSTNAME=mail.myname.tld
      - PERMIT_DOCKER=network
      - SSL_TYPE=letsencrypt
      - ONE_DIR=1
      - DMS_DEBUG=1
      - SPOOF_PROTECTION=0
      - REPORT_RECIPIENT=1
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=0
    networks:
      - realms_glass_overlay
    volumes:
      - ./mailserver/var/mail:/var/mail/
      - ./mailserver/var/mail-state:/var/mail-state/
      - ./mailserver/var/mail-log:/var/log/mail/
      - ./mailserver/config/:/tmp/docker-mailserver/
      - ./certbot/etc/letsencrypt/:/etc/letsencrypt/
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

**Logs:**

```
mailserver.1.v5lnv8mkfjrf@simba    | [   INF   ]  Welcome to docker-mailserver 11.1.0
mailserver.1.v5lnv8mkfjrf@simba    | [   INF   ]  Initializing setup
mailserver.1.v5lnv8mkfjrf@simba    | [   INF   ]  Checking configuration
mailserver.1.v5lnv8mkfjrf@simba    | [   INF   ]  Configuring mail server
mailserver.1.v5lnv8mkfjrf@simba    | chown: changing ownership of '/var/log/mail': Permission denied
mailserver.1.v5lnv8mkfjrf@simba    | chown: changing ownership of '/var/log/mail/clamav.log': Permission denied
mailserver.1.v5lnv8mkfjrf@simba    | chown: changing ownership of '/var/log/mail/freshclam.log': Permission denied
mailserver.1.v5lnv8mkfjrf@simba    | sha512sum: /etc/letsencrypt/live/zoozoo.space/privkey.pem: Permission denied
mailserver.1.v5lnv8mkfjrf@simba    | [   INF   ]  Post-configuration checks
mailserver.1.v5lnv8mkfjrf@simba    | chown: changing ownership of '/var/mail/zoozoo.space/admin': Permission denied
mailserver.1.v5lnv8mkfjrf@simba    | chown: changing ownership of '/var/mail/zoozoo.space': Permission denied
mailserver.1.v5lnv8mkfjrf@simba    | chown: changing ownership of '/var/mail': Permission denied
mailserver.1.v5lnv8mkfjrf@simba    | [  ERROR  ]  Failed to fix /var/mail permissions
mailserver.1.v5lnv8mkfjrf@simba    | [  ERROR  ]  Shutting down
mailserver.1.v5lnv8mkfjrf@simba    | 2022-09-01 16:35:03,890 WARN received SIGTERM indicating exit request
```
