### ISSUE TITLE
SSL_accept error server won't sent anymore

### ISSUE THREAD

**Issue by Skyfay** [docker-mailserver/docker-mailserver#2766]
My mail server no longer sends mails.
This morning it was still working and now nothing works at all.
I recently renewed the Letsencrypt certificates because they had expired. I don't know if it has anything to do with that.
Now no more e-mails can be sent following error:
```Sep  6 19:42:40 mail-server postfix/smtps/smtpd[1830]: connect from static.43.231.16.95.clients.your-server.de[95.216.204.62]


Sep  6 19:42:40 mail-server postfix/smtps/smtpd[1830]: SSL_accept error from static.43.231.16.95.clients.your-server.de[95.216.204.62]: lost connection
Sep  6 19:42:40 mail-server postfix/smtps/smtpd[1830]: lost connection after CONNECT from static.43.231.16.95.clients.your-server.de[95.216.204.62]
Sep  6 19:42:40 mail-server postfix/smtps/smtpd[1830]: disconnect from static.43.231.16.95.clients.your-server.de[43.231.16.95] commands=0/0```

**Comment by polarathene** [comment]
`docker-compose down && docker-compose up`?

**Comment by Skyfay** [comment]
> `docker-compose down && docker-compose up`?

I have already tried.

**Comment by polarathene** [comment]
How did you approach renewing the certs? You have not shared any `docker-compose.yaml`.

Re-creating the container with the new certificate files should work. This is not something we can easily assist you with.

Try enabling `LOG_LEVEL=trace` and re-creating the container like suggested, then share the logs here? It may have some information about problems during the startup process. If not, this is likely a configuration issue on your end that could be a variety of causes.

**Comment by Skyfay** [comment]
> How did you approach renewing the certs? You have not shared any `docker-compose.yaml`
I renewed the certificates via the web server. I just tested again, without encryption and with port 25 it works. But not over port 465 and with SSL.

> Try enabling `LOG_LEVEL=trace` and re-creating the container like suggested, then share the logs here?
The same logs I already sent...

I also have `- LETSENCRYPT_TEST=true` active, but no error in the logs.

```
version: "3"
networks:
  local:
    ipam:
      config:
        - subnet: 172.20.15.0/24
  webserver:
    external:
      name: webserver
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./data/nginx/data:/etc/nginx/conf.d/:ro
      - ./data/certbot/www:/var/www/certbot/:ro
      - ./data/certbot/conf/:/etc/nginx/ssl/:ro
#     - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      webserver:
        ipv4_address: 172.19.0.2
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./data/certbot/www:/var/www/certbot/:rw
      - ./data/certbot/conf/:/etc/letsencrypt/:rw
    networks:
      webserver:
        ipv4_address: 172.19.0.3      
  mail-server:
    image: mailserver/docker-mailserver:latest
    container_name: mail-server
    hostname: mail-server
    domainname: example.com
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
    restart: always
    volumes:
      - ./data/mail-server/data/mail-data/:/var/mail/
      - ./data/mail-server/data/mail-state/:/var/mail-state/
      - ./data/mail-server/data/mail-logs/:/var/log/mail/
      - ./data/mail-server/data/config/:/tmp/docker-mailserver/
      - ./data/certbot/certs/:/etc/letsencrypt/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_FAIL2BAN=1
      # Using letsencrypt for SSL/TLS certificates
      - SSL_TYPE=letsencrypt
      # Allow sending emails from other docker containers
      # Beware creating an Open Relay: https://docker-mailserver.github.io/docker-mailserver/edge/config/environment/#permit_docker
      - PERMIT_DOCKER=network
      # All env below are default settings:
      - ONE_DIR=1
      - ENABLE_POSTGREY=0
      - ENABLE_CLAMAV=0
      - ENABLE_SPAMASSASSIN=0
      # You may want to enable this: https://docker-mailserver.github.io/docker-mailserver/edge/config/environment/#spoof_protection
      # See step 8 below, which demonstrates setup with enabled/disabled SPOOF_PROTECTION:
      - SPOOF_PROTECTION=0
      - RELAY_HOST=smtp-relay.gmail.com
      - RELAY_PORT=25
      - TLS_LEVEL=modern
      - LETSENCRYPT_TEST=true
      - LOG_LEVEL=trace
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
      - SYS_PTRACE
    networks:
      local:
        ipv4_address: 172.20.15.2
#     webserver:
#       ipv4_address: 172.19.0.254
```
Funnily enough, it has worked without problems until today. But as of this afternoon it no longer works.

**Comment by polarathene** [comment]
> Certbot Volume: `- ./data/certbot/conf/:/etc/letsencrypt/:rw`
> DMS Volume: `- ./data/certbot/certs/:/etc/letsencrypt/`

This is your problem.

This is explained in [our SSL docs](https://docker-mailserver.github.io/docker-mailserver/edge/config/security/ssl/#provisioning-methods) for LetsEncrypt support (**EDIT:** Ignore this reason, it's more likely the problem mentioned next):

> _Make sure that the entire folder is mounted to `docker-mailserver` as there are typically symlinks from `/etc/letsencrypt/live/mail.example.com` to `/etc/letsencrypt/archive`._

Whereas, you seem to have possibly chosen `/data/certbot/certs/` based on the [advice of a `docker run` example](https://docker-mailserver.github.io/docker-mailserver/edge/config/security/ssl/#example-using-docker-for-lets-encrypt):

```bash
# Change `mail.example.com` below to your own FQDN.
# Requires access to port 80 from the internet, adjust your firewall if needed.
docker run --rm -it \
  -v "${PWD}/docker-data/certbot/certs/:/etc/letsencrypt/" \
  -v "${PWD}/docker-data/certbot/logs/:/var/log/letsencrypt/" \
  -p 80:80 \
  certbot/certbot certonly --standalone -d mail.example.com
```

You can see that `certs/` in that example maps to the Certbot container `/etc/letsencrypt/` folder in the container.

Your Certbot container is using `conf/`, so it **probably doesn't have the same content**. Maybe you changed this at some point, and it worked fine with old certificates at `certs/`, but once the update happened for `conf/` they were **no longer in sync?**

**Fix:** Bring your DMS container down, and then adjust the volume path to `conf/` instead of `certs/`, it will match the correct local folder then.

**Comment by Skyfay** [comment]
> **Fix:** Bring your DMS container down, and then adjust the volume path to `conf/` instead of `certs/`, it will match the correct local folder then.

Yes, I actually made a mistake there. I adjusted it, deleted all containers, recreated the certificates and started again but still the same error... 
How can that be?

```
version: "3"
networks:
  local:
    ipam:
      config:
        - subnet: 172.20.15.0/24
  webserver:
    external:
      name: webserver
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./data/nginx/data:/etc/nginx/conf.d/:ro
      - ./data/certbot/www:/var/www/certbot/:ro
      - ./data/certbot/conf/:/etc/nginx/ssl/:ro
#     - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      webserver:
        ipv4_address: 172.19.0.2
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./data/certbot/www:/var/www/certbot/:rw
      - ./data/certbot/conf/:/etc/letsencrypt/:rw
    networks:
      webserver:
        ipv4_address: 172.19.0.3      
  mail-server:
    image: mailserver/docker-mailserver:latest
    container_name: mail-server
    hostname: mail-server
    domainname: skysmtp.ch
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
    restart: always
    volumes:
      - ./data/mail-server/data/mail-data/:/var/mail/
      - ./data/mail-server/data/mail-state/:/var/mail-state/
      - ./data/mail-server/data/mail-logs/:/var/log/mail/
      - ./data/mail-server/data/config/:/tmp/docker-mailserver/
      - ./data/certbot/conf/:/etc/letsencrypt/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_FAIL2BAN=1
      # Using letsencrypt for SSL/TLS certificates
      - SSL_TYPE=letsencrypt
      # Allow sending emails from other docker containers
      # Beware creating an Open Relay: https://docker-mailserver.github.io/docker-mailserver/edge/config/environment/#permit_docker
      - PERMIT_DOCKER=network
      # All env below are default settings:
      - ONE_DIR=1
      - ENABLE_POSTGREY=0
      - ENABLE_CLAMAV=0
      - ENABLE_SPAMASSASSIN=0
      # You may want to enable this: https://docker-mailserver.github.io/docker-mailserver/edge/config/environment/#spoof_protection
      # See step 8 below, which demonstrates setup with enabled/disabled SPOOF_PROTECTION:
      - SPOOF_PROTECTION=0
      - RELAY_HOST=smtp-relay.gmail.com
      - RELAY_PORT=25
      - LETSENCRYPT_TEST=true
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
      - SYS_PTRACE
    networks:
      local:
        ipv4_address: 172.20.15.2
```
