### ISSUE TITLE
[BUG] mailserver picks outdated certificate from multiple entries in acme.json although there is a valid one available

### ISSUE THREAD

**Issue by noresistence** [docker-mailserver/docker-mailserver#2804]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

SSL Certificate import from acme.json file, coming from Traefik2

### What happened and when does this occur?

```Markdown
The Mailserver extracts the first certificate for mail.domain in acme.json, although this one is outdated. There is another entry for mail.domain in acme.json with the currently valid certificate.
```

### What did you expect to happen?

```Markdown
When there are multiple entries for my domain in acme.json, the certificate with the latest expiration date should be picked for export instead of picking the first entry, as that can be outdated.
```

### How do we replicate the issue?

```Markdown
1. Traefik2 stored multiple versions of the mailserver certificate in acme.json. First entry is an outdated certificate, and further down, another entry is an up-to-date certificate for the same domain.
2. Start Mailserver with such an acme.json
3. Mailserver will use the outdated SSL certificate
4. Remove outdated entry from acme.json and do not touch the rest of acme.json, such that now the up-to-date certificate is the first entry for mailserver's domain.
5. Mailserver will now pick up the correct certificate.
```

### DMS version

v11.1.0

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yml
services:
  mailserver:
    build: .
    container_name: mailserver
    # If the FQDN for your mail-server iposts only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail
    domainname: ${DOMAIN}
    env_file: mailserver.env
    environment:
      # General settings
      OVERRIDE_HOSTNAME: "mail.${DOMAIN}"
      # SSL settings
      SSL_TYPE: letsencrypt
      SSL_DOMAIN: "mail.${DOMAIN}"
      # [...]
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    # "implicit TLS" is stronger security than "explicit TLS"
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      # - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      # - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
      - "995:995"  # POP3 (with TLS)
    volumes:
      - mail-data:/var/mail/
      - mail-state:/var/mail-state/
      - mail-logs:/var/log/mail/
      - /etc/localtime:/etc/localtime:ro
      # Access to Traefik's SSL certificates
      # Mailserver will use '/etc/letsencrypt/acme.json' which is set up as a symlink 
      # to '/traefik/acme.json' in the Dockerfile. This is used to be able to include
      # this file from a docker volume in readonly mode without setting the whole 
      # directory /etc/letsencrypt to be readonly (as that would conflict with the creation
      # of the 'live' subdirectory that's used by mailserver to export certificates)
      - traefik_data:/traefik:ro
      # include mailman's maps
      - mailman_core:/opt/mailman/core
    restart: always
    depends_on:
      - mailserver_db
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    networks:
      - mail
```

### Other relevant information

```Markdown
### My guess to what's the cause of and solution to the problem

Usually, acme.json is expected to only have one entry per (sub-)domain. On my other server, that's true. But this is not guaranteed; on our affected server (using the same traefik configuration), Traefik2 has kept one outdated version alongside the recent certificate for some (not all) domains in acme.json. 

Solution to this problem is to adapt the certificate import: Check whether there are multiple certificates for the domain in acme.json and then to pick the most recent one. 

### Dockerfile

Should not be relevant, but for the sake of completeness, this is our addition to the Dockerfile to manage the import of `acme.json`. This has no effect on the contents of `acme.json` and is also used on another server that did not expect any issues.


FROM docker.io/mailserver/docker-mailserver:11.1.0

ARG DEBIAN_FRONTEND=noninteractive

[...]

# let /etc/letsencrypt/acme.json point to /traefik/acme.json
# such that we can mount the traefik volume to /traefik in readonly mode
# without having /etc/letsencrypt readonly
RUN mkdir -p /etc/letsencrypt && ln -s /traefik/acme.json /etc/letsencrypt/acme.json

[...]
```
```


### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [ ] I am inexperienced with mail servers
- [ ] I am uncomfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

### Improvements to this form?

```Markdown
I don't know where to put the following information; maybe an input for "Your guess to what's going wrong or your ideas for possible solutions (if any)?"
```

**Comment by polarathene** [comment]
The line of code that will find a matching certificate for the DMS domain is here:

https://github.com/docker-mailserver/docker-mailserver/blob/a09d46a67718086a7a48b3c9773aac3ad8f69622/target/bin/acme_extract.py#L18

And we have the following [test `acme.json`](https://github.com/docker-mailserver/docker-mailserver/blob/a09d46a67718086a7a48b3c9773aac3ad8f69622/test/test-files/ssl/example.test/with_ca/ecdsa/wildcard/ecdsa.acme.json). As you can see there is no information about dates here. If that is still the case with your own `acme.json`, then the date exists inside the certificate only, and someone would need to write Python code to parse that.

We are also open towards contributions that port the python script to something as easily maintainable. I wrote the current python script, porting a shell script we had prior.

I do not know Python well however, nor do I have the time this year to look further into it. I believe that's the same for all other maintainers here regarding python unfortunately.

Presumably python or some python package could make getting that date information and comparing it against potential other copies possible, but I don't now how much more that'd complicate the support on our end. Two of us are fans of rust however. And I believe I could port this to a rust executable instead, but again my year is fully booked at present.

**Comment by casperklein** [comment]
fyi, there is no need for complicated parsing of the certificate:

```bash
if openssl x509 -noout -checkend 0 -in $CERTIFICATE; then
	echo "not expired"
else
    echo "expired!!!"
fi
```

**Comment by polarathene** [comment]
I suppose it could return all certs found for the requested FQDN, and we use a shell script to find the one that isn't expired :man_shrugging: 

I assume that there would be more than one not expired, as a renewal may usually happen within 30 days to expiry? But that may vary, so you might have to pick the one with the longest time until expiry.

**Comment by Moe1369** [comment]
Offtopic @noresistence  but would you mind sharing/explaining your config?
I'm trying to set up traefik + docker-mailserver properly but apparently can't.

**Comment by noresistence** [comment]
@Moe1369 This is my Traefik + docker-mailserver setup (well, at least enough of it that you should be able to get going) and some explanations. Enjoy.

### Traefik
We use Traefik v2. A named volume `data` is mounted at `/etc/traefik`. Certificates will be stored there.

*`Traefik/docker-compose.yml`*
```yml
version: '3'

volumes:
  data:

networks:
  traefik:
    external: true

services:
  traefik:
    container_name: traefik
    # Traefik v2, explicit version
    image: traefik:v2.9.4
    # should restart, whenever docker restarts
    restart: always
    ports:
      # HTTP
      - "80:80"
      # HTTPS
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # this is where certificates will be stored
      - data:/etc/traefik
    networks:
      - traefik
```
Start Traefik once to create the data volume. Then copy the config into the volume.

*Traefik Config: `traefik.yml`*
```
[...]

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    # only expose containers that have the label `traefik.enable=true`
    exposedByDefault: false
    # Defines a default docker network to use for connections to all containers.
    network: traefik

certificatesResolvers:
  letsencrypt:
    acme:
      email: your-letsencrypt-contact@e.mail
      storage: "/etc/traefik/acme.json"
      httpChallenge:
        # used during the challenge
        entryPoint: web
```


## Docker-Mailserver
This is how we include the certificate directory in the Docker Mailserver. Idea is to mount the traefik volume at `/traefik` in read-only mode. Docker-Mailserver expects the file `acme.json` in `/etc/letsencrypt`, but needs write access to the directory. Therefore have `/etc/letsencrypt/acme.json` point to `/traefik/acme.json`.  This way, the certificates can be mounted read-only from an external volume, and at the same time accessed from a writable directory.

#### Dockerfile
```Dockerfile
FROM docker.io/mailserver/docker-mailserver:11.2.0@sha256:c9a60db3e76817cd930b551257405c769bfd5241615ea4d49ac74b156c41455f

ARG DEBIAN_FRONTEND=noninteractive

[...]

# let /etc/letsencrypt/acme.json point to /traefik/acme.json
# such that we can mount the traefik volume to /traefik in readonly mode
# without having /etc/letsencrypt readonly
RUN mkdir -p /etc/letsencrypt && ln -s /traefik/acme.json /etc/letsencrypt/acme.json

[...]

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
```

#### docker-compose.yml
The relevant portion for docker-mailserver itself is in the [issue description](https://github.com/docker-mailserver/docker-mailserver/issues/2804#issue-1391107227). But one important service has been left out:
You need some web-accessible service listening at `mail.yourdomain` for Traefik to trigger a certificate request for your mailserver domain. This uses BasicAuth with some long, random password to not expose the whoami-data to anyone. Alternatively, you could use some webserver or whatever you would like to be publicly visible at mail.yourdomain.
```yml
 networks:
   traefik:
     external: true

# this is how to mount traefik's data volume in my setup
volumes:
  traefik_data:
    external: true
  [...]

services:
 # docker-mailserver: see issue description
 [...]
 
 # Service for Traefik, to order certificates for mail.${DOMAIN}
  whoami:
    image: docker.io/traefik/whoami:latest@sha256:24829edb0dbaea072dabd7d902769168542403a8c78a6f743676af431166d7f0
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.MailserverWhoAmI.loadbalancer.server.port=80"
      - "traefik.http.routers.MailserverWhoAmI.rule=Host(`mail.${DOMAIN}`)"
      # Create BasicAuth Middleware for WhoAmI Service (don't want it to be exposed)
      # Password: gibberish
      # User: nobody
      - "traefik.http.middlewares.MailserverWhoAmIAuth.basicauth.users=nobody:$$ab$$cd$$efghijklmnopqrstuvwxyz"
      # Apply BasicAuth Middleware to the Router
      - "traefik.http.routers.MailserverWhoAmI.middlewares=MailserverWhoAmIAuth@docker"
    networks:
      - traefik
```
