### ISSUE TITLE
[FR] Send-only domains

### ISSUE THREAD

**Issue by Giotino** [docker-mailserver/docker-mailserver#2813]
# Feature Request

There is a problem delivering emails to the correct mailserver when the domain exists in the sending mailserver.

## Context

If a domain exists in a mailserver, the server becomes its "final destination", catching all the emails for that domain and not relaying them (if needed).

### Is your Feature Request related to a Problem?

The fact that every domain ends up in the `virtual_mailbox_domains` list (https://www.postfix.org/postconf.5.html#virtual_mailbox_domains) create problems in the following case:

I have my domain `example.org` with all the mailboxes on `mailserver1`. I also use `mailserver2` only to send emails (like from `noreply@example.org`).

The problem is that when I send an email from `noreply@example.org` to `user@example.org` using `mailserver2` it fails becase `mailserver2` can't find `user`.

### Describe the Solution you'd like

There should be a way to prevent domains to be in the `virtual_mailbox_domains` list, marking them as send-only (as they wouldn't be able to receive any emails).

### Are you going to implement it?

Yes, I already have.

https://github.com/Giotino/docker-mailserver/commit/b651e3e93db22cfa0239430ad91d844c47d90b87

I created a new configuration file `sendonly-domains.cf` with the list of domains that shouldn't be in the `virtual_mailbox_domains` list.

### What are you going to contribute??

In addition to the code in the commit, I can add the option to add send-only domains to the setup.sh and then open a PR.

### Alternatives you've considered

I tried to set a relay for the domain to the mailserver with the mailboxes, but it's ignored.

An easy solution would be disabling the spoofing protection and using a mailbox with an "invalid" domain to send, but it will create a security problem where the user can send emails from any address.

### Who will that Feature be useful to?

See the case described before.

### What have you done already?

Implemented it.

### Drawbacks of the implementation

I don't know if it's really a drawback, but I think it should be taken in consideration.

Non-delivery notifications (for example if the destination address doesn't exists) are delivered to the mailserver specified in the MX record of the domain.

**Email aliases and dkim signature seems to not be applied to the mailserver generated notifications.**

**Comment by polarathene** [comment]
> The problem is that when I send an email from `noreply@example.org` to `user@example.org` using `mailserver2` it fails becase `mailserver2` can't find `user`.

You can send a mail from a domain that your mail-server does not manage.

If you send the mail as an authenticated user on port 587 or 465, it should be sent to the intended server. The user you authenticate as should be a mail account for the server you're authenticating to, but you can send from/as anyone.

It's then the receiving mail servers job to check if you're authorized to send on behalf of that domain for deciding to accept the mail or not.

I have an example of this with an offline three instance setup with a mail client sending mail to a DMS instance that it authenticates to, sends the mail to the destination mail server, on behalf of another that isn't involved but manages that domain (DNS records).

---

> I tried to set a relay for the domain to the mailserver with the mailboxes, but it's ignored.

There is a few different ways to configure relaying or address rewriting IIRC, but DMS has limited official support.

Our relay support I believe is for relay hosts. You can have domains for your mail-server connect to another mail-server with authentication, and then that account can send mail from that server on behalf of your original mail-server. It would not rewrite the `FROM` address though AFAIK.

**Comment by Giotino** [comment]
Thanks for your response.

I think you misinterpreted my phrase:

> > The problem is that when I send an email from `noreply@example.org` to `user@example.org` using `mailserver2` it fails becase `mailserver2` can't find `user`.
>
> You can send a mail from a domain that your mail-server does not manage.
> If you send the mail as an authenticated user on port 587 or 465, it should be sent to the intended mailserver.

Normally that's true, but in this case, as `mailserver2` know the domain `example.org`, the delivery simply fails with a `550 5.1.1 <user@example.org> User doesn't exists` error, becase the mailserver thinks that the email is for it since it's configured to be the "final destination" for `example.org`.

> The user you authenticate as should be a mail account for the mailserver you're authenticating to, but you can send from/as anyone.

I shouldn't be able to send as anyone if `SPOOF_PROTECTION` is enabled, what I think you are suggesting is to disable it because in this scenario is the destination mailserver that should check if the mailsever is authorized to send emails from my addresses.

But that's not a safe configuration if there are other accounts (from the same or other domains), because they can spoof each other and the destination mailserver is going to accept all the emails because my mailserver is authorized to send for all the domains that it manages.

Just to give you a more detailed overview of my scenario:

```
MailServer 1:
user1@domain1.com
user2@domain1.com

MailServer 2:
noreply@domain1.com (send-only, no mailbox)
user3@domain2.com
user4@domain3.com
```

**Comment by polarathene** [comment]
> because `mailserver2` thinks that the email is for it, since it's configured to be the "final destination" for `example.org`.

I would appreciate clarification on why it's configured that way, if it's not intended to be used that way?

If you only want to send mail out as `noreply@<externally-managed-domain>`, no mail storage (sent to you, or bounces) since the mail-server doesn't actually manage the domain itself, it'd seem you should not create an account or alias for that purpose?

---

> I shouldn't be able to send as anyone if `SPOOF_PROTECTION` is enabled

Just to clarify, without this ENV, only a user that successfully authenticates on ports 587 or 465 is by default permitted to do such. Not any untrusted inbound mail arriving at port 25, regardless of who it is to / from.

But I can understand that you'd want to restrict what your mail accounts can send as. You're probably right about our alias support needing a config review, however we can still allow select users to send mail as different addresses (_which we can still constrain what is allowed_).

If you have aliases or accounts in "MailServer2", you'll still have the same delivery problem, but I assume you don't need that if this configuration below works for you.

---

## Example - Allowing a mail account to send from permitted addresses (without needing to rely on aliases)

Here is a smaller and revised version of [my relay test environment](https://github.com/docker-mailserver/docker-mailserver/issues/2601#issuecomment-1135520225) I shared a while back.

I have added in comments for the `docker-compose.yml` which of the DMS instances match your example config. It will allow us to do the following:
- A mail client will send a new mail to `mail.origin.test` (MailServer 2). This is a submission over port 465 authenticated as the `hello@origin.test` user. Thus untrusted third-parties will not be able to relay mail this way.
- The mail that was sent has a `FROM` (sender address) of `noreply@destination.test` and a `TO` (recipient address) of `hello@destination.test`.
- `mail.origin.test` would normally reject this with the ENV `SPOOF_PROTECTION=1`, but we've added the `noreply@destination.test` as **an alternative sender address for our mail account `hello@origin.test`** (_which you can login via SASL auth with the accounts address/username, or any alias assigned to it AFAIK_).
- `mail.origin.test` ("MailServer 2") will notice that it should send this mail to a different mail sever (`mail.destination.test`, "MailServer 1") and have no issue doing so...(_unless you have told Postfix it should receive mail for `destination.test`, due to creating accounts or aliases with that domain_).
- `mail.destination.test` then receives the mail, gets a HELO from `mail.origin.test`, runs checks to verify the server is who it says it is.
  - For example, the SPF check will request the associated DNS TXT record for the domain in `FROM` and ensure the HELO (`mail.origin.test`, "MailServer 2") and IP are valid. (_Technically the HELO check in `policyd-spf` seems to replace the sender address with a fake one from the HELO AFAIK, which I think is intended to compare against the IP._)

### Config files for testing this locally

<details>
<summary>docker-compose offline reproduction example</summary>

```yaml
services:
  # A DNS service for the two containers to resolve each others FQDNs
  # And retrieve any relevant DNS records like MX and TXT (SPF)
  dms-coredns:
    image: coredns/coredns:1.10.0
    container_name: dms-dns
    volumes:
      - ./coredns/Corefile:/Corefile:ro
      - ./coredns/zones:/zones:ro
    # The private network IP for this container that others send DNS queries to:
    networks:
      dms_test_network:
        ipv4_address: 172.16.238.10

  # -- Your "MailServer 2" --
  # Your mail-server that wants to send mail as `noreply@destination.test`,
  # With SPOOF_PROTECTION=1, we have to explicitly authorize what account
  # may send FROM that address.
  dms-mta-origin:
    image: mailserver/docker-mailserver:11.1
    container_name: dms-origin
    hostname: mail.origin.test
    environment:
      - SSL_TYPE=letsencrypt
      - TEST_ACCOUNT=hello@origin.test
      - TEST_PASS=whatever
      - TEST_ACCOUNT_PERMIT_SENDER=noreply@destination.test
      - SPOOF_PROTECTION=1
      - POSTMASTER_ADDRESS=hello@origin.test
    # This is a minimal example, so no state is persisted:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./tls:/etc/letsencrypt/live:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
    entrypoint: /entrypoint.sh
    # This example runs completely offline with a custom DNS server and static container IP assigned:
    dns: 172.16.238.10
    networks:
      dms_test_network:
        ipv4_address: 172.16.238.11

  # -- Your "MailServer 1" --
  # This is the intended mail-server to receive mail from dms-origin above.
  dms-mta-destination:
    image: mailserver/docker-mailserver:11.1
    container_name: dms-destination
    hostname: mail.destination.test
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./tls:/etc/letsencrypt/live:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
    environment:
        - SSL_TYPE=letsencrypt
        - TEST_ACCOUNT=hello@destination.test
        - SPOOF_PROTECTION=1
        - POSTMASTER_ADDRESS=hello@destination.test
    entrypoint: /entrypoint.sh
    dns: 172.16.238.10
    networks:
      dms_test_network:
        ipv4_address: 172.16.238.12

# Defines the local subnet range we'll use for our test network above
networks:
  dms_test_network:
    name: coredns-ipam
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
```

</details>

<details>
<summary>CoreDNS files to volume mount</summary>

A basic `Corefile` config that specifies two domains (zones) for our containers, each zone file is pretty much the same config with the domain `origin` / `destination` and their associated IP being the only difference.

**`coredns/Corefile`:**
```
# We have chosen .test, as this is a reserved TLD that normally DNS resolvers
# should ignore when queried. It should never resolve an IP from a public resolver
origin.test {
    file /zones/origin.test {
        reload 15s
    }
    log
}

destination.test {
    file /zones/destination.test {
        reload 15s
    }
    log
}

. {
    # For any other query, we can log it, or uncomment to forward the query,
    # to a public resolver. Useful if you need to install a package.
    #forward . 8.8.8.8 9.9.9.9
    log
}
```


**`coredns/zones/origin.test`:**

```
$ORIGIN origin.test.
$TTL 60

@       SOA    origin.test. admin.origin.test. 2022100800 4h 1h 14d 10m
@       NS     ns1.origin.test.

; Mail
; SPF `mx`: Authorize the DMS mail-server at MX record
; SPF `ip4`: Optional - Authorizes a third-party client (for testing) to
; send mail on behalf of this mail-server without relaying through it.
@       MX  10 mail.origin.test.
@       TXT    "v=spf1 mx ip4:172.16.238.99 -all"

; A records
@       A      172.16.238.11
mail    A      172.16.238.11
ns1     A      172.16.238.10
```


**`coredns/zones/destination.test`:**

```
$ORIGIN destination.test.
$TTL 60

@       SOA    destination.test. admin.destination.test. 2022100800 4h 1h 14d 10m
@       NS     ns1.destination.test.

; Mail
; SPF `a`: Authorize the mail-server at mail.origin.test to send on
; behalf of destination.test (FROM noreply@destination.test)
@       MX  10 mail.destination.test.
@       TXT    "v=spf1 mx a:mail.origin.test -all"

; A records
@       A      172.16.238.12
mail    A      172.16.238.12
ns1     A      172.16.238.10
```

</details>

<details>
<summary>DMS container volume mounts</summary>

The `entrypoint.sh` script just automates adding an initial account (_which we set as `POSTMASTER` to avoid some error logs_) and optionally permit that account to send mail as a different user when `SPOOF_PROTECTION=1`. This is useful for testing, but you could provide your own `postfix-accounts.cf` or shell in with `docker exec -it container_name bash` and run the commands yourself :)

The local directory `tls/` contains a folder for each FQDN (`mail.origin.test` and `mail.destination.test`). Both folders have the files `fullchain.pem` and `privkey.pem`. Those are locally generated certs for testing with, created via [SmallStep's `step certificate create` CLI tool](https://smallstep.com/docs/step-cli/reference/certificate/create), I have [documented usage here](https://github.com/docker-mailserver/docker-mailserver/tree/master/test/test-files/ssl/example.test).

**`entrypoint.sh`:**

```bash
#!/bin/bash
set -e

function create_testing_account
{
  if [[ ! -f "/tmp/docker-mailserver/postfix-accounts.cf" ]]
  then
    echo "Initializing test email account..."

    if [[ ! -d /tmp/docker-mailserver ]]
    then
      mkdir -p /tmp/docker-mailserver
    fi

    local TEST_ACCOUNT="${TEST_ACCOUNT:=hello@example.test}"
    local TEST_PASS="${TEST_PASS:=notsecure}"
    setup email add "${TEST_ACCOUNT}" "${TEST_PASS}"

    if [[ -n ${TEST_ACCOUNT_PERMIT_SENDER} ]]
    then
      # Create a new config file with this mapping:
      echo "${TEST_ACCOUNT_PERMIT_SENDER} ${TEST_ACCOUNT}" > /tmp/sender_login_maps.cf
      # And since the start-up scripts would override the config,
      # we can create a `user-patches.sh` file to update Postfix
      # afterwards.
      # WARNING: --- This is just an example, NOT production advice ---
      echo \
      "postconf 'smtpd_sender_login_maps = unionmap:{ hash:/etc/aliases, texthash:/tmp/sender_login_maps.cf, pcre:/etc/postfix/maps/sender_login_maps.pcre }'" \
      > /tmp/docker-mailserver/user-patches.sh
    fi
  fi
}

create_testing_account

# Run the CMD from Dockerfile:
# https://github.com/docker-mailserver/docker-mailserver/blob/0d30b92a83118e7c1cea7cdc40007a3f41d4fe6c/Dockerfile#L301
supervisord --configuration /etc/supervisor/supervisord.conf
```

</details>

---

### Sending a mail to our test environment

With the above config all setup as local files, and the certs created. You can now just run `docker-compose up` and it'll be good to go shortly after.

You can also open some terminal tabs or similar to follow a containers individual logs like `docker-compose logs -f dms-mta-origin`. Or `docker exec -it dms-mta-origin bash` if you want to run some commands within the container.

Next step is to send a test mail, and see that it works fine :+1: 

<details>
<summary>Example: Sending a mail to our offline test environment</summary>

Send email to `mail.origin.test` DMS instance that will relay as `noreply@destination.test` to the destination mail-server (_even if that's another address at `destination.test`_).

You could submit the mail via a MUA like Thunderbird, but that would need to make sure the MUA can connect to this local testing containers. If you expose the DNS ports of the CoreDNS container, and your system is configured to check it for DNS for the domains (_or you could use `/etc/hosts` to set the IP and skip this though_), then that should work. You'd likewise need to expose any mail ports needed, like port 465 in this example.

I have written a small program in Rust that reads a config file and generates/sends a mail from that. I avoid all the DNS / ports trouble by running it in a Docker container configured to use the same DNS and subnet like the containers in `docker-compose.yml`. You could do the same if you like with other mail programs, or I can provide source for mine.

```bash
docker run --rm -t --name mail-tester \
  --dns 172.16.238.10 \
  --network coredns-ipam \
  --ip 172.16.238.99 \
  --volume "${PWD}/templates:/templates:ro" \
  --volume "${PWD}/certs:/certs:ro" \
  smtp-tester --file /templates/noreply.toml
```

**`templates/noreply.toml`:**
```TOML
subject = "Mail subject title here"
body = "Message content here"

# Provide the CA certificate to verify chain of trust from the TLS cert sent by MTA
ca_cert = "/certs/ca-cert.ecdsa.pem"

# HOST will resolve to `mail.origin.test` by MX record,
# FROM address must exist (or map to one that does) on DMS mail-server if SPOOF_PROTECTION is enabled
# TO is the destination for the HOST to send to (it will lookup the mail-server via DNS MX record)
host = "origin.test"
from = "noreply@destination.test"
to = "hello@destination.test"

# Authenticated submission is required:
port = 465
tls = "Implicit"
creds = { user = "hello@origin.test", pass = "whatever" }
```

</details>
