### ISSUE TITLE
Port 993 is not listened by default

### ISSUE THREAD

**Issue by winston0410** [docker-mailserver/docker-mailserver#2824]
# Subject

I have questions about TLS/SSL/STARTTLS/OpenSSL

## Description

I am running docker-mailserver in K8S. I notice that port 993 (implicit IMAPS) is not listened by default, and I cannot find the option to enable that port [in the reference](https://docker-mailserver.github.io/docker-mailserver/edge/config/environment/#smtp_only). I have checked the ports being listened with the following command:

``` BASH
kubectl exec -n mailserver --stdin --tty deploy/mailserver -- /bin/sh -c "ss -tulpn | grep LISTEN"
Defaulted container "mailserver" out of: mailserver, prep-config (init)
tcp   LISTEN 0      100        127.0.0.1:10025      0.0.0.0:*                                     
tcp   LISTEN 0      100          0.0.0.0:587        0.0.0.0:*                                     
tcp   LISTEN 0      100          0.0.0.0:143        0.0.0.0:*    users:(("dovecot",pid=371,fd=32))
tcp   LISTEN 0      100          0.0.0.0:465        0.0.0.0:*                                     
tcp   LISTEN 0      100          0.0.0.0:65265      0.0.0.0:*    users:(("dovecot",pid=371,fd=54))
tcp   LISTEN 0      100          0.0.0.0:25         0.0.0.0:*                                     
tcp   LISTEN 0      4096       127.0.0.1:8891       0.0.0.0:*                                     
tcp   LISTEN 0      4096       127.0.0.1:8893       0.0.0.0:*                                     
tcp   LISTEN 0      100             [::]:143           [::]:*    users:(("dovecot",pid=371,fd=33))
tcp   LISTEN 0      100             [::]:65265         [::]:*    users:(("dovecot",pid=371,fd=55))
```

This is the env that I am using

```sh
TLS_LEVEL=modern
POSTSCREEN_ACTION=drop
OVERRIDE_HOSTNAME=smtp.foo.bar
SMTP_ONLY=0
POSTMASTER_ADDRESS=noreply@foo.bar
UPDATE_CHECK_INTERVAL=10d
POSTFIX_INET_PROTOCOLS=ipv4
ONE_DIR=1
ENABLE_AMAVIS=0
SUPERVISOR_LOGLEVEL=warn
```

**Comment by georglauterbach** [comment]
I will have a look.

**Comment by winston0410** [comment]
The image that I am using is: docker.io/mailserver/docker-mailserver:11.1.0@sha256:c55f48f69fb620c636b10ce5555cf4f4e97816205b439d75129e808182a76228

**Comment by georglauterbach** [comment]
This is the output of your command when I run it inside the container:

``` CONSOLE
root@mail:/# ss -tulpn | grep LISTEN | grep dovecot
tcp   LISTEN 0      100          0.0.0.0:993        0.0.0.0:*    users:(("dovecot",pid=606,fd=34))                                                                               
tcp   LISTEN 0      100          0.0.0.0:143        0.0.0.0:*    users:(("dovecot",pid=606,fd=32))
```

Maybe you're missing something like

``` YAML
- name: doesnt-matter-really
  containerPort: 993
  protocol: TCP
```

in your deployment?

You you `exec` into the container (kubectl exec -it -n mail <mailserver-pod-name>`) and execute `ss -tulpn | grep LISTEN | grep dovecot` again and see the result?

**Comment by winston0410** [comment]
Indeed adding that ports in the Deployment, I am able to get that port again. This is my output:

```sh
base ❯ kubectl exec -n mailserver --stdin --tty deploy/mailserver -c mailserver -- "/bin/sh"
# ss -tulpn | grep LISTEN | grep dovecot
tcp   LISTEN 0      100          0.0.0.0:143        0.0.0.0:*    users:(("dovecot",pid=407,fd=32))
tcp   LISTEN 0      100          0.0.0.0:65265      0.0.0.0:*    users:(("dovecot",pid=407,fd=56))
tcp   LISTEN 0      100          0.0.0.0:993        0.0.0.0:*    users:(("dovecot",pid=407,fd=34))
tcp   LISTEN 0      100             [::]:143           [::]:*    users:(("dovecot",pid=407,fd=33))
tcp   LISTEN 0      100             [::]:65265         [::]:*    users:(("dovecot",pid=407,fd=57))
tcp   LISTEN 0      100             [::]:993           [::]:*    users:(("dovecot",pid=407,fd=35))
```

I thought `ports` is only used for describing ports that will be used by the image, no idea why would it affect the image...

After that I tried to connect to the port with openssl, but I get no response:

```sh
base ❯ openssl s_client -starttls imap -connect local.mail.jyut.info:993 -debug
CONNECTED(00000003)
```
I tried to use `curl` to debug the issue inside the container, the response that I am getting for `993` is different with other ports(25, 587, 143). I guess it means there is something wrong for that port, even inside the container:

```sh
kubectl exec -n mailserver --stdin --tty deploy/mailserver -c mailserver -- "/bin/sh"

# curl localhost:25 -v
*   Trying 127.0.0.1:25...
* Connected to localhost (127.0.0.1) port 25 (#0)
> GET / HTTP/1.1
> Host: localhost:25
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Received HTTP/0.9 when not allowed

* Closing connection 0
curl: (1) Received HTTP/0.9 when not allowed

# curl localhost:587 -v
*   Trying 127.0.0.1:587...
* Connected to localhost (127.0.0.1) port 587 (#0)
> GET / HTTP/1.1
> Host: localhost:587
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Received HTTP/0.9 when not allowed

* Closing connection 0
curl: (1) Received HTTP/0.9 when not allowed

# curl localhost:143 -v
*   Trying 127.0.0.1:143...
* Connected to localhost (127.0.0.1) port 143 (#0)
> GET / HTTP/1.1
> Host: localhost:143
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Received HTTP/0.9 when not allowed

* Closing connection 0
curl: (1) Received HTTP/0.9 when not allowed

# curl localhost:993 -v
*   Trying 127.0.0.1:993...
* Connected to localhost (127.0.0.1) port 993 (#0)
> GET / HTTP/1.1
> Host: localhost:993
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

**Comment by winston0410** [comment]
This is my full configuration:

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: mailserver
  annotations:
    linkerd.io/inject: disabled
---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: data
  namespace: mailserver

spec:
  storageClassName: "oci-bv"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service

metadata:
  name: mailserver-service
  namespace: mailserver
  labels:
    app: mailserver

spec:
  type: ClusterIP

  selector:
    app: mailserver

  ports:
    - name: msa
      port: 587
      targetPort: 587
      protocol: TCP
    - name: imap
      port: 143
      targetPort: 143
      protocol: TCP
    - name: imaps
      port: 993
      targetPort: 993
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: mailserver
  namespace: mailserver

  annotations:
    ignore-check.kube-linter.io/run-as-non-root: >-
      'mailserver' needs to run as root
    ignore-check.kube-linter.io/privileged-ports: >-
      'mailserver' needs privilegdes ports
    ignore-check.kube-linter.io/no-read-only-root-fs: >-
      There are too many files written to make The
      root FS read-only

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailserver

  template:
    metadata:
      labels:
        app: mailserver

      annotations:
        # FIXME Need to enable apparmor in host first
        # container.apparmor.security.beta.kubernetes.io/mailserver: runtime/default

    spec:
      # REF https://docker-mailserver.github.io/docker-mailserver/edge/config/troubleshooting/debugging/#enable-verbose-debugging-output
      hostname: mail
      initContainers:
        - name: prep-config
          image: docker.io/mailserver/docker-mailserver:11.1.0@sha256:c55f48f69fb620c636b10ce5555cf4f4e97816205b439d75129e808182a76228
          command: [
              "sh",
              "-c",
              "mkdir -p /tmp/docker-mailserver;
              setup email add root@foo.bar $K8S_MAILSERVER_PWD;
              setup config dkim;"
            ]
          volumeMounts:
            - name: tmp-files
              mountPath: /tmp
              readOnly: false
          env:
            - name: K8S_MAILSERVER_PWD
              valueFrom:
                secretKeyRef:
                  name: mailserver-secret
                  key: K8S_MAILSERVER_PWD
      containers:
        - name: mailserver
          image: docker.io/mailserver/docker-mailserver:edge@sha256:a78c0134351729a4edf6657759b62d4c5e129ed6eb69f059a1e7811936d75439
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            privileged: false
            capabilities:
              add:
                # file permission capabilities
                - CHOWN
                - FOWNER
                - MKNOD
                - SETGID
                - SETUID
                - DAC_OVERRIDE
                # network capabilities
                - NET_ADMIN # needed for F2B
                - NET_RAW # needed for F2B
                - NET_BIND_SERVICE
                # miscellaneous  capabilities
                - SYS_CHROOT
                - KILL
              drop: [ALL]
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              memory: 1Gi
              cpu: 300m

          volumeMounts:
            # PVCs
            - name: data
              mountPath: /var/mail
              subPath: data
              readOnly: false
            - name: data
              mountPath: /var/mail-state
              subPath: state
              readOnly: false
            - name: data
              mountPath: /var/log/mail
              subPath: log
              readOnly: false

            # certificates
            - name: certificates-rsa
              mountPath: /secrets/ssl/rsa/
              readOnly: true

            # other
            - name: tmp-files
              mountPath: /tmp
              readOnly: false

            # override postfix main config
            - name: files
              subPath: postfix-main.cf
              mountPath: /tmp/docker-mailserver/postfix-main.cf
              readOnly: true

            # override postfix master config
            - name: files
              subPath: postfix-master.cf
              mountPath: /tmp/docker-mailserver/postfix-master.cf
              readOnly: true
          ports:
            - name: msa
              containerPort: 587
              protocol: TCP
            - name: imap
              containerPort: 143
              protocol: TCP
            - name: imaps
              containerPort: 993
              protocol: TCP

          envFrom:
            - configMapRef:
                name: mailserver.environment

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 5

          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - supervisorctl status | grep -E "mailserver|postfix" | grep RUNNING
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 1
            failureThreshold: 3

      restartPolicy: Always

      volumes:
        # configuration files
        - name: files
          configMap:
            name: mailserver.files

        # PVCs
        - name: data
          persistentVolumeClaim:
            claimName: data

        # certificates
        - name: certificates-rsa
          secret:
            secretName: mail-tls-certificate-rsa
            items:
              - key: tls.key
                path: tls.key
              - key: tls.crt
                path: tls.crt

        # other
        - name: tmp-files
          emptyDir: {}

```
