### ISSUE TITLE
[FR] Disable "AUTH LOGIN" for non-submission smtp port

### ISSUE THREAD

**Issue by mazzz1y** [docker-mailserver/docker-mailserver#2895]
# Feature Request

## Context

Currently is possible to connect to 25 port and send email after "AUTH LOGIN" command. I want to disallow any type of sending emails by connection to this port and use it only for receiving emails.

Sending should be possible only by connecting to submission ports which can be protected by firewall.

### Describe the Solution you'd like

Add environment variable to disable this and set it by default by security reasons

### Are you going to implement it?

First I want to know maybe this issue can be handled by existing way. Maybe I missed something

**Comment by mazzz1y** [comment]
Fixed by:
```
# postfix-main.cf
smtpd_sasl_auth_enable=no
```

I think by default server should not offer `AUTH LOGIN` on 25 port. Please correct me if I'm wrong

**Comment by georglauterbach** [comment]
Are you currently actually able to receive emails This option is turned on and it is a sane default (see <https://serverfault.com/a/691963>), because you probably need it to properly receive emails.

When you set `ENABLE_SASLAUTHD=0` and `SMTP_ONLY=1`, the option is turned off. Is this what you want - a send-only mail server?

**Comment by mazzz1y** [comment]
> Are you currently actually able to receive emails or send emails at all? 

Yes! Just check `smtp.google.com:25`:

```
$ openssl s_client -starttls smtp -connect smtp.google.com:25
...
read R BLOCK
250-mx.google.com at your service, [xxx]
250-SIZE 157286400
250-8BITMIME
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
```

As you can see it doesn't offer "AUTH LOGIN". It is not required for receiving email. And I think that it *should be* disabled, because users shouldn't use this port for submission.

Currently with default settings if password is compromised anyone from internet can connect to the 25 port for submission. I think it is not correct behavior.

I can be wrong because I don't have experience with postfix. But I'm sure that I disabled "AUTH LOGIN" and now it working as I expecting.

**Comment by mazzz1y** [comment]
> Wait a second; if your password is compromised, you are in trouble, even with port 465/587. TLS encryption does not have anything to do with the password :)

All ports except 25 can be closed by firewall

> I agree that users should not do it. But still to this day, some MTAs/relays use port 25. Either live with it, or don't receive mails from them.

Can you please show me example when auth on 25 port is required? Just for my understanding. It doesn't affect email receiving(I tested it) and I think that reqular user must disable it. So I didn't get your point.

Also I checked similar docker-based services: [Mailu](https://github.com/Mailu/Mailu) and [Poste.io](https://poste.io) and both don't allow auth on 25 port.

> I assume this can be closed then?

Yea, we can close it but I want to make it clear :)

**Comment by mazzz1y** [comment]
Proof:

* Mailu: https://github.com/Mailu/Mailu/blob/master/core/admin/mailu/internal/views/auth.py#L16 (16-18 lines)
* Poste.io:
```
# telnet response
220 xxx ESMTP Haraka/2.8.28 ready
EHLO User
250-xxx Hello xxx [xxx], Poste.io is at your service
250-PIPELINING
250-8BITMIME
250-SMTPUTF8
250-SIZE 26214400
250 STARTTLS
421 timeout
```

That means at least it makes sense

**Comment by georglauterbach** [comment]
> > Wait a second; if your password is compromised, you are in trouble, even with port 465/587. TLS encryption does not have anything to do with the password :)
> All ports except 25 can be closed by firewall

That's not the point I'm making. I'm just saying that encryption does not have anything to do with passwords.

**Comment by casperklein** [comment]
I think here are misunderstandings.

> Sending should be possible only by connecting to submission ports which can be protected by firewall.

I guess OP refers to outgoing mails from users.

> That's not the point I'm making. I'm just saying that encryption does not have anything to do with passwords.

If connection to port 465/587 is limited to some users by a firewall, a leaked password wouldn't have an impact on port 25, when authentication is disabled there. This may be an additional security layer, **but is in now way a valid mitigation for leaked password(s).**

> But still to this day, some MTAs/relays use port 25.
>  am the only user haha. All MTAs connect via 465/587

I think you mixed up MTAs and MUAs:

- MTA = Mailserver
- MUA = Mailclients

Afaik, MTAs don't use submission ports.

Conclusion from my side: If all users/clients use the submission ports for sending emails only, then disabling AUTH on port 25 seems reasonable to me. This doesn't affect receiving mails for configured domains in DMS on that port. When something is not needed --> disable it.

So making this configurable would be a good addition IMO. I am also open for making this a default from a security perspective in future DMS versions.

**Comment by mazzz1y** [comment]
Thank you, got it. 

Anyone who want to disable auth can do it as it described in https://github.com/docker-mailserver/docker-mailserver/issues/2895#issuecomment-1310055504

**Comment by georglauterbach** [comment]
Alright, I was off a bit :) We can implement this. I am just not sure whether this can go into the next minor release or whether this is a breaking change, which would need to go into v12.

**Comment by georglauterbach** [comment]
When I try to send an email via `telnet` on port 25 on my mail server, even with `smtpd_sasl_auth_enable = yes`, I see

``` CONSOLE
georg@swift ➜ telnet my_mail_server_dns_name 25
Trying <IP>...
Connected to my_mail_server_dns_name.
Escape character is '^]'.
220-This is Postscreen, please wait
220 my_mail_server_dns_name ESMTP
EHLO my_user_name
250-my_mail_server_dns_name
250-SIZE 52428800
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250-SMTPUTF8
250 CHUNKING
```

No `AUTH LOGIN`. What am I missing?

**Comment by mazzz1y** [comment]
The only one different thing from default setup: I use mailserver behind proxy with proxy protocol. Maybe it is related, need to test it from scratch. I will check and back to you

**Comment by mazzz1y** [comment]
I tried to run this configuration with and without proxy protocol and it happens only with proxy protocol(!) Trying to understand it

```
~ telnet localhost 25
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
220-xxx ESMTP
EHLO User
220 xxx ESMTP
250-xxx
250-PIPELINING
250-SIZE 51200000
250-ETRN
250-STARTTLS
250-AUTH PLAIN LOGIN
250-AUTH=PLAIN LOGIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 CHUNKING
```

### Configuration:

#### docker-compose.yml
<details>

```
version: '3.8'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: domain.com
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /opt/traefik/data/ssl/acme.json:/etc/letsencrypt/acme.json:ro
    environment:
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=0
      - ONE_DIR=1
      - DMS_DEBUG=0
      - TZ=Europe/Chisinau
      - SSL_TYPE=letsencrypt
      - SPOOF_PROTECTION=1      
      - POSTFIX_INET_PROTOCOLS=ipv4
      - SSL_DOMAIN=domain.com
      - SA_SPAM_SUBJECT=''
      - ENABLE_FETCHMAIL=1
      - FETCHMAIL_POLL=60
      - POSTFIX_MESSAGE_SIZE_LIMIT=51200000
    cap_add:
      - NET_ADMIN
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.smtp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smtp.entrypoints=smtp"
      - "traefik.tcp.routers.smtp.service=smtp"
      - "traefik.tcp.services.smtp.loadbalancer.server.port=25"
      - "traefik.tcp.services.smtp.loadbalancer.proxyProtocol.version=1"
      
  reverse-proxy:
    image: docker.io/traefik:latest
    container_name: docker-traefik
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.smtp.address=:25"
      - "--entryPoints.smtp-ssl.address=:465"
      - "--entryPoints.imap-ssl.address=:993"
      - "--entryPoints.sieve.address=:4190"
    ports:
      - "25:25"
```

</details>

#### docker-data/dms/config/postfix-main.cf
<details>

```
postscreen_upstream_proxy_protocol = haproxy
```

</details>

#### docker-data/dms/config/postfix-master.cf
<details>

```
submission/inet/smtpd_upstream_proxy_protocol=haproxy
smtps/inet/smtpd_upstream_proxy_protocol=haproxy
```

</details>

**Comment by mazzz1y** [comment]
Reproduced without proxy protocol. Need to pass Postscreen, `AUTH LOGIN` will appear after that. So it is not related to haproxy

**Comment by georglauterbach** [comment]
> > EDIT: Now I tried it with my own mail server; could not log in after setting smtpd_sasl_auth_enable = no in /etc/postfix/main.cf. @mazzz1y did you do more than just setting smtpd_sasl_auth_enable to no? I will double-check my setup though now.
> > EDIT2: Indeed, I set it to yes again and I was able to log in again. There either is something off with my setup or just setting this option in main.cf is not enough.
> What port are you using to connect?

I was imprecise. What I meant is: when I use a MUA (like Thunderbird), the connection is refused.

> I think it should work because smtpd_sasl_auth_enable overwritten on master.cf for submission ports.

So you did touch `master.cf`?

**Comment by mazzz1y** [comment]
> I think it should work because smtpd_sasl_auth_enable overwritten on master.cf for submission ports.
> So you did touch master.cf?

no, please check default `master.cf` there is smtpd_sasl_auth_enable=yes under submission section

**Comment by polarathene** [comment]
`master.cf` that we ship ensures submission ports 587 and 465 require auth:

https://github.com/docker-mailserver/docker-mailserver/blob/2bc4078e351bc6f3867524e38d0b5c578b107fb5/target/postfix/master.cf#L20

https://github.com/docker-mailserver/docker-mailserver/blob/2bc4078e351bc6f3867524e38d0b5c578b107fb5/target/postfix/master.cf#L33

`main.cf` sets the default for `smtp` transports to otherwise use (port 25 inbound):

https://github.com/docker-mailserver/docker-mailserver/blob/2bc4078e351bc6f3867524e38d0b5c578b107fb5/target/postfix/main.cf#L74

If you configure for a relay host, this is also enforced (port 25 outbound):

https://github.com/docker-mailserver/docker-mailserver/blob/2bc4078e351bc6f3867524e38d0b5c578b107fb5/target/scripts/helpers/relay.sh#L193

---

I don't have an environment to check with telnet at present, but a consistent reproducible example would be good :+1: 

I lack the time to dig through `git blame` but assume the `main.cf` default came before `master.cf` settings, it's possibly redundant addition from 5 years or so ago and the default could be changed. However that should wait until the next major version in case anyone has been relying on that default.

Port 25 inbound should only be used for receiving mail, not submitting mail to be sent outbound. An MTA can be a relay with submission ports open for another MTA to relay mail through, sometimes relay services offer alternative ports like port 25, but it's not required AFAIK.

**Comment by mazzz1y** [comment]
> but a consistent reproducible example would be good

No problems:

#### docker-compose.yml
<details>

```yaml
version: '3.8'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: domain.com
    ports:
      - "25:25"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /opt/traefik/data/ssl/acme.json:/etc/letsencrypt/acme.json:ro
    environment:
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_CLAMAV=0
      - ENABLE_POSTGREY=0
      - SSL_TYPE=letsencrypt
      - SSL_DOMAIN=domain.com
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
```

</details>

Step-by-step scenario:

1) Change `domain.com` in `docker-compose.yml` to your domain and make sure that letsencrypt secrets mounted correctly
2) Start it and create user:
```bash
docker-compose up -d
docker-compose exec mailserver setup email add eofjei@hfewhewf.com weifhweoifwhfowihfe # dummy credentials just for testing
```
3) Check logs and make sure that all started
4) Send `EHLO User` to 25 port
```bash
~ telnet localhost 25
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
220-mail.domain.com ESMTP # wait here a few seconds for passing postscreen
220 mail.domain.com ESMTP # see duplicate line? looks like postscreen passed, lets send EHLO
# for make sure check logs, you should see something like "PASS NEW [172.23.0.1]:47213"
EHLO User
250-mail.domain.com
250-PIPELINING
250-SIZE 10240000
250-ETRN
250-STARTTLS
250-AUTH PLAIN LOGIN # <--
250-AUTH=PLAIN LOGIN  # <--
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 CHUNKING
```
4) Try to disable auth and check if `AUTH LOGIN` persist in telnet output
```bash
~ echo 'smtpd_sasl_auth_enable=no' > docker-data/dms/config/postfix-main.cf
~ docker-compose stop
~ docker-compose rm -f # make sure that everything dropped
~ docker-compose up -d
~ telnet localhost 25
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
220 mail.domain.com ESMTP
# before EHLO please make sure that postscreen passed
# check it in logs, you should see something like "PASS OLD [172.23.0.1]:47292"
EHLO User 
250-mail.domain.com
250-PIPELINING
250-SIZE 10240000
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 CHUNKING
# AUTH LOGIN disappeared
```
5) lets check if auth works on 587 port
```bash
~ openssl s_client -starttls smtp -connect 127.0.0.1:587
...
read R BLOCK
EHLO User
250-mail.domain.com
250-PIPELINING
250-SIZE 10240000
250-ETRN
250-AUTH PLAIN LOGIN # success
250-AUTH=PLAIN LOGIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 CHUNKING
```

## Summary
```bash
echo 'smtpd_sasl_auth_enable=no' > docker-data/dms/config/postfix-main.cf
```
This command disables `AUTH LOGIN` unless otherwise stated in `master.cf` as it described in https://github.com/docker-mailserver/docker-mailserver/issues/2895#issuecomment-1312595980. Thank you @polarathene 

Please let me know if something not clear or need to describe it more
