### ISSUE TITLE
[BUG] SASL authentication failure: cannot connect to saslauthd server: No such file or directory

### ISSUE THREAD

**Issue by maxswjeon** [docker-mailserver/docker-mailserver#2900]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

postfix, saslauthd

### What happened and when does this occur?

`SMTP_ONLY` and `ENABLE_SASLAUTHD` are set to 1, and `RELAY_*` settings are set.  
`SASLAUTHD_MECHANISMS` is set to `shadow` and I added posix user named `test` with password `password`
I'm trying to authenticate from the internet and send them to RELAY since **Gmail `smtp-relay.gmail.com` doesn't allow localhost on EHLO`.**

### What did you expect to happen?

Able to authenticate with `test` and `password`, and use the relay.

### How do we replicate the issue?

1. Set up the mailserver with these values. Comments and blank values in `mailserver.env` is removed for readability

    **`mailserver.env`**
    ```
    DMS_DEBUG=0
    ONE_DIR=1
    ENABLE_UPDATE_CHECK=1
    UPDATE_CHECK_INTERVAL=1d
    PERMIT_DOCKER=none
    TZ=Asia/Seoul
    ENABLE_SRS=1
    ENABLE_CLAMAV=0
    ENABLE_AMAVIS=0
    AMAVIS_LOGLEVEL=0
    ENABLE_DNSBL=0
    ENABLE_FAIL2BAN=0
    FAIL2BAN_BLOCKTYPE=drop
    POSTSCREEN_ACTION=enforce
    SMTP_ONLY=1
    SSL_TYPE=letsencrypt
    ENABLE_QUOTAS=1
    LOGROTATE_INTERVAL=weekly
    POSTFIX_INET_PROTOCOLS=all
    DOVECOT_INET_PROTOCOLS=all
    ENABLE_SPAMASSASSIN=0
    SPAMASSASSIN_SPAM_TO_INBOX=1
    ENABLE_SPAMASSASSIN_KAM=0
    MOVE_SPAM_TO_JUNK=1
    SA_TAG=2.0
    SA_TAG2=6.31
    SA_KILL=6.31
    SA_SPAM_SUBJECT=***SPAM*****
    ENABLE_FETCHMAIL=0
    FETCHMAIL_POLL=300
    DOVECOT_MAILBOX_FORMAT=maildir
    ENABLE_POSTGREY=0
    POSTGREY_DELAY=300
    POSTGREY_MAX_AGE=35
    POSTGREY_TEXT="Delayed by Postgrey"
    POSTGREY_AUTO_WHITELIST_CLIENTS=5
    ENABLE_SASLAUTHD=1
    SASLAUTHD_MECHANISMS=shadow
    SASLAUTHD_MECH_OPTIONS=
    SRS_SENDER_CLASSES=envelope_sender
    DEFAULT_RELAY_HOST=smtp-relay.gmail.com
    RELAY_HOST=smtp-relay.gmail.com
    RELAY_PORT=465
    RELAY_USER=maxswjeon@codingbear.kr
    RELAY_PASSWORD=[[REDACTED]]
    ```

    **`certbot.sh`**
    certbot.sh is for let's encrypt certificate issue and renewal.
    ```
    #!/bin/sh

    CREDENTIAL_FILE="$(mktemp)"
    echo "dns_cloudflare_api_token = $CLOUDFLARE_API_TOKEN" > "$CREDENTIAL_FILE"

    if [ ! -d "/etc/letsencrypt/live/${DOMAIN}" ]; then
            certbot certonly --dns-cloudflare --dns-cloudflare-credentials "$CREDENTIAL_FILE" --agree-tos -m "$MAIL" -d "$DOMAIN" --rsa-key-size 4096
    fi

    touch /healthy

    while true; do
            certbot renew

            sleep 1d
    done
    ```

    **`docker-compose.yml`**
    ```
    services:
      certbot:
        image: certbot/dns-cloudflare:latest
        restart: always
        entrypoint: /docker-entrypoint.sh
        healthcheck:
          test: ["CMD", "cat", "/healthy"]
          timeout: 3s
          retries: 0
          start_period: 0s
        environment:
          - MAIL=${MAIL}
          - DOMAIN=${DOMAIN}
          - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
        volumes:
          - ./certbot.sh:/docker-entrypoint.sh
          - ./certs:/etc/letsencrypt
      mailserver:
        image: docker.io/mailserver/docker-mailserver:latest
        hostname: mail
        domainname: codingbear.kr
        env_file: mailserver.env
        # More information about the mail-server ports:
        # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
        # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
        # This server is only for sending (SMTP Only). Do not expose 143 and 993
        ports:
          - "25:25"    # SMTP  (explicit TLS => STARTTLS)
          # - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
          - "465:465"  # ESMTP (implicit TLS)
          - "587:587"  # ESMTP (explicit TLS => STARTTLS)
          # - "993:993"  # IMAP4 (implicit TLS)
        volumes:
          - ./data/data/:/var/mail/
          - ./data/state/:/var/mail-state/
          - ./logs/:/var/log/mail/
          - ./config:/tmp/docker-mailserver/
          - /etc/localtime:/etc/localtime:ro
          - ./certs:/etc/letsencrypt
        restart: always
        stop_grace_period: 1m
        cap_add:
          - NET_ADMIN
        healthcheck:
          test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
          timeout: 3s
          retries: 0
    ```
2. Set up required `.env`s for certbot. May be skipped if `./certs` are replaced by `/etc/letsencrypt`
3. Bring up the docker compose project (using `docker-compose up` or `docker compose up`
4. Run `docker-compose exec useradd test` (or `docker compose exec useradd test`) and `docker-compose exec passwd test` (or `docker compose exec passwd test`)
5. Restart the server (`docker-compose restart mailserver` or `docker compose restart mailserver`)
6. Try logging in with `openssl s_client -connect localhost:465` and run these commands
    ```
    EHLO localhost
    AUTH LOGIN
    dGVzdA==
    cGFzc3dvcmQ=
    ```
7. Encounter the `SASL authentication failure: cannot connect to saslauthd server: No such file or directory` Error

### DMS version

v11.2.0

### What operating system is DMS running on?

Linux

### Which operating system version?

Ubuntu 22.04

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yml
services:
  certbot:
    image: certbot/dns-cloudflare:latest
    restart: always
    entrypoint: /docker-entrypoint.sh
    healthcheck:
      test: ["CMD", "cat", "/healthy"]
      timeout: 3s
      retries: 0
      start_period: 0s
    environment:
      - MAIL=${MAIL}
      - DOMAIN=${DOMAIN}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    volumes:
      - ./certbot.sh:/docker-entrypoint.sh
      - ./certs:/etc/letsencrypt
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    hostname: mail
    domainname: codingbear.kr
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    # This server is only for sending (SMTP Only). Do not expose 143 and 993
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      # - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      # - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./data/data/:/var/mail/
      - ./data/state/:/var/mail-state/
      - ./logs/:/var/log/mail/
      - ./config:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ./certs:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### Relevant log output

```bash
mailserver-mailserver-1  | Nov 15 02:29:12 mail postfix/smtps/smtpd[3891]: error: open database /etc/postfix/vmailbox: No such file or directory
mailserver-mailserver-1  | Nov 15 02:29:12 mail postfix/smtps/smtpd[3891]: warning: hostname web.vm.home.codingbear.kr does not resolve to address 172.21.0.1
mailserver-mailserver-1  | Nov 15 02:29:12 mail postfix/smtps/smtpd[3891]: connect from unknown[172.21.0.1]
mailserver-mailserver-1  | Nov 15 02:29:12 mail postfix/smtps/smtpd[3891]: Anonymous TLS connection established from unknown[172.21.0.1]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (4096 bits) server-digest SHA256
mailserver-mailserver-1  | Nov 15 02:29:12 mail postfix/smtps/smtpd[3891]: warning: connect to Milter service inet:localhost:8891: Cannot assign requested address
mailserver-mailserver-1  | Nov 15 02:29:38 mail postfix/smtps/smtpd[3891]: warning: SASL authentication failure: cannot connect to saslauthd server: No such file or directory
mailserver-mailserver-1  | Nov 15 02:29:38 mail postfix/smtps/smtpd[3891]: warning: unknown[172.21.0.1]: SASL LOGIN authentication failed: generic failure
mailserver-mailserver-1  | Nov 15 02:29:43 mail postfix/smtps/smtpd[3891]: lost connection after AUTH from unknown[172.21.0.1]
mailserver-mailserver-1  | Nov 15 02:29:43 mail postfix/smtps/smtpd[3891]: disconnect from unknown[172.21.0.1] ehlo=1 auth=0/1 commands=1/2
```

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [X] I am rather experienced with docker
- [x] I am inexperienced with mail servers
- [ ] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [X] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution
