### ISSUE TITLE
Freshclam stopped updating after last update

### ISSUE THREAD

**Issue by lugdunum-1964** [docker-mailserver/docker-mailserver#2942]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

freshclam updates of antivirus database

### What happened and when does this occur?

```Markdown
I received a mail from the clamav system that freshclam had failed
```

### What did you expect to happen?

```Markdown
freshclam retrieving a database update
```

### How do we replicate the issue?

```Markdown
1. I updated the mailserver:
   docker-compose down; docker-compose pull; docker-compose up --build -d
2. 
3.
...
```

### DMS version

v11.3

### What operating system is DMS running on?

Linux

### Which operating system version?

Debian GNU/Linux 11

### What instruction set architecture is DMS running on?

ARM64 / ARM v8 (and newer)

### What container orchestration tool are you using?

Docker

### docker-compose.yml

```yml
version: '3.3'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    env_file: mailserver.env

    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    # More information about the mailserver ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    ports:
      - "25:25"     # SMTP  (explicit TLS => STARTTLS)
      # "143:143"   # IMAP4 (explicit TLS => STARTTLS)  <-- disabled
      - "465:465"   # ESMTP (implicit TLS)
      - "587:587"   # ESMTP (explicit TLS => STARTTLS)
      - "993:993"   # IMAP4 (implicit TLS)
      - "4190:4190" # ManageSieve
    volumes:
      - "./volumes/maildata:/var/mail"
      - "./volumes/mailstate:/var/mail-state"
      - "./volumes/maillogs:/var/log/mail"
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/:/tmp/docker-mailserver/${SELINUX_LABEL}"              # <-- local (re)configuration
      - "/mnt/proxy/certs/:/etc/letsencrypt"                             # <-- SSL certificates
      - "/mnt/proxy/config/dhparams.pem/:/etc/postfix/dhparams.pem:ro"   # <-- TLS crypto file
      - "/mnt/proxy/config/dhparams.pem/:/etc/dovecot/dh.pem:ro"         # <-- same TLS crypto file

    restart: unless-stopped
    stop_grace_period: 1m
    cap_add: [ "NET_ADMIN", "SYS_PTRACE" ]
```

### Relevant log output

```bash
Sun Dec 18 12:00:01 2022 -> --------------------------------------
Sun Dec 18 12:00:01 2022 -> ERROR: Can't create freshclam.dat in /var/lib/clamav
Sun Dec 18 12:00:01 2022 -> Hint: The database directory must be writable for UID 106 or GID 108
Sun Dec 18 12:00:01 2022 -> ERROR: Failed to save freshclam.dat!
Sun Dec 18 12:00:01 2022 -> WARNING: Failed to create a new freshclam.dat!

ad infinitum, ad nauseam
```

### Other relevant information

I repaired it by logging in to the mailserver container and 
`chgrp 108 /var/lib/clamav; chmod g+w /var/lib/clamav.`

But that won't survive a stop and start. I could add a volume to make the changes persistent. But
it probably should be handled in the Dockerfile.

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [X] I am rather experienced with docker
- [ ] I am inexperienced with mail servers
- [X] I am rather experienced with mail servers
- [ ] I am uncomfortable with the CLI
- [X] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution
