### ISSUE TITLE
letsencrypt ssl created but not exists

### ISSUE THREAD

**Issue by vahidalvandi** [docker-mailserver/docker-mailserver#3047]
```
sudo docker run --rm -it \
  -v "${PWD}/docker-data/certbot/certs/:/etc/letsencrypt/" \
  -v "${PWD}/docker-data/certbot/logs/:/var/log/letsencrypt/" \
  -p 80:80 \
  certbot/certbot certonly --standalone -d email.****.com
```

Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/email.****.com/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/email.****.com/privkey.pem

after i moved to 
`cd  /etc/letsencrypt`
`ls `
it is empty not exists live directory

after **sudo docker compose up**

mailserver  | [  ERROR  ]  Cannot find a valid DOMAIN for '/etc/letsencrypt/live/<DOMAIN>/', tried: '', 'email.****.com', '****.com'

**Comment by polarathene** [comment]
Are you actually using `email..com`? Or is this an attempt to hide information? Pretend instead your domain is `example.com`, so `email.example.com`.

You have not provided a `docker-compose.yml`. We do not have sufficient information to understand the problem.

---

> it is empty not exists live directory

You have not been clear here.

`/etc/letsencrypt` is a location in the container only. You have used Docker certbot container to get your certificate, it is storing the `/etc/letsencrypt` content in the local location `./docker-data/certbot/certs/`, verify that content is there.

If the content is there, then mount that into the docker-mailserver container like our SSL docs demonstrate.

**Comment by vahidalvandi** [comment]
this my **docker-compose.yml** 

```
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: email
    domainname: ****.com
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/securit>
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation m>
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    environment:
      - SSL_TYPE=letsencrypt
```

**Comment by vahidalvandi** [comment]
> 

yes cert exists in docker path

/home/ubuntu/docker-data/certbot/certs/live/email.****.com

**Comment by polarathene** [comment]
Thank you.

As [our docs show you](https://docker-mailserver.github.io/docker-mailserver/edge/config/security/ssl/#example-using-docker-for-lets-encrypt), you need to mount that folder:

```yaml
services:
  mailserver:
    # For the FQDN 'mail.example.com':
    hostname: mail
    domainname: example.com
    environment:
      - SSL_TYPE=letsencrypt
    volumes:
      - ./docker-data/certbot/certs/:/etc/letsencrypt
```
