### ISSUE TITLE
Unable to get SMTP working with TLS

### ISSUE THREAD

**Issue by cradcore** [docker-mailserver/docker-mailserver#3102]
I am unable to get SMTP working with a self signed certificate. It works okay without SSL. This is all on my local LAN. 

IMAP works okay:
``` BASH
$ docker exec mailserver openssl s_client -connect 0.0.0.0:143 -starttls imap -CApath /etc/ssl/certs/
Can't use SSL_get_servername
depth=0 CN = cradcore.local Leaf
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = cradcore.local Leaf
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 CN = cradcore.local Leaf
verify return:1
. OK Pre-login capabilities listed, post-login capabilities have more.
DONE
CONNECTED(00000003)
---
Certificate chain
 0 s:CN = cradcore.local Leaf
   i:CN = cradcore.local Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
...
```

SMTP fails:
``` BASH
$ docker exec mailserver openssl s_client -connect 0.0.0.0:25 -starttls smtp -CApath /etc/ssl/certs/
Didn't find STARTTLS in server response, trying anyway...
140468394607936:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331:
CONNECTED(00000003)
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 266 bytes and written 316 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---

```

So does the verification of the cert dates:
``` BASH
$ docker exec mailserver openssl s_client \
  -connect 0.0.0.0:25 \
  -starttls smtp \
  -CApath /etc/ssl/certs/ \
  2>/dev/null | openssl x509 -noout -dates
Could not read certificate from <stdin>
402742DBAB7F0000:error:1608010C:STORE routines:ossl_store_handle_load_result:unsupported:../crypto/store/store_result.c:151:
Unable to load certificate
```

My docker-compose.yml entry:
``` YML
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    cap_add:
      - NET_ADMIN
    container_name: mailserver
    domainname: cradcore.local
    hostname: mailserver
    environment:
      - ENABLE_AMAVIS=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=0
      - ENABLE_SALSAUTHD=0
      - ENABLE_SPAMASSASSIN=0
      - ONE_DIR=1
      - PERMIT_DOCKER=network
      - POSTFIX_INET_PROTOCOLS=ipv4
      - SPOOF_PROTECTION=0
      - SSL_TYPE=self-signed
      - TERM=xterm-256color
      - TZ=America/Denver
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./mailserver/config/:/tmp/docker-mailserver/
      - ./mailserver/config/postfix:/etc/postfix
      - ./mailserver/data/:/var/mail/
      - ./mailserver/logs/:/var/log/mail/
      - ./mailserver/ssl:/tmp/docker-mailserver/ssl
      - ./mailserver/state/:/var/mail-state/
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

And the docker logs:
``` BASH
$ docker logs mailserver
[   INF   ]  Welcome to docker-mailserver 11.3.0
[   INF   ]  Initializing setup
[   INF   ]  Checking configuration
[   INF   ]  Configuring mail server
[ WARNING ]  Alias 'mb@cradcore.local' will not be added to '/etc/dovecot/userdb' twice
[ WARNING ]  Alias 'root@cradcore.local' will not be added to '/etc/dovecot/userdb' twice
[  ERROR  ]  No difference after call to 'sed' in 'sedfile' (sed -i /^smtpd_recipient_restrictions = / s/, reject_rbl_client zen.spamhaus.org=127.0.0.\[2..11\]// /etc/postfix/main.cf)
[  ERROR  ]  No difference after call to 'sed' in 'sedfile' (sed -i -r s|^(smtpd_tls_chain_files =).*|\1 /etc/dms/tls/mailserver.cradcore.local-key.pem /etc/dms/tls/mailserver.cradcore.local-cert.pem| /etc/postfix/main.cf)
[  ERROR  ]  No difference after call to 'sed' in 'sedfile' (sed -i -r s|^#?(smtpd?_tls_CAfile =).*|\1 /etc/dms/tls/cacert.pem| /etc/postfix/main.cf)
[   INF   ]  Post-configuration checks
[   INF   ]  Starting miscellaneous tasks
[   INF   ]  Starting daemons
[   INF   ]  mailserver.cradcore.local is up and running
```

I had originally tried using a certificate generated by a self-signed CA I use on my local network, and then followed the instructions (in the wiki)[https://docker-mailserver.github.io/docker-mailserver/edge/config/security/ssl/#self-signed-certificates] but both produce the same error.

Please help me understand what I'm missing here
