### ISSUE TITLE
return error in gmail with other domain

### ISSUE THREAD

**Issue by vahidalvandi** [docker-mailserver/docker-mailserver#3180]
main server is **mail.mailerchi.ir** 
i want use multi domain feature , i added new email like `sudo ./setup.sh email add info@webine.ir` and add a dns zone in webine.ir 

a   record   x.x.x.x
mail.webine.ir mx x.x.x.x
dkim , spf , dmarc 

also in mailerchi.ir 

a   record   x.x.x.x
mail.mailerchi.ir mx x.x.x.x
dkim , spf , dmarc 

with equal ip address

All the settings are correct, but when I send an email from info@webine.ir, it gives the following error, but when I send from info@mailerchi.ir, I have no problem.

```

This is the mail system at host mail.mailerchi.ir.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

[<va6893@gmail.com>](mailto:va6893@gmail.com): host alt1.gmail-smtp-in.l.google.com[142.250.150.26] said:
    550-5.7.1 [109.122.199.13      12] Our system has detected that this
    message is 550-5.7.1 likely unsolicited mail. To reduce the amount of spam
    sent to Gmail, 550-5.7.1 this message has been blocked. Please visit
    550-5.7.1  https://support.google.com/mail/?p=UnsolicitedMessageError 550
    5.7.1  for more information.
    f21-20020ac25335000000b004d98a4cc75dsi2328779lfh.376 - gsmtp (in reply to
    end of DATA command)


Reporting-MTA: dns; mail.mailerchi.ir
X-Postfix-Queue-ID: 45EC180F61
X-Postfix-Sender: rfc822; [info@webine.ir](mailto:info@webine.ir)
Arrival-Date: Sat, 18 Mar 2023 21:18:48 +0330 (+0330)

Final-Recipient: rfc822; [va6893@gmail.com](mailto:va6893@gmail.com)
Original-Recipient: [rfc822;va6893@gmail.com](mailto:rfc822;va6893@gmail.com)
Action: failed
Status: 5.7.1
Remote-MTA: dns; alt1.gmail-smtp-in.l.google.com
Diagnostic-Code: smtp; 550-5.7.1 [109.122.199.13      12] Our system has
    detected that this message is 550-5.7.1 likely unsolicited mail. To reduce
    the amount of spam sent to Gmail, 550-5.7.1 this message has been blocked.
    Please visit 550-5.7.1
    https://support.google.com/mail/?p=UnsolicitedMessageError 550 5.7.1  for
    more information. f21-20020ac25335000000b004d98a4cc75dsi2328779lfh.376 -
    gsmtp

```

aslo this my docker-compose.yml

```
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail
    domainname: mailerchi.ir
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      #- "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      #- "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ./docker-data/certbot/certs/:/etc/letsencrypt
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - SSL_TYPE=letsencrypt
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

```
