### ISSUE TITLE
Mail server can not connect LDAP server

### ISSUE THREAD

**Issue by wang-dagou** [docker-mailserver/docker-mailserver#3195]
Recently, I deployed docker mail server, and I want it to authenticate users to log in through ldap. Unfortunately, it seems that I have specified the authentication method for ldap, but mail server always logs in through passwd file. I will send my configuration to you. I hope someone with a heart can help me find out where my configuration is incorrect. Thank you very much

mailserver.env
```
AUTH_MECHANISMS=PLAIN LOGIN CRAM-MD5 DIGEST-MD5 NTLM XOAUTH2
ENABLE_LDAP=true
LDAP_START_TLS=false
LDAP_SERVER_HOST=192.168.102.221
LDAP_SEARCH_BASE=dc=ldap,dc=sichuancredit,dc=cn
LDAP_BIND_DN=cn=admin,dc=ldap,dc=sichuancredit,dc=cn
LDAP_BIND_PW=xxxxxxxx
LDAP_QUERY_FILTER_USER=(&(objectclass=inetOrgPerson)(memberOf=cn=development,ou=groups,dc=ldap,dc=sichuancredit,dc=cn)(mail=%u))
```

docker-compose.yml
```
services:
  mailserver:
    image: registry.sichuancredit.cn/base/mail-server:latest
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail
    domainname: sichuancredit.cn
    env_file: mailserver.env
    dns: 8.8.8.8
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
      - "110:110"
      - "995:995"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /Mail/docker-mailserver-11.3.1/ssl:/tmp/ssl:ro
      - /etc/resolv.conf:/etc/resolv.conf
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

```
