### ISSUE TITLE
[BUG] Mailbox isn't owned by user, can't save messages

### ISSUE THREAD

**Issue by shruuub** [docker-mailserver/docker-mailserver#3221]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

Sending messages works fine, however, when a email is sent to the user, after the mailserver completes all the checks, it says (stripped):cannot update mailbox /var/mail/user

### What happened and when does this occur?

```
Apr  5 08:07:56 mail postfix/qmgr[1162]: 46CA45004FFD: from=<hello@example.com>, size=2151, nrcpt=1 (queue active)
Apr  5 08:07:56 mail postfix/trivial-rewrite[1865]: warning: do not list domain mail.example.com in BOTH mydestination and virtual_mailbox_domains
Apr  5 08:07:56 mail postfix/local[2876]: warning: specify "strict_mailbox_ownership = no" to ignore mailbox ownership mismatch
Apr  5 08:07:56 mail postfix/local[2876]: 46CA45004FFD: to=<mail@mail.example.com>, relay=local, delay=357, delays=357/0.01/0/0.02, dsn=4.2.0, status=deferred (cannot update mailbox /var/mail/mail for user mail. destination /var/mail/mail is not owned by recipient)
```

Sending a mail from the real domain to the subdomain dms is hosted on to the user mail. The same occures for every other mailprovider though. Everything works, but the email isn't saved, supposedly because of permission errors. Probably an easy fix, but I'm not sure how, and the interwebs didn't give anything useful as well.

### What did you expect to happen?

Messages getting saved on the server and showing up in my IMAP inbox folder.

### How do we replicate the issue?

1.Run a mailserver (on a subdomain)
2. Add an user
3.Send an email to said user from an external account.

### DMS version

v.11.3.0

### What operating system is DMS running on?

Linux

### Which operating system version?

Debian 11

### What instruction set architecture is DMS running on?

AMD64 / x86_64

### What container orchestration tool are you using?

Docker

### docker-compose.yml

```yml
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:11.3.0
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.example.com
    domainname: mail.example.com
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
      - "993:993"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ./docker-data/certbot/certs/:/etc/letsencrypt
    environment:
      - ENABLE_FAIL2BAN=1
      # Using letsencrypt for SSL/TLS certificates
      - SSL_TYPE=letsencrypt
      # Allow sending emails from other docker containers
      # Beware creating an Open Relay: https://docker-mailserver.github.io/docker-mailserver/latest/config/environment/#permit_docker
      - PERMIT_DOCKER=network
      # You may want to enable this: https://docker-mailserver.github.io/docker-mailserver/latest/config/environment/#spoof_protection
      # See step 8 below, which demonstrates setup with enabled/disabled SPOOF_PROTECTION:
      - SPOOF_PROTECTION=0
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    restart: always
  ipv6nat:
    image: robbertkl/ipv6nat
    restart: always
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro


networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: fd00:0123:4567::/48
          gateway: fd00:0123:4567::1
```

### What level of experience do you have with Docker and mail servers?

- [ ] I am inexperienced with docker
- [X] I am rather experienced with docker
- [X] I am inexperienced with mail servers
- [ ] I am rather experienced with mail servers
- [X] I am uncomfortable with the CLI
- [ ] I am rather comfortable with the CLI

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution
