### ISSUE TITLE
other: Thunderbird cannot store messages with file attachments >10m over imap

### ISSUE THREAD

**Issue by Artenuvielle** [docker-mailserver/docker-mailserver#3274]
### Subject

Other

### Description

I am not sure if it is a misconfiguration on my side, a bug or simply not possible with Thunderbird:

I set up a docker-mailserver (version 12.0.0) via portainer and added a user via the setup.sh script via ssh. I can connect to the server via Thunderburd and send and receive mails correctly. However when creating a new mail, adding a file attachment (15mb, I think error starts at message sizes >10mb) and trying to save it as a draft Thunderbird errors with the following message ({} means roughly translated from german):
`{The current process in "Drafts" has failed. The server of the account "user@example.com" answered:} [LIMIT] Mail size is larger than the maximum size allowed by server configuration (0.001 + 0.000 secs).`

This is the docker-compose of the stack:
```
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    hostname: mail
    domainname: example.com
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - mailserver-mail-data:/var/mail/
      - mailserver-mail-state:/var/mail-state/
      - mailserver-mail-logs:/var/log/mail/
      - mailserver-config:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - certs:/certs:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    env_file: stack.env

volumes:
  mailserver-mail-data:
    external: true
  mailserver-mail-state:
    external: true
  mailserver-mail-logs:
    external: true
  mailserver-config:
    external: true
  certs:
    external: true
```

With the following env variables:
```
OVERRIDE_HOSTNAME=
LOG_LEVEL=debug
SUPERVISOR_LOGLEVEL=
ONE_DIR=1
ACCOUNT_PROVISIONER=
PERMIT_DOCKER=none
TZ=Europe/Berlin
ENABLE_AMAVIS=1
AMAVIS_LOGLEVEL=0
ENABLE_DNSBL=0
ENABLE_OPENDKIM=1
ENABLE_OPENDMARC=1
ENABLE_POP3=
ENABLE_CLAMAV=0
ENABLE_FAIL2BAN=1
FAIL2BAN_BLOCKTYPE=drop
SMTP_ONLY=
SSL_TYPE=manual
SSL_CERT_PATH=/certs/fullchain.pem
SSL_KEY_PATH=/certs/privkey.pem
TLS_LEVEL=
SPOOF_PROTECTION=1
ENABLE_SRS=0
NETWORK_INTERFACE=
VIRUSMAILS_DELETE_DELAY=
POSTFIX_DAGENT=
POSTFIX_MAILBOX_SIZE_LIMIT=52428800
ENABLE_QUOTAS=1
POSTFIX_MESSAGE_SIZE_LIMIT=
CLAMAV_MESSAGE_SIZE_LIMIT=
ENABLE_MANAGESIEVE=
POSTMASTER_ADDRESS=external@gmail.com
ENABLE_UPDATE_CHECK=1
UPDATE_CHECK_INTERVAL=1d
POSTSCREEN_ACTION=enforce
DOVECOT_MAILBOX_FORMAT=maildir
POSTFIX_INET_PROTOCOLS=all
DOVECOT_INET_PROTOCOLS=all
MOVE_SPAM_TO_JUNK=1
ENABLE_RSPAMD=
ENABLE_RSPAMD_REDIS=
RSPAMD_LEARN=
PFLOGSUMM_TRIGGER=
PFLOGSUMM_RECIPIENT=
PFLOGSUMM_SENDER=
LOGWATCH_INTERVAL=
LOGWATCH_RECIPIENT=
LOGWATCH_SENDER=
REPORT_RECIPIENT=0
REPORT_SENDER=
LOGROTATE_INTERVAL=daily
ENABLE_SPAMASSASSIN=1
SPAMASSASSIN_SPAM_TO_INBOX=1
ENABLE_SPAMASSASSIN_KAM=0
SA_TAG=2.0
SA_TAG2=6.31
SA_KILL=10.0
SA_SPAM_SUBJECT=***SPAM*****
SA_SHORTCIRCUIT_BAYES_SPAM=
SA_SHORTCIRCUIT_BAYES_HAM=
ENABLE_FETCHMAIL=0
FETCHMAIL_POLL=300
FETCHMAIL_PARALLEL=
ENABLE_LDAP=
LDAP_START_TLS=
LDAP_SERVER_HOST=
LDAP_SEARCH_BASE=
LDAP_BIND_DN=
LDAP_BIND_PW=
LDAP_QUERY_FILTER_USER=
LDAP_QUERY_FILTER_GROUP=
LDAP_QUERY_FILTER_ALIAS=
LDAP_QUERY_FILTER_DOMAIN=
LDAP_QUERY_FILTER_SENDERS=
DOVECOT_TLS=
DOVECOT_BASE=
DOVECOT_DEFAULT_PASS_SCHEME=
DOVECOT_DN=
DOVECOT_DNPASS=
DOVECOT_URIS=
DOVECOT_LDAP_VERSION=
DOVECOT_AUTH_BIND=
DOVECOT_USER_FILTER=
DOVECOT_USER_ATTRS=
DOVECOT_PASS_FILTER=
DOVECOT_PASS_ATTRS=
ENABLE_POSTGREY=1
POSTGREY_DELAY=300
POSTGREY_MAX_AGE=35
POSTGREY_AUTO_WHITELIST_CLIENTS=5
POSTGREY_TEXT="Delayed by Postgrey"
ENABLE_SASLAUTHD=0
SASLAUTHD_MECHANISMS=
SASLAUTHD_MECH_OPTIONS=
SASLAUTHD_LDAP_SERVER=
SASLAUTHD_LDAP_START_TLS=
SASLAUTHD_LDAP_TLS_CHECK_PEER=
SASLAUTHD_LDAP_TLS_CACERT_DIR=
SASLAUTHD_LDAP_TLS_CACERT_FILE=
SASLAUTHD_LDAP_BIND_DN=
SASLAUTHD_LDAP_PASSWORD=
SASLAUTHD_LDAP_SEARCH_BASE=
SASLAUTHD_LDAP_FILTER=
SASLAUTHD_LDAP_PASSWORD_ATTR=
SASLAUTHD_LDAP_AUTH_METHOD=
SASLAUTHD_LDAP_MECH=
SRS_SENDER_CLASSES=envelope_sender
SRS_EXCLUDE_DOMAINS=
SRS_SECRET=
SRS_DOMAINNAME=
DEFAULT_RELAY_HOST=
RELAY_HOST=
RELAY_PORT=25
RELAY_USER=
RELAY_PASSWORD=
```
