### ISSUE TITLE
bug report: Rspamd configuration is not taken into account when using `setup config dkim`

### ISSUE THREAD

**Issue by tchapi** [docker-mailserver/docker-mailserver#3321]
### Preliminary Checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.
- [X] I searched the issue tracker but was unable to find my issue.
- [X] I read the [extended documentation in general](https://docker-mailserver.github.io/docker-mailserver/latest/) but found nothing to resolve the issue.
- [X] I read the [documentation on debugging](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/), tried the proposed steps to debug the problem, but was still unable to resolve the issue.
- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree

### Foreword

Thank you for this amazing piece of software 🙌🏼 !!

### Affected Component(s)

Rspamd / DKIM

### What happened and when does this occur?

Using the provided example docker-compose file (verbatim from [here](https://docker-mailserver.github.io/docker-mailserver/latest/examples/tutorials/basic-installation/)) where `ENABLE_RSPAMD=1`.

I want to create the DKIM configuration, using Rspamd, so I:

1. Create a first user:

```
❯ docker compose run mailserver setup email add user@example.com
Enter Password: *****
```

2. Then start the container to see if everything works (it does):

```
❯ docker compose up
[+] Running 1/0
 ✔ Container mailserver  Created                                                                                                                                                                                         
Attaching to mailserver
mailserver  | [   INF   ]  Welcome to docker-mailserver 12.1.0
mailserver  | [   INF   ]  Checking configuration
mailserver  | [   INF   ]  Configuring mail server
mailserver  | [ WARNING ]  !! INSECURE !! SSL configured with plain text access - DO NOT USE FOR PRODUCTION DEPLOYMENT
mailserver  | [   INF   ]  Starting daemons
mailserver  | [   INF   ]  mail.example.com is up and running
...
```

3. Then try to create the DKIM config as specified in the [documentation](https://docker-mailserver.github.io/docker-mailserver/latest/config/best-practices/dkim_dmarc_spf/)

```
❯ docker compose run mailserver setup config dkim
[   INF   ]  Creating DKIM private key '/tmp/docker-mailserver/opendkim/keys/example.com/mail.private'
```

➡️ It's using the open-dkim flavour, not the rspamd-dkim flavour

> **Note**
>
> Using `setup` directly in the running container yields the same result

### What did you expect to happen?

Have the keys created in the Rspamd flavour (in /config/rspamd/...) , not the OpenDKIM one

### How do we replicate the issue?

See above ⏫ 

### DMS version

latest from ghcr.io

### What operating system is DMS running on?

macOS (not officially supported)

### Which operating system version?

darwin/Ventura

### What instruction set architecture is DMS running on?

ARM64 / AArch64 (ARM v8 and newer)
M1 mac FYI

### What container orchestration tool are you using?

Docker Compose

### compose.yaml

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.example.com
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_RSPAMD=1
      - ENABLE_OPENDKIM=0
      - ENABLE_OPENDMARC=0
      - ENABLE_POLICYD_SPF=0
      - ENABLE_AMAVIS=0
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    restart: always
```

### Relevant log output

The env var is correctly set

```
❯ docker compose run -it mailserver bash
root@mail:/# printenv | grep RSPAMD
ENABLE_RSPAMD=1
```

But I think `/etc/dms-settings` is not correctly created:

```
❯ docker compose run -it mailserver bash
root@mail:/# ls /etc/dms-settings
ls: cannot access '/etc/dms-settings': No such file or directory
```

### Other relevant information

It _might_ be a macOS issue but I don't see why this specific `/etc/dms-settings` would fail to be created, tbh.

💁🏼 Happy to help debug if needed

### What level of experience do you have with Docker and mail servers?

- [X] I am rather experienced with docker
- [X] I am rather experienced with mail servers
- [X] I am rather comfortable with the CLI
