### ISSUE TITLE
bug report: Email forwarding no longer possible in v12.1 after MR #3270

### ISSUE THREAD

**Issue by JuroOravec** [docker-mailserver/docker-mailserver#3350]
### Preliminary Checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.
- [X] I searched the issue tracker but was unable to find my issue.
- [X] I read

  - the [extended documentation in general](https://docker-mailserver.github.io/docker-mailserver/latest/) but found nothing to resolve the issue;
  - the [documentation on debugging](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/), tried the proposed steps to debug the problem, but was still unable to resolve the issue;
  - this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree;
  - the [documentation about filing a bug report](https://docker-mailserver.github.io/docker-mailserver/latest/contributing/issues-and-pull-requests/#filing-a-bug-report).

### What operating system is the host running?

Linux

### Which operating system version?

Ubuntu 22

### What computer architecture is the host running?

AMD64 (x86_64)

### What container orchestration tool are you using?

Docker

### DMS version

v12.0

### What happened and when does this occur?

Context:

These tutorials suggest that if you create an email (using the `setup` script), and then alias it to an external email address, that you can get Docker Mailserver to forward the emails:
- https://docker-mailserver.github.io/docker-mailserver/latest/examples/tutorials/basic-installation/#using-dms-as-a-local-mail-relay-for-containers
- https://www.libe.net/en-docker-mailserver#mail-server-commissioning

However, this doesn't work anymore in v12.1. The error message (`[...] is already defined as an account`) led me to believe it's because of this change (https://github.com/docker-mailserver/docker-mailserver/pull/3270) introduced last month.

When I used mailserver version 12.0, it did work as expected - I could set up alias for an email and that way force the mailserver to forward the email. (Then I had other issues and ultimately failed trying to forward emails to my Gmail account, but that's a whole different story).

### What did you expect to happen?

Be able to use Docker Mailserver to forward incoming emails to 3rd party email address.

If there is a different (preferred) way to forward emails, I'm happy to use that. But if not and the change in https://github.com/docker-mailserver/docker-mailserver/pull/3270 broke the only option, that sounds like a bug that needs fixin'.

### Container configuration files

```yml
services:
  mailserver:
    # NOTE: Do not upgrade beyond 12.0.
    # This MR broke the option to forward email
    # https://github.com/docker-mailserver/docker-mailserver/pull/3270
    image: ghcr.io/docker-mailserver/docker-mailserver:12.0
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: system-mail.example.com
    env_file: mailserver.env
    environment:
      - RELAY_PASSWORD=${MAIL_RELAY_PASSWORD}
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./volumes/dms/mail-data/:/var/mail/
      - ./volumes/dms/mail-state/:/var/mail-state/
      - ./volumes/dms/mail-logs/:/var/log/mail/
      - ./volumes/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/certbot/conf:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### What level of experience do you have with containers, mail servers, and using a terminal?

- [ ] I am inexperienced with containers
- [X] I am rather experienced with containers
- [X] I am inexperienced with mail servers
- [ ] I am rather experienced with mail servers
- [ ] I am uncomfortable with using a terminal (CLI)
- [X] I am rather comfortable with using a terminal (CLI)
