### ISSUE TITLE
bug report: incoming mail delays and then extensive log file entries

### ISSUE THREAD

**Issue by MarcS1975** [docker-mailserver/docker-mailserver#3362]
### Preliminary Checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.
- [X] I searched the issue tracker but was unable to find my issue.
- [X] I read

  - the [extended documentation in general](https://docker-mailserver.github.io/docker-mailserver/latest/) but found nothing to resolve the issue;
  - the [documentation on debugging](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/), tried the proposed steps to debug the problem, but was still unable to resolve the issue;
  - this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree;
  - the [documentation about filing a bug report](https://docker-mailserver.github.io/docker-mailserver/latest/contributing/issues-and-pull-requests/#filing-a-bug-report).

### What operating system is the host running?

Linux

### Which operating system version?

Debian 11

### What computer architecture is the host running?

ARM64 (AArch64)

### What container orchestration tool are you using?

Docker Compose

### DMS version

12.1

### What happened and when does this occur?

When someone new is sending me emails, there is a **45-60min delay** during which no mailserver log entries are generated, and then suddenly the mailserver log file is flooded with 1000s of lines like below.
Where is the mail for 45mins? 

### What did you expect to happen?

I expect emails to arrive instantly (like emails from known senders)

### Container configuration files

```yml
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver2
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    
    hostname: mail.mydomain.com
    ports:
      - "28:25"
      - "146:143"
      - "590:587"
      - "997:993"
      - "468:465"
    volumes:
    - /srv/dev-disk-by-uuid-14a35ebc-6358-492c-af84-4e920f0c55bc/Docker/volumes/ajmail2/mail-data/:/var/mail/
    - /srv/dev-disk-by-uuid-14a35ebc-6358-492c-af84-4e920f0c55bc/Docker/volumes/ajmail2/mail-state/:/var/mail-state/
    - /srv/dev-disk-by-uuid-14a35ebc-6358-492c-af84-4e920f0c55bc/Docker/volumes/ajmail2/mail-logs/:/var/log/mail/
    - /srv/dev-disk-by-uuid-14a35ebc-6358-492c-af84-4e920f0c55bc/Docker/volumes/ajmail2/config/:/tmp/docker-mailserver/
    - /etc/localtime/:/etc/localtime:ro
    - /srv/dev-disk-by-uuid-14a35ebc-6358-492c-af84-4e920f0c55bc/Docker/volumes/letsencrypt/fromDSM_T17/xmail44.win/:/tmp/dms/custom-certs/
    
    environment:
      - LOG_LEVEL=debug #by AJ
      - PFLOGSUMM_TRIGGER=daily_cron # by AJ
      - PFLOGSUMM_RECIPIENT=mymail@gmail.com # by AJ
      - LOGWATCH_INTERVAL=daily # by AJ
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=0 # by AJ
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/tmp/dms/custom-certs/fullchain.pem
      - SSL_KEY_PATH=/tmp/dms/custom-certs/privkey.pem
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
```

### Relevant log output

```Text
`action=pass, reason=client whitelist, client_name=mail-cwlgbr01on2069.outbound.protection.outlook.com, client_address=yy.yyy.yyy.yy/32, sender=send-user@xxx.com, recipient=myUser@MYDOMAIN`
```

### What level of experience do you have with containers, mail servers, and using a terminal?

- [ ] I am inexperienced with containers
- [X] I am rather experienced with containers
- [X] I am inexperienced with mail servers
- [ ] I am rather experienced with mail servers
- [ ] I am uncomfortable with using a terminal (CLI)
- [X] I am rather comfortable with using a terminal (CLI)
