### ISSUE TITLE
bug report: Rspamd crash when sending or receiving

### ISSUE THREAD

**Issue by FriderKlugser** [docker-mailserver/docker-mailserver#3374]
### Preliminary Checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.
- [X] I searched the issue tracker but was unable to find my issue.
- [X] I read

  - the [extended documentation in general](https://docker-mailserver.github.io/docker-mailserver/latest/) but found nothing to resolve the issue;
  - the [documentation on debugging](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/), tried the proposed steps to debug the problem, but was still unable to resolve the issue;
  - this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree;
  - the [documentation about filing a bug report](https://docker-mailserver.github.io/docker-mailserver/latest/contributing/issues-and-pull-requests/#filing-a-bug-report).

### What operating system is the host running?

Linux

### Which operating system version?

Debian 11 (Bullseye)

### What computer architecture is the host running?

ARM64 (AArch64)

### What container orchestration tool are you using?

Docker Compose

### DMS version

v12.1.0

### What happened and when does this occur?

From time to time Rspamd crashs when sending or receiving an e-mail. And then doesn't check e-mails properly, as seen (missing) in the Web interface history.

I'm running DMS on an Raspberry Pi 4 (8 GB).

### What did you expect to happen?

No Rspamd crashs.

### Container configuration files

compose.yaml
```YAML
services:
  Mailserver:
    container_name: Mailserver
    hostname: mx.domain.tld
    image: docker.io/mailserver/docker-mailserver:latest
    pull_policy: always
    healthcheck: {disable: true}
    restart: unless-stopped
    stop_grace_period: 1m30s
    stdin_open: true
    tty: true
    networks: [bridge-mail]
    cap_add: [NET_ADMIN]
    ports:
    - "25:25"
    - "143:143"
    - "465:465"
    - "587:587"
    - "993:993"
    - "4190:4190" # ManageSieve
    - "11334:11334" # Rspamd
    volumes:
    - ./Mailserver/config:/tmp/docker-mailserver:rw
    - ./Mailserver/data:/var/mail:rw
    - ./Mailserver/state:/var/mail-state:rw
    - ./Mailserver/log:/var/log/mail:rw
    - ./Certbot/etc/archive/domain.tld:/etc/letsencrypt/archive/domain.tld:ro
    - ./Certbot/etc/live/domain.tld:/etc/letsencrypt/live/domain.tld:ro
    env_file: ./Mailserver/mailserver.env

networks:
  bridge-mail:
    name: bridge-mail
    driver: bridge
```

mailserver.env Changes
```Dotenv
TZ=Europe/Berlin

SPOOF_PROTECTION=1

ENABLE_OPENDKIM=0
ENABLE_OPENDMARC=0
ENABLE_POLICYD_SPF=0
ENABLE_CLAMAV=1
ENABLE_RSPAMD=1
ENABLE_AMAVIS=0
ENABLE_DNSBL=1
ENABLE_FAIL2BAN=1

SSL_TYPE=letsencrypt

POSTFIX_INET_PROTOCOLS=ipv4
DOVECOT_INET_PROTOCOLS=ipv4

DEFAULT_RELAY_HOST=[host.provider.tld]:465
RELAY_HOST=host.provider.tld
RELAY_PORT=465
RELAY_USER=relay_user@domain.tld
RELAY_PASSWORD=...
```

postfix-main.cf
```INI
myorigin = $mydomain
smtp_tls_wrappermode = yes
```

postfix-regexp.cf
```
/^(abuse|admin|administrator|hostmaster|postmaster|security|webmaster)@(domain\.tld|otherdomain\.othertld)$/ user@domain.tld
```

dkim_signing.conf
```INI
allow_username_mismatch = true;

selector = "email";
path = "/tmp/docker-mailserver/rspamd/dkim/rsa-2048-$selector-$domain.private.txt";
```

worker-controller.inc
```INI
password = "...";
enable_password = "...";
```

### Relevant log output

```Text
/var/log/supervisor/rspamd.log
2023-05-28 21:21:56 #609(rspamd_proxy) rspamd_crash_sig_handler: caught fatal signal 11(Segmentation fault), pid: 609, trace:
2023-05-28 21:21:56 #609(rspamd_proxy) rspamd_print_crash: 0: 0000007FA202F9D4: <unknown>
2023-05-28 21:21:56 #609(rspamd_proxy) rspamd_print_crash: 1: 000000000000003A: <unknown>
2023-05-28 21:21:56 #582(main) <65aa52>; main; rspamd_check_termination_clause: rspamd_proxy process 609 terminated abnormally with exit code 0 by signal: Segmentation fault but NOT created core file (throttled=no); core file limits: -1 current, -1 max
2023-05-28 21:21:56 #582(main) <65aa52>; main; rspamd_cld_handler: respawn process rspamd_proxy in lieu of terminated process with pid 609
2023-05-28 21:21:58 #582(main) <65aa52>; main; rspamd_fork_worker: prepare to fork process rspamd_proxy (1); listen on: 127.0.0.1:11332
2023-05-28 21:21:58 #919093(rspamd_proxy) <65aa52>; main; rspamd_worker_set_limits: use system max file descriptors limit: 1024KiB cur and 1024KiB max
2023-05-28 21:21:58 #919093(rspamd_proxy) <65aa52>; main; rspamd_worker_set_limits: use system max core size limit: -1B cur and -1B max
2023-05-28 21:22:13 #608(rspamd_proxy) <f29daa>; proxy; rspamd_redis_connected: skip obtaining bayes tokens for BAYES_HAM of classifier bayes: not enough learns 0; 200 required
2023-05-28 21:22:13 #608(rspamd_proxy) <f29daa>; proxy; rspamd_redis_connected: skip obtaining bayes tokens for BAYES_SPAM of classifier bayes: not enough learns 0; 200 required
```

I don't know if it has something to do with the following Output:

```
/var/log/supervisor/rspamd-redis.log
# WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
```

### What level of experience do you have with containers, mail servers, and using a terminal?

- [ ] I am inexperienced with containers
- [X] I am rather experienced with containers
- [ ] I am inexperienced with mail servers
- [X] I am rather experienced with mail servers
- [ ] I am uncomfortable with using a terminal (CLI)
- [X] I am rather comfortable with using a terminal (CLI)

**Comment by polarathene** [comment]
> `rspamd_worker_set_limits`

These seem to be about [this part of rspamd codebase](https://github.com/rspamd/rspamd/blob/770e290862b105ed5700a1c769452adc39bb77b9/src/libserver/worker_util.c#L714-L816). I don't know if it would help, but presently Dockers systemd unit files set these limits too high by default, and since rspamd has code referencing them it might be a concern.

For now can you try see if this helps resolve the issue? [Adjust the `ulimits` for your DMS service in compose](https://docs.docker.com/compose/compose-file/05-services/#ulimits):

```
ulimits:
  nproc: 65535
  nofile:
    soft: 1024
    hard: 524288
```

The `nofile` values are more sane at least. I'm not quite sure about `nproc`, and if that should differ with soft/hard limits.

On one of my 1GB RAM VPS instances the host has only `3246` for `nproc` (`ulimit -Su && ulimit -Hu`). IIRC the `nproc` default value scales based on system memory available, so on your Pi it might be more like 24k? Docker sets it to `infinity` (highest possible), which I don't think is prone to problems like `nofile` can be, but maybe something more sane like the 65k above (`2^16`) is ok, or you could try with the `ulimit -Hu` value reported on your RPi system.

That will at least help rule out these concerns :sweat_smile: 

---

> `# WARNING overcommit_memory is set to 0! Background save may fail under low memory condition.`

This is just a warning from Redis. You'd need to adjust this kernel setting with `sysctl` to make it happy.

It's probably not related to the issue. AFAIK, it is saying that it can be less strict about memory allocation, but if your Pi is low on memory to persist the DB from RAM to disk (_it needs double the amount Redis is using I think_), then you'd be at risk of that failing.

If your Pi is low on available memory when this issue happens, it might be worth trying and letting us know if it resolves the issue.

---

> ```
> #609(rspamd_proxy) rspamd_crash_sig_handler: caught fatal signal 11(Segmentation fault), pid: 609, trace:
> #582(main) <65aa52>; main; rspamd_check_termination_clause: rspamd_proxy process 609 terminated abnormally with exit code 0 by signal: Segmentation fault but NOT created core file (throttled=no); core file limits: -1 current, -1 max
> #582(main) <65aa52>; main; rspamd_cld_handler: respawn process rspamd_proxy in lieu of terminated process with pid 609
> ```

Is it possible that this is crashing low on memory? If it is, you could try using zram perhaps or adding enough swap on disk to try see if this extends the time required for a crash to occur?
