### ISSUE TITLE
bug report: SASL disabled by default and can't enable without adding SMTP_ONLY

### ISSUE THREAD

**Issue by mvlahovski** [docker-mailserver/docker-mailserver#3386]
### 📝 Preliminary Checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.
- [X] I searched the issue tracker but was unable to find my issue.
- [X] I have read:  
  - The [extended documentation in general](https://docker-mailserver.github.io/docker-mailserver/latest/) but found nothing to resolve the issue;
  - The [documentation on debugging](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/), tried the proposed steps to debug the problem, but was still unable to resolve the issue;
  - This project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree;
  - The [documentation about filing a bug report](https://docker-mailserver.github.io/docker-mailserver/latest/contributing/issues-and-pull-requests/#filing-a-bug-report).

### 👀 What Happened?

I deployed docker-mailserver for the first time yesterday using latest, however I'm not able to enable authentication for smtpd, thus getting "503 5.5.1 Error: authentication not enabled" errors. I need to have "smtpd_sasl_auth_enable = yes" in main.cf, however I find it impossible to set that to yes by using the DMS environment variables.

I found that https://github.com/docker-mailserver/docker-mailserver/issues/1796 possibly lead to this code in Feb-2021 (target/scripts/startup/setup.d/postfix.sh):

  if [[ ${ENABLE_SASLAUTHD} -eq 0 ]] && [[ ${SMTP_ONLY} -eq 1 ]]; then
    sed -i -E \
      's|^smtpd_sasl_auth_enable =.*|smtpd_sasl_auth_enable = no|g' \
      /etc/postfix/main.cf
    sed -i -E \
      's|^  -o smtpd_sasl_auth_enable=.*|  -o smtpd_sasl_auth_enable=no|g' \
      /etc/postfix/master.cf
  fi

At the time the default setting for smtpd_sasl_auth_enable was "yes" which meant it gets disabled when ENABLE_SASLAUTHD=0 and SMTP_ONLY=1 - and doesn't get touched under any other cisrcumstances.

However this commit https://github.com/docker-mailserver/docker-mailserver/commit/199e3c77214290f16b97dcccb97c1c3a6a5d0aeb from Feb-2023 changed the default setting of smtpd_sasl_auth_enable to "no", and there is no way to set it to yes with the existing code (unless you set SMTP_ONLY=1 which is not what I need).

Note I have not enabled SSL yet.

Workaround:
When I mount main.cf directly as a volume and set smtpd_sasl_auth_enable to "yes", this works as expected:
    volumes:
      - ./docker-data/dms/config/main.cf:/etc/postfix/main.cf

Please advise.

### 👟 Reproduction Steps

Deploy with docker-compose.yml pointing to latest:
image: ghcr.io/docker-mailserver/docker-mailserver:latest

 - set ENABLE_SASLAUTHD=1 in mailserver.env, result is:

$ docker exec -it mailserver grep smtpd_sasl_auth_enable /etc/postfix/main.cf
/etc/postfix/main.cf:smtpd_sasl_auth_enable = no

And when trying to authenticate connecting to SMTP server:
AUTH LOGIN
503 5.5.1 Error: authentication not enabled

### 🐋 DMS Version

v12.1.0

### 💻 Operating System and Architecture

CentOS Linux release 7.9.2009 (Core)

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: <hostname>
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```
