### ISSUE TITLE
bug report: editing before.dovecot.sieve requires a container restart

### ISSUE THREAD

**Issue by kirillrogovoy** [docker-mailserver/docker-mailserver#3392]
### 📝 Preliminary Checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.
- [X] I searched the issue tracker but was unable to find my issue.
- [X] I have read:  
  - The [extended documentation in general](https://docker-mailserver.github.io/docker-mailserver/latest/) but found nothing to resolve the issue;
  - The [documentation on debugging](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/), tried the proposed steps to debug the problem, but was still unable to resolve the issue;
  - This project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree;
  - The [documentation about filing a bug report](https://docker-mailserver.github.io/docker-mailserver/latest/contributing/issues-and-pull-requests/#filing-a-bug-report).

### 👀 What Happened?

I use before.dovecot.sieve for generic email filtering.

Every time I edit that file on the host, the new rules don't get applied.

I sh-ed into the container and ran
```sh
cat /usr/lib/dovecot/sieve-global/before/50-before.dovecot.sieve
```
to make sure that this file is outdated until I go `docker compose down && docker compose up -d`

It seems that there **is** automatic change detection for a number of postfix and dovecot files, so this behavior was unexpected.

### 👟 Reproduction Steps

1. Add `before.dovecot.sieve` following the guide here: https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/mail-sieve/
2. Restart the container.
3. SH inside the container and make sure that `cat /usr/lib/dovecot/sieve-global/before/50-before.dovecot.sieve` shows you the latest version of the file.
4. Change ` before.dovecot.sieve` on the host.
5. SH inside the container and make sure that `cat /usr/lib/dovecot/sieve-global/before/50-before.dovecot.sieve` shows you the **old** version of the file.
6. Optionally, you may send yourself an email that would prove that the rules from the latest version don't apply.

### 🐋 DMS Version

v12.1.0

### 💻 Operating System and Architecture

Stock Ubuntu 22.04.2 LTS on Hetzner

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.rogovoy.me
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25" # SMTP  (explicit TLS => STARTTLS)
      # - "143:143" # IMAP4 (explicit TLS => STARTTLS)
      - "465:465" # ESMTP (implicit TLS)
      # - "587:587" # ESMTP (explicit TLS => STARTTLS)
      - "993:993" # IMAP4 (implicit TLS)
      # - "4190:4190" # Managed sieve
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ./docker-data/certbot/certs/:/etc/letsencrypt
      - ./docker-data/dms/config/dovecot/fts-xapian-plugin.conf:/etc/dovecot/conf.d/10-plugin.conf:ro

    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```
