### ISSUE TITLE
question: DMS with Roundcube + Roundcube Password Plugin

### ISSUE THREAD

**Issue by ValentinRgt** [docker-mailserver/docker-mailserver#3405]
### Subject

I would like some feedback concerning a use case

### Description

Hello,

I have setup Docker Mailserver with Roundcube on my server until now everything works fine, however I would like to use the roundcube password plugin so that my collaborators can manage their password without my intervention except that I can't get it to communicate with the dovecot server...

Could you please help me with this configuration?

**Comment by polarathene** [comment]
> Could you please help me with this configuration?

I don't think this would work reliably for you.

We presently have two ways to manage passwords. Our file based `postfix-accounts.cf` that you use `setup email add ...` command to manage, and LDAP which you manage with other software and we just direct auth through that.

With LDAP, Dovecot will send password login through that, but with `postfix-accounts.cf` each time the container is started or the change detection service is triggered, we re-create the Dovecot accounts DB with our `postfix-accounts.cf`. So any modification directly to Dovecot by something else would lose it's changes at that point.

Your best bet would be use LDAP and provide some way to update passwords through that. Presently LDAP does opt-out of our change detection service. So any file support to reload services or config would require container restarts to apply.

There are others interested in a password/account API and OAUTH/OIDC support, both which might be other alternatives you could leverage but I'm not aware of anyone actively working on either right now.

**Comment by ValentinRgt** [comment]
Eventually, if you integrate Roundcube into the docker image to make this plugin functional wouldn't that be possible?

For example, a parameter in the .env like ROUNDCUBE_ENABLED=true|false ...etc behind?

**Comment by polarathene** [comment]
> if you integrate Roundcube into the docker image to make this plugin functional wouldn't that be possible?

Maybe? I don't know if we'd do that though. It'd be more likely you'd run Roundcube as a separate container and we have some example in docs on how to better integrate with DMS. That requires someone to contribute such however.

Users have requested ability to not require admin to manage passwords on behalf of others, and that's not always for Roundcube, an API would better meet the needs and could be integrated into DMS image. Then someone could probably make a Roundcube plugin that uses that API, or the alternative of using LDAP/OIDC (_which'd manage passwords elsewhere_).

**Comment by ValentinRgt** [comment]
I agree about the LDAP, but you said that the container had to be restarted after modification, so the problem isn't solved...

You said that in the doc there was a section talking about DMS and Roundcube? I'd like the page, but I can't find it...

**Comment by polarathene** [comment]
> had to be restarted after modification

Anything that our change detector supports reloading services for to apply config changes. Anything that is managed by LDAP isn't a concern there. If you use the `setup ...` command and it modifies relay config, or you update cert files, that won't be detected without the change detector.

> You're also talking about APIs

Not implemented. There was an attempt but it stalled. Users want it but there's been very little contribution towards making it possible.

> You said that in the doc there was a section talking about DMS and Roundcube?

No, misunderstanding again. I was suggesting that we would more likely document how to setup Roundcube as a separate container to use with DMS, instead of add Roundcube into DMS image.

We have no such docs. You can find some users sharing config in our issues with search, but this does not address the request you have for password plugin integration.

**Comment by ValentinRgt** [comment]
docker-compose.yaml
```yaml
version: '3'

name: mailserver-stack

services:
  mailserver:
    image: mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: DOMAIN_NAME.EXT
    env_file: /opt/docker/mailserver/mailserver/mailserver.env
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
      - "110:110"
      - "995:995"
      - "143:143"
      - "993:993"
      - "4190:4190"
    volumes:
      - /opt/docker/mailserver/mailserver/mail/data/:/var/mail/
      - /opt/docker/mailserver/mailserver/mail/state/:/var/mail-state/
      - /opt/docker/mailserver/mailserver/mail/logs/:/var/log/mail/
      - /opt/docker/mailserver/mailserver/config/:/tmp/docker-mailserver/
#     - /opt/docker/mailserver/mailserver/certs/:/certs
      - /opt/docker/mailserver/mailserver/certbot/certs/:/etc/letsencrypt/
      - /opt/docker/mailserver/mailserver/certbot/logs/:/var/log/letsencrypt/
#     - /opt/docker/mailserver/mailserver/backup/:/backup/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    networks:
      - mailserver
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

  roundcubeemail:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    restart: always
    env_file: /opt/docker/mailserver/roundcube/roundcube.env
    volumes:
      - /opt/docker/mailserver/roundcube/www/:/var/www/html
      - /opt/docker/mailserver/roundcube/config/:/var/roundcube/config
      - /opt/docker/mailserver/roundcube/db/:/var/roundcube/db
      - /opt/docker/mailserver/roundcube/temp/:/tmp/roundcube-temp
    ports:
      - "9000:80"
    depends_on:
      - mailserver
    networks:
      - mailserver

networks:
  mailserver:
    name: mailserver_network
    driver: bridge
```

roundcube.env
```yaml
# PostgreSQL => pgsql
# MySQL => mysql
# SQLite => sqlite
ROUNDCUBEMAIL_DB_TYPE=sqlite

# Use this parameter if you use PostgreSQL or MySQL
#ROUNDCUBEMAIL_DB_HOST=localhost

# Use this parameter if you use PostgreSQL or MySQL
# PostgreSQL => 5432
# MySQL => 3306
#ROUNDCUBEMAIL_DB_PORT=3306

# Use this parameter if you use PostgreSQL or MySQL
#ROUNDCUBEMAIL_DB_NAME=roundcube

# Use this parameter if you use PostgreSQL or MySQL
#ROUNDCUBEMAIL_DB_USER=roundcube

# Use this parameter if you use PostgreSQL or MySQL
#ROUNDCUBEMAIL_DB_PASSWORD=roundcube

# Roundcube Skin
ROUNDCUBEMAIL_SKIN=elastic

# Doc : https://github.com/roundcube/google-spell-pspell
#ROUNDCUBEMAIL_SPELLCHECK_URI

# Roundcube languages
ROUNDCUBEMAIL_ASPELL_DICTS=fr,en

# Roundcube max upload file size
ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=5M

# Roundcube plugins
ROUNDCUBEMAIL_PLUGINS=archive,zipdownload,enigma,password,emoticons,identicon

ROUNDCUBEMAIL_DEFAULT_HOST=tls://mail.DOMAIN_NAME.EXT
ROUNDCUBEMAIL_DEFAULT_PORT=143

ROUNDCUBEMAIL_SMTP_SERVER=tls://mail.DOMAIN_NAME.EXT
ROUNDCUBEMAIL_SMTP_PORT=587
```
