### ISSUE TITLE
other: Help needed with configuring DMS behind Traefik + Enable POP3S 

### ISSUE THREAD

**Issue by marverix** [docker-mailserver/docker-mailserver#3413]
### Subject

I would like to configure a not documented mail server use case

### Description

Hello,

first of all, let me express my gratitude for all the work put in by the authors and the 
contributors to the project. Hats off!

I'm using Traefik on my server for some time already, so I'm not new to this software, but also I'm not an expert. I'm new to DMS.

I was following mainly https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/mailserver-behind-proxy/#configuration-of-the-used-proxy-software + looked at the issues reported here, on GH. I must say, that DMS is lacking in the area of documentation and it's not easy for newcomers to configure it. For example:
* Traefik will throw errors when using `HostSNI` without instructing Traefik what to do with TLS (eg. enable the passthrough)
* Documentation tells to use protocol version 1 for SMTP, which will cause SMTP to not work. Version protocol must be 2.
* Documentation (about integration with Traefik) is missing parts of code responsible for letsencrypt JSON file (yes, this is in the other documentation page, but I don't agree that this is proper way - in 2023, most people will use letsencrypt to have encrypted connections).
* Missing information how to configure POP3, or at least any link for futher reading

Now, my configuration:

#### docker-compose-traefik.yaml

```yaml
version: "3.8"

networks:
  internal_network:
    name: vps_internal_network
    external: true

services:
  traefik:
    image: traefik:2.9.10
    container_name: traefik
    restart: unless-stopped
    volumes:
    - ./traefik:/etc/traefik
    - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
    - internal_network
    ports:
    - "80:80"                     # HTTP
    - "443:443"                   # HTTPS
    - "465:465"                   # SMTP (TLS)
    - "993:993"                   # IMAP (TLS)
    - "995:995"                   # POP3 (TLS)
    - "127.0.0.1:8080:8080"       # Dashboard
```

#### docker-compose-dms.yaml

```yaml
version: "3.8"

networks:
  internal_network:
    name: vps_internal_network
    external: true

services:
  mail_example_org:
    image: ghcr.io/docker-mailserver/docker-mailserver:12.1.0
    container_name: mail_example_org
    hostname: example.org
    restart: unless-stopped
    networks:
    - internal_network
    environment:
    - LOG_LEVEL=debug
    - SSL_TYPE=letsencrypt
    - ENABLE_OPENDKIM=1
    - ENABLE_OPENDMARC=1
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_SPAMASSASSIN_KAM=1
    - ENABLE_POP3=1
    - ENABLE_CLAMAV=0
    - ENABLE_FAIL2BAN=1
    - FAIL2BAN_BLOCKTYPE=drop
    - ENABLE_POSTGREY=0
    - ENABLE_UPDATE_CHECK=0
    - SPOOF_PROTECTION=1
    - POSTMASTER_ADDRESS=postmaster@example.org
    volumes:
    - ./mail/example_org/data/:/var/mail/
    - ./mail/example_org/state/:/var/mail-state/
    - ./mail/example_org/logs/:/var/log/mail/
    - ./mail/example_org/config/:/tmp/docker-mailserver/
    - ./traefik/certs/letsencrypt.json:/etc/letsencrypt/acme.json:ro
    - /etc/localtime:/etc/localtime:ro
    cap_add:
    - NET_ADMIN # For Fail2Ban to work
    labels:
    - traefik.enable=true

    - traefik.tcp.routers.smtp_mail_example_org.rule=HostSNI(`example.org`)
    - traefik.tcp.routers.smtp_mail_example_org.tls.passthrough=true
    - traefik.tcp.routers.smtp_mail_example_org.entrypoints=smtp
    - traefik.tcp.routers.smtp_mail_example_org.service=smtp_mail_example_org
    - traefik.tcp.services.smtp_mail_example_org.loadbalancer.server.port=465

    - traefik.tcp.routers.imap_mail_example_org.rule=HostSNI(`example.org`)
    - traefik.tcp.routers.imap_mail_example_org.tls.passthrough=true
    - traefik.tcp.routers.imap_mail_example_org.entrypoints=imap
    - traefik.tcp.routers.imap_mail_example_org.service=imap_mail_example_org
    - traefik.tcp.services.imap_mail_example_org.loadbalancer.server.port=10993

    - traefik.tcp.routers.pop3_mail_example_org.rule=HostSNI(`example.org`)
    - traefik.tcp.routers.pop3_mail_example_org.tls.passthrough=true
    - traefik.tcp.routers.pop3_mail_example_org.entrypoints=pop3
    - traefik.tcp.routers.pop3_mail_example_org.service=pop3_mail_example_org
    - traefik.tcp.services.pop3_mail_example_org.loadbalancer.server.port=10995
```

#### ./mail/example_org/config/dovecot.cf

```
haproxy_trusted_networks = 172.23.0.0/24   # <-- this is docker internal_network ip subnet
haproxy_timeout = 3 secs

service imap-login {
  inet_listener imap_haproxy {
    haproxy = yes
    ssl = yes
    port = 10993
  }
}

service pop3-login {
  inet_listener pop3_haproxy {
    haproxy = yes
    ssl = yes
    port = 10995
  }
}
```

#### ./mail/example_org/config/postfix-main.cf

```
postscreen_upstream_proxy_protocol = haproxy
```

#### ./mail/example_org/config/postfix-master.cf

```
submission/inet/smtpd_upstream_proxy_protocol=haproxy
submissions/inet/smtpd_upstream_proxy_protocol=haproxy
```

NOTE: Above config files are taken from DMS documentation (except POP3 config part).

### What is working

* Connecting to the SMTP with Thunderbird
* Sending emails
* Connecting to the IMAP with Thunderbird
* Connecting to the POP3 with Thunderbird

### What is not working

* Retrieving emails via POP3 - Thunderbird says "No new emails"
* When Thunderbird was connected via IMAP+SMTP, when I sent an email, Thunderbird reported that couldn't put anything into the "Sent" folder
* When trying to add an account to GMail (so it retrieves the email via POP3), Google reported a Timeout error. Which is super strange for me, because second ago (and retested later) Thunderbird had no issue whatsoever with connecting

I really appreciate for any help. Also I'm open to contribute to the project with updating the documentation about Traefik, so it's up to date.

Br,
Marek
