### ISSUE TITLE
bug report: rspamd gives a 'Bad Request' on 'Scan message' in the WebUI

### ISSUE THREAD

**Issue by Dubbeldrank** [docker-mailserver/docker-mailserver#3427]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

When i try to 'Scan Message' the source of a spam mail in the Scan/Learn section of the WebUI i get a Bad Request error. Everything else on the WebUI works fine, even learning that same message in the same field as  SPAM or HAM works fine. It's just that single feature. I couldn't find anything in the logs.

### 👟 Reproduction Steps

Paste the source of an email in the Scan/Learn section of the WebUI and scan it.
![Screenshot 2023-07-14 160617](https://github.com/docker-mailserver/docker-mailserver/assets/23383389/9b3bf52f-40c9-4bae-a187-7a72ba91741e)

### 🐋 DMS Version

12.1.0

### 💻 Operating System and Architecture

Debian GNU/Linux 12 (bookworm)

### ⚙️ Container configuration files

```yml
version: '3.8'

services:
  mail:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mail
    hostname: mail
    domainname: something.something
    network_mode: bridge
    ports:
      - "25:25"
      - "587:587"
      - "993:993"
      - "4190:4190"
      - "11334:11334"
    volumes:
      - /opt/docker/mail/data/mail-data:/var/mail/
      - /opt/docker/mail/data/mail-state/:/var/mail-state/
      - /opt/docker/mail/data/mail-logs/:/var/log/mail/
      - /opt/docker/mail/config/:/tmp/docker-mailserver/
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    environment:
      - OVERRIDE_HOSTNAME=
      - DMS_DEBUG=0
      - LOG_LEVEL=info
      - SUPERVISOR_LOGLEVEL=
      - ONE_DIR=1
      - ACCOUNT_PROVISIONER=
      - POSTMASTER_ADDRESS=postmaster@something.something
      - ENABLE_UPDATE_CHECK=1
      - UPDATE_CHECK_INTERVAL=1d
      - PERMIT_DOCKER=none
      - TZ=Europe/Amsterdam
      - NETWORK_INTERFACE=
      - TLS_LEVEL=
      - SPOOF_PROTECTION=1
      - ENABLE_SRS=0
      - ENABLE_OPENDKIM=0
      - ENABLE_OPENDMARC=0
      - ENABLE_POLICYD_SPF=0
      - ENABLE_POP3=
      - ENABLE_CLAMAV=1
      - ENABLE_RSPAMD=1
      - ENABLE_RSPAMD_REDIS=
      - RSPAMD_LEARN=1
      - RSPAMD_GREYLISTING=0
      - RSPAMD_HFILTER=1
      - RSPAMD_HFILTER_HOSTNAME_UNKNOWN_SCORE=6
      - ENABLE_AMAVIS=0
      - AMAVIS_LOGLEVEL=0
      - ENABLE_DNSBL=1
      - ENABLE_FAIL2BAN=1
      - FAIL2BAN_BLOCKTYPE=drop
      - ENABLE_MANAGESIEVE=1
      - POSTSCREEN_ACTION=enforce
      - SMTP_ONLY=
      - SSL_TYPE=letsencrypt
      - SSL_CERT_PATH=
      - SSL_KEY_PATH=
      - SSL_ALT_CERT_PATH=
      - SSL_ALT_KEY_PATH=
      - VIRUSMAILS_DELETE_DELAY=
      - POSTFIX_DAGENT=
      - POSTFIX_MAILBOX_SIZE_LIMIT=
      - ENABLE_QUOTAS=1
      - POSTFIX_MESSAGE_SIZE_LIMIT=102400000
      - CLAMAV_MESSAGE_SIZE_LIMIT=
      - PFLOGSUMM_TRIGGER=
      - PFLOGSUMM_RECIPIENT=
      - PFLOGSUMM_SENDER=
      - LOGWATCH_INTERVAL=
      - LOGWATCH_RECIPIENT=
      - LOGWATCH_SENDER=
      - REPORT_RECIPIENT=
      - REPORT_SENDER=
      - LOGROTATE_INTERVAL=weekly
      - POSTFIX_REJECT_UNKNOWN_CLIENT_HOSTNAME=0
      - POSTFIX_INET_PROTOCOLS=all
      - DOVECOT_INET_PROTOCOLS=all
      - ENABLE_SPAMASSASSIN=0
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_SPAMASSASSIN_KAM=0
      - MOVE_SPAM_TO_JUNK=1
      - SA_TAG=2.0
      - SA_TAG2=6.31
      - SA_KILL=10.0
      - SA_SPAM_SUBJECT=***SPAM*****
      - ENABLE_FETCHMAIL=0
      - FETCHMAIL_POLL=300
      - ENABLE_LDAP=
      - LDAP_START_TLS=
      - LDAP_SERVER_HOST=
      - LDAP_SEARCH_BASE=
      - LDAP_BIND_DN=
      - LDAP_BIND_PW=
      - LDAP_QUERY_FILTER_USER=
      - LDAP_QUERY_FILTER_GROUP=
      - LDAP_QUERY_FILTER_ALIAS=
      - LDAP_QUERY_FILTER_DOMAIN=
      - DOVECOT_TLS=
      - DOVECOT_USER_FILTER=
      - DOVECOT_PASS_FILTER=
      - DOVECOT_MAILBOX_FORMAT=maildir
      - DOVECOT_AUTH_BIND=
      - ENABLE_POSTGREY=0
      - POSTGREY_DELAY=300
      - POSTGREY_MAX_AGE=35
      - POSTGREY_TEXT="Delayed by Postgrey"
      - POSTGREY_AUTO_WHITELIST_CLIENTS=5
      - ENABLE_SASLAUTHD=0
      - SASLAUTHD_MECHANISMS=
      - SASLAUTHD_MECH_OPTIONS=
      - SASLAUTHD_LDAP_SERVER=
      - SASLAUTHD_LDAP_BIND_DN=
      - SASLAUTHD_LDAP_PASSWORD=
      - SASLAUTHD_LDAP_SEARCH_BASE=
      - SASLAUTHD_LDAP_FILTER=
      - SASLAUTHD_LDAP_START_TLS=
      - SASLAUTHD_LDAP_TLS_CHECK_PEER=
      - SASLAUTHD_LDAP_TLS_CACERT_FILE=
      - SASLAUTHD_LDAP_TLS_CACERT_DIR=
      - SASLAUTHD_LDAP_PASSWORD_ATTR=
      - SASLAUTHD_LDAP_AUTH_METHOD=
      - SASLAUTHD_LDAP_MECH=
      - SRS_SENDER_CLASSES=envelope_sender
      - SRS_EXCLUDE_DOMAINS=
      - SRS_SECRET=
      - DEFAULT_RELAY_HOST=
      - RELAY_HOST=
      - RELAY_PORT=25
      - RELAY_USER=
      - RELAY_PASSWORD=
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
```

### 📜 Relevant log output

```Text
Couldn't find any rspamd WebUI logs indicating an error.
```
