### ISSUE TITLE
bug report: Postfix loses certificate after start

### ISSUE THREAD

**Issue by di-rect** [docker-mailserver/docker-mailserver#3441]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

When I start my container it seems that after some seconds I cannot lookup my certificate of Postfix anymore using:

```
#openssl s_client -showcerts -connect mydomain.tld:465 -servername mydomain.tld
CONNECTED(00000003)
80AB4A148C7F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:../ssl/record/rec_layer_s3.c:308:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 320 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
```

I also get the following error after (trying to) send an email over port 465:

`Jul 25 10:07:36 mail postfix/smtps/smtpd[843]: warning: TLS library problem: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331`

IMAP (Dovecot) stays using the right certificate

### 👟 Reproduction Steps

- Start container
- Wait for a while or try to send an e-mail over port SSL (465)
- Check using `openssl s_client -showcerts -connect mydomain.tld:465 -servername mydomain.tld`

### 🐋 DMS Version

v12.1.0

### 💻 Operating System and Architecture

Ubuntu 22.04

### ⚙️ Container configuration files

```yml
Relevant is:

   hostname: mail
   domainname: mydomain.tld

   environment:
      - ONE_DIR=0
      - OVERRIDE_HOSTNAME=mydomain.tld
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - SSL_TYPE=letsencrypt
      - SSL_DOMAIN=mydomain.tld
```

### 📜 Relevant log output

```Text
Jul 25 10:07:36 mail postfix/smtps/smtpd[843]: warning: TLS library problem: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331:
```
