### ISSUE TITLE
other: DMS not sending emails externally, keeps using port 25

### ISSUE THREAD

**Issue by schumi2004** [docker-mailserver/docker-mailserver#3451]
### Subject

I have questions about TLS/SSL/STARTTLS/OpenSSL

### Description

Hi all,

This weekend i setup DMS on my private ISP connection.
Got certificates up and running, DKIM, SPF and DMARC is configured and all checks are successful.
Checks like "openssl s_client -starttls smtp -connect gmail-smtp-in.l.google.com:587 -crlf -ign_eof" are working as expected.
Receiving mails is also working perfect except all outgoing mail.

I'm using my own certifcates generated by SWAG (NGINX) from linuxserver.io

```
version: "3"
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.domain.tld
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    environment:
      #- LOG_LEVEL=debug
      #- SUPERVISOR_LOGLEVEL=debug
      - POSTMASTER_ADDRESS=postmaster@domain.tld
      - TZ=Europe/Amsterdam
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/tmp/docker-mailserver/swag-ssl/letsencrypt/live/domain.tld/fullchain.pem
      - SSL_KEY_PATH=/tmp/docker-mailserver/swag-ssl/letsencrypt/live/domain.tld/privkey.pem
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=0
    # Add other environment variables as needed here
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - /mnt/docker_data_host/mailserver-data/mail-data/:/var/mail/
      - /mnt/docker_data_host/mailserver-data/mail-state/:/var/mail-state/
      - /mnt/docker_data_host/mailserver-data/mail-logs/:/var/log/mail/
      - /mnt/docker_data_host/mailserver-data/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker_data_host/swag-data/config/etc/:/tmp/docker-mailserver/swag-ssl/:rw
    restart: unless-stopped
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    networks:
      ipvlan_custom:
        ipv4_address: 10.0.0.165

networks:
  ipvlan_custom:
    name: ipvlan_custom
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
```

When sending mails, although having the client configured to use anything other than port 25, it's always using port 25 for outgoing connections. I understand the purpose of port 25 but i have read in other issues that DMS would automaticly upgrade connections? All ports configured in compose file are open and accesable and the mail server seems to be correclty configured from the outside world when using tools like mxtoolbox

Currently i'm getting such events in mail.log:
Jul 30 22:31:48 mail postfix/smtp[15103]: connect to gmail-smtp-in.l.google.com[2a00:1450:4025:402::1a]:25: Cannot assign requested address
Jul 30 22:32:18 mail postfix/smtp[15103]: connect to gmail-smtp-in.l.google.com[142.250.27.27]:25: Connection timed out
Jul 30 22:32:18 mail postfix/smtp[15103]: connect to alt1.gmail-smtp-in.l.google.com[2a00:1450:4025:c03::1a]:25: Cannot assign requested address
Jul 30 22:32:48 mail postfix/smtp[15103]: connect to alt1.gmail-smtp-in.l.google.com[142.251.9.26]:25: Connection timed out
Jul 30 22:32:48 mail postfix/smtp[15103]: connect to alt2.gmail-smtp-in.l.google.com[2a00:1450:4010:c1c::1b]:25: Cannot assign requested address

AND

Jul 30 22:37:18 mail postfix/smtp[15633]: connect to mx1.hc756-17.eu.iphmx.com[23.90.116.143]:25: Connection timed out
Jul 30 22:37:48 mail postfix/smtp[15633]: connect to mx2.hc756-17.eu.iphmx.com[23.90.111.146]:25: Connection timed out
Jul 30 22:38:18 mail postfix/smtp[15633]: connect to mx1.hc674-87.eu.iphmx.com[23.90.116.133]:25: Connection timed out
Jul 30 22:38:48 mail postfix/smtp[15633]: connect to mx1.hc756-17.eu.iphmx.com[23.90.116.141]:25: Connection timed out
Jul 30 22:39:18 mail postfix/smtp[15633]: connect to mx2.hc756-17.eu.iphmx.com[23.90.116.143]:25: Connection timed out

I'm not using IPv6 so those can be ignored but IPv4 works perfect.

Any thoughts, did i miss anything?
