### ISSUE TITLE
Unable to fetch email nor send, but email is received in directory

### ISSUE THREAD

**Issue by elcolie** [docker-mailserver/docker-mailserver#3458]
### Subject

I would like some feedback concerning a use case

### Description

```
version: '2'

services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.elcolie.com
    environment:
      - SSL_TYPE=letsencrypt
    volumes:
      - ./docker-data/certbot/certs/:/etc/letsencrypt
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_RSPAMD=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    restart: always
```

I am following the example from the official doc. Currently I can received email. They are stored in `docker-data`
```bash
(tomav) root@ip-172-31-23-120:/mnt/xvdf1/tomav-mailserver/docker-data/dms/mail-data/elcolie.com/sarit/new# ls -alh
total 28K
drwxr-xr-x 2 5000 5000 4.0K Aug  6 02:02 .
drwxr-xr-x 6 5000 5000 4.0K Aug  6 02:03 ..
-rw-r--r-- 1 5000 5000 3.5K Aug  5 16:50 1691254203.M613339P1280.mail.elcolie.com,S=3514,W=3576
-rw-r--r-- 1 5000 5000 4.6K Aug  5 17:11 1691255484.M350226P804.mail.elcolie.com,S=4661,W=4753
-rw-r--r-- 1 5000 5000 4.6K Aug  6 02:02 1691287356.M237362P783.mail.elcolie.com,S=4655,W=4749
```

**Problems:**
1. I have tried `pop3/imap` from thunderbird to read my email. It does not work
2. I am unable to use `smtp` to send out email from thunderbird.

**Question:**
Where I can find thunderbird client configure of the `example`?
