### ISSUE TITLE
bug report: 

### ISSUE THREAD

**Issue by sgpinkus** [docker-mailserver/docker-mailserver#3467]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

opendkim is looking in the wrong place for keys. Container logs:

> Aug  8 08:22:44 mail opendkim[393]: can't load key from /etc/opendkim/keys/example.com/mail.private: No such file or directory

But `setup` is generating keys under /tmp/docker-mailserver/...`:

> $ docker exec -ti mail setup config dkim keysize 2048 selector y
[   INF   ]  Creating DKIM private key '/tmp/docker-mailserver/opendkim/keys/example.com/y.private'

### 👟 Reproduction Steps

```
docker compose up -d
docker exec -ti mail setup config dkim keysize 2048 selector y
# now try send an email.
```
### 🐋 DMS Version

v12.1.0

### 💻 Operating System and Architecture

Debian GNU/Linux 11 (bullseye) x86_64 GNU/Linux

### ⚙️ Container configuration files

```yml
version: "3"
services:
  mail:
    image: "ghcr.io/docker-mailserver/docker-mailserver:latest"
    container_name: mail
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.example.com
    env_file: mail.env
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - mail_data:/var/mail/
      - mail_state:/var/mail-state/
      - mail_logs:/var/log/mail/
      - mail_config:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt/live/mail.example.com:/etc/letsencrypt/live/mail.example.com:ro
      - /etc/letsencrypt/archive/mail.example.com:/etc/letsencrypt/archive/mail.example.com:ro
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    cap_add:
      - NET_ADMIN
volumes:
  mail_data: ~
  mail_state: ~
  mail_logs: ~
  mail_config: ~
```

### 📜 Relevant log output

```Text
As above:
```
