### ISSUE TITLE
other: Error while setting up TLS with certbot-dns-cloudflare

### ISSUE THREAD

**Issue by jpsanchezl10** [docker-mailserver/docker-mailserver#3492]
### Subject

I would like to contribute to the project

### Description

I set up my mail server. with with certbot-cloudflare and I still cant connect with connection security :TLS:
this is my docker-compose.yaml:
```
version: '3.8'

services:
  mailserver:
    image: mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: webhosting
    domainname: mail.mydomain.mx
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "465:465"
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_POSTGREY=1
      - ENABLE_FAIL2BAN=1
      - ONE_DIR=1
      - TZ=America/New_York
      - ENABLE_SASLAUTHD=0
      - RELAY_HOST=smtp.sendgrid.net
      - RELAY_PORT=587
      - RELAY_USER=apikey
      - RELAY_PASSWORD=SG.*******
      - SSL_TYPE=letsencrypt

    volumes:
      - ~/docker/mailserver/data/:/var/mail/
      - ~/docker/mailserver/state/:/var/mail-state/
      - ~/docker/mailserver/logs/:/var/log/mail/
      - ~/docker/mailserver/config/:/tmp/docker-mailserver/
      - ./docker-data/certbot/certs/:/etc/letsencrypt/:ro
    restart: always


  certbot-cloudflare:
    image: certbot/dns-cloudflare:latest
    command: certonly --dns-cloudflare --dns-cloudflare-credentials /run/secrets/cloudflare-api-token -d mail.mydomain.mx
    volumes:
      - ./docker-data/certbot/certs/:/etc/letsencrypt/
      - ./docker-data/certbot/logs/:/var/log/letsencrypt/
    secrets:
      - cloudflare-api-token

  certbot-cloudflare-renew:
    image: certbot/dns-cloudflare:latest
    command: renew --dns-cloudflare --dns-cloudflare-credentials /run/secrets/cloudflare-api-token
    volumes:
      - ./docker-data/certbot/certs/:/etc/letsencrtypt/
      - ./docker-data/certbot/logs/:/var/log/letsencrypt/
    secrets:
      - cloudflare-api-token

secrets:
  cloudflare-api-token:
    file: ./docker-data/certbot/secrets/cloudflare.ini


```

To connect to my server, I need to comment this line ''- SSL_TYPE=letsencrypt'' so I cannot use TLS.

logs
```Aug 20 16:29:47 webhosting dovecot: imap-login: Login: user=<myemail@mydomain.mx>, method=PLAIN, rip=192.168.1.64, lip=172.18.0.2, mpid=1054, TLS, session=<K/5wn2ADGtPAqAFA>

Aug 20 16:29:49 webhosting postfix/submission/smtpd[879]: connect from unknown[80.94.95.184]

Aug 20 16:29:49 webhosting postfix/submission/smtpd[879]: disconnect from unknown[80.94.95.184] ehlo=1 auth=0/1 rset=0/1 quit=1 commands=2/4

Aug 20 16:30:04 webhosting postfix/submission/smtpd[862]: connect from unknown[80.94.95.184]

Aug 20 16:30:08 webhosting postfix/submission/smtpd[862]: disconnect from unknown[80.94.95.184] ehlo=1 auth=0/1 rset=0/1 quit=1 commands=2/4

Aug 20 16:30:12 webhosting postfix/submission/smtpd[879]: connect from unknown[192.168.1.64]

Aug 20 16:30:12 webhosting postfix/submission/smtpd[879]: SSL_accept error from unknown[192.168.1.64]: -1

Aug 20 16:30:12 webhosting postfix/submission/smtpd[879]: warning: TLS library problem: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../ssl/record/rec_layer_s3.c:1543:SSL alert number 42:

Aug 20 16:30:12 webhosting postfix/submission/smtpd[879]: lost connection after STARTTLS from unknown[192.168.1.64]

Aug 20 16:30:12 webhosting postfix/submission/smtpd[879]: disconnect from unknown[192.168.1.64] ehlo=1 starttls=0/1 c```
