### ISSUE TITLE
dovecot overrided files permission denied at server start 

### ISSUE THREAD

**Issue by leccyril** [docker-mailserver/docker-mailserver#3500]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

i start a simple docker postfix with dovecot files overrided but in the server, permission denied

![image](https://github.com/docker-mailserver/docker-mailserver/assets/3234598/87941231-0c89-4a7b-8877-4a7456b0a014)

and the status of overrided files
![image](https://github.com/docker-mailserver/docker-mailserver/assets/3234598/730c17e1-29ea-4bf4-b1d3-6ed12b1703cc)

### 👟 Reproduction Steps

execute sudo docker-compose up and check the logs

with this compose file

```
version: '3'
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.xx.ae
    domainname: xx.ae
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - /usr/local/docker/mailserver/mail-data/:/var/mail/
      - /usr/local/docker/mailserver/mail-state/:/var/mail-state/
      - /usr/local/docker/mailserver/mail-logs/:/var/log/mail/
      - /usr/local/docker/mailserver/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ./docker-data/dms/config/dovecot/dovecot.conf:/etc/dovecot/dovecot.conf
      - ./docker-data/dms/config/dovecot/dovecot-dict-sql.conf.ext:/etc/dovecot/dovecot-dict-sql.conf.ext
      - ./docker-data/dms/config/dovecot/dovecot-sql.conf.ext:/etc/dovecot/dovecot-sql.conf.ext
      
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ENABLE_SASLAUTHD=0
      - ONE_DIR=1
      - DMS_DEBUG=0
      - PERMIT_DOCKER=host
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
```

I just want to reproduce locally a server running to test shared mail not working in production

### 🐋 DMS Version

12.1.0

### 💻 Operating System and Architecture

linux fedora 37

### ⚙️ Container configuration files

```yml
version: '3'
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.equitativa.ae
    domainname: equitativa.ae
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - /usr/local/docker/mailserver/mail-data/:/var/mail/
      - /usr/local/docker/mailserver/mail-state/:/var/mail-state/
      - /usr/local/docker/mailserver/mail-logs/:/var/log/mail/
      - /usr/local/docker/mailserver/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ./docker-data/dms/config/dovecot/dovecot.conf:/etc/dovecot/dovecot.conf
      - ./docker-data/dms/config/dovecot/dovecot-dict-sql.conf.ext:/etc/dovecot/dovecot-dict-sql.conf.ext
      - ./docker-data/dms/config/dovecot/dovecot-sql.conf.ext:/etc/dovecot/dovecot-sql.conf.ext
      
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ENABLE_SASLAUTHD=0
      - ONE_DIR=1
      - DMS_DEBUG=0
      - PERMIT_DOCKER=host
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
```

**Comment by polarathene** [comment]
> i start a simple docker postfix with dovecot files overrided but in the server, permission denied

You are configuring an unsupported configuration (SQL):

```
- ./docker-data/dms/config/dovecot/dovecot.conf:/etc/dovecot/dovecot.conf
- ./docker-data/dms/config/dovecot/dovecot-dict-sql.conf.ext:/etc/dovecot/dovecot-dict-sql.conf.ext
- ./docker-data/dms/config/dovecot/dovecot-sql.conf.ext:/etc/dovecot/dovecot-sql.conf.ext
```

Notice the error you're getitng about owenship permissions, and your other image that shows `?` for user and group ID. This means the container does not recognize whatever UID and GID your host has for these files. That could be preventing Dovecot from reading the config?

> I just want to reproduce locally a server running to test shared mail not working in production

`/var/mail` is meant to be set to UID and GID of `5000` which our Dovecot config is also configured for, and the startup scripts will run `chown -R` at this location to ensure all content has the correct ownership.

Have you provided an external source of `/var/mail` from somewhere else?

---

I can only assume that you know what you're doing with mail server configuration outside of DMS if you insist on unsupported configuration. We can't really assist much with that.

You'll also notice the script is repeating a message to make an account. the default `ACCOUNT_PROVISIONER` mode is `FILE` which expects Dovecot account to be created with our `setup email add ...` command which creates a `postfix-accounts.cf` file in `/tmp/docker-mailserver`. After that it'll start the mail server fully.

You might have a better time with a less opinionated image? DMS is more focused on simplifying setup of a mail server for users that don't know what they're doing, and aren't needing to configure internal services directly, but instead through the ways we document such as config files in `/tmp/docker-mailserver` and environment variables.

---

Additionally, I'm not sure why you have this, it's a configuration error:

```yaml
hostname: mail.equitativa.ae
domainname: equitativa.ae
```

Where did you get the advice for this? Or did our docs explain something poorly about how to set this part up?

It should just be the `hostname`:

https://github.com/docker-mailserver/docker-mailserver/blob/39ae101266af7511d85fbb5e9e4b19324390f5ce/compose.yaml#L5-L6

So for you it would be `hostname: mail.equitativa.ae`, no `domainname`.

**Comment by polarathene** [comment]
> I need to reproduce on case locally because shared email not working...

There is a PR trying to implement shared mailbox support for DMS: https://github.com/docker-mailserver/docker-mailserver/pull/3239

> what should i do to allow permission ? any specifiq command or try to change content but inside the container how to do it nano do not exists?

This tells me you have not paid attention to the requirement you confirmed at the start of the bug report:

![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/8b19489d-da8e-42c8-b93a-2e0d2ba1a8e0)

We have a link straight to [our debug docs page](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) right there with this information..

![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/ca723b4d-b049-4e20-87af-d558704d2034)

So...

```bash
# Shell into DMS container:
docker exec -it container_name_here bash

# Install nano
apt-get update && apt-get install nano
```

If you need to adjust permisions you have `chown` and `chmod` commands, you can look up search engine result how to use those if you don't know them.

---

> for dovecot basically it is just a file copy so think about another file name

`dovecot.conf` is one of the Dovecot configs, it's the main one. You also added config for SQL support, but we cannot help you there as this is not what DMS supports. You're not meant to change internal configs like that with our image, we assume things are configured a certain way and only we control internal changes. When you make your own direct changes this is unsupported.

In the docs sidebar menu on the left, you can see we support overriding these configs to some extent:

![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/8591cc09-00f3-4237-b072-5e0c0a667bbe)

There is a [page for Dovecot](https://docker-mailserver.github.io/docker-mailserver/latest/config/advanced/override-defaults/dovecot/), where you can provide an extra config file, or it does say you can try direct override, but advises you to copy our internal config first, and apply your changes to that one. This way it will have better compatibility if most other settings are what we expect them to be, but some changes may not work well.

---

One other option you have is to [run the container without our startup scripts default command](https://github.com/docker-mailserver/docker-mailserver/blob/af09db6648b2bbb13b7364f39b9cf76d482cdfb2/Dockerfile#L306), `docker run --rm -it ghcr.io/docker-mailserver/docker-mailserver bash`

Now you are in the container like `docker exec`, but nothing of ours should be running. You can configure Dovecot and start it manually without anything else. This might let you better follow a random tutorial online, but our config is not default.

> the configuration error i just took a tuto with both conf

If you want default Dovecot config, perhaps you should [just use a base image like we do](https://github.com/docker-mailserver/docker-mailserver/blob/af09db6648b2bbb13b7364f39b9cf76d482cdfb2/Dockerfile#L10) `docker run --rm -it docker.io/debian:11-slim bash`, and install Dovecot packages as the guide should advise you?

I don't think the guide expects you to modify an existing Dovecot setup, so you may run into differences that cause you problems to troubleshoot.

---

> I just want to test locally so what can i put instead?
> Simple local test

I don't know what simple local test means to you. DMS does not have shared mailbox feature yet.

You can do local offline test, but some features to be tested properly need DNS setup, so you would need to setup a local resolver like CoreDNS for the mail DNS records. You also probably would want to supply some certificates. Your "Simple local test" may not need this for the functionality you want to test though.

We already provide simple getting started `compose.yaml` config here: https://github.com/docker-mailserver/docker-mailserver/blob/af09db6648b2bbb13b7364f39b9cf76d482cdfb2/compose.yaml

Use our docs to make changes for anything else you need that we support.

**Comment by leccyril** [comment]
Hello, 

thank you for all informations, ok fo the shared mailbox i managed to make it work, 

now i just want start postfix and dovecot http server server so i review simply the compose.yaml

what i dont understand is why in documentation it does not explain how to manage permissions simply to copy it i tried some configuration and i still have those logs

```
[   INF   ]  Welcome to docker-mailserver 12.1.0
[   INF   ]  Checking configuration
[   INF   ]  Configuring mail server
chown: changing ownership of '/var/log/mail': Permission denied
sed: can't read /etc/dovecot/conf.d/10-master.conf: Permission denied
sed: can't read /etc/dovecot/conf.d/10-master.conf: Permission denied
sed: can't read /etc/dovecot/conf.d/10-master.conf: Permission denied
/usr/local/bin/setup.d/dovecot.sh: line 141: /tmp/docker-mailserver/dovecot-quotas.cf: Permission denied
[ WARNING ]  You need at least one mail account to start Dovecot (120s left for account creation before shutdown
```

So ok just with small peace of code i can just make an exec in a started container and modify the file, but why i have permission denied on /var/log/mail ? 

do i have to create a dovecot user on my local laptop ?

**Comment by polarathene** [comment]
> why i have permission denied on /var/log/mail ?

Presently during the container startup for DMS, or when a `check-for-changes.sh` event is triggered, there is a function call to `chown -R` on `/var/mail` that will ensure ownership is `5000:5000`.

This will be applied as the containers `root` user, so would carry through to your volume mount on the Docker host.

---

> ```
> chown: changing ownership of '/var/log/mail': Permission denied
> sed: can't read /etc/dovecot/conf.d/10-master.conf: Permission denied
> sed: can't read /etc/dovecot/conf.d/10-master.conf: Permission denied
> sed: can't read /etc/dovecot/conf.d/10-master.conf: Permission denied
> /usr/local/bin/setup.d/dovecot.sh: line 141: /tmp/docker-mailserver/dovecot-quotas.cf: Permission denied
> ```

Since these are happening in the logs during startup, something is preventing DMS from performing that `chown` (_did  you mount read-only, or is this running from Rootless mode or perhaps on a macOS/Windows host?_).

---

Then something else you've done seems to be preventing reading `/etc/dovecot/conf.d/10-master.conf`, which I assume you mounted directly as per the docs guidance (_and these permissions, or read-only mount? prevent modification from the containers root user_):

<img width="435" alt="image" src="https://github.com/docker-mailserver/docker-mailserver/assets/5098581/ca86ca57-0b28-400c-8639-9b70617d0736">

---

Finally, for v12.1 we can lookup the mentinoed script and line failure:

https://github.com/docker-mailserver/docker-mailserver/blob/652bbd831f6d25bf79b619094610011891ecddb7/target/scripts/startup/setup.d/dovecot.sh#L138-L142

The docker config volume at `/tmp/docker-mailserver` is detected, and the Dovecot quotas feature is enabled (default), but whomever implemented the feature decided it should create an empty config file at startup when one doesn't exist. That fails which suggests eithe read-only or something similar preventing Docker to write to the location on the host.

**Comment by polarathene** [comment]
Can you share what modifications you're trying to apply through the Dovecot override?

As you can see from the errors above, DMS is trying to modify that file during startup as it expects it has ownership over it. It may be better for you to use `user-patches.sh` and `cp` from `/tmp/docker-mailserver` location to overwrite the internal version.

---

We could probably fix the `/tmp/docker-mailserver` permission issue by preventing the empty file creation, I don't think that is necessary. You can set [`ENABLE_QUOTAS=0`](https://docker-mailserver.github.io/docker-mailserver/v12.1/config/environment/#enable_quotas) to avoid this for now since you probably don't need the Dovecot Quotas feature?

---

The `/var/mail` override is a bit more tricky. We don't have an opt-out for that right now. You can comment it out [at the source](https://github.com/docker-mailserver/docker-mailserver/blob/652bbd831f6d25bf79b619094610011891ecddb7/target/scripts/helpers/utils.sh#L28-L42) and do a build of the image locally to workaround that. Alternatively if you do not need the mail location persisting to your host, you could skip this volume, or choose to use a named data volume instead of a bind mount volume. Both should resolve that.

**Comment by leccyril** [comment]
i run under linux fedora 38 with for each command sudo (and then i have to type my password)

i only run the docker compose command nothing else :/

here my new configuration according to the documentation 

```
version: '3'
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.equitativa.ae
    #env_file: mailserver.env
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "8082:8082"
    volumes:
      - ./docker-data/mail-data/:/var/mail/
      - ./docker-data/mail-state/:/var/mail-state/
      - ./docker-data/mail-logs/:/var/log/mail/
      - ./docker-data/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ./docker-data/dms/config/dovecot/10-master.conf:/etc/dovecot/conf.d/10-master.conf
    environment:
      - ENABLE_SPAMASSASSIN=1
      #- SPAMASSASSIN_SPAM_TO_INBOX=1
      #- ENABLE_CLAMAV=1
      #- ENABLE_FAIL2BAN=1
      #- ENABLE_POSTGREY=1
      #- ENABLE_SASLAUTHD=0
      #- ONE_DIR=1
      - DMS_DEBUG=1
      - PERMIT_DOCKER=host
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
```
in the conf fil i just added this 

doveadm_api_key = jemjoujou

```
service doveadm {
        unix_listener doveadm-server {
                user = vmail
        }
        inet_listener {
                port = 2425
        }
        inet_listener_http {
                port = 8082
        }
}
```

and the file override permissions : 

`-rw-r--r--. 1 root root 3476 Sep 14 09:36 /home/cyril.leclerc/dev/save/mailserver/docker-data/dms/config/dovecot/10-master.conf`

this is automatically created with this command

```
sudo mkdir -p ./docker-data/dms/config/dovecot
sudo docker cp mailserver:/etc/dovecot/conf.d/10-master.conf ./docker-data/dms/config/dovecot/10-master.conf
```

**Comment by polarathene** [comment]
I misread the `chown` failure. It wasn't `/var/mail` but `/var/log/mail` 😅 

I think the line for that change is happening at:

https://github.com/docker-mailserver/docker-mailserver/blob/86edaf9a8a3ad8d5b2bba3d9a6ad94b675ca7d1a/target/scripts/startup/setup.d/log.sh#L10

```yaml
volumes:
      # Useful for providing / persisting config:
      - ./docker-data/config/:/tmp/docker-mailserver/
      # Maybe useful, but optional:
      - /etc/localtime:/etc/localtime:ro
```

If you don't have a need for the other volumes, then just discard them for now, should remove any write errors like to `/var/log/mail`.

Now in your config volume, let's try this. Create a file with just the part you want to add, like you showed me. Let's call it `./docker-data/config/dovecot-override.conf`. Then create a new file `./docker-data/config/user-patches.sh`:

```bash
#! /bin/bash

# Add the file content to the end of `10-master.conf` file:
cat /tmp/docker-mailserver/dovecot-override.conf >> /etc/dovecot/conf.d/10-master.conf

# Alternatively, if you want to replace the whole file instead:
# cp /tmp/docker-mailserver/custom-10-master.conf /etc/dovecot/conf.d/10-master.conf
```

That should read your snippet after all the DMS setup is done, but before Dovecot gets started. So no more errors should happen there either. Then it will append that to the DMS `10-master.conf`, which [should currently be this content](https://github.com/docker-mailserver/docker-mailserver/blob/86edaf9a8a3ad8d5b2bba3d9a6ad94b675ca7d1a/target/dovecot/10-master.conf).

It doesn't look like there is any existing config there for `doveadm` service, so I think that'll work for you, but `user = vmail` may not. I am not sure if the container understands `vmail` user, most Dovecot guides will refer to that, but I think in DMS this is the `docker` user (UID 5000, GID 5000), so you may want to try change to that.

This should work for you and is two simple files. Just note that if you are using Docker Compose, you should make sure you run it with `docker compose --force-recreate up`. The `--force-recreate` is like `docker compose down && docker compose up`, which will recreate the container (_throw away any internal changes that don't persist to a volume_).

If you don't do that, restarting the container with changes still inside such as the `10-master.conf` will probably start to get multiple copies of your `dovecot-override.conf` added at the end.

**Comment by leccyril** [comment]
hi ok thanks we saw that on mounting files something happen i tried with my user and chown on root , after on the docker container we have this

![image](https://github.com/docker-mailserver/docker-mailserver/assets/3234598/7a08704f-0da9-4526-931f-b7cc8940f7f5)

so for each thing mounted we have this issue

i really appreciate your help the doveadm http is baes on this

https://doc.dovecot.org/admin_manual/doveadm_http_api/#configuration

**Comment by polarathene** [comment]
> on mounting files something happen i tried with my user and chown on root
> so for each thing mounted we have this issue

I am not sure why that is all `?` Perhaps it is Fedora denying access to information. Usually if the user does not exist in the container it would still show the UID or GID. What filesystem is the host location? Is it lacking file attributes/metadata?

---

> `DMS_DEBUG=1`

This shouldn't be relevant anymore, we replaced it with [`LOG_LEVEL`](https://docker-mailserver.github.io/docker-mailserver/latest/config/environment/#log_level). Where did you come across it?

> `SYS_PTRACE`

This also shouldn't be necessary?

Fedora may be influencing the errors you experienced due to SELinux. I am really not sure about that `/var/log/mail` failure

---

> and i always run
> 
> `docker compose down && docker compose up`

Good 👍 that should help avoid some problems at least.

I think Fedora is causing extra problems here. I can't really assist further due to that. You can run a VM with a different OS like EndeavourOS which shouldn't have any surprises like that, or maybe Ubuntu. 

Alternatively try temporarily disabling SELinux, the docs for Docker also have information on relaxing restrictions/security I think.

**Comment by polarathene** [comment]
> now i have to add manually the http configuration

? Just use the `user-patches.sh` feature?: https://docker-mailserver.github.io/docker-mailserver/v12.1/config/advanced/override-defaults/user-patches/

I showed you two commands you can use: https://github.com/docker-mailserver/docker-mailserver/issues/3500#issuecomment-1718882224

**Comment by leccyril** [comment]
ok i will test this because to install nano according to your previous advice to change content file but

```
sudo docker exec -it mailserver apt-get install nano
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package nano
```

**Comment by leccyril** [comment]
> I misread the `chown` failure. It wasn't `/var/mail` but `/var/log/mail` 😅
> 
> I think the line for that change is happening at:
> 
> https://github.com/docker-mailserver/docker-mailserver/blob/86edaf9a8a3ad8d5b2bba3d9a6ad94b675ca7d1a/target/scripts/startup/setup.d/log.sh#L10
> 
> ```yaml
> volumes:
>       # Useful for providing / persisting config:
>       - ./docker-data/config/:/tmp/docker-mailserver/
>       # Maybe useful, but optional:
>       - /etc/localtime:/etc/localtime:ro
> ```
> 
> If you don't have a need for the other volumes, then just discard them for now, should remove any write errors like to `/var/log/mail`.
> 
> Now in your config volume, let's try this. Create a file with just the part you want to add, like you showed me. Let's call it `./docker-data/config/dovecot-override.conf`. Then create a new file `./docker-data/config/user-patches.sh`:
> 
> ```shell
> #! /bin/bash
> 
> # Add the file content to the end of `10-master.conf` file:
> cat /tmp/docker-mailserver/dovecot-override.conf >> /etc/dovecot/conf.d/10-master.conf
> 
> # Alternatively, if you want to replace the whole file instead:
> # cp /tmp/docker-mailserver/custom-10-master.conf /etc/dovecot/conf.d/10-master.conf
> ```
> 
> That should read your snippet after all the DMS setup is done, but before Dovecot gets started. So no more errors should happen there either. Then it will append that to the DMS `10-master.conf`, which [should currently be this content](https://github.com/docker-mailserver/docker-mailserver/blob/86edaf9a8a3ad8d5b2bba3d9a6ad94b675ca7d1a/target/dovecot/10-master.conf).
> 
> It doesn't look like there is any existing config there for `doveadm` service, so I think that'll work for you, but `user = vmail` may not. I am not sure if the container understands `vmail` user, most Dovecot guides will refer to that, but I think in DMS this is the `docker` user (UID 5000, GID 5000), so you may want to try change to that.
> 
> This should work for you and is two simple files. Just note that if you are using Docker Compose, you should make sure you run it with `docker compose --force-recreate up`. The `--force-recreate` is like `docker compose down && docker compose up`, which will recreate the container (_throw away any internal changes that don't persist to a volume_).
> 
> If you don't do that, restarting the container with changes still inside such as the `10-master.conf` will probably start to get multiple copies of your `dovecot-override.conf` added at the end.

so this is not working because when i mount this folder tmp, then when i launch the setup phase i have thos error

`/usr/local/bin/helpers/database/db.sh: line 114: /tmp/docker-mailserver/postfix-accounts.cf: Permission denied
`
it is making me crazy

**Comment by polarathene** [comment]
> `E: Unable to locate package nano`

Something is wrong with your system.

**Comment by polarathene** [comment]
> it is making me crazy

Remove all volumes.

Run `docker exec -it mailserver bash`, now you have shell into the container.

Try `ping google.com` and `curl google.com`. If these have errors they cannot reach public internet, firewall maybe?

If it is working ok, now try `setup email add hello@example.test secret`. With no volumes mounted, this should not error.

You can try stop the container and add a new folder with the two files I mentioned (`dovecot-override.conf` + `user-patches.sh`) then mount this as your new `/tmp/docker-mailserver`.

If you get permission problem again, you need to try disabling the security. This is probably nothing to do with DMS and would happen with any container you run with volume mounted and trying to change files on it. You need to find out how to fix that in Fedora, I think it is SELinux or requires running Docker commands with extra args to fix (see the Docker docs).

You will have better time with VM running a different linux distro with Docker inside that. I like VMWare Workstation Player, but when I tried Fedora I remember this was annoying to install, whereas it is very easy on EndeavourOS with the AUR.

Fedora uses BTRFS by default these days. You did not mention what filesystem you are mounting from, there is a possibility that this is also affecting the compatibility.

**Comment by leccyril** [comment]
O after some instigation as you mentionned selinux cause issue so adding :Z make the trick

```
version: '3'
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.equitativa.ae
    #env_file: mailserver.env
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "8082:8082"
    volumes:
      - ./docker-data/mail-data/:/var/mail/:Z
      - ./docker-data/mail-state/:/var/mail-state/:Z
      - ./docker-data/mail-logs/:/var/log/mail/:Z
      - ./docker-data/config/:/tmp/docker-mailserver/:Z
      - /etc/localtime:/etc/localtime:ro
      - ./docker-data/dms/config/dovecot/10-master.conf:/etc/dovecot/conf.d/10-master.conf:Z
    environment:
      - ENABLE_QUOTAS=0 
      - PERMIT_DOCKER=host
    cap_add:
      - NET_ADMIN
    restart: always
```

then for the apt-get we need to do apt-geu update, then the install work, but some cmd are not existing, like ifconfig or netstat
