### ISSUE TITLE
bug report: only /20 subnet works

### ISSUE THREAD

**Issue by Xirado** [docker-mailserver/docker-mailserver#3518]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I tried running docker-mailserver in an external docker network with a `/16` subnet. I noticed that i could no longer access any ports using the container ip (also not externally). I compared my custom network with the one that gets created by default and noticed that the default one has a `/20` subnet. When specifying an external /20 subnet in my compose.yaml, it suddenly worked again. 

What's the reason for this behaviour? 

### 👟 Reproduction Steps

compose.yaml:
```yaml
services:
  mailserver:
    networks:
      mailserver:
        ipv4_address: 10.8.0.2
networks:
  mailserver:
    ipam:
      config:
        - subnet: 10.8.0.0/16
          gateway: 10.8.0.1
``` 

On the docker host:
```
$ telnet 10.8.0.2 25
Trying 10.8.0.2...
```

compose.yaml:
```yaml
services:
  mailserver:
    networks:
      mailserver:
        ipv4_address: 192.168.176.2
networks:
  mailserver:
    ipam:
      config:
        - subnet: 192.168.176.0/20
          gateway: 192.168.176.1
``` 

On the docker host:
```
$ telnet 192.168.176.2 25
Trying 192.168.176.2...
Connected to 192.168.176.2.
Escape character is '^]'.
220-mail.redacted.foo ESMTP
```
### 🐋 DMS Version

v12.1.0

### 💻 Operating System and Architecture

Debian GNU/Linux 11 (bullseye) x86_64

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:12.1.0
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: redacted.foo
    env_file: mailserver.env
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    cap_add:
      - NET_ADMIN
    networks:
      mailserver:
        ipv4_address: 10.8.0.2
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

networks:
  mailserver:
    ipam:
      config:
        - subnet: 10.8.0.0/16
          gateway: 10.8.0.1
```
