### ISSUE TITLE
bug report: connect to Milter service inet:localhost:11332: Cannot assign requested address

### ISSUE THREAD

**Issue by aphex3k** [docker-mailserver/docker-mailserver#3521]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Every time I send an email I see the following warning in the log
```
 warning: connect to Milter service inet:localhost:11332: Cannot assign requested address
```
The email gets sent correctly, however it seems to skip DKIM signing because RSPAMd proxy worker is unable to start or smtpd is at least unable to connect to it.

I'm trying to find out if this is an issue with `docker`, `docker-mailserver`, `SELinux`, or if I botched a configuration somewhere. My SELinux audit doesn't show anything conspicuous and (temporarily) disabling SELinux doesn't resolve/change the issue.

Neither `lsof` nor `ss` show port 11332 on the host.

I use the following `custom-commands.conf`:

```
enable-module dkim
enable-module dkim_signing
enable-module dmarc
enable-module spf
enable-module mx_check
enable-module greylist
enable-module rbl
enable-module phishing

set-option-for-module mx_check enabled true

set-option-for-module dmarc enabled true

set-option-for-module spf enabled true

set-option-for-module greylist enabled true

set-option-for-module rbl enabled true

set-option-for-module phishing enabled true

set-option-for-module classifier-bayes autolearn true

set-option-for-module dkim_signing enabled true
set-option-for-module dkim_signing path "/tmp/docker-mailserver/rspamd/dkim/rsa-1024-$selector-$domain.private.txt
set-option-for-module dkim_signing selector "mail"
set-option-for-module dkim_signing check_pubkey true
set-option-for-module dkim_signing allow_pubkey_mismatch false
``` 

### 🐋 DMS Version

v12.1.0

### 💻 Operating System and Architecture

Debian 5.10 + SELinux

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.<redacted>.com
    env_file: mailserver.env
    environment:
      - SSL_TYPE=letsencrypt
      - ENABLE_FAIL2BAN=1
      - ENABLE_MANAGESIEVE=1
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/rspamd/
      - ENABLE_RSPAMD=1
      - ENABLE_CLAMAV=1
      - ENABLE_OPENDKIM=0
      - ENABLE_OPENDMARC=0
      - ENABLE_POLICYD_SPF=0
      - ENABLE_AMAVIS=0
      - ENABLE_SPAMASSASSIN=0
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"       # SMTP  (explicit TLS => STARTTLS)
      - "143:143"     # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"     # ESMTP (implicit TLS)
      - "587:587"     # ESMTP (explicit TLS => STARTTLS)
      - "993:993"     # IMAP4 (implicit TLS)
      - "4190:4190"   # MANAGESIEVE
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/ssl/#lets-encrypt-recommended
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
    stop_grace_period: 2m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    cap_add:
     - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### 📜 Relevant log output

```Text
Aug 31 11:36:23 mail postfix/submission/smtpd[2241]: connect from <redacted>.com[<redacted>]
Aug 31 11:36:23 mail postfix/submission/smtpd[2241]: warning: connect to Milter service inet:localhost:11332: Cannot assign requested address
Aug 31 11:36:23 mail postfix/submission/smtpd[2241]: Anonymous TLS connection established from <redacted>.com[<redacted>]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Aug 31 11:36:23 mail postfix/submission/smtpd[2241]: 8F24563006CC: client=ip68-101-236-151.sd.sd.cox.net[68.101.236.151], sasl_method=PLAIN, sasl_username=<redacted>
Aug 31 11:36:23 mail postfix/sender-cleanup/cleanup[2269]: 8F24563006CC: replace: header Mime-Version: 1.0 (Mac OS X Mail 16.0 \(3731.600.7\)) from <redacted>.com[<redacted>]; from=<redacted> to=<redacted> proto=ESMTP helo=<smtpclient.apple>: MIME-Version: 1.0
Aug 31 11:36:23 mail postfix/sender-cleanup/cleanup[2269]: 8F24563006CC: message-id=<redacted>
```
