### ISSUE TITLE
bug report: docker compose up with default compose.yml throws the error

### ISSUE THREAD

**Issue by east2dd** [docker-mailserver/docker-mailserver#3530]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

`docker-compose up` should run smtp server, but cannot run server.

### 👟 Reproduction Steps

1. clone repo
2. move to repo directory
3. run `docker compose up`
4. add email using `./setup.sh email add a@mars.com`

It seems fine until adding a email. After a email is added, I got error `fatal: bind: private/smtpd: Invalid argument`
I used default `compose.yaml` and `mailserver.env` files.

### 🐋 DMS Version

v12.1.0

### 💻 Operating System and Architecture

MacOS 13.5.1

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.mars.com
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### 📜 Relevant log output

```Text
mailserver  | Sep  6 15:16:48 mail amavis[595]: starting. /usr/sbin/amavisd-new at mail.huasong.com amavisd-new-2.11.1 (20181009), Unicode aware, LC_CTYPE="C.UTF-8"
mailserver  | Sep  6 15:16:48 mail amavis[595]: perl=5.032001, user=, EUID: 109 (109);  group=, EGID: 111 111 (111 111)
mailserver  | Sep  6 15:16:48 mail amavis[595]: (!)Net::Server: 2023/09/06-15:16:48 Can't connect to UNIX socket at file /var/lib/amavis/amavisd.sock [Invalid argument]\n  at line 66 in file /usr/share/perl5/Net/Server/Proto/UNIX.pm
mailserver  | Sep  6 15:16:48 mail postfix/postfix-script[679]: starting the Postfix mail system
mailserver  | Sep  6 15:16:48 mail postfix/master[680]: fatal: bind: private/smtpd: Invalid argument
```
