### ISSUE TITLE
question: How to configure Traefik for port 465? (Postfix smtpd throws TLS library error)

### ISSUE THREAD

**Issue by mich2k** [docker-mailserver/docker-mailserver#3546]
### 📝 Preliminary Checks

- [x] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Hello, after having carefully followed every step reported in #3063 I still do not manage in any way running implicit TLS SMTP meanwhile implicit imap works, wondering how to interpret these logs I get

### 👟 Reproduction Steps

Use DMS behind Traefik reverse proxy

### 🐋 DMS Version

v12.1.0

### 💻 Operating System and Architecture

Linux sbserver 5.15.0-83-generic #92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### ⚙️ Container configuration files

```yml
dovecot config override:


haproxy_trusted_networks = 172.25.0.2, 32
haproxy_timeout = 3 secs
service imap-login {
  inet_listener imaps {
    haproxy = yes
    ssl = yes
    port = 10993
  }
}
```
postfix-master

```
submission/inet/smtpd_upstream_proxy_protocol=haproxy
submissions/inet/smtpd_upstream_proxy_protocol=haproxy
```
postfix-main

```
postscreen_upstream_proxy_protocol = haproxy
```

container compose

```yml

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    restart: always
    container_name: mailserver
    hostname: mail.domain.com
    env_file: mailserver.env
    volumes:
      - ${DOCKER_VOLUMES_FOLDER}/dms/mail-data/:/var/mail/
      - ${DOCKER_VOLUMES_FOLDER}/dms/mail-state/:/var/mail-state/
      - ${DOCKER_VOLUMES_FOLDER}/dms/mail-logs/:/var/log/mail/
      - ${DOCKER_VOLUMES_FOLDER}/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_VOLUMES_FOLDER}/traefik/acme.json:/etc/letsencrypt/acme.json:ro
    cap_add:
      - NET_ADMIN
    stop_grace_period: 1m
    environment:
      - SSL_TYPE=letsencrypt
      - SSL_DOMAIN=domain.com # using wildcard cert

    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.smtp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smtp.entrypoints=smtp"
      - "traefik.tcp.routers.smtp.service=smtp"
      - "traefik.tcp.services.smtp.loadbalancer.server.port=25"
      - "traefik.tcp.services.smtp.loadbalancer.proxyProtocol.version=1"
      - "traefik.tcp.routers.smtp-ssl.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smtp-ssl.tls=false"
      - "traefik.tcp.routers.smtp-ssl.entrypoints=smtp-ssl"
      - "traefik.tcp.routers.smtp-ssl.service=smtp-ssl"
      - "traefik.tcp.services.smtp-ssl.loadbalancer.server.port=465"
      - "traefik.tcp.services.smtp-ssl.loadbalancer.proxyProtocol.version=1"
      - "traefik.tcp.routers.imap-ssl.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.imap-ssl.entrypoints=imap-ssl"
      - "traefik.tcp.routers.imap-ssl.service=imap-ssl"
      - "traefik.tcp.services.imap-ssl.loadbalancer.server.port=10993"
      - "traefik.tcp.services.imap-ssl.loadbalancer.proxyProtocol.version=2"
      - "traefik.tcp.routers.sieve.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.sieve.entrypoints=sieve"
      - "traefik.tcp.routers.sieve.service=sieve"
      - "traefik.tcp.services.sieve.loadbalancer.server.port=4190"
    
    networks:
      proxy:
        ipv4_address: 172.25.0.12
```

### 📜 Relevant log output

```
Sep 23 12:27:27 mail postfix/smtps/smtpd[415654]: connect from traefik.proxy[172.25.0.2]
Sep 23 12:27:27 mail postfix/smtps/smtpd[415654]: SSL_accept error from traefik.proxy[172.25.0.2]: -1
Sep 23 12:27:27 mail postfix/smtps/smtpd[415654]: warning: TLS library problem: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331:
Sep 23 12:27:27 mail postfix/smtps/smtpd[415654]: lost connection after CONNECT from traefik.proxy[172.25.0.2]
Sep 23 12:27:27 mail postfix/smtps/smtpd[415654]: disconnect from traefik.proxy[172.25.0.2] commands=0/0
Sep 23 12:27:27 mail postfix/smtps/smtpd[415654]: connect from traefik.proxy[172.25.0.2]
Sep 23 12:27:27 mail postfix/smtps/smtpd[415654]: SSL_accept error from traefik.proxy[172.25.0.2]: -1
Sep 23 12:27:27 mail postfix/smtps/smtpd[415654]: warning: TLS library problem: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331:
Sep 23 12:27:27 mail postfix/smtps/smtpd[415654]: lost connection after CONNECT from traefik.proxy[172.25.0.2]
Sep 23 12:27:27 mail postfix/smtps/smtpd[415654]: disconnect from traefik.proxy[172.25.0.2] commands=0/0
Sep 23 12:27:28 mail postfix/smtps/smtpd[415654]: connect from traefik.proxy[172.25.0.2]
Sep 23 12:27:28 mail postfix/smtps/smtpd[415654]: SSL_accept error from traefik.proxy[172.25.0.2]: -1
Sep 23 12:27:28 mail postfix/smtps/smtpd[415654]: warning: TLS library problem: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331:
Sep 23 12:27:28 mail postfix/smtps/smtpd[415654]: lost connection after CONNECT from traefik.proxy[172.25.0.2]
Sep 23 12:27:28 mail postfix/smtps/smtpd[415654]: disconnect from traefik.proxy[172.25.0.2] commands=0/0
Sep 23 12:27:28 mail postfix/smtps/smtpd[415654]: connect from traefik.proxy[172.25.0.2]
Sep 23 12:27:28 mail postfix/smtps/smtpd[415654]: SSL_accept error from traefik.proxy[172.25.0.2]: -1
Sep 23 12:27:28 mail postfix/smtps/smtpd[415654]: warning: TLS library problem: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331:
Sep 23 12:27:28 mail postfix/smtps/smtpd[415654]: lost connection after CONNECT from traefik.proxy[172.25.0.2]
Sep 23 12:27:28 mail postfix/smtps/smtpd[415654]: disconnect from traefik.proxy[172.25.0.2] commands=0/0
Sep 23 12:27:28 mail postfix/smtps/smtpd[415654]: connect from traefik.proxy[172.25.0.2]
Sep 23 12:27:28 mail postfix/smtps/smtpd[415654]: SSL_accept error from traefik.proxy[172.25.0.2]: -1
Sep 23 12:27:28 mail postfix/smtps/smtpd[415654]: warning: TLS library problem: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331:
Sep 23 12:27:28 mail postfix/smtps/smtpd[415654]: lost connection after CONNECT from traefik.proxy[172.25.0.2]
Sep 23 12:27:28 mail postfix/smtps/smtpd[415654]: disconnect from traefik.proxy[172.25.0.2] commands=0/0
Sep 23 12:42:20 mail postfix/smtps/smtpd[417225]: connect from traefik.proxy[172.25.0.2]
Sep 23 12:42:20 mail postfix/smtps/smtpd[417225]: SSL_accept error from traefik.proxy[172.25.0.2]: -1
Sep 23 12:42:20 mail postfix/smtps/smtpd[417225]: warning: TLS library problem: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331:
Sep 23 12:42:20 mail postfix/smtps/smtpd[417225]: lost connection after CONNECT from traefik.proxy[172.25.0.2]
Sep 23 12:42:20 mail postfix/smtps/smtpd[417225]: disconnect from traefik.proxy[172.25.0.2] commands=0/0
```

**Comment by polarathene** [comment]
As a first step, could you help narrow the configuration down to a minimal reproduction? I've not used Traefik.

- I assume we can drop the IMAP config (Dovecot) for now to focus on just the port 465 issue (Postfix submission)
- Is haproxy important? Can you elaborate what that is doing?
- Are we able to rule out the `acme.json` support for now?
  - Technically we can try with the `acme.json` first and ignore Traefik + haproxy changes to confirm the cert is working correctly. We have [tests that check this](https://github.com/docker-mailserver/docker-mailserver/blob/8c0cfa0836bcf20e78a2d5d1ae02270004ee0aed/test/tests/parallel/set1/tls/letsencrypt.bats), but they don't perform any mail submission, but they do [test establishing TLS connection is successful (_including for port 465_)](https://github.com/docker-mailserver/docker-mailserver/blob/8c0cfa0836bcf20e78a2d5d1ae02270004ee0aed/test/helper/tls.bash#L31-L34).
  - We have some self-signed certs (_and variants with a self-signed root CA instead of LetsEncrypt_) used for testing with [`mail.example.test` / `example.test` here](https://github.com/docker-mailserver/docker-mailserver/tree/8c0cfa0836bcf20e78a2d5d1ae02270004ee0aed/test/test-files/ssl/example.test). Those also include an `acme.json`. I suppose Traefik would need to be configured to use those as well, but a bit more tricky to setup trust for the self-signed root CA. Don't worry about this too much, it's just an idea a better controlled reproduction environment.

---

I don't have much time myself to dig into this, and that's probably the case for others too. So it'd be best to minimize the `compose.yaml` to focus on the core issue with port 465.

It should be possible to reduce down to this, plus whatever extra Traefik config with labels is needed? Do you have a traefik service also configured for `compose.yaml` for easier reproduction?

```yaml
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:12.1
    container_name: mailserver
    hostname: mail.domain.com
    # You should be able to reproduce without needing any other volumes (just `postfix-accounts.cf` and overrides needed)
    volumes:
      - ${DOCKER_VOLUMES_FOLDER}/dms/config/:/tmp/docker-mailserver/
      - ${DOCKER_VOLUMES_FOLDER}/traefik/acme.json:/etc/letsencrypt/acme.json:ro
    # skip env file, since that's not helping identify minimum environment settings
    environment:
      - SSL_TYPE=letsencrypt
      # You shouldn't need SSL_DOMAIN (docs are a bit outdated regarding that)
      # - SSL_DOMAIN=domain.com # using wildcard cert
    # What is the minimum labels needed here to reproduce the port 465 issue with traefik?
    labels:
      - "traefik.enable=true"
    networks:
      proxy:
        ipv4_address: 172.25.0.12

# No healthcheck or other service settings needed
```

---

Try the following (_`localhost` should be fine as-is_):

```bash
# Test the connection directly on DMS (and maybe also against the traefik container):
# Success should have `Verification: OK` in output
docker exec -it mailserver sh -c 'timeout 1 openssl s_client -connect localhost:465'
```

Extra options you can add to the end of that command:
- `-CAfile /path/to/ca.file` if using custom CA instead of LetsEncrypt (_if running in a container, this path must exist in the container_)
- `-servername mail.example.test` if testing FQDN (_eg: openssl request to traefik, this provides SNI for it to route_). Adjust to your actual configured `hostname` for DMS.

You could use the cert files I linked with the `-CAfile` and `-servername` options for `mail.example.test`, but as mentioned this may be extra hassle to setup correctly (_either adding to containers / host trust stores_). Since you've got Dovecot IMAP working successfully, it'd seem the issue is with Postfix.

With your setup, does this also produce the TLS error when it runs the openssl command in the DMS container? If it does that is helpful, if it doesn't, it should when going through Traefik (_you'll likely need the `-servername` option_).

---

<details>
<summary>Ignore this (misunderstanding)</summary>

**EDIT:** This is bad advice 😅 (_trusting client IPs like Traefik, shouldn't be related to authenticating trust over port 465_)

Another option for testing could be related to the Postfix network trust. ~~You configured this explicitly for Dovecot above, but I don't see similar done for Postfix.~~ (_**EDIT:** My mistake, dovecot was haproxy trust, not client trust_)

We have support for that with `PERMIT_DOCKER`, but be careful here as when the host can be reached by IPv6 IP, it can route to Docker IPv4 via the bridge gateway allowing to bypass trust. Either disable IPv6 access to the host, or configure an IPv6 ULA network for docker (_see our `:edge` docs, IPv6 page was rewritten for v13 release_).

Note that [`PERMIT_DOCKER` doesn't look like it was implemented properly IMO](https://github.com/docker-mailserver/docker-mailserver/issues/3478). You could try `PERMIT_DOCKER=host` for now, or maybe `mynetworks` directly via `postfix-main.cf` override to whitelist the network addresses you do want to trust explicitly. Our `main.cf` default defines the following:

https://github.com/docker-mailserver/docker-mailserver/blob/f28fce9cc432f1f447bd963d9e54e44bcf2c27dd/target/postfix/main.cf#L17

However since Feb 2022 the default of `PERMIT_DOCKER` was changed to `none` which empties that entirely:

https://github.com/docker-mailserver/docker-mailserver/blob/f28fce9cc432f1f447bd963d9e54e44bcf2c27dd/target/scripts/startup/setup.d/networking.sh#L45-L48

AFAIK, this shouldn't need to change. Authenticating over port 465 should provide the trust, while whitelisting clients from IPs or entire subnets bypasses that. ~~It's possible that this is why Dovecot is working for you on IMAP?~~ (_**EDIT: Nevermind that's haproxy specific_)

</details>

**Comment by mich2k** [comment]
Hello, thank you for the help..

This is the compose

```
version: '3.5'
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    restart: always
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.domain.com
#    env_file: mailserver.env
    volumes:
      - ${DOCKER_VOLUMES_FOLDER}/dms/mail-data/:/var/mail/
      - ${DOCKER_VOLUMES_FOLDER}/dms/mail-state/:/var/mail-state/
      - ${DOCKER_VOLUMES_FOLDER}/dms/mail-logs/:/var/log/mail/
      - ${DOCKER_VOLUMES_FOLDER}/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_VOLUMES_FOLDER}/traefik/acme.json:/etc/letsencrypt/acme.json:ro # /live:ro

    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    stop_grace_period: 1m
    environment:
      - SSL_TYPE=letsencrypt
#      - SSL_DOMAIN=domain.com

    # healthcheck:
    #   test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
    #   timeout: 3s
    #   retries: 0

    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.smtp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smtp.entrypoints=smtp"
      - "traefik.tcp.routers.smtp.service=smtp"
      - "traefik.tcp.services.smtp.loadbalancer.server.port=25"
      - "traefik.tcp.services.smtp.loadbalancer.proxyProtocol.version=1"
      - "traefik.tcp.routers.smtp-ssl.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smtp-ssl.tls=false"
      - "traefik.tcp.routers.smtp-ssl.entrypoints=smtp-ssl"
      - "traefik.tcp.routers.smtp-ssl.service=smtp-ssl"
      - "traefik.tcp.services.smtp-ssl.loadbalancer.server.port=465"
      - "traefik.tcp.services.smtp-ssl.loadbalancer.proxyProtocol.version=1"
      - "traefik.tcp.routers.imap-ssl.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.imap-ssl.entrypoints=imap-ssl"
      - "traefik.tcp.routers.imap-ssl.service=imap-ssl"
      - "traefik.tcp.services.imap-ssl.loadbalancer.server.port=10993"
      - "traefik.tcp.services.imap-ssl.loadbalancer.proxyProtocol.version=2"
      - "traefik.tcp.routers.sieve.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.sieve.entrypoints=sieve"
      - "traefik.tcp.routers.sieve.service=sieve"
      - "traefik.tcp.services.sieve.loadbalancer.server.port=4190"
    
    networks:
      proxy:
        ipv4_address: 172.25.0.14


  traefik:
    image: traefik:2.10
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
      - "853:853"
      - "25:25"
      - "465:465"
      - "993:993"
      - "4190:4190"
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_API_TOKEN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKER_VOLUMES_FOLDER}/traefik/traefik.yml:/traefik.yml:ro
      - ${DOCKER_VOLUMES_FOLDER}/traefik/acme.json:/acme.json
      - ${DOCKER_VOLUMES_FOLDER}/traefik/config.yml:/config.yml:ro
      - ${DOCKER_VOLUMES_FOLDER}/traefik/logs:/var/log/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.domain.com`)"


      - "traefik.http.routers.traefik-secure.service=api@internal"
    networks:
       proxy:
          ipv4_address: 172.25.0.2


networks:
  proxy:
    driver: bridge
    name: proxy
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1

```
and the traefik.yml


```
api:
  dashboard: true
  debug: true

accessLog:
  filePath: "/var/log/access.log"

log:
  level: INFO
  format: json
  filePath: /var/log/traefik/traefik.log

accesslog:
   format: json
   filePath: /var/log/traefik/access.log

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  # HTTPS endpoint, with domain wildcard
  https:
    address: :443
    http:
      tls:
        # Generate a wildcard domain certificate
        certResolver: cloudflare
        domains:
          - main: domain.com
            sans:
              - '*.domain.com'

  dot:
    address: ":853"
    
  smtp:
    address: ":25"

  smtp-ssl:
    address: ":465"

  imap-ssl:
    address: ":993"

  sieve:
    address: ":4190"


serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config.yml

certificatesResolvers:
  cloudflare:
    acme:
      email: mail@domain.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
```

I commented out the mailserver.env and deleted the imap config file

from ` docker exec -it mailserver sh -c 'timeout 1 openssl s_client -connect localhost:465' ` I get

```
 Server Temp Key: X25519, 253 bits
---
SSL handshake has read 5036 bytes and written 363 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
```
and also including the servername flag I get the "Verification: OK" (same output)

Looking the docker logs of the container 
```
Sep 24 19:32:01 mail postfix/smtps/smtpd[9526]: connect from localhost[127.0.0.1]
Sep 24 19:32:01 mail postfix/smtps/smtpd[9526]: Anonymous TLS connection established from localhost[127.0.0.1]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (4096 bits) server-digest SHA256
Sep 24 19:32:01 mail opendmarc[464]: ignoring connection from localhost
Sep 24 19:32:02 mail postfix/smtps/smtpd[9526]: lost connection after CONNECT from localhost[127.0.0.1]
Sep 24 19:32:02 mail postfix/smtps/smtpd[9526]: disconnect from localhost[127.0.0.1] commands=0/0
```
meanwhile when connecting from an external client (no vpn) or a client from the server itself (with wireguard vpn & split dns) the same error logs happen:

```
Sep 24 19:30:13 mail postfix/smtps/smtpd[9352]: warning: TLS library problem: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331:
```

and thunderbird returns "Thunderbird failed to find the settings for your account"

I thank you again for the very detailed answer, if you have no time please I will just keep trying by myself
