### ISSUE TITLE
bug report: Setup Config DKIM doesn't generate new

### ISSUE THREAD

**Issue by aalfiann** [docker-mailserver/docker-mailserver#3555]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I just use docker-mailserver, eveything working fine, I can sending, receiving email.

but I found that DKIM is invalid, then I tried to generate new DKIM with different key size.

I did 
```bash
docker exec -ti mailserver setup config dkim keysize 1024
```

then I check carefully the **mail.private** and **mail.txt** in `docker-data/dms/config` also in `/tmp/docker-mailserver`

the keys is not generating new, it still the same old keys.

for more information, here is my docker-compose.yml
```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.power-up.tv
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "465:465"
      - "993:993"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - ./docker-data/certbot/certs/:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_FAIL2BAN=1
      # Using letsencrypt for SSL/TLS certificates:
      - SSL_TYPE=letsencrypt
      # Allow sending emails from other docker containers:
      # Beware creating an Open Relay: https://docker-mailserver.github.io/docker-mailserver/latest/config/environment/#permit_docker
      - PERMIT_DOCKER=network
      # You may want to enable this: https://docker-mailserver.github.io/docker-mailserver/latest/config/environment/#spoof_protection
      # See step 6 below, which demonstrates setup with enabled/disabled SPOOF_PROTECTION:
      - SPOOF_PROTECTION=0
      - TZ=Europe/London
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    restart: always
```

### 👟 Reproduction Steps

1. Please try with my docker-compose.yml
2. Try to run `docker exec -it mailserver setup config dkim keysize 1024`
3. Then take a look, is the keys will generate new?

### 🐋 DMS Version

v12.1.0

### 💻 Operating System and Architecture

Ubuntu 20
