### ISSUE TITLE
"Relay access denied" after upgrade from 10.0.0 to 12.1.0

### ISSUE THREAD

**Issue by michabbb** [docker-mailserver/docker-mailserver#3556]
### Subject

Something else that requires developers attention

### Description

hi there,

without changing any config or dns related stuff, the mailserver is no longer able to send emails (in my case to gmail) 😢 
and yes, sorry, I tried with my old mailserver.env 🙈 

so version 12.1.0 shows me:

```txt
Sep 28 21:08:21 mx postfix/smtpd[1330]: NOQUEUE: reject: RCPT from youtrack_youtrack_1.mailserver[192.168.32.3]: 554 5.7.1 <my@xxxxxxxxxx.de>: Relay access denied; from=<xxxxxxxx@xxxxxxxx> to=<my@xxxxxxxx.de> proto=ESMTP helo=<4e641f8296c3>
```

while version 10.0.0 works:

```txt
Sep 28 21:14:18 5b68b6b5631e postfix/smtp[2631]: connect to ASPMX.L.GOOGLE.COM[2a00:1450:4010:c08::1b]:25: Cannot assign requested address
Sep 28 21:14:18 5b68b6b5631e postfix/smtp[2631]: Trusted TLS connection established to aspmx.l.google.com[64.233.161.26]:25: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature ECDSA (P-256) server-digest SHA256
Sep 28 21:14:19 5b68b6b5631e postfix/smtp[2631]: 6E3E9780444: to=<my@xxxxxxxxxx.de>, relay=ASPMX.L.GOOGLE.COM[64.233.161.26]:25, delay=1.2, delays=0.06/0.03/0.26/0.86, dsn=2.0.0, status=sent (250 2.0.0 OK  1695928459 l28-20020ac24a9c000000b0050420b0a643si7129085lfp.521 - gsmtp)
```

is the problem maybe related to the "helo":
```
helo=<4e641f8296c3>
``` 
🤔 

I will check the latest docu and config, but in the meantime, maybe someone of you knows what has changed between these both versions that causes this problem.

thanks for any help!! 🙏

**Comment by michabbb** [comment]
okay, i am the point where i changed so much stuff i don´t know which combination did the trick. so some infos in case someone finds this issue. in my situation I have another docker-container that got a "Relay Access Denied" but hosts from outside were able to send. so I realized this has nothing to do with google. my other container was not able to talk to the mailserver, but that hat something to do with the "networks" I was using. i thought any container can contact the mailserver with its public IP (which is the same of the docker host) - but somehow I had issues here. 

so I guess one important part is to set `PERMIT_DOCKER=network` inside the `mailserver.env`.

and here´s my config for the mailserver:

```yml
networks:
    web:
        external: true
    internal: 
        external: true

x-logging-settings: &default_logging
  driver: json-file
  options:
    max-size: 10m
    max-file: '3'

services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:12.1.0
    logging: *default_logging
    hostname: mx.xxxxxxxxxx
    container_name: mailserver
    env_file: mailserver.env
    environment:
      SSL_TYPE: letsencrypt
      SSL_DOMAIN: mx.xxxxxxxxxxxxxxx
      ENABLE_FAIL2BAN: 1
      FAIL2BAN_BLOCKTYPE: drop
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    # More information about the mailserver ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ${PWD}/data/data/maildata:/var/mail
      - ${PWD}/data/data/mailstate:/var/mail-state
      - ${PWD}/data/data/maillogs:/var/log/mail
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/data/config/:/tmp/docker-mailserver/
      - /docker/traefik/acme.json:/etc/letsencrypt/acme.json:ro
    restart: always
    networks:
     - web
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    stop_grace_period: 1m
    cap_add: [ "NET_ADMIN", "SYS_PTRACE" ]
    labels:
      - traefik.enable=false 

  whoami:
    image: docker.io/traefik/whoami:latest
    logging: *default_logging
    restart: always
    networks:
      - internal
      - web
    expose:
      - 80
    labels:
      - traefik.http.routers.whoami.rule=Host(`mx.xxxxxxxxxxxxx`)
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.tls.certresolver=leresolver
      - traefik.port=80       
```

and here is my other container that always got the "Relay Access Denied":

```yml
version: "3.9"

networks:
    web:
        external: true

x-logging-settings: &default_logging
  driver: json-file
  options:
    max-size: 10m
    max-file: '3'

services:
  youtrack:
    image: jetbrains/youtrack:latest
    logging: *default_logging
    networks:
     - web
    volumes:
     - ${PWD}/data/data:/opt/youtrack/data
     - ${PWD}/data/conf:/opt/youtrack/conf
     - ${PWD}/data/logs:/opt/youtrack/logs
     - ${PWD}/data/backup:/opt/youtrack/backups
     - /etc/localtime:/etc/localtime:ro
     - /etc/timezone:/etc/timezone:ro
     - /tmp/:/tmp/
    restart: always 
    expose:
     - 8080
    environment:
     - TZ=Europe/Berlin
    labels:
     - traefik.http.routers.youtrack.rule=Host(`xxxxxxxxxxxxxxx`)
     - traefik.http.routers.youtrack.tls=true
     - traefik.http.routers.youtrack.tls.certresolver=leresolver
     - traefik.port=8080
```

so having both containers/services on the same host, I was forced to have both in the same network to make this work.
and of course use `PERMIT_DOCKER=network`.
