### ISSUE TITLE
bug report: SA should not send a daily cron error mail when Amavis is disabled

### ISSUE THREAD

**Issue by Waldorf3** [docker-mailserver/docker-mailserver#3569]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I get a mail daily with this error with the following subject:

> Cron [root@mail](mailto:root@mail) test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )

And this as content:

> /etc/cron.daily/spamassassin:
> run-parts: /etc/spamassassin/sa-update-hooks.d/amavisd-new exited with return code 3
> run-parts: /etc/cron.daily/spamassassin exited with return code 1

Have pulled latest container and restarted, but it still throws this daily error.

### 👟 Reproduction Steps

uhm. Install it and run it for 24 hours. 

### 🐋 DMS Version

I don't know, all it says is TAG:latest

### 💻 Operating System and Architecture

Debian 12

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.domain.com
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
      - "10.10.10.101:11334:11334"
    volumes:
      - ./mail-data/:/var/mail/
      - ./mail-state/:/var/mail-state/
      - ./mail-logs/:/var/log/mail/
      - ./config/:/tmp/docker-mailserver/
      - ./worker-controller.inc:/etc/rspamd/local.d/worker-controller.inc
      - /etc/localtime:/etc/localtime:ro
      - ../npm/config/letsencrypt:/etc/letsencrypt:ro
    environment:
      - ENABLE_AMAVIS=2
      - ENABLE_DNSBL=1
      - ENABLE_OpenDKIM=1
      - ENABLE_OpenDMARC=1
      - ENABLE_POLICYD_SPF=1
      - ENABLE_POP3=1
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=1
      - SSL_TYPE=letsencrypt
      - ENABLE_RSPAMD=0
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=0
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    restart: always
```
