### ISSUE TITLE
bug report: SPF Fail - Not authorized in Outlook sending to DMS

### ISSUE THREAD

**Issue by Kira-Kitsune** [docker-mailserver/docker-mailserver#3573]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Although everything works fine on GMail, Proton and Thunderbird (to use to send from my custom email)

I could only send to outlook.com but could not receive, it would return 
`Recipient address rejected: Message rejected due to: SPF fail - not authorized. ` (550 5.7.23)
nor does it allow me to sign in with outlook IMAP

I do not know why this doesn't work, something to do with Microsoft. I've searched all over the place and couldn't find an answer.

### 🐋 DMS Version

v12.1.0

### 💻 Operating System and Architecture

Ubuntu 22.04.3 LTS

### ⚙️ Container configuration files

```yml
version: "3"
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.kirakitsune.com
    env_file: mailserver.env
    environment:
      # Set SSL certificate type.
      - SSL_TYPE=letsencrypt

    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ./docker-data/certbot/certs/:/etc/letsencrypt/:ro
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```
