### ISSUE TITLE
bug report: keysize parameter seems to be ignored with opendkim key generation

### ISSUE THREAD

**Issue by 101smurf** [docker-mailserver/docker-mailserver#3628]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I'm trying to generate 2048 byte keys for compatibility with Microsoft's mailservers. 4096 byte keys work with Protonmail, and the signature is valid. 

### 👟 Reproduction Steps

Our testing server (trying to generate a new keypair): 
```bash
gophish-dev-server  ~ sudo docker exec -ti mailserver /bin/bash -c 'rm /tmp/docker-mailserver/opendkim/keys/a-testing-domain.com/*'

gophish-dev-server  ~ sudo docker exec -ti mailserver /bin/bash -c 'ls /tmp/docker-mailserver/opendkim/keys/a-testing-domain.com/*'
ls: cannot access '/tmp/docker-mailserver/opendkim/keys/a-testing-domain.com/*': No such file or directory

gophish-dev-server  ~ sudo docker exec -ti mailserver setup config dkim keysize 2048
[   INF   ]  Creating DKIM private key '/tmp/docker-mailserver/opendkim/keys/a-testing-domain.com/mail.private'

gophish-dev-server  ~ sudo docker exec -ti mailserver /bin/bash -c 'ls -lash /tmp/docker-mailserver/opendkim/keys/a-testing-domain.com/mail.private'
4.0K -rw------- 1 root root 1.7K Nov  8 11:16 /tmp/docker-mailserver/opendkim/keys/a-testing-domain.com/mail.private
```

Our production (still on  4096 byte keys)
```bash
sudo docker exec -ti mailserver /bin/bash -c 'ls -lash /tmp/docker-mailserver/opendkim/keys/somesite.net/mail.private'
4.0K -rw------- 1 root root 3.2K Aug 25  2022 /tmp/docker-mailserver/opendkim/keys/somesite.net/mail.private
```

### 🐋 DMS Version

d5db200744f1

### 💻 Operating System and Architecture

Ubuntu 22.04.3 LTS 

### ⚙️ Container configuration files

```yml
mailserver:
  image: docker.io/mailserver/docker-mailserver:11.3.1
  container_name: mailserver
  hostname: "somehostname"
  domainname: "whatever.com"
  ports:
        - "25:25"    # SMTP  (explicit TLS => STARTTLS)
        - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
        - "465:465"  # ESMTP (implicit TLS)
        - "587:587"  # ESMTP (explicit TLS => STARTTLS)
        - "993:993"  # IMAP4 (implicit TLS)
  environment:
        - ENABLE_SPAMASSASSIN=1
        - SPAMASSASSIN_SPAM_TO_INBOX=1
        - ENABLE_CLAMAV=1
        - ENABLE_POSTGREY=1
        - ENABLE_SASLAUTHD=0
        - ONE_DIR=1
        - TZ=Europe/Amsterdam
        - SSL_TYPE=letsencrypt
  volumes:
        - mailserver_data:/var/mail
        - mailserver_state:/var/mail-state
        - mailserver_logs:/var/log/mail
        - mailserver_config:/tmp/docker-mailserver
        - "ourcerts/whatever.crt:/etc/letsencrypt/live/whatever/fullchain.pem"
        - "ourcerts/whatever.key:/etc/letsencrypt/live/whatever/privkey.pem"
  restart: unless-stopped
```

### 📜 Relevant log output

```console
$ sudo docker logs mailserver 2>&1 | grep -i opendkim
Nov  8 10:56:51 mail opendkim[889]: 997AF27ABB4: no signing table match for 'root@mail.whatever.com'
Nov  8 10:56:51 mail opendkim[889]: 997AF27ABB4: no signature data
Nov  8 11:06:24 mail opendkim[889]: 0CB3627AC57: DKIM-Signature field added (s=mail, d=whatever.com)
```

```console
gophish-dev-server  $ sudo docker logs mailserver 2>&1 | grep -i a-testing-domain.com
gophish-dev-server  $
```
