### ISSUE TITLE
bug report: Version 13 LDAP config / connection error

### ISSUE THREAD

**Issue by cloud-erik** [docker-mailserver/docker-mailserver#3668]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

After upgrade to version 13 the LDAP connection is not working anymore.
LDAP connection was running with v12 smoothless.
Downgrade to v12 brings it back to work.

### 👟 Reproduction Steps

Upgrade existing LDAP installtion to v13

### 🐋 DMS Version

v13

### 💻 Operating System and Architecture

Ubuntu

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:12.1.0 # or latest / 13 to get th error
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail
    domainname: xxx.xxx
    #env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
      - "4190:4190" # MANAGESIEVE
      - "10993:10993" # dovecot IMAP HA-Proxy
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - ./docker-data/dms/amavis_conf/:/etc/amavis/conf.d
      - ./docker-data/dms/config/dovecot-local.conf:/etc/dovecot/local.conf
      - ./docker-data/dms/cron/sa-learn:/etc/cron.d/sa-learn
      - /data/compose/certs:/etc/letsencrypt/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - ONE_DIR=${ONE_DIR}
      - PERMIT_DOCKER=${PERMIT_DOCKER}
      - TZ=${TZ}
      - ENABLE_AMAVIS=${ENABLE_AMAVIS}
      - AMAVIS_LOGLEVEL=${AMAVIS_LOGLEVEL}
      - ENABLE_DNSBL=${ENABLE_DNSBL}
      - ENABLE_CLAMAV=${ENABLE_CLAMAV}
      - ENABLE_FAIL2BAN=${ENABLE_FAIL2BAN}
      - FAIL2BAN_BLOCKTYPE=${FAIL2BAN_BLOCKTYPE}
      - SSL_TYPE=${SSL_TYPE}
      - SSL_CERT_PATH=${SSL_CERT_PATH}
      - SSL_KEY_PATH=${SSL_KEY_PATH}
      - SPOOF_PROTECTION=${SPOOF_PROTECTION}
      - ENABLE_QUOTAS=${ENABLE_QUOTAS}
      - POSTFIX_MESSAGE_SIZE_LIMIT=${POSTFIX_MESSAGE_SIZE_LIMIT}
      - CLAMAV_MESSAGE_SIZE_LIMIT=${CLAMAV_MESSAGE_SIZE_LIMIT}
      - ENABLE_UPDATE_CHECK=${ENABLE_UPDATE_CHECK}
      - UPDATE_CHECK_INTERVAL=${UPDATE_CHECK_INTERVAL}
      - POSTSCREEN_ACTION=${POSTSCREEN_ACTION}
      - DOVECOT_MAILBOX_FORMAT=${DOVECOT_MAILBOX_FORMAT}
      - POSTFIX_INET_PROTOCOLS=${POSTFIX_INET_PROTOCOLS}
      - DOVECOT_INET_PROTOCOLS=${DOVECOT_INET_PROTOCOLS}
      - PFLOGSUMM_TRIGGER=${PFLOGSUMM_TRIGGER}
      - LOGWATCH_INTERVAL=${LOGWATCH_INTERVAL}
      - LOGROTATE_INTERVAL=${LOGROTATE_INTERVAL}
      - ENABLE_SPAMASSASSIN=${ENABLE_SPAMASSASSIN}
      - SPAMASSASSIN_SPAM_TO_INBOX=${SPAMASSASSIN_SPAM_TO_INBOX}
      - ENABLE_SPAMASSASSIN_KAM=${ENABLE_SPAMASSASSIN_KAM}
      - MOVE_SPAM_TO_JUNK=${MOVE_SPAM_TO_JUNK}
      - SA_TAG=${SA_TAG}
      - SA_TAG2=${SA_TAG2}
      - SA_KILL=${SA_KILL}
      - SA_SPAM_SUBJECT=${SA_SPAM_SUBJECT}
      - SA_SHORTCIRCUIT_BAYES_SPAM=${SA_SHORTCIRCUIT_BAYES_SPAM}
      - SA_SHORTCIRCUIT_BAYES_HAM=${SA_SHORTCIRCUIT_BAYES_HAM}
      - ENABLE_FETCHMAIL=${ENABLE_FETCHMAIL}
      - FETCHMAIL_POLL=${FETCHMAIL_POLL}
      - FETCHMAIL_PARALLEL=${FETCHMAIL_PARALLEL}
      - ACCOUNT_PROVISIONER=${ACCOUNT_PROVISIONER}
      - LDAP_SERVER_HOST=${LDAP_SERVER_HOST}
      - LDAP_SEARCH_BASE=${LDAP_SEARCH_BASE}
      - LDAP_BIND_DN=${LDAP_BIND_DN}
      - LDAP_BIND_PW=${LDAP_BIND_PW}
      - LDAP_QUERY_FILTER_USER=${LDAP_QUERY_FILTER_USER}
      - LDAP_QUERY_FILTER_GROUP=${LDAP_QUERY_FILTER_GROUP}
      - LDAP_QUERY_FILTER_ALIAS=${LDAP_QUERY_FILTER_ALIAS}
      - LDAP_QUERY_FILTER_DOMAIN=${LDAP_QUERY_FILTER_DOMAIN}
      - DOVECOT_DEFAULT_PASS_SCHEME=${DOVECOT_DEFAULT_PASS_SCHEME}
      - DOVECOT_LDAP_VERSION=${DOVECOT_LDAP_VERSION}
      - DOVECOT_AUTH_BIND=${DOVECOT_AUTH_BIND}
      - DOVECOT_USER_FILTER=${DOVECOT_USER_FILTER}
      - DOVECOT_USER_ATTRS=${DOVECOT_USER_ATTRS}
      - DOVECOT_PASS_ATTRS=${DOVECOT_PASS_ATTRS}
      - DOVECOT_PASS_FILTER=${DOVECOT_PASS_FILTER}
      - ENABLE_POSTGREY=${ENABLE_POSTGREY}
      - POSTGREY_DELAY=${POSTGREY_DELAY}
      - POSTGREY_MAX_AGE=${POSTGREY_MAX_AGE}
      - POSTGREY_AUTO_WHITELIST_CLIENTS=${POSTGREY_AUTO_WHITELIST_CLIENTS}
      - POSTGREY_TEXT=${POSTGREY_TEXT}
      - ENABLE_SASLAUTHD=${ENABLE_SASLAUTHD}
      - SASLAUTHD_MECHANISMS=${SASLAUTHD_MECHANISMS}
      - SASLAUTHD_MECH_OPTIONS=${SASLAUTHD_MECH_OPTIONS}
      - SRS_SENDER_CLASSES=${SRS_SENDER_CLASSES}
      - ENABLE_MANAGESIEVE=${ENABLE_MANAGESIEVE}
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    networks:
       ipv6:
         ipv6_address: xxxxx::25

networks:
  ipv6:
    external: true   


env:
LOG_LEVEL=info
ONE_DIR=1
UPDATE_CHECK_INTERVAL=1d
PERMIT_DOCKER=none
TZ=Europe/Berlin
ENABLE_AMAVIS=1
AMAVIS_LOGLEVEL=0
ENABLE_DNSBL=1
ENABLE_CLAMAV=1
ENABLE_FAIL2BAN=1
FAIL2BAN_BLOCKTYPE=reject
SSL_TYPE=manual
SPOOF_PROTECTION=1
ENABLE_QUOTAS=1
POSTFIX_MESSAGE_SIZE_LIMIT=102400000
CLAMAV_MESSAGE_SIZE_LIMIT=100M
ENABLE_UPDATE_CHECK=1
UPDATE_CHECK_INTERVAL=1d
POSTSCREEN_ACTION=enforce
DOVECOT_MAILBOX_FORMAT=maildir
POSTFIX_INET_PROTOCOLS=all
DOVECOT_INET_PROTOCOLS=all
PFLOGSUMM_TRIGGER=logrotate
LOGWATCH_INTERVAL=weekly
LOGROTATE_INTERVAL=weekly
ENABLE_SPAMASSASSIN=1
SPAMASSASSIN_SPAM_TO_INBOX=1
ENABLE_SPAMASSASSIN_KAM=1
MOVE_SPAM_TO_JUNK=1
SA_TAG=-100000
SA_TAG2=3.75
SA_KILL=100000
SA_SPAM_SUBJECT=***SPAM(_SCORE_)***
SA_SHORTCIRCUIT_BAYES_SPAM=0
SA_SHORTCIRCUIT_BAYES_HAM=0
ENABLE_FETCHMAIL=0
FETCHMAIL_POLL=300
FETCHMAIL_PARALLEL=0
ACCOUNT_PROVISIONER=LDAP
LDAP_SERVER_HOST=xxx
LDAP_SEARCH_BASE=DC=ldap,DC=xx,DC=xxx
LDAP_BIND_DN=cn=ldap-user,ou=users,DC=ldap,DC=xxx,DC=xxx
LDAP_BIND_PW=xxx
LDAP_QUERY_FILTER_USER=(&(mail=%s)(memberOf=cn=email,ou=groups,dc=ldap,dc=xxx,dc=xxx))
LDAP_QUERY_FILTER_GROUP=(&(mailGroupMember=%s)(memberOf=cn=email,ou=groups,dc=ldap,dc=xxx,dc=xxx))
LDAP_QUERY_FILTER_ALIAS=(&(mailAlias=%s)(memberOf=cn=email,ou=groups,dc=ldap,dc=xxx,dc=xxx))
LDAP_QUERY_FILTER_DOMAIN=(|(mail=*@%s)(mailalias=*@%s)(mailGroupMember=*@%s))
DOVECOT_DEFAULT_PASS_SCHEME=SHA512-CRYPT
DOVECOT_LDAP_VERSION=3
DOVECOT_AUTH_BIND=yes
DOVECOT_USER_FILTER=(&(memberOf=cn=email,ou=groups,dc=ldap,dc=xxx,dc=xxx)(mail=%u))
DOVECOT_USER_ATTRS==home=/var/mail/%d/%n,=uid=5000,=gid=5000
DOVECOT_PASS_ATTRS=mail=user,userPassword=password
DOVECOT_PASS_FILTER=(&(memberOf=cn=email,ou=groups,dc=ldap,dc=xxx,dc=xxx)(mail=%u))
ENABLE_POSTGREY=1
POSTGREY_DELAY=300
POSTGREY_MAX_AGE=60
POSTGREY_AUTO_WHITELIST_CLIENTS=3
POSTGREY_TEXT=Delayed by Postgrey
ENABLE_SASLAUTHD=0
SASLAUTHD_MECHANISMS=rimap
SASLAUTHD_MECH_OPTIONS=127.0.0.1
SRS_SENDER_CLASSES=envelope_sender,header_sender
SSL_CERT_PATH=/etc/letsencrypt/xxx.fullchain
SSL_KEY_PATH=/etc/letsencrypt/xxx.key
ENABLE_MANAGESIEVE=1
```

### 📜 Relevant log output

```Text
mail dovecot: auth: Fatal: LDAP /etc/dovecot/dovecot-ldap.conf.ext: ldap_initialize() failed with uris xxx: Bad parameter to an ldap routine

And several followup errors when emals are received (to check if user exists) or someone tries to login in dovecot.
```
