### ISSUE TITLE
bug report: User unknown in local recipient table

### ISSUE THREAD

**Issue by Eirikr70** [docker-mailserver/docker-mailserver#3679]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

A user (eric) is set and present /tmp/docker-mailserver/postfix-accounts.cf
```
eric@domain.fr|{SHA512-CRYPT}xxx.
vault@domain.fr|{SHA512-CRYPT}xxx
matrix@domain.fr|{SHA512-CRYPT}xxx
```
```
eric@vault:~/mailserver $ sudo ./setup.sh email list
* eric@domain.fr ( 5.7M / ~ ) [0%]

* vault@domain.fr ( 0 / ~ ) [0%]

* matrix@domain.fr ( 40K / ~ ) [0%]
```
But emails sent to that user are rejected

### 👟 Reproduction Steps

Send an email from sender.net to domain.fr

### 🐋 DMS Version

v13.0.1 pulled as latest

### 💻 Operating System and Architecture

Debian 12, arm64

### ⚙️ Container configuration files

```yml
version: '3.8'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: domain.fr
#    domainname: domain.fr
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
#      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
#      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - logs:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - ./docker-data/fail2ban/:/etc/fail2ban/
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
#    runtime: "runsc"

volumes:
  logs:
    external: true
```

### 📜 Relevant log output

```Text
mailserver  | Dec  3 11:19:47 domain postfix/postscreen[229006]: CONNECT from [a.a.a.a]:58449 to [b.b.b.b]:25
mailserver  | Dec  3 11:19:53 domain postfix/postscreen[229006]: PASS NEW [a.a.a.a]:58449
mailserver  | Dec  3 11:19:54 domain postfix/smtpd[229016]: connect from smtp-outgoing-2003.sender.net[a.a.a.a]
mailserver  | Dec  3 11:19:54 domain postfix/smtpd[229016]: Anonymous TLS connection established from smtp-outgoing-2003.sender.net[a.a.a.a]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange ECDHE (P-256) server-signature ECDSA (P-256) server-digest SHA256
mailserver  | Dec  3 11:19:54 domain postfix/trivial-rewrite[229019]: warning: do not list domain domain.fr in BOTH mydestination and virtual_mailbox_domains
mailserver  | Dec  3 11:19:54 domain policyd-spf[229021]: prepend Received-SPF: Pass (mailfrom) identity=mailfrom; client-ip=a.a.a.a; helo=smtp-outgoing-2003.sender.net; envelope-from=eric.xxx@sender.net; receiver=<UNKNOWN>
mailserver  | Dec  3 11:19:54 cespedes postfix/smtpd[229016]: NOQUEUE: reject: RCPT from smtp-outgoing-2003.laposte.net[a.a.a.a]: 550 5.1.1 <eric@domain.fr>: Recipient address rejected: User unknown in local recipient table; from=<eric.xxx@sender.net> to=<eric@domain.fr> proto=ESMTP helo=<smtp-outgoing-2003.sender.net>
mailserver  | Dec  3 11:19:54 domain postfix/smtpd[229016]: disconnect from smtp-outgoing-2003.sender.net[a.a.a.a] ehlo=2 starttls=1 mail=1 rcpt=0/1 rset=1 quit=1 commands=6/7
```
```


### Improvements to this form?

_No response_
