### ISSUE TITLE
bug report: [Possible bugs]: Rspamd can not sign the outbound emails

### ISSUE THREAD

**Issue by WillWang8216** [docker-mailserver/docker-mailserver#3730]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

When sending out emails, it is not dkim-signed. Rspamd failed to do so. Everything is pretty much out of the box. I did not tamper any code.

The following is my mailserver.env
```
OVERRIDE_HOSTNAME=mail.mydomain.com
DMS_DEBUG=0
LOG_LEVEL=debug
SUPERVISOR_LOGLEVEL=debug
ONE_DIR=1
DMS_VMAIL_UID=
DMS_VMAIL_GID=
ACCOUNT_PROVISIONER=
POSTMASTER_ADDRESS=
ENABLE_UPDATE_CHECK=1
UPDATE_CHECK_INTERVAL=1d
PERMIT_DOCKER=network
TZ=Asia/Taipei
NETWORK_INTERFACE=
TLS_LEVEL=
SPOOF_PROTECTION=1
ENABLE_SRS=1
ENABLE_OPENDKIM=0
ENABLE_OPENDMARC=0
ENABLE_POLICYD_SPF=0
ENABLE_POP3=
ENABLE_CLAMAV=1
ENABLE_RSPAMD=1
ENABLE_RSPAMD_REDIS=0
RSPAMD_LEARN=1
RSPAMD_CHECK_AUTHENTICATED=1
RSPAMD_GREYLISTING=1
RSPAMD_HFILTER=1
RSPAMD_HFILTER_HOSTNAME_UNKNOWN_SCORE=6
ENABLE_AMAVIS=1
AMAVIS_LOGLEVEL=0
ENABLE_DNSBL=1
ENABLE_FAIL2BAN=1
FAIL2BAN_BLOCKTYPE=reject
ENABLE_MANAGESIEVE=1
POSTSCREEN_ACTION=enforce
SMTP_ONLY=
SSL_TYPE=letsencrypt
SSL_CERT_PATH=
SSL_KEY_PATH=
SSL_ALT_CERT_PATH=
SSL_ALT_KEY_PATH=
VIRUSMAILS_DELETE_DELAY=
POSTFIX_DAGENT=
POSTFIX_MAILBOX_SIZE_LIMIT=
ENABLE_QUOTAS=1
POSTFIX_MESSAGE_SIZE_LIMIT=26000000
CLAMAV_MESSAGE_SIZE_LIMIT=
PFLOGSUMM_TRIGGER=daily_cron
PFLOGSUMM_RECIPIENT=myemail@gmail.com
PFLOGSUMM_SENDER=
LOGWATCH_INTERVAL=weekly
LOGWATCH_RECIPIENT=emailvault1993@gmail.com
LOGWATCH_SENDER=
REPORT_RECIPIENT=
REPORT_SENDER=
LOGROTATE_INTERVAL=weekly
POSTFIX_REJECT_UNKNOWN_CLIENT_HOSTNAME=1
POSTFIX_INET_PROTOCOLS=all
DOVECOT_INET_PROTOCOLS=all
ENABLE_SPAMASSASSIN=0
SPAMASSASSIN_SPAM_TO_INBOX=1
ENABLE_SPAMASSASSIN_KAM=1
MOVE_SPAM_TO_JUNK=1
MARK_SPAM_AS_READ=0
SA_TAG=-100000
SA_TAG2=3.75
SA_KILL=100000
SA_SPAM_SUBJECT=***SPAM*****
SA_SHORTCIRCUIT_BAYES_SPAM=1
ENABLE_FETCHMAIL=0
FETCHMAIL_POLL=300
ENABLE_GETMAIL=0
GETMAIL_POLL=5
LDAP_START_TLS=
LDAP_SERVER_HOST=
LDAP_SEARCH_BASE=
LDAP_BIND_DN=
LDAP_BIND_PW=
LDAP_QUERY_FILTER_USER=
LDAP_QUERY_FILTER_GROUP=
LDAP_QUERY_FILTER_ALIAS=
LDAP_QUERY_FILTER_DOMAIN=
DOVECOT_TLS=
DOVECOT_USER_FILTER=
DOVECOT_PASS_FILTER=
DOVECOT_MAILBOX_FORMAT=maildir
DOVECOT_AUTH_BIND=
ENABLE_POSTGREY=0
POSTGREY_DELAY=300
POSTGREY_MAX_AGE=35
POSTGREY_TEXT="Delayed by Postgrey"
POSTGREY_AUTO_WHITELIST_CLIENTS=5
ENABLE_SASLAUTHD=0
SASLAUTHD_MECHANISMS=pam
SASLAUTHD_MECH_OPTIONS=
SASLAUTHD_LDAP_SERVER=
SASLAUTHD_LDAP_BIND_DN=
SASLAUTHD_LDAP_PASSWORD=
SASLAUTHD_LDAP_SEARCH_BASE=
SASLAUTHD_LDAP_FILTER=
SASLAUTHD_LDAP_START_TLS=
SASLAUTHD_LDAP_TLS_CHECK_PEER=
SASLAUTHD_LDAP_TLS_CACERT_FILE=
SASLAUTHD_LDAP_TLS_CACERT_DIR=
SASLAUTHD_LDAP_PASSWORD_ATTR=
SASLAUTHD_LDAP_AUTH_METHOD=
SASLAUTHD_LDAP_MECH=
SRS_SENDER_CLASSES=envelope_sender
SRS_EXCLUDE_DOMAINS=
SRS_SECRET=
DEFAULT_RELAY_HOST=
RELAY_HOST=
RELAY_PORT=25
RELAY_USER=
RELAY_PASSWORD=
```
My dkim_signing.conf
```
enabled = true;

sign_authenticated = true;
sign_local = true;

use_domain = "header";
use_redis = false; # don't change unless Redis also provides the DKIM keys
use_esld = true;

check_pubkey = true; # you wan't to use this in the beginning

domain {
    mydomain.com {
        path = "tmp/docker-mailserver/rspamd/dkim/rsa-2048-defaultmail-mydomain.com.private.txt";
        selector = "defaultmail";
    }}
```

### 👟 Reproduction Steps

After pulling the image and creating the container with the mailserver.env variables, I then ran
`docker exec -ti <CONTAINER NAME> setup config dkim keysize 2048 selector 2021-dkim domain 'mydomain.com'` and added the record to my dns provider. However, the email sent weren't signed.

### 🐋 DMS Version

v13.0.1

### 💻 Operating System and Architecture

Linux Main-WP-Oracle424-U 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:29:11 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: mailserver/docker-mailserver:edge
    #image: mailserver/docker-mailserver@sha256:6d54113b36972d086d3af2ffef85ee808c756caaaff2cc485a6f354bd68e67a9
    #image: mailserver/docker-mailserver@sha256:aa60891530d01f7ef44f5c2ac30693a73c3d60693b5ca594b853005b2df6b145
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.mydomain.com
      #domain: mydomain.com
    dns: 1.1.1.1
    env_file: stack.env
    networks:
      - dms-ipv6
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
      - "11334:11334"  # rspamd web ui
    volumes:
      - /home/will/mailserver/docker-data/dms/mail-data/:/var/mail/
        #Rspamd redis persistence
      - /home/will/mailserver/docker-data/dms/mail-state/:/var/mail-state/
      - /home/will/mailserver/docker-data/dms/mail-logs/:/var/log/mail/
      - /home/will/mailserver/docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
        #- /home/will/mailserver/docker-data/dms/opendkim/:/tmp/docker-mailserver/opendkim/
        # Rsapmd + opendkim
      - /home/will/mailserver/docker-data/dms/config/rspamd/override.d/dkim_signing.conf:/etc/rspamd/override.d/dkim_signing.conf
        # Rspamd abusix
      - /home/will/mailserver/docker-data/dms/config/rspamd/local.d/groups.conf:/etc/rspamd/local.d/groups.conf
      - /home/will/mailserver/docker-data/dms/config/rspamd/local.d/rbl.conf:/etc/rspamd/local.d/rbl.conf
      - /home/will/mailserver/docker-data/dms/config/rspamd/rspamd.local.lua:/etc/rspamd/rspamd.local.lua
        # White lable of spf
      - /home/will/mailserver/docker-data/dms/config/postfix-policyd-spf.conf:/etc/postfix-policyd-spf-python/policyd-spf.conf
        # Mail encryption on the server
      - /home/will/mailserver/docker-data/dms/config/dovecot/10-custom.conf:/etc/dovecot/conf.d/10-custom.conf
        # Mail encrytion keys
      - /home/will/mailserver/docker-data/dms/certs:/certs
      - /home/will/mailserver/docker-data/dms/cron/sa-learn:/etc/cron.d/sa-learn

    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

networks:
  dms-ipv6:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd00:cafe:face:feed::/64
```

### 📜 Relevant log output

```Text
2023-12-28 17:34:13 #1223(rspamd_proxy) <b9c213>; proxy; dkim_module_load_key_format: cannot load dkim key tmp/docker-mailserver/rspamd/dkim/rsa-2048-defaultmail-mydomain.com.private.txt: cannot parse raw private key: error:0D06B08E:asn1 encoding routines:asn1_d2i_read_bio:not enough data
```
