### ISSUE TITLE
bug report: Catch-all ignores all existing email addresses

### ISSUE THREAD

**Issue by Dubbeldrank** [docker-mailserver/docker-mailserver#3751]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Without a catch-all every email address just operates as expected, email is delivered to the correct inboxes. As soon as i add a catch-all for a domain all email is delivered in the inbox of the email address that is linked in the catch-all. The catch all is added using setup.sh and appears in postfix-virtual.cf as expected. When i remove the catch-all email is delivered to the correct inboxes again. This is not related to this specific version of docker-mailserver, it's been behaving like this for multiple versions.

### 👟 Reproduction Steps

./setup.sh alias add @domain.tld mailbox1@domain.tld

In the logs below:
mailbox1 is the address used to recieve the email that has no existing email account on the server
mailbox2 is the email addess that has an existing email account on the server and where the test email is sent to

### 🐋 DMS Version

13.2.0

### 💻 Operating System and Architecture

Debian 12 AMD64

### ⚙️ Container configuration files

```yml
services:
  mail:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mail
    hostname: mail.domain.tld
    network_mode: bridge
    ports:
      - "25:25"
      - "587:587"
      - "993:993"
      - "4190:4190"
      - "11334:11334"
    volumes:
      - /opt/docker/mail/data/mail-data:/var/mail/
      - /opt/docker/mail/data/mail-state/:/var/mail-state/
      - /opt/docker/mail/data/mail-logs/:/var/log/mail/
      - /opt/docker/mail/config/:/tmp/docker-mailserver/
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    environment:
      - OVERRIDE_HOSTNAME=
      - DMS_DEBUG=0
      - LOG_LEVEL=info
      - SUPERVISOR_LOGLEVEL=
      - ONE_DIR=1
      - DMS_VMAIL_UID=
      - DMS_VMAIL_GID=
      - ACCOUNT_PROVISIONER=
      - POSTMASTER_ADDRESS=postmaster@domain.tld
      - ENABLE_UPDATE_CHECK=1
      - UPDATE_CHECK_INTERVAL=1d
      - PERMIT_DOCKER=none
      - TZ=Europe/Amsterdam
      - NETWORK_INTERFACE=
      - TLS_LEVEL=
      - SPOOF_PROTECTION=1
      - ENABLE_SRS=0
      - ENABLE_OPENDKIM=0
      - ENABLE_OPENDMARC=0
      - ENABLE_POLICYD_SPF=0
      - ENABLE_POP3=
      - ENABLE_IMAP=1
      - ENABLE_CLAMAV=1
      - ENABLE_RSPAMD=1
      - ENABLE_RSPAMD_REDIS=
      - RSPAMD_LEARN=1
      - RSPAMD_CHECK_AUTHENTICATED=0
      - RSPAMD_GREYLISTING=0
      - RSPAMD_HFILTER=1
      - RSPAMD_HFILTER_HOSTNAME_UNKNOWN_SCORE=6
      - ENABLE_AMAVIS=0
      - AMAVIS_LOGLEVEL=0
      - ENABLE_DNSBL=1
      - ENABLE_FAIL2BAN=1
      - FAIL2BAN_BLOCKTYPE=drop
      - ENABLE_MANAGESIEVE=1
      - POSTSCREEN_ACTION=enforce
      - SMTP_ONLY=
      - SSL_TYPE=letsencrypt
      - SSL_CERT_PATH=
      - SSL_KEY_PATH=
      - SSL_ALT_CERT_PATH=
      - SSL_ALT_KEY_PATH=
      - VIRUSMAILS_DELETE_DELAY=
      - POSTFIX_DAGENT=
      - POSTFIX_MAILBOX_SIZE_LIMIT=
      - ENABLE_QUOTAS=1
      - POSTFIX_MESSAGE_SIZE_LIMIT=102400000
      - CLAMAV_MESSAGE_SIZE_LIMIT=
      - PFLOGSUMM_TRIGGER=
      - PFLOGSUMM_RECIPIENT=
      - PFLOGSUMM_SENDER=
      - LOGWATCH_INTERVAL=
      - LOGWATCH_RECIPIENT=
      - LOGWATCH_SENDER=
      - REPORT_RECIPIENT=
      - REPORT_SENDER=
      - LOGROTATE_INTERVAL=weekly
      - POSTFIX_REJECT_UNKNOWN_CLIENT_HOSTNAME=0
      - POSTFIX_INET_PROTOCOLS=all
      - DOVECOT_INET_PROTOCOLS=all
      - ENABLE_SPAMASSASSIN=0
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_SPAMASSASSIN_KAM=0
      - MOVE_SPAM_TO_JUNK=1
      - SA_TAG=2.0
      - SA_TAG2=6.31
      - SA_KILL=10.0
      - SA_SPAM_SUBJECT=***SPAM*****
      - ENABLE_FETCHMAIL=0
      - FETCHMAIL_POLL=300
      - FETCHMAIL_PARALLEL=0
      - ENABLE_GETMAIL=0
      - GETMAIL_POLL=5
      - LDAP_START_TLS=
      - LDAP_SERVER_HOST=
      - LDAP_SEARCH_BASE=
      - LDAP_BIND_DN=
      - LDAP_BIND_PW=
      - LDAP_QUERY_FILTER_USER=
      - LDAP_QUERY_FILTER_GROUP=
      - LDAP_QUERY_FILTER_ALIAS=
      - LDAP_QUERY_FILTER_DOMAIN=
      - DOVECOT_TLS=
      - DOVECOT_USER_FILTER=
      - DOVECOT_PASS_FILTER=
      - DOVECOT_MAILBOX_FORMAT=maildir
      - DOVECOT_AUTH_BIND=
      - ENABLE_POSTGREY=0
      - POSTGREY_DELAY=300
      - POSTGREY_MAX_AGE=35
      - POSTGREY_TEXT="Delayed by Postgrey"
      - POSTGREY_AUTO_WHITELIST_CLIENTS=5
      - ENABLE_SASLAUTHD=0
      - SASLAUTHD_MECHANISMS=
      - SASLAUTHD_MECH_OPTIONS=
      - SASLAUTHD_LDAP_SERVER=
      - SASLAUTHD_LDAP_BIND_DN=
      - SASLAUTHD_LDAP_PASSWORD=
      - SASLAUTHD_LDAP_SEARCH_BASE=
      - SASLAUTHD_LDAP_FILTER=
      - SASLAUTHD_LDAP_START_TLS=
      - SASLAUTHD_LDAP_TLS_CHECK_PEER=
      - SASLAUTHD_LDAP_TLS_CACERT_FILE=
      - SASLAUTHD_LDAP_TLS_CACERT_DIR=
      - SASLAUTHD_LDAP_PASSWORD_ATTR=
      - SASLAUTHD_LDAP_AUTH_METHOD=
      - SASLAUTHD_LDAP_MECH=
      - SRS_SENDER_CLASSES=envelope_sender
      - SRS_EXCLUDE_DOMAINS=
      - SRS_SECRET=
      - DEFAULT_RELAY_HOST=
      - RELAY_HOST=
      - RELAY_PORT=25
      - RELAY_USER=
      - RELAY_PASSWORD=
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    # - SYS_PTRACE
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### 📜 Relevant log output

```Text
Jan  5 19:39:20 mail postfix/postscreen[16597]: PASS NEW [2001:4860:4864:20::35]:53339

Jan  5 19:39:20 mail postfix/smtpd[16618]: connect from mail-oa1-x35.google.com[2001:4860:4864:20::35]

Jan  5 19:39:20 mail postfix/smtpd[16618]: Anonymous TLS connection established from mail-oa1-x35.google.com[2001:4860:4864:20::35]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (2048 bits) server-digest SHA256

Jan  5 19:39:20 mail postfix/smtpd[16618]: E3327100481: client=mail-oa1-x35.google.com[2001:4860:4864:20::35]

Jan  5 19:39:20 mail postfix/cleanup[16629]: E3327100481: message-id=<CAD4OO4eH0EGDiWO6zbaVsxQy0_nVgtmbccvD7nEMAP=6E==Chw@mail.gmail.com>

Jan  5 19:39:21 mail postfix/qmgr[13264]: E3327100481: from=<sender@gmail.com>, size=2829, nrcpt=1 (queue active)

Jan  5 19:39:21 mail dovecot: lmtp(16633): Connect from local

Jan  5 19:39:21 mail dovecot: lmtp(mailbox1@domain.tld)<16633><AFCHCtlMmGX5QAAANIH7jQ>: sieve: msgid=<CAD4OO4eH0EGDiWO6zbaVsxQy0_nVgtmbccvD7nEMAP=6E==Chw@mail.gmail.com>: stored mail into mailbox 'INBOX'

Jan  5 19:39:21 mail postfix/lmtp[16631]: E3327100481: to=<mailbox1@domain.tld>, orig_to=<mailbox2@domain.tld>, relay=mail.domain.tld[/var/run/dovecot/lmtp], delay=0.33, delays=0.25/0/0/0.08, dsn=2.0.0, status=sent (250 2.0.0 <mailbox1@domain.tld> AFCHCtlMmGX5QAAANIH7jQ Saved)

Jan  5 19:39:21 mail postfix/qmgr[13264]: E3327100481: removed

Jan  5 19:39:21 mail dovecot: lmtp(16633): Disconnect from local: Logged out (state=READY)

Jan  5 19:39:21 mail postfix/smtpd[16618]: disconnect from mail-oa1-x35.google.com[2001:4860:4864:20::35] ehlo=2 starttls=1 mail=1 rcpt=1 bdat=1 quit=1 commands=7
```
