### ISSUE TITLE
bug report: apt update inside container does not work 

### ISSUE THREAD

**Issue by hanscees** [docker-mailserver/docker-mailserver#3802]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

inside the container apt update does not work. 

```console
$ apt update 

W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Could not connect to debian.map.fastlydns.net:80 (199.232.150.132), connection timed out Unable to connect to deb.debian.org:http:
W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Unable to connect to deb.debian.org:http:
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Unable to connect to deb.debian.org:http:
W: Failed to fetch http://rspamd.com/apt-stable/dists/bullseye/InRelease  Could not connect to rspamd.com:80 (135.181.136.158), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

### 👟 Reproduction Steps

do `apt update` inside container

The solution is to replace all http with https inside 

```
nano /etc/apt/sources.list
nano /etc/apt/sources.list.d/rspamd.list
```

then it does work and you can install vim.

I haven't figured out if this also gets rid of this error that keeps occurring

```
Jan 21 17:13:25 mail rspamd[1009]: <5t8s4f>; map; http_map_error: error reading http://sa-update.surbl.org/rspamd/surbl-hashbl-map.inc(78.47.239.92:80): connection with http server terminated incorrectly: IO write error: Connection timed out
 ```

### 🐋 DMS Version

v13.3.0 

### 💻 Operating System and Architecture

Description:	VMware Photon OS 4.0

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    #image: docker.io/mailserver/docker-mailserver:edge
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail
    domainname: hanscees.vet
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
      - "995:995"  # pop3 (implicit TLS)
      - "110:110"  # pop3 (implicit TLS)
    volumes:
      #- etc:/etc
      - maildata:/var/mail/
      - mailstate:/var/mail-state/
      - log:/var/log/
      - Tconfig:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ssl:/tmp/ssl
    restart: always
    stop_grace_period: 1m
    environment:
     - WHITELIST_INT_NETWORKS=192.168.0.0/24
     # If you need SSL connection, you can provide your own certificates
     - SSL_TYPE=manual
     - SSL_CERT_PATH=/tmp/ssl/fullchain.pem
     - SSL_KEY_PATH=/tmp/ssl/privkey.pem
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### 📜 Relevant log output

```Text
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Could not connect to debian.map.fastlydns.net:80 (199.232.150.132), connection timed out Unable to connect to deb.debian.org:http:
W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Unable to connect to deb.debian.org:http:
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Unable to connect to deb.debian.org:http:
W: Failed to fetch http://rspamd.com/apt-stable/dists/bullseye/InRelease  Could not connect to rspamd.com:80 (135.181.136.158), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

### Improvements to this form?

give a place to add solution
