### ISSUE TITLE
bug report: 

### ISSUE THREAD

**Issue by metzgerd** [docker-mailserver/docker-mailserver#3814]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

After the Update to the latest Version I can not send emails anymore. Thested from Thunderbird and FairMail.

I think jumped from Version 11.x to the latest Version 13.3.0 which was build 3 days ago.

I use default protocols / not overwriting the protocols:
```
smtpd_tls_mandatory_protocols = !SSLv2,!SSLv3,!TLSv1,!TLSv1.1
smtpd_tls_protocols = !SSLv2,!SSLv3,!TLSv1,!TLSv1.1
```
postfix.main.cf
```
postscreen_upstream_proxy_protocol = haproxy
mynetworks = xxx
postscreen_dnsbl_sites = zen.spamhaus.org*3 bl.mailspike.net b.barracudacentral.org*2 bl.spameatingmonkey.net dnsbl.sorbs.net psbl.surriel.com list.dnswl.org=127.0.[0..255].0*-2 list.dnswl.org=127.0.[0..255].1*-3 list.dnswl.org=127.0.[0..255].[2..3]*-4
```
I'm using HA Proxy and connecting to Port 465.

### 👟 Reproduction Steps

I think jumped from Version 11.x to the latest Version 13.3.0 which was build 3 days ago.
Update:
Version 12.1.0 ist working
Version 13.0.1 and 13.3.0 has the issue

### 🐋 DMS Version

mailserver/docker-mailserver   latest    527bc4bc1c75   3 days ago   629MB

### 💻 Operating System and Architecture

Ubuntu 20.04.6 LTS

### ⚙️ Container configuration files

```yml
version: '2'
services:
  mail:
    #image: tvial/docker-mailserver:latest
    image: docker.io/mailserver/docker-mailserver:latest
    #dns: 1.1.1.1
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
    - "465:465"
    - "4190:4190"
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - ./config/postfix-policyd-spf.conf:/etc/postfix-policyd-spf-python/policyd-spf.conf:Z
    - ./letsencrypt/:/etc/letsencrypt/:Z
    - ./maildata:/var/mail:Z
    - ./mailstate:/var/mail-state:Z
    - ./maillogs:/var/log/mail:Z
    - ./config/:/tmp/docker-mailserver/:Z
    env_file:
    - .env
    - env-mailserver
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always
```

### 📜 Relevant log output

```Text
mail    | Jan 23 09:29:44 mail postfix/submissions/smtpd[5564]: connect from unknown[10.x.x.x]
mail    | Jan 23 09:29:44 mail postfix/submissions/smtpd[5564]: SSL_accept error from unknown[10.x.x.x]: -1
mail    | Jan 23 09:29:44 mail postfix/submissions/smtpd[5564]: warning: TLS library problem: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331:
mail    | Jan 23 09:29:44 mail postfix/submissions/smtpd[5564]: lost connection after CONNECT from unknown[10.x.x.x]
mail    | Jan 23 09:29:44 mail postfix/submissions/smtpd[5564]: disconnect from unknown[10.x.x.x] commands=0/0
```
