### ISSUE TITLE
Setting `RELAY_HOST` forces expectation to provide relay credentials

### ISSUE THREAD

**Issue by cfis** [docker-mailserver/docker-mailserver#3842]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I have an internal email server that uses a postfix server I have setup on AWS as a relay. My configuration is:

```
RELAY_HOST=host.aws.com
RELAY_PORT=587
```

Notice I do not set `RELAY_USER` nor `RELAY_PASSWORD`. That is because the relay server is configured to only accept traffic  from the IP address of the internal server.

However, by setting RELAY_HOST, SMTP authentication is turned on here:

https://github.com/docker-mailserver/docker-mailserver/blob/9ac11021e1c33d87ec706f3f76b6c3197f1f000d/target/scripts/helpers/relay.sh#L165

Which is called from here:

https://github.com/docker-mailserver/docker-mailserver/blob/9ac11021e1c33d87ec706f3f76b6c3197f1f000d/target/scripts/helpers/relay.sh#L186

This code is a bit too aggressive. Instead, I it should enable SMTP authentication only if `RELAY_USER` or `RELAY_PASSWORD` are set.

### 👟 Reproduction Steps

See above.

### 🐋 DMS Version

v13.3.1

### 💻 Operating System and Architecture

Fedora 39 x64

**Comment by polarathene** [comment]
Interestingly, I was actually touching up the relay host feature docs since they needed some love. unfortunately I don't have the time to refactor the actual scripts (which definitely need work).

![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/a786ac06-a2db-4274-a72b-933444664013)

![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/8c4dbeac-b05d-4d58-a942-80dad2a6c81f)

---

In your case, without any credentials you'd want to use `main.cf` setting `relayhost` which the ENV `DEFAULT_RELAY_HOST` can handle.

`RELAY_HOST` + `RELAY_PORT` + `RELAY_USER` + `RELAY_PASSWORD` are effectively an entirely different set of ENV for specifying multiple relayhosts with credential mappings. The current implementation for that is also poor 😞

**Comment by polarathene** [comment]
> This code is a bit too aggressive. Instead, I it should enable SMTP authentication only if `RELAY_USER` or `RELAY_PASSWORD` are set.

As said, the logic is entirely written for `RELAY_HOST`, which is used to populate the `postfix-sasl-password.cf` file. `RELAY_HOST` takes only the host, and is sadly quite inflexible there, unlike `DEFAULT_RELAY_HOST` where you can specify both port and brackets or no brackets.

If you don't need the credential maps, but still need credentials you could assign `smtp_sasl_password_maps` a different table type like `inline` / `static` I think instead of a file.

**Comment by polarathene** [comment]
> I have an internal email server that uses a postfix server I have setup on AWS as a relay. My configuration is:
> 
> ```
> RELAY_HOST=host.aws.com
> RELAY_PORT=587
> ```
> 
> Notice I do not set `RELAY_USER` nor `RELAY_PASSWORD`. That is because the relay server is configured to only accept traffic from the IP address of the internal server.

Just to clarify, is this to another DMS instance on AWS? You're not using AWS SES as the relayhost right?

Port 465 would be more ideal btw, but I don't think we support that yet as a relay transport (_requires modification to `master.cf` as default inherits `smtp` transport which is configured for STARTTLS_).

**Comment by cfis** [comment]
I worked around it by adding a postfix-main.cf file to the config directory with this line:

```
smtp_sasl_auth_enable = no
```

I'll take a look at `DEFAULT_RELAY_HOST`. 

For a fix, I was thinking the `_relayhost_configure_postfix` method could be updated to first check if `RELAY_USER` and/or `RELAY_PASSWORD` are set.

The relay is not SES, it is just an ec2 instance running postfix that I have used for years (so no DMS either). Although I did take a look at SES a couple of days ago to see if that would be a better solution.

And thanks for the welcome!

**Comment by polarathene** [comment]
[`smtp_sasl_auth_enable = yes`](https://www.postfix.org/postconf.5.html#smtp_sasl_auth_enable ) should just enable the ability to use credentials but not enforce them?

I think the actual setting was one that was reliant upon that being enabled, [`smtp_sasl_security_options = noanonymous`](https://www.postfix.org/postconf.5.html#smtp_sasl_security_options).

---

So sorry about all that, I missed the settings you were referencing from the function snippet:

https://github.com/docker-mailserver/docker-mailserver/blob/4a05d7bb7caeb67347034f5280f41f2a42170410/target/scripts/helpers/relay.sh#L165-L170

https://github.com/docker-mailserver/docker-mailserver/blob/4a05d7bb7caeb67347034f5280f41f2a42170410/target/scripts/helpers/relay.sh#L180-L187

So you're absolutely right there, those are specific to credentials, and the enforcement of TLS for the connection is also related to that expectation of supplying credentials. That can totally be moved into this:

https://github.com/docker-mailserver/docker-mailserver/blob/4a05d7bb7caeb67347034f5280f41f2a42170410/target/scripts/helpers/relay.sh#L62-L68

We can't rely on only the two credentials ENV however as a separate config file also provides 1 or more relayhost credential mappings (_to support sender dependent relayhosts_):

https://github.com/docker-mailserver/docker-mailserver/blob/4a05d7bb7caeb67347034f5280f41f2a42170410/target/scripts/helpers/relay.sh#L77-L84

Whereas the ENV credentials are only for `RELAY_HOST` ENV and are appended to the same internally generated config file:

https://github.com/docker-mailserver/docker-mailserver/blob/4a05d7bb7caeb67347034f5280f41f2a42170410/target/scripts/helpers/relay.sh#L86-L89

However the logic was intentionally kept separate outside as it's own function because it's config that gets set once, and we don't tamper with it during change detection events, incase the user has modified it explicitly instead (eg: `postfix-main.cf` / `user-patches.sh`):

https://github.com/docker-mailserver/docker-mailserver/blob/4a05d7bb7caeb67347034f5280f41f2a42170410/target/scripts/helpers/relay.sh#L190-L195

**Comment by polarathene** [comment]
## Reproduction

Here's a rough Docker Compose config with three instances of DMS to demonstrate the relay support.
- I've included both:
  - The suggested `DEFAULT_RELAY_HOST` config to show that works as you want.
  - An alternative `postfix-main.cf` override that demonstrates the more common credentials config (_without any DMS `relay.sh` logic involved_).
- The first container has the relayhost configuration and you can send a test mail through `swaks` within the container.
- Observe the logs and both `dms-relay` and `dms-destination` will have responded. Although since this example lacks proper DNS `dms-destination` will reject the mail. It still demonstrates the mail was relayed correctly though 👍 

```bash
docker exec -it dms-origin swaks \
  --server localhost --from john.doe@origin.test --to jane.doe@destination.test
```

`compose.yaml`:

```yaml
services:
  # DMS configured as a relayhost
  origin:
    image: mailserver/docker-mailserver
    container_name: dms-origin
    hostname: mail.origin.test
    environment:
      # Allows for mail clients in the container to be trusted (eg: swaks)
      PERMIT_DOCKER: container
      # Just providing a relayhost for all mail to be relayed through, without any credentials:
      DEFAULT_RELAY_HOST: "[mail.relay.test]:25"
    # Lazy DNS routing for the relayhost config to resolve to the relay container:
    links:
      - "relay:mail.relay.test"
    configs:
      - source: dms-accounts-origin
        target: /tmp/docker-mailserver/postfix-accounts.cf
    # Alternative direct configuration via our override support for a relayhost with optional credentials
    #  - source: relayhost-config
    #    target: /tmp/docker-mailserver/postfix-main.cf

  # The relayhost to receive mail from DMS and deliver to the actual intended recipient:
  relay:
    image: mailserver/docker-mailserver
    container_name: dms-relay
    hostname: mail.relay.test
    environment:
      # For this example, since port 25 is public and would not usually trust relaying mail received,
      # This setting will trust our connected containers (view via command `postconf mynetworks`)
      PERMIT_DOCKER: connected-networks
    # Lazy DNS routing for the recipient address to resolve to final MTA destination:
    links:
      - "destination:destination.test"
    configs:
      - source: dms-accounts-relay
        target: /tmp/docker-mailserver/postfix-accounts.cf

  # This is the MTA that owns the original recipient mailbox (jane.doe@destination.test)
  destination:
    image: mailserver/docker-mailserver
    container_name: dms-destination
    hostname: mail.destination.test
    # Links can't be used here as the feature complains about a cylic chain
    # Thus without proper DNS, the mail will be rejected when it arrives as it can't recognize the sender domain as valid
    configs:
      - source: dms-accounts-destination
        target: /tmp/docker-mailserver/postfix-accounts.cf

# Using the Docker Compose `configs.content` feature instead of volume mounting separate files.
# NOTE: This feature requires Docker Compose v2.23.1 (Nov 2023) or newer:
# https://github.com/compose-spec/compose-spec/pull/446
configs:
  # This is roughly what the DMS relay.sh helper script should support:
  relayhost-config:
    content: |
      # Relay all outbound mail through this host:
      relayhost = [mail.relay.test]:587
      # Optional credentials support (using a static value instead of lookup table file):
      smtp_sasl_password_maps = static:origin-user@relay.test:secret
      smtp_sasl_auth_enable = yes
      smtp_sasl_security_options = noanonymous
      # If TLS was setup, you'd also probably want to ensure a secure connection:
      #smtp_tls_security_level = encrypt

  # DMS requires an account to complete setup, but otherwise not required for origin / destination containers
  # NOTE: All accounts are configured with the same `secret` password.
  dms-accounts-origin:
    # NOTE: `$` needed to be repeated to escape it,
    # which opts out of the `compose.yaml` variable interpolation feature.
    content: |
      john.doe@origin.test|{SHA512-CRYPT}$$6$$sbgFRCmQ.KWS5ryb$$EsWrlYosiadgdUOxCBHY0DQ3qFbeudDhNMqHs6jZt.8gmxUwiLVy738knqkHD4zj4amkb296HFqQ3yDq4UXt8.

  dms-accounts-relay:
    content: |
      origin-user@relay.test|{SHA512-CRYPT}$$6$$sbgFRCmQ.KWS5ryb$$EsWrlYosiadgdUOxCBHY0DQ3qFbeudDhNMqHs6jZt.8gmxUwiLVy738knqkHD4zj4amkb296HFqQ3yDq4UXt8.

  dms-accounts-destination:
    content: |
      jane.doe@destination.test|{SHA512-CRYPT}$$6$$sbgFRCmQ.KWS5ryb$$EsWrlYosiadgdUOxCBHY0DQ3qFbeudDhNMqHs6jZt.8gmxUwiLVy738knqkHD4zj4amkb296HFqQ3yDq4UXt8.
```
