### ISSUE TITLE
bug report: startup error = mailserver  | chown: cannot access '': No such file or directory

### ISSUE THREAD

**Issue by plittlefield** [docker-mailserver/docker-mailserver#3846]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Received a curious error on startup, 4th line down ...

`mailserver  | chown: cannot access '': No such file or directory`

... just after the version lines.

e.g.

```
mailserver  | [   INF   ]  Welcome to docker-mailserver v13.3.1
mailserver  | [   INF   ]  Checking configuration
mailserver  | [   INF   ]  Configuring mail server
mailserver  | chown: cannot access '': No such file or directory
mailserver  | [   INF   ]  Starting daemons
mailserver  | [   INF   ]  mail.xxxxxxxxxx.me.uk is up and running
mailserver  | Jan 29 10:14:18 mail amavis[725]: starting. /usr/sbin/amavisd-new at mail.xxxxxxxxxx.me.uk amavisd-new-2.11.1 (20181009), Unicode aware, LC_CTYPE="C.UTF-8"

```

### 👟 Reproduction Steps

```
sudo -i
cd /root/docker/mailserver/
docker compose up -d
docker compose logs
```

### 🐋 DMS Version

v13.3.1

### 💻 Operating System and Architecture

Ubuntu 22.04.3 LTS

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.xxxxxxxxxxxx.me.uk
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "0.0.0.0:25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "0.0.0.0:143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "0.0.0.0:465:465"  # ESMTP (implicit TLS)
      - "0.0.0.0:587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "0.0.0.0:993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./data/mail-data/:/var/mail/
      - ./data/mail-state/:/var/mail-state/
      - ./data/mail-logs/:/var/log/mail/
      - ./data/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /root/docker/certbot/certs/:/etc/letsencrypt
    environment:
      - TZ=Europe/London
      - SSL_TYPE=letsencrypt
      - SSL_DOMAIN=xxxxxxxxxxxx.me.uk
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### 📜 Relevant log output

```Text
mailserver  | [   INF   ]  Welcome to docker-mailserver v13.3.1
mailserver  | [   INF   ]  Checking configuration
mailserver  | [   INF   ]  Configuring mail server
mailserver  | chown: cannot access '': No such file or directory
mailserver  | [   INF   ]  Starting daemons
mailserver  | [   INF   ]  mail.xxxxxxxxxx.me.uk is up and running
mailserver  | Jan 29 10:14:18 mail amavis[725]: starting. /usr/sbin/amavisd-new at mail.xxxxxxxxxx.me.uk amavisd-new-2.11.1 (20181009), Unicode aware, LC_CTYPE="C.UTF-8"
```
