### ISSUE TITLE
bug report: SIEVE filters stop working

### ISSUE THREAD

**Issue by f0086** [docker-mailserver/docker-mailserver#3859]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

After update, my sieve filters do no longer work. The sieve files exists, but can not be accessed or be used to actually filter emails any more.

### 👟 Reproduction Steps

Accessing sieve filter files through my email client (clawsmail) results in a empty list. The log (from the email client) shows no error:

```
sieve_prefs.c:535:Read 8 Sieve config elements
[2024-01-31 00:54:27] Sieve> LISTSCRIPTS
[2024-01-31 00:54:27] Sieve< OK "Listscripts completed."
```

The files are here:
```
$....mailserver/docker-data/dms/mail-data/domain.tld/mail/sieve # ls -al
total 28
drwx------    3 104999   104999        4096 Dec 23 21:15 .
drwxr-xr-x   44 104999   104999        4096 Jan 31 00:45 ..
-rw-------    1 104999   104999         180 Mar 27  2023 beacon.sieve.sieve
-rw-------    1 104999   104999        1276 Dec 23 21:15 mailinglists.sieve.sieve
-rw-------    1 104999   104999         127 Jan  8  2023 main.sieve.sieve
-rw-------    1 104999   104999         897 Mar 27  2023 spam.sieve.sieve
drwx------    2 104999   104999        4096 Dec 23 21:15 tmp
```

The mails did not get filtered by sieve any more

### 🐋 DMS Version

v13.3.1

### 💻 Operating System and Architecture

Alpinelinux

### ⚙️ Container configuration files

```yml
version: '3.8'

services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: domain.tld
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
      - "4190:4190" # Sieve
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt/:/certs/
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    dns:
      - 1.1.1.1
      - 8.8.8.8
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```
