### ISSUE TITLE
Huge font sizes when sending from Outlook for Mac

### ISSUE THREAD

**Issue by mhspelt** [docker-mailserver/docker-mailserver#3881]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Sometimes emails get delivered where a part of the text is in a huge font, like 110 pt instead of 11.0. So far this seems to happen exclusively to some users that are using Outlook on a Mac. It seems like occasionally (not always), the dot in CSS like "font-size: 11.0pt" is getting removed.

According to [this](https://answers.microsoft.com/en-us/outlook_com/forum/all/outlook-2013-email-font-sizes-changing-after-being/698a54c5-61cd-42a9-b781-eb665d946b11) and [this](https://answers.microsoft.com/en-us/outlook_com/forum/all/giant-font-sizes-in-outlook/d50c5d8b-425f-4467-8d0e-612df723cf11) Microsoft Community topic, this usually gets caused by a misconfigured SMTP server that does "dot stuffing" or the antivirus engine.

![image](https://github.com/docker-mailserver/docker-mailserver/assets/21200417/c9500cb5-90c8-43b4-a68d-0077555fefd8)

Is this something to be fixed on the DMS image side, or something I can do in my configuration? Obviously disabling the antivirus altogether is not my preferred solution.

### 👟 Reproduction Steps

It's hard to reproduce, but it seems to occur exclusively when sending mail from Outlook on Mac. However, the outgoing emails look fine; by the time they appear in the recipient's inbox they don't. 

It only happens occasionally, my guess only when the message body is wrapped at the dot in the font size, like so
`<span style="font-size:11
.0pt;....>text</span>`

### 🐋 DMS Version

v13.3.1

### 💻 Operating System and Architecture

Ubuntu 22.04

### ⚙️ Container configuration files

```yml
mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.example.com
    env_file: /srv/docker/dms/mailserver.env
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
    volumes:
      - /var/mail:/var/mail/
      - /srv/docker/dms/state/:/var/mail-state/
      - /srv/docker/dms/logs/:/var/log/mail/
      - /srv/docker/dms/config/:/tmp/docker-mailserver/
      - /srv/docker/dms/postfix:/etc/postfix
      - /srv/docker/dms/dovecot:/etc/dovecot
      - /etc/localtime:/etc/localtime:ro
      - /srv/docker/letsencrypt/:/etc/letsencrypt:ro
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    restart: unless-stopped
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```
