### ISSUE TITLE
bug report: Improper restarts

### ISSUE THREAD

**Issue by robbertkl** [docker-mailserver/docker-mailserver#3886]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I'm doing a docker restart (e.g. `docker restart <container>` or `docker compose restart <service>`) but on startup it logs:

```
[ WARNING ]  This container was (likely) improperly restarted which can result in undefined behavior
[ WARNING ]  Please destroy the container properly and then start DMS again
```

If not this, then what would be a clean way to restart? Of course `docker compose up -d --force-recreate <service>` works, but that recreates the container, not really a restart.

Additionally, as a result of this "improper restart" I also get these errors that I don't get on normal startup:

```
mv: cannot stat '/etc/cron.d/dovecot-purge.disabled': No such file or directory
mv: cannot stat '/etc/cron.d/amavisd-new': No such file or directory
ln: failed to create symbolic link '/usr/lib/dovecot/sieve-pipe/rspamc': File exists
```

After this, is it in a messed up state? And should I recreate the container?

### 🐋 DMS Version

v13.3.1

### 💻 Operating System and Architecture

FedoraCoreOS 39 x86_64

### ⚙️ Container configuration files

```yml
  mail:
    container_name: mail
    image: mailserver/docker-mailserver
    hostname: ######
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - '25:25'
      - '465:465'
      - '587:587'
      - '993:993'
    volumes:
      - mail-data:/var/mail
      - mail-state:/var/mail-state
      - mail-logs:/var/log/mail
      - mail-config:/tmp/docker-mailserver
      - letsencrypt:/etc/letsencrypt
    environment:
      ENABLE_RSPAMD: 1
      ENABLE_FAIL2BAN: 1
      ENABLE_CLAMAV: 0
      ENABLE_OPENDMARC: 0
      ENABLE_OPENDKIM: 0
      ENABLE_POLICYD_SPF: 0
      ENABLE_AMAVIS: 0
      ENABLE_SPAMASSASSIN: 0
      ENABLE_UPDATE_CHECK: 0
      DOVECOT_MAILBOX_FORMAT: mdbox
      SSL_TYPE: letsencrypt
      SPOOF_PROTECTION: 1
      MOVE_SPAM_TO_JUNK: 1
      MARK_SPAM_AS_READ: 1
      RSPAMD_LEARN: 1
      TZ: Europe/Amsterdam
```

### 📜 Relevant log output

```Text
[   INF   ]  Starting daemons
[   INF   ]  ###### is up and running
2024-02-13 00:09:51,296 WARN received SIGTERM indicating exit request
[   INF   ]  Welcome to docker-mailserver v13.3.1
[   INF   ]  Checking configuration
[ WARNING ]  This container was (likely) improperly restarted which can result in undefined behavior
[ WARNING ]  Please destroy the container properly and then start DMS again
[   INF   ]  Configuring mail server
mv: cannot stat '/etc/cron.d/dovecot-purge.disabled': No such file or directory
mv: cannot stat '/etc/cron.d/amavisd-new': No such file or directory
ln: failed to create symbolic link '/usr/lib/dovecot/sieve-pipe/rspamc': File exists
[   INF   ]  Starting daemons
[   INF   ]  ###### is up and running
```
