### ISSUE TITLE
bug report: bug report: When The Server restarts, I need to add an email or the docker will shut down: You need at least one mail account to start Dovecot

### ISSUE THREAD

**Issue by jpsanchezl10** [docker-mailserver/docker-mailserver#3905]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

You need at least one mail account to start Dovecot (50 seconds left for acc creation before shutdown)
I have more than 6 accounts and I have to create a new account each time the server restarts.
how can I solve this?

### 👟 Reproduction Steps

Restart the server.

### 🐋 DMS Version

v13.3.1

### 💻 Operating System and Architecture

Amazon linux arm t.4g micro

### ⚙️ Container configuration files

```yml
docker compose:
`  mailserver:
    image: mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: ****
    domainname: ******.com
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "465:465"
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=0
      - ENABLE_POSTGREY=0
      - ENABLE_FAIL2BAN=1
      - FAIL2BAN_BLOCKTYPE=drop
      - ONE_DIR=1
      - TZ=America/New_York
      - ENABLE_SASLAUTHD=0
      - RELAY_HOST=smtp.sendgrid.net
      - RELAY_PORT=587
      - RELAY_USER=apikey
      - RELAY_PASSWORD=**********
      - SSL_TYPE=letsencrypt

    volumes:
      - ~/docker/mailserver/data/:/var/mail/
      - ~/docker/mailserver/state/:/var/mail-state/
      - ~/docker/mailserver/logs/:/var/log/mail/
      - ~/docker/mailserver/config/:/tmp/docker-mailserver/
      - ./docker-data/certbot/certs/:/etc/letsencrypt/:ro
    restart: always
    cap_add:
      - NET_ADMIN`
```

### 📜 Relevant log output

```Text
You need at least one mail account to start Dovecot (50 seconds left for acc creation before shutdown)
```
