### ISSUE TITLE
bug report: History of Rspamd is empty after recreate of the container

### ISSUE THREAD

**Issue by mixman68** [docker-mailserver/docker-mailserver#3910]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

History of Rspamd is empty after recreate of the container

### 👟 Reproduction Steps

Create a mail server with ENABLE_RSPAMD=1 and persistance ONE_DIR=1

Receive a mail to the instance, go to Rspamd console and see the mail in history tab

docker compose down your stack and up -d

Go to Rspamd console and see the history tab is empty

### 🐋 DMS Version

13.3.1

### 💻 Operating System and Architecture

Debian 12 Bookworm

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:13.3.1
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    domainname: redacted.fr
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - target: 25
        published: 25
        protocol: tcp
        mode: host
      - target: 143
        published: 143
        protocol: tcp
        mode: host
      - target: 465
        published: 465
        protocol: tcp
        mode: host
      - target: 587
        published: 587
        protocol: tcp
        mode: host
      - target: 993
        published: 993
        protocol: tcp
        mode: host
      - target: 11334
        published: 11334
        protocol: tcp
        mode: host
    volumes:
      - /var/local/mailserver/mail-data/:/var/mail/
      - /var/local/mailserver/mail-state/:/var/mail-state/
      - /var/local/mailserver/mail-logs/:/var/log/mail/
      - /var/local/mailserver/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/ssl/redacted/:/etc/ssl/redacted/
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
```

### 📜 Relevant log output

```Text
I don't have log of this issue, I don't know how debug it
```
