### ISSUE TITLE
bug report: Queue file write error for non local email UPDATE: IT FIXED ITSELF WITH NO INTERVENTION

### ISSUE THREAD

**Issue by jpsanchezl10** [docker-mailserver/docker-mailserver#3912]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

the server cannot write into my mailbox.
I have two servers, the first one works fine, and the second one can only receive email from local domain .
In the logs you can see the server got the mail but an error occurred.

I am able to :
Send Email to any domain ,
Receive email from local domain,
Login , etc.
I cannot:
Receive email from other domains(queue file error).

error:
` milter-reject: END-OF-MESSAGE `
and
`Queue file write error`
I'm forwarding to ports on 60,000+mail port number using Nginx:
stream
{

    server
    {
            listen 25;
            proxy_pass 10.0.4.161:60025;
    }

    server
    {
            listen 587;
            proxy_pass 10.0.4.161:60587;
    }
    server
    {
            listen 110;
            proxy_pass 10.0.4.161:60110;
    }
    server
    {
            listen 143;
            proxy_pass 10.0.4.161:60143;
    }
    server
    {
            listen 993;
            proxy_pass 10.0.4.161:60993;
    }
    server
    {
            listen 995;
            proxy_pass 10.0.4.161:60995;
    }
    server
    {
            listen 465;
            proxy_pass 10.0.4.161:60465;
    }
}

### 👟 Reproduction Steps

No rep steps

### 🐋 DMS Version

12.1.0

### 💻 Operating System and Architecture

Amazon linux arm t.4g micro

### ⚙️ Container configuration files

```yml
services:
  mailserver_conciergeai:
    image: mailserver/docker-mailserver:latest
    container_name: mailserver_conciergeai
    hostname: imap
    domainname: mydomain.com
    ports:
      - "60025:25"
      - "60587:587"
      - "60143:143"
      - "60110:110"
      - "60993:993"
      - "60995:995"
      - "60465:465"
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=0
      - ENABLE_POSTGREY=0
      - ENABLE_FAIL2BAN=1
      - FAIL2BAN_BLOCKTYPE=drop
      - ONE_DIR=1
      - TZ=America/New_York
      - ENABLE_SASLAUTHD=0
      - RELAY_HOST=smtp.sendgrid.net
      - RELAY_PORT=587
      - RELAY_USER=apikey
      - RELAY_PASSWORD=***
      - SSL_TYPE=letsencrypt

    volumes:
      - ~/docker/mailserver_conciergeai/data/:/var/mail/
      - ~/docker/mailserver_conciergeai/state/:/var/mail-state/
      - ~/docker/mailserver_conciergeai/logs/:/var/log/mail/
      - ~/docker/mailserver_conciergeai/config/:/tmp/docker-mailserver/
      - ~/docker/mailserver_conciergeai/docker-data/certbot/certs/:/etc/letsencrypt/:ro
    restart: always
    cap_add:
      - NET_ADMIN
```

### 📜 Relevant log output

```Text
`
Feb 26 18:26:31 imap opendkim[505]: 35FF6A041282: ip-10-0-4-23.us-east-2.compute.internal [10.0.4.23] not internal

Feb 26 18:26:31 imap opendkim[505]: 35FF6A041282: not authenticated

Feb 26 18:26:31 imap opendkim[505]: 35FF6A041282: DKIM verification successful

Feb 26 18:26:31 imap opendkim[505]: 35FF6A041282: s=20230601 d=gmail.com a=rsa-sha256 SSL 

Feb 26 18:26:31 imap opendmarc[514]: 35FF6A041282: gmail.com pass

Feb 26 18:26:31 imap postfix/cleanup[34851]: warning: incoming/35FF6A041282: too many reverse jump records

Feb 26 18:26:31 imap postfix/cleanup[34851]: warning: milter8_message: error reading incoming/35FF6A041282: Success

Feb 26 18:26:31 imap postfix/cleanup[34851]: 35FF6A041282: milter-reject: END-OF-MESSAGE from ip-10-0-4-23.us-east-2.compute.internal[10.0.4.23]: 4.3.0 Queue file write error; from=<myname@gmail.com> to=<myname@mydomain.com> proto=ESMTP helo=<mail-ua1-f45.google.com>`
```
