### ISSUE TITLE
bug report: TLS library problem

### ISSUE THREAD

**Issue by rafailml** [docker-mailserver/docker-mailserver#3926]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I'm trying to migrate my existing mail server to DMS on the same VPS. I'm stopping old postfix and dovecot.  Then I'm able to start docker container (docker-compose up -d), but I can't connect to my new mail server. 

### 👟 Reproduction Steps

Nothing special, just starting DMS with docker-compose up -d 
It is running, as I can see from docker ps:
```
1dbe1476c05a   ghcr.io/docker-mailserver/docker-mailserver:latest   "/usr/bin/dumb-init …"   5 minutes ago   Up 5 minutes (healthy)   0.0.0.0:25->25/tcp, :::25->25/tcp, 0.0.0.0:143->143/tcp, :::143->143/tcp, 0.0.0.0:465->465/tcp, :::465->465/tcp, 0.0.0.0:587->587/tcp, :::587->587/tcp, 110/tcp, 995/tcp, 0.0.0.0:993->993/tcp, :::993->993/tcp, 4190/tcp   mailserver
```
but **docker logs mailserver** show error. I'm posting log in log section.

When I try to use roundcube to access my email, I'm getting: 
```
IMAP Error: Login failed for user@mydomain.com against mail.mydomain.com from 172.24.0.1. Could not connect to mail.mydomain.com:143: Connection refused
```

It looks like my ports are closed but if I stop DMS (with docker-compose down) and start again old postfix and dovecot everything is OK.

### 🐋 DMS Version

13.3.1

### 💻 Operating System and Architecture

Ubuntu 22.04 server

### ⚙️ Container configuration files

```yml
mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.mydomain.com
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - '25:25' # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - '143:143' # IMAP4 (explicit TLS => STARTTLS)
      - '465:465' # ESMTP (implicit TLS)
      - '587:587' # ESMTP (explicit TLS => STARTTLS)
      - '993:993' # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### 📜 Relevant log output

```Text
[   INF   ]  Starting daemons
[  DEBUG  ]  Starting cron
[  DEBUG  ]  Starting rsyslog
[  DEBUG  ]  Starting dovecot
[  DEBUG  ]  Starting update-check
[  DEBUG  ]  Starting opendkim
[  DEBUG  ]  Starting opendmarc
[  DEBUG  ]  Starting postfix
[  DEBUG  ]  Starting fail2ban
[  DEBUG  ]  Starting amavis
[  DEBUG  ]  Starting changedetector
[   INF   ]  mail.xxx.com is up and running
Mar  4 18:11:46 mail amavis[750]: starting. /usr/sbin/amavisd-new at mail.mydomain.com amavisd-new-2.11.1 (20181009), Unicode aware, LC_CTYPE="C.UTF-8"
Mar  4 18:11:46 mail amavis[750]: perl=5.032001, user=, EUID: 110 (110);  group=, EGID: 112 112 (112 112)
Mar  4 18:11:46 mail amavis[750]: Net::Server: Group Not Defined.  Defaulting to EGID '112 112'
Mar  4 18:11:46 mail amavis[750]: Net::Server: User Not Defined.  Defaulting to EUID '110'
Mar  4 18:11:46 mail amavis[750]: No ext program for   .zoo, tried: zoo
Mar  4 18:11:46 mail amavis[750]: No ext program for   .doc, tried: ripole
Mar  4 18:11:46 mail amavis[750]: No decoder for       .F
Mar  4 18:11:46 mail amavis[750]: No decoder for       .doc
Mar  4 18:11:46 mail amavis[750]: No decoder for       .zoo

.....

connect from mydomai.com[xxx.xxx.xxx.xxx]
SSL_accept error from mydomain.com[xxx.xxx.xxx.xxx]: -1
warning: TLS library problem: error:140940F4:SSL routines:ssl3_read_bytes:unexpected message:../ssl/record/rec_layer_s3.c:1495:
lost connection after STARTTLS from mydomain.com[xxx.xxx.xxx.xxx]
disconnect from mydomain.com[xxx.xxx.xxx.xxx] ehlo=1 starttls=0/1 commands=1/2
```

**Comment by polarathene** [comment]
> `env_file: mailserver.env`

You have a config issue, this is not helpful. Neither is the full file copy/paste, please only share what you actually changed from defaults.

I assume you've configured TLS based on information from our docs, so please share how you've done so with ENV.

---

> ```
> IMAP Error: Login failed for user@mydomain.com against mail.mydomain.com from 172.24.0.1. Could not connect to mail.mydomain.com:143: Connection refused
> ```

I can see from here that you have an IP `172.24.0.1`, this is coming from outside that docker network and being routed through the gateway IP, you want to avoid that where possible.

> ```yaml
>    cap_add:
>      - NET_ADMIN
>      - SYS_PTRACE
> ```

Where are you seeing the `SYS_PTRACE`? have we still got that documented somewhere? You shouldn't need that AFAIK. Since you have `NET_ADMIN`, do you also have Fail2Ban enabled?

That's only going to cause problems for you right now, you don't want your local troubleshooting to be affected by F2B blocking your client(s) connections from failures. This will be more likely with that gateway IP issue if all clients now share the same internal IP instead of their real IP, since any failure from any client will then ban access to everyone.

**Comment by rafailml** [comment]
OK, I created new docker-compose.yaml:
```yaml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.mydomain.com
    ports:
      - '25:25' # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - '143:143' # IMAP4 (explicit TLS => STARTTLS)
      - '465:465' # ESMTP (implicit TLS)
      - '587:587' # ESMTP (explicit TLS => STARTTLS)
      - '993:993' # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    environment:
      - SSL_TYPE=letsencrypt
      - PERMIT_DOCKER=network
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=0
      - ENABLE_CLAMAV=0
      - ENABLE_SPAMASSASSIN=0
      - SPOOF_PROTECTION=0
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

Now I'm able to connect from Apple Mail, and I can read my messages, but I cannot send and receive messages.
Here is what I got in logs:
```
connect frommydomain.com[xxx.xxx.xxx.xxx]
Anonymous TLS connection established from mydomain.com[xxx.xxx.xxx.xxx]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
NOQUEUE: reject: RCPT from mydomain.com[xxx.xxx.xxx.xxx]: 554 5.7.1 <mydomain.com[xxx.xxx.xxx.xxx]>: Client host rejected: Access denied; from=<user@mydomain.com> to=<other_user@other_domain.com> proto=ESMTP helo=<smtpclient.apple>
```

If I try to log in with rouncube (which is running in other container, that's why I put PERMIT_DOCKER=network) I'm still getting:
```
IMAP Error: Login failed for user@mydomain.com against mail.mydomain.com from 172.24.0.1. Could not connect to mail.mydomain.com:143: Connection refused
```

Also I found that 
```
SSL_accept error from mydomain.com[xxx.xxx.xxx.xxx]: -1
```
