### ISSUE TITLE
[  ERROR  ]  Cannot find a valid DOMAIN for '/etc/letsencrypt/live/<DOMAIN>/', tried: '', 'mail.domain.com', 'domain.com'

### ISSUE THREAD

**Issue by arreehm** [docker-mailserver/docker-mailserver#3935]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Domain replaced with `domain.com` but it exits in `/etc/letsencrypt/live/domain.com` there are wildcard certificates that are working just fine.

I don't know what to do. Nginx is using those certificates just fine.

### 🐋 DMS Version

v13.3.1

### 💻 Operating System and Architecture

Debian 12

### ⚙️ Container configuration files

```yml
version: '3.8'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.domain.com
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      # Path should be adjusted accordingly:
      - ./docker-data/nginx-proxy/certs/:/etc/letsencrypt/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - LETSENCRYPT_DOMAIN=domain.com
      - ENABLE_FAIL2BAN=1
      # If letsencrypt for SSL/TLS certificate is used (otherwise adapt)
      - SSL_TYPE=letsencrypt
      - PERMIT_DOCKER=network
      - ONE_DIR=1
      - ENABLE_POP3=1
      - ENABLE_IMAP=1
      - ENABLE_AMAVIS=1
      - ENABLE_OPENDKIM=1
      - ENABLE_OPENDMARC
      - ENABLE_POSTGREY=1
      - ENABLE_CLAMAV=1
      - ENABLE_SPAMASSASSIN=1
      - SPOOF_PROTECTION=1
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
      - SYS_PTRACE
```

### 📜 Relevant log output

```Text
mailserver    | [   INF   ]  Welcome to docker-mailserver v13.3.1
mailserver    | [   INF   ]  Checking configuration
mailserver    | [   INF   ]  Configuring mail server
mailserver    | [  ERROR  ]  No difference after call to 'sed' in 'sedfile' (sed -i s|^postmaster_address = .*$|postmaster_address = postmaster@domain.com|g /etc/dovecot/conf.d/15-lda.conf)
mailserver    | [  ERROR  ]  No difference after call to 'sed' in 'sedfile' (sed -i -e s|#ssl = yes|ssl = yes|g /etc/dovecot/conf.d/10-master.conf)
mailserver    | [  ERROR  ]  No difference after call to 'sed' in 'sedfile' (sed -i -e s|#ssl = yes|ssl = required|g /etc/dovecot/conf.d/10-ssl.conf)
mailserver    | [  ERROR  ]  No difference after call to 'sed' in 'sedfile' (sed -i -e s|#port = 995|port = 995|g /etc/dovecot/conf.d/10-master.conf)
mailserver    | [  ERROR  ]  No difference after call to 'sed' in 'sedfile' (sed -i -e s|#port = 993|port = 993|g /etc/dovecot/conf.d/10-master.conf)
mailserver    | [  ERROR  ]  No difference after call to 'sed' in 'sedfile' (sed -i s|quota_max_mail_size =.*|quota_max_mail_size = 10M|g /etc/dovecot/conf.d/90-quota.conf)
mailserver    | [  ERROR  ]  No difference after call to 'sed' in 'sedfile' (sed -i s|quota_rule = \*:storage=.*|quota_rule = *:storage=0|g /etc/dovecot/conf.d/90-quota.conf)
mailserver    | POSTGREY_TEXT="Delayed by Postgrey"
mailserver    | [  ERROR  ]  Cannot find a valid DOMAIN for '/etc/letsencrypt/live/<DOMAIN>/', tried: '', 'mail.domain.com', 'domain.com'
mailserver    | [  ERROR  ]  _find_letsencrypt_domain | LETSENCRYPT_DOMAIN appears to be misconfigured, please verify.
mailserver    | [  ERROR  ]  Shutting down
```
