### ISSUE TITLE
Unable to Get SMTP auth to work via port 25

### ISSUE THREAD

**Issue by ShatteredSystems** [docker-mailserver/docker-mailserver#3948]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Unable to get simple SMTP authentication to work after adding an account. Only need to use port 25 from a local machine to a local machine. 

Error on Mail server:
```
mailserver  | Mar 19 10:26:36 mail postfix/postscreen[2682]: CONNECT from [172.26.0.1]:47248 to [172.26.0.2]:25
mailserver  | Mar 19 10:26:36 mail postfix/postscreen[2682]: PASS OLD [172.26.0.1]:47248
mailserver  | Mar 19 10:26:36 mail postfix/smtpd[2683]: warning: hostname otherServer does not resolve to address 172.26.0.1
mailserver  | Mar 19 10:26:36 mail postfix/smtpd[2683]: connect from unknown[172.26.0.1]
mailserver  | Mar 19 10:26:36 mail postfix/smtpd[2683]: disconnect from unknown[172.26.0.1] ehlo=1 quit=1 commands=2
```

Error on Machine trying to connect:

```
SMTP Server Port
25
Verify security certificate
Verify
Test Error
Connection: opening to 127.0.0.1:25, timeout=300, options=array (
  'ssl' => 
  array (
    'verify_peer' => false,
    'verify_peer_name' => false,
    'allow_self_signed' => true,
  ),
)
Connection: opened
SMTP INBOUND: "220 mail.example.com ESMTP"
SERVER -> CLIENT: 220 mail.example.com ESMTP

CLIENT -> SERVER: EHLO 192.168.10.254

SMTP INBOUND: "250-mail.example.com"
SMTP INBOUND: "250-PIPELINING"
SMTP INBOUND: "250-SIZE 10240000"
SMTP INBOUND: "250-ETRN"
SMTP INBOUND: "250-ENHANCEDSTATUSCODES"
SMTP INBOUND: "250-8BITMIME"
SMTP INBOUND: "250 CHUNKING"
SERVER -> CLIENT: 250-mail.example.com
250-PIPELINING
250-SIZE 10240000
250-ETRN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 CHUNKING

SMTP Error: Could not authenticate.
CLIENT -> SERVER: QUIT

SMTP INBOUND: "221 2.0.0 Bye"
SERVER -> CLIENT: 221 2.0.0 Bye

Connection: closed
SMTP Error: Could not authenticate.
```

Adding it to the local hosts file does get rid of the unknown error but the same error without being able to authenticate happens.

Confirmed users in `data/dms/config/postfix-accounts.cf`

Actually look like the documentation example: `user1@example.com|{SHA512-CRYPT}$6$2YpW1nYtPBs2yLYS$z.5PGH1OEzsHHNhl3gJrc3D.YMZkvKw/vp.r5WIiwya6z7P/CQ9GDEJDr2G2V0cAfjDFeAQPUoopsuWPXLk3u1`

### 🐋 DMS Version

13.3.1

### 💻 Operating System and Architecture

Ubuntu 22.04.4 LTS

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.example.com
    domainname: example.com
    ports:
      - "25:25"
      #- "465:465"
      #- "587:587"
      #- "993:993"
    volumes:
      #- /opt/docker-data/dms/mail-data/:/var/mail/
      #- /opt/docker-data/dms/mail-state/:/var/mail-state/
      #- /opt/docker-data/dms/mail-logs/:/var/log/mail/
      #- /opt/docker-data/dms/config/:/tmp/docker-mailserver/
      #- /etc/localtime:/etc/localtime:ro
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      #- ENABLE_RSPAMD=0
      #- ENABLE_CLAMAV=0
      #- ENABLE_FAIL2BAN=0
      #- PERMIT_DOCKER=none
      #- SPOOF_PROTECTION=0
      #- DEFAULT_RELAY_HOST=[1.1.1.1]:25
      #- RELAY_HOST=1.1.1.1
      #- RELAY_PORT=25
      #- RELAY_USER=[]
      #- RELAY_PASSWORD=[]
      - ENABLE_SMTP_AUTH=true
      - smtpd_sasl_auth_enable=yes
      - SMTP_ONLY=1
      - DMS_DEBUG=1
      - LOG_LEVEL=debug
    #cap_add:
    #  - NET_ADMIN # For Fail2Ban to work
    restart: always
```
