### ISSUE TITLE
Feature request: Replace Redis

### ISSUE THREAD

**Issue by Zepmann** [docker-mailserver/docker-mailserver#4001]
### Context

Docker Mailserver uses Redis. Redis [screwed around](https://redis.com/blog/redis-adopts-dual-source-available-licensing/) with their license. Redis was originally licensed exclusively under the BSD-3 license, which is quite compatible with Docker Mailserver's MIT license. However, I believe that their [new license](https://github.com/redis/redis?tab=License-1-ov-file) is less compatible, and does not align with the values of the community that contributes to DMS.

### Description

For the short term I would not change anything, since Redis still works and [the way DMS includes Redis relies on standard Debian packages](https://github.com/docker-mailserver/docker-mailserver/blob/master/target/scripts/build/packages.sh#L178). The currently used Debian version does not offer an alternative yet, I believe. Ideally we will also not use community packages. While I am reluctant to continue to use Redis due to the questionable license (for now a "soft" concern), I am even more reluctant for the risk that stuff breaks (a "hard" concern). :wink:

[Valkey](https://github.com/valkey-io/valkey) is a drop-in replacement for Redis [developed and maintained by the Linux Foundation](https://www.linuxfoundation.org/press/linux-foundation-launches-open-source-valkey-community). It [uses the BSD-3 license](https://github.com/valkey-io/valkey?tab=License-1-ov-file) as Redis once used to. I expect that Valkey will be available in the future in Debian's repositories. Once it does, I expect that the pull request to replace Redis with Valkey will be relatively small.

If there would be a roadmap, I would suggest to add this to it. Otherwise, is it an idea to keep this issue open?

### Alternatives

* Keep using Redis. I would not recommend this. Many open source projects are switching to alternatives, which shows that such one-sided license changes are frowned upon.
* There are some other drop-in alternatives to Redis being developed as well. For now I expect Valkey to be the best drop-in replacement in the future since it is backed by the Linux Foundation. It's fine if another replacement is a better fit if my expectation is wrong, of course.

### Applicable Users

The entire community, including users and contributors.

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute?

If no one else is interested in implementing this, I'll be happy to make an attempt. To keep changes and maintenance to a minimum, I will wait until Debian includes Valkey or another drop-in alternative.

**Comment by polarathene** [comment]
I'm aware of the recent events, but I'd like to wait for things to settle first.

Either Redis will realize their mistake and address the issue, or a fork will establish itself as the replacement over time. I've seen this back and forth with various other well established projects in the past too, and sometimes within 1-2 years it circles back to the original project.

v14 will upgrade to Debian Bookworm. Perhaps that releases backports repo will get valkey, or you'll need to wait until a future Debian release introduces the packages. We're still waiting on Dovecot upgrade too IIRC, which Dovecot maintainers have been reluctant to push for Bookworm until they make a new release last I checked.

Generally we prefer to minimize the use of community repos to get new packages as they sometimes introduce maintenance burdens (_in the past we've had this with Dovecot community builds and plugins/extensions becoming out of sync requiring us to build them ourselves_).

**Comment by Zepmann** [comment]
@polarathene 

> Either Redis will realize their mistake and address the issue, or a fork will establish itself as the replacement over time. I've seen this back and forth with various other well established projects in the past too, and sometimes within 1-2 years it circles back to the original project.

True. A good approach in the meantime is to not remove support for Redis even if an alternative is available. Just make something like Valkey the default and offer Redis as an (unsupported, so no additional testing needed) alternative.

> We're still waiting on Dovecot upgrade too IIRC, which Dovecot maintainers have been reluctant to push for Bookworm until they make a new release last I checked.

Correct. Dovecot's community repo will only host 2.4 for Bookworm. For that 2.4 neeeds to be released. I haven't seen a date for that yet. In the meantime we need to stick with 2.3 and accept a minor downgrade.

> Generally we prefer to minimize the use of community repos to get new packages as they sometimes introduce maintenance burdens

Another problem (unrelated to this issue) is ARM, which is not supported by Dovecot's repositories. The gap between versions will grow larger if Dovecot does provide ARM packages and if we don't get them from somewhere else. Otherwise just stick with whatever is stable and secure.

> That said. DMS does support using an external Redis instance AFAIK, so if any changes are needed to adapt that to Valkey or similar, we'd be open to contributions there. That would be the advised approach to using an alternative to Redis for now, while the packaged redis service would be still in our container image, it wouldn't be run which should be acceptable?

I am aware. As I wrote, it is a "soft" concern for now. Ideally I host my entire mail stack including its dependencies from a single project. Technical stability for mail is very important to me, so a "hard" concern always gets higher priority. That is why I suggest for now to do nothing. I just opened this issue to make it easy to refer to and fix the moment it is convenient.

I do not expect that any changes to DMS are required to use an external instance of Valkey as a drop-in replacement. I agree that this is likely a viable workaround for now, but it does not solve this issue. This issue is not only relevant for a single instance, but for the project and the community as a whole. I think it is important to take a stand against anyone who decides to singlehandedly change the legal and social contract under which the community operates. Today it is Redis, tomorrow it is another dependency.

Now I am not saying that we have to make every upstream dependency soft and easy to replace. However, I do think it pays off to keep track of issues and go with the flow of the community concerning drop-in replacements that exclusively operate under the licenses that we like. 😃

**Comment by georglauterbach** [comment]
I'm also all for replacing Redis due to their recent "changes"... it's a shame really. I agree with what's been said already, and we will wait a bit. This issue has been marked appropriately already - it won't be closed automatically.

**Comment by georglauterbach** [comment]
I have personally now made the switch to Valkey for all of my services in my private infrastructure that were using Redis before. I can confidently say that everything works flawlessly and as expected.

My stance: We can go forward with this.

**Comment by Zepmann** [comment]
I share your opinion, @georglauterbach. However, incorporating support for Valkey in DMS seems to not be worth the trouble at the moment. At the time of writing, Debian and Ubuntu packages are not available through official repositories. At risk of speaking out of turn since I am only a contributor: A guideline for DMS is that community repositories are not used. In order of preference (where a discussion could be had to swap positions 1 and 2, but for Valkey right now it is irrelevant):

1. The original project provides up-to-date Debian stable packages for all architectures that DMS supports. DMS supports amd64 and arm64 as far as I am aware. Valkey does not provide any Debian packages.
2. Debian stable provides packages for all architectures that DMS supports. These will likely be older, but (as the name of the repository implies) stable and supported. Debian currently does not offer Valkey.
3. Community repositories provide up-to-date Debian stable packages for all architectures that DMS supports. There [is a community repository for Valkey](https://www.percona.com/blog/new-valkey-packages-by-percona/), but I advise against using this due to problems in the past related to the use of such repositories.

But not all hope is lost! A maintainer of Valkey expects that it will be available through official repositories at some point in the future. See [this discussion](https://github.com/orgs/valkey-io/discussions/629). While I am very eager to replace Redis with Valkey, I would hate to do a lot of work when a ready-made solution exists in the future. This is especially true for more of a principle issue and not a technical issue, since Redis still works.

**Comment by georglauterbach** [comment]
I completely agree. What I meant to say was that, in case we need to decide whether we want to do it at all, I'd vote for, not against it :) You are 100% correct @Zepmann, though. No need to change anything yet; it would indeed incur unnecessary load.

I've marked it as "Accepted" in the backlog for now. Implentation has not started, and it will not start before Valkey becomes easily installable.

**Comment by avifenesh** [comment]
@Zepmann Hi, Valkey is available now in the official repository. What is the status as far as you see it?

**Comment by Zepmann** [comment]
@avifenesh 

As far as I understand, [Valkey is not yet available in Debian stable](https://packages.debian.org/search?keywords=valkey&searchon=names&suite=stable&section=all). Docker Mailserver [is based on the current Debian stable](https://github.com/docker-mailserver/docker-mailserver/blob/master/Dockerfile#L10) ("bookworm"), so a seamless transition is not yet possible.

**Comment by Zepmann** [comment]
@avifenesh 

It might be that Valley is available in backports, which I have less experience with. Does DMS already use backports? If not, I would avoid adding support for it just for this "soft" concern.

**Comment by avifenesh** [comment]
@Zepmann Yes, my bad. It's available in bookworm as backport.
And available on Debian Trixie, 13, not yet stable.

**Comment by polarathene** [comment]
> Does DMS already use backports?

No, but I'm open to that for DMS v15 if @casperklein and @georglauterbach consider it acceptable? (_**EDIT:** Seems better to wait until Debian 13?_)

This will upgrade Dovecot back to 2.3.21 that we previously had before DMS v14 from what I can see which would be nice. Although there's some risk with preferring packages from backports, thus might be better to wait until Debian 13 (Trixie) is out later this year 🤷‍♂ 

---

I don't know about switching Redis to Valkey for DMS v15. User interest is low (_based on the 👍 reactions to the request_).

We use it only for Rspamd AFAIK, and only when you choose not to use an external instance which DMS should still support.

I've not looked into this much, so I'm not sure what the friction is like for:
- Using a separate DB container is like and how that differs between Redis vs Valkey config wise.
- Switching from Redis to Valkey and if that affects the way Rspamd devs respond to support requests.
  - Their docs are littered with redis (_their docs search provides results for `redis`, nothing for `valkey`_)
  - While Valkey is a fork of Redis, compatibility may diverge from that point onwards. That is my concern, see [AWS ElastiCache comparison](https://docs.aws.amazon.com/AmazonElastiCache/latest/dg/VersionManagementConsiderations-valkey.html) which is already tracking differences.

**EDIT:** Comparison to separate image doesn't appear to require much more work. Redis vs Valkey differences change wise are minimal as shown below but I've not tried running those, nor do I have a production deployment of DMS.

## Request for interested users - Trial run DMS with Valkey

[DMS Rspamd with internal Redis (default)](https://docker-mailserver.github.io/docker-mailserver/v14.0/config/security/rspamd/#persistence-with-redis) docs are light (_I don't think I was quite confident with the redis config, I have a [task to review redis config](https://github.com/docker-mailserver/docker-mailserver/issues/3855) if anyone has input for that_), the linked page does direct users to the ENV [`ENABLE_RSPAMD_REDIS=0`](https://docker-mailserver.github.io/docker-mailserver/v14.0/config/environment/#enable_rspamd_redis) for configuring an external Redis:

> ![Image](https://github.com/user-attachments/assets/10c27a0d-281a-4de5-95f0-ed197735f8d2)

Apologies if it's been covered earlier in this discussion thread, but has someone tried Valkey that way?

The docs quoted above leave out service configuration (_[DMS does this at runtime for Redis config adjustments](https://github.com/docker-mailserver/docker-mailserver/blob/83bfe72d489beda875717130eba9b348218f3bda/target/scripts/startup/setup.d/security/rspamd.sh#L119-L156)_), our persistence support is implicit through the installed package defaults (**NOTE:** Debian default redis config differs from upstream_), an official Valkey/Redis image may behave a bit differently as a result.

---

### Custom DMS build

As our support for running Redis within DMS appears to be rather minimal, you should be able to test Valkey with the following (_similar to [our Dovecot Solr guide](https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/dovecot-solr/#composeyaml) which Valkey seems to fall into the same support policy for the time being_):

```yaml
# Modify onto your `compose.yaml` DMS service accordingly, or use this as `compose.override.yaml`:

services:
  dms:
    # The `image` setting now represents the tag for the local build configured below:
    image: localhost/dms:latest
    # Local build (no need to try pull `image` remotely), adjust `pull_policy`:
    # NOTE: Adds some extra noise when bringing the container up each time:
    # https://github.com/docker/compose/issues/12462
    pull_policy: build
    build:
      dockerfile_inline: |
        FROM docker.io/mailserver/docker-mailserver:latest
        RUN <<HEREDOC
          # Add the backports repo:
          echo 'deb https://deb.debian.org/debian bookworm-backports main' > /etc/apt/sources.list.d/bookworm-backports.list

          # Install valkey (backports repo will be used since no package exists on main):
          RUN apt-get -qq update && apt-get -qq install valkey

          # Quick workaround (replace the configured `redis-server` command with `valkey-server`):
          # NOTE: This will still use the DMS modified redis config, compatibility is assumed.
          sed -i -r 's|^(command=)redis(-server.*)|\1valkey\2|' /etc/supervisor/conf.d/dms-services.conf
        HEREDOC
```

Custom build:
- Add the [Debian Bookworm backports repo](https://backports.debian.org/Instructions/) + install Valkey package.
- Retrofit the [existing `rspamd-redis` supervisor service](https://github.com/docker-mailserver/docker-mailserver/blob/v14.0.0/target/supervisor/conf.d/dms-services.conf#L115) in DMS to run Valkey instead of Redis.

The backports repo will only install the package when it's not provided by another, otherwise it needs to be explicitly requested with `package-name/bookworm-backports` or via `-t` (_also ensures any deps from the backports is installed, replacing any existing ones on system_), either could be bring incompatibilities though according to the backports doc link.

### Separate image

Alternatively with a separate [Valkey image](https://hub.docker.com/r/valkey/valkey/) (not tested):

```yaml
# Modify onto your `compose.yaml` DMS service accordingly, or use this as `compose.override.yaml`:

services:
  # https://hub.docker.com/r/valkey/valkey/
  valkey:
    image: docker.io/valkey/valkey:8.0
    # Assign a predictable FQDN to the default bridge network Compose will create.
    # Other containers in the network can access this, no need to expose ports publicly.
    hostname: valkey.example.test
    # Mount a data volume or the container will unfortunately use an anonymous volume implicitly:
    # https://github.com/valkey-io/valkey-container/blob/ae6141ea5d62c775b8bdb9be7396b951da435673/8.0/debian/Dockerfile#L107-L114
    volumes:
      - db-valkey:/data

  dms:
    environment:
      ENABLE_RSPAMD_REDIS: 0
    configs:
      - source: rspamd-db-config
        target: /etc/rspamd/local.d/redis.conf

configs:
  rspamd-db-config:
    content: |
      servers = "valkey.example.test:6379";
      expand_keys = true;
```

Port 6379 is default as is `valkey-server` as the command ([`Dockerfile`](https://github.com/valkey-io/valkey-container/blob/ae6141ea5d62c775b8bdb9be7396b951da435673/8.0/debian/Dockerfile#L107-L114)), at a glance nothing else should be required for DMS integration, but you might want to verify the disk persistence.

---

## Conclusion

Redis naming replacement aside, there is much to change regarding the DMS integration for Redis:

https://github.com/docker-mailserver/docker-mailserver/blob/eb165ded65859794bbeca66e529a3466ceee298b/target/scripts/startup/setup.d/mail_state.sh#L29

https://github.com/docker-mailserver/docker-mailserver/blob/eb165ded65859794bbeca66e529a3466ceee298b/target/scripts/startup/setup.d/mail_state.sh#L98

https://github.com/docker-mailserver/docker-mailserver/blob/eb165ded65859794bbeca66e529a3466ceee298b/target/supervisor/conf.d/dms-services.conf#L115

Probably better to wait until the package doesn't depend on backports, but you're welcome to test with the above examples and let us know when Debian 13 releases how Valkey has been working out for you since 😎
