### ISSUE TITLE
bug report: SSL from letsn encrypt ACME-companion fail to send TLS mail 

### ISSUE THREAD

**Issue by kawaegle** [docker-mailserver/docker-mailserver#4006]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I follow the setup guide and I try to setup the SSL using letsencrypt and the ACME docker proxy as on [this link](https://docker-mailserver.github.io/docker-mailserver/edge/config/security/ssl/#example-using-nginx-proxy-and-acme-companion-with-docker-compose)

but Gmail return me that the TLS is not activated 

I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance. * but maybe i'm just too dumb and as I don't know exactly what to search I don't find any issue that fit my case 
> SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself.

as this quote it's mostly just my fault

### 👟 Reproduction Steps

start SSL docker compose and after the docker mail server compose

the path of the SSL certs are one level below inside a folder for SSL named 01-SSL and certs was on a volume but I didn't find how to bind an already existing volume to another docker compose so I use a bind volume from the folder certs of ACME companion

once done just create a user setup thunderbird or any other mail client and send a mail to a gmail address and the gmail TLS is shown as broken

[From the doc](https://docker-mailserver.github.io/docker-mailserver/edge/config/security/ssl/#testing-a-certificate-is-valid) we can test if SSL is valid using 
```sh  
openssl s_client   -connect mail.oppaiweeb.tech:25   -starttls smtp   -CApath /etc/ssl/certs/
```

and it return from my laptop 
``` 
Connecting to 64:ff9b::bca5:d836
CONNECTED(00000003)
Didn't find STARTTLS in server response, trying anyway...
40B76307B9770000:error:0A00010B:SSL routines:tls_validate_record_header:wrong version number:ssl/record/methods/tlsany_meth.c:80:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 201 bytes and written 360 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
This TLS version forbids renegotiation.
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

directly from the docker 
```sh
CONNECTED(00000003)
Didn't find STARTTLS in server response, trying anyway...
140587279734080:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 201 bytes and written 344 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0
```

and using this command

on my laptop
```sh
Connecting to 64:ff9b::bca5:d836
CONNECTED(00000003)
depth=0 CN=docker-mailserver.invalid
verify error:num=18:self-signed certificate
verify return:1
depth=0 CN=docker-mailserver.invalid
verify return:1
---
Certificate chain
 0 s:CN=docker-mailserver.invalid
   i:CN=docker-mailserver.invalid
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jan 13 08:38:15 2024 GMT; NotAfter: Jan 10 08:38:15 2034 GMT
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDCTCCAfGgAwIBAgIUaHldLHfWRSgahBjIdX0ZdlTEwpwwDQYJKoZIhvcNAQEL
BQAwJDEiMCAGA1UEAwwZZG9ja2VyLW1haWxzZXJ2ZXIuaW52YWxpZDAeFw0yNDAx
MTMwODM4MTVaFw0zNDAxMTAwODM4MTVaMCQxIjAgBgNVBAMMGWRvY2tlci1tYWls
c2VydmVyLmludmFsaWQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDq
cpSmP1w6u5WWhzPB3jJ5Fcb8AKt40pDbCKk+y0wFook2jZgfgXyOhsgEhKfafxA8
ubw6OkRjDprv8vZP3aalWPW+7q+hm4W1QjOOrjXzAXCkGWxTG7Ga3hz9ljOQbSSw
0Z+vgY8X6BZ3j+aq+VgkGGdQZsDHQNgMwXLBn+pzTYBeShAEH/doG1MNyEzcUU0v
FOTMn8f4keeov8hRbpARUJx71sQK9K8zc2RihrvFmcUdkp7F+pCCvD4nPGMncje4
MLUoE/hC1KvvGbJJcUX3NHLWWr66+731xD+exq0+tE8A6fPwBhswTVDN9gkEJQi3
SzwbzHi+NixxN034tlAdAgMBAAGjMzAxMAkGA1UdEwQCMAAwJAYDVR0RBB0wG4IZ
ZG9ja2VyLW1haWxzZXJ2ZXIuaW52YWxpZDANBgkqhkiG9w0BAQsFAAOCAQEAy4p9
39CfN9VQ3PjLLEp1FZuj7rxdN9ByKb6lNk+9UznKPhCP8JYIqlEOhSzlrMqPqqiQ
Kgv+HeUCTu0DF4yW5PnWlfqksF+eu6ftNBlmf6bZ3HUJRYN09ZCTBUvKDO+7TQWG
S0m/g5b1QGGbPpvDuZo+XG+n1Yq7pdJB5HGbxEHj2KJ9MX3QvFsIXipXXO8zN1K+
aHffRS6i4bw/pfwdz+PRUuhRM/CxLCBH/I3cIukXbDYtfjtPXOj0bx81VNgXqszj
5KjIVGpoUFRuyfNKW+TOnCk4aY0LT2bt8OS6ppUNT2iC8n1jPHaAhg7EPbvHwReE
37gWM5RQpxsPaW1R2A==
-----END CERTIFICATE-----
subject=CN=docker-mailserver.invalid
issuer=CN=docker-mailserver.invalid
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1337 bytes and written 407 bytes
Verification error: self-signed certificate
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
This TLS version forbids renegotiation.
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 18 (self-signed certificate)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 1930569EE07911B4DEF117EA0E8F9BAAB0E2F222B243C43643B41FF76F8C252C
    Session-ID-ctx:
    Resumption PSK: F0FA01FC976BDE9F15431E4E90D85448DB2770B6EA40974EC44220803A089B04130CB9408A104F59761675D334FDD3DB
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - 0e b4 73 d2 e6 22 10 bd-b7 3a a5 5d 1b 2c 17 85   ..s.."...:.].,..
    0010 - 4a 65 1c b2 3c 70 96 65-c1 a3 49 8f 2c de d6 d8   Je..<p.e..I.,...
    0020 - 9b 30 81 8d a2 51 6f 5c-21 3c d0 28 7d 31 3d 14   .0...Qo\!<.(}1=.
    0030 - 7f d5 a3 40 5f 61 8c e6-80 b3 a9 c1 d6 51 bb 68   ...@_a.......Q.h
    0040 - 4e dc 36 3e 43 9d 79 1d-f5 5a 21 91 41 51 03 d4   N.6>C.y..Z!.AQ..
    0050 - 0f 5d a7 f4 31 46 e8 4f-65 1b 85 f3 a7 d6 a2 b1   .]..1F.Oe.......
    0060 - 87 b5 4c 2b 46 a7 51 c4-3c 60 9f 9b 0f 3c 37 20   ..L+F.Q.<`...<7
    0070 - 97 4f 45 2c d9 bf 16 ba-79 63 19 27 7c 9b 08 82   .OE,....yc.'|...
    0080 - b9 1d c5 68 aa e5 8a d4-a1 46 7f ec 6c 4d 6c 68   ...h.....F..lMlh
    0090 - ab 53 c0 a9 0e 97 f8 5d-a7 10 14 b5 84 f6 88 d5   .S.....]........
    00a0 - ac b4 36 51 1a 9c c0 14-b1 14 e3 5e 0c ed cd 65   ..6Q.......^...e
    00b0 - 97 4b 05 4f ad d7 e6 4f-f3 86 3e 51 84 be d3 b0   .K.O...O..>Q....
    00c0 - 6a ef 0b 99 85 df db b9-2d 93 16 8a af 5a 1a cc   j.......-....Z..

    Start Time: 1715013876
    Timeout   : 7200 (sec)
    Verify return code: 18 (self-signed certificate)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK

```

on the docker 
```sh
root@mail:/# openssl s_client   -servername mail.oppaiweeb.tech   -connect mail.oppaiweeb.tech:465
CONNECTED(00000003)
depth=0 CN = docker-mailserver.invalid
verify return:1
---
Certificate chain
 0 s:CN = docker-mailserver.invalid
   i:CN = docker-mailserver.invalid
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDCTCCAfGgAwIBAgIUaHldLHfWRSgahBjIdX0ZdlTEwpwwDQYJKoZIhvcNAQEL
BQAwJDEiMCAGA1UEAwwZZG9ja2VyLW1haWxzZXJ2ZXIuaW52YWxpZDAeFw0yNDAx
MTMwODM4MTVaFw0zNDAxMTAwODM4MTVaMCQxIjAgBgNVBAMMGWRvY2tlci1tYWls
c2VydmVyLmludmFsaWQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDq
cpSmP1w6u5WWhzPB3jJ5Fcb8AKt40pDbCKk+y0wFook2jZgfgXyOhsgEhKfafxA8
ubw6OkRjDprv8vZP3aalWPW+7q+hm4W1QjOOrjXzAXCkGWxTG7Ga3hz9ljOQbSSw
0Z+vgY8X6BZ3j+aq+VgkGGdQZsDHQNgMwXLBn+pzTYBeShAEH/doG1MNyEzcUU0v
FOTMn8f4keeov8hRbpARUJx71sQK9K8zc2RihrvFmcUdkp7F+pCCvD4nPGMncje4
MLUoE/hC1KvvGbJJcUX3NHLWWr66+731xD+exq0+tE8A6fPwBhswTVDN9gkEJQi3
SzwbzHi+NixxN034tlAdAgMBAAGjMzAxMAkGA1UdEwQCMAAwJAYDVR0RBB0wG4IZ
ZG9ja2VyLW1haWxzZXJ2ZXIuaW52YWxpZDANBgkqhkiG9w0BAQsFAAOCAQEAy4p9
39CfN9VQ3PjLLEp1FZuj7rxdN9ByKb6lNk+9UznKPhCP8JYIqlEOhSzlrMqPqqiQ
Kgv+HeUCTu0DF4yW5PnWlfqksF+eu6ftNBlmf6bZ3HUJRYN09ZCTBUvKDO+7TQWG
S0m/g5b1QGGbPpvDuZo+XG+n1Yq7pdJB5HGbxEHj2KJ9MX3QvFsIXipXXO8zN1K+
aHffRS6i4bw/pfwdz+PRUuhRM/CxLCBH/I3cIukXbDYtfjtPXOj0bx81VNgXqszj
5KjIVGpoUFRuyfNKW+TOnCk4aY0LT2bt8OS6ppUNT2iC8n1jPHaAhg7EPbvHwReE
37gWM5RQpxsPaW1R2A==
-----END CERTIFICATE-----
subject=CN = docker-mailserver.invalid

issuer=CN = docker-mailserver.invalid

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1337 bytes and written 391 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: BD22D8D0A80E11591D9DA782A9F015E319E4BA76F13CCA90FB086EF330F2E42A
    Session-ID-ctx:
    Resumption PSK: 4EEFE222D8282A55C9A98EF2BA82FA6B189F607AE2256C45615B503E645CB9C0C8F000342798660564EEA02AA3240BA6
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - 0e b4 73 d2 e6 22 10 bd-b7 3a a5 5d 1b 2c 17 85   ..s.."...:.].,..
    0010 - b5 2d 97 71 3a 85 e3 1c-b4 19 50 0c 47 53 71 4a   .-.q:.....P.GSqJ
    0020 - 1c 4b 9e 5e dc 9a c9 b9-0c 30 08 a2 98 05 a4 cc   .K.^.....0......
    0030 - 7e 6d 10 f0 55 7f c9 f3-d2 39 f4 48 51 68 42 c4   ~m..U....9.HQhB.
    0040 - cb fa 38 f3 22 e7 ab 14-20 15 bd 65 ad 55 a5 b4   ..8."... ..e.U..
    0050 - cb 05 71 d6 10 54 c5 c2-eb 3a 0e 28 ff cb 7a 60   ..q..T...:.(..z`
    0060 - 8e 72 f2 bf 3f ca 2a a4-f4 57 0d 14 42 75 22 c2   .r..?.*..W..Bu".
    0070 - 10 3f 9c 56 fc 84 8d 29-98 84 3e 06 97 e6 fd 18   .?.V...)..>.....
    0080 - 67 88 f4 4c f4 b0 84 8c-65 86 1a b0 61 41 d6 9f   g..L....e...aA..
    0090 - 86 5d 13 83 7b a9 a6 6a-f4 4e 49 95 31 c1 38 b6   .]..{..j.NI.1.8.
    00a0 - 69 d8 82 f9 16 21 b3 77-3f 92 f7 6c 49 bf e5 aa   i....!.w?..lI...
    00b0 - a2 c1 33 e2 b0 11 d1 21-20 77 72 63 57 b2 54 e7   ..3....! wrcW.T.
    00c0 - 37 90 62 21 90 b6 f1 f0-c5 29 6e e2 84 ed e1 cf   7.b!.....)n.....

    Start Time: 1715013805
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
```

### 🐋 DMS Version

13.3.1

### 💻 Operating System and Architecture

debian  11 

### ⚙️ Container configuration files

```yml
-compose mail
networks:
  mail:
  ssl_mail:
    external: true

volumes:
  mail_data:
  mail_state:
  mail_logs:
  mail_config:

services:
  mail_server:
    image: mailserver/docker-mailserver:13.3.1
    container_name: mail_server
    restart: always
    volumes:
      - mail_data:/var/mail/
      - mail_state:/var/mail-state/
      - mail_logs:/var/log/mail/
      - mail_config:/tmp/docker-mailserver/
      - ./main.cf:/etc/postfix/main.cf
      - /etc/localtime:/etc/localtime:ro
      - ../01-SSL/certs/:/etc/letsencrypt/live/:ro
    environment:
      SSL_TYPE: letsencrypt
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      PERMIT_DOCKER: network
    ports:
      - "25:25"        
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    hostname: ${VIRTUAL_HOST}
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    stop_grace_period: 1m


```docker-compose SSL
networks:
  ssl:
  ssl_mail:
    external: true
  
volumes:
  nginx_conf:
  vhost:
  nginx_html:
  acme:

services:
  nginx_proxy:
    image: nginxproxy/nginx-proxy:1.3-alpine
    container_name: nginx_proxy
    restart: always
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - /run/docker.sock:/tmp/docker.sock:ro
    networks:
      - ssl
      - ssl_mail
    ports:
      - "80:80"
      - "443:443"

  acme_companion:
    image: nginxproxy/acme-companion:2.2
    container_name: nginx_proxy_acme
    restart: always
    volumes_from:
      - nginx_proxy
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=contact@mail.oppaiweeb.tech
    networks:
      - ssl
```
```


### 📜 Relevant log output

_No response_

### Improvements to this form?

_No response_
