### ISSUE TITLE
[BUG]: RSPAMD needs a password for the web interface

### ISSUE THREAD

**Issue by jiriks74** [docker-mailserver/docker-mailserver#4022]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

[The documentation says]()

> Rspamd provides a [web interface](https://rspamd.com/webui/), which contains statistics and data Rspamd collects. The interface is enabled by default and reachable on port 11334.

This doesn't mention the need to setup a custom password that is needed to get into the web interface.

The documentation also [mentions]() that DMS doesn't set a password but only provides an option to disable it altogether:

> DMS does not set a default password for the controller worker. You may want to do that yourself. In setups where you already have an authentication provider in front of the Rspamd webpage, you may want to [set the secure_ip option to "0.0.0.0/0" for the controller worker](https://docker-mailserver.github.io/docker-mailserver/latest/config/security/rspamd/#with-the-help-of-a-custom-file) to disable password authentication inside Rspamd completely.

I'll work on a PR that will ad a section to the documentation that explains how to add the password and therefore *enable* the WebUI by utilizing the custom config file but I think that this should be an option in DMS as the UI is enabled by default.

### 👟 Reproduction Steps

1. [See the docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/security/rspamd/#web-interface)
2. Open port `11334` in the container
3. Connect to the web interface
4. See password prompt
5. [See rspamd documentation](https://www.rspamd.com/webui/) to know that **must** set a password in order to be able to log in

### 🐋 DMS Version

v13.3.1

### 💻 Operating System and Architecture

Debian GNU/Linux 11 (bullseye) aarch64

### ⚙️ Container configuration files

```yml
Not relevant
```

### 📜 Relevant log output

```Text
Not relevant
```

**Comment by jiriks74** [comment]
LOL the options are wrong **and** in Portuguese! XD

**Comment by cohenchris** [comment]
I was actually messing around with this a few days ago... From what I can tell, this is not a bug with docker-mailserver, but rather the expected behavior by rspamd. In the link you posted for reproduction step #5, I don't see where it says a password _must_ be set in order to log in.

[Here's](https://github.com/rspamd/rspamd-docker/issues/27#issuecomment-1920972537) an issue about exactly this on the rspamd-docker github repo. The response: "The password is the true default, which is not allowed to be actually-used, so it must be set."

Seems as if there's not really a default password, so you either must set a new one or remove it alltogether.

**Comment by cohenchris** [comment]
That being said, I agree there should be a bit more documentation about this. I'm able to disable the password prompt as is explained in the docs, but I couldn't figure out how to set a new password.

I think there's some good value in adding a dms-specific default password (like just 'dms' or 'rspamd'?), so that if the user wants to change the password, they can just edit the existing file.

**Comment by jiriks74** [comment]
> In the link you posted for reproduction step 5, I don't see where it says a password must be set in order to log in.

Sorry it's on another site. You have to click on a link `change the default controller password` to get there. [It's here](https://www.rspamd.com/doc/tutorials/quickstart.html#setting-the-controller-password):

> Important information: the default passwords (namely, `q1` and `q2`) are BANNED, so you cannot use them in your installation. Please set the appropriate passwords before using the controller. This is done to prevent an occasional data leak caused by misconfiguration.

I've already created a PR mentioning the setup required to make the WebUI work: #4023

**Comment by polarathene** [comment]
Generally you should route your web access via a reverse proxy like Caddy, Nginx, or Traefik. This allows you to access via the browser with the standard HTTP port 80 and HTTPS port 443, along with delegating responsibility to manage certificates for any web service it routes for.

Here is an example:

```Caddyfile
# Automatically provisions a LetsEncrypt certificate for rspamd.example.com
# Routes traffic from http to https, and from https://rspamd.example.com to
# the rspamd web UI running in DMS
rspamd.example.com {
  reverse_proxy dms:11334
}
```

You can do local offline testing too, here's an example with added commentary:

```Caddyfile
# Global config settings:
{
  # Self-signed CA provisioned certs instead of default LetsEncrypt:
  local_certs
  # This SNI will be used as a fallback when direct IP is used:
  default_sni hello.test
}

# A site block for routing an incoming request to handle:
# NOTE: http:// will be implicitly redirected to https://
# That is unrelated to the https:// below, which accepts any other https address (including direct IP)
localhost, hello.test, https:// {
  # If you disable local_certs, this allows opt-in per site block:
  tls internal
  # Alternatively you can provide your own custom cert files:
  #tls /dms/certs/cert.ecdsa.pem /dms/certs/key.ecdsa.pem

  # Route to the rspamd web UI port at the `dms` container within the same network:
  reverse_proxy dms:11334
  # For simple testing without routing the connection to another service,
  # You can respond with some text instead:
  #respond "Hey there!"
}
```

Then to use this Caddy config, you would save it as `Caddyfile` and pair it with this `compose.yaml`:

```yaml
services:
  web-frontend:
    image: caddy:2.7
    container_name: reverse-proxy
    # Publish HTTP and HTTPS ports:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    # This is can be skipped if you add the caddy service to the same DMS `compose.yaml`
    networks:
      - dms-network

# Since this is a separate `compose.yaml` file,
# It needs to reference the networks of other containers to reach them:
networks:
  dms-network:
    # If you didn't create your own network and let compose implicitly handle it,
    # it will look like this, check the name via `docker network ls`
    name: dms_default
    external: true
```

There are similar projects for Docker that skip the need for managing a separate config file, and instead integrate with Docker labels, such as `nginx-proxy` and `caddy-docker-proxy`. We have an example of `nginx-proxy` in the SSL docs.

For the password portion, you can use [BasicAuth](https://caddyserver.com/docs/caddyfile/directives/basicauth), which will pop up a window asking for username and password:

```Caddyfile
rspamd.example.com {
  basicauth {
    # Username "Bob", password "hiccup"
    Bob $2a$14$Zkx19XLiW6VYouLHR5NmfOFU0z2GTNmpkT/5qqR7hx4IjWJPDhjvG
  }

  reverse_proxy dms:11334
}
```

A better approach is to use [`forward_auth`](https://caddyserver.com/docs/caddyfile/directives/forward_auth) to delegate auth to another service that manages identities and better auth mechanisms. You could also [restrict access by client IP](https://caddyserver.com/docs/caddyfile/matchers#client-ip).

A deployment may already be leveraging that, along with Caddy or similar, which makes it rather simple to support rspamd web UI, but I can understand if this is extra complexity for those that aren't familiar with this kind of setup.

---

Since that integration can vary so much, DMS doesn't try to bundle anything like that within the image. It also falls out of the focus of DMS 😅 

However by using the advice above, you could disable the rspamd password via `secure_ip` as mentioned as a way to secure access to the DMS container via the proxy (_the rspamd web UI port would not need to be published to the host, it'll only be reached via containers internally_).

Or just configure rspamd with a password if you prefer the simplicity and non-standard port for web access 👍

**Comment by jiriks74** [comment]
I don't want to bundle some config only an option for the password like: `RSPAMD_CONTROLER_PASSWORD`.

Also i don't want to set this up with a proxy. This is something that I won't use often enough to warrant exposing it to the internet. I have a VPN for this use case.

**Comment by polarathene** [comment]
> I don't want to bundle some config only an option for the password like: `RSPAMD_CONTROLER_PASSWORD`.

We're trying to avoid accepting any more ENV that effectively adjust one config line.

I understand the convenience but it was becoming a problem as more niche PRs tried to get an ENV into DMS that updated a single line of config for them. This isn't something that warrants a new ENV.

I don't see the proposed ENV being approved by maintainers (_security concerns aside since secrets leaks in a few places when using ENV_).

---

If you don't want to create a separate config file for Caddy, compose does support defining inline configs which can self contain configs in `compose.yaml`, but it'll be more verbose than a separate file with volume mount (with an extra caveat to keep in mind due to `$` in the bcrypt hash value:

```yaml
services:
  mailserver:
    image: mailserver/docker-mailserver:edge
    container_name: dms
    hostname: mail.example.test

  # Containers can connect to the ports of other containers in their network
  # without requiring them to be published to the host :)
  web:
    image: caddy:2.7
    container_name: reverse-proxy
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    ports:
      - "80:80"

configs:
  caddyfile:
    content: |
      :80 {
        # Optional: username `DMS`, password `secret`:
        # NOTE: Using this `compose.yaml` feature requires any `$` to become `$$` to prevent interpolation.
        basicauth {
          DMS $$2a$$12$$86yy9WEYnIXCyVoHmPKrCuobV/QxyPFlUz9TK3xIWeO8uyQ0vHX5W
        }

        # `dms` can be the service name, container name, or hostname
        reverse_proxy dms:11334
        #reverse_proxy mail.example.test:11334
        #reverse_proxy mailserver:11334
      }
```

Obviously the DMS config would need to updated to run the rspamd service for the web UI, but provided you have Docker Compose release from this year the above will work.

```bash
# Run it and visit `http://localhost` in the browser:
docker compose up
```

---

> Also i don't want to set this up with a proxy.
> This is something that I won't use often enough to warrant exposing it to the internet. I have a VPN for this use case.

As my example from my previous response stated you do not need to expose anything to the internet.

All that changes is the port you'd access directly on the DMS container (11334) would instead be connected indirectly through a separate container on port 80/443, but you don't need to type the port.

The config above is very simple for local use, no HTTPS/certs (_The `:80 { ... }` ensures that, otherwise you'd need `local_certs`, [`auto_https disable`](https://caddyserver.com/docs/automatic-https), or similar_), just visit `http://localhost` instead of appending `:11334` and you're good to go!

Having `http://rspamd.localhost` / `http://rspamd.example.test` or similar can be supported via simple DNS config, or via Caddyfile `http://localhost/rspamd` is possible should you want to later serve more web services locally (_or just stick to custom ports, which Caddy can likewise manage better_).

---

No worries if you want to avoid all that (_despite being copy/paste simple_), if you prefer to manage a password via rspamd config and access via port 11334 that's fine too 👍
