### ISSUE TITLE
bug report: postconf: fatal: -P option requires service_name[/type[/parameter]]

### ISSUE THREAD

**Issue by ghnp5** [docker-mailserver/docker-mailserver#4049]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I'm seeing this in the logs:

> postconf: fatal: -P option requires service_name[/type[/parameter]]

### 👟 Reproduction Steps

```
# docker compose pull
# docker compose down mailserver
[+] Running 2/2
 ✔ Container mailserver        Removed                            
# docker compose up -d
[+] Running 2/2
 ✔ Container mailserver               Started        
```

### 🐋 DMS Version

v14.0.0

### 💻 Operating System and Architecture

AlmaLinux 9

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: mailserver
    restart: always
    stop_grace_period: 1m
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS => SSL/TLS)
      - "993:993"  # IMAP4 (implicit TLS => SSL/TLS)
      - "127.0.0.1:11334:11334" # rspamd
    volumes:
      - ...:/var/mail
      - ...:/var/mail-state
      - ...:/var/log/mail
      - ...:/var/mail-ms-certs:ro
      - ./config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
      - mailserver.env
    dns:
      - 9.9.9.9
      - 8.8.8.8
      - 1.1.1.1
      - 1.0.0.1
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
#   fatal: unable to determine open file limit
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000


---------------

postfix-main.cf:

postscreen_dnsbl_sites = 

mynetworks = 127.0.0.0/8 [::1]/128 [fe80::]/64 172.16.0.0/12 192.168.0.0/16 10.0.0.0/8

smtpd_helo_restrictions = permit_mynetworks, permit
smtpd_sender_restrictions = reject_authenticated_sender_login_mismatch, permit_sasl_authenticated, permit_mynetworks
```

### 📜 Relevant log output

```Text
postalias: warning: /etc/aliases.db: duplicate entry: "root"
postconf: fatal: -P option requires service_name[/type[/parameter]]
Executing user-patches.sh...
Finished user-patches.sh...
```
