### ISSUE TITLE
bug report: When using Amazon SES as relay and Sieve configured Amazon still reports back `said: 530 Authentication required (in reply to MAIL FROM command` and won't send

### ISSUE THREAD

**Issue by dac11011** [docker-mailserver/docker-mailserver#4051]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

When using Amazon SES as relay, which works fine sending regular emails, and Sieve configured, Amazon still reports back `said: 530 Authentication required (in reply to MAIL FROM command` and won't send through Sieve.

I have an Autoresponder configured through Sieve and it won't send the mail out because it's not using Authentication properly to my relay Amazon SES.

```
Jun  6 15:49:11 mail postfix/smtp[2486]: Trusted TLS connection established to email-smtp.us-east-2.amazonaws.com[3.23.0.113]:25: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange ECDHE (P-256) server-signature RSA-PSS (2048 bits) server-digest SHA256
Jun  6 15:49:11 mail postfix/smtp[2486]: 65B2B1DC7BA: to=<user1@gmail.com>, relay=email-smtp.us-east-2.amazonaws.com[3.23.0.113]:25, delay=0.32, delays=0.05/0.01/0.24/0.02, dsn=5.0.0, status=bounced (host email-smtp.us-east-2.amazonaws.com[3.23.0.113] said: 530 Authentication required (in reply to MAIL FROM command))
```

However sending regular emails works fine through Amazon SES.  Do I need to configure Sieve some where to use SMTP Auth to Amazon? I've got all of the proper variables set in `.env` file:

```
DEFAULT_RELAY_HOST
RELAY_HOST
RELAY_PORT
RELAY_USER
RELAY_USERNAME
RELAY_PASSWORD
AWS_SES_USERPASS
```

Any help would be much appreciated.

### 👟 Reproduction Steps

Configure mail server to use Amazon SES as a relay, then configure Sieve.  Try to send an autoresponder email out through Sieve and it will not work.

### 🐋 DMS Version

v12.1

### 💻 Operating System and Architecture

Ubuntu 22.04

### 📜 Relevant log output

```yaml
version: '3.7'

services:
  mail:
    image: docker.io/mailserver/docker-mailserver:${IMAGE_VERSION}
    container_name: mail
    hostname: mail.domain.com
    domainname: domain.com
    restart: always
    networks:
      federated:
        ipv4_address: 172.1.1.10
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "4190:4190"
    volumes:
      - ./data/root/certs:/root/certs
      - ./data/var/mail:/var/mail/
      - ./data/var/mail-state:/var/mail-state/
      - ./data/var/log/mail:/var/log/mail/
      - ./data/tmp/docker-mailserver:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./.env
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

networks:
  network1:
    external: true
```
