### ISSUE TITLE
question: DMS upgraded to a major release implicitly via Watchtower and is broken, what should I do?

### ISSUE THREAD

**Issue by mzedeler** [docker-mailserver/docker-mailserver#4061]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

My server just pulled the latest version, which appears to be version 14, and now my log files are filling up with this:

```
mail          | 2024-06-09 17:43:09,864 WARN exited: fail2ban (exit status 255; not expected)
```
...and all mail services are down.

### 👟 Reproduction Steps

I am using v14 with the following settings:

```env
OVERRIDE_HOSTNAME=<redacted>
ENABLE_CLAMAV=1
ENABLE_SPAMASSASSIN=1
ENABLE_MANAGESIEVE=1
POSTMASTER_ADDRESS=postmaster@<redacted>
ENABLE_POSTGREY=0
ENABLE_FAIL2BAN=1
SSL_TYPE=letsencrypt
TLS_LEVEL=intermediate
POSTSCREEN_ACTION=enforce
```

(I've just noticed that the above are not necessarily the same as the ones in `docker-compose.yml` below, but I don't think it matters.

### 🐋 DMS Version

v14.0.0

### 💻 Operating System and Architecture

```
Linux mail-server 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### ⚙️ Container configuration files

```yml
version: "3"
services:
  mail:
    image: mailserver/docker-mailserver:latest
    hostname: mail
    domainname: zedeler.dk
    container_name: mail
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    ports:
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
    environment:
      - ENABLE_CLAMAV=1
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_MANAGESIEVE=1
      - POSTMASTER_ADDRESS=postmaster@zedeler.dk
      - ENABLE_POSTGREY=1
      - ENABLE_FAIL2BAN=1
      - ONE_DIR=1
      - POSTFIX_MESSAGE_SIZE_LIMIT=26000000
      - SSL_TYPE=letsencrypt
    volumes:
      - /data/mail/data:/var/mail
      - /data/mail/state:/var/mail-state
      - /etc/letsencrypt:/etc/letsencrypt
      - /data/mail/config:/tmp/docker-mailserver
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 mail
```

### 📜 Relevant log output

I tried to track this down by running fail2ban manually, and it seems to expect `/var/run/fail2ban` to exist, which it doesn't.
