### ISSUE TITLE
bug report: rsync auto learn ham not learning

### ISSUE THREAD

**Issue by danielvandenberg95** [docker-mailserver/docker-mailserver#4067]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

When moving mail to spam, in the rsync dashboard BAYES_SPAM learned increases by one. 
When moving mail out of spam into inbox or archive, BAYES_HAM does not increase. 

Not a clue where to start debugging

![Screenshot_20240615-082708](https://github.com/docker-mailserver/docker-mailserver/assets/8654023/747dcaf9-a89c-444a-a4d3-c31855af5957)

### 👟 Reproduction Steps

Wait for non-spam to arrive in spam. 
Move it out of there.

### 🐋 DMS Version

V14.0.0

### 💻 Operating System and Architecture

Alpine X86_64

### ⚙️ Container configuration files

```yml
version: '3.8'
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    networks:
      - host
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail
    domainname: me
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    #ports:
      #- "25:25"    # SMTP  (explicit TLS => STARTTLS)
      #- "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      #- "465:465"  # ESMTP (implicit TLS)
      #- "587:587"  # ESMTP (explicit TLS => STARTTLS)
    volumes:
      - /mnt/DockerData/mailserver/mail-data:/var/mail/
      - /mnt/DockerData/mailserver/mail-state:/var/mail-state/
      - /mnt/DockerData/mailserver/mail-log:/var/log/mail
      
      - /mnt/DockerData/mailserver/config:/tmp/docker-mailserver/
      - /mnt/DockerData/mailserver/config/sasl_passwd:/etc/postfix/sasl_passwd
      - /mnt/DockerData/mailserver/config/sasl_passwd.db:/etc/postfix/sasl_passwd.db
      - /etc/localtime:/etc/localtime:ro
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    #command: 
    #entrypoint: setup
    environment:
      - OVERRIDE_HOSTNAME=<<me>>
      - ENABLE_FAIL2BAN=1
      - ENABLE_RSPAMD=1
      - SA_TAG=-100000.0
      - POSTMASTER_ADDRESS=<<me>>
      - ENABLE_UPDATE_CHECK=1
      - PFLOGSUMM_TRIGGER=logrotate
      - REPORT_SENDER=<<me>>
      #- LOG_LEVEL=debug
      - POSTFIX_MESSAGE_SIZE_LIMIT=50000000
      - RSPAMD_LEARN=1
      - ENABLE_OPENDKIM=0
      - ENABLE_OPENDMARC=0
      - ENABLE_POLICYD_SPF=0
      - ENABLE_AMAVIS=0
      - ENABLE_SPAMASSASSIN=0
    deploy:
      placement:
        constraints:
          - node.hostname == truenas-docker
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
networks:
  host:
    external:
      name: "host"
```

### 📜 Relevant log output

```Text
CLAMAV_MESSAGE_SIZE_LIMIT='25M'
DEFAULT_RELAY_HOST=''
DMS_VMAIL_GID='5000'
DMS_VMAIL_UID='5000'
DOVECOT_INET_PROTOCOLS='all'
DOVECOT_MAILBOX_FORMAT='maildir'
DOVECOT_TLS='no'
ENABLE_AMAVIS='0'
ENABLE_CLAMAV='0'
ENABLE_DNSBL='0'
ENABLE_FAIL2BAN='1'
ENABLE_FETCHMAIL='0'
ENABLE_GETMAIL='0'
ENABLE_IMAP='1'
ENABLE_MANAGESIEVE='0'
ENABLE_OAUTH2='0'
ENABLE_OPENDKIM='0'
ENABLE_OPENDMARC='0'
ENABLE_POLICYD_SPF='0'
ENABLE_POP3='0'
ENABLE_POSTGREY='0'
ENABLE_QUOTAS='1'
ENABLE_RSPAMD='1'
ENABLE_RSPAMD_REDIS='1'
ENABLE_SASLAUTHD='0'
ENABLE_SPAMASSASSIN='0'
ENABLE_SPAMASSASSIN_KAM='0'
ENABLE_SRS='0'
ENABLE_UPDATE_CHECK='1'
FAIL2BAN_BLOCKTYPE='drop'
FETCHMAIL_PARALLEL='0'
FETCHMAIL_POLL='300'
GETMAIL_POLL='5'
LOGROTATE_COUNT='4'
LOGROTATE_INTERVAL='weekly'
LOGWATCH_INTERVAL='none'
LOGWATCH_RECIPIENT=≪me≫
LOGWATCH_SENDER=≪me≫
LOG_LEVEL='debug'
MARK_SPAM_AS_READ='0'
MOVE_SPAM_TO_JUNK='1'
NETWORK_INTERFACE='eth0'
OVERRIDE_HOSTNAME=≪blabla≫
PERMIT_DOCKER='none'
PFLOGSUMM_RECIPIENT=≪blabla≫
PFLOGSUMM_SENDER=≪blabla≫
PFLOGSUMM_TRIGGER='logrotate'
POSTFIX_DAGENT=''
POSTFIX_INET_PROTOCOLS='all'
POSTFIX_MAILBOX_SIZE_LIMIT='0'
POSTFIX_MESSAGE_SIZE_LIMIT='50000000'
POSTFIX_REJECT_UNKNOWN_CLIENT_HOSTNAME='0'
POSTGREY_AUTO_WHITELIST_CLIENTS='5'
POSTGREY_DELAY='300'
POSTGREY_MAX_AGE='35'
POSTGREY_TEXT='Delayed by Postgrey'
POSTMASTER_ADDRESS=≪blabla≫
POSTSCREEN_ACTION='enforce'
RELAY_HOST=''
REPORT_RECIPIENT=≪blabla≫
REPORT_SENDER=≪blabla≫
RSPAMD_CHECK_AUTHENTICATED='0'
RSPAMD_GREYLISTING='0'
RSPAMD_HFILTER='1'
RSPAMD_HFILTER_HOSTNAME_UNKNOWN_SCORE='6'
RSPAMD_LEARN='1'
RSPAMD_NEURAL='0'
SA_KILL='10.0'
SA_TAG2='6.31'
SA_TAG='-100000.0'
SMTP_ONLY='0'
SPAMASSASSIN_SPAM_TO_INBOX='1'
SPAM_SUBJECT=''
SPOOF_PROTECTION='0'
SRS_DOMAINNAME=≪blabla≫
SRS_EXCLUDE_DOMAINS=''
SRS_SECRET=''
SRS_SENDER_CLASSES='envelope_sender'
SSL_TYPE=''
SUPERVISOR_LOGLEVEL='warn'
TLS_LEVEL='modern'
TZ=''
UPDATE_CHECK_INTERVAL='1d'
VIRUSMAILS_DELETE_DELAY='7'
2024-06-15 07:55:25+02:00 INFO  start-mailserver.sh: Starting daemons
2024-06-15 07:55:25+02:00 DEBUG start-mailserver.sh: Starting cron
2024-06-15 07:55:26+02:00 DEBUG start-mailserver.sh: Starting rsyslog
2024-06-15 07:55:26+02:00 DEBUG start-mailserver.sh: Starting dovecot
2024-06-15 07:55:26+02:00 DEBUG start-mailserver.sh: Starting update-check
2024-06-15 07:55:27+02:00 DEBUG start-mailserver.sh: Starting rspamd-redis
2024-06-15 07:55:27+02:00 DEBUG start-mailserver.sh: Starting rspamd
2024-06-15 07:55:28+02:00 DEBUG start-mailserver.sh: Starting postfix
2024-06-15 07:55:28+02:00 DEBUG start-mailserver.sh: Starting fail2ban
2024-06-15 07:55:29+02:00 DEBUG start-mailserver.sh: Starting changedetector
2024-06-15 07:55:29+02:00 INFO  start-mailserver.sh: ≪blabla≫
 is up and running
2024-06-15T07:55:29.681505+02:00 mail postfix/postfix-script[1049]: warning: group or other writable: /var/lib/postfix/./prng_exch
2024-06-15T07:55:29.836613+02:00 mail postfix/postfix-script[1060]: starting the Postfix mail system
2024-06-15T07:55:30.853240+02:00 mail postfix/master[1061]: daemon started -- version 3.7.10, configuration /etc/postfix
2024-06-15T07:56:00.412916+02:00 mail dovecot: imap-login: Login: user=<me@me.nl>, method=PLAIN, rip=192.168.0.11, lip=192.168.0.67, mpid=1165, session=<ZBP3YucauG/AqAAL>
2024-06-15T07:56:06.410056+02:00 mail dovecot: imap-login: Login: user=<me@me.nl>, method=PLAIN, rip=192.168.0.11, lip=192.168.0.67, mpid=1179, session=<uaxSY+cahHfAqAAL>
```
