### ISSUE TITLE
bug report: adding new email account using setup email is failing

### ISSUE THREAD

**Issue by aalfiann** [docker-mailserver/docker-mailserver#4071]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I did run
```bash
docker exec mailserver setup email add aalfiann@nanowebdev.eu.org
```

but I got error aborting
```bash
2024-06-16 23:23:56+07:00 ERROR addmailuser: Password must not be empty
2024-06-16 23:23:56+07:00 ERROR addmailuser: Aborting
```

My expectation is, it should be prompted to input a password afterwards since no password was supplied.

### 👟 Reproduction Steps

Here is what I did:
1. Run >> docker compose -f docker-compose.yml up -d
2. Adding new first email >> docker exec mailserver setup email add aalfiann@nanowebdev.eu.org
3. Done, because its failing

### 🐋 DMS Version

v14.0.0

### 💻 Operating System and Architecture

Ubuntu 22

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.nanowebdev.eu.org
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - ./docker-data/certbot/certs/:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    environment:
      # Brute Force Protection
      - ENABLE_FAIL2BAN=1
      # Using letsencrypt for SSL/TLS certificates:
      - SSL_TYPE=letsencrypt
      # Allow sending emails from other docker containers:
      # Beware creating an Open Relay: https://docker-mailserver.github.io/docker-mailserver/latest/config/environment/#permit_docker
      - PERMIT_DOCKER=network
      # You may want to enable this: https://docker-mailserver.github.io/docker-mailserver/latest/config/environment/#spoof_protection
      # See step 6 below, which demonstrates setup with enabled/disabled SPOOF_PROTECTION:
      - SPOOF_PROTECTION=0
      # Set Timezone
      - TZ=Asia/Jakarta
      # Using RSPAMD
      - ENABLE_RSPAMD=1
      - ENABLE_CLAMAV=1
      # Rspamd replaces the functionality of all these anti-spam services, disable them:
      - ENABLE_OPENDKIM=0
      - ENABLE_OPENDMARC=0
      - ENABLE_POLICYD_SPF=0
      - ENABLE_AMAVIS=0
      - ENABLE_SPAMASSASSIN=0
      # Provided you've set `RSPAMD_GREYLISTING=1`, also disable Postgrey:
      - ENABLE_POSTGREY=0
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    restart: unless-stopped
```

### 📜 Relevant log output

```Text
root@mail:/srv/mailserver# docker exec mailserver setup email add aalfiann@nanowebdev.eu.org

2024-06-16 23:23:56+07:00 ERROR addmailuser: Password must not be empty
2024-06-16 23:23:56+07:00 ERROR addmailuser: Aborting
```
