### ISSUE TITLE
bug report:  `Client host rejected: Access denied` - One of my services connects but fails to send mail through DMS

### ISSUE THREAD

**Issue by kawaegle** [docker-mailserver/docker-mailserver#4075]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?
seem related but don't help https://github.com/docker-mailserver/docker-mailserver/issues/359
when I setup DMS and the mailler of gitea and vikunja, the gitea's mailler work as expected, but vikunja still fail to send but connect with success 

### 👟 Reproduction Steps

Setup DMS:
setup DMS as a simple Mail server
Fix DKIM DMARC SPF error

Setup Gitea:
setup gitea mailler (it work like a charm) 

Setup Vikunja:
setup vikunja mailler (sending SMTP RCPT TO command: 554 5.7.1 <unknown[192.168.176.1]>: Client host rejected: Access denied)

### 🐋 DMS Version

13.3.1

### 💻 Operating System and Architecture

debian 12

### ⚙️ Container configuration files

```yml
networks:
  mail:
  ssl_mail:
    external: true

volumes:
  mail_data:
  mail_state:
  mail_logs:
  mail_config:
  webmail_db:
  webmail_web:

services:
  mail_server:
    image: mailserver/docker-mailserver:13.3.1
    container_name: mail_server
    restart: always
    volumes:
      - mail_data:/var/mail/
      - mail_state:/var/mail-state/
      - mail_logs:/var/log/mail/
      - mail_config:/tmp/docker-mailserver/
      - ./postfix.cf:/tmp/docker-mailserver/postfix-main.cf
      - /etc/localtime:/etc/localtime:ro
      - ../01-SSL/certs/:/etc/letsencrypt/live/:ro
    environment:
      SSL_TYPE: letsencrypt
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      PERMIT_DOCKER: network
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    hostname: ${VIRTUAL_HOST}
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    stop_grace_period: 1m
    domainname: ${VIRTUAL_SMTP_HOST} # ${DOMAINNAME}

  webmail_client:
    image: roundcube/roundcubemail:1.6.6-fpm-alpine
    container_name: webmail_client
    restart: always
    depends_on:
      - webmail_db
    volumes:
      - webmail_web:/var/www/html
    networks:
      - mail
    environment:
      ROUNDCUBEMAIL_SMTP_SERVER: tls://${VIRTUAL_HOST}
      ROUNDCUBEMAIL_DEFAULT_HOST: tls://${VIRTUAL_HOST}
      ROUNDCUBEMAIL_DEFAULT_PORT: 143
      ROUNDCUBEMAIL_SMTP_PORT: 587
      ROUNDCUBEMAIL_DB_TYPE: pgsql
      ROUNDCUBEMAIL_DB_HOST: ${DB_HOST}
      ROUNDCUBEMAIL_DB_NAME: ${DB_NAME}
      ROUNDCUBEMAIL_DB_USER: ${DB_USER}
      ROUNDCUBEMAIL_DB_PASSWORD: ${DB_PASS}
      ROUNDCUBEMAIL_SKIN: elastic

  webmail_nginx:
    image: nginx:alpine
    container_name: webmail_nginx
    restart: always
    depends_on:
      - webmail_client
    volumes:
      - webmail_web:/var/www/html
      - ./nginx-template.conf:/etc/nginx/templates/default.conf.template
    environment:
      NGINX_HOST: webmail_client
      NGINX_PHP_CGI: webmail_client:9000
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
    networks:
      - ssl_mail
      - mail
    links:
      - webmail_client

  webmail_db:
    image: postgres:15
    container_name: ${DB_HOST}
    restart: always
    volumes:
      - webmail_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - mail


---------
networks:
  gitea:
  ssl_git:
    external: true

volumes:
  gitea_db:
  gitea_data:

services:
  gitea_server:
    image: gitea/gitea:1.21
    container_name: gitea_server
    restart: always
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./themes:/data/gitea/public/assets/
    depends_on:
      - db
    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__database__DB_TYPE: ${DB_TYPE}
      GITEA__database__HOST: gitea_db:3306
      GITEA__database__NAME: ${SQL_DB}
      GITEA__database__USER: ${SQL_USER}
      GITEA__database__PASSWD: ${SQL_PASSWORD}
      GITEA__service__DISABLE_REGISTRATION: ${DISABLE_REGISTRATION}
      GITEA__service__REQUIRE_SIGNIN_VIEW: ${DISABLE_REGISTRATION}
      GITEA__mailer__ENABLED: true
      GITEA__mailer__FROM: ${MAILER_FROM}
      GITEA__mailer__PROTOCOL: smtp+starttls
      GITEA__mailer__SMTP_ADDR: ${MAIL_SERVER}
      GITEA__mailer__SMTP_PORT: 587
      GITEA__mailer__USER: ${MAIL_USER}
      GITEA__mailer__PASSWD: ${MAIL_PASS}
      GITEA__APP_NAME: ${APP_NAME}
      GITEA__ui__DEFAULT_THEME: gitea-auto
      GITEA__ui__THEMES: ${THEMES_LIST}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
    networks:
      - ssl_git
      - gitea
    ports:
      - "2222:22"

  db:
    image: mariadb:10
    container_name: gitea_db
    restart: always
    volumes:
      - gitea_db:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: ${SQL_USER}
      MYSQL_PASSWORD: ${SQL_PASSWORD}
      MYSQL_DATABASE: ${SQL_DB}
    networks:
      - gitea



----------




networks:
  vikunja:
  ssl_orga:
    external: true

volumes:
  vikunja_db:
  vikunja_data:
  shlink_data:

services:
  vikunja_api:
    image: vikunja/api:0.22
    container_name: vikunja_api
    restart: always
    depends_on:
      - vikunja_db
    volumes:
      - vikunja_data:/app/vikunja/files
    environment:
      VIKUNJA_DATABASE_HOST: ${VIKUNJA_DATABASE_HOST}
      VIKUNJA_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      VIKUNJA_DATABASE_TYPE: ${VIKUNJA_DATABASE_TYPE}
      VIKUNJA_DATABASE_USER: ${MYSQL_USER}
      VIKUNJA_DATABASE_DATABASE: ${MYSQL_DATABASE}
      VIKUNJA_SERVICE_JWTSECRET: ${VIKUNJA_SERVICE_JWTSECRET}
      VIKUNJA_SERVICE_FRONTENDURL: ${VIKUNJA_SERVICE_FRONTENDURL}

      VIKUNJA_MAILER_ENABLED: ${VIKUNJA_MAILER_ENABLED}
      VIKUNJA_MAILER_HOST: ${VIKUNJA_MAILER_HOST}
      VIKUNJA_MAILER_PORT: ${VIKUNJA_MAILER_PORT}
      VIKUNJA_MAILER_AUTHTYPE: ${VIKUNJA_MAILER_AUTHTYPE}
      VIKUNJA_MAILER_USERNAME: ${VIKUNJA_MAILER_USERNAME}
      VIKUNJA_MAILER_FROMEMAIL: ${VIKUNJA_MAILER_FROMEMAIL}
      VIKUNJA_SERVICE_ENABLEREGISTRATION: false
      VIKUNJA_LOG_MAILLEVEL: INFO
      VIKUNJA_LOG_MAIL: stdout

      VIRTUAL_HOST: ${VIRTUAL_VIKUNJA_API_HOST}
      VIRTUAL_PORT: ${VIRTUAL_VIKUNJA_API_PORT}
      LETSENCRYPT_HOST: ${VIRTUAL_VIKUNJA_API_HOST}
    networks:
      - ssl_orga
      - vikunja

  vikunja_frontend:
    image: vikunja/frontend:0.22
    container_name: vikunja_front
    restart: unless-stopped
    depends_on:
      - vikunja_api
    environment:
      VIKUNJA_API_URL: ${VIKUNJA_API_URL}
      VIRTUAL_HOST: ${VIRTUAL_VIKUNJA_FRONT_HOST}
      VIRTUAL_PORT: ${VIRTUAL_VIKUNJA_FRONT_PORT}
      LETSENCRYPT_HOST: ${VIRTUAL_VIKUNJA_FRONT_HOST}
    networks:
      - ssl_orga
      - vikunja

  vikunja_db:
    image: mariadb:10
    container_name: vikunja_db
    restart: always
    volumes:
      - vikunja_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - vikunja
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
```

### 📜 Relevant log output

```Text
Jun 17 17:26:17 mail postfix/submission/smtpd[855]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 554 5.7.1 <unknown[.168.224.1]>: Client host rejected: Access denied; from=<noreply-vikunja@mail.domain.com> to=<user@mail.domain.com> proto=ESMTP helo=<09a1ac15f4db>
Jun 17 17:26:22 mail postfix/submission/smtpd[855]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 554 5.7.1 <unknown[192.168.224.1]>: Client host rejected: Access denied; from=<noreply-vikunja@mail.domain.com> to=<user@mail.domain.com> proto=ESMTP helo=<09a1ac15f4db>
Jun 17 17:42:13 mail postfix/submission/smtpd[2443]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 554 5.7.1 <unknown[192.168.224.1]>: Client host rejected: Access denied; from=<noreply-vikunja@mail.domain.com> to=<user@mail.domain.com> proto=ESMTP helo=<09a1ac15f4db>
```

### MORE
checking vikuja issue and trying on my own
