### ISSUE TITLE
bug report: ClamAV doesn't start after update

### ISSUE THREAD

**Issue by Nebucatnetzer** [docker-mailserver/docker-mailserver#4083]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

After updating to 14.0.0 didn't want to start anymore

Could this be a problem with ARM64?

I unfortunately don't have much more logs as I disabled ClamAV while investigating this issue and only enabled debugging afterwards: https://github.com/docker-mailserver/docker-mailserver/issues/4082

### 🐋 DMS Version

v14.0.0

### 💻 Operating System and Architecture

NixOS 24.05 ARM64

### 📜 Relevant log output

```Text
un 19 22:26:57 mail docker-mailserver-start[1398]: 2024-06-19 22:26:57,389 WARN exited: clamav (exit status 1; not expected)
Jun 19 22:26:57 mail docker-mailserver-start[1398]: 2024-06-19 22:26:57,429 WARN exited: clamav (exit status 1; not expected)
Jun 19 22:26:57 mail docker-mailserver-start[1398]: 2024-06-19 22:26:57,479 WARN exited: clamav (exit status 1; not expected)
Jun 19 22:26:57 mail docker-mailserver-start[1398]: 2024-06-19 22:26:57,532 WARN exited: clamav (exit status 1; not expected)
Jun 19 22:26:57 mail docker-mailserver-start[1398]: 2024-06-19 22:26:57,595 WARN exited: clamav (exit status 1; not expected)
Jun 19 22:26:57 mail docker-mailserver-start[1398]: 2024-06-19 22:26:57,695 WARN exited: clamav (exit status 1; not expected)
```

**Comment by polarathene** [comment]
Does a v14 image work with ClamAV disabled? Given the linked issue, the ClamAV concern might be a side-effect to the real problem.

**Comment by polarathene** [comment]
Closing as identified the cause.

- `ONE_DIR=0` + `/var/mail-state` volume mount (NFS) were used. v14 removed the `ONE_DIR` ENV as it was redundant, since mounting `/var/mail-state` implies the expectation of `ONE_DIR=1` to use that location.
- ClamAV state was now attempting to be persisted to `/var/mail-state`, but due to NFS usage (_which DMS does not support officially_), failures ensued.

**Comment by okainov** [comment]
>Closing as identified the cause.

Thanks for investigation, but I'm not sure I understand what do I do with this...

I had old installation of docker-mailserver from version 7 which I decided to upgrade today. Did every sequential upgrade to every new major version, and it was fine until 14.0 where I'm getting this error.

Relevant info from my compose (which is intact from the old version)

```yaml
services:
 mail:
    build:
      context: docker-mailserver
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - maillogs:/var/log/mail
    - ./config/:/tmp/docker-mailserver/
    - /etc/letsencrypt/:/etc/letsencrypt/
    - ./postfix_sql/:/etc/postfix/sql/

volumes:
  maildata:
  mailstate:
  maillogs:
```

I'm not using any "ONE_DIR"...
