### ISSUE TITLE
question: Why does Fail2Ban not respect my whitelist `ignoreip` setting?

### ISSUE THREAD

**Issue by MarcS1975** [docker-mailserver/docker-mailserver#4091]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Fail2ban whitelisting does not work. I am trying ignore any lockups caused by IMAP clients hosted on my own network but this doesn't work. When I execute several 'incorrect' login attempts , my external IP still gets blocked by fail2ban (->banned in dovecot).
 
In accordance with the documentation I have added in the file _fail2ban-jail.cfg_ stored in the DMS 'config' folder 
`ignoreip = 127.0.0.1/8,xx.xx.xx.xxx`
whereby xx.xx.xx.xxx = my external IP4

But my IP does not get ignored by fail2ban and still gets blocked.

### 👟 Reproduction Steps

log into mail client (Roundcube or Rainloop) that connects to DMS
use wrong password
mail client IP gets blocked

### 🐋 DMS Version

13.3.1

### 💻 Operating System and Architecture

Debian 11

### ⚙️ Container configuration files

```yml
mailserver:
    image: docker.io/mailserver/docker-mailserver:13.3.1
    container_name: mailserver2
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: [myhost]
    ports:
      [myports]
    volumes:
    - /[mypath]/mail-data/:/var/mail/
    - /[mypath]/mail-state/:/var/mail-state/
    - /[mypath]/mail-logs/:/var/log/mail/
    - /[mypath]/config/:/tmp/docker-mailserver/
    - /etc/localtime/:/etc/localtime:ro
    - /[mypath]/certs/:/tmp/dms/custom-certs/
   
    environment:
      - TZ=Europe/London
      - LOG_LEVEL=debug 
      - PFLOGSUMM_TRIGGER=daily_cron # by AJ
      - POSTFIX_MESSAGE_SIZE_LIMIT=10240000 # by AJ
      - LOGWATCH_INTERVAL=daily 
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_SPAMASSASSIN_KAM=0 
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=0 # by AJ
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=0
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/tmp/dms/custom-certs/fullchain.pem
      - SSL_KEY_PATH=/tmp/dms/custom-certs/privkey.pem
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
 # healthcheck:
 #  test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
 # timeout: 3s
 # retries: 0
```
