### ISSUE TITLE
bug report: can't receive emails (Traefik v3, HAProxy v2, DMS Edge)

### ISSUE THREAD

**Issue by ineanto** [docker-mailserver/docker-mailserver#4094]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Hi, I'll do my best to give you as much information as I can about this issue.

After setting up DMS edge I try to send a mail with ```swaks``` using the following command as advised by the docs:
```swaks --helo not-relevant.test --server (server address) --port 25 --from hello@not-relevant.test --to user@example.com```

Swaks successfully connects to my server but then hangs for 30 seconds:
```
=== Trying (server address):25...
=== Connected to (server address).
<** Timeout (30 secs) waiting for server response
 -> QUIT
<-  220-(server address) ESMTP
<-  221 2.0.0 Bye
=== Connection closed with remote host.
```
When Swaks gets disconnected, DMS spits out this:
```
mail postfix/postscreen[804]: CONNECT from [my ip]:45040 to [172.16.42.8]:25
mail postfix/postscreen[804]: PREGREET 6 after 0 from [my ip]:45040: QUIT\r\n
mail postfix/postscreen[804]: DISCONNECT [my ip]:45040
```

**I must precise that things kinda worked before but mails had trouble sending but were sent nonetheless, so I tried starting from scratch and updated to Traefik v3 at the same time**

I've tried basically everything: 
- Starting from scratch
- Enabling dedicated HAProxy ports
- Lowering postscreen scan
- Using HAProxy v1
- Using a stable version of DMS and going back to Traefik V2
and probably more things that I've forgot.

### 🐋 DMS Version

edge

### 💻 Operating System and Architecture

Alpine Linux

### ⚙️ Container configuration files

```yml
mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:edge
    container_name: mailserver

    hostname: (server address with "mail." subdomain)

    environment:
      SSL_TYPE: letsencrypt

    labels:
      - "traefik.enable=true"

      # EXPLICIT TLS (STARTTLS) STARTS HERE
      - "traefik.tcp.routers.smtp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smtp.entrypoints=smtp"
      - "traefik.tcp.routers.smtp.service=smtp"
      - "traefik.tcp.services.smtp.loadbalancer.server.port=25"
      - "traefik.tcp.services.smtp.loadbalancer.proxyProtocol.version=2"

      # IMPLICIT TLS STARTS HERE
      - "traefik.tcp.routers.submission.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.submission.entrypoints=submission"
      - "traefik.tcp.routers.submission.service=submission"
      - "traefik.tcp.services.submission.loadbalancer.server.port=465"
      - "traefik.tcp.services.submission.loadbalancer.proxyProtocol.version=2"

      - "traefik.tcp.routers.imaps.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.imaps.entrypoints=imaps"
      - "traefik.tcp.routers.imaps.service=imaps"
      - "traefik.tcp.services.imaps.loadbalancer.server.port=993"
      - "traefik.tcp.services.imaps.loadbalancer.proxyProtocol.version=2"

      - "traefik.tcp.routers.sieve.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.sieve.entrypoints=sieve"
      - "traefik.tcp.routers.sieve.service=sieve"
      - "traefik.tcp.services.sieve.loadbalancer.server.port=4190"
      - "traefik.tcp.services.sieve.loadbalancer.proxyProtocol.version=2"

    volumes:
      - ./src/data/acme.json:/etc/letsencrypt/acme.json:ro
      - ./dms/mail-data/:/var/mail/
      - ./dms/mail-state/:/var/mail-state/
      - ./dms/mail-logs/:/var/log/mail/
      - ./dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
```

Update: 

I moved DMS outside of Traefik and everything worked flawlessly as soon as I started the container. Using as is until a solution is found, because I'd really like to have every service under Traefik.
