### ISSUE TITLE
question: Why does `doveadm auth test` fails with user added by `setup dovecot-master add` and `setup email add`

### ISSUE THREAD

**Issue by unlucio** [docker-mailserver/docker-mailserver#4098]
### Subject

Something else that requires developers attention

### Description

while still trying to debug this problem https://github.com/orgs/docker-mailserver/discussions/4096

looks like dovecot doesn't like users added by setup:

I'm using the `setup` command as suggested by the documentation but:

```
setup dovecot-master add test@mydomain.com aaaa
doveadm auth test test@mydomain.com aaaa
passdb: test@mydomain.com auth failed
extra fields:
  user=test@mydomain.com

setup email add test@mydomain.com aaaa 
doveadm auth test test@mydomain.com aaaa
passdb: test@mydomain.com auth failed
extra fields:
  user=test@mydomain.com
```

is this supposed to happen? 😵‍💫

**Comment by polarathene** [comment]
If tat wasn't working our test suite would fail:

https://github.com/docker-mailserver/docker-mailserver/blob/9175424d0f3c67622c030311cc720d7477f1c2b6/test/tests/parallel/set3/scripts/setup_cli.bats#L40-L67

It's likely that you re running the `doveadm` command too soon?

What happens is the `setup email add` command updates the `postfix-accounts.cf` file with a new line, and within 2 seconds that change should be detected which triggers Dovecot to add the account to it's UserDB. After all the change detection processing is done it issues a `dovecot reload`, from here your `doveadm` should work.

As you can see in the test case we wait until the account is created before we check auth. In the past this could take around 10s, but it should be fairly quick now, the 2 second window is how often the change detection service polls config files for changes.

**Comment by unlucio** [comment]
I doubt it was too soon:
my 1st test was actually with an account I created yesterday during setup, I'm still investigating why everything seems fine but my logs are full of those not-so-helpful errors and my user cannot authenticate. That container has been destroyed and created a ton of times right now.
I created the test accounts just as props for this post, after I saw `doveadm auth test` systematically fail.
To be sure I just ran that auth test again, several hours later, and here's the result:
<img width="377" alt="Screenshot_2024-07-04_at_00_23_57" src="https://github.com/docker-mailserver/docker-mailserver/assets/778799/5980c6ed-8d98-4b93-b5c4-cbb64141e30a">

```
root@mail:/# setup email list
* postmaster@mydomain.com

* test@mydomain.com

root@mail:/# setup dovecot-master list
* postmaster@mydomain.com

* test@mydomain.com

root@mail:/# doveadm auth test test@mydomain.com aaaaa
passdb: test@mydomain.com auth failed
extra fields:
  user=test@mydomain.com
```

I see the expected account,m and it still fails, both the test as well if I try a mail client.

**Comment by polarathene** [comment]
> while still trying to debug this problem https://github.com/orgs/docker-mailserver/discussions/4096

I've since read and responded to your related discussion.

Without a full bug report I've had to make some assumptions, but I'm going to guess you're trying to run DMS with Docker on macOS. That uses a VM with macOS specific drivers that are known to have issues, you can try searching through issues we've tagged with macOS label, or find the upstream issues on Github unrelated to DMS.

I know I've had no issue with this on Linux hosts or in WSL on Windows. I was able to authenticate without trouble with `doveadm auth test` or via ThunderBird.

I haven't done so recently, but given our test suite passes here I really don't see why that would fail for me if I were to try again.

---

> I see the expected account, and it still fails, both the test as well if I try a mail client.

If `doveadm auth test` fails, I don't think the mail client would succeed. You need to get that command working first.

If I am right about you trying to make DMS work with Docker on macOS, please try reproduce in an actual Linux VM running Docker without those macOS specific concerns in the way.

Here on WSL2 (Windows 11) your issue cannot be reproduced:

```yml
services:
  test:
    image: mailserver/docker-mailserver:edge
    container_name: dms
    hostname: example.test
```

```console
$ docker compose up -d
$ docker exec -it dms bash

# In the DMS container now:
$ setup email add hello@example.test secret
$ doveadm auth test hello@example.test secret
passdb: hello@example.test auth succeeded
extra fields:
  user=hello@example.test
```

**Comment by unlucio** [comment]
Thank you for your prompt answer, unfortunately, I ended up on an unplanned "vacation" in the hospital shortly after.

I'm not running DMS on macOS but in a docker-swarm cluster (all linux machines), forcing the deploy on the master node for sake of not having to deal too much with eventual network-related problems (the swarm ingress is actually traefik and ideally DMS will be behind traefik at some point).
The master-node, and machine where DMS is currently running, is:
- distro: Ubuntu 22.04.4 LTS
- kernel: 5.15.0-113-generic  123-Ubuntu SMP Mon Jun 10 08:16:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- docker: Docker version 20.10.17, build 100c701

> If doveadm auth test fails, I don't think the mail client would succeed. You need to get that command working first.

I completely agree, which is the reason I ditched the client (mail.app was just the most convenient one at the time of testing), and focused on that.

All what I reported was indeed on Linux.

I agree that having a full trace to debug it would be best: I tried to provide thought information about my setup on my community post. I hoped my environment, logs, and config files would be a good start. I'll add my compose as well:

```yaml
version: '3.8'

services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    hostname: mail.mydomain.com
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    env_file: .env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - '25:25' # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - '143:143' # IMAP4 (explicit TLS => STARTTLS)
      - '465:465' # ESMTP (implicit TLS)
      - '587:587' # ESMTP (explicit TLS => STARTTLS)
      - '993:993' # IMAP4 (implicit TLS)
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data/docker-mailserver/mail-data/:/var/mail/
      - /mnt/data/docker-mailserver/mail-state/:/var/mail-state/
      - /mnt/data/docker-mailserver/mail-logs/:/var/log/mail/
      - /mnt/data/docker-mailserver/config/:/tmp/docker-mailserver/
      - /mnt/data/traefik/certs/:/etc/letsencrypt/
    networks:
      - swarm-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

networks:
  swarm-net:
    external: true
```

What else can I dig up to provide useful information?
I of course thought about debug logs but they might be too much?
