### ISSUE TITLE
bug report: `postfix-main.cf` is appending warnings to `/etc/postfix/main.cf`

### ISSUE THREAD

**Issue by loeffelpan** [docker-mailserver/docker-mailserver#4145]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I added a configuration in postfix-main.cf referencing a file like `relay_domains = pgsql:/etc/postfix/pgsql-relay-domains.cf`.
This referenced file was not in place at time of executing postconf during startup, as it comes later with user-patches.sh.
Now I got errors from postfix as some options in the `main.cf` are not parsable.

NOTE: I added `postfix-pgsql` using my own `Dockerfile` with `FROM docker.io/mailserver/docker-mailserver:latest`.

### 👟 Reproduction Steps

1. Create a `postfix-main.cf` and add a line referencing a file, that does not exist.
2. Start the container and let the scripts place the config files in place.
3. See error as above because error messages from `postconf` are at the most bottom of `main.cf`
```
...
virtual_alias_maps = texthash:/etc/postfix/virtual
virtual_mailbox_domains = /etc/postfix/vhost
virtual_mailbox_limit = 0
virtual_mailbox_maps = texthash:/etc/postfix/vmailbox
virtual_transport = lmtp:unix:/var/run/dovecot/lmtp
postconf: warning: open "pgsql" configuration "/etc/postfix/pgsql-relay-domains.cf": No such file or directory
postconf: warning: open "pgsql" configuration "/etc/postfix/pgsql-transport-maps.cf": No such file or directory
```

### 🐋 DMS Version

v14.0.0

### 💻 Operating System and Architecture

Fedora CoreOS

### ⚙️ Container configuration files

```yml
services:

  mailserver:
    image: localhost/mailserver:latest
    build: .
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.kbw3.de
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./dms/mail-data:/var/mail:Z
      - ./dms/mail-state:/var/mail-state:Z
      - ./dms/mail-logs:/var/log/mail:Z
      - ./dms/config:/tmp/docker-mailserver:Z
      - ./dms/certs:/etc/certs:Z
    restart: unless-stopped
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    depends_on:
      db:
        condition: service_healthy

include:
  - simplelogin.yaml
  - postfix.yaml

networks:
  default:
    name: mailserver-simplelogin
```

### 📜 Relevant log output

```Text
2024-07-31T21:35:13.736273+02:00 mail postfix[1095]: fatal: /etc/postfix/main.cf, line 80: missing '=' after attribute name: "postconf: warning: open "pgsql" configuration "/etc/postfix/pgsql-transport-maps.cf": No such file or directory"
```

**Comment by loeffelpan** [comment]
I think this happens with this line:
https://github.com/docker-mailserver/docker-mailserver/blob/37e5203a6973956d9afadbd9bc575bc5662e7f56/target/scripts/startup/setup.d/postfix.sh#L132
But I have no idea for an improvement.

**Comment by polarathene** [comment]
> I think this happens with this line

That is correct, thanks for catching and reporting this bug ❤️ 

This [bug was introduced into DMS v14 by my PR](https://github.com/docker-mailserver/docker-mailserver/pull/3880) that tried to hide certain warnings but this unexpectedly was filtering `stderr` with `grep` to `stdout` that was merged with the original `stdout` being redirect to file `/tmp/postfix-main.new.cf`.

---

# Minimal reproduction

```yaml
services:
  dms:
    hostname: mail.example.com
    # The `image` setting now represents the tag for the local build configured below:
    image: local/dms:14.0
    # Local build (no need to try pull `image` remotely):
    pull_policy: build
    # Custom build of DMS, extending it to include the `postfix-pgsql` package:
    build:
      dockerfile_inline: |
        FROM docker.io/mailserver/docker-mailserver:14.0
        RUN apt-get update && apt-get install -y postfix-pgsql
    # These ENV aren't relevant. Added to minimize log output for this reproduction example:
    environment:
      SMTP_ONLY: 1
      ENABLE_AMAVIS: 0
    # Your config files that would normally be separate files provided via the `volumes` setting instead:
    configs:
      - source: postfix-main-updates
        target: /tmp/docker-mailserver/postfix-main.cf
      - source: user-patches
        target: /tmp/docker-mailserver/user-patches.sh

configs:
  # This particular failure needs requires a Postfix Table type, not just a file path (different error output)
  postfix-main-updates:
    content: |
      relay_domains = pgsql:/etc/postfix/pgsql-relay-domains.cf

  user-patches:
    content: |
      # Do something like create a file:
      touch /etc/postfix/pgsql-relay-domains.cf
```

## `docker compose up --force-recreate` output

### DMS v14

Failure due to `postconf` warning being accidentally appended into `/etc/postfix/main.cf`:

```
dms-1  | 2024-08-01 00:48:45+00:00 INFO  start-mailserver.sh: Welcome to docker-mailserver v14.0.0
dms-1  | 2024-08-01 00:48:45+00:00 INFO  start-mailserver.sh: Checking configuration
dms-1  | 2024-08-01 00:48:45+00:00 INFO  start-mailserver.sh: Configuring mail server
dms-1  | 2024-08-01 00:48:46+00:00 WARN  start-mailserver.sh: !! INSECURE !! SSL configured with plain text access - DO NOT USE FOR PRODUCTION DEPLOYMENT
dms-1  | 2024-08-01 00:48:46+00:00 INFO  start-mailserver.sh: Starting daemons
dms-1  | 2024-08-01 00:48:47+00:00 INFO  start-mailserver.sh: mail.example.test is up and running
dms-1  | 2024-08-01T00:48:53.357126+00:00 mail postfix[452]: fatal: /etc/postfix/main.cf, line 73: missing '=' after attribute name: "postconf: warning: open "pgsql" configuration "/etc/postfix/pgsql-relay-domains.cf": No such file or directory"
```

### With fix

Warning is now instead emitted to logs at the time of the `postconf -n` command, and any proper failure from misconfiguration will occur during Postfix startup.

**NOTE:** The warning could be emitted elsewhere when scripts use `postconf` command to read a setting instead of write: https://github.com/docker-mailserver/docker-mailserver/pull/2598#issuecomment-1141561786

**When `user-patches.sh` is not used:**

```
dms-1  | 2024-08-01 01:00:05+00:00 INFO  start-mailserver.sh: Welcome to docker-mailserver v14.0.0
dms-1  | 2024-08-01 01:00:05+00:00 INFO  start-mailserver.sh: Checking configuration
dms-1  | 2024-08-01 01:00:05+00:00 INFO  start-mailserver.sh: Configuring mail server
dms-1  | 2024-08-01 01:00:05+00:00 WARN  start-mailserver.sh: !! INSECURE !! SSL configured with plain text access - DO NOT USE FOR PRODUCTION DEPLOYMENT
dms-1  | postconf: warning: open "pgsql" configuration "/etc/postfix/pgsql-relay-domains.cf": No such file or directory
dms-1  | 2024-08-01 01:00:05+00:00 INFO  start-mailserver.sh: Starting daemons
dms-1  | 2024-08-01 01:00:06+00:00 INFO  start-mailserver.sh: mail.example.test is up and running
dms-1  | 2024-08-01T01:00:06.931600+00:00 mail postfix/postfix-script[528]: starting the Postfix mail system
dms-1  | 2024-08-01T01:00:06.940466+00:00 mail postfix/master[529]: daemon started -- version 3.7.11, configuration /etc/postfix
dms-1  | 2024-08-01T01:00:06.948552+00:00 mail postfix/qmgr[531]: error: open /etc/postfix/pgsql-relay-domains.cf: No such file or directory
```

**When `user-patches.sh` is used** (_but the config file is missing setting, in this case it's an empty file_):

```
dms-1  | 2024-08-01 00:58:43+00:00 INFO  start-mailserver.sh: Welcome to docker-mailserver v14.0.0
dms-1  | 2024-08-01 00:58:43+00:00 INFO  start-mailserver.sh: Checking configuration
dms-1  | 2024-08-01 00:58:43+00:00 INFO  start-mailserver.sh: Configuring mail server
dms-1  | 2024-08-01 00:58:43+00:00 WARN  start-mailserver.sh: !! INSECURE !! SSL configured with plain text access - DO NOT USE FOR PRODUCTION DEPLOYMENT
dms-1  | postconf: warning: open "pgsql" configuration "/etc/postfix/pgsql-relay-domains.cf": No such file or directory
dms-1  | 2024-08-01 00:58:44+00:00 INFO  start-mailserver.sh: Starting daemons
dms-1  | 2024-08-01 00:58:45+00:00 INFO  start-mailserver.sh: mail.example.test is up and running
dms-1  | 2024-08-01T00:58:45.318637+00:00 mail postfix/postfix-script[530]: starting the Postfix mail system
dms-1  | 2024-08-01T00:58:45.323546+00:00 mail postfix/master[531]: daemon started -- version 3.7.11, configuration /etc/postfix
dms-1  | 2024-08-01T00:58:46.533487+00:00 mail postfix/qmgr[533]: fatal: /etc/postfix/pgsql-relay-domains.cf: bad string length 0 < 1: dbname =
dms-1  | 2024-08-01T00:58:47.534472+00:00 mail postfix/master[531]: warning: process /usr/lib/postfix/sbin/qmgr pid 533 exit status 1
dms-1  | 2024-08-01T00:58:47.534483+00:00 mail postfix/master[531]: warning: /usr/lib/postfix/sbin/qmgr: bad command startup -- throttling
```

---

## Workarounds for DMS v14

I'll have the fix for this as part of DMS v14.1, in the meantime this config can probably be provided via a `volume`? Or if you have any Docker Compose since the start of 2024 you can use `configs` feature:

```yaml
services:
  dms:
    configs:
      - source: postfix-main-updates
        target: /tmp/docker-mailserver/postfix-main.cf
      - source: pgsql-relay
        target: /etc/postfix/pgsql-relay-domains.cf

configs:
  postfix-main-updates:
    content: |
      relay_domains = pgsql:/etc/postfix/pgsql-relay-domains.cf

  pgsql-relay:
    content: |
      user = postfix
      password = whatever
      hosts = localhost
      dbname = postfix
      query = SELECT domain FROM domain WHERE domain='%s' and backupmx = true
```

Otherwise, another option to avoid the v14 bug is to **not use `postfix-main.cf` for this**. You can configure it as part of your `user-patches.sh`. This will work fine provided nothing later attempts to regenerate `/etc/postfix/main.cf` (_like the startup script does prior to `user-patches.sh`_).

**`user-patches.sh`:**

```bash
#!/bin/bash
# This file runs before the Postfix service is started.

# Run your commands to create your config file:
touch /etc/postfix/pgsql-relay-domains.cf

# Update Postfix config as desired:
postconf 'relay_domains = pgsql:/etc/postfix/pgsql-relay-domains.cf'
```
