### ISSUE TITLE
bug report: `postconf: fatal: open /etc/postfix/main.cf for reading: No such file or directory`

### ISSUE THREAD

**Issue by DisruptionSystemsINC** [docker-mailserver/docker-mailserver#4151]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

It seems like as if postfix's configuration is not being generated/not being shipped in the container which causes issues with postfix's startup, in the form of a fatal error by postconf

### 👟 Reproduction Steps

1. Clone Project,
2. Configure mailserver.env and compose.yaml
3. main.cf seems to be missing and actively causing errors

### 🐋 DMS Version

v14.0.0

### 💻 Operating System and Architecture

Rocky 9

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.mydomainhere.com
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    environment:
      - SSL_TYPE=letsencrypt
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### 📜 Relevant log output

```Text
mailserver  | sha1sum: /etc/postfix/main.cf: No such file or directory
mailserver  | 2024-08-04 04:08:54+02:00 DEBUG start-mailserver.sh: Spam subject is set - the prefix '[SPAM] ' will be added to spam e-mails
mailserver  | 2024-08-04 04:08:54+02:00 TRACE start-mailserver.sh: Enabling '+editheader' Sieve extension
mailserver  | 2024-08-04 04:08:54+02:00 TRACE start-mailserver.sh: Adding global (before) Sieve script for subject rewrite
mailserver  | 2024-08-04 04:08:54+02:00 DEBUG start-mailserver.sh: Spam emails will be moved to the Junk folder
mailserver  | 2024-08-04 04:08:54+02:00 DEBUG start-mailserver.sh: Spam emails will not be marked as read
mailserver  | 2024-08-04 04:08:54+02:00 DEBUG start-mailserver.sh: Setting up Dovecot Local User
mailserver  | 2024-08-04 04:08:54+02:00 TRACE start-mailserver.sh: Regenerating postfix user list
mailserver  | 2024-08-04 04:08:54+02:00 DEBUG start-mailserver.sh: Creating user 'gandhi' for domain 'disruption-systems.com'
mailserver  | 2024-08-04 04:08:54+02:00 DEBUG start-mailserver.sh: Disabling OpenDKIM
mailserver  | 2024-08-04 04:08:54+02:00 DEBUG start-mailserver.sh: Disabling OpenDMARC
mailserver  | 2024-08-04 04:08:54+02:00 DEBUG start-mailserver.sh: Disabling policyd-spf
mailserver  | 2024-08-04 04:08:54+02:00 DEBUG start-mailserver.sh: Setting up Security Stack
mailserver  | 2024-08-04 04:08:54+02:00 DEBUG start-mailserver.sh: Postgrey is disabled
mailserver  | 2024-08-04 04:08:54+02:00 DEBUG start-mailserver.sh: Configuring Postscreen
mailserver  | sed: can't read /etc/postfix/main.cf: No such file or directory
mailserver  | 2024-08-04 04:08:54+02:00 DEBUG start-mailserver.sh: Disabling Postscreen DNSBLs
mailserver  | postconf: fatal: open /etc/postfix/main.cf for reading: No such file or directory
mailserver  | postconf: fatal: open /etc/postfix/main.cf for reading: No such file or directory
mailserver  | 2024-08-04 04:08:56+02:00 DEBUG start-mailserver.sh: SpamAssassin is disabled
mailserver  | 2024-08-04 04:08:56+02:00 DEBUG start-mailserver.sh: Enabling and configuring ClamAV
mailserver  | 2024-08-04 04:08:56+02:00 DEBUG start-mailserver.sh: Fail2Ban is disabled
mailserver  | 2024-08-04 04:08:56+02:00 TRACE start-mailserver.sh: Configuring fail2ban logrotate rotate count and interval
mailserver  | 2024-08-04 04:08:56+02:00 DEBUG start-mailserver.sh: Configuring Amavis
mailserver  | postconf: fatal: open /etc/postfix/main.cf for reading: No such file or directory
mailserver  | 2024-08-04 04:08:57+02:00 DEBUG start-mailserver.sh: Enabling and configuring Rspamd
mailserver  | 2024-08-04 04:08:57+02:00 TRACE start-mailserver.sh: (Rspamd setup) ----------  Setup started  ----------
mailserver  | 2024-08-04 04:08:57+02:00 WARN  start-mailserver.sh: (Rspamd setup) Running Amavis/SA & Rspamd at the same time is discouraged
mailserver  | 2024-08-04 04:08:57+02:00 DEBUG start-mailserver.sh: (Rspamd setup) Internal Redis is enabled, adding configuration
mailserver  | 2024-08-04 04:08:57+02:00 DEBUG start-mailserver.sh: (Rspamd setup) Adjusting Postfix's configuration
mailserver  | postconf: fatal: open /etc/postfix/main.cf for reading: No such file or directory
mailserver  | stat: cannot statx '/etc/postfix/main.cf': No such file or directory
mailserver  | /usr/local/bin/helpers/utils.sh: line 99: 1722737338 -  : syntax error: operand expected (error token is "-  ")
mailserver  | 2024-08-04 04:08:58+02:00 DEBUG print-environment: Printing environment variables. Make sure no sensitive data is copied.
mailserver  | cat: /etc/dms-settings: No such file or directory
mailserver  | 2024-08-04 04:08:58+02:00 INFO  start-mailserver.sh: Starting daemons
mailserver  | 2024-08-04 04:08:58+02:00 DEBUG start-mailserver.sh: Starting cron
mailserver  | 2024-08-04 04:08:58+02:00 DEBUG start-mailserver.sh: Starting rsyslog
mailserver  | 2024-08-04 04:08:59+02:00 DEBUG start-mailserver.sh: Starting dovecot
mailserver  | 2024-08-04 04:08:59+02:00 DEBUG start-mailserver.sh: Starting update-check
mailserver  | 2024-08-04 04:08:59+02:00 DEBUG start-mailserver.sh: Starting rspamd-redis
mailserver  | 2024-08-04 04:08:59+02:00 DEBUG start-mailserver.sh: Starting rspamd
mailserver  | stat: cannot statx '/etc/postfix/main.cf': No such file or directory
mailserver  | /usr/local/bin/helpers/utils.sh: line 99: 1722737339 -  : syntax error: operand expected (error token is "-  ")
mailserver  | 2024-08-04 04:08:59+02:00 INFO  start-mailserver.sh: mail.mydomain.com is up and running
mailserver  | 2024-08-04T04:09:15.461816+02:00 mail dovecot: imap-login: Login: user=<myuser@mydomain.com>, method=PLAIN, rip=192.168.194.2, lip=172.20.0.2, mpid=673, TLS, session=<1AUdDNIe1FfAqMIC>
mailserver  | 2024-08-04T04:09:15.666686+02:00 mail dovecot: imap(myuser@mydomain.com)<673><1AUdDNIe1FfAqMIC>: Disconnected: Logged out in=98 out=1119 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
mailserver  | 2024-08-04T04:09:16.053500+02:00 mail dovecot: imap-login: Login: user=<myuser@mydomain | 2024-08-04T04:09:16.258490+02:00 mail dovecot: imap(myuser@mydomain.com)<675><3QwmDNIeJljAqMIC>: Error: file_dotlock_open(/var/mail/mydomain.com/myuser/dovecot.list.index.log) failed: Permission denied (euid=5000(docker) egid=5000(docker) missing +w perm: /var/mail/mydomain.com/myuser, dir owned by 0:0 mode=0755)
```

### Improvements to this form?

-/-
