### ISSUE TITLE
DMS cannot find a valid letsencrypt domain?

### ISSUE THREAD

**Issue by g40** [docker-mailserver/docker-mailserver#4193]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

mailserver fails with error and shuts down.

### 👟 Reproduction Steps

In `mailserver.env`, `OVERRIDE_HOSTNAME` is set to `s2.domain.tld`.

### 🐋 DMS Version

V14.0.0

### 💻 Operating System and Architecture

Ubuntu 24.04

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: s2.domain.tld
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
      - "110:110"
      - "995:995"  # POP3
    environment:
      - ENABLE_POP3=1
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### 📜 Relevant log output

```Text
mailserver  | 2024-09-23 11:39:04+00:00 DEBUG start-mailserver.sh: Setting up SSL
mailserver  | 2024-09-23 11:39:04+00:00 DEBUG start-mailserver.sh: TLS configured with 'intermediate' ciphers
mailserver  | 2024-09-23 11:39:04+00:00 DEBUG start-mailserver.sh: Configuring SSL using 'letsencrypt'
mailserver  | 2024-09-23 11:39:04+00:00 ERROR start-mailserver.sh: Cannot find a valid DOMAIN for '/etc/letsencrypt/live/<DOMAIN>/', tried: '', 's2.domain.tld', 'domain.tld'
mailserver  | 2024-09-23 11:39:04+00:00 ERROR start-mailserver.sh: _find_letsencrypt_domain | LETSENCRYPT_DOMAIN appears to be misconfigured, please verify.    
mailserver  | 2024-09-23 11:39:04+00:00 ERROR start-mailserver.sh: Shutting down
```

### Improvements to this form?

There could be a list to enable the specification of pertinent data i.e. `letsencrypt` is working properly and `testtls.com` reports are as expected.

This is a fabulous project!. Thank you.
