### ISSUE TITLE
bug report: "TROUBLE in pre_loop_hook: BDB can't create db env. at /var/lib/amavis/db: Permission denied"

### ISSUE THREAD

**Issue by Eirikr70** [docker-mailserver/docker-mailserver#4202]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

When activating Amavis, I always get the following error, and Amavis dies and restarts
```
mailserver  | 2024-09-28T17:48:47.868966+02:00 mail amavis[956]: (!!)TROUBLE in pre_loop_hook: BDB can't create db env. at /var/lib/amavis/db: Permission denied, Permission denied. at /usr/share/perl5/Amavis/DB.pm line 58.
mailserver  | 2024-09-28 17:48:47,881 WARN exited: amavis (exit status 255; not expected)
```

### 👟 Reproduction Steps

Set `ENABLE_AMAVIS=1` in `mailserver.env`

### 🐋 DMS Version

v14.0.0

### 💻 Operating System and Architecture

Debian 12

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail.xxx.fr
    domainname: xxx.fr
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
#      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
#      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - /srv/nas/mail/dms/mail-data/:/var/mail/
      - /srv/nas/mail/dms/mail-state/:/var/mail-state/
      - /srv/nas/logs:/var/log/mail
      - /srv/nas/mail/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /srv/nas/mail/fail2ban/:/etc/fail2ban/
#      - /srv/nas/mail/amavis:/var/lib/amavis
      - /home/eric/swag/config/etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
#    runtime: "runsc"

# volumes:
#   logs:
#     external: true
```

### 📜 Relevant log output

```Text
mailserver  | 2024-09-28 17:48:40+02:00 INFO  start-mailserver.sh: Welcome to docker-mailserver v14.0.0
mailserver  | 2024-09-28 17:48:40+02:00 INFO  start-mailserver.sh: Checking configuration
mailserver  | 2024-09-28 17:48:40+02:00 INFO  start-mailserver.sh: Configuring mail server
mailserver  | 2024-09-28 17:48:43+02:00 INFO  start-mailserver.sh: Starting daemons
mailserver  | 2024-09-28 17:48:45+02:00 INFO  start-mailserver.sh: mail.xxx.fr is up and running
mailserver  | 2024-09-28T17:48:47.227092+02:00 mail amavis[956]: starting. /usr/sbin/amavisd at mail.xxx.fr amavis-2.13.0 (20230106), Unicode aware, LC_CTYPE="C.UTF-8"
mailserver  | 2024-09-28T17:48:47.227119+02:00 mail amavis[956]: perl=5.036000, user=, EUID: 999 (999);  group=(), EGID: 999 999 (999 999)
mailserver  | 2024-09-28T17:48:47.815512+02:00 mail amavis[956]: Net::Server: Group Not Defined.  Defaulting to EGID '999 999'
mailserver  | 2024-09-28T17:48:47.815578+02:00 mail amavis[956]: Net::Server: User Not Defined.  Defaulting to EUID '999'
mailserver  | 2024-09-28T17:48:47.826402+02:00 mail amavis[956]: No ext program for   .zoo, tried: zoo
mailserver  | 2024-09-28T17:48:47.826455+02:00 mail amavis[956]: No ext program for   .doc, tried: ripole
mailserver  | 2024-09-28T17:48:47.826855+02:00 mail amavis[956]: No ext program for   .zst, tried: unzstd
mailserver  | 2024-09-28T17:48:47.826901+02:00 mail amavis[956]: No decoder for       .F   
mailserver  | 2024-09-28T17:48:47.826919+02:00 mail amavis[956]: No decoder for       .doc 
mailserver  | 2024-09-28T17:48:47.826936+02:00 mail amavis[956]: No decoder for       .zoo 
mailserver  | 2024-09-28T17:48:47.826951+02:00 mail amavis[956]: No decoder for       .zst 
mailserver  | 2024-09-28T17:48:47.868966+02:00 mail amavis[956]: (!!)TROUBLE in pre_loop_hook: BDB can't create db env. at /var/lib/amavis/db: Permission denied, Permission denied. at /usr/share/perl5/Amavis/DB.pm line 58.
mailserver  | 2024-09-28 17:48:47,881 WARN exited: amavis (exit status 255; not expected)
```
