### ISSUE TITLE
question: How to ensure outbound SMTP traffic is sent through a specific host interface when using a bridge network?

### ISSUE THREAD

**Issue by MarekPikula** [docker-mailserver/docker-mailserver#4206]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I followed [the guide](https://docker-mailserver.github.io/docker-mailserver/edge/examples/use-cases/bind-smtp-network-interface/) to bind SMTP to a specific network address. When I try to send an e-mail, there is the following message in logs:

```
postfix/smtp[1264]: warning: smtp_connect_addr: bind aaa.aaa.aaa.aaa: Cannot assign requested address
```

What is the solution to this? Do I need to run DMS with host network, or is there any other way with bridge network?

### 🐋 DMS Version

v14.0.0

### 💻 Operating System and Architecture

Fedora 39

### ⚙️ Container configuration files

```yml
version: '2'

services:
  mail:
    image: mailserver/docker-mailserver:latest
    hostname: mail
    domainname: xxx
    container_name: xxx_mail
    ports:
      - "aaa.aaa.aaa.aaa:25:25"
      - "aaa.aaa.aaa.aaa:143:143"
      - "aaa.aaa.aaa.aaa:465:465"
      - "aaa.aaa.aaa.aaa:587:587"
      - "aaa.aaa.aaa.aaa:993:993"
      - "aaa.aaa.aaa.aaa:995:995"
    volumes:
      - xxx_maildata:/var/mail
      - xxx_mailstate:/var/mail-state
      - xxx_maillog:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
      - /store/config/sys_certs/certs/xxx.crt:/tmp/cert.pem
      - /store/config/sys_certs/private/xxx.key:/tmp/key.pem
    environment:
      ENABLE_SPAMASSASSIN: 1
      ENABLE_CLAMAV: 1
      ENABLE_FAIL2BAN: 0
      ENABLE_POSTGREY: 0
      ONE_DIR: 1
      LOG_LEVEL: debug

      ACCOUNT_PROVISIONER: 'LDAP'
      LDAP_SERVER_HOST: 'ldap://ldap'
      LDAP_BIND_DN: 'cn=xxx,dc=xxx,dc=xxx'
      LDAP_BIND_PW: 'xxxxxx'
      LDAP_SEARCH_BASE: 'dc=xxx,dc=xxx'
      LDAP_QUERY_FILTER_DOMAIN: '(&(|(mail=%s)(gosaMailAlternateAddress=%s))(objectClass=inetOrgPerson)(memberof=cn=mail,ou=groups,o=xxx,dc=xxx,dc=xxx))'
      LDAP_QUERY_FILTER_USER: '(&(mail=%s)(objectClass=inetOrgPerson)(memberof=cn=mail,ou=groups,o=xxx,dc=xxx,dc=xxx))'
      LDAP_QUERY_FILTER_ALIAS: '(&(gosaMailAlternateAddress=%s)(objectClass=inetOrgPerson)(memberof=cn=mail,ou=groups,o=xxx,dc=xxx,dc=xxx))'
      LDAP_QUERY_FILTER_GROUP: '(&(mailGroupMember=%s)(objectClass=inetOrgPerson)(memberof=cn=mail,ou=groups,o=xxx,dc=xxx,dc=xxx))'
      SPOOF_PROTECTION: 1

      DOVECOT_USER_FILTER: '(&(objectClass=inetOrgPerson)(memberof=cn=mail,ou=groups,o=xxx,dc=xxx,dc=xxx)(|(uid=%u)(mail=%u)))'
      DOVECOT_PASS_ATTRS: 'mail=user,userPassword=password'
      DOVECOT_USER_ATTRS: '=user=%{ldap:mail},=home=/var/mail/%d/%n'

      ENABLE_SASLAUTHD: 0
      SASLAUTHD_LDAP_SERVER: 'ldap'
      SASLAUTHD_LDAP_BIND_DN: 'cn=xxx,dc=xxx,dc=xxx'
      SASLAUTHD_LDAP_PASSWORD: 'xxxxxx'
      SASLAUTHD_LDAP_SEARCH_BASE: 'dc=xxx,dc=xxx'
      SASLAUTHD_LDAP_FILTER: '(&(objectClass=inetOrgPerson)(memberof=cn=mail,ou=groups,o=xxx,dc=xxx,dc=xxx)(|(uid=%u)(mail=%u@%d)))'

      POSTFIX_MESSAGE_SIZE_LIMIT: 52428800
      POSTMASTER_ADDRESS: 'xxx@xxx'

      SSL_TYPE: manual
      SSL_CERT_PATH: '/tmp/cert.pem'
      SSL_KEY_PATH: '/tmp/key.pem'
    cap_add:
      - NET_ADMIN
    networks:
      - default
      - ldap
    restart: always
    labels:
      traefik.enable: "false"
      com.centurylinklabs.watchtower.enable: true

volumes:
  xxx_maildata:
    external: true
  xxx_mailstate:
    external: true
  xxx_maillog:
    external: true

networks:
  ldap:
    external:
      name: xxx_ldap_default
```

### 📜 Relevant log output

```Text
postfix/smtp[1264]: warning: smtp_connect_addr: bind aaa.aaa.aaa.aaa: Cannot assign requested address
```

**Comment by MarekPikula** [comment]
> > I followed [the guide](https://docker-mailserver.github.io/docker-mailserver/edge/examples/use-cases/bind-smtp-network-interface/) to bind SMTP to a specific network address.
> 
> The guide has two suggested ways to configure, but both suggest adding an entry to `postfix-master.cf`, did you do that? Or only the `postfix-main.cf`?

Yes, I modified both files. Here are their contents:

postfix-main.cf:
```ini
message_size_limit = 104857600
mailbox_size_limit = 5368709120
smtpd_sasl_type = dovecot
smtpd_sasl_path = private/auth
smtp_bind_address = 147.135.197.135
```

postfix-master.cf:
```ini
smtp-amavis/unix/smtp_bind_address = 127.0.0.1
```

> I've not verified either of these configurations myself, but from the context you've provided you're wanting to bind to a host interface? That won't be available to the container without host mode networking.

Currently, as shown in the attached docker-compose, I use bridge mode, and I want to keep using it. The mention about the host mode networking is because I think that it would solve the issue. My question is, if it is possible to do it **without** the host mode.

> Are you sure you actually need to configure this feature? You're already binding the host interface explicitly in your ports config, that should be sufficient?

Yes, I need to configure it, as I have multiple services on the same server, with multiple dedicated IPs. I want to assign a single IP to the mail server, and I don't want to send from the main server IP (which is the case now). I want to have the same IP for all services so that it matches the reverse DNS. In the future, I'm planning to make my setup less convoluted, but it's what it is for now. I was hoping this configuration would work.

**Comment by polarathene** [comment]
> My question is, if it is possible to do it **without** the host mode.

If the container is not aware of the host IP, how can it bind to it otherwise?

> Yes, I need to configure it, as I have multiple services on the same server, with multiple dedicated IPs.
> I want to assign a single IP to the mail server, and I don't want to send from the main server IP (which is the case now).

Just to confirm, when you publish the ports to that specific IP like `147.135.197.135:25:25` in `compose.yaml`, you are saying that DMS is sending mail out via one of your other host IPs?

Perhaps the port publishing is only for inbound connections 🤔 Yep that seems to be the case, someone shared how they resolved that with some custom rules: https://github.com/moby/moby/issues/30053#issuecomment-1077041045

So it would seem to get Dockers default bridge network driver to work this way you'll need to manually manage/maintain those extra routing rules. Alternatively use a relay host which can be helpful by using services like SendGrid for the sender reputation / trust they have with providers for improved delivery (less likely to be rejected or placed in spam/junk folder).

If you do follow the advice I linked and it works for you let us know, perhaps we can improve that docs page a bit more so it helps others in your situation 👍

**Comment by MarekPikula** [comment]
Ok, I spent the last few hours trying to make it work. Indeed port publishing is only for inbound connections. I landed on the following solution:

I set up the default network to be macvlan bound to the selected IP. Here are the modified parts of the docker-compose:

```yaml
services:
  mail:
    ...
    # Removed the ports section, as it's now managed by the container itself published via the macvlan interface.
    networks:
      mail:
        ipv4_address: aaa.aaa.aaa.aaa
        mac_address: "ab:cd:ef:gh:ij:kl"  # OVH provides per-IP MAC address. Without it it didn't work.
      ldap:
    ...

networks:
  mail:
    driver: macvlan
    driver_opts:
      parent: eth0
      macvlan_mode: bridge
    ipam:
      driver: default
      config:
        - subnet: "aaa.aaa.aaa.0/24"
          gateway: "aaa.aaa.aaa.254"
 ...
```

Mind that I have a dedicated server at OVH, and it's not guaranteed to work for other providers.

In the future, I'll probably use SendGrid or similar.
