### ISSUE TITLE
bug report: dkim creates new domain key, but doesn't add it to rpamd dkim_signing.conf

### ISSUE THREAD

**Issue by sr105** [docker-mailserver/docker-mailserver#4225]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I setup dms using a test domain before migrating my existing domain. Dkim worked well. I added my existing domain. I created another dkim key with `docker exec -ti mailserver setup config dkim domain old_domain.com`. The key was created. However, the server wasn't signing old_domain messages. I noticed the dkim_signing.conf under rspamd and manually added old_domain to the domain {...} block. I restarted with docker compose down/up and it works now.

### 👟 Reproduction Steps

Use rspamd instead of opendkim. Setup dkim. Add a second domain by adding a user with that domain. Setup dkim for the new domain. See that rspamd doesn't sign emails for new domain.

### 🐋 DMS Version

v14.0.0

### 💻 Operating System and Architecture

Ubuntu 24.10

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.tallyshow.com
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

  # TODO add letsencrypt certs to apache
  # TODO auto redirect http to https
  webmail:
    profiles: ['disabled']
    image: roundcube/roundcubemail:latest
    container_name: webmail
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=mailserver  # Uses container name and ports from above
      - ROUNDCUBEMAIL_SMTP_SERVER=mailserver
      - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=10M
      - ROUNDCUBEMAIL_SPELLCHECK_URI=http://spellcheck/index.php
    ports:
      # TODO I think I want this on 80?
      - "8000:80"
    volumes:
      - ./docker-data/roundcube/www:/var/www/html
      - ./docker-data/roundcube/db/sqlite:/var/roundcube/db

  spellcheck:
    # https://github.com/roundcube/google-spell-pspell
    # https://hub.docker.com/r/roundcube/google-spell-pspell
    image: roundcube/google-spell-pspell
    container_name: spellcheck

docker exec -ti mailserver setup config dkim domain old_domain.com

docker compose up -d
```
