### ISSUE TITLE
bug report: `timeout after DATA` - Incoming mail from some domains not being accepted

### ISSUE THREAD

**Issue by groupmsl** [docker-mailserver/docker-mailserver#4248]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Mail from some domains is not successfully being delivered to my mail server. I don't know enough to work out why. Yesterday I purchased something online and realised several hours later that I hadn't received a receipt - I looked at the logs and could see IKEA (where I made my purchase) trying to send a message, but failing. It turns out there are lots of other occurrences of this from other domains also, which I hadn't noticed.

Not all messages are failing though, and I'm not sure why this is. Below is an example of two messages that have failed to be received. I'd appreciate any help resolving this - let me know what other information/testing is required.

```
Nov  4 07:59:20 mail postfix/postscreen[6578]: CONNECT from [192.71.68.96]:16791 to [172.10.10.16]:25
Nov  4 07:59:20 mail postfix/postscreen[6578]: PASS OLD [192.71.68.96]:16791
Nov  4 07:59:20 mail postfix/smtpd[6614]: connect from mail12.ikea.com[192.71.68.96]
Nov  4 07:59:20 mail postfix/smtpd[6614]: Anonymous TLS connection established from mail12.ikea.com[192.71.68.96]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (4096 bits) server-digest SHA256
Nov  4 07:59:20 mail postfix/smtpd[6614]: 8EC0D54923C: client=mail12.ikea.com[192.71.68.96]
Nov  4 08:04:20 mail postfix/smtpd[6614]: timeout after DATA (621 bytes) from mail12.ikea.com[192.71.68.96]
Nov  4 08:04:20 mail postfix/smtpd[6614]: disconnect from mail12.ikea.com[192.71.68.96] ehlo=2 starttls=1 mail=1 rcpt=1 data=0/1 commands=5/6
```

```
Nov  4 08:26:39 mail postfix/postscreen[10820]: CONNECT from [195.14.81.131]:11199 to [172.10.10.16]:25
Nov  4 08:26:39 mail postfix/postscreen[10820]: PASS OLD [195.14.81.131]:11199
Nov  4 08:26:39 mail postfix/smtpd[10821]: connect from mailg.mountainwarehouse.com[195.14.81.131]
Nov  4 08:26:39 mail postfix/smtpd[10821]: Anonymous TLS connection established from mailg.mountainwarehouse.com[195.14.81.131]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Nov  4 08:26:39 mail postfix/smtpd[10821]: BD42B549239: client=mailg.mountainwarehouse.com[195.14.81.131]
Nov  4 08:31:39 mail postfix/smtpd[10821]: timeout after DATA (0 bytes) from mailg.mountainwarehouse.com[195.14.81.131]
Nov  4 08:31:39 mail postfix/smtpd[10821]: disconnect from mailg.mountainwarehouse.com[195.14.81.131] ehlo=2 starttls=1 mail=1 rcpt=1 data=0/1 commands=5/6
```

### 🐋 DMS Version

v13.2.0

### 💻 Operating System and Architecture

Debian 12

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:13.2.0
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail.MYDOMAIN.co.uk
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "993:993"  # IMAP4 (implicit TLS)
      - "11334:11334" # Rspamd HTTP interface
    volumes:
      - mailserver-data:/var/mail/
      - mailserver-state:/var/mail-state/
      - mailserver-logs:/var/log/mail/
      - mailserver-config:/tmp/docker-mailserver/
      - /data/servers/certs/acme.json:/etc/letsencrypt/acme.json:ro
      - /etc/localtime:/etc/localtime:ro
      - ./rspamdCustomCommands.conf:/tmp/docker-mailserver/rspamd/custom-commands.conf
      - ./rspamdDkimSigningConfig.conf:/tmp/docker-mailserver/rspamd/override.d/dkim_signing.conf
    networks:
      - services
      - default
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN

  mailserver-certwww: #NOTE" Even though all this container does is provide a static page, it MUST be running, as it provides and renews the certificate which the mailserver uses also
    build: ./certwww
    image: mailserver-certwww
    container_name: mailserver-certwww
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailserver-certwww-http.rule=Host(`mail.MYDOMAIN.co.uk`)"
      - "traefik.http.routers.mailserver-certwww-http.entrypoints=http"
      - "traefik.http.routers.mailserver-certwww-http.middlewares=https-redirect"
      - "traefik.http.routers.mailserver-certwww.rule=Host(`mail.MYDOMAIN.co.uk`)"
      - "traefik.http.routers.mailserver-certwww.entrypoints=https"
      - "traefik.http.routers.mailserver-certwww.tls.certresolver=letsencrypt"
      - "traefik.http.services.mailserver-certwww.loadbalancer.server.port=5000"
    networks:
      - services

  mailserver-imapfilter:
    build: ./imapfilter
    image: mailserver-imapfilter
    container_name: mailserver-imapfilter
    restart: always

  mailserver-webmail:
    image: roundcube/roundcubemail
    container_name: mailserver-webmail
    volumes:
      - mailserver-webmail:/var/roundcube/db
    restart: always
    networks:
      - services
    environment:
      - "ROUNDCUBEMAIL_DB_TYPE=sqlite"
      - "ROUNDCUBEMAIL_SKIN=elastic"
      - "ROUNDCUBEMAIL_DEFAULT_HOST=ssl://mail.MYDOMAIN.co.uk"
      - "ROUNDCUBEMAIL_DEFAULT_PORT=993"
      - "ROUNDCUBEMAIL_SMTP_SERVER=ssl://mail.MYDOMAIN.co.uk"
      - "ROUNDCUBEMAIL_SMTP_PORT=465"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailserver-webmail-http.rule=Host(`webmail.MYDOMAIN.co.uk`)"
      - "traefik.http.routers.mailserver-webmail-http.entrypoints=http"
      - "traefik.http.routers.mailserver-webmail-http.middlewares=https-redirect"
      - "traefik.http.routers.mailserver-webmail.rule=Host(`webmail.MYDOMAIN.co.uk`)"
      - "traefik.http.routers.mailserver-webmail.entrypoints=https"
      - "traefik.http.routers.mailserver-webmail.tls.certresolver=letsencrypt"
      - "traefik.http.services.mailserver-webmail.loadbalancer.server.port=80"

  mailserver-backup:
    build: ./backup
    image: mailserver-backup
    container_name: mailserver-backup
    volumes_from:
      - mailserver-backup-target
    volumes:
      - /data/servers/mailserver:/destination
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/lib/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  mailserver-backup-target:
    image: ghcr.io/docker-mailserver/docker-mailserver:13.2.0
    container_name: mailserver-backup-target
    hostname: mail-backup-target.MYDOMAIN.co.uk
    env_file: mailserver-backup-target.env
    ports:
      - "9143:143"  # IMAP4 (implicit TLS)
    volumes:
      - mailserver-backup-data:/var/mail/
      - mailserver-backup-config:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

volumes:
  mailserver-data:
    name: mailserver-data
    external: true # Remove this once server is rebuilt (this is a hangover from moving from compose v1 to v2)
  mailserver-state:
    name: mailserver-state
    external: true # Remove this once server is rebuilt (this is a hangover from moving from compose v1 to v2)
  mailserver-logs:
    name: mailserver-logs
    external: true # Remove this once server is rebuilt (this is a hangover from moving from compose v1 to v2)
  mailserver-config:
    name: mailserver-config
    external: true # Remove this once server is rebuilt (this is a hangover from moving from compose v1 to v2)
  mailserver-webmail:
    name: mailserver-webmail
    external: true # Remove this once server is rebuilt (this is a hangover from moving from compose v1 to v2)
  mailserver-backup-data:
    name: mailserver-backup-data
    external: true # Remove this once server is rebuilt (this is a hangover from moving from compose v1 to v2)
  mailserver-backup-config:
    name: mailserver-backup-config
    external: true # Remove this once server is rebuilt (this is a hangover from moving from compose v1 to v2)

networks:
  default:
    name: mailserver
    internal: true
  services:
    external: true
```
