### ISSUE TITLE
feature request: Add postfix-mysql and dovecot-mysql

### ISSUE THREAD

**Issue by Fmstrat** [docker-mailserver/docker-mailserver#4256]
### Context

I use this service two-fold:
- As a primary mail server
- As a mail relay

In the second case, when paired with any service such as VimBAdmin which uses configs like the below for, say, `domain_maps.cf`:

```
user = vimbadmin
password = <redacted>
hosts = vimbadmin-mariadb
dbname = vimbadmin
query = SELECT domain FROM domain WHERE domain = '%s' AND backupmx = '0' AND active = '1'
```

99% of custom configuration for this works, except that both `postfix` and `dovecot` are missing the mysql packages.

### Description

Add `postfix-mysql` and `dovecot-mysql` to the packages.

### Alternatives

Add an `ADDITIONAL_PACKAGES` variable that custom installs them (or anything else) at the beginning.

### Applicable Users

Me ;)

### Are you going to implement it?

Yes, because I know the probability of someone else doing it is low and I can learn from it.

### What are you going to contribute?

Would happily add the packages to https://github.com/docker-mailserver/docker-mailserver/blob/master/target/scripts/build/packages.sh if devs are OK with that.

**Comment by polarathene** [comment]
Our feature request policy is that anything which doesn't require much effort for a user to do does not get added. Only when there's sufficient interest from the community expressed to deem it worthwhile. So in the meantime you should be good with the advice below 👍 

In this case you can do so as shown in these examples:
- https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/dovecot-solr/#composeyaml
- https://github.com/docker-mailserver/docker-mailserver/issues/4145#issuecomment-2261773587

```yaml
services:
  mailserver:
    hostname: mail.example.com
    # The `image` setting now represents the tag for the local build configured below:
    image: local/dms:14.0
    # Local build (no need to try pull `image` remotely):
    pull_policy: build
    # Add this `build` section to your real `compose.yaml` for your DMS service:
    build:
      dockerfile_inline: |
        FROM docker.io/mailserver/docker-mailserver:14.0
        RUN apt-get update && apt-get install postfix-mysql dovecot-mysql
```

> ### Alternatives
> Add an `ADDITIONAL_PACKAGES` variable that custom installs them (or anything else) at the beginning.

You can just [leverage our `user-patches.sh` feature](https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/dovecot-solr/#user-patchessh) for this, it's a few extra lines but very flexible.

```yaml
services:
  mailserver:
    hostname: mail.example.com
    configs:
      - source: user-patches
        target: /tmp/docker-mailserver/user-patches.sh

configs:
  user-patches:
    content: |
      apt-get update && apt-get install postfix-mysql dovecot-mysql
```

Alternatively, instead of `configs` just bind mount a separate script file via `volumes`, up to you.
