### ISSUE TITLE
bug report:  Outlook Attachment Icon

### ISSUE THREAD

**Issue by alessiodeia** [docker-mailserver/docker-mailserver#4263]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I installed DMS version 14.0.0 using Docker Compose. Everything works fine, but I've discovered a potential bug or compatibility issue with Outlook 2016/2021. When I send an email, it is saved in the "Sent" folder and is marked as having an attachment.

I traced the cause of the attachment icon appearing to my signature, which includes an embedded image. I attempted to modify the HTML of the signature to include an img tag that loads a remote URL, but the icon still appears. However, when I move the email to a local PST file or another IMAP server, the attachment icon disappears.

What steps can I take to resolve this issue?

### 👟 Reproduction Steps

- Install DMS and create a mailbox
- Add mailbox to Outlook 2016/2021 via IMAP config
- Setup a signature with an embedded image
- Try to send an email with just the signature
- Optional: try to move the Sent email inside another IMAP server or local PST folder

### 🐋 DMS Version

v14.0.0

### 💻 Operating System and Architecture

Rocky Linux 9.4 (Blue Onyx)

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:14.0.0
    container_name: mailserver
    hostname: example.com
    env_file: mailserver.env
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - /root/docker/mailserver/mail-data/:/var/mail/
      - /root/docker/mailserver/mail-state/:/var/mail-state/
      - /root/docker/mailserver/mail-logs/:/var/log/mail/
      - /root/docker/mailserver/config/:/tmp/docker-mailserver/
      - /root/docker/mailserver/config/15-mailboxes.conf:/etc/dovecot/conf.d/15-mailboxes.conf:ro
      - /root/docker/mailserver/config/fts-xapian-plugin.conf:/etc/dovecot/conf.d/10-plugin.conf:ro
      # - /root/docker/mailserver/solr-dovecot/10-plugin.conf:/etc/dovecot/conf.d/10-plugin.conf:ro
      - /root/docker/mailserver/getmailrc_general:/etc/getmailrc_general
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    logging:
        driver: "json-file"
        options:
            max-size: "1m"
```
