### ISSUE TITLE
bug report: DKIM keys keys become invalid

### ISSUE THREAD

**Issue by Xirado** [docker-mailserver/docker-mailserver#4268]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Ever since i started using dms, i've had to redo the dkim setup (./setup.sh config dkim --force) because when testing the mailservers functionality using [MailGenius](https://www.mailgenius.com/spf-and-dkim-key-email-checker/) every few months, i get point deductions because

* Your DKIM record is incorrect or has a typo
* Your DKIM signature does not match the "from" domain.

Whenever i generate new keys and set the DNS entry it works again, until it all repeats. Are these keys meant to expire? I thought maybe the keys are not saved when i restart DMS, but since i get `rspamd-dkim: Not overwriting existing files (use '--force' to overwrite existing files)` when not using `--force` that tells me that they are.

### 🐋 DMS Version

v14.0.0

### 💻 Operating System and Architecture

Debian 11 (bullseye) x86_64

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:14.0.0
    container_name: mailserver
    hostname: mail.xxxxx.xxx
    env_file: mailserver.env
    networks:
      mailserver:
        ipv4_address: 10.10.2.2
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

networks:
  mailserver:
    name: mailserver
    ipam:
      config:
        - subnet: 10.10.2.0/24
          gateway: 10.10.2.1
```
