### ISSUE TITLE
Whitelist / DKIM and Rspamd

### ISSUE THREAD

**Issue by df911** [docker-mailserver/docker-mailserver#4270]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Emails from `@richissime.net` are reject by Rspamd due to `R_DKIM_PERMFAIL`.

```
R_DKIM_PERMFAIL (9) [richissime.net:s=acdkim1]
RBL_SENDERSCORE (2) [52.128.42.240:from]
SUBJECT_ENDS_QUESTION (1)
WHITELIST_SPF (-1) [richissime.net:s:+]
URI_COUNT_ODD (1) [7]
BAD_REP_POLICIES (0.1)
MIME_GOOD (-0.1) [multipart/alternative,text/plain]
HAS_LIST_UNSUB (-0.01)
XM_UA_NO_VERSION (0.01)
```

### 👟 Reproduction Steps

I have configured a whitelist into the `override.d` folder but have the same problem. I would like to receive the emails from this domain.

**`multimap.conf`:**

```
WHITELIST_SENDER_DOMAIN {
    type = "from";
    filter = "email:domain";
    map = "/etc/rspamd/override.d/whitelist.sender.domain.map";
    action = "accept";
    score = -9;
}

WHITELIST_SENDER_EMAIL {
    type = "from";
    map = "/etc/rspamd/override.d/whitelist.sender.email.map";
    action = "accept";
    score = -9;
}
```

**`whitelist.sender.domain.map`:**

```
richissime.net
.richissime.net
```

**`whitelist.sender.email.map`:**

```
hello@richissime.net
```

### 🐋 DMS Version

v14.0.0

### 💻 Operating System and Architecture

Docker

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    restart: always
    domainname: XXXXX
    ports:
      - "25:25"
      - "587:587"
      - "993:993"
      - "11334:11334" 
    volumes:
      - ./mailserver/mail-data/:/var/mail/
      - ./mailserver/mail-state/:/var/mail-state/
      - ./mailserver/mail-logs/:/var/log/mail/
      - ./mailserver/config/:/tmp/docker-mailserver/
      - ./mailserver/certs/:/etc/letsencrypt/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_FAIL2BAN=1
      - ENABLE_FETCHMAIL=1
      - FETCHMAIL_POLL=300
      - ENABLE_MTA_STS=1
      - SSL_TYPE=letsencrypt
      - PERMIT_DOCKER=connected-networks
      - ONE_DIR=1
      - ENABLE_POSTGREY=0
      - POSTGREY_DELAY=30
      - ENABLE_CLAMAV=0
      - ENABLE_RSPAMD=1
      - RSPAMD_LEARN=1
      - ENABLE_OPENDKIM=0
      - ENABLE_OPENDMARC=0
      - ENABLE_POLICYD_SPF=0
      - ENABLE_AMAVIS=0
      - ENABLE_SPAMASSASSIN=0
      - POSTFIX_MESSAGE_SIZE_LIMIT=30240000
      - SPOOF_PROTECTION=1
      - PFLOGSUMM_TRIGGER=daily_cron
      - PFLOGSUMM_RECIPIENT=XXXX
      - PFLOGSUMM_SENDER=xxx
      - REPORT_RECIPIENT=XXXx
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
```

### 📜 Relevant log output

```Text
R_DKIM_PERMFAIL (9) [richissime.net:s=acdkim1]
RBL_SENDERSCORE (2) [52.128.42.240:from]
SUBJECT_ENDS_QUESTION (1)
WHITELIST_SPF (-1) [richissime.net:s:+]
URI_COUNT_ODD (1) [7]
BAD_REP_POLICIES (0.1)
MIME_GOOD (-0.1) [multipart/alternative,text/plain]
HAS_LIST_UNSUB (-0.01)
XM_UA_NO_VERSION (0.01)
```

```
 rspamd_task_write_log: id: <0.0.5.5A.1DB38C81ED4AFFC.0@mail-42-241.acems1.com>, qid: <EFC2174403E2>, ip: 52.128.42.236, from: <bounce-3454596-215-26828-xXXx=xxxXx@em-3454596.richissime.net>, (default: T (add header): [10.95/11.00] [R_DKIM_PERMFAIL(9.00){richissime.net:s=acdkim1;},PHISHING(2.00){webinarjam.com->acemlna.com;},R_BAD_CTE_7BIT(1.05){7bit;utf8;},R_SPF_ALLOW(-1.00){+ip4:52.128.40.0/21;},MIME_GOOD(-0.10){multipart/alternative;text/plain;},HAS_LIST_UNSUB(-0.01){},XM_UA_NO_VERSION(0.01){},ARC_NA(0.00){},ASN(0.00){asn:14618, ipnet:52.128.42.0/24, country:US;},DBL_BLOCKED_OPENRESOLVER(0.00){XX:email;acemlna.com:url;fonts.googleapis.com:url;},DKIM_TRACE(0.00){richissime.net:~;},DMARC_BAD_POLICY(0.00){richissime.net : Multiple policies defined in DNS;},DNSWL_BLOCKED(0.00){52.128.42.236:from;},FORGED_SENDER_VERP_SRS(0.00){},FROM_HAS_DN(0.00){},FROM_NEQ_ENVFROM(0.00){hello@richissime.net;bounce-3454596-215-26828-XXXXXX@em-3454596.richissime.net;},MIME_TRACE(0.00){0:+;1:+;2:~;},PREVIOUSLY_DELIVERED(0.00){XXXX;},RCPT_COUNT_ONE(0.00){1;},RCVD_COUNT_TWO(0.00){2;},RCVD_TLS_LAST(0.00){},SUBJECT_HAS_EXCLAIM(0.00){},TO_DN_ALL(0.00){},TO_MATCH_ENVRCPT_ALL(0.00){},URIBL_BLOCKED(0.00){acemlna.com:url;XXXX:email;fonts.googleapis.com:url;mail-42-236.acems1.com:helo;mail-42-236.acems1.com:rdns;webinarjam.com:url;}]), len: 32253, time: 1229.140ms, dns req: 53, digest: <f75b3ae0733bc134bf7e4ee206e8e115>, rcpts: <XXXXX>, mime_rcpts: <XXXX>
```
