### ISSUE TITLE
bug report: RSpamd incorrectly tags mail from amazon as spam due to SPF fail.

### ISSUE THREAD

**Issue by hapklaar** [docker-mailserver/docker-mailserver#4275]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Mail received from amazon.nl is marked as spam by Rspamd because of R_SPF_FAIL and VIOLATED_DIRECT_SPF. This is not correct as the sending IP is part of amazon.nl's SPF record.

As far as I have seen, this only happens with mail from amazon. In the example below the envelope from is 

### 👟 Reproduction Steps

Order something at amazon.nl :) Every mail received from them will be tagged as spam.

Tried some debugging in the container with rspamc and rspamadm commands, documented the results here https://github.com/rspamd/rspamd/issues/5204#issuecomment-2443937672 for results

### 🐋 DMS Version

14.0.0

### 💻 Operating System and Architecture

Ubuntu 20.04.6 LTS

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: host.hostname.tld
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
      - "11334:11334"   # RSPAMD WEBUI  
    dns:
      - <dns ip>
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - ./docker-data/dms/cron/sa-learn:/etc/cron.d/sa-learn
      - /etc/localtime:/etc/localtime:ro
      - ./docker-data/certbot/certs/:/etc/letsencrypt/
      - ./docker-data/dms/config/dovecot/fts-xapian-plugin.conf:/etc/dovecot/conf.d/10-plugin.conf:ro
      - ./docker-data/dms/cron/fts_xapian:/etc/cron.d/fts_xapian
    restart: always
    stop_grace_period: 1m
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    cap_add:
      - NET_ADMIN
```

### 📜 Relevant log output

```Text
R_SPF_FAIL (4.5) [-all]
VIOLATED_DIRECT_SPF (3.5)
R_DKIM_ALLOW (-1) [amazon.nl:s=pocyounenvo3pduufuztshjwld4syrfk,amazonses.com:s=uku4taia5b5tsbglxyj6zym32efj7xqv]
RWL_MAILSPIKE_EXCELLENT (-0.4) [54.240.1.135:from]
FORGED_SENDER (0.3) [update-bestelling@amazon.nl,202411251257185aba5200e99b4f9a8fe990c829b0p0eu-C1KT32N8F95D4L@bounces.amazon.com]
MIME_GOOD (-0.1) [multipart/alternative,text/plain]
ASN (0) [asn:16509, ipnet:54.240.0.0/21, country:US]
```
