### ISSUE TITLE
bug report: Problem with changing attachment size

### ISSUE THREAD

**Issue by rafalolb** [docker-mailserver/docker-mailserver#4280]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Hello, 

I set parameters by `compose.yaml`:

```yaml
environment:
  POSTFIX_MESSAGE_SIZE_LIMIT: 102400000
  CLAMAV_MESSAGE_SIZE_LIMIT:  150M
```

But if I open new mail by android Gmail app and I want to add attachment more than 10MB I get info:
"Max size of attachment is 10.2 MB"

I connect to my docker-mailserver and I check parameter, which are set correctly. 

What doing wrong? Please help me

### 🐋 DMS Version

v14.0.0

### 💻 Operating System and Architecture

Raspbian

**Comment by polarathene** [comment]
I'm not sure how the mail client would get max attachment size info prior to sending mail.

If you get the error when sending the mail, then make sure you [follow our docs advice properly](https://docker-mailserver.github.io/docker-mailserver/v14.0/config/debugging/#preliminary-checks) (_the very first part of the issue that you stated you did_) and restart the container correctly when changing config: `docker compose up --force-recreate`

---

## Example

Copy/paste this to a `compose.yaml` to run locally:

```yaml
services:
  dms:
    image: mailserver/docker-mailserver:14
    hostname: mail.example.localhost
    environment:
      # For using `swaks` with port 25 within the DMS container bypass security checks with:
      PERMIT_DOCKER: container
      # `message_size_limit`: https://www.postfix.org/postconf.5.html#message_size_limit
      # Default: 10.24MB, configured here to 102.4MB:
      POSTFIX_MESSAGE_SIZE_LIMIT: 102400000

# This example uses the Docker Compose `configs` feature instead of separate files so you can copy/paste this `compose.yaml`
# - The feature is compatible with any Compose release since 2024.
# - The character `$` below is changed to `$$` to opt-out of accidental variable interpolation (Compose feature).
configs:
  # An account provisioned for you already:
  # - Username: john.doe@example.test
  # - Password: secret
  dms-accounts:
    content: |
      john.doe@example.test|{SHA512-CRYPT}$$6$$sbgFRCmQ.KWS5ryb$$EsWrlYosiadgdUOxCBHY0DQ3qFbeudDhNMqHs6jZt.8gmxUwiLVy738knqkHD4zj4amkb296HFqQ3yDq4UXt8.
```

Here are the commands:

```
# Use `--force-recreate` to ensure a container is always recreated when you make changes:
$ docker compose up -d --force-recreate
$ docker compose exec -it dms bash

# Create a sparse file of 20MB in size
$ truncate --size 20MB /tmp/some-file.txt

# Use the swaks command in the container to test sending that attachment:
# This simulates mail arriving from another mail server on port 25 for one of your users,
# but due to `PERMIT_DOCKER: container` some security checks are skipped:
$ swaks --port 25 --from hello@not-relevant.test --to john.doe@example.test --attach @/tmp/some-file.txt --silent
```

The `--silent` flag is used to avoid noise, since the default output will otherwise show the raw mail with 20MB body attached.

Without setting `POSTFIX_MESSAGE_SIZE_LIMIT: 102400000`, the output would show this error for the `swaks` command:

```
<** 552 5.3.4 Error: message file too big
 -> QUIT
<-  221 2.0.0 Bye
=== Connection closed with remote host.
```

A successful delivery/submission will have no output. You can verify successful delivery to Dovecot via:
- `docker compose logs dms`
- A mail client accessing the inbox via IMAP
- Checking the size of `/var/mail`.

**NOTE:** If you need to test with authenticated submission instead of port 25, `PERMIT_DOCKER` ENV is not required, swap `swaks --port 25` for any of:
- `swaks --port 587 --auth-user john.doe@example.test --auth-password secret` (_no TLS for port 587, normally forbidden in DMS_)
- `swaks --port 587 -tls --auth-user john.doe@example.test --auth-password secret` (_`-tls` for port 587_)
- `swaks --port 465 -tlsc --auth-user john.doe@example.test --auth-password secret` (_`-tlsc` for port 465_)

**NOTE:** This example provides a file to `swaks` to attach, which is encoded via base64. Base64 increases the attachment size by approx 1.3x. Thus a 102.4MB limit reflects the attachment size Postfix receives (base64 encoded). Hence a 100MB file will exceed that limit, it's more like 75MB:

```console
$ truncate --size 75MB /tmp/some-file.txt
$ cat /tmp/some-file.txt | base64 > /tmp/some-file.txt.b64 && ls -l /tmp

-rw-r--r-- 1 root root  75000000 Dec  5 22:54 some-file.txt
-rw-r--r-- 1 root root 101315790 Dec  5 22:54 some-file.txt.b64
```
