### ISSUE TITLE
bug report: rspamd crashes due to bind `127.0.0.1:11332`

### ISSUE THREAD

**Issue by Eyecu** [docker-mailserver/docker-mailserver#4281]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

When starting DMS, or attempting to restart rspamd it gives an error that `127.0.0.1:11332` is already in use, and rspamd fails and just continues to attempt to restart over and over. I can't stop/kill it and it wont stay started long enough to keep a pid. 

### 👟 Reproduction Steps

start mailserver docker or restart rspamd.

### 🐋 DMS Version

v14.0.0

### 💻 Operating System and Architecture

Debian 12 bookworm

### ⚙️ Container configuration files

```yml
mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: openadmin_mailserver
    hostname: serv1.csnode.com
    env_file: mailserver.env
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "4190:4190"
      - "11334:11334"
    environment:
      - SSL_TYPE=letsencrypt
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/:/home/
    restart: always
    stop_grace_period: 1m
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    networks:
      - network
    cap_add:
      - NET_ADMIN

ENV file settings for rspamd
# Enables Rspamd
# **0** => Disabled
#   1   => Enabled
ENABLE_RSPAMD=1

# When `ENABLE_RSPAMD=1`, an internal Redis instance is enabled implicitly.
# This setting provides an opt-out to allow using an external instance instead.
# 0 => Disabled
# 1 => Enabled
ENABLE_RSPAMD_REDIS=

# When enabled,
#
# 1. the "[autolearning][rspamd-autolearn]" feature is turned on;
# 2. the Bayes classifier will be trained when moving mails from or to the Junk folder (with the help of Sieve scripts).
#
# **0** => disabled
# 1     => enabled
RSPAMD_LEARN=1

# This settings controls whether checks should be performed on emails coming
# from authenticated users (i.e. most likely outgoing emails). The default value
# is `0` in order to align better with SpamAssassin. We recommend reading
# through https://rspamd.com/doc/tutorials/scanning_outbound.html though to
# decide for yourself whether you need and want this feature.
#
# Note that DKIM signing of e-mails will still happen.
RSPAMD_CHECK_AUTHENTICATED=1

# Controls whether the Rspamd Greylisting module is enabled.
# This module can further assist in avoiding spam emails by greylisting
# e-mails with a certain spam score.
#
# **0** => disabled
# 1     => enabled
RSPAMD_GREYLISTING=1

# Can be used to enable or disable the Hfilter group module.
#
# - 0     => Disabled
# - **1** => Enabled
RSPAMD_HFILTER=1

# Can be used to control the score when the HFILTER_HOSTNAME_UNKNOWN symbol applies. A higher score is more punishing. Setting it to 15 is equivalent to rejecting the email when the check fails.
#
# Default: 6
RSPAMD_HFILTER_HOSTNAME_UNKNOWN_SCORE=6

# Can be used to enable or disable the (still experimental) neural module.
#
# - **0** => Disabled
# - 1     => Enabled
RSPAMD_NEURAL=0
```

### 📜 Relevant log output

```Text
2024-12-05 13:32:39 #7215(main) rspamd_inet_address_listen: bind 127.0.0.1:11332 failed: 98, 'Address already in use'
2024-12-05 13:32:39 #7215(main) <c18855>; main; spawn_workers: cannot listen on normal socket 127.0.0.1:11332: Address already in use
2024-12-05 13:32:39 #7215(main) <c18855>; main; spawn_workers: cannot create listen socket for rspamd_proxy at 127.0.0.1:11332
2024-12-05 13:32:39 #7215(main) <c18855>; main; rspamd_hard_terminate: shutting down Rspamd due to fatal error
```
