### ISSUE TITLE
bug report: DMS picking up wrong Let'sEncrypt certificate

### ISSUE THREAD

**Issue by Pendrag00n** [docker-mailserver/docker-mailserver#4288]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I have the certificates for two domains with different TLD inside `/etc/letsencrypt/live/`. One is _example.xyz_ and the other _example.net_ (The .xyz one was used for my old mailserver, I'm migrating to .net). When trying to spin up the container, it seems to pick the certificate for the .xyz domain instead of the .net one.
I've also tried feeding the cert and key manually using `SSL_TYPE=manual` with no success.
Am I missing something?

### 🐋 DMS Version

v14.0.0

### 💻 Operating System and Architecture

Debian GNU/Linux bookworm 12.8 aarch64

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: DMS
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.EXAMPLE.net
    environment:
      - SSL_TYPE=letsencrypt
      #- SSL_CERT_PATH=/tmp/dms/custom-certs/fullchain1.pem
      #- SSL_KEY_PATH=/tmp/dms/custom-certs/privkey1.pem
      #- ENABLE_RSPAMD=0
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      #- "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      #- "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```
