### ISSUE TITLE
bug report: Running DMS made my server unresponsive

### ISSUE THREAD

**Issue by finallight1** [docker-mailserver/docker-mailserver#4298]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

After launching the compose.yml example for the repository and bashing into the container, running the command `setup email add` resulted in freezing the entire AWS server. No reponses, all other services are frozen too and the reboot simply hangs the on the "Rebooting" state for hours.

### 👟 Reproduction Steps

- Using the example compose.yml file from the docs
- Changing the hostname to my domain
- Composing the mailserver
- Running `docker exec -it mailserver bash`
- Running `setup email add admin@{mydomain} {mypassword}` (Not the actual fields I have written of course)

### 🐋 DMS Version

v14.0.0

### 💻 Operating System and Architecture

Debian 12 amd64

### ⚙️ Container configuration files

```yml
name: 'dev-server'

services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: {mydomain}
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### 📜 Relevant log output

```Text
I am unable to retrieve any logs because the server is bricked
```
