### ISSUE TITLE
bug report: sasl auth with sending messages from connected-network

### ISSUE THREAD

**Issue by Bader-Idris** [docker-mailserver/docker-mailserver#4300]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Dear [Creators/Support Team],

I have been trying for a week to resolve an issue and have read half a book about Postfix, but I am still encountering an error. I have a functioning ExpressJS application that uses Nginx as a reverse proxy and has Let's Encrypt certificates.

I utilized the following Docker Compose service for the mail server:

```yaml
mail:
  image: mailserver/docker-mailserver:14.0
  container_name: mail
  hostname: mail.baderidris.com
  env_file: ./server/config/mailserver/mailserver.env
  ports:
    - "25:25" 
    - "143:143"
    - "465:465"
    - "587:587"
    - "993:993"
  volumes:
    - ./server/mailserver/mail-data:/var/mail/
    - ./server/mailserver/mail-state:/var/mail-state/
    - ./server/mailserver/mail-logs:/var/log/mail/
    - ./server/mailserver/config/:/tmp/docker-mailserver/
    - /etc/localtime:/etc/localtime:ro
    - certbot-etc:/etc/letsencrypt
    - certbot-var:/var/lib/letsencrypt
  # restart: always
  stop_grace_period: 1m
  # Uncomment if using `ENABLE_FAIL2BAN=1`:
  cap_add:
    - NET_ADMIN
  healthcheck:
    test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
    timeout: 3s
    retries: 0
  networks:
    - app-network

networks:
  app-network:
    driver: bridge
```

I have also added the following environment variables:

```sh
OVERRIDE_HOSTNAME=mail.baderidris.com
DMS_DEBUG=0
LOG_LEVEL=info
POSTMASTER_ADDRESS=postmaster@baderidris.com
ENABLE_UPDATE_CHECK=1
UPDATE_CHECK_INTERVAL=1d
PERMIT_DOCKER=connected-networks
ENABLE_SRS=0
ENABLE_OPENDKIM=1
ENABLE_OPENDMARC=1
ENABLE_POLICYD_SPF=1
ENABLE_IMAP=1
ENABLE_CLAMAV=0
ENABLE_RSPAMD=0
RSPAMD_LEARN=0
RSPAMD_CHECK_AUTHENTICATED=0
RSPAMD_GREYLISTING=0
RSPAMD_HFILTER=1
RSPAMD_HFILTER_HOSTNAME_UNKNOWN_SCORE=6
RSPAMD_NEURAL=0
ENABLE_AMAVIS=1
AMAVIS_LOGLEVEL=0
ENABLE_DNSBL=0
ENABLE_FAIL2BAN=1
FAIL2BAN_BLOCKTYPE=drop
ENABLE_MANAGESIEVE=1
POSTSCREEN_ACTION=enforce
SSL_TYPE=letsencrypt
LOGROTATE_INTERVAL=weekly
LOGROTATE_COUNT=4
POSTFIX_REJECT_UNKNOWN_CLIENT_HOSTNAME=0
POSTFIX_INET_PROTOCOLS=all
ENABLE_MTA_STS=0
DOVECOT_INET_PROTOCOLS=all
ENABLE_SPAMASSASSIN=0
ENABLE_SPAMASSASSIN_KAM=0
SPAMASSASSIN_SPAM_TO_INBOX=1
MOVE_SPAM_TO_JUNK=1
MARK_SPAM_AS_READ=0
SA_TAG=2.0
SA_TAG2=6.31
SA_KILL=10.0
ENABLE_FETCHMAIL=0
FETCHMAIL_POLL=300
FETCHMAIL_PARALLEL=0
ENABLE_GETMAIL=0
GETMAIL_POLL=5
DOVECOT_MAILBOX_FORMAT=maildir
ENABLE_POSTGREY=1
POSTGREY_DELAY=300
POSTGREY_MAX_AGE=35
POSTGREY_TEXT="Delayed by Postgrey"
POSTGREY_AUTO_WHITELIST_CLIENTS=5
ENABLE_SASLAUTHD=1
SRS_SENDER_CLASSES=envelope_sender
```

I have also executed the necessary setup commands to enable email sending:

```sh
docker exec -it mail setup email add contact@baderidris.com secret
docker exec -it mail setup dovecot-master add postmaster secret
docker exec -it mail setup config dkim domain 'baderidris.com'
```

When I send messages from the root user, they are received correctly using the following command:

```sh
(
echo "To: client <user@gmail.com>"
echo "Reply-to: Bader Idris <contact@baderidris.com>"
echo "Subject: Test Email from Postfix"
echo "From: Bader Idris <contact@baderidris.com>"
echo ""
echo "This is a test email sent from Postfix using sendmail."
) | sendmail -t
```

🔴 However, the issue arises when I attempt to send messages from my ExpressJS application with the following configuration: 🔴

```js
module.exports = {
  host: "mail", 
  port: 587, // Use STARTTLS
  secure: false, // Set to false for STARTTLS
  auth: {
    user: "contact@baderidris.com",
    pass: "secret",
  },
  tls: {
    rejectUnauthorized: false,
  },
};
```

I receive the following error: `sasl auth error`

```sh
mail postfix/submission/smtpd[5199]: warning: SASL authentication failure: Password verification failed
```

I would greatly appreciate any assistance or guidance you can provide to help resolve this issue.

Thank you for your time and support.

Best regards,
Bader Idris

### 👟 Reproduction Steps

how can I send messages from my containers externally, as when sending verification emails to my clinets

### 🐋 DMS Version

14.0.0

### 💻 Operating System and Architecture

Ubuntu 24.04.1 LTS x86_64
