### ISSUE TITLE
bug report: Second domain gets Client host rejected: Access denied

### ISSUE THREAD

**Issue by Togtja** [docker-mailserver/docker-mailserver#4308]
### 📝 Preliminary Checks

- [X] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

After adding a second domain to the mail server it is unable to send any emails and revives the error in the title and logs.
The second domain `Domain B` has a Let's Encrypt certificated created the same way as `Domain A` but different domains obviously.
It also has it's own DKIM entry:
`dms/config/rspamd/override.d/dkim_signing.conf`:
```env
# documentation: https://rspamd.com/doc/modules/dkim_signing.html

enabled = true;

sign_authenticated = true;
sign_local = true;
try_fallback = false;

use_domain = "header";
use_redis = false; # don't change unless Redis also provides the DKIM keys
use_esld = true;
#allow_username_mismatch = true;

check_pubkey = true; # you want to use this in the beginning
domain {
    domainA.com {
        path = "/tmp/docker-mailserver/rspamd/dkim/rsa-2048-mail-domainA.com.private.txt";
        selector = "mail";
    }
    domainB.com {
        path = "/tmp/docker-mailserver/rspamd/dkim/rsa-2048-mail-domainB.com.private.txt";
        selector = "mail";
    }
}


```

DomainA's relevant zonefile
```
*.domainA.com.		        600	IN	A	MY_IP
domainA.com.		        600	IN	MX	10 mail.domainA.com.
mail.domainA.com.		600	IN	A	MY_IP 
_dmarc.domainA.com.		600	IN	TXT	"v=DMARC1; ......"
domainA.com.			600	IN	TXT	"v=spf1 a mx ip4:MY_IP ~all"
mail._domainkey.domainA.com.	600	IN	TXT	"v=DKIM1; k=rsa; <generated from mailserver>"
```
DomainB's relevant zonefile
```
*.domainB.com.		        600	IN	A	MY_IP
domainB.com.		        600	IN	MX	10 mail.domainA.com.
mail.domainB.com.		600	IN	A	MY_IP 
_dmarc.domainB.com.		600	IN	TXT	"v=DMARC1; ......"
domainB.com.			600	IN	TXT	"v=spf1 a mx ip4:MY_IP ~all"
mail._domainkey.domainB.com.	600	IN	TXT	"v=DKIM1; k=rsa; ...... <generated from mailserver>"
```
Different DKIM but both points to `MX mail.domainA.com`

### 🐋 DMS Version

v14.0.0

### 💻 Operating System and Architecture

Ubuntu 24.04.1 LTS

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.domainA.no
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    ports:
      - "25:25" # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143" # IMAP4 (explicit TLS => STARTTLS)
      - "465:465" # ESMTP (implicit TLS)
      - "587:587" # ESMTP (explicit TLS => STARTTLS)
      - "993:993" # IMAP4 (implicit TLS)
    volumes:
      - ./data/dms/mail-data/:/var/mail/
      - ./data/dms/mail-state/:/var/mail-state/
      - ./data/dms/mail-logs/:/var/log/mail/
      - ./data/dms/config/:/tmp/docker-mailserver/
      - ./data/certbot/certs/:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### 📜 Relevant log output

```Text
mailserver  | 2025-01-11T21:12:40.418120+01:00 mail postfix/submissions/smtpd[1242]: connect from unknown[myip]
mailserver  | 2025-01-11T21:12:40.427726+01:00 mail postfix/submissions/smtpd[1242]: Anonymous TLS connection established from unknown[myip]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature ECDSA (prime256v1) server-digest SHA256
mailserver  | 2025-01-11T21:12:40.499256+01:00 mail postfix/submissions/smtpd[1242]: NOQUEUE: reject: RCPT from unknown[myip]: 554 5.7.1 <unknown[myip]>: Client host rejected: Access denied; from=<user@domainB> to=<test-jxaj9dmku@srv1.mail-tester.com> proto=ESMTP helo=<[192.168.1.183]>
mailserver  | 2025-01-11T21:12:40.511292+01:00 mail postfix/submissions/smtpd[1242]: lost connection after RCPT from unknown[myip]
mailserver  | 2025-01-11T21:12:40.511387+01:00 mail postfix/submissions/smtpd[1242]: disconnect from unknown[myip] ehlo=1 mail=1 rcpt=0/1 commands=2/3
```
