### ISSUE TITLE
Assess relevance of keeping Pyzor + Razor

### ISSUE THREAD

**Issue by polarathene** [docker-mailserver/docker-mailserver#4351]
### Subject

Something else that requires developers attention

### Description

This investigation was motivated by the associated `Dockerfile` content.

We don't have much context on relevance / demand for these packages and their inclusion into DMS, beyond several maintenance issues.

@casperklein since you use Amavis + SpamAssassin this may be relevant to you. I'm not sure how important these packages are (_they apparently [were of value at least 20 years ago](https://narkive.com/T6bs693J.5)_ 😅 )

No immediate action required, this is just public documentation of my notes when looking into this area of DMS.

## Pyzor integration broken since DMS v14?

Reference: [Pyzor docs](https://www.pyzor.org/en/latest/)

I assume not much thought was given to these packages and the original DMS author just added them by following some guide online for Amavis + SpamAssassin at the time.

It doesn't seem like `razor` is necessary for `pyzor` at a glance, but I've only observed Pyzor being included by SpamAssassin scan results, which [our docs show an example of](https://docker-mailserver.github.io/docker-mailserver/v14.0/config/environment/#sa_tag) (_[direct link to docs source](https://github.com/docker-mailserver/docker-mailserver/blob/59a379aed781d8e66b9388491aed245a9f5d9af1/docs/content/config/environment.md?plain=1#L610-L613)_):

> ![Image](https://github.com/user-attachments/assets/a637ab3a-7fff-4e32-8e84-09256217b864)

However I've also noticed that I cannot reproduce this `PYZOR_CHECK=1.985` addition from DMS v14 onwards (_[v14 changelog](https://github.com/docker-mailserver/docker-mailserver/releases/tag/v14.0.0)_), something has presumably changed?

I know I documented the [SpamAssassin changes with Debian 12 rather heavily](https://github.com/docker-mailserver/docker-mailserver/pull/3403#discussion_r1306282387), but installing `spamd` package and running it with `/etc/init.d/spamd start` (_`/etc/init.d/spamassassin start` on Debian 11 / DMS v13.3.1_) didn't make a difference.

```yaml
services:
  dms:
    image: ghcr.io/docker-mailserver/docker-mailserver:13.3.1
    hostname: mail.example.test
    environment:
      ENABLE_AMAVIS: 1
      ENABLE_SPAMASSASSIN: 1
      # For running swaks command:
      PERMIT_DOCKER: container
    configs:
      - source: dms-accounts-getmail
        target: /tmp/docker-mailserver/postfix-accounts.cf

configs:
  dms-accounts-getmail:
    content: |
      john.doe@example.test|{SHA512-CRYPT}$$6$$sbgFRCmQ.KWS5ryb$$EsWrlYosiadgdUOxCBHY0DQ3qFbeudDhNMqHs6jZt.8gmxUwiLVy738knqkHD4zj4amkb296HFqQ3yDq4UXt8.
```

```bash
docker compose up -d --force-recreate
docker compose exec -it dms bash

# Send mail (doesn't qualify as actual spam):
swaks --server 0.0.0.0 --to john.doe@example.test --body 'spam'

# View the mail:
less /var/mail/example.test/john.doe/new/*

# Send a spam mail (GTUBE test pattern):
swaks --server localhost --to john.doe@example.test --body 'XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X'

less /var/mail/example.test/john.doe/.Junk/new/*
```

<details>
<summary>Example - GTUBE with DMS v13.3.1</summary>

```
Return-Path: <root@mail.example.test>
Delivered-To: john.doe@example.test
Received: from mail.example.test
        by mail.example.test with LMTP
        id zUb8EOm3qWeiEAAAUi6ngw
        (envelope-from <root@mail.example.test>)
        for <john.doe@example.test>; Mon, 10 Feb 2025 08:25:13 +0000
Received: from localhost (localhost [127.0.0.1])
        by mail.example.test (Postfix) with ESMTP id 322011A3D0C
        for <john.doe@example.test>; Mon, 10 Feb 2025 08:25:13 +0000 (UTC)
X-Quarantine-ID: <gyXeL7wz45n5>
X-Spam-Flag: YES
X-Spam-Score: 1000.985
X-Spam-Level: ****************************************************************
X-Spam-Status: Yes, score=1000.985 tagged_above=2 required=6.31
        tests=[ALL_TRUSTED=-1, GTUBE=1000, PYZOR_CHECK=1.985]
        autolearn=no autolearn_force=no
Received: from mail.example.test (localhost [IPv6:::1])
        by mail.example.test (Postfix) with ESMTP id 6118A1A3CAD
        for <john.doe@example.test>; Mon, 10 Feb 2025 08:25:08 +0000 (UTC)
Date: Mon, 10 Feb 2025 08:25:08 +0000
To: john.doe@example.test
From: root@mail.example.test
Subject: ***SPAM*** test Mon, 10 Feb 2025 08:25:08 +0000
Message-Id: <20250210082508.004238@mail.example.test>

XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X
```

</details>

<details>
<summary>Example - GTUBE with DMS v14.0.0</summary>

```
Return-Path: <root@mail.example.test>
Delivered-To: john.doe@example.test
Received: from mail.example.test
        by mail.example.test with LMTP
        id RrbgErDQqWdwAwAAUi6ngw
        (envelope-from <root@mail.example.test>)
        for <john.doe@example.test>; Mon, 10 Feb 2025 10:10:56 +0000
Received: from localhost (localhost [127.0.0.1])
        by mail.example.test (Postfix) with ESMTP id 300911A3CB5
        for <john.doe@example.test>; Mon, 10 Feb 2025 10:10:56 +0000 (UTC)
X-Quarantine-ID: <NTL2rqm0XTRx>
X-Spam-Flag: YES
X-Spam-Score: 999
X-Spam-Level: ****************************************************************
X-Spam-Status: Yes, score=999 tagged_above=2 required=6.31
 tests=[ALL_TRUSTED=-1, GTUBE=1000] autolearn=no autolearn_force=no
Received: from mail.example.test (localhost [IPv6:::1])
        by mail.example.test (Postfix) with ESMTP id 5AA991A3C6E
        for <john.doe@example.test>; Mon, 10 Feb 2025 10:10:53 +0000 (UTC)
Date: Mon, 10 Feb 2025 10:10:53 +0000
To: john.doe@example.test
From: root@mail.example.test
Subject: test Mon, 10 Feb 2025 10:10:53 +0000
Message-Id: <20250210101053.000869@mail.example.test>

XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X
```

</details>

The score is `999` (GTUBE 1000, minus one point for trust), while v13.3.1 had almost 2 more points contributed by Pyzor. Unclear why it's not run in DMS v14, although `python3 --version` difference is 3.9.2 vs 3.11.2, and Pyzor 1.0.0 (2014) may have a compatibility issue there, replacing it with Pyzor 1.1.2 (Sep 2024) may fix it. The project [development history hasn't been too encouraging](https://github.com/SpamExperts/pyzor/issues/145#issuecomment-2647136252).

There's been no reports since DMS v14 release regarding the Pyzor regression.

---

## Initial investigation

These two packages (`pyzor` + `razor`) are included as part of our SpamAssassin support, which we only invoke through Amavis:

https://github.com/docker-mailserver/docker-mailserver/blob/eb165ded65859794bbeca66e529a3466ceee298b/target/scripts/build/packages.sh#L72-L75

https://github.com/docker-mailserver/docker-mailserver/pull/1756#issuecomment-763854042 (Jan 2021) introduced this ugly workaround in `Dockerfile`:

https://github.com/docker-mailserver/docker-mailserver/blob/59a379aed781d8e66b9388491aed245a9f5d9af1/Dockerfile#L164-L178

As this apparently failed in CI often enough due to some network request failing during image build?:

```bash
su - amavis -c "razor-admin -create && sleep 3 && razor-admin -register"
```

[Pyzor](https://github.com/SpamExperts/pyzor) (_[about page](https://www.pyzor.org/en/latest/about.html)_) + [Razor](https://salsa.debian.org/debian/razor) seems like it was originally introduced into DMS in April 2016? Not much context available and packages were already committed prior: https://github.com/docker-mailserver/docker-mailserver/pull/149

Later during a [base image switch from Ubuntu 16.04 to Debian 9 (Stretch, slim variant) in Jan 2018](https://github.com/docker-mailserver/docker-mailserver/pull/784#issuecomment-354596396), the Pyzor `discover` command was no longer valid (_as per PR description_) which has a [related Sep 2017 issue](https://github.com/docker-mailserver/docker-mailserver/issues/729#issuecomment-354543257) for more context. Prior to that issue [there was a problem with discover](https://github.com/docker-mailserver/docker-mailserver/issues/389#issue-191711952) reported in Nov 2016, likely related.

Additionally, consideration may be needed for `razor-admin -register`? (_which the workaround in question is related to_): https://github.com/docker-mailserver/docker-mailserver/issues/1815#issuecomment-780849353

> _Registers a new identity, used for authenticating with Razor Nomination Servers. Identities are a user + password pair stored in "<razorhome>/identity-<user>"._
> _The first time "razor-admin -register" exits successfully, a symlink "identity" is created to point to the active "identity-<user>" file._

Probably not ideal that we have that during the image build, some of our CI tests for spam may be engaging with that unintentionally? 🤷‍♂ 

These plugins are enabled by default for SpamAssassin in the config `/etc/spamassassin/v310.pre` (_DMS has no involvement with these configs_):

```
# Pyzor - perform Pyzor message checks.
#
loadplugin Mail::SpamAssassin::Plugin::Pyzor

# Razor2 - perform Razor2 message checks.
#
loadplugin Mail::SpamAssassin::Plugin::Razor2
```

Pyzor release 1.0.0 was in Dec 2014, with a [new release (1.1.2) released in Sep 2024](https://github.com/SpamExperts/pyzor/issues/145#issuecomment-2647136252) that mostly addresses Python 3 compatibility.

**Comment by polarathene** [comment]
No rush to remove for v15, my concern was more with the change in SpamAssassin behaviour.

Not only does v14 no longer seem to apply the Pyzor check, the first non-spam mail doesn't seem to get any SpamAssassin headers added. Perhaps something changed with SA 4.0 defaults now skipping appending such headers if the mail isn't considered spam? I haven't looked up the SA 4.0 changelog yet.

Regardless still an undocumented change in behaviour for DMS.

**Comment by polarathene** [comment]
To check if it was a Python 3 version compatibility issue, I manually swapped out the `pyzor` package (`1.0.0` from Dec 2014) with the latest PyPi release (`1.1.2` from Sep 2024) and still observed no Pyzor involvement with DMS v14 for the GTUBE mail.

---

A SpamAssassin dev [engaged with the Pyzor project in June 2023](https://github.com/SpamExperts/pyzor/issues/147), but it seems no maintainers have responded to that request or the devs PR. That doesn't really give much confidence in the project (_nor does the [project maintenance history](https://github.com/SpamExperts/pyzor/issues/145#issuecomment-2647136252)_), so perhaps dropping it is fine. That particular PR isn't relevant to us, SA still detects GTUBE itself fine, it's more about the state of the project maintenance.

I know even less about the razor integration if DMS has ever used that. Dropping these from a major release of DMS should be fine, and anyone who actually knows and cares about such could open an issue to justify bringing it back should that be relevant, but as of DMS v14 I don't think `pyzor` is working, if `razor` did at some point I'm not sure when that was (_assuming it would have added a score similar to `PYZOR_CHECK`_).

**Comment by casperklein** [comment]
> @casperklein since you use Amavis + SpamAssassin this may be relevant to you. 
I never did more than `ENABLE_AMAVIS=1` and `ENABLE_SPAMASSASSIN=1`.

I don't have an opinion on that from a technical point of view, because I never (had to) looked into it.

> Pyzor integration broken since DMS v14?

I did not notice any regression, but TBH, I don't receive much SPAM at all🙏 So it might be an unrecognized regression for me..

If you think it's broken / hard to fix and doesn't provide much benefit, we can remove it 👍

**Comment by polarathene** [comment]
FWIW [SpamAssassin news](https://spamassassin.apache.org/) announced SA 4.0.1 (March 2024) with:

> _This is a patch release that fixes issues that have surfaced since the release of 4.0.0._
> _It provides compatibility with the latest version of Perl, 5.38, which was released in July, 2023, as well as with recent release versions of some required Perl modules._

We're stuck on 4.0.0 with Debian 12, although I assume the backports repo would provide 4.0.1, I'm a bit surprised as I thought Debian would have been ok with updating stable branch with patch release like that 🤷‍♂ 

There's a possibility that upgrading will fix the regression, otherwise I'm not quite sure where the change in scan behaviour is coming from. For example you would get SA headers applied to non-spam mail prior to DMS v14, whereas now they are only appended when spam is detected. Whatever caused that change likely is related to the lack of Pyzor check too 🤔

**Comment by casperklein** [comment]
> [@casperklein](https://github.com/casperklein) since you use Amavis + SpamAssassin this may be relevant to you. I'm not sure how important these packages are (_they apparently [were of value at least 20 years ago](https://narkive.com/T6bs693J.5)_ 😅 )

Beside enabling SA, I don't have much experience with SA either 🤷 If it turns out to be an issue, we can always re-add those packages.

**Comment by casperklein** [comment]
For reference:

I checked some SPAM mails and can confirm, pyzor is still working with DMS `v15.x`:

<details>
<summary>Example</summary>

```
Return-Path: <catherinemart@coiffeur-jedzig.de>
Delivered-To: postmaster@my-mailserver.tld
Received: from mail.my-mailserver.tld
by mail.my-mailserver.tld with LMTP
id t/CDMIkfjmhnegAAdOYLmw
(envelope-from <catherinemart@coiffeur-jedzig.de>)
for <postmaster@my-mailserver.tld>; Sat, 02 Aug 2025 16:24:09 +0200
Received: from localhost (localhost [127.0.0.1])
by mail.my-mailserver.tld (Postfix) with ESMTP id BEA9B1E81914
for <postmaster@my-mailserver.tld>; Sat,  2 Aug 2025 16:24:09 +0200 (CEST)
X-Spam-Flag: YES
X-Spam-Score: 7.267
X-Spam-Level: *******
X-Spam-Status: Yes, score=7.267 tagged_above=0 required=6.31
 tests=[BAYES_00=-1.9, DIET_1=0.001, DKIM_SIGNED=0.1, DKIM_VALID=-0.1,
 HTML_MESSAGE=0.001, PYZOR_CHECK=1.392, RCVD_IN_DNSWL_BLOCKED=0.001,
 RCVD_IN_MSPIKE_H2=0.001, RCVD_IN_PSBL=2.7,
 RCVD_IN_VALIDITY_CERTIFIED_BLOCKED=0.001,
 RCVD_IN_VALIDITY_RPBL_BLOCKED=0.001, RCVD_IN_VALIDITY_SAFE_BLOCKED=0.001,
 RCVD_IN_ZEN_BLOCKED_OPENDNS=0.001, SPF_HELO_NONE=0.001, SPF_SOFTFAIL=0.665,
 URIBL_BLOCKED=0.001, URIBL_CT_SURBL=1.899, URIBL_DBL_BLOCKED_OPENDNS=0.001,
 URIBL_DBL_SPAM=2.5] autolearn=no autolearn_force=no
Authentication-Results: mail.my-mailserver.tld; dmarc=none (p=none dis=none) header.from=coiffeur-jedzig.de
Authentication-Results: mail.my-mailserver.tld;
dkim=pass (2048-bit key; unprotected) header.d=coiffeur-jedzig-de.20230601.gappssmtp.com header.i=@coiffeur-jedzig-de.20230601.gappssmtp.com header.a=rsa-sha256 header.s=20230601 header.b=q8dspywB;
dkim-atps=neutral
Received-SPF: Softfail (mailfrom) identity=mailfrom; client-ip=209.85.219.193; helo=mail-yb1-f193.google.com; envelope-from=catherinemart@coiffeur-jedzig.de; receiver=my-domain.tld 
Received: from mail-yb1-f193.google.com (mail-yb1-f193.google.com [209.85.219.193])
by mail.my-mailserver.tld (Postfix) with ESMTPS id EFBB61E80187
for <webmaster@my-domain.tld>; Sat,  2 Aug 2025 16:24:07 +0200 (CEST)
Received: by mail-yb1-f193.google.com with SMTP id 3f1490d57ef6-e8fe618dc71so1110284276.0
        for <webmaster@my-domain.tld>; Sat, 02 Aug 2025 07:24:07 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=coiffeur-jedzig-de.20230601.gappssmtp.com; s=20230601; t=1754144639; x=1754749439; darn=my-domain.tld;
        h=to:subject:message-id:date:list-unsubscribe:from:mime-version:from
         :to:cc:subject:date:message-id:reply-to;
        bh=bRR/y3fUbrvT22qOEaNbeYdf3ME0PJiwHDcYp8sHit8=;
        b=q8dspywByCVy0ChtrkxIChRyRwaFpu+2aPb/WVzbUBtlI/UOT90+qs/GrZa5ArH1Ff
         C6dQClfeeNR/I7/uzdDDwJl1M8+cCkzk19C+BNQX9ZzcAp50mySQjC3+GqDcHOvMLfJa
         UVsxR7dVgk7NrLGI224c2vTNTwCFTlxc3StLwcfERkAtX+plbvGBn223gws1AMrWlByW
         t+nHNSPlLLyChRsosiJreUK15CbwDZcpjKnzXaBSGZqVX7dWaWCVo188JrPW+F5vH3XA
         N/MRPVQ/NinPrLqRiZpPKdYJCnR/97CfUZjPXpguo6cGqwqurUbQLjLnjzwQSBX65HyZ
         GX7Q==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20230601; t=1754144639; x=1754749439;
        h=to:subject:message-id:date:list-unsubscribe:from:mime-version
         :x-gm-message-state:from:to:cc:subject:date:message-id:reply-to;
        bh=bRR/y3fUbrvT22qOEaNbeYdf3ME0PJiwHDcYp8sHit8=;
        b=IXUAdzxPJMY+GMWABdLmb2wkEy5U6Ugm12hGihqNUhQ+qJpmRQ/qk6E65Tncjq7xGE
         2prdCKmjjcz41UWQLV7hE/o2bCQhFsELhB6/yk3UZMKmPTu9NgCB2VD+4Ma8OHmlpTfA
         X7TwIk0MIeLSk/GEUOjYWt3xobCkMBGRtYXExCNsOR8U4G+Py6r16sd6hNKqrRTeS4VY
         eYuWqJ2hVXEwubo1I5F5WCnB85Y/dW7izW7am5B3QiRcHQ/in1ypVJMdKyit4vI7h8DX
         97kFCU/kXfSOCI0/2J4g/CybmrXyfUI7XxJ2litbbrvA86TCmxLrdC8OqZTjHPL/j4g9
         mgEA==
X-Forwarded-Encrypted: i=1; AJvYcCXwK8Zb+FWFB6MfT5Iz1Iifu1aHnFVoXMrGcvZ0NchxWbfzFSpinvmeNGWf+OHeL1MgoJS2zOm8huA=@my-domain.tld
X-Gm-Message-State: AOJu0YwdUZny73GM2wi4mkF57g41+ir/Msfy6ca1+XK93zXsyOLOh0YA
qVibHxWbRiOxwTYJk68Jcd9hRuVyJ6SuOHlRvHxLi2kjsOn2mnzR0MPBOkwTT5HV/+AtjA0SGLf
yh/wG5De0WP260YMiS9nGTAN/RVseQ6za2+VUwEgpBtI=
X-Gm-Gg: ASbGncvaBBd4oXeYqXvaPF+FkepGMRN7BH5PBh+E0/uob1RtJ65ISJNJILqLtvBObLu
mHrR8v+uVoZsGQInDKvhrOIK1Jy4TjFbI5Ro/b2OEpzZHSxg1Ww+XJZfUrkrz08xmuPSoU/0X9F
6fJ/Lmxxv+dN75MQiWjZbMHHz3IPaWnpksL6LmOHELMXtUH0EIB7Xnb5aRIiNb8mdAmaOk
X-Google-Smtp-Source: AGHT+IEK3jo0wiQimEiMeJt5mzP7kPBBoKxd9pD9Mg6hsyYgR0hZfAcBH5ghNUaU7dws9XGsEW68wMA+ES5qIUZ0UqY=
X-Received: by 2002:a05:690c:7010:b0:71a:41e2:b553 with SMTP id
 00721157ae682-71b7f5958fbmr43395317b3.26.1754144639456; Sat, 02 Aug 2025
 07:23:59 -0700 (PDT)
Received: from 174653659670 named unknown by gmailapi.google.com with
 HTTPREST; Sat, 2 Aug 2025 07:23:57 -0700
Received: from 174653659670 named unknown by gmailapi.google.com with
 HTTPREST; Sat, 2 Aug 2025 07:23:57 -0700
MIME-Version: 1.0
X-Priority: 3
From: =?UTF-8?B?0KHQhtC+dWRm0IbQsHLQtQ==?= <catherinemart@coiffeur-jedzig.de>
List-Unsubscribe: <mailto:unsubscribe@coiffeur-jedzig.de?subject=unsubscribe>, <https://coiffeur-jedzig.de/unsubscribe>
X-MSMail-Priority: Normal
Date: Sat, 2 Aug 2025 07:23:57 -0700
X-Gm-Features: Ac12FXyemry_O8Ya_DBwo_QMwfWkhvy3epYYZMvVHeZhL_RZ3FIHoXg5HRN5rl8
Message-ID: <CAGMZak37T3TNxJLRzcq1DsRvaXWyrzapDGkJDF5ZL2Ot+eM6cQ@mail.gmail.com>
To: =?UTF-8?B?0KHQhtC+dWRm0IbQsHLQtQ==?= <dhbrad@pcomp.net>
Content-Type: multipart/alternative; boundary="0000000000001ea666063b62a0ff"
Subject: *** SPAM *** Important: Secure Your
=?utf-8?b?0KHQhtC+dWRm0IbQsHLQtQ==?= Account!
```

</details>

---

I couldn't [find](https://github.com/docker-mailserver/docker-mailserver/issues?q=sort%3Aupdated-desc%20is%3Aissue%20state%3Aclosed%20pyzor) any recent issues with pyzor.

Given the fact that it still works and there are no complaints from users, it makes me question whether the removal of the package is justified?

---

`razor` seems to be alive, at least there are lot of [support requests](https://sourceforge.net/p/razor/support-requests), that get answered quickly.

But If I understood correctly, razor is not part of our SPAM scanning.

**Comment by georglauterbach** [comment]
I see your point!

I have always had a huge distaste for the way we have to handle `pyzor` in our Dockerfile, though. That weird `for` loop requirement is really awkward..

Not sure how to proceed here. I'm fine with bringing it back, but I'm reluctant nevertheless.

**Comment by polarathene** [comment]
> I checked some SPAM mails and can confirm, pyzor is still working with DMS `v15.x`:
> Given the fact that it still works and there are no complaints from users, it makes me question whether the removal of the package is justified?

@casperklein earlier in the issue I documented (_as quoted and linked below_) an observed regression with Amavis/SA introduced from DMS v14 / Debian 12 compared to prior v13 series with Debian 11. It's perhaps possible that since DMS v15 that has been fixed, where an SA bug fix release (`4.0.1`) from a while back finally landed in Debian 12 packages.

I haven't attempted to reproduce on DMS v15.x, but `pyzor` was noted as working when used directly, just something with the Amavis/SA integration was not.

> https://github.com/docker-mailserver/docker-mailserver/issues/4351#issue-2841988870
> 
> > However I've also noticed that I cannot reproduce this `PYZOR_CHECK=1.985` addition from DMS v14 onwards (_[v14 changelog](https://github.com/docker-mailserver/docker-mailserver/releases/tag/v14.0.0)_), something has presumably changed?

> https://github.com/docker-mailserver/docker-mailserver/issues/4351#issuecomment-2649522869
>
> > In a DMS v14 container:
> > 
> > ```console
> > # Create an spam email with GTUBE signature, but output it to file via `--dump-mail`
> > # So we can test it against pyzor directly:
> > $ swaks --data @/tmp/template.swaks \
> >   --to john.doe@example.test \
> >   --body 'XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X' \
> >   --dump-mail > /tmp/gtube.eml
> > 
> > $ pyzor --version
> > /usr/bin/pyzor 1.0.0
> > 
> > # Test pyzor is working by giving it an email to check:
> > $ pyzor check < /tmp/gtube.eml
> > public.pyzor.org:24441  (200, 'OK')     29093860        322576
> > 
> > # exit-code of 1 from `pyzor check` indicates spam:
> > $ echo $?
> > 1
> > ```

---

> I have always had a huge distaste for the way we have to handle `pyzor` in our Dockerfile, though. That weird `for` loop requirement is really awkward..

@georglauterbach 

I agree, although I'd rather have had a better understanding of why that would have been needed, if `pyzor` was to be brought back in, it should avoid that the PR should add context to why it must be done that way. Definitely something that could belong in a separate shell script rather than inlined into the `Dockerfile` itself too in that case.

---

> Not sure how to proceed here. I'm fine with bringing it back, but I'm reluctant nevertheless.

It would be good to know how much value Pyzor was bringing.

All I know is the Amavis + SA integration regressed in our DMS v14 release, and that none of the DMS maintainers really want to deal with support queries (_especially rather technical ones_) for those two services, along with switching to Rspamd by default (_lack of version pinning concern aside_).

Generally when users raise support requests regarding spam services in DMS, I don't see too much advice going on there other than:
- If you use the default Amavis, make sure you enable the non-default SA feature. If user chimes in that still doesn't help, we don't tend to have much else to suggest that isn't covered in our docs.
- If that still doesn't work, try switch to Rspamd and get back to us (_user rarely does, presumably it resolved the issue_).

Most users won't know about `pyzor`, and given other changes in DMS v16, it might be trickier to associate the impact of it's removal being the cause of regressed spam filtering, but we could keep that in mind should anyone say DMS v16 has notably regressed in spam filtering for Amavis + SA deployments?

**Comment by polarathene** [comment]
Should anyone be interested in why Pyzor is removed, and would like to bring it back the following reproduction needs to identify the conditions for regression since DMS v14. We can then reliably add a test case.

## Reproduction reference for regression

I was able to confirm that the reproduction still fails with our latest DMS release.

This could be potentially due to a change logic/trust handling in Amavis or SA since DMS v14, when perhaps:
- The GTUBE pattern might be ignored/skipped by SA from v4.0.0 onwards? I'd need something else to reliably reproduce spam. As was confirmed earlier in this issue `pyzor` itself would still score GTUBE when given the mail from `swaks` directly.
- When mail is delivered from a local connection in the same container. This is not due to `PERMIT_DOCKER=container` however, but there might be something about the connection such as the IP origin causing SA to skip some checks, this has been observed with Rspamd (_and Amavis I think?_) behaving differently vs a separate client container (different IP/rDNS)
- The use of `.test` TLD instead of public DNS resolvable address?

Either way, without additional data I cannot reproduce @casperklein observation of working Pyzor, but I can reliably produce the observed regression.

## DMS v15.1 (fails)

Works with DMS `v13.3.1`:

```
$ DMS_RELEASE=13.3.1 docker compose up -d --force-recreate &&\
 sleep 10 &&\
 docker compose exec -it dms check-for-pyzor

/var/mail/example.test/john.doe/.Junk/new/1755574519.M525505P684.mail.example.test,S=1206,W=1235:       tests=[ALL_TRUSTED=-1, GTUBE=1000, PYZOR_CHECK=1.985]
```

Fails since DMS `v14.0.0`, verified still an issue with DMS `v15.1.0`:

```console
$ DMS_RELEASE=15.1.0 docker compose up -d --force-recreate &&\
 sleep 10 &&\
 docker compose exec -it dms check-for-pyzor

No mail found with expected Pyzor metadata
```

This is using roughly the same original reproduction `compose.yaml`, but:
- A bit more verbose commentary and explicit ENV config.
- Embeds the reproduction script with added sleep to simplify timing concerns.

```yaml
services:
  dms:
    image: ghcr.io/docker-mailserver/docker-mailserver:${DMS_RELEASE:-15.1.0}
    hostname: mail.example.test
    environment:
      ENABLE_AMAVIS: 1 # NOTE: Already default enabled in DMS
      # Required for classification as Spam + Pyzor headers:
      ENABLE_SPAMASSASSIN: 1
      # These two skip when receiving mail from localhost regardless of `PERMIT_DOCKER` set to `none` or `container`:
      ENABLE_OPENDKIM: 0
      ENABLE_OPENDMARC: 0
      # Alternatively skipped if `PERMIT_DOCKER=container` when using swaks within the same container:
      # - This SPF service otherwise performs a DNS TXT record lookup that will fail for this example setup.
      # - Disabled to avoid delaying delivery from 5+ second query timeout.
      # - This concern is not relevant with swaks within the same container, local IP is trusted as per logs.
      ENABLE_POLICYD_SPF: 0
      # Other DNS queries (MX record or rDNS by Postfix?) are still stalling delivery unnecessarily for reproduction,
      # Resolve by trusting any client connection coming from within the container itself:
      # (Delay appears to be about 6 seconds by postscreen upon receiving swaks connection according to /var/log/mail.log)
      # (Confirmed postscreen causes delay: https://postfix.cs.utah.edu/postconf.5.html#postscreen_greet_wait )
      PERMIT_DOCKER: container
      # Avoid delay from DMS update check and mail notification sent to postmaster
      # (which would fail as postmaster is not configured)
      ENABLE_UPDATE_CHECK: 0
      #POSTMASTER_ADDRESS: john.doe@example.test
    configs:
      - source: dms-accounts
        target: /tmp/docker-mailserver/postfix-accounts.cf
      - source: check-for-pyzor
        target: /usr/local/bin/check-for-pyzor
        mode: 0755

configs:
  dms-accounts:
    content: |
      john.doe@example.test|{SHA512-CRYPT}$$6$$sbgFRCmQ.KWS5ryb$$EsWrlYosiadgdUOxCBHY0DQ3qFbeudDhNMqHs6jZt.8gmxUwiLVy738knqkHD4zj4amkb296HFqQ3yDq4UXt8.

  check-for-pyzor:
    content: |
      #!/bin/bash

      # Send mail with GTUBE spam pattern:
      swaks --silent --server localhost --to john.doe@example.test --body 'XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X'

      # Allow a buffer of time to process mail by Postfix + Dovecot after swaks completes the delivery:
      sleep 3

      # Check for Pyzor metadata in mail headers:
      grep -R -i pyzor /var/mail/example.test/john.doe/.Junk/new/
      [[ $? -eq 1 ]] && echo 'No mail found with expected Pyzor metadata'
```

---

### DMS v14 (fails) vs DMS v13.3.1 (works)

<details>
<summary>Collapsed for brevity (click to view)</summary>

The below quoted content is sourced from the [opening comment](https://github.com/docker-mailserver/docker-mailserver/issues/4351#issue-2841988870) of this issue.

Clearly you can see and reproduce with a DMS v14 container that is missing the Pyzor result output from SpamAssassin appended headers (_this regression motivated the removal of `pyzor` as no one was willing to fully investigate the cause_).

> ```yaml
> services:
>   dms:
>     image: ghcr.io/docker-mailserver/docker-mailserver:${DMS_RELEASE:-13.3.1}
>     hostname: mail.example.test
>     environment:
>       ENABLE_AMAVIS: 1
>       ENABLE_SPAMASSASSIN: 1
>       # For running swaks command (skips postscreen 6s delay by trusting connections from container IP):
>       PERMIT_DOCKER: container
>     configs:
>       - source: dms-accounts
>         target: /tmp/docker-mailserver/postfix-accounts.cf
> 
> configs:
>   dms-accounts:
>     content: |
>       john.doe@example.test|{SHA512-CRYPT}$$6$$sbgFRCmQ.KWS5ryb$$EsWrlYosiadgdUOxCBHY0DQ3qFbeudDhNMqHs6jZt.8gmxUwiLVy738knqkHD4zj4amkb296HFqQ3yDq4UXt8.
> ```
>
> ```console
> DMS_RELEASE=14 docker compose up -d --force-recreate
> docker compose exec -it dms bash
> 
> # Send mail (doesn't qualify as actual spam):
> swaks --server 0.0.0.0 --to john.doe@example.test --body 'spam'
> 
> # View the mail:
> less /var/mail/example.test/john.doe/new/*
> 
> # Send a spam mail (GTUBE test pattern):
> swaks --server localhost --to john.doe@example.test --body 'XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X'
> 
> less /var/mail/example.test/john.doe/.Junk/new/*
> ```

Results expanded for DMS `v13.3.1` vs DMS `v14.0.0`:

> <img width="836" height="1064" alt="Image" src="https://github.com/user-attachments/assets/b1055ffc-17e1-44df-9728-9eada733be38" />

</details>
