### ISSUE TITLE
bug report: DMS fails to send mails in internal docker network

### ISSUE THREAD

**Issue by moookino** [docker-mailserver/docker-mailserver#4401]
### 📝 Preliminary Checks

- [x] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Hi,

I followed example to setup dms behind traefik
Internal services under same network within traefik proxy fail to send messages

[example](https://docker-mailserver.github.io/docker-mailserver/v15.0/examples/tutorials/mailserver-behind-proxy/)

config

### 👟 Reproduction Steps

e.g. snappymail when try to send an email or do domain verification, imap and sieve pass and smtp fails

### 🐋 DMS Version

v15

### 💻 Operating System and Architecture

Debian 12, x86_64

### ⚙️ Container configuration files

```yml
services:
  mail:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    restart: always
    networks:
      - proxy
    volumes:
      - ./dms/mail-data/:/var/mail/
      - ./dms/mail-state/:/var/mail-state/
      - ./dms/mail-logs/:/var/log/mail/
      - ./dms/config/:/tmp/docker-mailserver/
      - /letsencrypt/acme.json:/etc/letsencrypt/acme.json:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SSL_TYPE=letsencrypt
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=0 
      - PERMIT_DOCKER=connected-networks
      - ENABLE_POSTGREY=1
      - ENABLE_FAIL2BAN=1
      - CONTAINER_NAME=docker-mailserver
      - POSTMASTER_ADDRESS=redacted
      - SPOOF_PROTECTION=1
      - ENABLE_MANAGESIEVE=1
      - LOG_LEVEL=trace
    hostname: mail.example.com
    container_name: docker-mailserver
    dns: 1.1.1.1
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.tcp.routers.smtp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smtp.entrypoints=smtp"
      - "traefik.tcp.routers.smtp.service=smtp"
      - "traefik.tcp.routers.smtp.tls=false"
      - "traefik.tcp.services.smtp.loadbalancer.server.port=25"
      - "traefik.tcp.services.smtp.loadbalancer.proxyProtocol.version=2"
      
      - "traefik.tcp.routers.smtp-ssl.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smtp-ssl.entrypoints=smtp-ssl"
      - "traefik.tcp.routers.smtp-ssl.tls.passthrough=true"
      - "traefik.tcp.routers.smtp-ssl.service=smtp-ssl"
      - "traefik.tcp.services.smtp-ssl.loadbalancer.server.port=10465"
      - "traefik.tcp.services.smtp-ssl.loadbalancer.proxyProtocol.version=2"

      - "traefik.tcp.routers.imap-ssl.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.imap-ssl.entrypoints=imap-ssl"
      - "traefik.tcp.routers.imap-ssl.service=imap-ssl"
      - "traefik.tcp.routers.imap-ssl.tls.passthrough=true"
      - "traefik.tcp.services.imap-ssl.loadbalancer.server.port=10993"
      - "traefik.tcp.services.imap-ssl.loadbalancer.proxyProtocol.version=2"

      - "traefik.tcp.routers.sieve.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.sieve.entrypoints=sieve"
      - "traefik.tcp.routers.sieve.service=sieve"
      - "traefik.tcp.services.sieve.loadbalancer.server.port=14190"
```

### 📜 Relevant log output

```Text
mail postfix/submissions/smtpd[2359]: warning: haproxy read: unrecognized protocol header: \026\003\001\002\000\001\000\001\374\003\003I\305\324nS\267\355\366\370s\361\337\005J\271P\375\203\365\211\262\\\317s\002\371\273\020\021\224\334/ \3056\220\033\250\306%:Fj\r\214R\242\332\n>\203=\251Z\240\n/E\362\242xw\3316\260\000\212\023\002\023\003\023\001\300/\300+\3000\300,\000\236\000\242\000\243\000\237\300'\300#\300\023\300\t\300(\300$\300\024\300\n\000g\0003\000@\000k\0008\0009\000\234\000\235\300\254\300\236\0002\300\234\000<\000/\300\255\300\237\000j\300\235\000=\0005\314\251\314\250\314\252\300]\300a\300W\300S\300\\\300`\300V\300R\300s\300w\000\304\000\303\300r\300v\000\276\000\275\000\210\000\207\000E\000D\300Q\300P\000\300\000\272\000\204\000A\000\377\001\000\001)\000\000\000\023\000\021\000\000\016mail.murrum.eu\000\v\000\004\003\000\001\002\000\n\000\026\000\024\000\035\000\027\000\036\000\031\000\030\001\000\001\001\001\002\001\003\001\004\000#\000\000\000\026\000\000\000\027\000\000\000\r\0000\000.\004\003\005\003\006\003\b\a\b\b\b\032\b\033\b\034\b\t\b\n\b\v\b\004\b\005\b\006\004\001\005\001\006\001\003\003\003\001\003\002\004\002\005\002\006\002\000+\000\005\004\003\004\003\003\000-\000\002\001\001\0003\000&\000$\000\035\000 8\304\344\354r\031\260\fB\252]\a\346\255W\376x\373l_\315\356\214\371\207#\241\316\347\353Mj\000\025\000s\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000
```
