### ISSUE TITLE
other: outgoing traffic on ports

### ISSUE THREAD

**Issue by MarcS1975** [docker-mailserver/docker-mailserver#4406]
### Subject

Dsync 

### Description

Hi I am trying to setup a dsync between two DMS but the outgoing connection does not work on any port. Incoming is fine and outgoing works fine from the docker host. 
Is there anything in DMS setup restricting outgoing packages?

**Comment by polarathene** [comment]
Do you have full control over the hosts and network?

If you're using a server provisioned from some service online they may have outbound port 25 blocked intentionally (_see our debugging / troubleshooting docs page_).

**Comment by polarathene** [comment]
You will need to share more context.
- Are the two instances of DMS on the same system, or separate hosts?
- Are there multiple network interfaces?
- What version of Docker are you running?
- Are you using Docker Compose? If so what version?
- What OS and kernel are these containers running on? (_linux host, or via VM / WSL2?_)
- Do you have any firewall on the hosts that might be affecting the flow of traffic? firewalld for example may have any private docker networks in the `docker` zone which may affect routing.

It will be mostly guess work, but there should not be anything specific to DMS affecting this. You'll probably experience the same with a basic web server instance running and trying to reach via curl in a container as well.

**Comment by polarathene** [comment]
> > Are there multiple network interfaces?
> 
> yes

This is potentially relevant thanks.

> > Do you have any firewall on the hosts that might be affecting the flow of traffic? firewalld for example
> 
> The KVM has a firewall but I opened it. I can reach each container from the other host, just not from the other DMS container.

Can you try isolating this to a container that isn't DMS? Here's an example:

```yaml
services:
  reverse-proxy:
    image: caddy:2.9
    ports:
      - '3000:80' # Publish to whatever host port you like
    configs:
      - source: caddy-config
        target: /etc/caddy/Caddyfile

configs:
  caddy-config:
    content: |
      # Global Settings
      {
        # Avoids provisioning cert via LetsEncrypt + no HTTP => HTTPS redirect:
        auto_https off
      }

      # Host should reflect the public IP of this server that you published the port to.
      # Remote should reflect the public IP from the connection of the client (curl).
      # The `X-Forwarded-For` header is only set when there is another trusted proxy involved.
      :80 {
        respond "
      Caddy received:
      - Host (Server IP): {host}
      - Remote (Client IP): {remote_host}
      - Forwarded From (via a reverse-proxy): {header.X-Forwarded-For}
      "
      }

# `.bridge.host_binding_ipv4` => bind to a specific host IP (default is `0.0.0.0`, aka all interfaces)
# `.host_ipv4` => the IP for a host interface to route traffic from, this will be your client IP
#
# NOTE: `198.51.100.42` is from the private IPv4 range assigned for documentation purposes.
# Change it to the IP of your preferred public network interface.
networks:
  default:
    name: caddy-net
    driver_opts:
      #com.docker.network.bridge.host_binding_ipv4: 198.51.100.42
      com.docker.network.host_ipv4: 198.51.100.42
    # Optionally assign an IPv6 subnet (example uses a portion of the private ULA range):
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd00:face:feed:cafe::/64
```

```bash
# NOTE: If you make any changes to `driver_opts` config above, this won't be sufficient.
# You will need to use `docker compose down` to destroy the existing network to create a new one.
docker compose up -d --force-recreate

# Join the custom network:
docker run --rm -it --network caddy-net fedora
# Use DNS or direct IP to query the other Caddy instance of your other system:
curl http://example.com:3000
```

When you run this test, you should see that you get something like (_where `example.com` => `1.2.3.4`_):

```
Caddy received:
- Host (Server IP): 1.2.3.4
- Remote (Client IP): 198.51.100.42
- Forwarded From (via a reverse-proxy):
```

If you run the test again (_be sure to use `docker compose down` before modifying `compose.yaml`_) and you remove the `networks` section, you should now be getting similar network behaviour that you're having with DMS? (_if you receive a response from Caddy it will tell you which remote IP is being used, IPv4 or IPv6_)

If you perform the `curl` call with a DNS resolved IP instead of a direct IP, it may use IPv6 if your DNS has that configured. That may potentially contribute to the issue.

You are running one of the containers in a VM guest, thus the host has a virtual network by the VM, and then within the VM is a virtual network managed by Docker. You need to ensure the routing for such is working properly, hence why we're doing this basic web server test with Caddy to verify if it's specific to DMS or Docker to Docker in general.

If Caddy is successful, it's possible that the problem is related to some security check in DMS such as rDNS or a related mismatch from the extra indirection of the VM guest.

---

> server1_host -> reach -> server2_host - > DMS_conteiner WORKS
> server2_host -> reach -> server1_host - > DMS_conteiner WORKS
> server1_DMS_Container -> reach -> server2_host - > DMS_conteiner FAIL
> server2_DMS_Container -> reach -> server1_host - > DMS_conteiner FAIL

Have you confirmed if a container can reach a host service (at the other physical host), and then also a service running in the VM guest that isn't additionally wrapped in a container?

```
server1_DMS_Container -> reach -> server2_host -> Service on host (no container)
server1_DMS_Container -> reach -> server2_host -> Service in VM (no container)
```

That may help clarify where the routing issue is. Should only need to do this if the suggested test with Caddy fails just like you've had with DMS.

---

> > Are the two instances of DMS on the same system, or separate hosts?
> 
> separate host, different physical locations

Earlier you stated you had full control over the network infrastructure. Just to confirm, these two physical hosts are co-located in the same building, you do have absolute oversight, no third-party services are providing these systems or managing the network?

You must have something misconfigured as this shouldn't be failing AFAIK 🤔
