### ISSUE TITLE
bug report: Since v15.0.1 SpamAssassin is no longer working

### ISSUE THREAD

**Issue by ontheair81** [docker-mailserver/docker-mailserver#4428]
### 📝 Preliminary Checks

- [x] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

After updating to v15.0.1 all spam emails appear in the user's inbox instead of the junk folder. When going back to v15.0.0 the spam emails are moved correctly.

I did not change any settings inbetween these two versions. Using traditional SpamAssassin instead of Rspamd. 

Any help is greatly appreciated!

### 👟 Reproduction Steps

Simply by updating to v15.0.1 and wait for spam.
(Among other addresses, my server hosts an email address that has been publicly known for 20 years and attracts a lot of spam.)

### 🐋 DMS Version

v15.0.1

### 💻 Operating System and Architecture

Debian 12 x86

### ⚙️ Container configuration files

```yml
services:

    mailserver:
        image: "ghcr.io/docker-mailserver/docker-mailserver:15.0.1"
#       image: "ghcr.io/docker-mailserver/docker-mailserver:15.0.0"
        container_name: "mailserver"
        # If the FQDN for your mail-server is only two labels (eg: example.com),
        # you can assign this entirely to `hostname` and remove `domainname`.
        hostname: "mail"
        domainname: "mydomain.com"
        env_file: "/home/user/docker_compose/mailserver/mailserver.env"
        # More information about the mail-server ports:
        # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
        # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
        ports:
           - "25:25"
           - "143:143"
           - "465:465"
           - "587:587"
           - "993:993"
           - "4190:4190"
        volumes:
           - "/home/user/bind-mounts/dms/mail-data/:/var/mail/"
           - "/home/user/bind-mounts/dms/mail-state/:/var/mail-state/"
           - "/home/user/bind-mounts/dms/mail-logs/:/var/log/mail/"
           - "/home/user/bind-mounts/dms/config/:/tmp/docker-mailserver/"
           - "/home/user/docker_compose/mailserver/policyd-spf.conf:/etc/postfix-policyd-spf-python/policyd-spf.conf"
           - "/home/user/bind-mounts/certstore:/etc/letsencrypt/live/:ro"
        restart: "always"
        stop_grace_period: "1m"
        cap_add:
          - "NET_ADMIN"
        dns:
          - "9.9.9.9"
          - "8.8.8.8"
          - "1.1.1.1"
```

Here are the relevant ENV:

```env
# Enables Rspamd
# **0** => Disabled
#   1   => Enabled
ENABLE_RSPAMD=0

# Amavis content filter (used for ClamAV & SpamAssassin)
# 0 => Disabled
# 1 => Enabled
ENABLE_AMAVIS=1

# This enables DNS block lists in Postscreen.
# Note: Emails will be rejected, if they don't pass the block list checks!
# **0** => DNS block lists are disabled
# 1     => DNS block lists are enabled
ENABLE_DNSBL=0

ENABLE_SPAMASSASSIN=1

# KAM is a 3rd party SpamAssassin ruleset, provided by the McGrail Foundation.
# If SpamAssassin is enabled, KAM can be used in addition to the default ruleset.
# - **0** => KAM disabled
# - 1 => KAM enabled
#
# Note: only has an effect if `ENABLE_SPAMASSASSIN=1`
ENABLE_SPAMASSASSIN_KAM=1

# deliver spam messages in the inbox (eventually tagged using SPAM_SUBJECT)
SPAMASSASSIN_SPAM_TO_INBOX=1

# spam messages will be moved in the Junk folder (SPAMASSASSIN_SPAM_TO_INBOX=1 required)
MOVE_SPAM_TO_JUNK=1

# spam messages wil be marked as read
MARK_SPAM_AS_READ=0

# add spam info headers if at, or above that level:
SA_TAG=1.0

# add 'spam detected' headers at that level
SA_TAG2=1.1

# triggers spam evasive actions
SA_KILL=100000.0
```

**Comment by polarathene** [comment]
Nothing in our changelog stands out.

You could try checking if the SpamAssassin version (_or related packages_) has changed between these versions as that's something we don't have pinned.

Any relevant configs internally that might have changed?

I actually think I noticed a difference in SpamAssassin behaviour from v14 onwards, which is where it upgraded to major version 4.0. There was a bug fix release for that but Debian had not updated the package to include the patch release for quite some time... but perhaps they finally did by the time we made the DMS `15.0.1` release?

---

Without a sufficient minimal reproduction there's not much that is actionable here. We're considering SpamAssassin to be grouped as part of our legacy services in future, so if you do not have any specific reason to keep using it perhaps go over our Rspamd docs page and look at migrating?

If you switch to Rspamd, any feedback would be appreciated. Such as:
- Unclear documentation or friction points experienced?
- If the migration went smoothly and is working well for you after a while.

**Comment by casperklein** [comment]
https://github.com/docker-mailserver/docker-mailserver/blob/70d645d863fe51537398f067ec94ca8f6b27d706/target/scripts/startup/setup.d/security/misc.sh#L296-L317

Check if those mails have the header "X-Spam-Flag: YES" set.

**Comment by ontheair81** [comment]
Thanks for the feedback!

> You could try checking if the SpamAssassin version (_or related packages_) has changed between these versions as that's something we don't have pinned.

SpamAssassin changed from 4.0.0 (DMS v15.0.0) to 4.0.1 (DMS v15.0.1).
Amavis is the same (2.13.0).

> Check if those mails have the header "X-Spam-Flag: YES" set.

In v15.0.1 there are no X-Spam-Flag headers in spam mails.

Additionally I checked the logs:
In v15.0.1 all mails are always marked as clean and stored in the inbox, even the most obvious spam:
```
amavis[1572]: (01572-07) Passed CLEAN
dovecot: lmtp([MyRecipient])<22481><58aOCwHL42fRVwAAK1OIHw>: sieve: msgid=<HShwwjp.84159.266.slR-c3RlZkBuLWxlaG5lcnQuZGU=@141361.cxdkhEe5YJ1-seed.schoko-music.de>: stored mail into mailbox 'INBOX'
```

In v15.0.0 spam is marked this way:
```
amavis[186697]: (186697-13) Passed SPAMMY
dovecot: lmtp([MyRecipient])<220705><B9EjNWM942chXgMAK1OIHw>: sieve: msgid=<67051273R26121436R12282851D83664111H@idoylybxm>: fileinto action: stored mail into mailbox [SPECIAL-USE \Junk]
```

> Are you saying that sieve was working fine with DMS v15.0.0 and has changed for you with v15.0.1?

Sieve is fine. I have a lot of filter rules, that are working both in v15.0.0 and v15.0.1

_The main question seems to be, why Amavis (/SpamAssassin) is marking all and every mail as CLEAN. Weird._

> so if you do not have any specific reason to keep using it perhaps go over our Rspamd docs page and look at migrating?

I have not migrated (yet) because of several reasons:
- Honestly, SpamAssassin was working great until the recent update and filtered out almost 100% of the spam, even with the recipients that attract a lot of spam. The filter was trained for years and just works perfect.
- The migration to Rspamd seems to be a bigger task, as it affects more than just spam filtering. I don't want to break anything in this production system and risk downtime.
- If sooner or later I am "forced" to migrate to Rspamd, I was thinking about setting up another mailserver first, just for testing purposes. And afterwards roll things out to the production machine. "As soon as there is enough time"™.

But yes, if the "traditional way" is not going to work anymore, maybe I have to find a way to speed up the migration to Rspamd.

**Comment by casperklein** [comment]
> The main question seems to be, why Amavis (/SpamAssassin) is marking all and every mail as CLEAN. Weird.

You can send a test mail, containing this [string](https://en.wikipedia.org/wiki/GTUBE) `XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X`.

If this mail is not recognized as SPAM, something is wrong with your setup.

> I have not migrated (yet) because of several reasons:

Same here 👍

**Comment by polarathene** [comment]
> SpamAssassin changed from 4.0.0 (DMS v15.0.0) to 4.0.1 (DMS v15.0.1).

Ah, ok so Debian finally chose to land in the bug fix release 1 whole year later after the SA 4.0.1 release. Debian 12 was initially released in June 2023 for what it's worth, the recent Debian release is 12.10 (March 15 2025).

Not exactly ideal timing for DMS v15 and our subsequent point releases 😆 

This may require me to revisit: https://github.com/docker-mailserver/docker-mailserver/issues/4351

---

> * Honestly, SpamAssassin was working great until the recent update and filtered out almost 100% of the spam, even with the recipients that attract a lot of spam. The filter was trained for years and just works perfect.

Please see my references, I express [concern about Amavis + SA and other services now deemed as legacy for DMS](https://github.com/docker-mailserver/docker-mailserver/issues/4364#issuecomment-2661088880), notably [this separate issue](https://github.com/docker-mailserver/docker-mailserver/issues/4351) where SA has changed since DMS v14, you and many other users were just not aware of it as SA was semi-working still even though it was no longer behaving the same.

> * The migration to Rspamd seems to be a bigger task, as it affects more than just spam filtering. I don't want to break anything in this production system and risk downtime.

I understand that but as per [this proposal](https://github.com/docker-mailserver/docker-mailserver/issues/4364), we have introduced Rspamd since April 2023 into DMS and ironed out many issues to get it at parity, in some cases it doing even better than the default services it replaces.

We need user feedback with the migration process to improve the docs we have and better identify any other remaining issues/concerns which a broader audience would help instill confidence.

> * If sooner or later I am "forced" to migrate to Rspamd, I was thinking about setting up another mailserver first, just for testing purposes. And afterwards roll things out to the production machine. "As soon as there is enough time"™.

That's fine I can understand the reluctance. However as maintainer time is low for DMS and these bugs appearing with Amavis / SA over time aren't necessarily something under our own control but from upstream, the more these services break with DMS the more I encourage adopting Rspamd which is going in the opposite direction of becoming a superior choice.

For many users the switch has gone smoothly and resolved any issues they faced with services that Rspamd replaced, some of the legacy services don't have proper or any support for equivalent modern features that Rspamd does (_ARC is one of those I think, necessary for some users forwarding Gmail IIRC_).

---

> But yes, if the "traditional way" is not going to work anymore, maybe I have to find a way to speed up the migration to Rspamd.

I improved our Rspamd docs page with DMS v15 to assist with the migration, but if you choose to wait longer that's fine.

As the linked proposal notes, there are plans to better align the ENV related to these services for example. I also plan to make the DKIM setup easier for DMS v15.1, so I understand if you'd rather wait for such improvements/changes to settle before you switch.

---

If you follow @casperklein advice, you will find good reference/examples for such testing covered here: https://github.com/docker-mailserver/docker-mailserver/issues/4351

Basically you can shell into DMS and run the following:

```bash
# Send a spam mail (GTUBE test pattern):
swaks --server localhost --to john.doe@example.test --body 'XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X'

less /var/mail/example.test/john.doe/.Junk/new/*
```

I will note that I recall an observation that the above may behave differently vs sending from a separate container (_like Alpine with `apk add swaks`_) or host/client.

I have not had time to continue investigating that however but it's something most of our test suite won't flag as we often do mail tests within the same DMS container like shown above. Once I finally get that test suite overhauled, we'll have better regression testing in place.

**Comment by polarathene** [comment]
If you follow @casperklein advice, you will find good reference/examples for such testing covered here: https://github.com/docker-mailserver/docker-mailserver/issues/4351

Basically you can shell into DMS and run the following:

```bash
# Send a spam mail (GTUBE test pattern):
swaks --server localhost --to john.doe@example.test --body 'XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X'

less /var/mail/example.test/john.doe/.Junk/new/*
```

I will note that I recall an observation that the above may behave differently vs sending from a separate container (_like Alpine with `apk add swaks`_) or host/client.

I have not had time to continue investigating that however but it's something most of our test suite won't flag as we often do mail tests within the same DMS container like shown above. Once I finally get that test suite overhauled, we'll have better regression testing in place.

**Comment by ontheair81** [comment]
Thanks for the feedback! Migration to Rspamd is on my to-do list, but it will take some time before it can be implemented.

For the moment I just updated to v15.0.2, with the same results as in v15.0.1 (which was to be expected).

> You can send a test mail, containing this [string](https://en.wikipedia.org/wiki/GTUBE) `XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X`.
> 
> If this mail is not recognized as SPAM, something is wrong with your setup.

I tried that, and the mail is recognized as spam. It contains the corresponding flags in the header and it was moved to the junk folder automatically.
In contrast to "real" incoming spam, which is still missing the flags and is not moved to junk.

At the moment I keep running v15.0.2, moving spam manually to the junk folder to train the filter (training is triggered every 24 hours by a cronjob).
Maybe the newer SpamAssassin is not respecting the bayes files created by older versions for some reason. But that's just a shot in the dark.

**Comment by polarathene** [comment]
> In contrast to "real" incoming spam, which is still missing the flags and is not moved to junk.

When I was looking into https://github.com/docker-mailserver/docker-mailserver/issues/4351 I had noticed that SA (_since `4.0.0` introduced in DMS v14 IIRC_) there was a change for Spam headers only ever being applied to mail delivered into the Junk folder. Anything that SA didn't consider spam would no longer receive the headers.

You can confirm that's what you experience with DMS v15? Could you share an example of spam vs non-spam?

The DMS v14 GTUBE mail for example scores slightly lower than DMS v13.3:

```
Return-Path: <root@mail.example.test>
Delivered-To: john.doe@example.test
Received: from mail.example.test
        by mail.example.test with LMTP
        id RrbgErDQqWdwAwAAUi6ngw
        (envelope-from <root@mail.example.test>)
        for <john.doe@example.test>; Mon, 10 Feb 2025 10:10:56 +0000
Received: from localhost (localhost [127.0.0.1])
        by mail.example.test (Postfix) with ESMTP id 300911A3CB5
        for <john.doe@example.test>; Mon, 10 Feb 2025 10:10:56 +0000 (UTC)
X-Quarantine-ID: <NTL2rqm0XTRx>
X-Spam-Flag: YES
X-Spam-Score: 999
X-Spam-Level: ****************************************************************
X-Spam-Status: Yes, score=999 tagged_above=2 required=6.31
 tests=[ALL_TRUSTED=-1, GTUBE=1000] autolearn=no autolearn_force=no
Received: from mail.example.test (localhost [IPv6:::1])
        by mail.example.test (Postfix) with ESMTP id 5AA991A3C6E
        for <john.doe@example.test>; Mon, 10 Feb 2025 10:10:53 +0000 (UTC)
Date: Mon, 10 Feb 2025 10:10:53 +0000
To: john.doe@example.test
From: root@mail.example.test
Subject: test Mon, 10 Feb 2025 10:10:53 +0000
Message-Id: <20250210101053.000869@mail.example.test>

XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X
```

If you have an example spam mail with a message body (_and optionally subject header_) that is sufficient to trigger the spam score for you on DMS v15, you can try to replicate that via a mail client sending that mail message body to a minimal DMS instance?

---

## Reproduction guide

```bash
docker compose exec -it dms bash

# Send you spam mail:
swaks --server mail.example.test --to john.doe@example.test --body 'spam'
# Optionally create a file to paste the contents of the spam body message:
# nano /tmp/spam-msg
# swaks --server mail.example.test --to john.doe@example.test --body '@/tmp/spam-msg'

# If it arrived in junk:
less /var/mail/example.test/john.doe/.Junk/new/*

# If it arrived in the regular mailbox (no spam headers):
less /var/mail/example.test/john.doe/new/*
```

Minimal config example:

```yaml
services:
  dms:
    image: ghcr.io/docker-mailserver/docker-mailserver:15.0.0
    hostname: mail.example.test
    environment:
      ENABLE_AMAVIS: 1
      ENABLE_SPAMASSASSIN: 1
      # For running swaks command, use `connected-networks` if running swaks from another container:
      PERMIT_DOCKER: container
    configs:
      - source: dms-accounts
        target: /tmp/docker-mailserver/postfix-accounts.cf
    # Optionally expose a port if mail client is not via container
    # in the same docker network:
    ports:
      # Docker Engine v27.0.1 will allow omitting host port when it's the same value
      # Docker Compose v2 allows for no quotes as the value won't be mistaken for hexadecimal
      - 25

# A pre-provisioned account for testing:
# `setup email add john.doe@example.test secret`
# NOTE: You can modify the address and the password (secret) will still work.
configs:
  dms-accounts:
    content: |
      john.doe@example.test|{SHA512-CRYPT}$$6$$sbgFRCmQ.KWS5ryb$$EsWrlYosiadgdUOxCBHY0DQ3qFbeudDhNMqHs6jZt.8gmxUwiLVy738knqkHD4zj4amkb296HFqQ3yDq4UXt8.

# Optional - Name the network to easily join a container to it:
# docker run --rm -it --network spam-test alpine ash
# apk add swaks
# swaks --server mail.example.test --to john.doe@example.test --body 'spam'
networks:
  default:
    name: spam-test
```

If you can minimize this to a reproduction like above that I could verify on my end that would be helpful.
