### ISSUE TITLE
bug report: No SpamAssassin config file

### ISSUE THREAD

**Issue by ShoelessTom** [docker-mailserver/docker-mailserver#4435]
### 📝 Preliminary Checks

- [x] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I wanted to edit my custom SpamAssassin rules but when i went into /docker-data/dms/config, it only showed dovecot-quotas.cf  opendkim  postfix-accounts.cf.
I read in https://docker-mailserver.github.io/docker-mailserver/latest/faq/#how-can-i-manage-my-custom-spamassassin-rules that there is supposed to be a spamassassin-rules.cf file in there.

### 👟 Reproduction Steps

I did nothing special to trigger this bug, the file is just not there.

### 🐋 DMS Version

v15.0.2

### 💻 Operating System and Architecture

 Ubuntu 24.04.1 LTS x86_64

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail.364247.xyz
    domainname: 364247.xyz
    dns: 1.1.1.1 # This line is newly added and recommended
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt/:/tmp/ssl:ro # Add this line. It will be used later.
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### 📜 Relevant log output

```Text

```
