### ISSUE TITLE
bug report: Cannot add users in user-patches.sh as that is only executed after/when a user already exists

### ISSUE THREAD

**Issue by rklec** [docker-mailserver/docker-mailserver#4440]
### 📝 Preliminary Checks

- [x] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I have followed https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/override-defaults/user-patches/ respectively https://docker-mailserver.github.io/docker-mailserver/latest/faq/#how-to-adjust-settings-with-the-user-patchessh-script to mount a config file named `user-patches.sh` into the container that is executed at startup.

I use https://docker-mailserver.github.io/docker-mailserver/edge/config/account-management/provisioner/file/ and know/have the commands for setting up userrs

### 👟 Reproduction Steps

See below for the compose file where I mount the volume/config.

And I place a config script like this in `./config/user-patches.sh` like this to be executed at startup to create some test users:
```
#!/bin/sh
# Add email users at container startup

setup email add test@mail.localhost test
setup email add user@example.com password
setup email add admin@example.com strongpassword

echo "User setup complete."
```

The issue seems to be, as the logs show, that the script `user-patches.sh` is only executed **after** dovecot is started. However, dovecot prints this into the console and will exit the container/not continue running the script:
>  You need at least one mail account to start Dovecot

Aka we have a chicken and egg problem, I want to provide a provisioning script for adding what exactly it asks for, but it cannot continue unless I provide a user.
And I have not found a different way than doing so in a `docker-compose` file where other services then depend on the mailserver (that's why it has a healthcheck).

IMHO, this is in contrast to what is written here aka it claims there the script runs directly after config setup, but actually it is executed after dovecot has started already - where dovecot blocks processing?
https://github.com/docker-mailserver/docker-mailserver/blob/23bb1c8e50dad1462c645b8a9cf50aeee8bc2625/config-examples/user-patches.sh#L4-L5

In the log below, I executed a manual `setup email add` command in a new shell to make dovecot continue and only then *afterwards* it executed the script.

### 🐋 DMS Version

v15.0.0

### 💻 Operating System and Architecture

Windows/WSL (Ubuntu)

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    volumes:
      - mailserver-data:/var/mail/
      - mailserver-state:/var/mail-state/
      - mailserver-logs:/var/log/mail/
      - ./config:/tmp/docker-mailserver/ # <--
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    restart: unless-stopped
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 5
volumes:
  mailserver-data:
  mailserver-state:
  mailserver-logs:
```

### 📜 Relevant log output

```Text
2025-04-02 15:37:43+02:00 WARN  start-mailserver.sh: You need at least one mail account to start Dovecot (120s left for account creation before shutdown)
2025-04-02T13:37:53.314539070Z 2025-04-02 15:37:53+02:00 WARN  start-mailserver.sh: You need at least one mail account to start Dovecot (110s left for account creation before shutdown)
2025-04-02T13:38:03.321012054Z 2025-04-02 15:38:03+02:00 WARN  start-mailserver.sh: You need at least one mail account to start Dovecot (100s left for account creation before shutdown)
2025-04-02T13:38:13.327634618Z 2025-04-02 15:38:13+02:00 WARN  start-mailserver.sh: You need at least one mail account to start Dovecot (90s left for account creation before shutdown)
2025-04-02T13:38:23.333085493Z 2025-04-02 15:38:23+02:00 WARN  start-mailserver.sh: You need at least one mail account to start Dovecot (80s left for account creation before shutdown)
2025-04-02T13:38:33.337923209Z 2025-04-02 15:38:33+02:00 WARN  start-mailserver.sh: You need at least one mail account to start Dovecot (70s left for account creation before shutdown)
2025-04-02T13:38:43.624043947Z 2025-04-02 15:38:43+02:00 WARN  start-mailserver.sh: !! INSECURE !! SSL configured with plain text access - DO NOT USE FOR PRODUCTION DEPLOYMENT
2025-04-02T13:38:43.852635357Z (the log output from the script is here)
```

**Comment by polarathene** [comment]
The `setup email add ...` command simply creates `postfix-accounts.cf`, and during container startup before any services are run that file is checked to create the Dovecot UserDB accounts during Dovecot config stage.

After all this is done then `user-patches.sh` is run, and after that the services for DMS like Dovecot is started, but also `check-for-changes.sh` which will poll for changes to files like `postfix-accounts.cf` to trigger recreating the Dovecot UserDB, which is why that works for you in a running container instance.

---

So rather than a post-hook via `user-patches.sh` you would be better served either providing the `postfix-accounts.cf` file premade via whatever means you prefer (`volumes`, `configs`, `Dockerfile`), or even hijacking the containers entrypoint script.

https://github.com/docker-mailserver/docker-mailserver/blob/23bb1c8e50dad1462c645b8a9cf50aeee8bc2625/Dockerfile#L307-L308

Add a new entrypoiint script (_this will always run regardless of command_):

```bash
#!/usr/bin/dumb-init /bin/bash

# Add email users at container startup
setup email add test@mail.localhost test
setup email add user@example.com password
setup email add admin@example.com strongpassword

echo "User setup complete."

# Start DMS (runs CMD):
exec "${@}"
```

In your `compose.yaml` then change the entrypoint:

```yaml
services:
  dms:
    entrypoint: /path/to/custom/entrypoint.sh
```

Alternatively override the default `CMD` instead and leave the entrypoint as-is:

```bash
#!/bin/bash

# Add email users at container startup
setup email add test@mail.localhost test
setup email add user@example.com password
setup email add admin@example.com strongpassword

echo "User setup complete."

# Start DMS:
exec supervisord -c '/etc/supervisor/supervisord.conf'
```

Likewise update `compose.yaml`:

```yaml
services:
  dms:
    command: /path/to/custom/command.sh
```

**NOTE:** Make sure it's executable (`chmod +x` or compose setting `mode: 0500`).

---

Personally my preferred way is static user accounts via Docker Compose `configs`:

https://github.com/docker-mailserver/docker-mailserver/blob/23bb1c8e50dad1462c645b8a9cf50aeee8bc2625/demo-setups/relay-compose.yaml#L22-L27

https://github.com/docker-mailserver/docker-mailserver/blob/23bb1c8e50dad1462c645b8a9cf50aeee8bc2625/demo-setups/relay-compose.yaml#L76-L79

https://github.com/docker-mailserver/docker-mailserver/blob/23bb1c8e50dad1462c645b8a9cf50aeee8bc2625/demo-setups/relay-compose.yaml#L87-L96

You can copy/paste the account line and change the mail address to whatever you like (password is `secret`). So putting it all together..

```yaml
services:
  dms:
    configs:
      - source: dms-accounts
        target: /tmp/docker-mailserver/postfix-accounts.cf

# Using the Docker Compose `configs.content` feature instead of volume mounting separate files.
# NOTE: This feature requires Docker Compose v2.23.1 (Nov 2023) or newer:
# https://github.com/compose-spec/compose-spec/pull/446
configs:
  # DMS expects an account to be configured to run, this example provides accounts already created.
  # Login credentials:
  # user: "test@mail.localhost" password: "secret"
  # user: "user@example.com" password: "secret"
  # user: "admin@example.com" password: "secret"
  dms-accounts:
    # NOTE: `$` needed to be repeated to escape it,
    # which opts out of the `compose.yaml` variable interpolation feature.
    content: |
      test@mail.localhost|{SHA512-CRYPT}$$6$$sbgFRCmQ.KWS5ryb$$EsWrlYosiadgdUOxCBHY0DQ3qFbeudDhNMqHs6jZt.8gmxUwiLVy738knqkHD4zj4amkb296HFqQ3yDq4UXt8.
      user@example.com|{SHA512-CRYPT}$$6$$sbgFRCmQ.KWS5ryb$$EsWrlYosiadgdUOxCBHY0DQ3qFbeudDhNMqHs6jZt.8gmxUwiLVy738knqkHD4zj4amkb296HFqQ3yDq4UXt8.
      admin@example.com|{SHA512-CRYPT}$$6$$sbgFRCmQ.KWS5ryb$$EsWrlYosiadgdUOxCBHY0DQ3qFbeudDhNMqHs6jZt.8gmxUwiLVy738knqkHD4zj4amkb296HFqQ3yDq4UXt8.
```

If you want the passwords to be different just run the `setup email add` command in a DMS container and then run `cat /tmp/docker-mailserver/postfix-accounts.cf`, now copy the `SHA512-CRYPT...` hash and make sure any `$` is replaced to `$$` like explained above and you'll have different passwords 👍
