### ISSUE TITLE
bug report: docker compose up error httpReadSeeker

### ISSUE THREAD

**Issue by thuyydt** [docker-mailserver/docker-mailserver#4444]
### 📝 Preliminary Checks

- [x] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I got issue when run docker compose up:
`failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:1a44789376cdaa2*****`
What's wrong with me?

### 👟 Reproduction Steps

docker compose up -d 

### 🐋 DMS Version

v15.0.2

### 💻 Operating System and Architecture

Mac OS 15.3.2

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.example.com
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### 📜 Relevant log output

```Text
➜  docker-mailserver docker compose up -d 
[+] Running 0/1
 ⠴ mailserver Pulling                                                                                                                                            62.6s 
failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:1a44789376cdaa2b427884676bd77dc07950c7f036c09c911b2ce1151a642ad2?se=2025-04-09T08%3A20%3A00Z&sig=kZvQbg4sIOhVHsQ6NR512vptAHHR28z3VrBH6FYqIL4%3D&sp=r&spr=https&sr=b&sv=2019-12-12": context deadline exceeded
```
