### ISSUE TITLE
bug report: setting attachment sizes fails.

### ISSUE THREAD

**Issue by g40** [docker-mailserver/docker-mailserver#4457]
### 📝 Preliminary Checks

- [x] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

Following https://github.com/docker-mailserver/docker-mailserver/issues/4280 

In `compose.yaml`
```
    environment:
      - ENABLE_POP3=1
      - POSTFIX_MESSAGE_SIZE_LIMIT: 102400000
  ```
```
docker compose up -d --build
services.mailserver.environment.[1]: unexpected type map[string]interface {}
```

### 👟 Reproduction Steps

Add postfix message size to compose.yaml, then attempt to run DMS.

### 🐋 DMS Version

Not known

### 💻 Operating System and Architecture

Ubuntu 24.04.2 LTS

### ⚙️ Container configuration files

```yml
moi@s2:~/dms$ cat compose.yaml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: xx.yyy.net
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      # - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
      # - "110:110"
      - "995:995"  # POP3
    environment:
      - ENABLE_POP3=1
      # - POSTFIX_MESSAGE_SIZE_LIMIT: 102400000
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro/
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
```

### 📜 Relevant log output

```Text

```
