### ISSUE TITLE
bug report: `warning: hostname does not resolve to address ` on custom network

### ISSUE THREAD

**Issue by stefanpejcic** [docker-mailserver/docker-mailserver#4469]
### 📝 Preliminary Checks

- [x] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I keep seeing this false positive:
```
warning: hostname XXXX.XXXXXX.rs does not resolve to address  YYYYYYYYYYYY
```

when using in docker compose [standard ports](https://github.com/docker-mailserver/docker-mailserver/blob/fc51996e4310c1ccad5966f3880944434a987aff/compose.yaml#L10) and custom network:

```
network:
  - host
```

but **not** seeing it when running on host:
```
network_mode: host
```

I tried searching the code to find the message and determine what is used for checking, but could't find the source. dig probably, so port `53` ?

If someone could point me in the right direction to the file with that check, i'm happy to contribute 🙌 

### 👟 Reproduction Steps

run [this](https://github.com/docker-mailserver/docker-mailserver/blob/master/compose.yaml#L10) example with custom network

### 🐋 DMS Version

v15.0.2

### 💻 Operating System and Architecture

ubuntu24, x84

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: openadmin_mailserver
    hostname: local.host
    env_file: mailserver.env
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
      - "110:110"  # POP3
      - "995:995"  # POP3 (with TLS)
      - "11334:11334" # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/rspamd/#web-interface
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /home/:/home/
    restart: always
    stop_grace_period: 1m
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    networks:
      - network
    cap_add:
      - NET_ADMIN
```

### 📜 Relevant log output

```Text
warning: hostname XXXX.XXXXXX.rs does not resolve to address  YYYYYYYYYYYY
```
