### ISSUE TITLE
bug report: postfix/master[10341]: fatal: unable to determine open file limit

### ISSUE THREAD

**Issue by mfreeman451** [docker-mailserver/docker-mailserver#4507]
### 📝 Preliminary Checks

- [x] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

I'm trying to run this in a new cluster and having issues, I've tried to install from manifest and helm, running into this same issue.

I've modified my helm values.yaml to work around this, attempting to add what I thought might a missing capability, and modifying the seccomp profile, nothing is helping:

If I shell in, `ulimit -a` works fine, can also set new ulimits as root.

### 🐋 DMS Version

sha256:cc9f15c4d545c9e6fa81acf8b6b4e337ebc545b6d293d5f187d4a62f9303c492

### 💻 Operating System and Architecture

k3s kubernetes / ubuntu 24.xx hosts

### ⚙️ Container configuration files

```yml
# Image configuration
image:
  name: "ghcr.io/docker-mailserver/docker-mailserver"
  tag: "latest"
  pullPolicy: "IfNotPresent"

# Certificate configuration
certificate: "mail-tls-certificate-rsa"

podSecurityContext:
  seccompProfile:
    type: Unconfined

# Deployment configuration
deployment:
  replicas: 1
  strategy:
    type: "Recreate"

  # Security context for extra capabilities
  containerSecurityContext:
    capabilities:
      add:
        - NET_ADMIN
        - NET_BIND_SERVICE
        - SYS_CHROOT
        - CHOWN
        - DAC_OVERRIDE
        - FOWNER
        - SETGID
        - SETUID
        - SYS_RESOURCE

  env:
    # General
    OVERRIDE_HOSTNAME: "mail.carverauto.dev"
    POSTMASTER_ADDRESS: "postmaster@carverauto.dev"
    POSTSCREEN_ACTION: "ignore"
    ONE_DIR: 1
    ENABLE_CLAMAV: 0
    ENABLE_SPAMASSASSIN: 1
    SPAMASSASSIN_SPAM_TO_INBOX: 1
    ENABLE_FAIL2BAN: 1

    # SSL Configuration
    #SSL_TYPE: "manual"
    #SSL_CERT_PATH: "/etc/letsencrypt/live/mail.carverauto.dev/tls.crt"
    #SSL_KEY_PATH: "/etc/letsencrypt/live/mail.carverauto.dev/tls.key"

    # Network settings
    NETWORK_INTERFACE: "eth0"
    POSTFIX_INET_PROTOCOLS: "all"
    PERMIT_DOCKER: "none"
    POSTFIX_MYNETWORKS: "10.0.0.0/8, ipv6removed/64, ipv6scrubbed/64, scrubbed/64"
    POSTSCREEN_UPSTREAM_PROXY_PROTOCOL: "haproxy"
    POSTFIX_SUBMISSION_SMTPD_UPSTREAM_PROXY_PROTOCOL: "haproxy"
    POSTFIX_SUBMISSIONS_SMTPD_UPSTREAM_PROXY_PROTOCOL: "haproxy"
    ENABLE_POSTFIX_VIRTUAL_TRANSPORT: 1
    DOVECOT_INET_PROTOCOLS: "all"

    # Debug
    LOG_LEVEL: "trace"

# Service configuration
service:
  type: "LoadBalancer"
  loadBalancer:
    #publicIp: "XXXXipv6removed"
    allowedIPs:
      - "0.0.0.0/0"

  # Put all other service configs under annotations since they're not natively supported
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "mail.carverauto.dev"
    metallb.universe.tf/address-pool: "k3s-pool"
    kubernetes.io/ip-family-policy: "PreferDualStack"
    service.kubernetes.io/external-traffic-policy: "Local"

  # Define ports through the chart's proxy protocol settings instead
  proxyProtocol:
    enabled: true
    trustedNetworks: "10.0.0.0/8 192.168.0.0/16 ipv6addressremoved/40"

  # Add selector to match your working config
  selector:
    app: mailserver

# Persistence configuration
persistence:
  mail-data:
    enabled: true
    size: 10Gi
    storageClass: "local-path"
    accessModes:
      - ReadWriteOnce

  mail-state:
    enabled: true
    size: 5Gi
    storageClass: "local-path"
    accessModes:
      - ReadWriteOnce

  mail-config:
    enabled: true
    size: 1Gi
    storageClass: "local-path"
    accessModes:
      - ReadWriteOnce

# Enable proxy protocol support
proxyProtocol:
  enabled: true
  trustedNetworks: "10.0.0.0/8 192.168.0.0/16 XXXX/31 XXX/31 XXXX/24"
```

### 📜 Relevant log output

```Text
2025-06-15T02:35:21.257490+00:00 docker-mailserver-64965b86d-svwww postfix/postfix-script[10340]: starting the Postfix mail system
2025-06-15T02:35:21.260423+00:00 docker-mailserver-64965b86d-svwww postfix/master[10341]: fatal: unable to determine open file limit
```
