### ISSUE TITLE
autocreation of ldap user's mailboxes fails

### ISSUE THREAD

**Issue by HappyBasher** [docker-mailserver/docker-mailserver#475]
Hi!

Autocreation of ldap user's mailboxes fails with permission denied error:

/var/log/mail/mail.log:
```
Jan 13 13:34:34 mail dovecot: imap-login: Login: user=<zell>, method=PLAIN, rip=10.16.1.253, lip=172.18.0.2, mpid=969, TLS, session=<n43+5PlFOAAKEAH9>
Jan 13 13:34:34 mail dovecot: imap(zell): Error: user zell: Initialization failed: Namespace '': mkdir(/var/mail//zell) failed: Permission denied (euid=10034(<unknown>) egid=10000(<unknown>) missing +w perm: /var/mail/, we're not in group 5000(docker), dir owned by 5000:5000 mode=0775)
Jan 13 13:34:34 mail dovecot: imap(zell): Error: Invalid user settings. Refer to server log for more information.
```

docker-compose.yml:
```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:2.1
    hostname: mail
    domainname: linuxmuster.lokal
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    - ./config/dovecot-ldap.conf.ext:/etc/dovecot/dovecot-ldap.conf.ext
    - ./config/ldap.conf:/etc/ldap/ldap.conf
    environment:
    - ENABLE_SPAMASSASSIN=0
    - ENABLE_CLAMAV=0
    - ENABLE_FAIL2BAN=0
    - ENABLE_LDAP=1
    - LDAP_SERVER_HOST=10.16.1.1
    - LDAP_SEARCH_BASE=dc=linuxmuster,dc=lokal
    - LDAP_BIND_DN=cn=admin,dc=linuxmuster,dc=lokal
    - LDAP_BIND_PW=bind_password
    - SSL_TYPE=self-signed
    - ONE_DIR=1
    - DMS_DEBUG=1
    cap_add:
    - NET_ADMIN

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```

config/dovecot-ldap.conf.ext:
```

base = dc=linuxmuster,dc=lokal
default_pass_scheme = SSHA
uris = ldaps://10.16.1.1
dn = cn=admin,dc=linuxmuster,dc=lokal
dnpass = bind_password
pass_attrs = uid=user, userPassword=password
pass_filter = (&(objectClass=posixAccount)(uid=%u))
ldap_version = 3
```

config/ldap.conf:
```
#
# LDAP Defaults
#

# See ldap.conf(5) for details
# This file should be world readable but not world writable.

BASE	dc=linuxmuster,dc=local
URI	ldaps://10.16.1.1

#SIZELIMIT	12
#TIMELIMIT	15
DEREF		never

# TLS certificates (needed for GnuTLS)
TLS_CACERT	/etc/ssl/certs/ca-certificates.crt

TLS_REQCERT never
```

Any hints?

Regards, Thomas
